### ISSUE TITLE
Python Multi-Container Apps, Extending & Composite requirements.txt Files

### ISSUE THREAD

**Issue by KitHaywood** [docker/compose#10009]
### Description

Good Afternoon,

Hoping this is the correct place to ask the following, and that I have not missed the answer to this in the dox. I am building a multi-image/multi-container application using docker compose - all the containers use Python. ~ 80% of the dependencies for each container are homogenous across the project space. I build my own images from Dockerfiles in each subdir.

The current setup is the following.  (parenthesised terms are placeholder for later explanation)

```
workingdir
│   utils.py
│   modelparams.yml
|   (base-python-container-Dockerfile ?)
│   (template-requirements.txt ?)  
|
└─── server
│   │--- serve.py
│   │--- Dockerfile
│   │--- requirements.txt
│ 
└─── multiplexer
│   │--- distribute.py
│   │--- Dockerfile
│   │--- requirements.txt
│   
└─── model-client-1
|   │--- runmodel.py
│   │--- Dockerfile
│   │--- requirements.txt
|
└─── model-client-2
    │--- runmodel.py
    │--- Dockerfile
    │--- requirements.txt
```
An example Dockerfile looks like:
```docker
# syntax=docker/dockerfile:1
FROM python:3.9
WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python3","-u","server.py"]
```
The remaining ~ 20% of dependencies are specific to the function of the container. My questions is this - what is the most effective way to capture my 80% dependencies in a "template" image fashion? I have played around with docker-compose **extends** but am struggling. I would really like to do something along the line of the following in a common-services.yml

```
services:
   base-python-container:
      image: base-python-container:latest
      volumes:
          - ./template-requirements.txt:/workingdir/template-requirements.txt
          - ./utils.py:/workingdir/utils.ps
          - ./modelparams.yaml:/workingdir/modelparams.yaml
      env_file:
          - credentials.env
    command:
     - pip3 install -r requirements.txt
       
```
And this in docker-compose.yml
```
services:
    server:
        image: server:latest
        extends:
            file: common-services.yml
            service: base-python-container
.....
```
Is this even possible? Is this even the correct approach? I am running into the following error, which to me seems to be about contexts and build-time/run-time and other scary things I don't need to know in depth
```
ERROR: for multiplexer  Cannot start service multiplexer: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python3 server.py": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.
```
Should i un-nest the whole project? What am i missing here? Do i need a top-level Dockerfile as shown? 

Thank you for your help in advance, please excuse if the answer is jaw-droppingly obvious!

K

**Comment by ndeloof** [comment]
We recently introduced support for additional context, which you can use to access files from another path in your project:

```yaml
services:
    server:
      build: 
        context: server
        additional_contexts:
          shared-files: .
```

you can then declare in your Dockerfile:
```
COPY --from=shared-files template-requirements.txt /workingdir/template-requirements.txt
```

read more on https://docs.docker.com/build/bake/build-contexts/
