### ISSUE TITLE
[BUG] Docker compose >=2.10 stuck on stopping containers started with --attach-dependencies option

### ISSUE THREAD

**Issue by sidz** [docker/compose#10021]
### Description

This issue was fixed in 2.6.0 and is not reproducible till 2.9.0 (includes 2.9.0) But since 2.10 was broken again.
Here my old issue: https://github.com/docker/compose/issues/9494

I assume (but not sure) that this https://github.com/docker/compose/pull/9488 PR fixes old issue. But as I can see fix is still in v2 branch.

### Steps To Reproduce

1. Define 3 services in the `docker-compose.yaml` with depends_on key. (example below)
2. Up only php container with `--attach-dependencies` eg. `docker compose up php --attach-dependencies`
3. Click on Ctrl + C or run docker compose kill in the separate tab
4. Docker stops only php container and freezes on this step and don't stop others.

```
version: "3.4"

services:
    php:
        image: php:8.1.12-fpm-alpine3.16
        depends_on:
            - mailhog

    memcache:
        image: memcached:1.6-alpine
        restart: on-failure

    mailhog:
        image: mailhog/mailhog
        ports:
            - "127.0.0.1:8025:8025"
```

### Compose Version

```Text
Docker Compose version v2.13.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.13.0)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 50
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-53-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.41GiB
 Name: sid
 ID: ULXA:3XFE:FTGL:CKAH:WTPB:5HTB:DQS6:IKL6:IBG7:YDWW:LYTZ:EAXA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
