### ISSUE TITLE
[BUG] cli multifile "config" generates bad extra_hosts entries

### ISSUE THREAD

**Issue by drewboswell** [docker/compose#10038]
### Description

if you merge 2 or more docker_compose files then the extra_hosts is not output in an array as per spec. It creates a corrupted manifest

### Steps To Reproduce

1. create 2 docker-compose files
```yaml
# compose file 1
services:
  frontend:
    extra_hosts:
      - "dev.local:192.168.2.2"
      - "npm.dev.local:192.168.2.3"
    build:
      context: build/docker
      dockerfile: frontendTest/Dockerfile
      args:
        test: 2
```
```yaml
# compose file 2
services:
  frontend:
    build:
      args:
        test: 1
```
3. Run: `docker-compose -f docker-compose.1.yml config`
```yaml
services:
  frontend:
    build:
      args:
        test: '1'
      context: .
      dockerfile: frontendTest/Dockerfile
    extra_hosts:
      dev.local: 192.168.2.2
      npm.dev.local: 192.168.2.3
version: '3.9'
```
# observed result
```yaml
extra_hosts:
      dev.local: 192.168.2.2
      npm.dev.local: 192.168.2.3
```
# expected result
```yaml
extra_hosts:
    - dev.local:192.168.2.2
    - npm.dev.local:192.168.2.3
```

### Compose Version

```Text
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-53-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.22GiB
 Name: pclnx-gl089
 ID: 7DAP:IMVW:LBYV:5BRZ:QHJP:7SP3:OLVB:S2FG:REDA:UQRR:MBGX:LFOS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.31.0.0/16, Size: 24
```
