### ISSUE TITLE
[BUG] docker compose start service, trying to start dependency services

### ISSUE THREAD

**Issue by hahattan** [docker/compose#10061]
### Description

`docker compose start <service>` will try to start dependency services even if I created them with `--no-deps` and result in error:
```
no such service: <dependency_service>
```

However, if I run just run `docker compose start` without specifying services, there's no error.

### Steps To Reproduce

example `docker-compose-example.yml`:
```yml
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
volumes:
  db_data:
  wp_data:
```

1. docker compose -p test -f docker-compose-example.yml up --no-deps -d wordpress
2. docker compose -p test -f docker-compose-example.yml stop
3. docker compose -p test -f docker-compose-example.yml start wordpress
```shell
vagrant@second:~$ docker compose -p test -f docker-compose-example.yml up -d --no-deps wordpress
[+] Running 4/4
 ⠿ Network test_default        Created                                                                                                    0.0s
 ⠿ Volume "test_db_data"       Created                                                                                                    0.0s
 ⠿ Volume "test_wp_data"       Created                                                                                                    0.0s
 ⠿ Container test-wordpress-1  Started                                                                                                    0.7s
vagrant@second:~$ docker compose -p test -f docker-compose-example.yml stop
[+] Running 1/1
 ⠿ Container test-wordpress-1  Stopped                                                                                                    1.4s
vagrant@second:~$ docker compose -p test -f docker-compose-example.yml start wordpress
no such service: db

```

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a05d175400b1145e5e6a735a6710579d181e7fb0
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-58-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 763.3MiB
 Name: second
 ID: VF3F:TJ6M:A2P3:HNGJ:5MHF:DJIC:U7CS:UCCX:RRJU:JTDF:GC4Z:C4GC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: botckris
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Anything else?

Might be irrelevant but I noticed the error log is slightly different if running `docker compose` w/o `-p` option:
```shell
vagrant@second:~$ docker compose -f docker-compose-example.yml up -d --no-deps wordpress
[+] Running 4/4
 ⠿ Network vagrant_default        Created                                                                                                 0.0s
 ⠿ Volume "vagrant_wp_data"       Created                                                                                                 0.0s
 ⠿ Volume "vagrant_db_data"       Created                                                                                                 0.0s
 ⠿ Container vagrant-wordpress-1  Started                                                                                                 0.7s
vagrant@second:~$ docker compose -f docker-compose-example.yml stop
[+] Running 1/1
 ⠿ Container vagrant-wordpress-1  Stopped                                                                                                 1.3s
vagrant@second:~$ docker compose -f docker-compose-example.yml start wordpress
service "db" has no container to start

```
