### ISSUE TITLE
Allow overriding the default naming scheme for containers and other entities

### ISSUE THREAD

**Issue by EuleMitKeule** [docker/compose#10069]
### Description

I would love to have the option to declare a custom default naming scheme for every service in my `docker-compose.yml` file.
Since I don't like having the project/directory name prefix contained in my services, right now I have to specify the `container_name` element for every service I create like this:
```yaml
services:
  foo:
    image: ubuntu
    container_name: foo
  bar:
    image: nginx
    container_name: bar
```
This could be accomplished by allowing the user to specify a top level element like this or something similar to it:
```yaml
naming_scheme: no-prefix

services:
  foo:
    image: ubuntu
  bar:
    image: nginx
```
