### ISSUE TITLE
Secrets from shell commands

### ISSUE THREAD

**Issue by quasis** [docker/compose#10081]
### Description

It is extremelly convinient to generate secrets on the fly in some cases. How about adding an option to generate the secret using a series of shell commands? For example:

```
secrets:
    password:
         bash: cat /etc/shadow | grep 'root:' | cut -d: -f2
    private_key:
         sh: openssl ecparam -noout -genkey -name prime256v1
```

**Comment by ndeloof** [comment]
Such discussion should take place on github.com/compose-spec

One major drawback doing so is that this assumes user has `openssl` installed on his machine, and you on't control the version he's using. A better approach then is to rely on init containers

**Comment by ndeloof** [comment]
Illustration example:
```yaml
services:
  init:
    image: alpine/openssl
    command: ecparam -noout -genkey -name prime256v1 -out /var/run/secrets/private_key
    volumes:
      - /var/run/secrets/
  myapp:
    image: alpine
    command: cat  /var/run/secrets/private_key
    volumes_from:
      - init
    depends_on:
      init:
        condition: service_completed_successfully 
```

This is quite verbose, we _really_ need a better syntax to define init container. But at least the building blocks exists
