### ISSUE TITLE
Update deprecated feature warning with steps to correct behavior

### ISSUE THREAD

**Issue by kmanwar89** [docker/compose#10093]
### Description

In docker compose, the _external.name_ service configuration has been deprecated. If a compose file contains the legacy syntax, i.e.:

```
networks:
  default:
    external:
      name: <network name>
```
a warning message is seen advising the user the feature is deprecated, but no guidance is provided on what the new syntax should be. A user may attempt to simply delete the `external` line from the compose file, but this does not work for all services. An example of a service that breaks is authentik.

The original warning text is: `WARN[0000] network default: network.external.name is deprecated in favor of network.name `. I propose the warning message text be updated to advise the user to include `external: true` in the network stanza to avoid compatibility issues. 

The proposed warning message might say: `WARN[0000] network default: network.external.name is deprecated. If an external network needs to be defined, use "external: true" in the network stanza`

**Comment by hahattan** [comment]
Hi, I came across this issue today and I followed the warning message to update my network:
```yaml
networks:
  external_network:
    external: true
```

It did eliminate the warning message but I noticed it also created the `<project>_default` network additionally.
I tried adding `default` back:
```yaml
networks:
  default:
    external_network:
      external: true
```
But get the following error:
```
networks.default Additional property edgexpert_edgex-network is not allowed
docker: exit status 15
```

@ndeloof can you show me how to configure this correctly? Thanks

**Comment by ndeloof** [comment]
```yml
networks:
  default:
    name: external_network:
    external: true
```

see https://github.com/compose-spec/compose-spec/blob/master/06-networks.md
