### ISSUE TITLE
[BUG] Not all attached containers are stopped on CTRL + C

### ISSUE THREAD

**Issue by sidz** [docker/compose#10120]
### Description

Compose doesn't stop attached containers on CTRL + C.

### Steps To Reproduce

1. Define 3 services in the docker-compose.yaml with `depends_on` key. (example below)
2. Up only php container with `--attach-dependencies` eg. `docker compose up php --attach-dependencies` (**not in daemon mode**)
3. Click on Ctrl + C
4. Docker stops only php container but others are still in the running state

```
version: "3.4"

services:
    php:
        image: php:8.1.12-fpm-alpine3.16
        depends_on:
            - mailhog

    memcache:
        image: memcached:1.6-alpine
        restart: on-failure

    mailhog:
        image: mailhog/mailhog
        ports:
            - "127.0.0.1:8025:8025"
```

### Compose Version

```Text
Docker Compose version v2.14.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.14.2)

Server:
 Containers: 19
  Running: 0
  Paused: 0
  Stopped: 19
 Images: 38
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.41GiB
 Name: sid
 ID: 6F76:W6AV:4SUL:T4LA:ESVC:WGOU:WF4D:6TCP:O2SY:HF55:BH5J:II2H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
