### ISSUE TITLE
[BUG] <port range>

### ISSUE THREAD

**Issue by nkartem** [docker/compose#10131]
### Description

I have a problem when running a container through docker compose. The docker compose file describes the range of ports 10000-20000 / UDP with this configuration, the container does not start and the server freezes.  If you reduce the port range by 10000-11500 then the container start time = 113.6s

docker-compose.yaml

```
version: '3.1'

services:

  asterisk:
    image: nkartem/asterisk
    container_name: asterisk
    restart: always
    ports:
      - 5022:5022/udp
#      - 10000-20000:10000-20000/udp
      - 10000-11500:10000-11500/udp
      - 8088:8088/tcp
    command: systemctl start asterisk
```

### Compose Version

```Text
Docker Compose version v2.14.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-425.3.1.el8.x86_64
 Operating System: Red Hat Enterprise Linux 8.7 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.754GiB
 Name: asterisk
 ID: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxxx:xxxxx:xxxx:xxxx:xxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
