### ISSUE TITLE
[BUG] container for service "db" has no healthcheck configured

### ISSUE THREAD

**Issue by harshraj22** [docker/compose#10155]
### Description

service has `healthcheck` implemented, but still other service is not able to find.

```yml
version: '3.1'

services:
  db:
    container_name: db-mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: DB
      # MYSQL_USER: root
    volumes:
      - /Users/harshraj22/Desktop/lab/pro/smallProjects/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:  ["mysql", "$$MYSQL_DATABASE", "-uroot", "-p$$MYSQL_ROOT_PASSWORD", "-e", "'SELECT 1;'"] # ["mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pmypassword"] #;
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 10s

  connect:
    build: './'
    depends_on:
      db:
        condition: service_healthy
        # condition: service_started

```

``` Dockerfile
FROM python:3.8-alpine

COPY connect.py connect.py
RUN pip3 install PyMySQL

CMD [ "python3", "connect.py" ]
```

```python
# connect.py


# specify database configurations
config = {
    'host': 'db-mysql',
    'port': 3306,
    'user': 'root',
    'password': 'mypassword',
    'database': 'DB'
}
db_user = config.get('user')
db_pwd = config.get('password')
db_host = config.get('host')
db_port = config.get('port')
db_name = config.get('database')
# specify connection string


import pymysql.cursors
# https://github.com/PyMySQL/PyMySQL/

# Connect to the database
connection = pymysql.connect(host=db_host,
                             user=db_user,
                             password=db_pwd,
                             database=db_name,
                             cursorclass=pymysql.cursors.DictCursor)

with connection:
    # with connection.cursor() as cursor:
    #     # Create a new record
    #     sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
    #     cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # # connection is not autocommit by default. So you must commit to save
    # # your changes.
    # connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT * FROM Occurrences;"
        cursor.execute(sql)
        result = cursor.fetchone()
        result = cursor.fetchall()
        print(result)
```

```sql
DROP DATABASE IF EXISTS `DB`;
CREATE DATABASE `DB`;
USE `DB`;

DROP TABLE IF EXISTS `Occurrences`;
CREATE TABLE `Occurrences` (
  `IdOccurrence` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Min_probability` double NOT NULL,
  PRIMARY KEY (`IdOccurrence`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;
INSERT INTO `Occurrences` VALUES (1,'Frequent',20),(2,'Probable',10),(5,'Possible',1),(6,'Rare',0.1),(7,'Remote',0);
```

### Steps To Reproduce

Add these files to a directory. run `docker-compose up --build` in the directory.

### Compose Version

```Text
Docker Compose version v2.13.0
Docker Compose version v2.13.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 15
  Running: 1
  Paused: 0
  Stopped: 14
 Images: 26
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: FINB:NZ7U:X53P:CY45:ZNJZ:XSVU:R7NX:SS3O:N2SB:OVDY:7ZXM:LAH5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Output:
```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/0
 ⠿ Container db-mysql       Created                          0.0s
 ⠿ Container sql-connect-1  Rec...                           0.1s
Attaching to db-mysql, sql-connect-1
db-mysql       | 2023-01-09 18:35:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
db-mysql       | 2023-01-09 18:35:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-mysql       | 2023-01-09 18:35:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
db-mysql       | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
container for service "db" has no healthcheck configured
```
