### ISSUE TITLE
On arm64  - exec /usr/local/bin/docker-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by LiliDeng** [docker/compose#10185]
I use below docker-compose.yml file. use docker-compose version v2.0.1 (also try with the latest version), when run command `docker-compose up`, encounter exec /usr/local/bin/docker-entrypoint.sh: exec format error issue, any insights or guide for further investigation? Thanks!

```
sudo docker-compose up
[+] Running 2/2
 ⠿ Container 20230120-062611-854-db-1  Created                                                                                                                                                           0.1s
 ⠿ Container wordpress_ex              Created                                                                                                                                                           0.1s
Attaching to 20230120-062611-854-db-1, wordpress_ex
20230120-062611-854-db-1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
20230120-062611-854-db-1 exited with code 0
wordpress_ex              | exec /usr/local/bin/docker-entrypoint.sh: exec format error
20230120-062611-854-db-1 exited with code 1
wordpress_ex exited with code 1
```

```
cat docker-compose.yml
version: '3.3'
services:
   db:
     platform: linux/amd64
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     platform: linux/amd64
     image: wordpress:latest
     container_name: wordpress_ex
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
```

**Comment by glours** [comment]
Hello @LiliDeng 
Can you provide us the output of `docker compose version` and `docker info` please?

**Comment by LiliDeng** [comment]
Hi @glours, please check below.

```
docker compose version
Docker Compose version v2.0.1
root@lisa--759-e0-n0:/home/lisatest/lisa_working/20230120/20230120-031919-759# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.0.1)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 9
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1098-azure
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 7.752GiB
 Name: lisa--759-e0-n0
 ID: 2XFD:EOJP:46CD:4CYJ:5ZDM:NYDN:X6A7:J42R:LINT:LPNV:JUCK:IAWA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by glours** [comment]
I'm not able to reproduce your issue, so few questions for you:
 * Did you test with the [Mysql 8](https://hub.docker.com/layers/library/mysql/8.0/images/sha256-56b3754c827c12d583689a3c619b49653d0b22cc19e341511544685ffcd6037d?context=explore) as this version finally support arm architecture?
 * Do you have data you wanted to keep in your volume or is it possible for you to run a `docker compose down --volumes` to remove the whole volume content and be sure the mysql container will completely re-setup the database?
 * And the last one, why aren't you using the latest version of Compose v2 but a version which was released in Septembre 2021?

**Comment by mactijn** [comment]
Isn't this simply because there's `platform: linux/amd64` for both services while trying to use this on `aarch64` ?

**Comment by ZachThomasAU** [comment]
> Isn't this simply because there's `platform: linux/amd64` for both services while trying to use this on `aarch64` ?

Why would that be an issue? I regularly compose linux/arm64 builds on an x86_64 architecture without any problems.

**Comment by mactijn** [comment]
> Why would that be an issue? I regularly compose linux/arm64 builds on an x86_64 architecture without any problems.

I'm not sure how known you are with multi-arch setups, so my apologies if this all seems obvious.

`exec format error` is an error you get when you try to run a binary for architecture X on a machine with architecture Y, and the machine is not set up to translate CPU instructions from X to Y.

My guess is that your x86_64 machine is set up with qemu and binfmt support to run aarch64 binaries, and your aarch64 machine is not.

See https://docs.docker.com/build/building/multi-platform/ for more info on this.

**Comment by LiliDeng** [comment]
Thanks all. Use `mysql/mysql-server:8.0.23`  work well, close this issue.

```
version: '3.3'
services:
   db:
     image: mysql/mysql-server:8.0.23
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress_ex
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
```
