### ISSUE TITLE
[BUG] Healthcheck test is lost when start_period is changed in override file

### ISSUE THREAD

**Issue by tobiasge** [docker/compose#10188]
### Description

Given the files below I get the following output from `docker compose config`:
```yaml
name: healthcheck-test
services:
  my_service:
    healthcheck:
      timeout: 3s
      interval: 15s
      start_period: 1m30s
    image: some/image:latest
    networks:
      default: null
networks:
  default:
    name: healthcheck-test_default
```

I would expect the `healthcheck` section to contain the `test` entry:
```yaml
      test:
      - CMD-SHELL
      - exit 0
```

### Steps To Reproduce

Create the following files:
docker-compose.yml:
```yaml
version: '3.8'
services:
  my_service:
    image: some/image:latest
    healthcheck:
      test: "exit 0"
      start_period: 60s
      timeout: 3s
      interval: 15s
```

docker-compose.override.yml:
```yaml
version: '3.8'
services:
  my_service:
    healthcheck:
      start_period: 90s
```

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.10.0-docker)
  compose: Docker Compose (Docker Inc., v2.15.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 13
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-20-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.771GiB
 Name: debian-server
 ID: FWIK:WDV7:AKRU:W7HN:KL4C:4B73:5EXD:FZ4C:UHKZ:AJIB:RNEW:SF7G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: tgenannt
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
