### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Boffice** [docker/compose#10232]
### Description

Hello,

I am getting following error, when i try to add command parameter to docker-compose.yml file:

> Container disconnected from docker_default network

### Steps To Reproduce

1. I run **docker-compose up -d** with bellow code

```
version: '3'

services:
  bo:
    image: php:7.4-apache
    restart: always
    depends_on:
      - mysql
    ports:
      - "8888:80"
    volumes:
      - bo_data:/var/www/html/
    command:
    - bash
    - -c
    - |
      apt-get update -y
      apt-get install -y libpng-dev libc-client-dev libkrb5-dev libzip-dev --no-install-recommends
      docker-php-ext-configure imap --with-kerberos --with-imap-ssl
      docker-php-ext-install -j$$(nproc) imap
      docker-php-ext-install mysqli gd zip
      a2enmod rewrite
    container_name: bo-web
  mysql:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3305:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    container_name: bo-db

volumes:
  bo_data: 
    driver: local
  mariadb-data: 
    driver: local
```

My container keeps disconnecting and i get error:

> Container disconnected from docker_default network

2. i run **docker compose down -v** modify docker-compose.yml file and run **docker compose up -d**
```
version: '3'

services:
  bo:
    image: php:7.4-apache
    restart: always
    depends_on:
      - mysql
    ports:
      - "8888:80"
    volumes:
      - bo_data:/var/www/html/
    command:
    - bash
    - -c
    - |
      apt-get update -y
      apt-get install -y libpng-dev libc-client-dev libkrb5-dev libzip-dev --no-install-recommends
      docker-php-ext-configure imap --with-kerberos --with-imap-ssl
      docker-php-ext-install -j$$(nproc) imap
      docker-php-ext-install mysqli gd zip
      a2enmod rewrite
    container_name: bo-web
  mysql:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3305:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    container_name: bo-db

volumes:
  bo_data: 
    driver: local
  mariadb-data: 
    driver: local
```

All works fine, only difference between those two configs is that first one has commands parameter and second one doesn't. 

I did try to run simple commands like echo i get same error:

   ``` command:
    - bash
    - -c
    - |
      echo "test"

```

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Docker Compose version v2.15.1
[backoffice@fedora docker]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.6-200.fc37.x86_64
 Operating System: Fedora Linux 37 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.5GiB
 Name: fedora
 ID: 6bbb1e6a-8be4-4b43-a31b-afcf0e4a0a49
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
