### ISSUE TITLE
[BUG] Docker Compose CLI plugin has different functionality to docker-compose script with group_add

### ISSUE THREAD

**Issue by christovic** [docker/compose#10248]
### Description

I have a docker-compose.yaml file for Jellyfin that goes as such:

```
services:
  jellyfin:
    build: .
    container_name: jellyfin
    user: dockeru:dockeru
    restart: unless-stopped
    group_add:
      - video
      - render
    ports:
      - 8096:8096
    networks:
      - proxy
    volumes:
      - /home/jellyfin/data/jellyfin/config:/config
      - /home/jellyfin/data/jellyfin/icons/snp:/icons
      - /home/jellyfin/data/jellyfin/cache:/cache
      - /mnt/chungus/media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
```

Dockerfile:
```
FROM jellyfin/jellyfin:latest

RUN groupadd -g 107 render 
RUN groupadd -g 1500 dockeru 
RUN adduser --no-create-home --uid 1500 -gid 1500 dockeru
```

`dockeru` is a user on the host, added to the groups `video` and `render`

When I run `docker-compose up -d`, `dockeru` inside the container is part of the groups `video` and `render`. 

When I run `docker compose up -d`, `dockeru` inside the container is *not* part of the groups `video` and `render`. 

I've also tried using the group id instead of the group name to no avail.

### Steps To Reproduce

As above

### Compose Version

```Text
docker compose version
Docker Compose version v2.2.2

docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.2.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 44
  Running: 30
  Paused: 0
  Stopped: 14
 Images: 308
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-17-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.53GiB
 Name: blackbox
 ID: MQ6O:PY6X:EVB4:MJHS:5XHU:UCKF:KQ4J:QDQT:5GIF:2LB7:HGEK:3MQM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username:
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?
A quick demonstration:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/41591830/217226095-c4a2a97b-4911-43c9-a060-885bf7117bdb.png">
