### ISSUE TITLE
config subcommand: ` --no-consistency` silently ignored when used together with `--images`

### ISSUE THREAD

**Issue by mactijn** [docker/compose#10286]
Using the Docker Compose CLI plugin, I am attempting to extract the image names from a `docker-compose.yml` file that is actually a not-yet-parsed Jinja2 template.

The tests below are performed using:
- Ubuntu 20.04
- Docker Engine 23.0.1
- Docker Compose 2.16.0

Minimal `docker-compose.yml`:
```yaml
version: '3.8'
services:
  foo:
    image: alpine:latest
    volumes:
      - '[% keys_certs.foo.path %]:/run/secrets/:ro'
```

Output of `docker compose config --no-consistency`:
```yaml
name: compose-bug
services:
  foo:
    image: alpine:latest
    networks:
      default: null
    volumes:
    - type: volume
      source: '[% keys_certs.foo.path %]'
      target: /run/secrets
      read_only: true
      volume: {}
networks:
  default:
    name: compose-bug_default
```
This indicates to me that the file is at least somewhat valid.

Output of `docker compose config --images`:
```
service "foo" refers to undefined volume [% keys_certs.foo.path %]: invalid compose project
```
This is to be expected, as that is neither a valid filesystem path or a volume that exists.

One could assume at this point (as I did) that combining these arguments could potentially produce the desired results.

## Actual result
Output of `docker compose config --images --no-consistency`:
```
service "foo" refers to undefined volume [% keys_certs.foo.path %]: invalid compose project
```
This indicates to me that the `--no-consistency` flag is silently being ignored.

## Expected result
I would have expected to either get:
- a list of whatever the string value is of all occurrences of `image` in every item in `services`
- a fatal error with a message indicating that `--no-consistency` cannot be used together with `--images`
- a warning message indicating that `--no-consistency` will be ignored when used together with `--images`, followed by the current error message.

## Workaround
This workaround employs a 3rd-party tool, `jq`, to parse the JSON-formatted output:
```bash
docker compose config --no-consistency --format json | jq -r '.services|map(select(.image?)|.image)[]'
```
