### ISSUE TITLE
[BUG] Merged network interpreted as external 

### ISSUE THREAD

**Issue by AdrienPoupa** [docker/compose#10290]
### Description

I am merging two compose files using `COMPOSE_FILE`: `COMPOSE_FILE=docker-compose.yml:folder/docker-compose.yml`

The second Compose file refers to a network defined in the first, but if the network does not exist, it fails saying the external network was not found, when it fact it is not external to begin with:

docker-compose.yml
```yml
version: "3.9"
  services:
    traefik:
      image: traefik:v2.9

networks:
  default:
    name: docker-compose-nas
```

folder/docker-compose.yml
```yml
version: "3.9"
  services:
    adguardhome:
      image: adguard/adguardhome
      networks:
        adguardhome:
          ipv4_address: 10.0.0.10
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=docker-compose-nas"
        - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"

networks:
  adguardhome:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_adguard
    ipam:
      config:
        - subnet: 10.0.0.0/24
```

Here, I would expect that `adguardhome` will join both `docker-compose-nas` and `adguardhome`.

```bash
$ docker compose up -d
network docker-compose-nas declared as external, but could not be found
```

workaround:

```bash
$ docker network create docker-compose-nas
$ docker compose up -d
```

Even more weird, sometimes it works, sometimes it does not, as if the order it reads the Compose file changed.

I tried to set `external: true` in `folder/docker-compose.yml`'s `docker-compose-nas` network, results in the same error message.

I tried to set `external: false` in `folder/docker-compose.yml`'s `docker-compose-nas` network, then it creates a new network that's not `docker-compose-nas`

I think the error here is that the `folder/docker-compose.yml` file is parsed without interpreting that  `docker-compose.yml` defines the `docker-compose-nas` network, and that it must be external, but it is not.

Previously, I was using `folder/docker-compose.yml` in a different folder, outside of the main `docker-compose.yml` scope. I specified `external: true` for the `docker-compose-nas` network and it was working fine because the network already existed.

### Compose Version

```Text
2.15.1
```

### Docker Environment

```Text
23.0.0
```

**Comment by AdrienPoupa** [comment]
That was a mistake on my end. The following works:
```yml
      networks:
        default:
        adguardhome:
          ipv4_address: 10.0.0.10
```
