### ISSUE TITLE
Get deterministic ports when restarting containers

### ISSUE THREAD

**Issue by mhoangvslev** [docker/compose#10297]
### Description

I am in the situation where I cannot start all containers at once, i.e I can only start one container at a time. The latest release allowed me to do just that. The workflow requires that I have to start-stop containers frequently.

Given the `docker-compose.yml` below. Since I only use 10 containers, I specify the port ranges with the interval of 10.

```yaml
  bsbm-virtuoso:
    #container_name: "bsbm-virtuoso"
    image: openlink/virtuoso-opensource-7:7.2.8
    #image: tenforce/virtuoso:virtuoso7.2.5
    #user: "1000:1000"
    environment:
      SPARQL_UPDATE: "false"
      DBA_PASSWORD: "dba"
      VIRT_SPARQL_MaxQueryCostEstimationTime: 0
      VIRT_SPARQL_ResultSetMaxRows: 0
      VIRT_SPARQL_MaxQueryExecutionTime: 0
      #VIRT_SPARQL_MaxQueryExecutionTime: 300
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
    volumes:
      #- "../model/dataset:/usr/local/virtuoso-opensource/share/virtuoso/vad"
      - "../model/dataset:/usr/share/proj"
    ports:
      - 33201-33210:1111
      - 34201-34210:8890
```

Each time I restart a container, it takes a random port among the 10 specified. Is there a way to assign a port to a container permanently until it's downed (not stopped)?

Quick search on Google points me to issues  #722 and #1241 but those are really not the same.
