### ISSUE TITLE
[BUG] `docker-compose create --scale SERVICE=<num>` create containers for other services

### ISSUE THREAD

**Issue by mhoangvslev** [docker/compose#10345]
### Description

- Given the compose file below:
```yaml
services:
  virtuoso-1:
    container_name: "bsbm-product-only"
    image: openlink/virtuoso-opensource-7:7.2.9
    environment:
      SPARQL_UPDATE: "false"
      DBA_PASSWORD: "dba"
      VIRT_HTTPServer_ServerThreads: 20
      VIRT_HTTPServer_MaxClientConnections: 20
      VIRT_Parameters_MaxClientConnections: 20
      VIRT_SPARQL_MaxQueryCostEstimationTime: 0
      VIRT_SPARQL_ResultSetMaxRows: 0
      VIRT_SPARQL_MaxQueryExecutionTime: 0
      #VIRT_SPARQL_MaxQueryExecutionTime: 300
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
    volumes:
      - "../model/dataset:/usr/local/virtuoso-opensource/share/virtuoso/vad"
      # - "../model/tmp/product:/usr/share/proj"
    ports:
      - 1111:1111
      - 8890:8890

  virtuoso-2:
    image: openlink/virtuoso-opensource-7:7.2.7
    environment:
      SPARQL_UPDATE: "false"
      DBA_PASSWORD: "dba"
      VIRT_HTTPServer_ServerThreads: 20
      VIRT_HTTPServer_MaxClientConnections: 20
      VIRT_SPARQL_MaxQueryCostEstimationTime: 0
      VIRT_SPARQL_ResultSetMaxRows: 0
      VIRT_SPARQL_MaxQueryExecutionTime: 0
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
      VIRT_Parameters_ThreadCleanupInterval: 10
      VIRT_Parameters_ResourcesCleanupInterval: 10
      VIRT_Parameters_MaxClientConnections: 20
      VIRT_Parameters_IndexTreeMaps: 256
      VIRT_Plugins_Load1: "plain, geos"
      VIRT_Plugins_Load2: "plain, proj4"
      VIRT_Plugins_Load3: "plain, shapefileio"
      #VIRT_Plugins_Load4: "plain, graphql"
    volumes:
      #- "../model/dataset:/usr/local/virtuoso-opensource/share/virtuoso/vad"
      - "../model/dataset:/usr/share/proj"
    ports:
      - 33201-33210:1111
      - 34201-34210:8890

```
- Upon doing `docker-compose create --scale virtuoso-2=10`, one container for `virtuoso-1` is created as well.

### Compose Version

```Text
Docker Compose version v2.16.0
```
