### ISSUE TITLE
[Feature request]: Generate visual representation (graph) of compose file

### ISSUE THREAD

**Issue by BenjaminGuzman** [docker/compose#10364]
### Description

It would be nice if we could see a visual representation of our services declared in the YAML config.

To achieve that we generate graphviz code based on the YAML configuration, and then let the user convert that code to any format she/he wants or even modify it to suit their needs.

## Example

Let's say this is our config file:

```yaml
version: "3.9"
services:
  service1:
    image: guzmanbenjamin/service1
    networks:
      - internal-net

  service2:
    image: guzmanbenjamin/service2
    networks:
      - internal-net
    depends_on:
      - service1
      - postgres
      - mongo

  postgres:
    image: postgres
    networks:
      - internal-net

  mongo:
    image: mongo
    command: --auth
    networks:
      - internal-net

  gateway:
    image: nginx
    ports:
      - "127.0.0.1:80:80"
      - "443:443"
    networks:
      - internal-net
      - public-net
    depends_on:
      - service1
      - service2

networks:
  internal-net:
    external: true
  public-net:
    driver: bridge
    enable_ipv6: true
```

Then, it would be nice if a subcommand existed, let's name it `viz` such that when running

```shell
docker compose viz
```

The following graphviz code is generated

```
digraph {
    service1 [style="filled" fillcolor="burlywood1" label=<<font point-size="15">service1</font><br/><font point-size="10">internal-net</font>>]
    service2 [style="filled" fillcolor="aquamarine" label=<<font point-size="15">service2</font><br/><font point-size="10">internal-net</font>>]
    postgres [style="filled" fillcolor="burlywood1" label=<<font point-size="15">postgres</font><br/><font point-size="10">internal-net</font>>]
    mongo [style="filled" fillcolor="burlywood1" label=<<font point-size="15">mongo</font><br/><font point-size="10">internal-net</font>>]
    gateway [style="filled" fillcolor="lightslateblue" label=<<font point-size="15">gateway</font><br/><font point-size="10">internal-net<br/>public-net<br/>127.0.0.1:80:80<br/>443:443</font>>]

    service2 -> service1
    service2 -> mongo
    service2 -> postgres
    gateway -> service1
    gateway -> service2
}
```

And, finally, when running graphviz tools such as `dot`, this image is generated.

![example](https://user-images.githubusercontent.com/33078735/224505976-3022553b-c0ce-4a73-b934-12972585cece.svg)

Excuse my color selection, but that's exactly what user may be able to customize with options.

List of subcommand options proposed:

- `--network <bool>`: Include the name(s) of the network(s) a service is attached to.
- `--ports <bool>`: Include the exposed port(s) of a service.
- `--image <bool>`: Include the image used to instantiate the container.

Also, more options may be included to configure the graph design such as:

- `--color <string>`: Define how to color nodes in graph. Examples: `depth;red,#00ff00,blue` would color level 1 nodes in red, then level 2 nodes in green, and level 3 nodes in blue. Or, `network;internal-net=pink,public-net=red` would color nodes attached to internal-net red, and so on...
- `--layout <string>`: Define the [layout](https://graphviz.org/docs/layouts/) of the graph. Examples: `twopi`, `circo`.
