### ISSUE TITLE
Automatically mount volumes on host with `create --scale`

### ISSUE THREAD

**Issue by mhoangvslev** [docker/compose#10378]
### Description

- Given the following yaml:
```yaml
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.7
    environment:
      SPARQL_UPDATE: "false"
      DBA_PASSWORD: "dba"
      VIRT_HTTPServer_ServerThreads: 20
      VIRT_HTTPServer_MaxClientConnections: 20
      VIRT_SPARQL_MaxQueryCostEstimationTime: 0
      VIRT_SPARQL_ResultSetMaxRows: 0
      VIRT_SPARQL_MaxQueryExecutionTime: 0
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
      VIRT_Parameters_MaxClientConnections: 20
      VIRT_Parameters_IndexTreeMaps: 256
      VIRT_Parameters_DefaultIsolation: 1; READ UNCOMMITED
      VIRT_Parameters_ThreadCleanupInterval: 1; Automatically clean up threads
      VIRT_Parameters_ResourcesCleanupInterval: 1; Automatically clean up threads
      VIRT_Plugins_Load1: "plain, geos"
      VIRT_Plugins_Load2: "plain, proj4"
      VIRT_Plugins_Load3: "plain, shapefileio"
      #VIRT_Plugins_Load4: "plain, graphql"
    volumes:
      - "../model/dataset:/usr/share/proj"
      - "./backup/container{CONTAINER_NAME}:/path/to/target
    ports:
      - 33201-33210:1111
      - 34201-34210:8890
```

- Is there a way to make it mount newly created volumes on host directories `"./backup/container{CONTAINER_NAME}`?
