### ISSUE TITLE
Docker compose throws an error while docker-compose worked

### ISSUE THREAD

**Issue by mlynckat** [docker/compose#10382]
Hi everyone,

I'm having following issue: 
I have a docker-compose.yml file and it works without problems if I start my docker with docker-compose up.
However, if I start it with docker compose up (docker-compose-plugin), it doesn't work anymore. It throws an error: 
`Error response from daemon: invalid mount config for type "volume": invalid mount path: 'mongodb-data-statbot' mount path must be absolute`

Here is my docker-compose.yml:
```
version: "3.8"
services:
  mongodb-statbot:
    image: mongo
    container_name: mongodb-statbot
    env_file:
      - .env
    volumes:
      - mongodb-data-statbot:/data/db
    networks:
      - mongodb_network_statbot
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  mongo-express-statbot:
    image: mongo-express
    container_name: mongo-express-statbot
    env_file:
      - .env
    volumes:
      - mongodb-data-statbot
    depends_on:
      - mongodb-statbot
    networks:
      - mongodb_network_statbot
    ports:
      - 8081:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"

    depends_on:
      - mongodb-statbot

    networks:
      - mongodb_network_statbot

    restart: always

    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend

    env_file:
      - .env
    ports:
      - "80:80"
    
    restart: always
    command: ["npm", "start"]

    depends_on:
      - backend

    networks:
      - mongodb_network_statbot

volumes:
  mongodb-data-statbot:
    name: mongodb-data-statbot
networks:
  mongodb_network_statbot:
    name: mongodb_network_statbot
```

Any idea how I can fix it?

Thank you in advance.
