### ISSUE TITLE
[BUG] multiple Extension FIelds on the same level no longer works in 2.17.0

### ISSUE THREAD

**Issue by GuyKh** [docker/compose#10394]
### Description

When using two Extension Fields (`<<:x-function`) ([documentation1](https://docs.docker.com/compose/compose-file/11-extension/) , [medium article](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd)) in a single service in docker-compose, getting: 
`line 106: mapping key "<<" already defined at line 105 ` error

This used to work up until `2.17.0-rc0`

### Steps To Reproduce

1. Using this docker-compose.yaml:
```
version: "3.9"

x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

x-common-keys-dns: &common-keys-dns
  dns:
   - 1.1.1.1
   - 1.0.0.1

services:
  <<: *common-keys-core
  <<: *common-keys-dns
  redis:
    image: "redis:alpine"
```

2. run `docker compose up -d`
3. Getting:
```
yaml: unmarshal errors:
  line 15: mapping key "<<" already defined at line 14
```

### Compose Version

```Text
2.17.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 21
  Running: 21
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-16-generic
 Operating System: Ubuntu Lunar Lobster (development branch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.51GiB
 Name: nuc
 ID: 472ec251-c659-4904-8146-9b78e36847b1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: guykhmel
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
```
```


### Anything else?

Used to work up until 2.17.0

**Comment by GuyKh** [comment]
A workaround would be to create a single extension field containing both, but this is wrong programming;
i.e.

```
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

x-common-keys-dns: &common-keys-dns
  dns:
   - 1.1.1.1
   - 1.0.0.1

x-common-keys-core-dns: &common-keys-core-dns
  <<: *common-keys-dns
  security_opt:
    - no-new-privileges:true
  restart: always

```

**Comment by milas** [comment]
YAML parsing was improved in v2.17 - the old behavior of allowing multiple merge keys was a quirk of the parser. 

However, as @jorgenader mentioned, you can provide multiple anchors in a single merge key.

This is the expected pattern as documented at https://yaml.org/type/merge.html.

```yaml
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always

x-common-keys-dns: &common-keys-dns
  dns:
   - 1.1.1.1
   - 1.0.0.1

services:
  redis:
    <<: [*common-keys-core, *common-keys-dns]
    image: "redis:alpine"
```

Running `docker compose config`:
```shell
$ docker compose config
name: anchors
services:
  redis:
    dns:
    - 1.1.1.1
    - 1.0.0.1
    image: redis:alpine
    networks:
      default: null
    restart: always
    security_opt:
    - no-new-privileges:true
networks:
  default:
    name: anchors_default
x-common-keys-core:
  restart: always
  security_opt:
  - no-new-privileges:true
x-common-keys-dns:
  dns:
  - 1.1.1.1
  - 1.0.0.1
```
