### ISSUE TITLE
network_mode=host can't be used together with custom network.

### ISSUE THREAD

**Issue by yingshaoxo** [docker/compose#10397]
### Description

I have a traefik gateway. It needs to get TCP source_ip (the sender's IP address), because SMTP needs to verify if an email is send from the right people by checking IP address.

But it seems like once I set `network_mode=host`, I can no longer use `networks: other_bridge_network`

Here is my config:

```yaml
version: "3.9"

networks:
  backend_service:
    external: true

services:
  traefik:
    network_mode: "host"
    networks:
      - backend_service
    image: "traefik:v3.0.0-beta2" #"traefik:v2.9.6"
    container_name: "traefik"
    command:
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.file.directory=/traefik_dynamic_configs"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.smtp.address=:25"
    ports:
      - "80:80"
      - "25:25"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configs/traefik_dynamic_configs:/traefik_dynamic_configs" # <== Volume for dynamic conf file
    restart: unless-stopped

  weloveparty_account_auth_service:
    networks:
      - backend_service
    build: 
      context: ../python_user_auth_system
      dockerfile: ./Dockerfile
    image: yingshaoxo/weloveparty_account_auth_service
    expose:
      - "40051"
      - "40052"
      - "25:25"
    volumes:
      - type: bind
        source: ./configs/python_user_auth_system/config.py
        target: /code/src/config.py
    environment: 
      - redis_network_name=redis
    restart: unless-stopped
```

___

I could just use `bridge network`, but it won't allow me to get the real IP of requests. It only gets the docker-internal-gateway IP address, an LAN address.

Another question: **If I can't get the real IP of requests, how can I ban IP address to prevent DDOS attack?**
