### ISSUE TITLE
[BUG] mapping key "<<" already defined in version >=2.17.0

### ISSUE THREAD

**Issue by frederikhs** [docker/compose#10407]
### Description

Upon upgrading from Docker Compose version 2.16.0 to Docker Compose version 2.17.2 it seems like 2.17 and above dropped support for merging in yaml, ref: https://yaml.org/type/merge.html

```
yaml: unmarshal errors:
  line 155: mapping key "<<" already defined at line 154
  line 192: mapping key "<<" already defined at line 191
```

I seems to happen when to merge keys `<<` exists in the same service. If only 1 exist there is not error.

I see nowhere this is mentioned. I will therefore make this issue a bug since it is.

### Steps To Reproduce

Using the follow docker compose file:

```yaml
x-environment: &env
  environment:
    SOME_VARIABLE: "some_value"

x-deploy-limit: &deploy-limit
  deploy:
    resources:
      limits:
        memory: 24M

services:
  service_a:
    image: alpine
    command: [ "sleep", "infinity"]
    <<: *env
    <<: *deploy-limit
```

Running:
```sh
docker compose config
```

Results in:
```sh
yaml: unmarshal errors:
  line 16: mapping key "<<" already defined at line 15
```

### Compose Version

```Text
$ docker compose version
Docker Compose version 2.17.2
$ docker-compose version
Docker Compose version 2.17.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.10.4
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.17.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 17
  Paused: 0
  Stopped: 0
 Images: 42
 Server Version: 23.0.1
 Storage Driver: btrfs
  Btrfs:
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.08GiB
 Name: g9
 ID: YW5O:Q2E6:YWE4:K65D:PTOH:TAYN:AGI6:LEYU:I2NH:B3UQ:CRQH:PZFG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
