### ISSUE TITLE
[Question] Docker for WordPress ?

### ISSUE THREAD

**Issue by BlackStar1991** [docker/compose#10416]
### Description

I try to install docker for WordPress on Windows Desctop version. My file `docker-compose.yml` looks like: 

```
version: "3.9"

services:
  # WordPress service
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: cracker
    depends_on:
      - db
    volumes:
      - ["./:/var/www/html"]
    networks:
      - cracker

  # MySQL service
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: cracker
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - cracker

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
```
But when I try to raise containers with `docker-compose up -d` I get an error `services.wordpress.volumes.0 must be a string`  Can you suggest what is wrong?

### Steps To Reproduce

1) I try to raise containers with `docker-compose up -d` 
2)Got bug

### Compose Version

```Text
version: "3.9"
```
