### ISSUE TITLE
[BUG] docker-compose-plugin v2.17.2 error "name Does not match pattern '^[a-z0-9][a-z0-9_-]*$'"

### ISSUE THREAD

**Issue by HenkAJV** [docker/compose#10431]
### Description

I upgraded my Ubuntu Linux server from docker-compose-plugin v2.16.0 to 2.17.2.
The docker compose works without any issues on V2.16.

I now get the following error when I run `docker compose -f ./application.yml up -d`

> **name Does not match pattern '^[a-z0-9][a-z0-9_-]*$'**
Should this not allow both upper and lower case characters?

Here is how my yml file looks like.  
I think it's failing because I have Uppercase character (R and P) in the name string. I changed it to lowercase, and it works. Not sure if this is a correct or expected behaviour which is the reason, I am reporting it here.

```yml
version: '3.8'
name: main_fileservice_Redacted-Production
services:
  fileservice:
    image: Redacted.redacted.com:1400/fileservice:1.1.5
    container_name: File-Service-Redacted-Production-main
    volumes:
      - /opt/Redacted/File-Service-Redacted-Production/logs:/logs
      - /opt/Redacted/File-Service-Redacted-Production/encrypted.properties:/encrypted.properties:ro
      - /opt/Redacted/File-Service-Redacted-Production/encrypted.properties:/fileservice/encrypted.properties:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JDK_JAVA_OPTIONS=-Xms100m -Xmx1000m
    ports:
      - 8091:8091
    network_mode: bridge
    restart: unless-stopped
```

### Steps To Reproduce

1. Latest Docker running (docker-compose-plugin v2.17.2) on Ubuntu V 20.0.4
2. Create YML file with name attribute using mixed characters (Uppercase, Lowercase, Underscore, dash)

- Example name: ThisIs_A_Test_name

3. run `docker compose -f ./application.yml up -d`

### Compose Version

```Text
Docker Compose version v2.17.2
```
