### ISSUE TITLE
[BUG] Error with 'read_only: yes' in Docker Compose v2.17.0

### ISSUE THREAD

**Issue by advanceboy** [docker/compose#10465]
### Description

I encountered an error with Docker Compose v2.17.0 when trying to load the following compose file:

```yaml
version: '3'
services:
  ttt-test-pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword 
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
        read_only: yes
```

The error message states that `read_only: yes` "must be a boolean". This issue did not occur in v2.16.

```
services.ttt-test-pg.volumes.0.read_only must be a boolean
```

### Steps To Reproduce

1.  Windows 10
1.  Docker compose v2.17.0
1. Copy the above compose.yml
1. Then `docker compose build`
1.  You will see the error

### Compose Version

```Text
Docker: `Docker version 20.10.24, build 297e128`
Compose: `Docker Compose version v2.17.2` @ Windows 10
```

### Anything else?

Based on similar issues like #10411, it seems that the update to go-yaml/v3 is the root cause of this issue. While there was a breaking change from YAML 1.1 to 1.2 where yes/no and on/off are no longer considered booleans, go-yaml/v3 does support decoding to typed bool.

For compatibility reasons, it would be desirable for Docker Compose to accept yes/no and on/off as booleans when a boolean scalar is expected.
