### ISSUE TITLE
[BUG] npm ERR! path //package.json

### ISSUE THREAD

**Issue by ronnievsmith** [docker/compose#10510]
### Description

Why can I run `npm run start` just fine from Powershell but `docker compose up` adds a "//" to the path then fails to find my package.json file?

Docker Desktop v4.19.0 on Windows 11

I am using compose.yaml and when I open Powershell as Admin at my specific app folder and do `docker compose up` I get `npm ERR! enoent ENOENT: no such file or directory, open '//package.json'`. NOTE the `//package.json` which should be `package.json`.

When I do `npm run start` my nodejs app runs fine producing the log `I ran!`. My `index.js` is a single line of code, console.log("I ran!");

compose.yaml:
```
services:
  node:
    image: node
    command: npm run start
    ports:
      - 8080:8080
```
