### ISSUE TITLE
Prevent concurrent image builds

### ISSUE THREAD

**Issue by kirillgrachoff** [docker/compose#10530]
### Description

There's a case when docker-compose.yml contains following:
```yml
version: "3.9"
services:
  A:
    build: .
    ports:
      - "8082:8082"
    expose:
      - "8082"
    entrypoint: /opt/bin/A
  B:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    entrypoint: /opt/bin/B
```

on `docker compose up --build` it starts building `./Dockerfile` concurrently.

Is there a way to prevent 2 concurrent builds for the same image (to reduce build cache, memory/cpu usage and so on)?

(I can do this if the feature is needed and not too hard to implement)
