### ISSUE TITLE
Add ability to use toml file instead of .env

### ISSUE THREAD

**Issue by deny-7** [docker/compose#10543]
### Description

It would be great to add the ability to use a toml file instead of a regular .env, because toml provides much more functionality than a regular .env.

e.g.
```yaml
services:
  web:
    image: ${toml.services.images}
    ports: ${toml.services.ports}
    env_file: 
       - ${toml.services.env}
  redis:
    image: ${toml.services.images}
```
TOML example
```toml
[services]

[services.web]
image = "nginx"
ports = { 80 = 80, 443 = 443 }
env = {somevar1 = someval1, somevar2 = someval2}

[services.redis]
image = "redis"
```
