### ISSUE TITLE
Compose with bind volumes for local development in Linux

### ISSUE THREAD

**Issue by kashifm14** [docker/compose#10553]
### Description

I am having an issue when running Docker Compose using Docker Desktop for local development with two services in Ubuntu, similar to the guide at [docker docs](https://docs.docker.com/language/nodejs/develop/#use-compose-to-develop-locally)

I am mounting the current directory with the source code as a volume inside the container. I am running the app in debug mode inside the container. I want to make changes in my host, have the volume sync with the container, and run it inside the container.

This issue is that in Linux, when Docker Desktop copies files from the host to the container (bind volume), it remaps the user and group ids. The id of 0 (root) inside the container will be mapped to the host user (in my case, 1000). [Docs link](https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing)

My Docker container API runs using a non-root user with an id of 1000 (inside the container). Since the ids of files from the host synced inside the container by the volume mount are not matching those of the user that runs inside the container, I am running into **EACCES: permission denied.** ( _Could not write file '/usr/src/app/dist/utils/xl-parser.js.map': EACCES: permission denied, mkdir '/usr/src/app/dist'._ )

ls -la output inside my api container:  https://i.stack.imgur.com/yehnw.png

I am using a Nest.js project with some additional python scripts. 

**Can somebody tell me how to fix this?**

- I have tried so many ways to fix it, such as setting the container user id inside the container in the dockerfile to 1000, which is my host user id, but it does not work. 
- I tried all the ways listed in https://jtreminio.com/blog/running-docker-containers-as-current-host-user/ but to no avail. 
- I tried creating the image from scratch using a python:3.11.3-bullseye image, then creating the user and group, but the same issue. 
- Also tried editing the /etc/subuid and /etc/subgid to start id from 1000 instead of 100000, but in that case docker desktop doesnot start up after I make this change.  

docker-compose.yml
```yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT:-3000}
      # Only build development stage from Dockerfile
      target: development
    container_name: api-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - appnetwork
    depends_on:
      - postgres
    env_file:
      - .env
    # Run in debug mode: npm run start:debug
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    restart: unless-stopped

  postgres:
    image: postgres:15.2
    container_name: postgres-app
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    networks:
      - appnetwork
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  appnetwork:
    name: shared-app-network
    driver: bridge

volumes:
  db-data:
    driver: local
```

Dockerfile
```yml
ARG IMAGE=nikolaik/python-nodejs:python3.11-nodejs18-slim

FROM $IMAGE AS base
RUN mkdir -p /usr/src/app
RUN chown -R pn:pn /usr/src/app && chmod -R 700 /usr/src/app
ENV TZ="America/New_York"
WORKDIR /usr/src/app

FROM base AS development

USER pn

COPY --chown=pn:pn package*.json ./
COPY --chown=pn:pn python/* python/

RUN npm install
RUN pip install -r python/requirements.txt

COPY --chown=pn:pn . .

RUN npm run build

CMD [ "node", "dist/main" ]

## PRODUCTION 

FROM base AS production 
ARG APP_PORT=$APP_PORT

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

USER pn

COPY --chown=pn:pn package*.json ./
COPY --chown=pn:pn python/* python/

RUN npm install
RUN pip install -r python/requirements.txt 

COPY --from=development /usr/src/app/dist dist/

EXPOSE ${APP_PORT}

CMD [ "node", "dist/main" ]
```

Docker context output
```sh
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                               
desktop-linux *     moby                                                          unix:///home/santhosh/.docker/desktop/docker.sock                         

```

### Steps To Reproduce

1. Generate a nest.js project
2. Add the docker file and docker compose file to the project
3. Run ```docker compose up```

### Compose Version

```Text
Docker Compose version v2.17.3
```

### Docker Environment

```Text
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.84GiB
 Name: docker-desktop
 ID: e9c72fdf-2fa5-4769-a178-3f05587520c5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

File sharing in Linux: https://docs.docker.com/desktop/faqs/linuxfaqs/#how-do-i-enable-file-sharing

Local development with docker: https://docs.docker.com/language/nodejs/develop/#use-compose-to-develop-locally

**Comment by ndeloof** [comment]
AFAICT this issue is not specific to docker compose, but related to bind mount ownership, so this should be reported to the relevant project

Same issue doesn't apply to Docker Desktop Mac:
```
$ docker run -v $(pwd):/test -u 1000 alpine sh -c "echo hello > /test/foo && ls -al /test"
drwx------   18 1000     root           576 May 11 06:33 .
drwxr-xr-x    1 root     root             8 May 11 06:33 ..
-rw-r--r--    1 1000     root             6 May 11 06:33 foo
 ```
so this seems to be specific to Docker Desktop Linux

As a workaround, with latest version of compose you could use the new `watch` feature to get a comparable developer experience without the need to set a bind mount:

```yaml
services:
  api:
    build: ...
    x-develop:
      watch:
        - path: .
          action: sync
          target: /usr/src/app
```

read more on https://www.docker.com/blog/docker-compose-experiment-sync-files-and-automatically-rebuild-services-with-watch-mode/
