### ISSUE TITLE
Allow multiple ports to be defined in a single ENV variable

### ISSUE THREAD

**Issue by Pexers** [docker/compose#10556]
### Description

Compose lets us define one port in an ENV variable and use it in the _docker-compose_ file, but wouldn't it be even cooler if we could define multiple ports in a single variable? 😄

_docker-compose.yml_
```yaml
services:
  app:
    image: my-image
    ports: [ $PORTS ]
```

_.env_
```env
PORTS=8080:8080,5678:5678
```

Error when attempting this technique:
>1 error(s) decoding:
>
>*error decoding 'Ports': Invalid ip address: 8080
>Process exited with code 15

**Comment by ronnieroyston** [comment]
This issue makes the `--env-file` switch useless. The issue is that if you have a `prod.env` and `dev.env` where `prod.env` needs to listen on ports 80 and 443 you cannot pass multiple ports as an environment variable. You're stuck with a single port as the `.env` variable will not get interpreted as a list.

**Comment by ndeloof** [comment]
The common approach for port parametrization is to define a variable for published port, while container ports are hard coded by container image design:

```yaml
services:
  app:
    image: my-image
    ports: 
        - ${HTTP_PORT}:80
        - ${HTTPS_PORT}:443
```

Closing as a duplicate for https://github.com/docker/compose/issues/4249
