### ISSUE TITLE
[BUG] DOCKER_BUILDKIT=1 is not applied by docker-compose build

### ISSUE THREAD

**Issue by HarvyNBB** [docker/compose#10562]
### Description

DOCKER_BUILDKIT=1 is not applied by docker-compose build as the generated image is of type docker instead of OCI

As reference to the Doc:
https://docs.docker.com/build/attestations/slsa-provenance/
https://docs.docker.com/build/architecture/

As of Docker Engine 23.0 and Docker Desktop 4.19, Buildx is the default build client.
Provenance attestations is supported by default in BuildKit version >=0.11 and Buildx version >=0.10. 

For the current setup
buildkit version is v0.10.6
```
https://github.com/docker/cli/blob/v23.0.5/vendor.mod#L24
```

Therefore the provenance is not enabled by default hence it was enabled via env variable 

```
export BUILDX_NO_DEFAULT_ATTESTATIONS=0
```
Ref: https://docs.docker.com/build/building/env-vars/#buildx_no_default_attestations

### Context information (for bug reports)
output of docker compose version 
```
docker compose version 2.17.3
```

output of docker version
```
docker version
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:12:52 2023
 OS/Arch:           darwin/amd64
 Context:           default

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

output of docker-compose config
```
docker-compose config
name: jenkins-supportive-pipelines
services:
  nginx:
    build:
      context: /Users/me/projects/z/d
      dockerfile: ./Dockerfile
      args:
        DOCKER_BUILDKIT: "1"
    container_name: nginx-amd
    image: private-registry/nginx:latest-tmp
    networks:
      default: null
    platform: linux/amd64
networks:
  default:
    name: d_default
```

### Steps to reproduce the issue
1. Create a Dockerfile
```
FROM nginx:latest
RUN apt-get update && apt-get upgrade -y
```
2. Create a docker-compose.yml
```
version: '3.7'

services:
  nginx:
    container_name: nginx
    image: "nginx:latest"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
           - DOCKER_BUILDKIT=1
```
4. Create a docker-compose.override.yml 
```
version: '3.7'

services:
  nginx:
    container_name: nginx-amd
    image: private-registry/nginx:latest-tmp
    platform: linux/amd64
```
5. enable provenance for buildkit 
```
export BUILDX_NO_DEFAULT_ATTESTATIONS=0
```
8. Run docker-compose -f docker-compose.yml -f docker-compose.override.yml build nginx
9. The image is build successfully

### Observed result

1. Run docker buildx imagetools inspect private-registry/nginx:latest-tmp
```
Name:      private-registry/nginx:latest-tmp
MediaType: application/vnd.docker.distribution.manifest.v2+json
Digest:    sha256:d09cb6709b4ccb3b4892ba3544b6902fd32a787ca6275d004e5867e66af699e9
```
The image is of type docker --> MediaType: application/vnd.docker.distribution.manifest.v2+json

### Expected result

1. Run docker buildx imagetools inspect private-registry/nginx:latest-tmp
```
Name:      private-registry/nginx:latest-tmp
MediaType: application/vnd.oci.image.manifest.v1+json
Digest:   sha256:adbda89ea6f506813f15d2fb670a8d5060e9b1f5221aa4cd37a0b055f3141ab7
```
The image is of type oci --> MediaType: application/vnd.oci.image.manifest.v1+json

### Compose Version

```Text
docker compose version

Docker Compose version v2.17.3
```
docker-compose version
```
Docker Compose version 2.17.3
```
```


### Docker Environment

```Text
docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/me/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/me/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/me/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/me/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/me/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/me/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/me/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/me/.docker/cli-plugins/docker-scout

Server:
 Containers: 395
  Running: 1
  Paused: 0
  Stopped: 394
 Images: 389
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: xxxxxxxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
```


### Anything else?

OS version / distribution: macOS Ventura 13.3.1 (a) (22E772610a)
docker-compose install method: Docker Desktop version 4.19.0 (106363)
