### ISSUE TITLE
[BUG] Environment variable in docker compose with $$

### ISSUE THREAD

**Issue by DzianisMatveyeu** [docker/compose#10606]
### Description

I got an error when run` docker service scale` in` docker swarm` :
`the argument ('2${TASK_ID}1') for option '--p2p' is invalid`
```
version: "3.4"

networks:
  outside:
    external:
      name: "host"

services:
  seeds:
    image: ${IMAGE}
    environment:
      TASK_ID: '{{ .Task.Slot}}'
    command: nup -a /etc/account_files/seeds/account99$${TASK_ID}.json -f info -l info --genesis /etc/account_files/${GENESIS_FILE} --public-address ${VM_PUB} --address ${VM_ADDRESS} --p2p 2$${TASK_ID}1 --rpc 2$${TASK_ID}2 --seed ${VM_SEED}:301 --ddos-off
    logging:
      driver: loki
      options:
        loki-url: "http://eastus2.cloudapp.azure.com:3590/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
    networks:
      - outside
    volumes:
      - nup_seeds:/root/.nup
      - /home/nup/accounts:/etc/account_files


volumes:
  nup_seeds:
    external:
      name: 'nup_seeds-{{.Task.Slot}}'
```
docker container inspect 
![изображение](https://github.com/docker/compose/assets/105710544/44b388f5-b33d-4b68-8cd3-a45b6a66b34a)

### Compose Version

```Text
Docker Compose version v2.17.3
```

### Docker Environment

```Text
Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.10.4-docker)
  compose: Docker Compose (Docker Inc., v2.17.3)

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 1
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: l6vwinn3si6kc55oeqslsj8wt
  Is Manager: true
  ClusterID: 4fzcdx4rtypjw9ddzzc3xdg6f
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.2.4
  Manager Addresses:
   10.0.2.4:2377
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1038-azure
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: vm-nupay-prod-eastus2-seed-0
 ID: UB4D:AODH:UACC:QKUL:J4RR:NBIN:AMXF:ZMVI:7A7D:VSEI:XQWY:LPKD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
