### ISSUE TITLE
[Feature Request] - Adding support for single entry of extra_hosts: and dns: that apply to all services

### ISSUE THREAD

**Issue by ondrovic** [docker/compose#10609]
### Description

Would it be possible to either extend networks (since it seems to make sense going there) or allowing both extra_hosts and dns to be applied at root level and apply to all the services that are defined?

Example at network level
```yml
services:
 service1:
    network:
     - mynetwork
 service2:
    network:
     - mynetwork

networks:
 mynetwork:
    extra_hosts:
      - "host:ip"
      - "host:ip"
    dns:
      - ip
```

Example at root level
```yml
services:
 service1:
 service2:
 etc...

extra_hosts:
 - "host:ip"
 - "host:ip"
dns:
 - ip
```

Currently you would have to define everything in each of the services would make it easier to maintain
