### ISSUE TITLE
Managing Dofigen is the build section

### ISSUE THREAD

**Issue by taorepoara** [docker/compose#10615]
### Description

[Dofigen]([Dofigen](https://github.com/lenra-io/dofigen)) help creating Dockerfiles by defining the structure using YAML.

Managing [Dofigen](https://github.com/lenra-io/dofigen) to make it usable instead of the Dockerfile field to define the Dofigen file:

```yaml
services:
  webapp:
    build:
      context: .
      dofigen: dofigen.yml
```

Or directly define it like in the next example the builds a TypeScript project: 

```yaml
services:
  webapp:
    build:
      context: .
      dofigen: 
        builders:
          - name: module-loader
            from: &image "docker.io/bitnami/node:18"
            workdir: /tmp/module
            adds:
              - package.json
              - package-lock.json
            script:
              - npm ci --omit=dev --cache /tmp/cache
            caches:
              - /tmp/cache
          - name: builder
            from: *image
            workdir: /tmp/app
            adds:
              - .
            script:
              - npm i --cache /tmp/cache
              - npm run build
            caches:
              - /tmp/cache
        from: *image
        workdir: /app
        artifacts:
          - builder: module-loader
            source: "/tmp/module/"
            destination: "/app/"
          - builder: builder
            source: "/tmp/app/dist/"
            destination: "/app/dist/"
          - builder: builder
            source: "/tmp/app/resources/"
            destination: "/app/resources/"
        cmd:
          - node
          - node_modules/@lenra/app-server/dist/bin/app-lenra.js
        ports:
          - 3000
        envs:
          NODE_ENV: production
        ignores:
          - "**"
          - "!/*.json"
          - "!/src/"
          - "!/resources/"
```

**Comment by ndeloof** [comment]
Changes in the compose file format should be discussed on github.com/compose-spec/compose-spec.
Anyway, I don't expect we approve introducing into the compose-spec schema support for a nested format. Anyway it makes sense imho we don't get stuck with `docker build` approach for building images from a `Dockerfile`. 

I suggest we investigate the ability to declare a configurable image builder:
```yaml
services:
  webapp:
      build:
          context: .
          image-builder: # defaults to `docker`
```

with this set, `docker compose build` could then delegate image build to third party tool. For your example this would result into:

```yaml
services:
  webapp:
      build:
          context: .
          image-builder: dofigen
          x-dofigen-file: dofigen.yml  # custom extension can be used to pass parameters to plugable image builder
```

This could also be used to force use of `buildkit`, even when disabled by configuration, as `Dockerfile` might require advanced features and would fail with the classic builder.

Same would allow to integrate [dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container) or any comparable solution
