### ISSUE TITLE
support compose file root property `env_file` 

### ISSUE THREAD

**Issue by trim21** [docker/compose#10630]
### Description

works like cli argument `--env-file stringArray       Specify an alternate environment file.`

also to set compose env file instead of `$PWD/.env` without using cli arguments.

```yaml
version: "..."

env_file: '../.env'

services:
  ...
```

Also I think this should suppress default `.env` file and doesn't support env variable expanding `${}`.
