### ISSUE TITLE
ERROR [db 2/5] RUN apt-get update       && apt-cache showpkg postgresql

### ISSUE THREAD

**Issue by kuncevic** [docker/compose#10640]
### Expected behavior

`docker compose up` should not error

### Actual behavior

`docker compose up` errors with `ERROR [db 2/5] RUN apt-get update       && apt-cache showpkg postgresql`

### Information
  - macOS Version:  13.3.1 (a) 
  - Intel chip or Apple chip: Apple M1 Pro
  - Docker Desktop Version:  24.0.2, build cb74dfc

### Steps to reproduce the behavior

I have that docker file

```
version: '3.8'
services:
  common:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-16
    volumes:
      - .:/workspaces:cached
    # network_mode: service:db
    working_dir: /workspaces/common
    command: sleep infinity
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-16
    volumes:
      - .:/workspaces:cached
    # network_mode: service:db
    working_dir: /workspaces/frontend
    command: sleep infinity

  backend:
    # image: mcr.microsoft.com/devcontainers/typescript-node:0-16
    build: build/backend/
    volumes:
      - .:/workspaces:cached
    # network_mode: service:db
    working_dir: /workspaces/backend
    command: sleep infinity
    environment:
      PG_CONNECTION_STRING: "postgres://postgres:postgres@db/postgres"
      PGPASSWORD: postgres
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres

  db:
    build: build/db/
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
```

When running a `docker compose up` got an error `ERROR [db 2/5] RUN apt-get update       && apt-cache showpkg postgresql`

I've looked into this issue https://github.com/docker/for-mac/issues/6030 and haven't found a solution yet.

Here is the detailed error output: 

![a](https://github.com/docker/for-mac/assets/1283734/43fd7525-3480-40d8-8ce5-45dcb84582b7)
