### ISSUE TITLE
relative path mount  error

### ISSUE THREAD

**Issue by istrike** [docker/compose#10645]
### Description

I ran a script to test mounting a file into a container, but I encountered an error that was not expected. I also tested it in the current folder where the "test.yml" file exists. I was certain it's a bug because my laptop doesn't have the "/host_mnt" folder. 

```bash

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: 
unable to start container process: error during container init: 
error mounting "/host_mnt/Users/strike/tmp/microservice/app_test/mongo-init.js" to rootfs at 
"/docker-entrypoint-initdb.d/mongo-init.js": 
mount /host_mnt/Users/strike/tmp/microservice/app_test/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js 
(via /proc/self/fd/14), flags: 0x5000: not a directory: 
unknown: Are you trying to mount a directory onto a file (or vice-versa)? 
Check if the specified host path exists and is the expected type

```

my dir structure:
├── app_test
│   ├── mongo-express.tar.gz
│   ├── mongo-init.js
│   ├── mongo.tar.gz
│   ├── test.tar.gz
│   └── test.yml
├── deploy.py
├── out.yml
├── requirment.txt
├── set_env.env
├── set_env_copy.env

### Steps To Reproduce

```env
DATABASE_IP=localhost
CONFIG_SERVER_PORT=5678
```

```yaml

version: '3.9'

x-healthcheck: &ck
  restart: always
  healthcheck:
    test: ip a
    start_period: 5s
    interval: 10s
    timeout: 2s
    retries: 5

x-config-server: &config-server
  <<: *ck
  healthcheck:
    test: curl www.baidu.com || exit 1
  environment:
    TZ: Asia/Shanghai
    CONFIG_SERVER_URL: http://$DATABASE_IP:${CONFIG_SERVER_PORT}
    CONFIG_SERVER_USERNAME: admin
    CONFIG_SERVER_PASSWORD: admin

services:
  # Database - Mongo DB
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test
      DB_NAME: test
      DB_USER: root
    ports:
      - '27017:27017'
    volumes:
      # - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  # Database Manager
  mongo-express:
    image: mongo-express
    ports:
      - 8099:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: 172.23.3.28
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

```

1.  run command
```bash

docker-compose --env-file  set_env.env -f app_test/test.yml up -d

```

### Compose Version

```Text
Docker Compose version v2.12.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 64
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 7.675GiB
 Name: docker-desktop
 ID: VCLY:BBEL:FEXD:I2CK:QICD:5PTN:QKMC:VRWN:25M4:LZOT:O3KV:UDZV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.2.99
  hubproxy.docker.internal:5000
  registry.hncy.info
  0.0.0.0/0
  127.0.0.0/8
 Registry Mirrors:
  http://f1361db2.m.daocloud.io/
 Live Restore Enabled: false
```

### Anything else?

macOS:13.4

**Comment by ndeloof** [comment]
I tried to reproduce your issue with a simplified configuration:
```yaml
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
```

and created a text file `mongo-init.js` with "hello" inside

```
$ docker compose run mongo cat /docker-entrypoint-initdb.d/mongo-init.js
hello
```

Can you please try to reproduce, using latest release (v2.18.1) as v2.12 is pretty old
