### ISSUE TITLE
[BUG] Intermittent "container <id> is not connected to the network <network>" errors on up

### ISSUE THREAD

**Issue by milas** [docker/compose#10668]
### Description

Since I've run the E2E suite a bunch today, I've noticed the ddev test fails intermittently when bringing up the project:
```
Failed to start 004: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-004 docker-compose -f /tmp/TestComposeRunDdev2386477416/004/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 1', stdout='#1 [web internal] load build definition from Dockerfile
```

```
Network ddev-004_default  Creating
Network ddev-004_default  Created
Container ddev-004-web  Creating
Container ddev-004-dba  Creating
Container ddev-004-db  Creating
Error response from daemon: container 434c66ed5ce1c8b0a230b1ba25ac0b5cbedfc62710f3fbe01c0000d8fe2e2f80 is not connected to the network ddev_default'
```

That's coming from here: https://github.com/docker/compose/blob/5155d22e09313ddbf3de102a9870328e13d43af2/pkg/compose/convergence.go#L565

When I modified the test locally to leave things running, I could see that the container was in fact connected to the network, so I think this is another Engine race condition with networks given that we create the container just before this

### Steps To Reproduce

Run `TestComposeRunDdev` E2E test a bunch

### Compose Version

```Text
HEAD
```

### Docker Environment

```Text
Occurs on both Engine v20.10.x in CI and v24.x locally on my macOS Docker Desktop install
```

**Comment by milas** [comment]
Given that we're about to reconnect the network (with the full set of options? which I guess we can't do on create), would it make more sense to do the initial container create with network: none and then connect so we don't have to do the pre-emptive disconnect?

**Comment by ndeloof** [comment]
This was implemented to replicate the `docker run` API call payload, but maybe we indeed don't need to.

**Comment by ToshY** [comment]
I got the same error when I upgraded compose from `2.18.1` to `2.19.0`. Reverted back in the meantime.

**Comment by wintheriscomming** [comment]
We got the same error after upgrading to 2.19.0, after reverting to previous version things started working again.

**Comment by rfay** [comment]
This is preventing [DDEV](https://github.com/ddev/ddev) from using v2.19.0, not sure what the fix is, fails on every platform
* https://github.com/ddev/ddev/pull/5006
* https://buildkite.com/ddev/ddev-macos-amd64-mutagen/builds/4555#01890489-e535-4284-b8cb-a24618db7525

**Comment by rfay** [comment]
@ndeloof is there some kind of workaround for this behavior on our end, or does it require a fix to compose?

**Comment by milas** [comment]
Compose v2.19.1 was just released with a fix for this: https://github.com/docker/compose/releases/tag/v2.19.1

**Comment by ToshY** [comment]
> Compose v2.19.1 was just released with a fix for this: https://github.com/docker/compose/releases/tag/v2.19.1

While this seems to fix the `not connected to network` issue, it gave me a `forward host lookup failed: Host name lookup failure` in return when running [`waisbrot/wait` ](https://hub.docker.com/r/waisbrot/wait) with `docker compose run`.

**Example**

```yaml
version: '3.9'
  
services:
  mysql:
    image: ${MYSQL_IMAGE_VERSION}
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webapp

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: mysql:3306
      TIMEOUT: 300
    networks:
      - webapp

volumes:
  mysql_data:
    driver: local

networks:
  webapp:
    driver: bridge
```

```bash
$ docker compose up -d
[+] Running 4/4
 ✔ Container webapp-wait-1    Started                                                                                                                                                         3.0s
 ✔ Container webapp-mysql-1   Started                                                                                                                                                         2.9s

$ docker compose run --rm wait
Waiting for mysql:3306  .mysql: forward host lookup failed: Host name lookup failure
.mysql: forward host lookup failed: Host name lookup failure
.mysql: forward host lookup failed: Host name lookup failure

$ docker compose ps
NAME                            IMAGE                         COMMAND                  SERVICE             CREATED             STATUS              PORTS
webapp-mysql-1                  webapp-mysql                  "docker-entrypoint.s…"   mysql               8 minutes ago       Up 5 minutes        33060/tcp, 0.0.0.0:3308->3306/tcp, :::3308->3306/tcp
```

---

I'm reverting back to `v2.18.1` yet again 🙁

**Comment by rfay** [comment]
2.19.1 is not working for DDEV in many different ways (although the "not connected to network" seems to have gone away), hard to sort out all the [test failures](https://github.com/ddev/ddev/actions/runs/5424546725/jobs/9864059449?pr=5006) but *all* test types have some kind of new failure.

**Comment by akaspin** [comment]
Same. 2.19.1 not working. Reverted to 2.18.1.

**Comment by milas** [comment]
@ToshY I'm having trouble reproducing what you're seeing:

`compose.yaml`
```yaml
services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    networks:
      - webapp

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: mysql:3306
      TIMEOUT: 300
    networks:
      - webapp

volumes:
  mysql_data:
    driver: local

networks:
  webapp:
    driver: bridge
```

```
❯ docker compose up -d
[+] Running 2/2
 ✔ Container network-mysql-1  Started                                                                                                                 0.2s
 ✔ Container network-wait-1   Started                                                                                                                 0.1s

❯ docker compose run --rm wait
Waiting for mysql:3306  .  up!
Everything is up
```

If I start `wait` first, it will write out `mysql: forward host lookup failed: Unknown host, which is expected since that host does not yet exist. The error goes away and `wait` succeeds once the `mysql` service is started.
