### ISSUE TITLE
Allow URL in `services[].build.dockerfile` too

### ISSUE THREAD

**Issue by victorstanciu** [docker/compose#10665]
### Description

`services[].build` accepts a URL to a remote Dockerfile since https://github.com/docker/compose/pull/2430. It would be great if `services.build[].dockerfile` worked the same way, so that other subkeys of `build` could be specified (like `args`).

**Comment by ndeloof** [comment]
URL support applies to `context` attribute, not to the `dockerfile` one, which is defined as a path relative to the context root:
```yaml
services:
  demo:
    build:
      context: github.com/docker/compose
```

I'm closing this issue as "already implemented"

**Comment by victorstanciu** [comment]
@ndeloof thank you for checking into this so quickly, but are you sure that's the case? I can pass in a URL to the `build` parameter and Compose fetches the Dockerfile for me:

![image](https://github.com/docker/compose/assets/25879/6eb5ebf1-f30a-4d87-9748-4e460aca2f42)

This is the Compose file I used:

```
version: '3.7'
services:
    nginx:
        build: https://raw.githubusercontent.com/nginxinc/docker-nginx/master/mainline/alpine/Dockerfile
```
