### ISSUE TITLE
[BUG] docker compose hangs on when adding a volume to a service

### ISSUE THREAD

**Issue by AlessandroStaffolani** [docker/compose#10676]
### Description

I have a docker compose file with a bunch of services. A simple web stack, with a database, a backend, a frontend app, and https-portal service for ssl.

Initially, in my compose I had a volume for the DB data, logs and the ssl certificates and everything was working fine. Now I need to share some data between the backend and the frontend app. I added a new volume and mounted it on the 2 services. However, when restarting the compose (`docker compose up -d`), the `recreate` status of the backend service hangs indefinitely.

Here is my `docker-compose.yaml` file:

```yaml
version: "3"

services:

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
      - api-server
    restart: unless-stopped
    environment:
      DOMAINS: 'my-domain.com -> http://frontend:3000, api.my-domain.com -> http://api-server:4000'
    volumes:
      - https-portal-data:/var/lib/https-portal  #this works fine
    networks:
      - external-net

  api-server:
    image: my-namespace/api-server
    container_name: api-server
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - env_files/api-server.env
    volumes:
      - ./logs/api-server:/usr/src/api-server/logs  # this works fine as well
      - api-server-uploads:/usr/src/api-server/uploads  # this one is causing the problem
    depends_on:
      - mongo
    networks:
      - internal-net
      - external-net

  frontend:
    image: my-namespace/frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - env_files/frontend.env
    volumes:
      - api-server-uploads:/usr/src/api-server/uploads
    depends_on:
      - api-server
    networks:
      - external-net

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file:
      - env_files/mongo.env
    volumes:
      - mongo-data:/data/db # this volume works fine as well
    networks:
      - internal-net

networks:
  internal-net:
  external-net:

volumes:
  mongo-data:
  https-portal-data:
  api-server-uploads:

```

I have also tried to mount the volume directly on a relative path, so I removed from the `volumes` root  ` api-server-uploads:` and changed the services to use:

```yaml
version: "3"

services:
  ...
  api-server:
    ...
    volumes:
      - ./logs/api-server:/usr/src/api-server/logs  # this works fine as well
      - ./api-server-uploads:/usr/src/api-server/uploads
    ...

  frontend:
    ...
    volumes:
      - ./api-server-uploads:/usr/src/api-server/uploads
    ...
```

This last attempt has an even worse behavior. In this case the recreation least some seconds (as expected) but the folder is mounted without the actual files that were already in the `api-server` container.

### Steps To Reproduce

see description

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-73-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.93GiB
 Name: hello-label
 ID: c71fd020-b0af-46ec-8035-d00351f0de32
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I'm working on a DigitalOcean droplet with `Ubuntu 22.04.2 LTS`

**Comment by dilettadebellis** [comment]
I’m facing the same issue as well

**Comment by jamshid** [comment]
Yup this started happening a lot with a recent upgrade like compose 2.18 please fix. 

I Ctrl-C but it keeps running and I have to kill the compose process (`/Users/jamshid/.docker/cli-plugins/docker-compose compose up -d -t 180`).
```
 ✔ Container myproj-syslog-1                 Recreated                                                                                                                                            6.5s 
 ✔ Container myproj-test-1                   Recreated                                                                                                                                            4.0s 
 ⠼ Container myproj-elasticsearchleader-1    Recreate                                                                                                                                          4375.4s 
```
It seems to create weirdly named container:
`4c637469ee2b   elasticsearch:7.17.9a                                                  "/myinit.sh"             52 minutes ago   Created                                                                                                                                                                                                                                          b746afc956bb_myproj-elasticsearchleader-1`

**Comment by ndeloof** [comment]
I tried to reproduce with a simple config:

first started services without a shared volume:
```yaml
services:
  backend:
    image: nginx

  frontend:
    image: nginx
```
then updated config to add a shared volume:
```yaml
services:
  backend:
    image: nginx
    volumes:
      - data:/data

  frontend:
    image: nginx
    volumes:
      - data:/data

volumes:
  data:
```
I get services to be recreated and stared as expected.

If you can reproduce this state with service being stuck in "recreate" state, can you please capture it's state as reported by `docker ps -a` as well as `docker inspect <container>` ?



> the folder is mounted without the actual files that were already in the api-server container.

this is to be expected: doing a bind mount, the target path in your container(s) is replaced by a mount pointing to your local directory, and pre-existing files in container filesystem are hidden

**Comment by AlessandroStaffolani** [comment]
I might have understood the problem. Since this issue, I found a different solution so I had my services up and running. Now I tried to add a dummy volume and restart the compose, similarly to your experiment @ndeloof. Then I repeated the experiment by changing the volume name and volume config.

In the first experiment, I had:

```yaml
version: "3"

services:

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
      - api-server
    restart: unless-stopped
    environment:
      DOMAINS: 'my-domain.com -> http://frontend:3000, api.my-domain.com -> http://api-server:4000'
    volumes:
      - https-portal-data:/var/lib/https-portal  #this works fine
    networks:
      - external-net

  api-server:
    image: my-namespace/api-server
    container_name: api-server
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - env_files/api-server.env
    volumes:
      - ./logs/api-server:/usr/src/api-server/logs  # this works fine as well
      - ./api-server-uploads:/usr/src/api-server/uploads  # this one is causing the problem
      - data:/some-folder
    depends_on:
      - mongo
    networks:
      - internal-net
      - external-net

  frontend:
    image: my-namespace/frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - env_files/frontend.env
    volumes:
      - ./api-server-uploads:/usr/src/api-server/uploads 
      - data:/some-folder
    depends_on:
      - api-server
    networks:
      - external-net

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file:
      - env_files/mongo.env
    volumes:
      - mongo-data:/data/db # this volume works fine as well
    networks:
      - internal-net

networks:
  internal-net:
  external-net:

volumes:
  mongo-data:
  https-portal-data:
  data:
```

In the second, I have just changed the name from `data` to `data2` and changed the volume definition like follows:

```yaml
volumes:
  mongo-data:
  https-portal-data:
  data2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user/deployment/data-dist
```

During the last `docker compose up` I had again the infinite recreate issue. I suppose the problem is that the old `data` volume is still mounted on the container and it causes some error, but the `up` command is not catching it and instead, it hangs indefinitely.

Here the docker inspect of the api-server container:

```
[
    {
        "Id": "b756944e27d6b706c4a89b7effb150a436e1dcb2f51b7e4364710a1e552209e2",
        "Created": "2023-06-14T13:30:02.104556309Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "node",
            "dist/main.js"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 740704,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-06-14T13:30:28.861226791Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:05ead5cbb262c4b7bd767bff702762d6e98a564a29ca072273c6aebbf7d43c07",
        "ResolvConfPath": "/var/lib/docker/containers/b756944e27d6b706c4a89b7effb150a436e1dcb2f51b7e4364710a1e552209e2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b756944e27d6b706c4a89b7effb150a436e1dcb2f51b7e4364710a1e552209e2/hostname",
        "HostsPath": "/var/lib/docker/containers/b756944e27d6b706c4a89b7effb150a436e1dcb2f51b7e4364710a1e552209e2/hosts",
        "LogPath": "/var/lib/docker/containers/b756944e27d6b706c4a89b7effb150a436e1dcb2f51b7e4364710a1e552209e2/b756944e27d6b706c4a89b7effb150a436e1dcb2f51b7e4364710a1e552209e2-json.log",
        "Name": "/api-server",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/astaffolani/deployment/logs/api-server:/usr/src/api-server/logs:rw",
                "/home/astaffolani/deployment/api-server/uploads:/usr/src/api-server/uploads:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "3",
                    "max-size": "20m"
                }
            },
            "NetworkMode": "deployment_internal-net",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "deployment_data",
                    "Target": "/usr/src/api-server/dist",
                    "VolumeOptions": {}
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/7cbcb0ede252291f766dee27448fb25ced30be917c78a1a006575e4faf61d0f3-init/diff:/var/lib/docker/overlay2/ts6z4um510swrtr4qcjk1pi0c/diff:/var/lib/docker/overlay2/6c85bgeb3stt1vi3vv865a6t8/diff:/var/lib/docker/overlay2/n5hr7yp318yki4noxvb4lh4dr/diff:/var/lib/docker/overlay2/b6z4opr6da6166uwrrt6954ju/diff:/var/lib/docker/overlay2/i2nkzpmxeujlwxlaaytaftk4a/diff:/var/lib/docker/overlay2/uztaujwktmgf9ffvfyqui9dps/diff:/var/lib/docker/overlay2/c3f42bd5ce3d965f16e0dc8921e09fe554cc85cdbb9a5b6f6b4ca4ec3bb2588a/diff:/var/lib/docker/overlay2/85b6e9f0badbcdb717d6d43aca8559c7bfc994845b8d8d77e844c176713c1a89/diff:/var/lib/docker/overlay2/30c937b2ddd60098006a6914ddd712e012ee70bbccc5f04b0c6a7bcabb8daad6/diff:/var/lib/docker/overlay2/c32f87fb4b1f724f93f45d108b76ce446e82533b4a0e734f1136a468c47e1344/diff",
                "MergedDir": "/var/lib/docker/overlay2/7cbcb0ede252291f766dee27448fb25ced30be917c78a1a006575e4faf61d0f3/merged",
                "UpperDir": "/var/lib/docker/overlay2/7cbcb0ede252291f766dee27448fb25ced30be917c78a1a006575e4faf61d0f3/diff",
                "WorkDir": "/var/lib/docker/overlay2/7cbcb0ede252291f766dee27448fb25ced30be917c78a1a006575e4faf61d0f3/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/astaffolani/deployment/logs/api-server",
                "Destination": "/usr/src/api-server/logs",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/astaffolani/deployment/api-server/uploads",
                "Destination": "/usr/src/api-server/uploads",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "deployment_data",
                "Source": "/var/lib/docker/volumes/deployment_data/_data",
                "Destination": "/usr/src/api-server/dist",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "b756944e27d6",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "4000": {},
                "4000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "NODE_VERSION=18.16.0",
                "YARN_VERSION=1.22.19"
            ],
            "Cmd": [
                "node",
                "dist/main.js"
            ],
            "Image": "hello-label/api-server",
            "Volumes": null,
            "WorkingDir": "/usr/src/api-server",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "3785c54c97df30334f74a9ffa0e93834fcce0fd477736213bd9886fe82f92ae6",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "mongo:service_started:false,redis:service_started:false",
                "com.docker.compose.image": "sha256:05ead5cbb262c4b7bd767bff702762d6e98a564a29ca072273c6aebbf7d43c07",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "deployment",
                "com.docker.compose.project.config_files": "/home/astaffolani/deployment/hello-label-compose.yaml",
                "com.docker.compose.project.working_dir": "/home/astaffolani/deployment",
                "com.docker.compose.replace": "f095a267ebf0f26c128bac093cfa4800aa1113705095a339bbadb9c410eef7b0",
                "com.docker.compose.service": "api-server",
                "com.docker.compose.version": "2.18.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ad623e792a8527ce950c8eddf0c1268b01be7d2fa0bc1fcc6577e09801d13879",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4000/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/ad623e792a85",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "deployment_external-net": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "api-server",
                        "api-server",
                        "b756944e27d6"
                    ],
                    "NetworkID": "0da59533e419eb5a3b23aa1763730cc82b583220c9a5077d62dc06690e9560a7",
                    "EndpointID": "e3a4aea24f2f007de5896a2e1271aa82aca27e8b22387f944719839c718d2df8",
                    "Gateway": "172.23.0.1",
                    "IPAddress": "172.23.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:17:00:02",
                    "DriverOpts": null
                },
                "deployment_internal-net": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "api-server",
                        "api-server",
                        "b756944e27d6"
                    ],
                    "NetworkID": "e0af984a8596d0f06a89e094dc07773742d85f18bfb5108c413622fae1904679",
                    "EndpointID": "4e463e0bc6187dd58417acc3bbe1806b2a326393b1b5a79271705794cff7b485",
                    "Gateway": "172.22.0.1",
                    "IPAddress": "172.22.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:16:00:04",
                    "DriverOpts": null
                }
            }
        }
    }
]
```
