### ISSUE TITLE
Enhancement of “docker compose up `--abort-on-container-exit`"

### ISSUE THREAD

**Issue by ulyssessouza** [docker/compose#10671]
### Description

This is a proposition to enhance the functionality of the flag by adding a fine grained mechanism to choose the services affected by the flag.

For compatibility reasons, I would propose the addition of a new flag. Let’s call it `--abort-on-services-exit` which would receive a list of services on which it would apply.

```yaml
services:
  web:
    image: nginx
  backend:
    image: myapp
  infrastructure-service1:
    image: some_infra_thing
  infrastructure-service2:
    image: some_infra_thing
```

Usage:
```bash
docker compose up —abort-on-services-exit infrastructure-service1 \
                  —abort-on-services-exit infrastructure-service2
```

This would shutdown the whole stack when an infrastructure service exits not the rest of the services `web` or `backend`.
Note that `--abort-on-services-exit` is not compatible with `--abort-on-container-exit` nor `--exit-code-from`.
