### ISSUE TITLE
feature: Add label support for volumes (networks) to the compose spec

### ISSUE THREAD

**Issue by oliv3r** [docker/compose#10689]
### Description

Currently, it is not possible to add volume (or network etc) labels in a compose file.

```yaml
volumes:
  myvol:
    labels:
      mylabel: <content>
      mylabel2: <more content>
      mylabel3:
```

With the changes of supporting labels on all objects, compose should support this as well.
