### ISSUE TITLE
`compose up --initialize-only`

### ISSUE THREAD

**Issue by felipecrs** [docker/compose#10696]
### Description

I use `docker compose` in CI pipelines to start some services required for, let's say, some E2E testing.

Imagine the following:

```yaml
services:
  one:
    image: ubuntu:latest
    command: [sleep, infinity]
  two:
    image: ubuntu:latest
    command: [sleep, infinity]
```

And a CI pipeline (using Jenkins as GitHub Actions doesn't support native parallelism):

```groovy
// Jenkinsfile

pipeline {
    agent any
    stages {
        stage('Start services') {
            parallel {
                stage('One') {
                    steps {
                        sh 'docker compose up --wait one'
                    }
                }
                stage('Two') {
                    steps {
                        sh 'docker compose up --wait two'
                    }
                }
            }
        }
    }
}
```

The reason why I separate the `docker compose up` calls (instead of `docker compose up --wait one two`) is because I want to keep the logs easy to browse, I want to know quicker which service failed to start, and because I have different error handling depending on which service failed to start.

However, the example above, sometimes fails with:

```
Error response from daemon: network example_default is ambiguous (2 matches found on name)
```

And, I believe, that happens because the two commands tries to initialize the environment at the same time (i.e. create the named volumes, created the named networks - or the default network).

Thus, it would be nice to have a command like `docker compose up --initialize-only` that would only create the named volumes and networks but not start any service, so I could call it before calling the two parallel `docker compose up` for the services.

One workaround is:

```yaml
services:
  initialize:
    profiles: [initialize]
    image: hello-world:latest
  one:
    image: ubuntu:latest
    command: [sleep, infinity]
  two:
    image: ubuntu:latest
    command: [sleep, infinity]
```

Then I can run `docker compose --profile initialize up initialize`.
