### ISSUE TITLE
[BUG] x-develop watch not working

### ISSUE THREAD

**Issue by MauriceArikoglu** [docker/compose#10705]
### Description

The x-develop / watch configuration in my compose file does not work at all when run with `docker compose up --wait -d && docker compose alpha watch`.

I get this output, after that - infinite silence

```
watch command is EXPERIMENTAL
watching .
watching .
watching ./infra/nginx/
```

Compose.yml

```
services:
  proxy:
    container_name: 'nginx-reverseproxy'
    hostname: proxy
    build:
      context: './infra/nginx/'
      dockerfile: 'Dockerfile.dev'
    x-develop:
      watch:
        - action: rebuild
          path: './infra/nginx/'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './infra/nginx/data:/data'
    healthcheck:
      test: "service nginx status || exit 0"
      interval: 1s
      timeout: 5s
      retries: 10
```

Inside my infra/nginx directory I have my nginx.conf and the following Dockerfile (Dockerfile.dev)

```
FROM nginx:1.25.0-alpine

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/lib/nginx/cache && \
    chown nginx /var/lib/nginx/cache && \
    chmod 700 /var/lib/nginx/cache
```

### Steps To Reproduce

Copy compose.yml from above
setup ./infra/nginx with any nginx.conf and the Dockerfile
Run docker compose up --wait -d && docker compose alpha watch

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/me/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/me/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/me/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/me/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/me/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/me/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/me/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/me/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 69622abd-668e-42e2-acfc-33a649da49d9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by MauriceArikoglu** [comment]
If I change the path to `'.'` from `'./infra/nginx/'` it still fails.

```
x-develop:
    watch:
      - action: rebuild
        path: '.'
```
