### ISSUE TITLE
[BUG] service "#extensions" has neither an image nor a build context

### ISSUE THREAD

**Issue by jinnnyang** [docker/compose#10747]
### Description

Docker Compose can not start a basic project，and throw
```
service "#extensions" has neither an image nor a build context specified: invalid compose project
```
After exploring, the issue is caused by the "x-ui" node under serverces(see docker-compose.yaml below).

### Steps To Reproduce

1. new `docker-compose.yaml`
   ```yaml
   version: '3.7'
   name: basic_stack
   services:
     nginx-ui:
       image: alpine:3.18.2
       container_name: Nginx
     x-ui:
       image: alpine:3.18.2
       container_name: XRay
   ```
2. `docker compose up`
3. throw 'service "#extensions" has neither an image nor a build context'
4. if you change `x-ui` to anything else, the project will start successfully. 

### Compose Version

```Text
any
```

### Docker Environment

```Text
I have test the following platform:
- Windows: Docker Desktop 4.20.1 (110738) 
- Ubuntu20.04: Docker version 24.0.2, build cb74dfc
```

### Anything else?

version: '3.7'
name: basic_stack
services:
  nginx-ui:
    image: alpine:3.18.2
    container_name: Nginx
  x-ui:
    image: alpine:3.18.2
    container_name: XRay
