### ISSUE TITLE
[BUG] parsing /Users/eleahburman/Desktop/code/money-matters-weekly/docker-compose.yaml: Top-level object must be a mapping

### ISSUE THREAD

**Issue by EleahBurman** [docker/compose#10769]
### Description

I just tried the command sudo docker compose run web django-admin startproject moneymattersweekly . and received Top-level object must be a mapping . What am I doing wrong?  Here is my yaml file 
```yaml
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
```
and here is my dockerfile 
```
# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
```
