### ISSUE TITLE
[BUG] IPv6 network is always treated as /64, even when specified otherwise

### ISSUE THREAD

**Issue by joel0** [docker/compose#10807]
### Description

Docker Compose appears to be assuming IPv6 networks are always /64, even when specified otherwise.

If I define a /16 IPv6 network, the first /64 of the container's `ipv6_address` are replaced with `subnet` and zeros.
If I define a /72 network, the bits between 64 and 72 are not checked to confirm the IP is in the network.

Take for example.
```
version: "2.4"
services:
  debian:
    image: "debian:bookworm"
    command: sh -c "apt update && apt install iproute2 -y && ip a && ip -6 route"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      my_net1:
        ipv6_address: "fd55:1:2:3:4:5:6:7"
      my_net2:
        ipv6_address: "fd66:1:2:3:4:5:6:7"
networks:
  my_net1:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.55.0.0/16
        - subnet: "fd55::/16"
  my_net2:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.66.0.0/16
        - subnet: "fd66:1:2:3::/72"
```
```
compose-debian-1  | 914: eth0@if915: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
compose-debian-1  |     link/ether 02:42:0a:37:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
compose-debian-1  |     inet 10.55.0.2/16 brd 10.55.255.255 scope global eth0
compose-debian-1  |        valid_lft forever preferred_lft forever
compose-debian-1  |     inet6 fd55::4:5:6:7/16 scope global nodad 
compose-debian-1  |        valid_lft forever preferred_lft forever
compose-debian-1  |     inet6 fe80::42:aff:fe37:2/64 scope link tentative 
compose-debian-1  |        valid_lft forever preferred_lft forever
compose-debian-1  | 916: eth1@if917: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
compose-debian-1  |     link/ether 02:42:0a:42:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
compose-debian-1  |     inet 10.66.0.2/16 brd 10.66.255.255 scope global eth1
compose-debian-1  |        valid_lft forever preferred_lft forever
compose-debian-1  |     inet6 fd66:1:2:3:4:5:6:7/72 scope global nodad 
compose-debian-1  |        valid_lft forever preferred_lft forever
compose-debian-1  |     inet6 fe80::42:aff:fe42:2/64 scope link 
compose-debian-1  |        valid_lft forever preferred_lft forever
compose-debian-1  | fd55::/16 dev eth0 proto kernel metric 256 pref medium
compose-debian-1  | fd66:1:2:3::/72 dev eth1 proto kernel metric 256 pref medium
compose-debian-1  | fe80::/64 dev eth0 proto kernel metric 256 pref medium
compose-debian-1  | fe80::/64 dev eth1 proto kernel metric 256 pref medium
compose-debian-1  | default via fd55::1 dev eth0 metric 1024 pref medium
```

Notice how `eth0` has `fd55::4:5:6:7/16` when it should be `fd55:1:2:3:4:5:6:7/16`.
Notice how `eth1` has `fd66:1:2:3:4:5:6:7/72` which should be invalid because it's not in `fd66:1:2:3::/72`.

### Steps To Reproduce

1. Run the `docker-compose.yml` file in the description.
2. Observe the incorrect and invalid IP addresses in the output.

### Compose Version

```Text
Docker Compose version v2.19.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 76
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-10-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.07GiB
 Name: <REDACTED>
 ID: PXFW:RPDP:IEET:YONZ:TXWS:D36O:ZZZ6:TYJC:WFAC:JBZW:C7Y4:X3EZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 23
  Goroutines: 35
  System Time: 2023-07-13T17:20:17.813576149-07:00
  EventsListeners: 0
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
