### ISSUE TITLE
[BUG] Duplicate source configs get overwritten when `compose.override.yaml` exists

### ISSUE THREAD

**Issue by mpyw** [docker/compose#10809]
### Description

I have noticed a bug when trying to mount the same source to multiple target paths in the configs section. While this operation usually works fine, when an any override is applied through `compose.override.yaml`, only the last one of the same name survives, and the others are overwritten.

This behavior is unexpected as the same source should be able to be mounted to multiple target paths without being overwritten by the override process.

### Steps To Reproduce

1. Prepare the following three files: `compose.yaml`, `compose.override.yaml` and `example.txt`.
2. Run the command `docker compose config`. This results in the following output, with `example_a.txt` and `example_b.txt` missing:
    ```yaml
    configs:
      - source: compose
        target: /workspace/compose.yaml
      - source: compose_override
        target: /workspace/compose.override.yaml
      - source: example_text
        target: /workspace/example_test_c.txt
    ```
3. Also run the command `docker compose run --rm workspace`. The result is the same as above, indicating the issue is not specific to the host environment.

#### `compose.yaml`

```yaml
services:
  workspace:
    image: docker:latest
    configs:
      - source: example
        target: /workspace/example_a.txt
      - source: example
        target: /workspace/example_b.txt
      - source: example
        target: /workspace/example_c.txt
      - source: compose
        target: /workspace/compose.yaml
      - source: compose_override
        target: /workspace/compose.override.yaml
    entrypoint: ['docker', 'compose']
    command: ['config']
    working_dir: /workspace
configs:
  example:
    file: ./example.txt
  compose:
    file: ./compose.yaml
  compose_override:
    file: ./compose.override.yaml
```

#### `compose.override.yaml`

```yaml
services:
  workspace: {}
```

#### `example.txt`

```
Hello, Compose
```

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client:
 Context:    orbstack
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/mpyw/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/mpyw/.docker/cli-plugins/docker-compose

Server:
 Containers: 18
  Running: 13
  Paused: 0
  Stopped: 5
 Images: 47
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.3.12-orbstack-00210-ga4f4fae8883e
 Operating System: OrbStack
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 5.132GiB
 Name: docker
 ID: 419d41ad-7381-42c4-ad83-389ee8fac738
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 192.168.215.0/24, Size: 24
   Base: 192.168.228.0/24, Size: 24
   Base: 192.168.247.0/24, Size: 24
   Base: 192.168.207.0/24, Size: 24
   Base: 192.168.167.0/24, Size: 24
   Base: 192.168.107.0/24, Size: 24
   Base: 192.168.237.0/24, Size: 24
   Base: 192.168.148.0/24, Size: 24
   Base: 192.168.214.0/24, Size: 24
   Base: 192.168.165.0/24, Size: 24
   Base: 192.168.227.0/24, Size: 24
   Base: 192.168.181.0/24, Size: 24
   Base: 192.168.158.0/24, Size: 24
   Base: 192.168.117.0/24, Size: 24
   Base: 192.168.155.0/24, Size: 24
   Base: 192.168.194.0/24, Size: 24
   Base: 192.168.147.0/24, Size: 24
   Base: 192.168.229.0/24, Size: 24
   Base: 192.168.183.0/24, Size: 24
   Base: 192.168.156.0/24, Size: 24
   Base: 192.168.97.0/24, Size: 24
   Base: 192.168.171.0/24, Size: 24
   Base: 192.168.186.0/24, Size: 24
   Base: 192.168.216.0/24, Size: 24
   Base: 192.168.242.0/24, Size: 24
   Base: 192.168.166.0/24, Size: 24
   Base: 192.168.239.0/24, Size: 24
   Base: 192.168.223.0/24, Size: 24
   Base: 192.168.164.0/24, Size: 24
   Base: 192.168.163.0/24, Size: 24
   Base: 192.168.172.0/24, Size: 24
   Base: 192.168.138.0/24, Size: 24
   Base: 172.17.0.0/16, Size: 16
   Base: 172.18.0.0/16, Size: 16
   Base: 172.19.0.0/16, Size: 16
   Base: 172.20.0.0/14, Size: 16
   Base: 172.24.0.0/14, Size: 16
   Base: 172.28.0.0/14, Size: 16
```

### Anything else?

I have been running this on macOS using OrbStack, but as I was able to reproduce the issue using an official image with Docker in Docker, I believe this is not a problem specific to my environment.
