### ISSUE TITLE
depends_on required property error

### ISSUE THREAD

**Issue by ShahimEssaid** [docker/compose#10804]
### Description

The handling of depneds_on when the referenced service is not active (due to profiles in my case) has changed. It used to ignore the missing service but now with the latest compose it is an error if the referenced service is not active. But, I noticed the [new "required" property](https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1)  to enable the previous behavior.  However, this property is causing `Additional property required is not allowed`

### Steps To Reproduce

1. Environment:
Ubuntu 22.04 with Docker installed from Docker repositories.
Docker Compose version v2.19.1
Docker version 24.0.4, build 3713ee1

2. With example compose.yaml:
```
services:
  first:
    image: hello-world

  second:
    image: hello-world
    depends_on:
      first:
        condition: service_completed_successfully
        required: false
```

3. Run:
09:40 $ docker compose up

4. Error:
validating /home/essaids/git/gh/se/hapi-server-setup/tmp/dc1/compose.yaml: services.second.depends_on.first Additional property required is not allowed

### Compose Version

```Text
Docker Compose version v2.19.1
Docker version 24.0.4, build 3713ee1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 1
  Paused: 0
  Stopped: 7
 Images: 77
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-46-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 73.4GiB
 Name: WVM4
 ID: e82f8658-d07f-477c-ab34-a5f152ef9e34
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glours** [comment]
👋 @ShahimEssaid 
The implementation of the new `depends_on.required` is currently in progress and it's still not supported by Compose. But it should be available soon

**Comment by ShahimEssaid** [comment]
If that implementation is still in progress, why was the previous behavior not continued until then?  My setup is not broken with no option to enable the previous behavior. This is not good.

**Comment by ShahimEssaid** [comment]
I understand that you fixed the previous implementation but now the specification has another item that the implementation is not compliant with. So, the implementation is still not according to the spec anyway so why not keep the old behavior as well until both issues are according to the spec?

Anyway, the fix is easy for me for not. I've downgraded to Docker Compose version v2.18.1 and all is good for now.  Yes, you can close for now but if the fix is not in the next release maybe you can consider reverting the fix until both fixes are in a release.

**Comment by janrito** [comment]
https://github.com/docker/compose/issues/9795

**Comment by austindrenski** [comment]
@glours I just encountered this error today with a very simple project in GitHub Actions.

I'm having trouble following the who/where/why of this^ discussion, but I'm pretty sure that my case _does not_ depend on "using a bug as a feature", so hoping we can get this reopened for some more attention on this issue.

```console
$ docker compose config | docker buildx bake --file - --push

ERROR: failed to parse -: parsing yaml: validating : services.fetch.depends_on.otel Additional property required is not allowed, parsing hcl: -.hcl:10,73-74: Invalid character; This character is not used within the language., and 23 other diagnostic(s)
```

```yaml
# original syntax fails
services:

  fetch:
    depends_on:
    - otel

  otel:
```
```yaml
# partial extended syntax fails
services:

  fetch:
    depends_on:
      otel:
        condition: service_healthy

  otel:
```
```yaml
# full extended syntax fails
services:

  fetch:
    depends_on:
      otel:
        condition: service_healthy
        required: true

  otel:
```

___



```yaml
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2.9.1

    - run: docker compose config | docker buildx bake --file - --push
```

```
Docker info
  /usr/bin/docker version
  Client:
   Version:           20.10.25+azure-2
   API version:       1.41
   Go version:        go1.19.10
   Git commit:        b82b9f3a0e763304a250531cb9350aa6d93723c9
   Built:             Thu Apr  6 10:55:17 UTC 2023
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.25+azure-2
    API version:      1.41 (minimum version 1.[12]
    Go version:       go1.19.10
    Git commit:       5df983c7dbe2f8914e6efd4dd6e0083a20c41ce1
    Built:            Thu May  4 13:33:05 2023
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.6.21+azure-3
    GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
   runc:
    Version:          1.1.8
    GitCommit:        82f18fe0e44a59034f3e1f45e475fa5636e539aa
   docker-init:
    Version:          0.19.0
    GitCommit:        
  /usr/bin/docker info
  Client:
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc., 0.11.2+azure-1)
    compose: Docker Compose (Docker Inc., 2.20.2+azure-1)
  
  Server:
   Containers: 0
    Running: 0
    Paused: 0
    Stopped: 0
   Images: 17
   Server Version: 20.10.25+azure-2
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
   runc version: 82f18fe0e44a59034f3e1f45e475fa5636e539aa
   init version: 
   Security Options:
    apparmor
    seccomp
     Profile: default
    cgroupns
   Kernel Version: 5.15.0-1041-azure
   Operating System: Ubuntu 22.04.2 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 6.769GiB
   Name: fv-az587-404
   ID: 3VSB:NXIS:24L2:M6PQ:TJO2:XRKH:EU3Y:O5W5:TBXJ:WCJP:B7JM:JHCV
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Registry: https://index.docker.io/v1/
   Labels:
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
```

```
Buildx version
  /usr/bin/docker buildx version
  github.com/docker/buildx 0.11.2+azure-1 9872040b66[26]
```

```
BuildKit version
  builder-4eb06548-2fb9-49d6-aa72-dbbf9e26261a0: v0.11.6
```
