### ISSUE TITLE
[BUG] Secrets on Windows Container mounted through Linux path

### ISSUE THREAD

**Issue by dev-anton-ko** [docker/compose#10817]
### Description

It seems secrets feature is not working on Windows Containers.

### Steps To Reproduce

Here's docker-compose.yml file.
Secrets > target has been added to illustrate the problem.
```
version: "3.8"

secrets:
  db_connection_string:
    file: db_connection_string.txt

services:
  test:
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    environment:
      - DB_CONNECTION_STRING=C:\ProgramData\docker\secrets\db_connection_string
    secrets:
        - source: db_connection_string
          target: C:\ProgramData\docker\secrets\db_connection_string
```
docker compose output:
`Error response from daemon: invalid mount config for type "bind": invalid mount path: '/run/secrets/C:\ProgramData\docker\secrets\db_connection_string'`

### Compose Version

```Text
Docker Compose version v2.20.0
```

### Docker Environment

```Text
Client:
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:52:09 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:51:02 2023
  OS/Arch:          windows/amd64
  Experimental:     false
```
