### ISSUE TITLE
[BUG] Multiple yaml anchors  cause parsing errors

### ISSUE THREAD

**Issue by dopry** [docker/compose#10824]
### Description

We use multiple anchors like mixins in our docker-compose.yaml to centralize common config. In many places we have a few anchors to define standardized behaviors and other anchors that define the container for a given service that may be re-used in multiple `services` which run with different contexts or configurations. This is a pretty limited example, but they get more complex than this. 

```bash
$ docker compose pull
parsing C:\Users\dopry\src\...\...\docker-compose.yml: yaml: unmarshal errors:
  line 157: mapping key "<<" already defined at line 156
```

```yaml

x-task: &task
  # docker stack deploy restart policy for tasks
  deploy:
    restart_policy:
      condition: on-failure
    replicas: 1
  # docker compose stand-alone restart policy for tasks
  restart: on-failure

x-service: &service
  # docker stack deploy restart policy for tasks
  deploy:
    restart_policy:
      condition: unless-stopped
    replicas: 1
  # docker compose stand-alone restart policy for services
  restart: unless-stopped

services:
 # update api database
  api-migrate: &api
    <<: *task
    image: ghcr.io/org/image:tag
    entrypoint: python manage.py migrate || exit 1

  # api
  api:
    <<: *api
    <<: *service
    ports:
      - "8000:80"
```

I would expect validation for duplicated symbols beginning with <<: to read the entire like to determine if is it a duplicate rather than just depending on the key. I wouldn't want it in introspect the anchors, since they likely do contain duplicates in some scenarios, historically the last has taken precedence is memory serves correctly.  altenatively the anchors should be processed and applied before validating the mapping keys.

### Steps To Reproduce

1. with docker desktop for windows running on WSL
2. create a service configuration that includes multiple yaml anchors
3. run docker compose up 

### Compose Version

```Text
2.19.1
```

### Docker Environment

```Text
$ docker info
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 10
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.6GiB
 Name: docker-desktop
 ID: 411b50bb-2d79-4e12-bd67-363500bfbf89
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
