### ISSUE TITLE
Add support for build additional_contexts to reference other service targets

### ISSUE THREAD

**Issue by andytson** [docker/compose#10834]
### Description

I'd like to be able to reference other services stages in a service's build contexts.

This is possible using buildx bake's `contexts` support for another bake target, but doesn't appear to be implemented yet in compose yet, but build.additional_contexts exists for other context types.

example:

```
service:
  console:
     build:
       context: ./docker/console
  app:
    build:
      context: ./docker/app
      additional_contexts:
        src: service:console
```

should provide the console build's target to app as src context.

To make this clear, `service:console` isn't supported currently by additional_contexts, it's what I'm asking for.
