### ISSUE TITLE
[BUG] "Imported compose file defines conflicting network" when using `include` tag.

### ISSUE THREAD

**Issue by mipro98** [docker/compose#10841]
### Description

I have several `docker-compose.yml` files inside multiple folders with services which all reside inside one proxy network which is defined and created externally (`external: true`).

I now wanted to have one "master" `docker-compose.yml` file which includes all the other compose.yml files through the new [`include`](https://docs.docker.com/compose/compose-file/14-include/) option.

Unfortunately, when evaluating the master `docker-compose.yml`, an error is thrown for conflicting networks. IMO this error doesn't make sense since all services are inside the same network so there shouldnt be merge conflicts.

### Steps To Reproduce

1. create a `/service1/docker-compose.yml` file:
```yml
version: "3.8"
services:
  service1:
    image: someimage
    networks:
      - proxy

networks:
    proxy:
        external: true
```

2.  create a `/service2/docker-compose.yml` file:
```yml
version: "3.8"
services:
  service2:
    image: someimage
    networks:
      - proxy

networks:
    proxy:
        external: true
```

3. Create a `docker-compose.yml` "master" file:
```yml
version: "3.8"
include:
  - service1/docker-compose.yml
  - service2/docker-compose.yml

networks:
     proxy:
         external: true

```

4. execute `docker-compose config` (or any other command) inside `/`:
```
imported compose file [/service2/docker-compose.yml] defines conflicting network proxy
```

### Compose Version

```Text
Docker Compose version 2.20.0
```

### Docker Environment

```Text
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.20.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 19
  Running: 19
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.3-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.525GiB
 Name: Server
 ID: 7DN3:T7IS:GPVY:FVAQ:5BW3:BAOK:6IUY:NALG:4EDL:33BT:TDQ3:WTMQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

If all services share the same network, compose should be able to merge the compose files without conflict.

If I remove
```yml
networks:
    proxy:
        external: true
```

from `service1` and `service2`, the conflict is gone, but the individual `docker-compose.yml` files can't be parsed by themselves anymore because of the missing external network definition.

Above block only seems to be allowed once throughout all included compose files plus the "master" compose file.

**Comment by ndeloof** [comment]
just like C-language `include`, the compose `include` feature just import definitions from another compose file, but does not support redefinition of resources so will complain about such conflicts.

You could use a `commons.yaml` compose file to define this network, and include it from all the other ones.

**Comment by mipro98** [comment]
Okay, makes sense.

I now managed to implement my desired system with a `commons.yml`. For reference, it's also important to not include the `commons.yml` in the in the included file again since otherwise the same issue would occur and we would not gain much. Therefore, now always 2 files are required for one service which makes it a bit less clean.

---

For reference, the structure I came up with for above system looks like this:

```
.
├── commons.yml
├── docker-compose.yml
├── service1
│   ├── docker-compose.yml
│   └── service1.yml
└── service2
    ├── docker-compose.yml
    └── service2.yml

```

`/commons.yml:`:
```yaml
networks:
    proxy:
        external: true
```

`/service1/service1.yml`:
```yaml
version: "3.8"
services:
  service1:
    image: someimage
    networks:
      - proxy
```

`/service1/docker-compose.yml`:
```yaml
version: '3'

include:
  - path: service1.yml
  - path: ../commons.yml
```

`/service2/service2yml`:
```yaml
version: "3.8"
services:
  service2:
    image: someimage
    networks:
      - proxy
```

`/service2/docker-compose.yml`:
```yaml
version: '3'

include:
  - path: service2.yml
  - path: ../commons.yml
```

`/docker-compose.yml` ("master" docker-compose):
```yaml
version: '3'

include:
  - path:  service1/service1.yml
  - path:  service2/service2.yml
  - path: ../commons.yml
```

---

I now can just go to `/` and write `docker-compose <up|down|stop|start|...>` for all services but I can also enter a folder (e.g. `service1`) and use  `docker-compose <up|down|stop|start|...>` there also as usual to only operate on this service.
