### ISSUE TITLE
[BUG] include specification gives me "container name is already in use by"

### ISSUE THREAD

**Issue by jpoggi** [docker/compose#10864]
### Description

Hi,

I'm trying to get the new include feature to work.

From a simple phpMyAdmin container I'm trying to connect to a MariaDB container.

### Steps To Reproduce

I have a simple MariaDB container running.

```
services:
  mariadb.server:
    container_name: mariadb.server
    image: mariadb:11.0
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - 3306:3306
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DATABASE: database
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: user
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    command: [mariadbd, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - /srv/mariadb/db_01:/var/lib/mysql
```

And I want to reach it from my phpMyAdmin container via this docker-compose.yml:

```
include:
  - ../mariadb/docker-compose.yml

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    restart: "no"
    mem_limit: 512m
    ports:
      - '80:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: https://phpmyadmin.example.com/
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    build: .
    depends_on:
      - mariadb.server
```

When I try to start the phpMyAdmin I get this error:

```
Error response from daemon: Conflict. The container name "/mariadb.server" is already in use by container "59398a6c2a36d991ab913b9960fa0cb92fd4ed7876b6b1d7658cbc9797c70485". You have to remove (or rename) that container to be able to reuse that name.
```

What am I missing ?

Regards

### Compose Version

```Text
Docker Compose version v2.20.2
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /home/jdoe/.docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 17
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
  no-new-privileges
 Kernel Version: 5.15.0-78-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.56GiB
 Name: rockatansky
 ID: BUG6:5O6Z:PFVL:CTQF:Y4OO:ELL5:XRBA:BXH5:HD6X:AQRF:ALI7:RFW6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
