### ISSUE TITLE
Cannot service with an empty list of links

### ISSUE THREAD

**Issue by tristan0x** [docker/compose#1086]
The following config drives *compose* crazy:

```yaml
service:
  build: .
  links:
```

Altough this is valid YAML., *compose* raises the following Exception: `TypeError: 'NoneType' object is not iterable`

This should be allowed.
