### ISSUE TITLE
Consistent naming convention

### ISSUE THREAD

**Issue by AzazeII** [docker/compose#10880]
### Description

After compose V2, containers created by docker compose have words in their names separated by hyphen, which is great. But now there is inconsistency between names of containers and all other entities(volumes, networks, images, etc..) managed by docker compose.
Minimal example from my real docker-compose project
```
version: '3'
services:
  sftp:
      image: atmoz/sftp
      restart: unless-stopped
      volumes:
          - sftp-config:/etc/sftp
          - sftp-ssh-config:/etc/ssh

volumes:
  sftp-config:
  sftp-ssh-config:
```

```bash
% sudo docker ps   
CONTAINER ID   IMAGE                               COMMAND                  CREATED      STATUS                  PORTS                                                                   NAMES
4953946efee7   atmoz/sftp                          "/entrypoint"            5 days ago   Up 21 hours             22/tcp                                                                  sftp-sftp-1

% sudo docker network ls
NETWORK ID     NAME                  DRIVER    SCOPE
1ddedf5fb39a   sftp_default          bridge    local

% sudo docker volume ls
DRIVER    VOLUME NAME
local     sftp_sftp-config
local     sftp_sftp-ssh-config
```

I propose making docker compose V2 use hyphen as word separator for names of all entities to be self-consistent. I guess existing `--compatibility` flag will be handy to prevent old compose projects from breaking
