### ISSUE TITLE
[BUG] Variables are not being processed in x-template context

### ISSUE THREAD

**Issue by typoworx-de** [docker/compose#10885]
### Description

Bug or Feature?!
Trying to use variable names from .env in x-fragments f.e. to reuse one build context for multiple versions does not work:

.env
```
APP_VERSION=12
```

docker-compose.yml
```
x-myapp-v12-build: &x-myapp-v12-build
  PHP_RELEASE: 8.2
  HTTPD_RELEASE: apache2

services:
  my-app:
    image: my-app:v${APP_RELEASE}
    build:
      context: .
      dockerfile: Dockerfile.project
      args:
        <<: *x-myapp-v${APP_RELEASE}-build
```

Error:
```yaml: line xyz : did not find expected alphabetic or numeric character```

I would expect that Variables are able to do so and I think it really would make sense to allow this to make Developers decide they use it or not.

### Compose Version

```Text
Docker Compose version v2.20.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 53
  Running: 10
  Paused: 0
  Stopped: 43
 Images: 193
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc sysbox-runc crun io.containerd.runc.v2
 Default Runtime: crun
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.89-xanmod1
 Operating System: Ubuntu 16.04.7 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.6GiB
 Name: gabriel-XMG
 ID: PZ6V:VDD5:IKCG:L27W:Q3BS:VO7L:GVQU:TELK:LD6F:5H3W:TEYI:7UKC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: typoworx
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.11:5000
  registry-api.php-stack.docker:5000
  127.0.0.0/8
 Registry Mirrors:
  http://registry-api.php-stack.docker:5000/
 Live Restore Enabled: false
 Default Address Pools:
   Base: 192.168.165.0/24, Size: 24
   Base: 172.30.0.0/16, Size: 24
```
