### ISSUE TITLE
[BUG] --no-path-resolution not working when using `extends`

### ISSUE THREAD

**Issue by codeart1st** [docker/compose#10897]
### Description

docker-compose.yml
```
version: '3.8'

services:
  test:
    extends:
      file: ./test/docker-compose.yml
      service: test
    volumes:
      - source: ${HOME}/test2
        target: /test2
        type: bind
        read_only: true
```

test/docker-compose.yml
```
version: '3.8'

services:
  test:
    image: TO_BE_REPLACED
    volumes:
      - source: ${HOME}/test
        target: /test
        type: bind
```

`docker compose -f docker-compose.yml config --no-interpolate --no-path-resolution`

```
name: foo
services:
  test:
    image: TO_BE_REPLACED
    networks:
      default: null
    volumes:
    - type: bind
      source: test/${HOME}/test
      target: /test
    - type: bind
      source: ${HOME}/test2
      target: /test2
      read_only: true
networks:
  default:
    name: foo_default
```

Related to #10557. I expected that --no-path-resolution also works for `extends`. Currently the path becomes `test/${HOME}/test` instead of `${HOME}/test`.

### Compose Version

```Text
Docker Compose version v2.20.2-desktop.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout
```
