### ISSUE TITLE
[BUG] Options `uid` and `gid` in `configs` section of service just... Don't work?

### ISSUE THREAD

**Issue by emilyyyylime** [docker/compose#10903]
### Description

The compose file reference on Docker docs [Seem to suggest](https://docs.docker.com/compose/compose-file/05-services/#long-syntax) that the fields `uid` and `gid` in `services.<service>.configs.<n>` control the user and group owning the bind inside the container, respectively --- furthermore, `docker compose` accepts the configuration options as expected. However; when starting the container with docker compose it becomes evident that the file owner is the same as in the host machine.

### Steps To Reproduce

With a local file `./local-file` and the following compose file:
```yaml
version: '3.3'

services:
  some-service:
    build:
      dockerfile_inline: |
        FROM ubuntu
        CMD ["ls", "-l", "/some-file"]
    configs:
      - source: conf
        target: /some-file
        uid: '0' # This does nothing?
        gid: '0'

configs:
  conf:
    file: ./local-file
```
Running `docker compose up`, the container prints:  (with the owner of `local-file` on the host having uid 1000)
```
-rw-r--r-- 1 1000 1000 0 Aug 16 09:10 /some-file
```
You may change the owner of the local file on the host machine and notice how the bind inside the container changes accordingly.

### Compose Version

```Text
Docker Compose version 2.20.3
```

### Docker Environment

```Text
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.20.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 36
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.758GiB
 ID: 240b0c58-f7c5-4c11-9133-03b385e8e7ae
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
