### ISSUE TITLE
Behavior of `depends_on` with `extends` is different from documents

### ISSUE THREAD

**Issue by fuyufjh** [docker/compose#10905]
### Description

As the [document](https://docs.docker.com/compose/multiple-compose-files/extends/#exceptions-and-limitations) described:

> `volumes_from` and `depends_on` are never shared between services using `extends`. These exceptions exist to avoid implicit dependencies; you always define `volumes_from` locally. This ensures dependencies between services are clearly visible when reading the current file. Defining these locally also ensures that changes to the referenced file don’t break anything.

However, in my own test, it seems that `depends_on` was not specially handled. Instead, the values are inherited and merged with new values. 

### Steps To Reproduce

Example: `docker-compose.yaml` is build on top of `base.yaml` but replacing postgres to mysql:

```yaml
# base.yaml
services:
  app:
    image: nginx:latest
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  postgresql:
    image: postgresql:latest
```

```yaml
# docker-compose.yaml
services:
  app:
    extends:
      file: base.yaml
      service: app
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
```

According to the document, the `depends_on` section of service `app` should not be inherited, but actually it was inherited:

```
$ docker compose up
service "app" depends on undefined service postgresql: invalid compose project
```

Moreover, it seems that the list of `depends_on` is actually merged together, which means that I can not override it in any way. 

### Compose Version

```Text
Docker Compose version v2.10.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.10.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 10
  Running: 0
  Paused: 0
  Stopped: 10
 Images: 14
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-1029-aws
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.56GiB
 Name: ip-172-31-18-73
 ID: VUD6:PECU:MW4P:KLLQ:HEY2:WFXP:WZVJ:CY2V:AGQE:AROF:BWDP:G472
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
