### ISSUE TITLE
[BUG] anchors should be available through includes

### ISSUE THREAD

**Issue by shaunco** [docker/compose#10912]
### Description

Just like services, networks, and volumes, **anchors** should be referenceable from includes. Per the [spec](https://github.com/compose-spec/compose-spec/blob/master/14-include.md) _"Any volumes, networks, **or other resources** pulled in from the included Compose file can be used by the current Compose application for cross-service references."_

With a shared.yml file like:
```yml
version: "3.8"

x-default-service:
  &default-service
  deploy:
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 10
      window: 120s
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  networks:
    - anchor-test

networks:
  anchor-test:
```

and a relying postgres.yml file like:
```yml
include:
  - ../shared/shared.yml

services:
  postgresql:
    <<: *default-service
    container_name: postgresql
    image: postgres:14
```

There is an error at the anchor reference line (`<<: *default-service`) that says: `yaml: unknown anchor 'default-service' referenced`

### Steps To Reproduce

1. Reproduce the two files above
2. Run `docker-compose -f postgres.yml config`

### Compose Version

```Text
`docker compose version`: `Docker Compose version v2.20.2-desktop.1`
`docker-compose version`: `Docker Compose version v2.20.2-desktop.1`
```
