### ISSUE TITLE
How to override `network_mode` with a normal `network` ?

### ISSUE THREAD

**Issue by olitomlinson** [docker/compose#10919]
### Description

Hey folks, I want to change the network mode of a service, via the override, but the normal rules of how overrides work don't apply for this kind of change it would seem.

Am I misunderstanding? Is this a bug? or is this a flaw in the design of how networks are declared?

`compose.yml`

```yaml
version: '3.4'
services:
  app-sidecar:
    image: ...
    network_mode: "service:some-other-app"
```

`compose.override.yml`

```yaml
version: '3.4'
services:
  app-sidecar:
    image: ...
    networks:
      - network
```

```bash
docker compose up 
```

Error : 

`service app-sidecar declares mutually exclusive ``network_mode`` and ``networks``: invalid compose project`

**Comment by ndeloof** [comment]
You have to reset `network_mode` on your override file so it is eventually unset in the mode:

`compose.override.yaml`
```yaml
version: '3.4'
services:
  app-sidecar:
    image: ...
    network_mode: !reset ""
    networks:
      - network
```

**Comment by olitomlinson** [comment]
@ndeloof 

I appreciate you taking the time to provide a solution, but unfortunately this does not work for me.

```yaml
 network_mode: !reset ""
 networks:
   - network
```

`service XXXXX declares mutually exclusive `network_mode` and `networks`: invalid compose project`

VSCode seems to be complaining about this too 

<img width="350" alt="image" src="https://github.com/docker/compose/assets/4224880/a724e64f-4ab4-4be2-934a-2b4f8ddfeab7">

**Comment by ndeloof** [comment]
which version of Docker Ccompose are you using ?
I can't tell about VSCode support for recent updates in compose file format, I assume they will always be missing something as long as we provide new features...

**Comment by olitomlinson** [comment]
Using Compose version `3.4` with Docker Desktop `4.21.1`

So I rebooted Docker Desktop and now this appears to be working fine. Thanks so much for your help @ndeloof 

```yAML
    network_mode: !reset ""
    networks:
      - network
```
