### ISSUE TITLE
[BUG] docker compose services.my_service.depends_on.0 must be a string

### ISSUE THREAD

**Issue by zioalex** [docker/compose#10937]
### Description

I am trying to make one service depending on another using the option depends_on defined as follow:
``` 
services:
  my_service:
      image: my_image
  healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20
  my_dependent_service:
    image: my_image
 depends_on: 
    - my_service:
         condition: service_healthy
```

This fails with:     
`validating compose.yml: services.my_dependent_service.depends_on.0 must be a string`

The expectation is that the service `my_dependent_service` start only when `my_service` is healthy

### Steps To Reproduce

With the sample config above, run:
docker compose up

### Compose Version

```Text
Docker Compose version v2.20.2

or Docker Compose version v2.20.3
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 23
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.63-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 923.2MiB
 Name: docker.home.local
 ID: 367a7258-8310-477e-a292-b1609ba0d496
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: nobody@gmail.com
 Experimental: false
 Insecure Registries:
  192.168.178.220:5000
  bigone.local:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Anything else?

I am running on a RP3 with Raspbian OS. 
Besides this problem docker and docker-compose work properly.
