### ISSUE TITLE
[BUG] Context path clobbered by extending a service which sets build args (Regression)

### ISSUE THREAD

**Issue by cphalpin** [docker/compose#10946]
### Description

This is a regression, the previous issue was #10771.

I'm using multiple compose files as well as extending services from other files. The build context is set in a main compose file which is then supplemented by a development compose file. The development compose file doesn't set any build options directly but extends a service from another file which sets build arguments. The build context then somehow get set to the parent directory of the file containing the extended service despite not being set by that service.

It doesn't happen if the build args are set directly by the development compose file itself or if it sets the build context to the same value as set by the main compose file.

Since nothing has explicitly set the build context other than the main compose file I would expect that value to be used.

### Steps To Reproduce

`compose/main.yml`:

```yaml
services:
  app:
    build:
      context: ..
```

`compose/dev.yml`:

```yaml
services:
  app:
    extends:
      file: abstract/dev.yml
      service: app-base
```

`compose/abstract/dev.yml`:

```yaml
services:
  app-base:
    build:
      args:
        var: val
```

`docker compose -f compose/main.yml -f compose/dev.yml config` now returns:

```yaml
name: compose
services:
  app:
    build:
      context: <repo-path>/compose/abstract
      dockerfile: Dockerfile
      args:
        var: val
    networks:
      default: null
networks:
  default:
    name: compose_default
```

Note the build context value.

### Compose Version

```Text
Docker Compose version 2.20.3
```

### Docker Environment

```Text
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.11.2
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.20.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.1.0-280-gc7fa31d4c4
    Path:     /usr/lib/docker/cli-plugins/docker-scan

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 853
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.9-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.27GiB
 Name: canute
 ID: DRIE:ONIL:5OF4:J3MH:6JKH:VZSM:JMCX:DUNP:Q7OB:MO2W:2I3Q:2OYK
 Docker Root Dir: /home/docker
 Debug Mode: false
 Username: cphalpin
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Previous issue: https://github.com/docker/compose/issues/10771
