### ISSUE TITLE
support 'noperm' volume mount option for windows volume

### ISSUE THREAD

**Issue by msingh0101** [docker/compose#10961]
### Description

This is related to the issue discussed here over on the terraform github forum:  https://github.com/hashicorp/terraform/issues/33773#issuecomment-1703219320

There are tools/services that will attempt a chmod on files.   If the mount is windows, those tools fail.
A solution would be to support the 'noperm' file mount option to ignore such errors from things like chmod.
I have attempted doing the below, but it appears to have no effect:

```
volumes:
    win_mount:
      name: win_mount
      driver_opts:
        type: cifs
        o: noperm
        device: ../..
```
After doing the above, once in the container and the file path is mounted, i should be able to tocuh a file, attempt a chmod on it, and the error should be ignored.  Instead i still get 'operation not permitted'
