### ISSUE TITLE
[BUG] The Compose file './docker-compose.yml' is invalid because: services.pihole.environment contains an invalid type, it should be an object, or an array

### ISSUE THREAD

**Issue by startergo** [docker/compose#10987]
### Description

```
version: "3.3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    environment:
      # TZ: 'set timezone'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole/:/etc/pihole/'
      - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './pihole/var-log/:/var/log'
      - './pihole/etc-cont-init.d/10-fixroutes.sh:/etc/cont-init.d/10-fixroutes.sh'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      internal:
      lan:
        ipv4_address: 192.168.1.3
```

### Steps To Reproduce

1. openwrt environment following:
2. https://forum.openwrt.org/t/running-pihole-on-openwrt-x86-rpi-using-docker-tutorial-experiences/108144

### Compose Version

```Text
docker-compose version
docker-compose version 1.28.2, build unknown
docker-py version: 4.4.1
CPython version: 3.9.16
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```
```


### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.17
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version: de40ad0
 Security Options:
  cgroupns
 Kernel Version: 5.4.179
 Operating System: OpenWrt 21.02.2
 OSType: linux
 Architecture: armv7l
 CPUs: 2
 Total Memory: 497.5MiB
 Name: OpenWrt
 ID: RDFY:LDFL:H5IJ:HFQP:JCLJ:MEFK:3IUR:VFZ2:VQCH:56Z3:L3DB:2REO
 Docker Root Dir: /opt/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
```


### Anything else?

_No response_

**Comment by startergo** [comment]
Edited the ```yml```. Now getting different error:

```
version: "3.3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
environment:
  # TZ: 'set timezone'
  # WEBPASSWORD: 'set a secure password here or it will be random'
  # Volumes store your data between container upgrades
volumes:
  - ./pihole/etc-pihole/:/etc/pihole/
  - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
  - ./pihole/var-log/:/var/log
  - ./pihole/etc-cont-init.d/10-fixroutes.sh:/etc/cont-init.d/10-fixroutes.sh
# Recommended but not required (DHCP needs NET_ADMIN)
# https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
cap_add:
  - NET_ADMIN
  restart: unless-stopped
networks:
  internal:
  lan:
    ipv4_address: 192.168.1.3
networks:
  internal:
  lan:
  name: lan
  driver: macvlan
  driver_opts:
    parent: br-lan.20
  ipam:
  config:
    - subnet: 192.168.1.0/24
    
```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 6, column 5
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 27, column 6

**Comment by glours** [comment]
You have to comment the `environment` attribute if you don't declare any env variables and also respect yaml indentation 
```yaml
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    #environment:
    # TZ: 'set timezone'
    # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - ./pihole/etc-pihole/:/etc/pihole/
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      - ./pihole/var-log/:/var/log
      - ./pihole/etc-cont-init.d/10-fixroutes.sh:/etc/cont-init.d/10-fixroutes.sh
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - CAP_NET_ADMIN
    restart: unless-stopped
    networks:
      internal:
      lan:
        ipv4_address: 192.168.1.3
networks:
  internal:
  lan:
    name: lan
    driver: macvlan
    driver_opts:
      parent: br-lan.20
    ipam:
      config:
```
