### ISSUE TITLE
[BUG] docker-compose can't work on desktop docker 

### ISSUE THREAD

**Issue by foxnight2** [docker/compose#10988]
### Description

Follow the reproduce, the container cant work with docker-compose.
But `docker run` can work

ENV : windows 11

### Steps To Reproduce

1. install desk-docker on windows 11  (Docker Compose version v2.20.2-desktop.1)
2. docker pull any_image
3. compose.yaml
```
version: '3.0'

services:
  test:
    image: openvino/ubuntu22_runtime:latest
    ports:
      - "8000:80"
    restart: always
```

4. docker-compose up -d
5. The container always restart. But using the docker run, my container can run.

### Compose Version

```Text
Docker Compose version v2.20.2-desktop.1)
```

### Docker Environment

```Text
windows docker
```
