### ISSUE TITLE
[BUG] dependent container restarts when `service_completed_successfully` is used

### ISSUE THREAD

**Issue by sprat** [docker/compose#10985]
### Description

I have a service that depends on another service to generate its configuration, so I used the following snippet to express the dependency:
```yaml
services:
  job:
    # ...
    depends_on:
      conf-generator:
        condition: service_completed_successfully
```

I would expect the `conf-generator` service to be executed only once, but it executes every time I to start the `job` service, either with `docker compose up job`  or `docker compose run job`.

To me, the following line (from `docker compose ps -A`) correspond to the definition of the `service_completed_successfully` status:
```shell
NAME                    IMAGE            COMMAND                   SERVICE          CREATED          STATUS                      PORTS
test-conf-generator-1   busybox:latest   "touch /conf/my.conf"     conf-generator   26 seconds ago   Exited (0) 11 seconds ago  
```
Or maybe the `service_completed_successfully` meaning should be clarified in the documentation/compose spec?

### Steps To Reproduce

Here is a  `compose.yaml`  file demonstrating my use-case:

```yaml
name: test
services:
  job:
    image: busybox:latest
    command: test -f /conf/my.conf  # this would be a process using the generated configuration file
    volumes:
      - conf:/conf
    depends_on:
      conf-generator:
        condition: service_completed_successfully

  conf-generator:
    image: busybox:latest
    command: touch /conf/my.conf  # generate the configuration
    volumes:
      - conf:/conf

volumes:
  conf: {}
```

when I run this compose file:
```shell
$ docker compose up
[+] Running 3/2
 ✔ Network test_default             Created                                                                                                                                                                                             0.1s 
 ✔ Container test-conf-generator-1  Created                                                                                                                                                                                             0.0s 
 ✔ Container test-job-1             Created                                                                                                                                                                                             0.0s 
Attaching to test-conf-generator-1, test-job-1
test-conf-generator-1 exited with code 0
test-job-1 exited with code 0

$ docker compose up
[+] Running 2/0
 ✔ Container test-conf-generator-1  Created                                                                                                                                                                                             0.0s 
 ✔ Container test-job-1             Created                                                                                                                                                                                             0.0s 
Attaching to test-conf-generator-1, test-job-1
test-conf-generator-1 exited with code 0
test-job-1 exited with code 0
```

As you see, the `test-conf-generator-1` container is started the second time even if it has already completed successfully the first time, I don't expect that.

### Compose Version

```Text
Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 14
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-83-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.486GiB
 Name: hades
 ID: XT2T:NMXN:5VPO:WXVB:ZJ5M:EQAO:OQRK:S545:F5JW:QMOM:WCU7:L5YU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: sprat
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
