### ISSUE TITLE
[BUG] additional_contexts not allowed in macOS

### ISSUE THREAD

**Issue by kchawla-pi** [docker/compose#11004]
### Description

On MacOS 13.4.1c (M1Pro), Docker-Desktop v4.23.0, I get the error  
`services.app_backend.build Additional property additional_contexts is not allowed`

The same file works properly in Windows and Linux.

#### Env
MacOS (M1 Pro) Ventura 13.4.1c

#### Config
```yaml
# compose.yaml
services:
  app_backend: &app_backend
    tty: true
    container_name: airsaas-app_backend
    # noinspection YAMLSchemaValidation
    <<:
      - *envfiles
      - *envs
    working_dir: /projectdir
    build:
      context: ./app_backend
      additional_contexts:
        certificates: ./_certificates
        resources: ./_resources
        common: ./common
```
#### Run
`docker-compose --file compose.yaml build`

#### Error
 `services.app_backend.build Additional property additional_contexts is not allowed`

#### Expected
The config should build without errors.

### Compose Version

```Text
docker compose version
Docker Compose version v2.21.0-desktop.1

docker-compose version
Docker Compose version v2.14.0
```

### Docker Environment

```Text
docker info
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.11.2-desktop.4)
  compose: Docker Compose (Docker Inc., v2.21.0-desktop.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.20)
  init: Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.26.0)
  scout: Command line tool for Docker Scout (Docker Inc., 0.24.1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.3.13-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: e99d0dfc-6c2b-4793-b174-ee6c4278c5bd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: You're not using the default seccomp profile
WARNING: daemon is not using the default seccomp profile
```

### Anything else?

PS: I am getting different versions with `docker-compose version` and `docker compose version`. Is this normal? Aren't they aliases now? Is that the reason of the error? I have never used anything except Docker-Desktop on MacOS and Windows.
