### ISSUE TITLE
[BUG] "up" fails when a container had an "Error" at some point, even if it became "Healthy" after a restart

### ISSUE THREAD

**Issue by andygoossens** [docker/compose#11030]
### Description

When I bring "up" several services with Docker Compose, and at point one container fails (due to an intermittent network issue between containers, which could be another Docker bug in itself), then the Docker Compose command fails due to that Error, even if the container got Healthy again in the meanwhile thanks to its `restart_policy`.

I expected the Docker Compose command to be successful as the container became Healthy again.

### Steps To Reproduce

1. On AlmaLinux 8.8, with the Docker CE Stable repository.
2. With a compose file that looks somewhat like this:
```
services:
  app:
    container_name: deploy-app
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null
      start_period: 30s

  app-dependant:
    container_name: deploy-app-dependant
    depends_on:
      app:
        condition: service_healthy
```
3. I run `docker compose -p deploy up --build -d`
4. Which fails with exit code 1 and this output:
```
Container deploy-app  Error
...
Container deploy-app  Healthy
Container deploy-app-dependant  Starting
Container deploy-app-dependant  Started
dependency failed to start: container deploy-app is unhealthy
```

### Compose Version

```Text
Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-477.21.1.el8_8.x86_64
 Operating System: AlmaLinux 8.8 (Sapphire Caracal)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 25.21GiB
 Name: devvm73
 ID: W4SO:UBLD:UW7N:AOSI:LCIB:NRMD:I334:ZEJ5:LU4A:JVMA:D42E:F5PX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Adding the `--wait` command line parameter does not make a difference.
