### ISSUE TITLE
[BUG] restart:always failure when mounting to a local volume

### ISSUE THREAD

**Issue by kirwinrMK** [docker/compose#11044]
### Description

Current Behavior: 
Container does not restart on exit.

Expected Behavior:
Container restarts on exit.

### Steps To Reproduce

```
version: "3.9"

# Services/Containers
services:
  # Sensor data collection
  sensors:
    build: ./sensors
    container_name: sensors
    logging:
      driver: local
    ports:
      - "8000:8000"
    volumes:
      - /tmp/ble_adv.sock:/tmp/ble_adv.sock
      - config:/etc/telem_config
    restart: always
  

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: /app/config
      o: bind
```
When forcing an exit from python container it does not automatically restart the container,
`docker ps -a` gives `exited(1)` as status.

Using `docker inspect sensors | grep -i error` after a failure to restart I get:
`"Error": "failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/tmp/ble_adv.sock\" to rootfs at \"/tmp/ble_adv.sock\": mount /tmp/ble_adv.sock:/tmp/ble_adv.sock (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"`

If I remove the `config` volume the container seems to restart automatically as it should.

### Compose Version

```Text
Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 62
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.629GiB
 Name: telemetry2
 ID: 56c8036f-d7e4-4817-90a3-813a1b36c15e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```
