### ISSUE TITLE
[BUG] included compose file does not read exported environment variables

### ISSUE THREAD

**Issue by roylez** [docker/compose#11054]
### Description

I do not use `.env` file, instead I put them directly in the shell, and this does not seem to work even though the `.env` loading bug for `include` has been fixed.

### Steps To Reproduce

Working compose file

```
version: '3'

services:
  busybox:
    image: busybox
    command: echo ${FOO}; sleep 1000
```

If splitting it into two, it does not work

```
# compose.yml
version: '3'

include:
  - busybox.yml

services: {}

# busybox.yml
version: '3'

services:
  busybox:
    image: busybox
    command: echo ${FOO}; sleep 1000
```

Use this command to start

```
FOO=hello docker-compose up
```

### Compose Version

```Text
2.20.3
```
