### ISSUE TITLE
removed/inserted USB devices do not work with "restart: always"

### ISSUE THREAD

**Issue by aldas** [docker/compose#11075]
### Description

I have a compose file that runs service that read USB serial device (cheap usb to serial GPS on a sailing boat). When that device "/dev/ttyUSB0" is unplugged the container will be removed and will no recover when that USB replugged and `/dev/ttyUSB0` reappears. 

It would be essential that this container will not be removed from running list and stays in restart loop - thus enabling recovery/0-maintenance after reboots/disconnects

### Steps To Reproduce

compose file is this
```yaml
version: "3.7"
services:
 backend_nmea0183serialscrape:
   # unnecessary things omitted
   restart: always
   devices:
     - /dev/ttyUSB0:/dev/ttyUSB0:rw
   device_cgroup_rules:
     # https://stackoverflow.com/a/62758958/2514290
     - "c 188:* rmw"
     - "c 166:* rmw"
     - "c 4:* rmw"
   group_add:
     - dialout
   volumes:
     - /run/udev:/run/udev:ro
```

### Compose Version

```Text
v2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
Version:    24.0.2
Context:    default
Debug Mode: false

Server:
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 24.0.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Using metacopy: false
 Native Overlay Diff: true
 userxattr: false
Logging Driver: journald
Cgroup Driver: systemd
Cgroup Version: 2
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
runc version: v1.1.7-0-g860f061
init version: de40ad0
Security Options:
 apparmor
 seccomp
  Profile: builtin
 cgroupns
Kernel Version: 5.15.0-78-generic
Operating System: Ubuntu 22.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.604GiB
Name: 90231
ID: 331cee29-e1f8-49e0-9021-b0ba782c3214
Docker Root Dir: /var/lib/docker
Debug Mode: false
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
