### ISSUE TITLE
[BUG] Docker compose ignoring .dockerignore in git repo

### ISSUE THREAD

**Issue by guidopetri** [docker/compose#11080]
### Description

I'm attempting to build a service from a git repo. This build works when using `docker build -f Dockerfile.client .`, but does not when running `docker compose -d up cleanslate_frontend_builder` to build and start the service. The git repo can be found [here](https://github.com/guidopetri/cleanslate.git#main), and I'm building the `Dockerfile.client` dockerfile. The specific error I get is related to typing and makes it clear that the `.dockerignore` in the root of the repo is being ignored, and can be found [in this issue in the cleanslate repo](https://github.com/successible/cleanslate/issues/181).

```yaml
  cleanslate_frontend_builder:
    build:
      context: https://github.com/guidopetri/cleanslate.git#main
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_VERSION=gpetri-b1d904c
        - NEXT_PUBLIC_HASURA_DOMAIN=cleanslate.${SITE_HOSTNAME}
    entrypoint: ''
    command: '/bin/bash'
    container_name: cleanslate_frontend
    restart: no
    depends_on:
      - cleanslate_backend
    volumes:
      - certbot_ssl:/etc/ssl:ro
      - cleanslate_files:/build
```

### Steps To Reproduce

1. Set up `docker-compose.yml` with the service listed above.
2. Run `docker compose up -d cleanslate_frontend_builder`
3. FAIL: The build fails because it's trying to use typing on files that are in the `.dockerignore`.

### Compose Version

```Text
`docker compose version`:

`Docker Compose version v2.21.0`

`docker-compose version`:

`-bash: docker-compose: command not found`
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 14
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s                                                                                                                                                             yslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.21-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.628GiB
 Name: <redacted>
 ID: b3a479bb-df04-4006-916d-b47fbd57041d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

### Anything else?

Issue in the `cleanslate` repo, where I originally encountered the bug: https://github.com/successible/cleanslate/issues/181

**Comment by jhrotko** [comment]
Hello, @guidopetri. 

- there is no `cleanslate_backend` (did you mean `server`?).
- I also cannot see the linked issue :( I get a 404 
- did you edit the `docker-compose.yml` from the repo or created a new one outside the repo? If it was outside your repo.

I tried running a `docker-compose.yml` like so 
```
services:
  cleanslate_frontend_builder:
    build:
      context: https://github.com/guidopetri/cleanslate.git#main
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_VERSION=gpetri-b1d904c
        - NEXT_PUBLIC_HASURA_DOMAIN=localhost
    entrypoint: ''
    command: '/bin/bash'
    container_name: cleanslate_frontend
    restart: no
    volumes:
      - certbot_ssl:/etc/ssl:ro
      - cleanslate_files:/build

volumes:
  certbot_ssl:
  cleanslate_files:
```

with the docker compose version (and current latest) you mentioned and I did not get any error. Could you also copy paste the exact error message you are getting?
<img width="1459" alt="Screenshot 2024-01-10 at 14 45 59" src="https://github.com/docker/compose/assets/22371565/a4193189-7ef5-4bb5-a36a-7efc75c36d1a">
