### ISSUE TITLE
[BUG] `service "test-abc" has neither an image nor a build context specified: invalid compose project`

### ISSUE THREAD

**Issue by stdedos** [docker/compose#11093]
### Description

```yaml
version: "3.9"

services:
  nginx:
    build:
      context: ../
      dockerfile: .gitlab/nginx/Dockerfile
    ports:
      - "80:80"
    cap_add:
      - NET_ADMIN

  abc:
    image: registry/abc:latest
    ports:
      - "127.0.0.1:1234:1234"

  moar_underscored_services:
    image: registry/moar_underscored_services:latest
    ports:
      - "127.0.0.1:9012:9012"

  def:
    image: registry/def:${DEF_TAG}
    ports:
      - "127.0.0.1:5678:5678"

  moar-dashed-services:
    image: registry/moar-dashed-services:latest
    ports:
      - "127.0.0.1:3456:3456"

  test-abc:
    image: ${ABC_IMAGE}
    depends_on:
      - abc
      - more_underscored_services
    entrypoint: ["npm", "run", "test"]

  test-def:
    image: ${DEF_IMAGE}
    depends_on:
      - more_underscored_services
      - def
      - moar_underscored_services
    entrypoint: ["npm", "run", "test"]
```

with this file, `DEF_TAG=$DOCKER_TAG_NAME DEF_IMAGE=$REGISTRY:$CI_COMMIT_REF_SLUG docker-compose -f path/.to/docker-compose.yml run test-def` happily compiles.

However, `docker compose` V2 (aliased via `docker-compose`) gives:

```
time="2023-10-12T12:29:46Z" level=warning msg="The \"ABC_TAG\" variable is not set. Defaulting to a blank ....
service "test-abc" has neither an image nor a build context specified: invalid compose project
```

_In case it is not obvious_, **`test-abc` is never called in this invocation**.

Is that expected?

### Compose Version

```Text
docker-cli-compose	2.17.3-r7	URL	Apache-2.0	v3.18	community	x86_64	Jake Buchholz Göktürk	2023-10-12 14:14:03
```

In Alpine
```


### Docker Environment

_No response_

### Anything else?

_No response_
