### ISSUE TITLE
[BUG(?)] Top-level "include" failing to include services

### ISSUE THREAD

**Issue by kjkent** [docker/compose#11096]
### Description

In the docs for `include`:

> Any volumes, networks, or other resources pulled in from the included Compose file can be used by the current Compose application for cross-service references.

Context: I'm attempting to split an unwieldy long compose file into its comprising services' subfolders, but having difficulty figuring out how to do so without repeating boiler-plate code. Extensions/anchors/aliases can't be split across files, `extends`  requires relative paths not relative to the file it's written in, and doesn't import externally-specified volumes.

`includes` seemed to ameliorate these issues, going off the quoted bit above. I've specified the nuts and bolts in compose-files in subfolders, and have linked to them in a main compose-file in the parent directory.

However, running `docker compose up` errors out as it can't find the extended service.

The docs linked above give examples for using `includes` with  `depends_on`, but don't specify that's the boundary of its utility, and the bit I quoted suggests that what I'm doing _should_ work.

Apologies if I've missed something in the docs, otherwise, perhaps this is unexpected behavior? Many thanks :)

### Steps To Reproduce

1. Create the following files:
```YAML
# ./docker-compose.yaml

x-service_defaults: &service_defaults
  user: ${UID}:${GID}
  restart: always

include:
  - ./prind/docker-compose.yaml

services:
  klipper:
    <<: *service_defaults
    extends:
      service: klipper-base
```
```YAML
# ./prind/docker-compose.yaml

services:
  klipper-base:
  #...
```
2. `docker compose up -d`

Result: `cannot extend service "klipper-base" in /mnt/hdd/docker/docker-compose.yaml: service not found`

### Compose Version

```Text
Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-13-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 23.43GiB
 Name: debvm
 ID: afa54c99-d8bf-4220-b2d6-98b761db6252
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
include applies as the last step of compose loading process, by copying the service definition into your project, but your project has to be already valid before this step takes place, so you can't extends and included service - but you can if you use `extends` with a `file` attribute. AFAICT what you're trying to do here is better implemented using `extends`:

```yaml
services:
  klipper:
    extends:
      service: klipper-base
      file: ./prind/docker-compose.yaml
```
