### ISSUE TITLE
[BUG] Impossible to set deploy section GPU count via environment interpolation

### ISSUE THREAD

**Issue by zacps** [docker/compose#11097]
### Description

GPU selection is often machine dependent, however it is currently impossible to set the count of GPUs requested via environment interpolation, for example:

```yaml
services:
  my-service:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPUS:-all}
              capabilities: [gpu]
```

With `GPUS=1` in `.env`, gives:

```
error decoding 'Deploy.Resources.Reservations.devices[0]': invalid string value for 'count' (the only value allowed is 'all')
```

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 12
  Running: 2
  Paused: 0
  Stopped: 10
 Images: 38
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-162-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 93.84GiB
 Name: bubbles02
 ID: d3406107-556b-4d7c-b46b-d7bcbca7b616
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
