### ISSUE TITLE
[BUG] Included compose files do not inherit profiles properly

### ISSUE THREAD

**Issue by koosham-figure** [docker/compose#11114]
### Description

In `compose.base.yaml`, I have a service that has a profiles tag:

```yaml
services:
  dev:
    image: some_image
    profiles: ["donotstart"]
```

In `compose.services.yaml`, I include `compose.base.yaml`:

```yaml
include:
  - compose.base.yaml

services:
    # production services (no profiles tag) ...
```

I am using the `donotstart` profile tag so that I can call `docker compose -f compose.services.yaml start` and run all services except `dev`.

## Issue:
I can run the `dev` container from the base compose file by running `docker compose -f compose.base.yaml run dev` without having to specify the profile name. But if I do the same on `compose.services.yaml`, I get this error:

```bash
no such service: dev
```

It is possible to run dev by specifying the profile, i.e., `docker compose -f compose.services.yaml --profile donotstart run dev`, but the inconsistency between the behaviors depending on how the service is defined (directly in the high-level compose file or in an included compose file) creates confusion and should be fixed.

### Steps To Reproduce

Explained in descriptions above.

### Compose Version

```Text
2.20.2
```
