### ISSUE TITLE
[BUG] start_period doesn't respect successful healthcheck results during the period

### ISSUE THREAD

**Issue by tboddyspargo** [docker/compose#11131]
### Description

Please let me know if this issue needs to be raised elsewhere. I'm not exactly sure where the problem lies.

I'm unsure if the issue is a code bug, a documentation problem, or my usage.

**Problem:** When `start_period` is defined for a service's healthcheck, successful results during that period will still not allow dependent services (with `condition: service_healthy`) to start up until the full `start_period` has elapsed. Based on my interpretation of [this documentation](https://docs.docker.com/engine/reference/builder/#healthcheck), the container/service is supposed to be marked `healthy` after the first successful healthcheck during the `start_period`. I expect this to allow dependent services (using `condition: service_healthy`) to immediately start up.

### Steps To Reproduce

Using this `docker-compose.yml` file:

```yaml
version: '3.7'
name: 'healthcheck-test'

services:
  service-a:
    container_name: service-a
    image: busybox
    command: sleep 60
    healthcheck:
      test: 'sleep 1'
      interval: 2s
      start_period: 30s # <--- This is the only difference. Should not interfere with service-b's ability to start up in ~2s.
  service-b:
    container_name: service-b
    image: busybox
    command: sleep 10 && echo 'hello world'
    depends_on:
      service-a:
        condition: service_healthy

  service-x:
    container_name: service-x
    image: busybox
    command: sleep 60
    healthcheck:
      test: 'sleep 1'
      interval: 2s
      # No start_period <-- This is the only difference. Allows service-y to start up in ~2s.
  service-y:
    container_name: service-y
    image: busybox
    command: sleep 10 && echo 'hello world'
    depends_on:
      service-x:
        condition: service_healthy

  service-1:
    container_name: service-1
    image: busybox
    command: sleep 60
    healthcheck:
      test: 'sleep 1'
      interval: 2s
      start_period: 2s # <--- This is the only difference. Should allow service-2 to start up in ~2s.
  service-2:
    container_name: service-2
    image: busybox
    command: sleep 10 && echo 'hello world'
    depends_on:
      service-1:
        condition: service_healthy
```

Run `docker compose up -d`. Observe service startup speed at the command line, or use `inspect` to check the timings precisely.

**Expected result:** `service-b` and `service-y` and `service-2` startup at almost exactly the same time.

**Actual result:** `service-y` starts up after ~2 seconds, but `service-b` _and_ `service-2` start up after ~30s.

### Compose Version

```Text
Docker Compose version v2.22.0-desktop.2
```

### Docker Environment

```Text
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/tyler/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/tyler/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/tyler/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/tyler/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/tyler/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/tyler/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/tyler/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/tyler/.docker/cli-plugins/docker-scout

Server:
 Containers: 30
  Running: 23
  Paused: 0
  Stopped: 7
 Images: 77
 Server Version: dev
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 19.52GiB
 Name: docker-desktop
 ID: 36252aca-a483-4b9d-b39c-ea24c2c0d207
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
