### ISSUE TITLE
docker-compose up creates new volume

### ISSUE THREAD

**Issue by Samjith888** [docker/compose#11159]
### Description

Using the below formatted docker-compose file , where the docker container restart whenever the machie reboots.

```
version: "3.0"

services:
  myapp:
    image: 'app'
    runtime: nvidia
    container_name: myapp
    pid: host
    build:
      context: .
      dockerfile: docker_test
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - 'driver': 'nvidia'
            'capabilities': ['gpu']
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY
    volumes:
      - /media/user/test_sd:/workspace
    network_mode: host
    tty: true
    stdin_open: true
```
Output of `df -h`
`/dev/mmcblk1p1  117G  609M  111G   1% /media/user/test_sd`

When the machine reboots and the docker is restarted, then renaming the mounted volume into test_sd1 and create new path '/media/user/test_sd' where the `test_sd` folder is empty. 

Output of `df -h` after the machine reboots
/dev/mmcblk1p1  117G  609M  111G   1% /media/user/test_sd1

### Steps To Reproduce

create the docker compose file as mentioned above and build the container, then reboot the machine after 1 minute.

### Compose Version

```Text
1.29.2
```
