### ISSUE TITLE
Allow build ulimit to be defined in the compose file

### ISSUE THREAD

**Issue by guilhermenovais** [docker/compose#11167]
### Description

Currently, it is only possible to set ulimits for the container execution, but I also need to set it for the build, so I need to manually build the image using `docker build -t _example_ --ulimit nofile=65536:65536 .` and then run `docker compose up`, instead of just running `docker compose up --build`.

It would be nice if there was an element inside the _build_ element that allowed ulimits to be defined.
This is what I have in mind:
```
version: '3'
services:
  example:
    image: _exemple_
    build:
      context: .
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
```
