### ISSUE TITLE
[BUG] timeout and stop_grace_period are ignored

### ISSUE THREAD

**Issue by chassing** [docker/compose#11205]
### Description

`docker compose down|restart --timeout 1` and `stop_grace_period: 1s` in compose file are ignored. I tried all combinations of `--timeout` with/without `stop_grace_period` and it's always the same behavior.

### Steps To Reproduce

1. given this demo `docker-compose.yml` file 
```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    stop_grace_period: 1s
    stop_signal: SIGKILL
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=${SERVICES:-sqs,dynamodb}
      - PERSISTENCE=${PERSISTENCE:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack_volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```
2. stopping (`docker compose down --timeout 1`) or restarting (`docker compose restart --timeout 1`) the container takes around 16 seconds
3. Expected behavior is the container is down (restarted) in max one second

### Compose Version

```Text
$ docker compose version
Docker Compose version 2.23.1
```
```


### Docker Environment

```Text
$ docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.23.1
    Path:     /Users/cassing/.docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-10-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.813GiB
 Name: colima
 ID: f07e57d0-7768-438f-8733-134a006ebb9c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: chassing
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
