### ISSUE TITLE
Docker-compose doesnt mount local folder

### ISSUE THREAD

**Issue by terbooter** [docker/compose#1121]
I can start my container in two ways:
1) Using console commands (bash script)
2) Using docker-compose util
Before each start I remove all containers and remove all images

In first case I made
```bash
docker build -t web-image .
docker run --restart=always -d -v $(pwd)/www:/app -p 82:80 web-image
```
Container working as expected. In folder /app I have my mounted project files

In second case I have docker-compose.yml config file
```yml
web:
  build: .  
  volumes:
    - www:/app
  ports:
    - "82:80"
  restart: always
```
```sh
docker-compose up -d 
```
In this case container folder /app is empty
