### ISSUE TITLE
Condition contains service_completed_successfully is an invalid type it should be a service_started or service_healthy

### ISSUE THREAD

**Issue by ramya-1000** [docker/compose#11238]
### Description

Iam using version 2.2 docker compose file  and the docker compose binary executable is v2.16.0 and tried with latest versions but getting the issue as Condition contains service_completed_successfully is an invalid type it should be a service_started or service_healthy.

### Compose Version

```Text
docker compose version
V2.21.0
docker compose version
docker-compose command not found
```

### Docker Environment

```Text
Docker Engine version 24.0.7
Buildx version v0.11.2
Docker compose version v2.21.0
```

**Comment by ndeloof** [comment]
You compose file is incomplete as it's missing dependent services definition, so I tried to reproduce with:
```yaml
services:
  postgresdb:
    image: nginx
    depends_on:
      postgresql:
        condition: service_healthy
      flyway:
        condition:  service_completed_successfully

  postgresql:
    image: nginx

  flyway:
    image: nginx
```
works as expected. Can you try to reproduce with this same minimalist compose file?

side note: `version: 'x.y'` is an obsolete notation, remove this from your compose files.
