### ISSUE TITLE
Project name in docker-compose.yml

### ISSUE THREAD

**Issue by fntlnz** [docker/compose#1123]
I have a number of projects which are using docker-compose and I'm starting to have the need to specify the project name directly into the `docker-compose.yml`

**Consider this scenario:**

I have two projects with the following directory structures

```
project1
|-- docker
|    |-- docker-compose.yml
|-- public
|    |--index.php
|-- vendor
|-- modules
```

```
project2
|-- docker
|    |-- docker-compose.yml
|-- public
|    |--index.php
|-- vendor
|-- modules
```
And with two `docker-compose.yml` like this:

```
web:
  image: fntlnz/nginx:1.6.2
  volumes:
    - ../:/var/www/project
  ports:
    - "127.0.0.2:80:80"
  links:
    - fpm:fpm

fpm:
  image: fntlnz/php-fpm:5.6.6
  volumes:
    - ../:/var/www/project
  links:
    - redis:redis

redis:
  image: redis
```

When I issue a `docker-compose up` in the `project1` directory it will start three containers with the following names `docker_web_1`, `docker_fpm_1`, `docker_redis_1`.

If now I issue the same command in the `project2` directory it recreates the same containers of project1 instead creating it's own.

I know that I can change the project name using the `-p` option or the `COMPOSE_PROJECT_NAME` environment variable but IMHO would be useful to have in the `docker-compose.yml` something like `project_name: project1`.

My docker-compose.yml would become:

```
project_name: project1
web:
  image: fntlnz/nginx:1.6.2
  volumes:
    - ../:/var/www/project
  ports:
    - "127.0.0.2:80:80"
  links:
    - fpm:fpm

fpm:
  image: fntlnz/php-fpm:5.6.6
  volumes:
    - ../:/var/www/project
  links:
    - redis:redis

redis:
  image: redis
```

**Comment by dnephin** [comment]
Probably a duplicate of #45 (#463)  and #745

**Comment by mikehaertl** [comment]
+1 but agree, that this should be closed as duplicate of #45. I think #745 is a little different, no?

**Comment by fntlnz** [comment]
It is definitely a duplicate of #45

**Comment by isaac-weisberg** [comment]
Dawg this is such a basic feature

**Comment by Z-a-r-a-k-i** [comment]
Would it be so difficult to add the possibility of setting the project name directly from inside the docker-compose.yml file ?
I mean now that I put docker-compose.yml files everywhere in my projects like in some src folder, it's a bit painful to have to create a .env file all the time and I know that a lot of developers are facing the same problem.

**Comment by benjick** [comment]
> Right now we can use .env file with custom project name and set `COMPOSE_PROJECT_NAME=SOMEPROJECTNAME`

Not really helpful if you have several YAML files in the same directory that you wanna use different project names for. Can't believe this function doesn't exist.

```yaml
version: '3.8'
project_name: foo
services:
  ...
```

would be so nice

**Comment by f1ames0ff** [comment]
Any updates?

**Comment by glours** [comment]
@f1ames0ff the support was introduce in [compose-go v1.1.0](https://github.com/compose-spec/compose-go/releases/tag/v1.1.0) so it supported in Compose v2 [since version `v2.3.0`](https://github.com/docker/compose/releases/tag/v2.3.0)

**Comment by Z-a-r-a-k-i** [comment]
> @f1ames0ff the support was introduce in [compose-go v1.1.0](https://github.com/compose-spec/compose-go/releases/tag/v1.1.0) so it supported in Compose v2 [since version `v2.3.0`](https://github.com/docker/compose/releases/tag/v2.3.0)

Cannot find the information, could you be more explicit about "the support"?

Thank you!

**Comment by MatthewLymer** [comment]
@Z-a-r-a-k-i 

```yml
version: "3"
name: "MySuperUniqueProjectName"
services:
  my-container-name: ...
```
