### ISSUE TITLE
no configuration file provided: not found with ligne docker compose up

### ISSUE THREAD

**Issue by JeremyMAQUAIRE** [docker/compose#11264]
### Description

I’m in my file or my .yml.
I checked the extension it is ok but has the command docker compose up, it does not find my folder. Thank you for your help 

### docker-compose.yml
```yaml
version: "3"

services:
  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: ""
      SECRET: ""
      ADMIN_EMAIL: "jeremy.dev63@gmail.com"
      ADMIN_PASSWORD: ""
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true
      PUBLIC_URL: "https://api.gochasse.com"
```
### Steps To Reproduce
```
root@ecstatic-margulis:/var/www/vhosts/gochasse.com/api.gochasse.com/directus# docker compose up
no configuration file provided: not found
root@ecstatic-margulis:/var/www/vhosts/gochasse.com/api.gochasse.com/directus# docker compose logs
no configuration file provided: not found
root@ecstatic-margulis:/var/www/vhosts/gochasse.com/api.gochasse.com/directus# docker compose up -d
no configuration file provided: not found
```
### Compose Version

```Text
root@ecstatic-margulis:/var/www/vhosts/gochasse.com/api.gochasse.com/directus# docker compose version
Docker Compose version v2.17.2
```

### Docker Environment

```Text
root@ecstatic-margulis:/var/www/vhosts/gochasse.com/api.gochasse.com/directus# docker version
Client:
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.20.7
 Git commit:        297e128
 Built:             Wed Aug 23 20:54:23 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       5d6db84
  Built:            Wed Aug 23 20:55:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```[tasklist]
### Tasks
```
