### ISSUE TITLE
[BUG] The initiated health check process is missing

### ISSUE THREAD

**Issue by yangjinheng** [docker/compose#11326]
### Description

* new version
> Docker Compose version v2.23.3
Created -> Started -> Healthy                                      -> 0.0s

* old version
> Docker Compose version v2.20.2
Created -> Starting -> Waiting -> Healthy                   -> 0.1s  ~ 24.8s

### Steps To Reproduce

# services with healthcheck

```yaml
services:
  mysql:
    image: mysql:8.2.0
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=password
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_bin"]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 --password="password" --silent']
      interval: 10s
      timeout: 1m30s
      retries: 3
      start_period: 10s
    networks: ["quicknet"]
    volumes:
      - mysql:/var/lib/mysql
```

### Compose Version

```Text
Docker Compose version v2.23.3
```

### Docker Environment

```Text
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 102
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7880925980b188f4c97b462f709d0db8e8962aff
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-89-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.39GiB
 Name: quick03v.mm.bjat.qianxin-inc.cn
 ID: d40f05e5-9c64-49b5-8022-1cb433d49351
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Product License: Community Engine
```
