### ISSUE TITLE
[BUG] On V2.24.0 cannot overwrite services properties when merging

### ISSUE THREAD

**Issue by RobinBergmark** [docker/compose#11339]
### Description

When merging two compose files, I get this error: 

`cannont override services.web.networks`

First noticed this on a system running Amazon Linux, but I've been able to reproduce something similar locally. If I downgrade to version `2.23.3` I don't get this error and it runs. 

I've managed to simplify the compose file to something that can seems to be reproducible. 

### Steps To Reproduce

Create these two compose files: 

`docker-compose.base.yml`
```
version: "3.8"

networks:
  testnetwork:
    driver: bridge

services:
  web:
    container_name: something-server
    image: image
    command: ./runsomething.sh
    networks:
      - testnetwork
```

`docker-compose.override.yml`
```
version: "3.8"

networks:
  testnetwork:
    driver: bridge

services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    image: image
```

Run using command: `docker compose -f ./docker-compose.base.yml -f ./docker-compose.override.yml up -d`

Causes error: `cannont override services.web.networks`

Run exactly the same with v2.23.3 and I do not get the error.

### Compose Version

```Text
Docker Compose version v2.24.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.0
    Path:     /home/rbr/.docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 21
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-14-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 30.98GiB
 Name: rbr-XPS-15-7590
 ID: QOMF:IWXG:WWZI:WXQC:P4TZ:L7FM:TUP5:RWP6:I7FO:EWIA:VNZF:Y5EC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
