### ISSUE TITLE
[BUG] On V2.24.0 error is thrown when there is "." in the service name

### ISSUE THREAD

**Issue by ayeganyan-atl** [docker/compose#11336]
### Description

When there is "." (dot sign) in the service name the following error is reported while starting containers:
```
3 error(s) decoding:
* 'services[dx-ref-java-quarkus-im-postgres.postgres-db].ports[0]' expected a map, got 'string'
* 'services[dx-ref-java-quarkus-im-postgres.postgres-db].ports[1]' expected a map, got 'string'
* 'services[dx-ref-java-quarkus-im-postgres.postgres-db].volumes[0]' expected a map, got 'string'
```

This works:
```yaml
  postgres-db:
    image: "postgres:12.11"
    ports:
      - "5432"
    volumes:
      - ".:/hello"
```

This does not work:
```yaml
  dx-ref-java-quarkus-im-postgres.postgres-db:
    image: "postgres:12.11"
    ports:
      - "5432"
    volumes:
      - ".:/hello"
 ```

### Steps To Reproduce

1. Install `docker compose` v2.24.0
2. Add `docker-compose.yml` with the following content
```yaml
  dx-ref-java-quarkus-im-postgres.postgres-db:
    image: "postgres:12.11"
    ports:
      - "5432"
    volumes:
      - ".:/hello"
 ```
3. start docker compose with `docker compose up` command

### Compose Version

```Text
v2.24.0
```

### Docker Environment

```Text
lient:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.24.0)
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Authorization: pipelines
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a6
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 5.10.101
 Operating System: Alpine Linux v3.18 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.956GiB
 Name: df8c3911-f5e9-4948-9128-99f386ad5030-7d9fn
 ID: JCUJ:QIMR:NY4Y:N6X6:PGWP:DU7N:ZGJC:T5OC:LMGL:XE6H:SORV:JGDY
 Docker Root Dir: /var/lib/docker/165536.165536
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://10.28.14.25:5000/
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by erayaydin** [comment]
I dont know how related with this issue but when using "long syntax" on compose file its not throw decode error, only with short syntax.

This works:
```
test.tld:
    image: "postgres:16"
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - source: ./
        target: /hello
        type: bind
```
