### ISSUE TITLE
[BUG] Version 2.24.0 breaks overriding integer environment variable

### ISSUE THREAD

**Issue by richardalmee** [docker/compose#11353]
### Description

The environment variables set as integer values in the `docker-compose.override.yml` do not have the same format in the container as those set as integer values in the `docker-compose.yml`

### Steps To Reproduce

Reproduction
* Create a `docker-compose.yml` containing
  ```yaml
  services:
    hello:
      image: "hello-world"
      environment:
        HELLO: 1
  ```
* Run `docker compose config`
    * Both v2.23.3 and v2.24.0 output
      ```yaml
      name: demo_issue_dc
      services:
        hello:
          environment:
            HELLO: "1"
          image: hello-world
          networks:
            default: null
      networks:
        default:
          name: demo_issue_dc_default
      ```
* And a `docker-compose.override.yml` containing
  ```yaml
  services:
    hello:
      environment:
        HELLO: 3
  ```
* Run `docker compose config`
  * v2.23.3 outputs
    ```yaml
    name: demo_issue_dc
    services:
      hello:
        environment:
          HELLO: "3"
        image: hello-world
        networks:
          default: null
    networks:
      default:
        name: demo_issue_dc_default
    ```
  * v2.24.0 outputs
    ```yaml
    name: demo_issue_dc
    services:
      hello:
        environment:
          HELLO: '%!s(int=3)'
        image: hello-world
        networks:
          default: null
    networks:
      default:
        name: demo_issue_dc_default
    ```

### Compose Version

```Text
Docker Compose version 2.24.0
```

### Docker Environment

```Text
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 32
  Running: 22
  Paused: 0
  Stopped: 10
 Images: 90
 Server Version: 24.0.7
 Storage Driver: btrfs
  Btrfs:
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 71909c1814c544ac47ab91d2e8b84718e517bb99.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.7.0-zen3-1-zen
 Operating System: Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.08GiB
 Name: come-otaree
 ID: ZXZO:QUMT:HXD7:RJLF:3BZB:FI3N:VFFT:37BL:7BMG:LJMG:GBQX:UMUS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by Doable149** [comment]
All values that are not strings are impacted apparently : 

Result of `docker compose config unleash-proxy` : 

```yaml
services:
 unleash-proxy:
    environment:
      JSON_LOGGER: '%!s(bool=true)'
      LOG_LEVEL: debug
```

**Comment by dkadioglu** [comment]
I think, I have another situation, where integers are not merged correctly. Again, this happens with the compose files of Zabbix, as they use multiple compose files extending each other. I am only using the file https://github.com/zabbix/zabbix-docker/blob/6.4/docker-compose_v3_alpine_pgsql_latest.yaml, so I tested only with that one. This compose file extends services from the file https://github.com/zabbix/zabbix-docker/blob/6.4/compose_zabbix_components.yaml. 

When I run docker compose -f docker-compose_v3_alpine_pgsql_latest.yaml config with version 2.24.1, I get two possible errors, as there are only two locations in compose_zabbix_components.yaml, where ulimits.nproc is set:

```validating /home/alarm/composefiles/zabbix/docker-compose_v3_alpine_pgsql_latest.yaml: services.zabbix-proxy-mysql.ulimits.nproc must be a integer```

```validating /home/alarm/composefiles/zabbix/docker-compose_v3_alpine_pgsql_latest.yaml: services.zabbix-proxy-sqlite3.ulimits.nproc must be a integer```

However, as an example, one of the two sections, where ulimits.nproc is defined, looks like this and contains a valid integer:
```
version: '3.8'
services:
 zabbix-server:
  init: true
  ports:
   - "${ZABBIX_SERVER_PORT}:10051"
  restart: "${RESTART_POLICY}"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ${DATA_DIRECTORY}/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ${DATA_DIRECTORY}/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ${DATA_DIRECTORY}/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ${DATA_DIRECTORY}/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro   - ${DATA_DIRECTORY}/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:ro
  tmpfs: /tmp
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_srv
  networks:
   zbx_net_database:
     aliases:
      - zabbix-server
   zbx_net_backend:
     aliases:
      - zabbix-server
   zbx_net_frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
  stop_grace_period: 30s
#  cap_add:
#    - "NET_RAW"
  sysctls:
   - net.ipv4.ip_local_port_range=1024 64999
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
#   - net.ipv4.ping_group_range=0 1995
  labels:
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
```
