### ISSUE TITLE
[BUG] v2.24.0 fails on "Circular reference" error on extended services with dependencies

### ISSUE THREAD

**Issue by stekycz** [docker/compose#11358]
### Description

Docker Compose started failing recently on `Circular reference` error. It happens when I extended a service from another compose file which contains more service definitions (even those I am not suing in the specific place) and the new file states dependencies among services.

### Steps To Reproduce

1. Create a file `docker-compose-base.yml`
```yaml
services:
  a:
    image: busybox
  b:
    image: busybox
  c:
    image: busybox
```
2. Create file `docker-compose.yml`
```yaml
services:
  a:
    extends:
      file: ./docker-compose-base.yml
      service: a
  b:
    extends:
      file: ./docker-compose-base.yml
      service: b
    depends_on:
      a:
        condition: service_started
```
3. Run `docker compose create`
Example error I would get
```
Circular reference:
    b in docker-compose.yml
    extends a in docker-compose-base.yml
    extends c in docker-compose-base.yml
    extends a in docker-compose.yml
    extends c in docker-compose-base.yml
```

### Compose Version

```Text
2.24.0
```
