### ISSUE TITLE
[BUG] --no-path-resolution ineffective since 2.24.1 for extended services

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11377]
### Description

`docker compose config --no-path-resolution` no longer works since 2.24.1 for services that extend another one from a different file

### Steps To Reproduce

1. Create `compose.yaml`

```yaml

services:
  service:
    build: .
    volumes:
      - ./:/mnt

  extended:
    extends:
      file: another.yaml
      service: service

```

2. Create `another.yaml`

```yaml

services:
  service:
    build: .
    volumes:
      - ./:/mnt


```

3. Run the config command with docker compose 2.24.1

```console

$ docker compose config --no-path-resolution
name: bug
services:
  extended:
    build:
      context: /path/to/bug
      dockerfile: Dockerfile
    networks:
      default: null
    volumes:
      - type: bind
        source: /path/to/bug
        target: /mnt
        bind:
          create_host_path: true
  service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
    volumes:
      - type: bind
        source: ./
        target: /mnt
        bind:
          create_host_path: true
networks:
  default:
    name: bug_default

```

4. Run the config command with docker compose 2.23.3

```console

$ docker compose config --no-path-resolution
name: bug
services:
  extended:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
    volumes:
      - type: bind
        source: .
        target: /mnt
        bind:
          create_host_path: true
  service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
    volumes:
      - type: bind
        source: ./
        target: /mnt
        bind:
          create_host_path: true
networks:
  default:
    name: bug_default


```

5. Note the differences

- the context path for the build and the source path for the volume of the extended service are resolved 

### Compose Version

```Text
Docker Compose version v2.24.1
```
