### ISSUE TITLE
[BUG] (undocumented) breaking change for path resolution for chained extended services since 2.24.1

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11379]
### Description

Since 2.24.1 it appears that all `file`s from `extends` are relative to the main compose file, but please see how this change is a breaking one following the steps below.

### Steps To Reproduce

1. Create `compose.yaml`

```yaml

services:
  service:
    extends:
      file: dir/level1.yaml
      service: service

```

2. Create `dir/level1.yaml`

```yaml

services:
  service:
    extends:
      file: ${DIR:-.}/level2.yaml
      service: service

```

3. Create `dir/level2.yaml`

```yaml

services:
  service:
    build: ..

```

4. Run the config command with 2.23.3

```console

$ docker compose config
name: bug
services:
  service:
    build:
      context: /path/to/bug
      dockerfile: Dockerfile
    networks:
      default: null
networks:
  default:
    name: bug_default

```

5. Attempt to run the config command with 2.24.1

```console

$ docker compose config
cannot read ./level2.yaml

```

6. Apply the workaround and run the config command with 2.24.1

```console

$ DIR=dir docker compose config
name: bug
services:
  service:
    build:
      context: /path/to/bug
      dockerfile: Dockerfile
    networks:
      default: null
networks:
  default:
    name: bug_default

```

7. Note the issues

- it is a breaking change and without a "DIR"-like workaround it's not possible to have the same compose files working with old and new versions of compose
- it's also a confusing change since the context, for example, remains relative to the file where it's used

### Compose Version

```Text
Docker Compose version v2.24.1
```
