### ISSUE TITLE
[BUG] ulimits validation when using extends

### ISSUE THREAD

**Issue by Aposhian** [docker/compose#11396]
### Description

In 2.21, I had a compose file that I was extending that set `ulimits`. This fails validation in 2.24 with:
```
validating ./compose.yml: services.test.ulimits.core must be a integer
```
when the value is clearly an integer. This used to work, and if I revert to 2.21, it still works.

### Steps To Reproduce

Create two compose files: `base.yml` and `compose.yml`:
`base.yml`:
```yml
services:
  base:
    image: busybox
    ulimits:
      core: 10000
```
and `compose.yml`:
```yml
services:
  test:
    extends:
      file: base.yml
      service: base
```
Then run `docker compose up`, and get the following error:
```
validating ./compose.yml: services.test.ulimits.core must be a integer
```

### Compose Version

```Text
Docker Compose version v2.24.1
```

### Anything else?

Additionally, during validation, `-1` should be allowed for unlimited size.
