### ISSUE TITLE
[BUG] Regression when overriding networks

### ISSUE THREAD

**Issue by c-w** [docker/compose#11408]
### Description

In `v2.24.0` there is a regression when using an override file to reset a network to its default state. This used to work all the way up to `v2.23.3`.

My use-case for this scenario is to use a specific docker network name when running in production (using the  `docker-compose.yml` file) while using the auto-generated network name when running in development (using the `docker-compose.override.yml` file).

### Steps To Reproduce

1. Create `docker-compose.yml`

```yml
services:
  test:
    image: hello-world
    networks:
      test:

networks:
  test:
    name: test
    external: true
```

2. Create `docker-compose.override.yml`

```yml
networks:
  test:
```

3. Run `docker compose up` and observe exit code 15 with error message "cannot override networks.test"

### Compose Version

```Text
First broken version: v2.24.0
Last good version: v2.23.3
```

**Comment by ndeloof** [comment]
> using an override file to reset a network to its default state

this was not expected to "reset" network, but to merge definitions which would be a no-op - the only way to get something removed from compose model is to tag with `!reset` (https://github.com/compose-spec/compose-spec/blob/master/13-merge.md#reset-value) - so you were relying on a bug.

There's a bug here anyway, let me investigate to fix this, and also check how we could better support your use-case

**Comment by c-w** [comment]
Thanks for the pointer to `!reset`. I experimented with it.

As per the docs, I'd assume that the following snippet should work, but it throws an error on both v2.24.3 ("service "test" refers to undefined network test: invalid compose project") and v2.23.3 ("networks.test must be a mapping or null"):

```yml
networks:
  test: !reset null
```

The following snippet works with v2.24.3 but with v2.23.3 I get "can't override attribute Name".

```yml
networks:
  test:
    name: !reset null
    external: !reset false
```

**Comment by luciangabor** [comment]
Just in case the old behavior was a bug, this might help (it achieves the same result with both versions):

```yaml

networks:                              
  test:
    name: ${COMPOSE_PROJECT_NAME:?}_test
    external: false

```
(`!reset` deletes the item, it does not assign a value)
