### ISSUE TITLE
[BUG] occasional "service x has neither an image nor a build context specified: invalid compose project"

### ISSUE THREAD

**Issue by ahwatts** [docker/compose#11413]
### Description

Using the following compose file:

```yaml
---
name: compose-test

services:
  pisa-base:
    image: alpine

  pisa-worker-base:
    extends:
      service: pisa-base

  pisa-worker:
    extends:
      service: pisa-worker-base
```

and I run `docker compose config`, I sometimes get an error message:

```
service "pisa-worker" has neither an image nor a build context specified: invalid compose project
```

I don't always get it, but maybe 10% of the time I do. I find that running this bash command typically gets at least one failure:

```
awatts@ironic-mullet compose-test $ for d in {0..20}; do docker compose config > /dev/null; echo $?; done
0
0
service "pisa-worker" has neither an image nor a build context specified: invalid compose project
15
service "pisa-worker" has neither an image nor a build context specified: invalid compose project
15
service "pisa-worker" has neither an image nor a build context specified: invalid compose project
15
0
0
0
0
0
0
0
0
0
0
0
0
service "pisa-worker" has neither an image nor a build context specified: invalid compose project
15
service "pisa-worker" has neither an image nor a build context specified: invalid compose project
15
0
0
```

### Steps To Reproduce

1. In an otherwise empty directory, use the following `docker-compose.yml`:

```yaml
---
name: compose-test

services:
  pisa-base:
    image: alpine

  pisa-worker-base:
    extends:
      service: pisa-base

  pisa-worker:
    extends:
      service: pisa-worker-base
```

2. Run the following bash command:

```
for d in {0..20}; do docker compose config > /dev/null; echo $?; done
```

3. I usually get at least one failure in running it 20 times, typically 3-4 of the runs fail.

### Compose Version

```Text
awatts@ironic-mullet compose-test $ docker compose version
Docker Compose version v2.24.2

awatts@ironic-mullet compose-test $ docker-compose version
bash: docker-compose: command not found...
Install package 'docker-compose' to provide command 'docker-compose'? [N/y]
```

### Docker Environment

```Text
awatts@ironic-mullet compose-test $ docker info
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 26
  Running: 25
  Paused: 0
  Stopped: 1
 Images: 69
 Server Version: 25.0.1
 Storage Driver: btrfs
  Btrfs:
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.13-200.fc39.x86_64
 Operating System: Fedora Linux 39 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.08GiB
 Name: ironic-mullet.eminorinc.com
 ID: SHFE:UOOW:MKUA:56MY:UHUL:QTQP:YZJX:C43V:XR4R:67RF:BWKS:22EM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
