### ISSUE TITLE
[BUG] Path resolution in compose files inconsistent and wrong

### ISSUE THREAD

**Issue by Dekadee** [docker/compose#11412]
### Description

Just upgrade to v2.24.2 and ran into this issue.

When using `extends` with `file` in a file that is `include`d from a subfolder, the path to other files is now relative to the top file and not relative to the file that actually `extends` the other YAML file.

Additionally, when trying to mount files into the container, the path resolution is relative to the directory BELOW where the file is actually located.

This is an issue that seems to have been introduced somewhere between v2.21.0 and v2.24.2, as with v2.21.0 everything still runs as expected.

### Steps To Reproduce

1. Use `docker compose`  v2.24.2
2. Create a folder setup like so:

```
> test.yml
> subfolder
> > sub.yml
> > sub2.yml

> config
> > test.cfg
```

test.yml:
```
version: '2.4'
include:
 - subfolder/sub2.yml
```

sub.yml:
```
version: '2.4'
services:
  test_service:
    image: hello-world
    volumes:
      - ../config/test.cfg:/config/test.cfg
```

sub2.yml:
```
version: '2.4'
services:
  test_service:
    extends:
      file: ./sub.yml
      service: test_service
    cpuset: "0"
```
3. Run `docker compose -f test.yml up`

This causes an error: `cannot read ./sub.yml`

4. Change `sub2.yml` to this:
```
version: '2.4'
services:
  test_service:
    extends:
      file: ./subfolder/sub.yml
      service: test_service
    cpuset: "0"
```

5. Run `docker compose -f test.yml up` again
6. A folder `config`  appears in `subfolder`, because the path is getting resolved from one folder too deep.
7. Change `sub.yml` to this:
```
version: '2.4'
services:
  test_service:
    image: hello-world
    volumes:
      - ../../config/test.cfg:/config/test.cfg
```
8. Everything works now, but path resolving does not make any sense anymore.

### Compose Version

```Text
Docker Compose version v2.24.2
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 29
  Running: 4
  Paused: 0
  Stopped: 25
 Images: 12
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-92-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 125.5GiB
 Name: autera
 ID: fb90f387-ce6a-4326-94e8-96965ae08316
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
