### ISSUE TITLE
[BUG] Overwriting labels no longer working on v2.24.2

### ISSUE THREAD

**Issue by crwenner** [docker/compose#11417]
### Description

There appears to be an issue with overriding labels with the new compose version. I am getting the following error:
```
cannot override services.app.labels
```
This is happening in our linux environment, and does not happen when we revert to the previous version 2.23.3.

### Steps To Reproduce

Simplified docker-compose.yml file:
```yaml
version: "3.7"

services:
  app: 
    labels:
      sqm.app: "foo-name"
```
Simplified docker-compose.override.yml file:
```yaml
version: "3.7"

services:
  app:
    labels:
      - "traefik.docker.network=sqm_default"
      - "traefik.port=80"
```

Running the following command:
```bash
docker compose -f docker-compose.yml -f docker-compose.override.yml up -d
```

Produces this error while running v2.24.2 compose:
`cannot override services.app.labels`

### Compose Version

```Text
Docker Compose version v2.24.2
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```
