### ISSUE TITLE
[BUG] the build context resets to default when inherited and the extending service has other build attributes with compose v2.24.4

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11431]
### Description

Please see the steps below

### Steps To Reproduce

1. Create `compose.yaml`

```yaml

services:
  outer-base:
    extends:
      file: dir/file.yaml
      service: base
  outer-service:
    extends:
      file: dir/file.yaml
      service: service

```

2. Create `dir/file.yaml`

```yaml

services:
  base:
    build:
      context: ..
  service:
    extends: base
    build:
      target: target

```

3. Compare the output of the `config` command using docker compose v2.24.4 and v2.23.3

```console

$ # for example, by having v2.24.4 installed in the PATH and v2.23.3 installed as a plugin
$ docker-compose version
Docker Compose version v2.24.4
$ docker compose version
Docker Compose version v2.23.3
$ docker-compose config --no-path-resolution
name: bug
services:
  outer-base:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
  outer-service:
    build:
      context: dir
      dockerfile: Dockerfile
      target: target
    networks:
      default: null
networks:
  default:
    name: bug_default
$ docker compose config --no-path-resolution
name: bug
services:
  outer-base:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
  outer-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: target
    networks:
      default: null
networks:
  default:
    name: bug_default

```

Please note that with v2.23.3, the context is correctly resolved to `.` for both services, while with v2.24.4 for the `outer-service` the context is resolved to `dir` and please note that the difference is brought by the fact that the `service` has the additional `target` `build` attribute.

### Compose Version

```Text
Docker Compose version v2.24.4
```
