### ISSUE TITLE
[BUG] include and override features order problem

### ISSUE THREAD

**Issue by emirhanmarlali** [docker/compose#11482]
### Description

docker compose behavior is changed when using [include ](https://docs.docker.com/compose/multiple-compose-files/include/)and [merge ](https://docs.docker.com/compose/multiple-compose-files/merge/)features at same time on the latest minor version (**v2.24.***). 

When a service is defined in a included docker compose file. Trying override that service with a docker-compose.override.yml causes `services.foo conflicts with imported resource` error.

Works as it should on docker compose version **v2.23.3**.

As I understand I assume;
In v2.23.* files listed in `include` are joined first then `...*.override.yml` files are applied.
But in v2.24.* first `...*.override.yml` files are applied then files listed in `include` are joined.

Tested with docker compose versions v2.23.3, v2.24.0 and v2.24.5 and docker versions 24.0.7

[Test Results Repo](https://github.com/emirhanmarlali/dc-include-issue)

### Steps To Reproduce

.env
```bash
COMPOSE_PROJECT_NAME=demo
COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml
```
./docker-compose.yml
```yaml
include:
  - foo.docker-compose.yml

services:
  main:
    image: alpine
```

./foo.docker-compose.yml
```yaml
services:
  foo:
    image: ubuntu:latest
```

./docker-compose.override.yml
```yaml
services:
  foo:
    image: ubuntu:lunar
```

Command;

```
docker compose config
```

Output:

```
services.foo conflicts with imported resource
```

**Expected** Output:

```yaml
name: demo
services:
  foo:
    image: ubuntu:lunar
    networks:
      default: null
  main:
    image: alpine
    networks:
      default: null
networks:
  default:
    name: demo_default
```

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 43
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.34GiB
 Name: mmarlal-74G59Y3
 ID: cbc0d97b-e2a4-4a56-8818-b7f68162990f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```
