### ISSUE TITLE
[BUG] Variables interpolated in extension fields do not appear in instances

### ISSUE THREAD

**Issue by strophy** [docker/compose#11501]
### Description

I'm trying to interpolate variables from a `.env` file into a compose file with an extension block.
```
# .env
GW_CA_CERT=certs/ca.crt
GW_TELEGRAF_CERT=certs/telegraf.pem
GW_TELEGRAF_KEY=certs/telegraf.key
```

The compose file attempts to use an extension block to keep the code DRY for two almost identical services, differing only by a bind mount of a single config file:
```
version: "3.8"

x-telegraf: &telegraf
  image: telegraf:1.19.0
  volumes:
    - ./${GW_CA_CERT:?err}:/${GW_CA_CERT:?err}:ro
    - ./${GW_TELEGRAF_CERT:?err}:/${GW_TELEGRAF_CERT:?err}:ro
    - ./${GW_TELEGRAF_KEY:?err}:/${GW_TELEGRAF_KEY:?err}:ro

services:
  telegraf:
    <<: *telegraf
    volumes:
     - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-2:
    <<: *telegraf
    volumes:
     - ./config/telegraf-2.conf:/etc/telegraf/telegraf.conf:ro
```
Result of `docker compose --file docker-compose.broken.yml config`:
```
name: demo
services:
  telegraf:
    image: telegraf:1.19.0
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/leon/demo/config/telegraf.conf
        target: /etc/telegraf/telegraf.conf
        read_only: true
        bind:
          create_host_path: true
  telegraf-2:
    image: telegraf:1.19.0
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/leon/demo/config/telegraf-2.conf
        target: /etc/telegraf/telegraf.conf
        read_only: true
        bind:
          create_host_path: true
networks:
  default:
    name: demo_default
x-telegraf:
  image: telegraf:1.19.0
  volumes:
    - ./certs/ca.crt:/certs/ca.crt:ro
    - ./certs/telegraf.pem:/certs/telegraf.pem:ro
    - ./certs/telegraf.key:/certs/telegraf.key:ro
```
Notice that although the variables are correctly interpolated into the `x-telegraf` block, they do not appear in instances that use the referenced block with `<<: *telegraf`. I expect to see four bind mounts for each service, but only the explicitly defined bind mount appears in the `volumes` block. Why is this occurring? Am I using the interpolation and extension features incorrectly, or is this a bug?

It seems the extension is templated first, and the env file templated afterwards, and it is erroring silently when encountering the variables in the volumes section of the extension block, instead of templating them into instances referencing the extension and then interpolating variables.

### Steps To Reproduce

`.env` file
```
GW_CA_CERT=certs/ca.crt
GW_TELEGRAF_CERT=certs/telegraf.pem
GW_TELEGRAF_KEY=certs/telegraf.key
```

`docker-compose.broken.yml` file
```
version: "3.8"

x-telegraf: &telegraf
  image: telegraf:1.19.0
  volumes:
    - ./${GW_CA_CERT}:/${GW_CA_CERT}:ro
    - ./${GW_TELEGRAF_CERT}:/${GW_TELEGRAF_CERT}:ro
    - ./${GW_TELEGRAF_KEY}:/${GW_TELEGRAF_KEY}:ro

services:
  telegraf:
    <<: *telegraf
    volumes:
     - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-2:
    <<: *telegraf
    volumes:
     - ./config/telegraf-2.conf:/etc/telegraf/telegraf.conf:ro
```
`docker-compose.works.yml` file
```
version: "3.8"

services:
  telegraf:
    image: telegraf:1.19.0
    volumes:
      - ./${GW_CA_CERT:?err}:/${GW_CA_CERT:?err}:ro
      - ./${GW_TELEGRAF_CERT:?err}:/${GW_TELEGRAF_CERT:?err}:ro
      - ./${GW_TELEGRAF_KEY:?err}:/${GW_TELEGRAF_KEY:?err}:ro
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-2:
    image: telegraf:1.19.0
    volumes:
      - ./${GW_CA_CERT:?err}:/${GW_CA_CERT:?err}:ro
      - ./${GW_TELEGRAF_CERT:?err}:/${GW_TELEGRAF_CERT:?err}:ro
      - ./${GW_TELEGRAF_KEY:?err}:/${GW_TELEGRAF_KEY:?err}:ro
      - ./config/telegraf-2.conf:/etc/telegraf/telegraf.conf:ro
```

Create these three files in a directory and run:
`docker compose --file docker-compose.broken.yml config`
`docker compose --file docker-compose.works.yml config`

And notice the difference in output.

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.7.3-060703-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.25GiB
 Name: XPS-HNCG1T3
 ID: cc0b7e32-9a49-4e36-8dcb-bc29ab771e28
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by strophy** [comment]
I think my above example is not a problem with interpolation, but with the single explicitly declared bind mount overwriting the bind mounts declared in the extension. After reading the documentation more carefully, it seems I am actually trying to achieve what is shown in [example 4](https://docs.docker.com/compose/compose-file/11-extension/#example-4) of the Extensions section. I would like to achieve a merge of the volumes similar to this minimal example:
```
version: "3.8"

x-telegraf: &telegraf
  image: telegraf:1.19.0

x-telegraf-volumes: &telegraf-volumes
  - ./certs/ca.crt:/certs/ca.crt:ro
  - ./certs/telegraf.pem:/certs/telegraf.pem:ro
  - ./certs/telegraf.key:/certs/telegraf.key:ro

services:
  telegraf:
    <<: *telegraf
    volumes:
      <<: *telegraf-volumes
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-2:
    <<: *telegraf
    volumes:
      <<: *telegraf-volumes
      - ./config/telegraf-2.conf:/etc/telegraf/telegraf.conf:ro
```

However, as stated in the documentation, this likely isn't possible because "[YAML merge](https://yaml.org/type/merge.html) only applies to mappings, and can't be used with sequences." Because volumes are declared as an array (sequence), I will need to declare the four volume mappings explicitly for each of my containers in the compose file. Would love confirmation of this, or any suggestions of different methods to achieve this goal.

**Comment by ndeloof** [comment]
issue indeed isn't related to interpolation but to yaml merge operator. You apply a merge at service level, but the yaml merge doesn't know about the compose model and how to merge `volumes`.
@strophy solution will fix this issue, the other option is for you to use an  `extends`:

```yaml
services:
  telegraf-base: 
    scale: 0 # won't get actually ran
    image: telegraf:1.19.0
    volumes:
      - ./${GW_CA_CERT}:/${GW_CA_CERT}:ro
      - ./${GW_TELEGRAF_CERT}:/${GW_TELEGRAF_CERT}:ro
      - ./${GW_TELEGRAF_KEY}:/${GW_TELEGRAF_KEY}:ro


  telegraf:
    extends: telegraf-base
    volumes:
     - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  telegraf-2:
    extends: telegraf-base
    volumes:
     - ./config/telegraf-2.conf:/etc/telegraf/telegraf.conf:ro
```
