### ISSUE TITLE
Circular Reference Error in Docker Compose v2.24.5 with extends Feature

### ISSUE THREAD

**Issue by asmundskalevik** [docker/compose#11516]
### Description

After upgrading to Docker Compose version 2.24.5, I encountered a "Circular reference" error when using the extends feature across multiple docker-compose.yml files. This issue did not occur in version 2.24.2. The setup involves three Docker Compose files where one service extends from another, which in turn extends from a base service defined in another file. The intended behavior is to inherit configurations across these files without issues.

### Steps To Reproduce

Create three Docker Compose files (base.yaml, intermediate.yaml, final.yaml) with the following content:
**base.yaml:**
```
version: '3.8'
services:
  app_base:
    image: alpine
    command: ["echo", "Hello from Base Service"]
```

**intermediate.yaml:**
```
version: '3.8'
services:
  app_service:
    extends:
      file: base.yaml
      service: app_base
    environment:
      - APP_MODE=intermediate
```
**final.yaml:**
```
version: '3.8'
services:
  app_service:
    extends:
      file: intermediate.yaml
      service: app_service
    ports:
      - "8080:80"
```
Run docker compose -f final.yaml up with Docker Compose version 2.24.5-1.

**Expected Result:**
The service app_service starts up successfully, inheriting configurations from both base.yaml and intermediate.yaml.

Actual **Result:**
Received a circular reference error:
```
Circular reference:
  app_service in /path/to/final.yaml
  extends app_service in /path/to/final.yaml
```
  

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 10
  Paused: 0
  Stopped: 5
 Images: 130
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-18-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.08GiB
 Name: hi-07679
 ID: MNE3:34UN:ICEY:TH6C:JDAJ:SL7M:ONQF:AQ5J:ORRX:N46F:Q42L:OLD7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: aasmunds
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

The problem persists only with Docker Compose version 2.24.5-1. This issue significantly impacts development workflows that rely on the extends feature for modular and reusable service configurations.
