### ISSUE TITLE
[BUG] Regression between 2.24.5 and 2.24.6 relating to `depends_on`: 

### ISSUE THREAD

**Issue by freyjadomville** [docker/compose#11522]
### Description

With 2.24.6, the attached compose files stop working with the following message:
```
service "published-data-api" can't be used with `extends` as it declare `depends_on`
```

### Steps To Reproduce

Use 2.24.5 and verify that the compose files work as intended

Update to 2.24.6

Run the following compose files to receive the output described in the description section:

docker-compose.yml
```
version: '3.8'

services:
  postgres:
    image: postgres:15
    networks:
      - client-portal
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - portalpgdata:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    extends:
      file: docker-compose.excel.yml
      service: pgadmin
    networks:
      - client-portal
    depends_on:
      - postgres
      - data-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cms:
    build:
      dockerfile: cms/Dockerfile.dev
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - portalcmsmedia:/opt/app/public/uploads
      - ./cms/types:/opt/app/types
      - /opt/app/src/plugins # comment this line out (and the one below) to do plugin development
    ports:
      - '${CMS_API_PORT}:1337'
      #- '8000:8000' # uncomment this line (and the one above) to do plugin development and connect to localhost:8000
    environment:
      HOST: '0.0.0.0'
      PORT: '1337'
      CMS_URL: 'http://localhost:${CMS_API_PORT}'
      APP_KEYS: '<anonymised_key>'
      API_TOKEN_SALT: '<anonymised_key>'
      ADMIN_JWT_SECRET: '<anonymised_key>'
      JWT_SECRET: '<anonymised_key>'
      TRANSFER_TOKEN_SALT: '<anonymised_key>'
      DATABASE_CLIENT: 'postgres'
      DATABASE_HOST: 'postgres'
      DATABASE_PORT: '5432'
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: 'false'
      DATABASE_POOL_MIN: '0'
      NEXT_REVALIDATE_TOKEN: ${NEXT_REVALIDATE_TOKEN}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      STRAPI_SES_AWS_ACCESS_KEY_ID: ${STRAPI_SES_AWS_ACCESS_KEY_ID}
      STRAPI_SES_AWS_SECRET_ACCESS_KEY: ${STRAPI_SES_AWS_SECRET_ACCESS_KEY}
      IS_LOCAL: 'true'
      REPORTS_BUCKET: ${REPORTS_BUCKET}
      REPORTS_QUEUE: ${REPORTS_QUEUE}
      REGION: ${REGION}
      LOCALSTACK_ENDPOINT: 'http://host.docker.internal:4566'
      CMS_PREVIEW_TOKEN: ${CMS_PREVIEW_TOKEN}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_HOST: ${FRONTEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT}
    networks:
      - client-portal
    command: npm run develop # -- --watch-admin # uncomment this line for plugin development
    depends_on:
      - postgres
      - localstack
      - auth-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      target: develop
    volumes:
      - ./frontend:/usr/src/app
      - ./common-data-client:/usr/src/common-data-client
      - portalcmsmedia:/usr/src/app/public/uploads
      - /usr/src/app/.next
      - /usr/src/app/node_modules # Anonymous volume to prevent the container's node_modules from being overwritten by the local one
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
      - 0.0.0.0:9232:9229
      - 0.0.0.0:9233:9230
    environment:
      NODE_ENV: 'development'
      WATCHPACK_POLLING: 'true'

      PORT: ${FRONTEND_PORT}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      PUBLISHED_DATA_API_URL: ${PUBLISHED_DATA_API_URL}
      THOUGHTSPOT_HOST: ${THOUGHTSPOT_HOST}
      THOUGHTSPOT_SECRET_KEY: ${THOUGHTSPOT_SECRET_KEY}
      THOUGHTSPOT_DATA_SOURCE: ${THOUGHTSPOT_DATA_SOURCE}
      THOUGHTSPOT_OVERRIDE_SUBSCRIPTION: ${THOUGHTSPOT_OVERRIDE_SUBSCRIPTION}
      NEXTAUTH_URL: 'http://localhost:${FRONTEND_PORT}'
      NEXT_REVALIDATE_TOKEN: ${NEXT_REVALIDATE_TOKEN}
      NEXTAUTH_SECRET: '0CaFHo7J6Q9xzYRPkjtLn5FEmgLl7Cp86MJTVjEzuUI='
      MIXPANEL_PROJECT_TOKEN: ${MIXPANEL_PROJECT_TOKEN}
      RESPONSE_ROW_LIMIT: ${RESPONSE_ROW_LIMIT}
    networks:
      - client-portal
    command: npm run dev
    depends_on:
      - auth-service
      - cms
      - published-data-api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  auth-service:
    build:
      dockerfile: auth-service/Dockerfile
      target: development
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume to prevent the container's node_modules from being overwritten by the local one
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
      - '9231:9229' # debug port
    environment:
      LOCALSTACK_ENDPOINT: 'http://host.docker.internal:4566'
      IS_LOCAL: 'true'
    env_file:
      - .env
    networks:
      - client-portal
    command: npm run start:debug
    depends_on:
      opensearch:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: portal-opensearch
    environment:
      - compatibility.override_main_response_version=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./auth-service/src/opensearch/synonyms:/usr/share/opensearch/config/analysis
    ports:
      - ${OPENSEARCH_PORT_1}:9200 
      - ${OPENSEARCH_PORT_2}:9600
    networks:
      - client-portal
    healthcheck:
      test: "curl -s http://opensearch:9200 > /dev/null || exit 1"
      interval: 2s
      timeout: 30s
      retries: 50
      start_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: portal-opensearch-dashboards
    ports:
      - 0.0.0.0:${OPENSEARCH_DASHBOARDS_PORT}:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - client-portal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  localstack:
    image: localstack/localstack:2.3.2
    hostname: localstack
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "http://_localstack/health?reload" ]
    environment:
      - SERVICES=s3,sqs,sns
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/tmp/localstack:rw
      - ./setup/entrypoints/create_localstack_resources.sh:/etc/localstack/init/ready.d/init-aws.sh
  
  published-data-api:
    extends:
      file: docker-compose.excel.yml
      service: published-data-api
    networks:
      - client-portal
    depends_on:
      - data-postgres

  data-postgres:
    extends:
      file: docker-compose.excel.yml
      service: data-postgres
    networks:
      - client-portal

  tracking-opensearch:
    extends:
      file: docker-compose.excel.yml
      service: opensearch
    networks:
      - client-portal

  tracking-opensearch-dashboards:
    extends:
      file: docker-compose.excel.yml
      service: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://tracking-opensearch:9200"]
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - client-portal
    
  mock-auth-server:
    extends:
      file: docker-compose.excel.yml
      service: mock-auth-server
    networks:
      - client-portal

networks:
  client-portal:
  published-data:
volumes:
  portalpgdata:
  portalpgadmin:
  portalcmsmedia:
  opensearch-data:
  localstack-data:
  pgdata:
  pgadmin:
  tracking-opensearch-data:

```

docker-compose.excel.yml
```
version: '3.7'

services:
  published-data-api:
    build:
      dockerfile: published-data-api/Dockerfile
      target: development
    cpus: 1
    mem_limit: 2048m
    shm_size: 2gb
    volumes:
      - ./published-data-api:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume to prevent the container's node_modules from being overwritten by the local one
    ports:
      - ${PUBLISHED_API_PORT}:${PUBLISHED_API_PORT}
      - '9229:9229'
    env_file:
      - .env
    networks:
      - published-data
    command: npm run start:debug
    depends_on:
      - data-postgres

  data-postgres:
    image: postgres:14
    cpus: 2
    mem_limit: 4096m
    shm_size: 4gb 
    networks:
      - published-data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - published-data
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT}:80'

  mock-auth-server:
    image: mocksserver/main
    networks:
      - published-data
    volumes:
      - type: bind
        source: ./mocks-server
        target: /input
    environment:
      MOCKS_FILES_WATCH: true
    ports:
      - 3100:3100
      - 3110:3110

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      - compatibility.override_main_response_version=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - tracking-opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - published-data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: opensearch-dashboards
    ports:
      - 0.0.0.0:5601:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - published-data
networks:
  published-data:
volumes:
  pgdata:
  pgadmin:
  tracking-opensearch-data:

```

### Compose Version

```Text
Docker Compose version 2.24.6

Docker Compose version 2.24.6
```

### Docker Environment

```Text
Client:
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.12.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.6
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 0
  Paused: 0
  Stopped: 15
 Images: 83
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7c3aca7a610df76212171d200ca3811ff6096eb8.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.17-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.06GiB
 Name: 67-bricks-freyja
 ID: 3PGQ:JXX3:3KCV:6L47:7RGR:JKQJ:LHKF:XTTJ:MLQ6:JD5W:AWJJ:RYUU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
