### ISSUE TITLE
[BUG] `.env` file relative to command location instead of project

### ISSUE THREAD

**Issue by ifellinaholeonce** [docker/compose#11531]
### Description

We have a project with multiple submodules all within an orchestration directory. We recently updated Docker (Docker Desktop Mac version to`v4.27.2` from `4.25.1`) and have noticed a change in how our `.env` is loaded during build.

Dir Structure
```
/orchestration/
 - submodule1/
   - app/
   - Dockerfile
   - .env
 - submodule2/
   - app/
   - Dockerfile
   - .env
 - docker-compose.yml
 - .env 
```
docker-compose.yml
```
version: "3"
services:
  api:
    extends:
      file: common-services.yml
      service: api_common
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
 ```
common-services.yml
```
version: "3"
services:
  api_common:
    image: api:latest
    build:
      context: submodule1
      args:
        MY_VAR: ${MY_VAR}
    environment:
      - PGUSER=${USER:-postgres}
      - PGHOST=postgres
      - PGPORT=5432
      - REDIS_URL=redis://redis:6379
    env_file:
      - submodule1/.env
      - submodule1/.env.shared

```

Previously we were able to run `docker-compose build` from any of the subdirectories and `MY_VAR` was correctly read from `orchestration/.env`. However, since updating to `v4.27.2` this variable will only be set if the command is run from `orchestration` and not from within a submodule.

Is this change in behaviour expected? Is there anyway we can get this back?

### Compose Version

```Text
Docker Compose version v2.24.5-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/tymm/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     /Users/tymm/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/tymm/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/tymm/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/tymm/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/tymm/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/tymm/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/tymm/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     /Users/tymm/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/tymm/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/tymm/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.658GiB
 Name: docker-desktop
 ID: cb5d60aa-25d0-476b-8aac-40e4ba6f509f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
