### ISSUE TITLE
[BUG] include doesn't support Extensions

### ISSUE THREAD

**Issue by DennisGaida** [docker/compose#11541]
### Description

Extensions seem not to be supported with `include` and I can't find any documentation (https://docs.docker.com/compose/compose-file/11-extension/) that says so or any workarounds to have working extensions in included files.

The use case is to have extensions in the "base" compose and use these extensions in the included compose files - just like you can do for e.g. `secrets`.

### Steps To Reproduce

docker-compose.yml
```yaml
version: '3.7'

x-common-keys: &common-keys
  restart: always

include:
  - docker-compose-included.yml
```
docker-compose-included.yml
```yaml
version: '3.7'
services:
  server:
    image: alpine
    <<: *common-keys
    entrypoint: printenv
```

result:
```
$ docker compose up
yaml: unknown anchor 'common-keys' referenced
```

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
