### ISSUE TITLE
[BUG] the build context resets to default when overriding via include

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11546]
### Description

Please see the steps below

### Steps To Reproduce

1. Create `dir/services.yaml` and `dir/optional.yaml`

```yaml

# dir/services.yaml
services:
  service:
    build:
      context: ..
    volumes:
      - ..:/tmp

```

```yaml

# dir/optional.yaml
services:
  service:
    build:
      args:
       ARG:

```

2. Create `compose.yaml` and `compose.override.yaml`

```yaml

# compose.yaml
include:
  - path:
      - dir/services.yaml

```

```yaml

# compose.override.yaml
include:
  - path:
      - dir/optional.yaml

```

3. Observe the output of the `config` command

```console

$ docker compose config
name: override-via-include
services:
  service:
    build:
      context: /path/to/override-via-include/dir
      dockerfile: Dockerfile
      args:
        ARG: null
    networks:
      default: null
    volumes:
      - type: bind
        source: /path/to/override-via-include
        target: /tmp
        bind:
          create_host_path: true
networks:
  default:
    name: override-via-include_default

```

Note that the build context is equivalent to `./dir`, while the (reference) bind source matches `.`, despite being identically defined in `dir/services.yaml`

The problem disappears if the override file directly overrides the service:

```console

$ cp dir/optional.yaml compose.override.yaml
$ cat compose.override.yaml
services:
  service:
    build:
      args:
       ARG:

$ docker compose config
name: override-via-include
services:
  service:
    build:
      context: /path/to/override-via-include
      dockerfile: Dockerfile
      args:
        ARG: null
    networks:
      default: null
    volumes:
      - type: bind
        source: /path/to/override-via-include
        target: /tmp
        bind:
          create_host_path: true
networks:
  default:
    name: override-via-include_default

```

The problem also disappears when extending the `dir/optional.yaml` services instead of including them:

```console

$ cat > compose.override.yaml <<'EOF'
services:
  service:
    extends:
      file: dir/optional.yaml
      service: service
EOF

$ docker compose config
name: override-via-include
services:
  service:
    build:
      context: /path/to/override-via-include
      dockerfile: Dockerfile
      args:
        ARG: null
    networks:
      default: null
    volumes:
      - type: bind
        source: /path/to/override-via-include
        target: /tmp
        bind:
          create_host_path: true
networks:
  default:
    name: override-via-include_default

```

### Compose Version

```Text
Docker Compose version v2.24.6
```

### Anything else?

It's a bit similar with #11431

**Comment by ndeloof** [comment]
The reason you get this is that `include` process compose resources from a (reusable) compose model, which has been fully resolved. So your `optional.yaml` get (default) build context path set to `.` (inside `dir`)

**Comment by luciangabor** [comment]
What if `dir/optional.yaml` from the initial example would contain:

```yaml

services:
  service:
#    build:
#      args:
#       ARG:
    environment:
      VAR:

```

If included, is it supposed to be in any way full?
But, I can live with duplicating the build contex ... should this issue be closed?

Based on what compose adds as defaults, given the simplest build definition I can find, the build context is the only "culprit":

```console

$ docker compose -f - config <<EOF
services:
  service:
    build:
      pull: true
EOF
name: default
services:
  service:
    build:
      context: /path/to/default
      dockerfile: Dockerfile
      pull: true
    networks:
      default: null
networks:
  default:
    name: default_default

```

I've checked and the dockerfile and the networks would be the ones I can define elsewhere.
