### ISSUE TITLE
[BUG] service can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by r3nor** [docker/compose#11544]
### Description

When trying to bring up a compose project that makes use of `extends` feature, I am getting the following error:

```
service "nginx" can't be used with `extends` as it declare `depends_on`
```

### Steps To Reproduce

1. Have a docker-compose.yml project with extends, like this:

```
nginx:
    extends:
      file: ./nginx/compose.yml
      service: nginx
    container_name: "${SERVER_NAME:}-nginx"
    env_file: .env
```

and the nginx/compose.yml:

```
version: "3.9"

services:
  nginx:
    image: nginx:1
    restart: unless-stopped
    depends_on:
      - web_app
    volumes:
      - ./html:/var/www/html
```

2. `docker compose up`

3. See error: service "nginx" can't be used with `extends` as it declare `depends_on`

### Compose Version

```Text
2.24.6
```

### Docker Environment

```Text
N/A
```

**Comment by ndeloof** [comment]
This is the expected behavior, see https://github.com/compose-spec/compose-spec/blob/master/05-services.md#restrictions

**Comment by meriouma** [comment]
This seems to be a new restriction added in 2.24.6. We have an `extends` combined with `depends_on` and everything was working fine with 2.25.2 and previous versions. Not sure why this wasn't flagged as a breaking change?

**Comment by r3nor** [comment]
Yeah, same for me. Was working fine on `2.24.5` and broke on this new `2.24.6` release.

**Comment by meriouma** [comment]
This makes reusing blocks much harder, as fragments cannot be used across files. As far as I know, using `extends` was the only way to have reusable `depends_on` blocks while allowing to separate services in multiple files and have a common file to extend from.

**Comment by r3nor** [comment]
@meriouma maybe you want to check out include: https://docs.docker.com/compose/compose-file/14-include/

**Comment by nhorton** [comment]
> @meriouma maybe you want to check out include: https://docs.docker.com/compose/compose-file/14-include/

That is not sufficient. It is common to do stuff like have an image like "background worker" and then have 3 instances of it - high-pri, medium-pri, and low-pri. You could then have the base depend on stuff like your DB and message bus and such, then just have 3 instances that extend the base. Now you have to repeat those dependencies over and over in the instantiations. This is definitely more degradation in compose.

We have used Compose for development purposes with a Kubernetes cluster for deployment. It deeply feels like Compose has been losing functionality while Kubernetes has been gaining it, and Kind is becoming more and more compelling to replace Compose from these sorts of things.

**Comment by davidlougheed** [comment]
encountering this too. why is a breaking change being included in a patch release at all?

**Comment by davidlougheed** [comment]
what's also frustrating here is that everything used to work as-intended before compose 2.24 and its use of a not-even-prod-ready compose-go project, but there wasn't really a clear alert that everything was going to break.

**Comment by Leonid99** [comment]
> This is the expected behavior, see https://github.com/compose-spec/compose-spec/blob/master/05-services.md#restrictions

@ndeloof So, what is the supported way of extending services that depend on other services?

**Comment by ndeloof** [comment]
@Leonid99 there's no way currently

**Comment by luciangabor** [comment]
It's possible to merge depends_on "later":

```console

$ find *.yaml -print -exec cat {} \;
compose.yaml
include:
  - path:
      - defs.yaml
      - deps.yaml
defs.yaml
services:
  x:
    image: x

  y:
    image: y
#    depends_on:
#      - x

  z:
   extends: y
deps.yaml
services:
  y:
    depends_on:
      - x

```

```console

$ docker compose config
name: deps
services:
  x:
    image: x
    networks:
      default: null
  "y":
    depends_on:
      x:
        condition: service_started
        required: true
    image: "y"
    networks:
      default: null
  z:
    image: "y"
    networks:
      default: null
networks:
  default:
    name: deps_default

```

**Comment by luciangabor** [comment]
... and if you want to "inherit" the depends_on, `deps.yaml` could be like this:

```yaml
services:
  y: &idem
    depends_on:
      - x
  z: *idem

```

**Comment by pironim** [comment]
Got this error with ubuntu update 

from docker-compose-plugin (2.24.6-1~ubuntu.22.04~jammy) 
to (2.24.5-1~ubuntu.22.04~jammy)

**Comment by ndeloof** [comment]
sure, but the same applies to other resources, without such a constraint:

file.yaml
```yaml
services:
  service:
    image: image
    volumes:
      - hidden:/work

volumes:
  hidden: ...
```

**Comment by luciangabor** [comment]
about that, extending services defined like this: https://docs.docker.com/compose/compose-file/05-services/#ipv4_address-ipv6_address doesn't work either, but it's not caught by checks if there's a homonym network around

**Comment by ndeloof** [comment]
that's my point: consistency check just validate there's a resource for any declared reference, whenever this might not have been declared in the original compose file. As we already do for networks/volumes, I don't see any reason we don't do the same for dependent services

**Comment by Leonid99** [comment]
The problem with this approach is that if more than one service derives
from the base service (and this is always the case — why would you go into
the effort of sharing functionality if there is just one service), you will
need to copy-paste the “depends_on” stanza into each one.
Also, if there is more than one service in the derivation chain, it will
make the derived services unusable on their own, i.e. consider a situation
where you have service “x" extending service “y" which extends service “z”,
all of which depend on the service “foo”. This change moves the “depends_on
foo” logic from z to x. Before this change, you could happily start a
container with services z and y, while after the change, only service x is
usable.

**Comment by davidlougheed** [comment]
hmm I removed my `extends` in favour of includes + merging and now I get bizarre network errors where services are not joining some (but not all) of the declared networks, leading to name resolution errors. maybe related, or maybe not

**Comment by felipecrs** [comment]
This is the cleanest solution I found for this issue:

```yaml
services:
  app-abstract:
    image: nginx
    profiles: [abstract]
  app-1:
    extends: app-abstract
    profiles: !reset []
    depends_on: ...
  app-2:
    extends: app-abstract
    profiles: !reset []
    depends_on: ...
```

But it's far from ideal having to add and reset `profiles` like this, not to mention VS Code does not like the `!reset` thing.

This is to say that there is no clean solution for this issue, one that would still allow to extend services within the same compose file without having to create extra compose files.

Perhaps, @ndeloof, you can consider allowing services to be marked as `abstract: true`. Such services would not be rendered by docker compose, they'd rather just be useful for other services extend from.
