### ISSUE TITLE
[BUG] Env vars of included compose files are being overwritten by those of the main compose file if they share the same name

### ISSUE THREAD

**Issue by martinwittmann** [docker/compose#11560]
### Description

When using docker compose's include feature and using .env files for the main compose file and the included compose file, env vars from the main compose file are being applied to the included compose file if the variables have the same name.

### Steps To Reproduce

When using the following setup:

### Directory structure:
├─ includes
│  ├─ .env
│  └─ included.yml
├─ .env
└─ docker-compose.yml

.env
```
TEST_VAR=project
``` 

docker-compose.yml
```
version: '3.8'

include:
  - path: ./includes/included.yml

services:
  app:
    image: hello-world

``` 

includes/.env
```
NAME:included
``` 

includes/included.yml
```
version: '3.8'

services:
  proxy:
    image: hello-world
    container_name: ${TEST_VAR}
``` 
 

...the output of docker compose config is this:

```
name: docker
services:
  app:
    image: hello-world
    networks:
      default: null
  proxy:
    container_name: project
    image: hello-world
    networks:
      default: null
networks:
  default:
    name: docker_default

``` 

## Expected result vs actual result
The container_name of the proxy service should have a value of "included" but it has a value of "project".

According to the documentation (https://docs.docker.com/compose/compose-file/14-include/) docker compose defaults to use the .env file in the same directory as the included yml file.

This seems to be true but *if* the .env file in the project root contains variables with the same name as the included yml's .env file, the values from the .env in project root are being used.

The correct value is being used if there is no variable with the same name in the project root's .env file.

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.12.1)
  compose: Docker Compose (Docker Inc., v2.24.5)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 145
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.10-76060610-generic
 Operating System: Pop!_OS 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.33GiB
 Name: pop-os
 ID: MVF6:RETN:VQSY:T4CD:VLIU:534F:IFSM:BOL7:RPA2:P2OS:INUK:NF3J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
