### ISSUE TITLE
[BUG] including files with a custom project directory breaks when compose is run from a nested folder

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11573]
### Description

Please see the steps below.

### Steps To Reproduce

1. With these `compose.yaml`, `dir/included.yaml` and `dir/extended.yaml` files:

```yaml

---
# compose.yaml
include:
  - project_directory: .
    path: dir/included.yaml

---
# dir/included.yaml
services:
  included:
    extends:
      file: dir/extended.yaml
      service: extended

---
# dir/extended.yaml
services:
  extended:
    image: image

```

2. Observe the output of the `config` command when ran from `.` or `dir`:

```console
$ docker compose config 
name: proj-dir
services:
  included:
    image: image
    networks:
      default: null
networks:
  default:
    name: proj-dir_default

$ env -C dir docker compose config 
cannot read dir/extended.yaml

```

### Compose Version

```Text
Docker Compose version v2.24.6
```

### Anything else?

Furthermore, in case of "double extends", I mean if `dir/extended.yaml` would look ... "as expected" ... like this:

```yaml

services:
  extended:
    extends:
      file: dir/base.yaml
      service: base

```

with `dir/base.yaml` like this:

```yaml
services:
  base:
    image: image

```

it would lead to:

```console

$ docker compose config
cannot read dir/dir/base.yaml

```

Which could be fixed by mixing both ways of referring to files in `dir`, but ... I guess this has to wait and see if the very first extend was indeed supposed to be relative to the customized project directory anyway ...
