### ISSUE TITLE
Healthchecks dependent on health status of depends_on

### ISSUE THREAD

**Issue by zmweske** [docker/compose#11582]
### Description

Hi, I was thinking it would be nice for a container that utilizes the depends_on and healthcheck attributes to report healthy only if all containers it depends on are healthy/running. 

```yaml
services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    healthcheck:
      ...
      depends_on:
        db:
          condition: service_healthy
  db:
    image: postgres
    healthcheck:
      ...
  redis:
    image: redis
```

Thoughts would be appreciated, and sorry if this has already been addressed, I did some digging around between here and [compose-spec](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#healthcheck) and many docs pages but there were so many places this could have been addressed that I couldn't search everything. 

Thanks
