### ISSUE TITLE
Add support for healthcheck on test failure command execution

### ISSUE THREAD

**Issue by ghevge** [docker/compose#11588]
### Description

Currently the healthcheck mechanism only offers support to update the status of the container. There is no native way of triggering any action on that container, in case a problem is detected. 

Will it be possible to add a parameter on the healthcheck tag to allow the passing of commands to be executed when healthcheck is failing? Something like "on_test_failure". 

IMO implementing such a functionality, should not be difficult, as it will be just a matter of using the same logic used to execute the "test", but this time, it will be executed only when the healthcheck is failing.

This will allow the implementation of containers restart mechanism, without relying on cron jobs or any other tricks to achieve this. 

Thanks

```
    healthcheck:
      test: curl -f http://localhost/system/healthcheck
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 2m
      on_test_failure: <user command here>
```
