### ISSUE TITLE
Add compose up `--no-start-exited` option

### ISSUE THREAD

**Issue by pavetok** [docker/compose#11590]
#### Problem

```yaml
services:
  db:
    ...
  migration:
    depends_on:
      db:
        condition: service_healthy
    ...
  app:
    depends_on:
      migration:
        condition: service_completed_successfully
    ...
```

Migration container started every time `docker compose up` fired. Even though there are no changes at all.
Ideally migration container started only when it created or recreated.

#### Possible interfaces

1. Add new option `--no-restart`
2. Add new option `--no-start-exited`
3. Generalize existing option `--no-start string` where string = {{.State.Status}}
4. ...
