### ISSUE TITLE
[BUG] Services in included compose files are not brought up with `docker compose up`

### ISSUE THREAD

**Issue by davidlougheed** [docker/compose#11609]
### Description

To get around the restrictions/issues with 2.24 in https://github.com/docker/compose/issues/11568, I have switched from using `extends:` to have a structured multi-file compose project to `includes:`. However, when I run `docker compose up`, services in the included files are not brought up. I don't see much documentation about this, and I'm not sure how I'd go about including these into the compose project. The `include` terminology implies, to me, that this should work, but I guess these are treated as separate somehow and thus are not brought up?

### Compose Version

```Text
Docker Compose version v2.24.7
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

**Comment by luciangabor** [comment]
Could you give more info? Did you use profiles? (with profiles you'd have to `docker compose --profile <profile name or '*'> up`

**Comment by davidlougheed** [comment]
No profiles were used for the included services. It's a bit complex to illustrate the setup we have, but essentially there's a main compose file which defines an NGINX gateway, with various services included. The gateway doesn't specify `depends_on` for services it proxies, since it uses dynamic resolution:

```
include:
  - path: $PWD/lib/aggregation/docker-compose.aggregation.yaml
  - path: $PWD/lib/authz/docker-compose.authz.yaml
  - path: $PWD/lib/drs/docker-compose.drs.yaml
  - path: $PWD/lib/katsu/docker-compose.katsu.yaml
  - path: $PWD/lib/reference/docker-compose.reference.yaml
  - path: $PWD/lib/web/docker-compose.web.yaml
  - path: $PWD/lib/wes/docker-compose.wes.yaml

services:
  gateway:
    # ...
```

**Comment by luciangabor** [comment]
Maybe try this way to include them:

```yaml

include:
  - path:
      - lib/aggregation/docker-compose.aggregation.yaml
      - lib/authz/docker-compose.authz.yaml
      - lib/drs/docker-compose.drs.yaml
      - lib/katsu/docker-compose.katsu.yaml
      - lib/reference/docker-compose.reference.yaml
      - lib/web/docker-compose.web.yaml
      - lib/wes/docker-compose.wes.yaml

```

If they are under different `path`s they're not merged together. Also, due to the same rules, the included files cannot merge with the services from the compose.yaml file itself.
You definitely don't want the PWD, which is just a shell/posix variable, "say" where are those files located in relation to the main compose.yaml file.

You can always check the resulting yaml with `docker compose config`.
