### ISSUE TITLE
[BUG] Ports duplicated when using extends

### ISSUE THREAD

**Issue by kierans** [docker/compose#11611]
### Description

When using `extends` on a service between two `docker-compose.yaml` files, the `ports` array is duplicated/merged resulting in an array where ports are listed twice. Therefore, when booting the container Docker complains about `bind: address already in use`

I’m using [Devcontainers][1] for this project, so I have the base project Compose config and a developer specific config

[1]: https://containers.dev/

### Steps To Reproduce

```yaml

# docker-compose.yaml

version: '3.8'

services:
  my-service:
    build:
      context: .
      target: service
    depends_on:
      - db
    ports:
      - "8080:8080"
```

```yaml

# .devcontainer/docker-compose-dev.yaml

version: '3.8'

services:
  my-service:
    extends:
      file: docker-compose.yaml
      service: my-service
    build:
      target: dev
    volumes:
      - .:/app
```

Looking at the config, the port mapping of `8080` is duplicated

```shell
$ cd .devcontainer
$ docker compose -f ../docker-compose.yaml -f docker-compose-dev.yaml config | less
```

```yaml
ports:
  - mode: ingress
    target: 8080
    published: "8080"
    protocol: tcp
  - mode: ingress
    target: 8080
    published: "8080"
    protocol: tcp
```

When the container launches, I get the error

```
...
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8080 -> 0.0.0.0:0: listen tcp 0.0.0.0:8080: bind: address already in use
```

### Compose Version

```Text
Docker Desktop 4.27.2
Docker Compose version v2.24.5-desktop.1
```

### Anything else?

This does work properly in `Docker Desktop 4.26` (`Docker Compose version v2.23.3-desktop.2`)
