### ISSUE TITLE
[BUG] `include` not resolving relative path correctly since `v2.24.7`

### ISSUE THREAD

**Issue by aboqasem** [docker/compose#11613]
### Description

`include` paths now depend on where you are running the command from.

### Steps To Reproduce

Run `docker compose -f main/compose.yml config`:

```
.
├── another_nested
│   └── compose.yml
├── main
│   └── compose.yml
└── nested
    └── compose.yml
```

```
File: another_nested/compose.yml
version: '3.9'

services:
  two:
    image: alpine

File: main/compose.yml
version: '3.9'

include:
  - ../nested/compose.yml

services: { }

File: nested/compose.yml
version: '3.9'

include:
  - ../another_nested/compose.yml

services: { }
```

In `v2.24.6`:

```
name: main
services:
  two:
    image: alpine
    networks:
      default: null
networks:
  default:
    name: main_default
```

In `v2.24.7`:

```
open ../another_nested/compose.yml: no such file or directory
```

But if you:

- Run `(cd main && docker compose config)`
- Or change `../another_nested/compose.yml` to `./another_nested/compose.yml`

It would work

### Compose Version

```Text
Docker Compose version v2.24.7
```

### Docker Environment

```Text
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/user/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6
    Path:     /Users/user/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/user/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/user/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/user/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/user/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/user/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/user/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/user/.docker/cli-plugins/docker-scout

Server:
 Containers: 32
  Running: 0
  Paused: 0
  Stopped: 32
 Images: 52
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 4.803GiB
 Name: docker-desktop
 ID: 35097c99-adf9-415d-89ff-7f45df5dfc01
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
