### ISSUE TITLE
[BUG] including files with a custom project directory is ... just broken in 2.25.0

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11626]
### Description

Extras from https://docs.docker.com/compose/compose-file/14-include/#project_directory
> project_directory defines a base path to resolve relative paths set in the Compose file. It defaults to the directory of the included Compose file.

This was broken even before, due to being applied ... "blindly" (see https://github.com/docker/compose/issues/11573 - I think it shouldn't apply to elements that define yaml "structure" - something that "brings" behavior).

Yet, with 2.25.0 it is simply ignored in the cases it actually worked before.
I've tried with env files, with bind mounts and build contexts.

### Steps To Reproduce

Including this:

```yaml

services:
  service:
    build:
      dockerfile_inline: |
        FROM busybox
        COPY /something /
    volumes:
      - type: bind
        source: something
        target: /mnt/bind
    env_file:
      - env

```

with a project directory set to a directory that contains an `env` file and a file or directory named `something` used to work

### Compose Version

```Text
Docker Compose version v2.25.0
```

**Comment by mint-jar** [comment]
I can confirm it is broken for me as well. Workaround for me is to downgrade to 2.24.7

```yaml
include:
    -   path:
            - docker/compose-hub.yml
        project_directory: .
```

```yaml
services:
    app-definition:
        build:
           dockerfile: ./docker/project/Dockerfile
```

v2.25.0 -> error: `could not find ../docker/docker/project: stat ../docker/docker/project no such file or directory`

v2.24.7 -> no error
