### ISSUE TITLE
[BUG] Docker Compose config doesn't honor format parameter

### ISSUE THREAD

**Issue by mhalbritter** [docker/compose#11651]
### Description

Hello,

since Docker Compose 2.25.0, `docker compose config` doesn't seem to honor the `format` parameter.

### Steps To Reproduce

With this config:

```yaml
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
```

running

```
docker compose --file compose.yaml --ansi never config --format=json
```

gives me:

```yaml
name: sb-40060
services:
  postgres:
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    image: postgres:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        protocol: tcp
networks:
  default:
    name: sb-40060_default
```

which looks like YAML, not JSON.

### Compose Version

```Text
> docker compose version
Docker Compose version v2.25.0
```

### Docker Environment

```Text
> docker info
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 68
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.7.9-200.fc39.x86_64
 Operating System: Fedora Linux 39 (KDE Plasma)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.5GiB
 Name: workstation
 ID: 39477fed-c319-4871-a149-961fcd877c6a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

See https://github.com/spring-projects/spring-boot/issues/40060.
