### ISSUE TITLE
[BUG] Error when binding port with host IP

### ISSUE THREAD

**Issue by PhoenixmitX** [docker/compose#11676]
### Description

Similar to: #11336

when mapping ports with a host ip you get following error:
```
3 error(s) decoding:

* 'services[traefik].ports[0]' expected a map, got 'string'
* 'services[traefik].ports[1]' expected a map, got 'string'
* 'services[traefik].ports[2]' expected a map, got 'string'
```

### Steps To Reproduce

- create docker-compose.yml
```yaml
services:
  traefik:
    image: "traefik:latest"
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      # dashboard
      - "127.0.1:8080:8080" # expose insecure dashboard to local host ip (local host ip cannot be accessed from outside of the host machine/network)
```

- run `docker compose up -d`

### Compose Version

```Text
Docker Compose version v2.25.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 10
  Paused: 0
  Stopped: 4
 Images: 99
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.13-1-pve
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 64GiB
 Name: dev
 ID: 5b9fdf09-e2e5-4c4b-bb6a-6792d60b4ce1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by nefingar** [comment]
I  might have found a workaround for your particular issue. Writing the localhost as "127.0.0.1" seems to fix the problem. At least I was able to start up the compose environment with that. I hope this helps you a bit.

**Comment by ndeloof** [comment]
The root cause it that `127.0.1` is not a valid IP address, but error is hidden during initial parsing

**Comment by Nuxij** [comment]
I am receiving this error with the following:

```yml
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "165.22.114.125:6379:6379"
```

```
1 error(s) decoding:

* 'services[redis].ports[0]' expected a map, got 'string'
```
