### ISSUE TITLE
Incomplete env. variable substitution in the "volumes" section

### ISSUE THREAD

**Issue by pavlo** [docker/compose#1167]
Hey guys, it looks like Compose does not handle env. variables substitution if there're two vars like shown below: 

    volumes:
      - ${APP_DIR_ON_HOST}:${APP_DIR_ON_CONTAINER}

in this case the first var (APP_DIR_ON_HOST) gets expanded just fine while the second one stays unchanged - it gets passed literally as a string `${APP_DIR_ON_CONTAINER}`

Shouldn't it expand the second one as well? I would expect that.

Please let me know if you want me to provide more detailed example.
P.

**Comment by wallnerryan** [comment]
#dibs for docker boston, looking into this now

**Comment by wallnerryan** [comment]
confirmed the issue

export DHOST=/tmp/
export DCONTAINER=/host/tmp/

```
mycontainer:
   image: ubuntu:12.04
   volumes:
      - ${DHOST}:${DCONTAINER}
   command: /bin/bash -c "while true; do echo hello world; sleep 1; done"
```

```
 [46] → docker exec -it compose_mycontainer_1 /bin/bash
root@90c7c4204386:/# ls
${DCONTAINER}  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  selinux  srv  sys  tmp  usr  var
```
