### ISSUE TITLE
Docker Compose watch property not recognized in version v2.24.5 and v2.26.1

### ISSUE THREAD

**Issue by octrow** [docker/compose#11694]
### Description

I’m encountering an issue with Docker Compose where the watch property in my docker-compose.test.yml file is not recognized. I’m using Docker Compose version v2.24.5 on Ubuntu 22.04 with WSL2 on Windows 11 Pro 21H2.

According to the Docker Compose documentation, the watch property is available in Docker Compose version 2.22 and later, so it should be recognized in the version I’m using (v2.24.5).

Any help would be appreciated.

### Steps To Reproduce

Run `docker compose -f docker-compose.test.yml down -v`
Run `docker-compose -f docker-compose.test.yml up`

**Expected result**:

The watch property should be recognized and the services should start as expected.

**Actual result:**

I get the following error message:

`validating /home/username/dev/web-backend/src/docker-compose.test.yml: services.api Additional property watch is not allowed`

**Additional information:**
Windows 11:
Docker Desktop version: 4.28.0 (139021), **turn on** WSL integration with Ubuntu in Settings/Resource
Docker Engine version: v25.0.3
Ubuntu 22.04 (WSL2):
Docker version on Ubuntu 22.04: 26.0.0, build 2ae903e
Docker Compose (plugin) version: v2.24.5
Docker Compose version (standalone): v2.26.1

### Compose Version

```Text
Docker Compose version v2.24.5 (plugin)
Docker Compose version v2.26.1 (standalone)
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /home/octrow/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 28
  Running: 0
  Paused: 0
  Stopped: 28
 Images: 353
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: DESKTOP-NAME
 ID: 264527eb-ccd9-4431-9b97-1f95112d87c9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Anything else?

docker-compose.test.yml:
```YAML
services:
  api:
    container_name: fastapi_container
    build:
      dockerfile: fastapi.dockerfile
      context: ./backend
    image: python3.11-poetry
    develop:
    watch:
        - action: sync
          paths: ./backend
          target: /usr/src/app
    env_file: [.env]
    ports: [8000:8000]
    volumes:
      - .:/usr/src/app
      - ./backend/app/static/avatar:/app/app/static/avatar
    command: uvicorn app.server:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
    networks: [backend_network]
  
  redis:
    container_name: redis_container
    image: redis:7.2
    env_file: [.env]
    networks: [backend_network]
  celeryworker:
    container_name: celeryworker_container
    build:
      dockerfile: celeryworker-new.dockerfile
      context: ./backend
    env_file: [.env]
    environment:
      REDIS_URI: ${REDIS_URI}
      broker_connection_retry_on_startup: 'true'
      C_FORCE_ROOT: 'true'
    depends_on: [redis]
    volumes:
      - ./backend/app/static/avatar:/app/app/static/avatar
    networks:
      - backend_network
 
  database:
    container_name: database_container
    image: postgres:16.1
    restart: always
    env_file: [.env]
    volumes: [postgres_data:/var/lib/postgresql/data/]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: [5432:5432]
    networks:
      - backend_network

volumes:
  postgres_data:
networks:
  backend_network:
    driver: bridge
```

fastapi.dockerfile:

```YAML
FROM tiangolo/uvicorn-gunicorn:python3.11 AS build

ENV PYTHONDONTWRITEBYTECODE=1 \
    INSTALL_PATH=/app
ENV PYTHONPATH=$INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY pyproject.toml poetry.lock $INSTALL_PATH/

RUN pip3 install --no-cache-dir poetry==1.7.1 && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-directory --no-ansi --directory $INSTALL_PATH

FROM build AS production

ENV PYTHONDONTWRITEBYTECODE=1 \
    POSTGRES_NEED_ASYNC_URI=true \
    POSTGRES_NEED_SYNC_URI=true \
    REDIS_NEED_CELERY_BROKER_URI=true \
    INSTALL_PATH=/app
ENV PYTHONPATH=$INSTALL_PATH

COPY --from=build --chown=app:app $INSTALL_PATH $INSTALL_PATH

COPY --chown=app:app ./ ./

WORKDIR $INSTALL_PATH

RUN mkdir -p /migrations/versions
RUN chmod +x ./scripts/alembic_first_migration.sh
```

**Comment by glours** [comment]
Hey @octrow 
You have an indentation issue, `watch` is a property of `develop` attribut and you also made a typo it `path` and not `paths`

```yaml
services:
  api:
    container_name: fastapi_container
    build:
      dockerfile: fastapi.dockerfile
      context: ./backend
    image: python3.11-poetry
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app
    env_file: [.env]
    ports: [8000:8000]
    volumes:
      - .:/usr/src/app
      - ./backend/app/static/avatar:/app/app/static/avatar
    command: uvicorn app.server:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
    networks: [backend_network]
  
  redis:
    container_name: redis_container
    image: redis:7.2
    env_file: [.env]
    networks: [backend_network]
  celeryworker:
    container_name: celeryworker_container
    build:
      dockerfile: celeryworker-new.dockerfile
      context: ./backend
    env_file: [.env]
    environment:
      REDIS_URI: ${REDIS_URI}
      broker_connection_retry_on_startup: 'true'
      C_FORCE_ROOT: 'true'
    depends_on: [redis]
    volumes:
      - ./backend/app/static/avatar:/app/app/static/avatar
    networks:
      - backend_network
 
  database:
    container_name: database_container
    image: postgres:16.1
    restart: always
    env_file: [.env]
    volumes: [postgres_data:/var/lib/postgresql/data/]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: [5432:5432]
    networks:
      - backend_network

volumes:
  postgres_data:
networks:
  backend_network:
    driver: bridge
```
