### ISSUE TITLE
[BUG] "deadlock" when mixing include and extends with a custom project directory

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11723]
### Description

Please see the steps below

### Steps To Reproduce

1. Given this `compose.yaml`

```yaml

include:
  - project_directory: .
    path:
      - dir/first.yaml
      - dir/second.yaml

```

2. Where `dir/second.yaml` extends a service from `dir/first.yaml` which extends a service from a `dir/base.yaml`

```yaml

# dir/second.yaml
services:
  second:
    extends:
      file: dir/first.yaml
      service: first

```

```yaml

# dir/first.yaml
services:
  first:
    extends:
      file: dir/base.yaml
      service: base

```

```yaml

# dir/base.yaml
services:
  base:
    image: image

```

3. The "deadlock" when it comes to this way of using include and extends with a custom project directory is quite obvious

- it's either possible to "fix" the syntax so that including `dir/first.yaml` works,
- or to be able to include `dir/second.yaml`

### Compose Version

```Text
Docker Compose version v2.26.1
```

### Anything else?

The bug part, as already mentioned in https://github.com/docker/compose/issues/11573 and https://github.com/docker/compose/issues/11626, has more to do with the way this feature is conceived  - I don't think that the project directory can be applied to include or extends - they should simply be relative to the file that refers them and, if customization is needed ... they're already customizable using variables.
