### ISSUE TITLE
Request for allowing separate definition of image `tag` under `services`

### ISSUE THREAD

**Issue by oalagtash** [docker/compose#11743]
### Description

It would immensely helpful if I can define the tag of an image separately. 
This allows the use of YAML anchors and aliases in the compose.yml. Especially if the docker compose gets big and many images have the same tag name (special release). 

For example:
The following is currently not possible:
```
version: "3.9"

x-image-tag: &image-tag 2.0.0

services:
    my-image-a:
        image: my-image-a:*image-tag
    my-image-b:
        image: my-image-b:*image-tag
```

But it would be possible if:
```
version: "3.9"

x-image-tag: &image-tag 2.0.0

services:
    my-image-a:
        image: my-image-a
        tag:*image-tag
    my-image-b:
        image: my-image-b
        tag:*image-tag
```

Many Thanks!

**Comment by ndeloof** [comment]
The common approach to this issue is to define tag by a variable, maybe using a default value or with `.env` file to declare a reasonable default value:

```yaml
services:
    my-image-a:
        image: my-image-a:${TAG:-dev}
```
