### ISSUE TITLE
[BUG] cli panic on bad env_file properties

### ISSUE THREAD

**Issue by mjpowersjr** [docker/compose#11771]
### Description

Admittedly it took me way to long to spot this problem in a `docker-compose.yaml` file :-)

The following will cause the docker compose cli to panic, and the error message does not give the user a hint as to what's wrong:

```yaml
env_file:
  - file: .env
    required: true
```

changing the same snippet to the correct definition fixes the panic:
```yaml
env_file:
  - path: .env
    required: true
```

### Compose Version

```Text
v2.26.1-desktop.1
```
