### ISSUE TITLE
How to append the already existing environment variable instead of overriding them

### ISSUE THREAD

**Issue by tejajagadeep** [docker/compose#11803]
### Description

I can rewriting my application properties for my spring boot project in my docker compose I want to know how I can append to already existing file instead of overriding the properties.

```yml
wishlist-service:
    image: tejajagadeep/movie-app-wishlist-service:latest
    container_name: wishlist-container
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
      - swagger.server.url=http://localhost:8769/,http://localhost:4200/
      - spring.data.mongodb.uri=mongodb://root:root1234@mongodb:27017/wishlistdb?authSource=admin
    ports:
      - "8082:8082"
    networks:
      - my-network
```

I want to append this property instead of overwriting it.

```yml
- swagger.server.url=http://localhost:8769/,http://localhost:4200/, + values
```
