### ISSUE TITLE
[BUG] Cannot stop, remove or kill database container

### ISSUE THREAD

**Issue by brunolnetto** [docker/compose#11866]
### Description

This seems a simple issue, with some  unknown annoyance source: As you can see below, I am able to host a database with following docker-compose.yaml settings. After command run `docker-compose up`, I want to bring it down, as usual. However, it does not allows me running none of known command a.k.a. `docker-compose down`, `docker kill container_id` `docker stop container_id`, `docker rm -f container_id`. On some, it either outputs following log:

`Error response from daemon: Could not kill running container b767088fcdb6aa61b70c4380db6da123e18df74b13093303363aed6e687798f1, cannot remove - permission denied
` 

### Steps To Reproduce

File environment: 

```
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_NAME=mydb
```

File docker-compose.yaml:

```
version: "3.8"

services:
  db:
    container_name: crawler-db
    image: postgres:14
    restart: always
    env_file: .env
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    command: postgres -c listen_addresses='*' -p $POSTGRES_PORT
    volumes:
      - ./data:/var/lib/postgresql/data_ 

volumes:
  postgres_data:
```

### Compose Version

```Text
Docker Compose version v2.23.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-107-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.36GiB
 Name: falcon
 ID: ea63feef-d565-434e-a157-82ed10a640cb
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Username: brunolnetto1234
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Thanks for the help.
