### ISSUE TITLE
Hello, I'm new to this, I need urgent help!

### ISSUE THREAD

**Issue by BrahianUY** [docker/compose#11879]
### Description

I put in the terminal (docker-compose up -d --force-recreate) and it tells me this error

- (Top-level object must be a mapping)

debug: false
uuid: ec741b61-5134-47ae-8d56-569335b8b05f
token_id: 1lRbT2GPSyIAu6bC
token: RVto05RWzMQaPTigGC0KtRT7PBjI9bT1rqMmmMHCMjN7Qxbm0KNqrMETm12O2jbt
api:
  host: 0.0.0.0
  port: 80
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/factual-personally-crawdad.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/factual-personally-crawdad.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://super-duper-cod-4jgqg9p7p75x2jgwj-80.app.github.dev'

**Comment by glours** [comment]
Hello @BrahianUY 
Is this the content of your `compose.yaml`? 
```yaml
debug: false
uuid: ec741b61-5134-47ae-8d56-569335b8b05f
token_id: 1lRbT2GPSyIAu6bC
token: RVto05RWzMQaPTigGC0KtRT7PBjI9bT1rqMmmMHCMjN7Qxbm0KNqrMETm12O2jbt
api:
host: 0.0.0.0
port: 80
ssl:
enabled: false
cert: /etc/letsencrypt/live/factual-personally-crawdad.ngrok-free.app/fullchain.pem
key: /etc/letsencrypt/live/factual-personally-crawdad.ngrok-free.app/privkey.pem
upload_limit: 100
system:
data: /var/lib/pterodactyl/volumes
sftp:
bind_port: 2022
allowed_mounts: []
remote: 'https://super-duper-cod-4jgqg9p7p75x2jgwj-80.app.github.dev/'
```
