### ISSUE TITLE
[BUG] docker compose up service fails because of required network from another service

### ISSUE THREAD

**Issue by RicardoM17** [docker/compose#11976]
### Description

Based on the `compose.yml` file below, we should be able to start `test_service` without the external network `test_network` being present as `test_service` does not depend on it.

- If I remove `other_service` from the compose file then this is possible.
- If I disable `other_service` with for example a `docker profile` this is also possible.

### Steps To Reproduce

Given the following compose file:

```
services:

  test_service:
    image: python:3
    container_name: test_service
    command: sleep infinity

  other_service:
    image: python:3
    container_name: other_service
    command: sleep infinity
    networks:
      test_network:
        ipv4_address: 8.8.8.8

networks:
  test_network:
    external: true
    name: bee_rf  
```

```
docker compose -f compose.yml up -d test_service
```

returns
```
Error response from daemon: network test_network not found
```

### Compose Version

```Text
Docker Compose version v2.26.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.0
    Path:     /home/ricardom/.docker/cli-plugins/docker-compose
WARNING: Plugin "/home/ricardom/.docker/cli-plugins/docker-compose-v2.15.1" is not valid: plugin candidate "compose-v2.15.1" did not match "^[a-z][a-z0-9]*$"
WARNING: Plugin "/home/ricardom/.docker/cli-plugins/docker-compose-v2.26.0" is not valid: plugin candidate "compose-v2.26.0" did not match "^[a-z][a-z0-9]*$"

Server:
 Containers: 17
  Running: 2
  Paused: 0
  Stopped: 15
 Images: 151
 Server Version: 25.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 6.4.0-060400-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 42.93GiB
 Name: ricardom-ThinkPad
 ID: 3LCX:H5OL:IEKQ:BR67:OSZ7:ZTJ3:QSQF:DAVP:4AI2:DQFH:KCVE:SWFK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
