### ISSUE TITLE
[BUG] <.env variable network name not working>

### ISSUE THREAD

**Issue by elgordodevops** [docker/compose#11982]
### Description

His guys, i have problems with .env passing variables but the problem is only in the network service definition, because the error show the correct value in the redis service, also the project name works in the redis container_name

(edit: extra info: i want to create a network, i dont wat to call a external network)

thanks!

(both files .yml and .env in same folder)

error:
root@server:/home/xxx/dev# docker compose -f docker-compose.yml config
service "redis" refers to undefined network xxx-dev-network: invalid compose project

versions
root@server:/home/xxx/dev# docker -v
Docker version 27.0.1, build 7fafd33

root@server:/home/xxx/dev# docker compose version
Docker Compose version v2.28.1

------docker-compose.yml
```yaml
services:
  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:alpine
    restart: always
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
    name: ${NETWORK_NAME}
```    
    
-------my .env
```    
PROJECT_NAME=xxx
AMBIENTE=dev
NETWORK_NAME=${PROJECT_NAME}-${AMBIENTE}-network
```
( also with plain text value without nesting variables not work, this not work NETWORK_NAME=network)

**Comment by jhrotko** [comment]
Hello @elgordodevops,

Interpolation is only possible for values and not for yaml keys. Generally, I believe this approach is problematic as it introduces unnecessary complexity.

```
networks:
   ${NETWORK_NAME}:  <-- this is won't work, interpolation does not work here
      name: ${NETWORK_NAME}  <-- OK
```
Does the name of the network really need to be dependent on the service name? If you are trying to generate a `docker-compose.yml`, use a templating tool like mustache or handlebars, and generate #the docker-compose.yml file yourself from env vars.

**Comment by elgordodevops** [comment]
Hi @jhrotko thanks for you help

Maybe i can do this in a different way, that im trying to do is to isolate the networks creating a template and filling the values with the .env, i need to isolate because i have multiple projects and multiple stages, like uat,dev, etc., 

is not possible also call the redis network with variables?, i trying to do this but i have this error
"docker compose -f docker-compose.yml config
service "redis" refers to undefined network dev-dbmx-network: invalid compose project"


```dockerfile
services:
  redis:
    container_name: ${AMBIENTE}-${PROJECT_NAME}-redis
    image: redis:alpine
    restart: always
    networks:
      - ${NETWORK_NAME}

networks:
  network:
    name: ${NETWORK_NAME}
```

**Comment by ndeloof** [comment]
@elgordodevops  use:
```yaml
services:
  redis:
    networks:
      - my_network

networks:
  my_network:
    name: ${NETWORK_NAME}
```

Anyway, IIRC we added support for interpolation on resources keys some time ago, I wonder this is a regression, need to give it a try
