### ISSUE TITLE
[BUG] docker compose produces no output for some commands

### ISSUE THREAD

**Issue by devinbarry** [docker/compose#12011]
### Description

I am running docker on Ubuntu server 22.04. I updated docker to the latest version and some commands started failing and produce no output. Here is what I see when I use the verbose flag:

```
docker compose --verbose pull
TRAC[0000] Docker Desktop integration not enabled
DEBU[0000] otel error                                    error="<nil>"
DEBU[0000] otel error                                    error="<nil>"
```

```
docker compose --verbose down
TRAC[0000] Docker Desktop integration not enabled
DEBU[0000] otel error                                    error="<nil>"
DEBU[0000] otel error                                    error="<nil>"
```

### Steps To Reproduce

I don't know if I could necessarily reproduce this. I would have to spin up a new VM and install docker again to see if this can be reproduced

### Compose Version

```Text
Docker Compose version v2.29.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-116-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.75GiB
 Name: minio
 ID: 102a8cc9-75f5-452f-8fc9-8c21d02c7829
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by idsulik** [comment]
@devinbarry hello! Thank you for the issue!  
I think it happens when there's nothing to do.  

- no images to pull and you executed `docker compose pull`
- nothing to down and you executed `docker compose down`

**Comment by devinbarry** [comment]
Here is a little more output from my terminal:
```
docker ps
CONTAINER ID   IMAGE         COMMAND                  CREATED        STATUS                  PORTS                                                                                        NAMES
2a4dbf83eab9   minio/minio   "/usr/bin/docker-ent…"   9 months ago   Up 20 hours (healthy)   0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:9001->9001/tcp, :::9001->9001/tcp, 9000/tcp   minio
```
```
docker compose --verbose -f docker-compose.yaml down
TRAC[0000] Docker Desktop integration not enabled
DEBU[0000] otel error                                    error="<nil>"
DEBU[0000] otel error                                    error="<nil>"
```
```
docker compose --verbose -f docker-compose.yaml logs --tail all
TRAC[0000] Docker Desktop integration not enabled
DEBU[0000] otel error                                    error="<nil>"
DEBU[0000] otel error                                    error="<nil>"
```
This is the docker compose file if you are interested:
```
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "443:443"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
      - ~/minio/.minio:/root/.minio
    env_file:
      - .env
    command: server --console-address ":9001" --address ":443" /data
    profiles:
      - server
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://${MINIO_SERVER_DOMAIN}/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  certbot:
    image: certbot/dns-cloudflare:latest
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d ${MINIO_SERVER_DOMAIN} --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --non-interactive
    volumes:
      - ./certbot-config:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
    profiles:
      - server
      - init
```
