### ISSUE TITLE
[BUG] Failed to compute cache key: failed to calculate checksum of ref ...

### ISSUE THREAD

**Issue by GayeongKimm** [docker/compose#12028]
### Description

Hi, I have a problems flowing this:
I'm working on a project that I'm doing at school, but it's so hard because I keep getting these errors.
Deploying using github operation and docker, but >> COPY build/libs/sopo-2.0.0.jar/sopo.jar error appears here
<img width="1470" alt="스크린샷 2024-07-28 오후 8 05 18" src="https://github.com/user-attachments/assets/99aad4bb-02b5-41cb-bb87-a23a74c71a31">

It's called the path problem, and the Dockerfile is in the root path, and build/libs are in the root path. Jar files are also created, so why does this happen?

I'm still a high school student developer, so there's a lot I don't know, so please help me.

### docker-compose.yml
```
version:  '3'

services:
  redis:
    image:  redis:alpine
    container_name:  redis
    hostname:  redis
    ports:
      - "6379:6379"

  springboot:
    build:
      context:  .
      dockerfile:  Dockerfile
    container_name:  sopo_redis
    depends_on:
      - redis
    ports:
      - "8080:8080"
  ```
