### ISSUE TITLE
[feature request] Allow hostnames for settings dns. 

### ISSUE THREAD

**Issue by cocoonkid** [docker/compose#12025]
### Description

Example as it works right now:

```
services:

  telegraf:
    image: telegraf
    command: >
            sh -c "sleep 10 && telegraf --config /etc/telegraf/telegraf.conf"
    volumes:
      - /manifests/{{ inventory_hostname }}/configuration/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  extra_hosts:
    - "host.docker.internal:host-gateway"
  dns:
    - 10.254.66.18
```

Examples as it should work when the feature has been implemented:

```
services:

  telegraf:
    image: telegraf
    command: >
            sh -c "sleep 10 && telegraf --config /etc/telegraf/telegraf.conf"
    volumes:
      - /manifests/{{ inventory_hostname }}/configuration/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  extra_hosts:
    - "host.docker.internal:host-gateway"
  dns:
    - host.docker.internal
```

```
services:

  telegraf:
    image: telegraf
    command: >
            sh -c "sleep 10 && telegraf --config /etc/telegraf/telegraf.conf"
    volumes:
      - /manifests/{{ inventory_hostname }}/configuration/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  extra_hosts:
    - "host.docker.internal:host-gateway"
  dns:
    - <other-container-hostname-getting-resolved-by-172.17.0.11-automagically>
```

Example ulgy hack to work around the issue but would like to simply declare:

```
  dns:
    - coredns

```

```

  telegraf:
    image: telegraf
    command: >
            sh -c "sleep 10 && telegraf --config /etc/telegraf/telegraf.conf"
    volumes:
      - /manifests/{{ inventory_hostname }}/configuration/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  extra_hosts:
    - "host.docker.internal:host-gateway"
  dns:
    - 192.168.1.10


  coredns:
    image: coredns/coredns:latest
    command: -conf /etc/coredns/Corefile
    ports:
      - "127.0.0.1:53:53/udp"
    volumes:
        - "/manifests/zabbix/coredns/:/etc/coredns:ro"
    networks:
      dns-net:
        ipv4_address: 192.168.1.10


and adding 

    networks:
      dns-net:

to very other service definition (via anchors.)
```
