### ISSUE TITLE
[BUG] include and !override do not work correctly in nested include scenario

### ISSUE THREAD

**Issue by eldiaboloz** [docker/compose#12029]
### Description

I am trying to use nested includes and it seems the !override option is not working as expected.
I have read a [similar issue](https://github.com/docker/compose/issues/11404#issuecomment-1911603630) and tried the same approach, but it doesnt work if there are multiple level of includes

### Steps To Reproduce

create 4 yaml files:
[main.yaml](https://gist.githubusercontent.com/eldiaboloz/a2d0dee90522b235529e4ee05ee2c31b/raw/afaae8080fa5290f26cfb398b2170f665e0a015e/main.yaml):
```
include:
  - "./service-main.yaml"
```
[extend.yaml](https://gist.githubusercontent.com/eldiaboloz/a2d0dee90522b235529e4ee05ee2c31b/raw/afaae8080fa5290f26cfb398b2170f665e0a015e/extend.yaml):
```
include:
  - path:
      - "./service-main.yaml"
      - "./service-extend.yaml"
```
[service-main.yaml](https://gist.githubusercontent.com/eldiaboloz/a2d0dee90522b235529e4ee05ee2c31b/raw/afaae8080fa5290f26cfb398b2170f665e0a015e/service-main.yaml):
```
services:
  test:
    image: "nginx"
    ports:
      - "127.0.0.1:80:80"
    environment:
      - VARA=test
```
[service-extend.yaml](https://gist.githubusercontent.com/eldiaboloz/a2d0dee90522b235529e4ee05ee2c31b/raw/afaae8080fa5290f26cfb398b2170f665e0a015e/service-extend.yaml):
```
services:
  test:
    ports: !override
      - "127.0.0.2:80:80"
    environment: !override
      - VARB=test
```
[run docker config](https://gist.githubusercontent.com/eldiaboloz/a2d0dee90522b235529e4ee05ee2c31b/raw/afaae8080fa5290f26cfb398b2170f665e0a015e/test.sh)
```
docker container run -it -v $PWD:/test -w /test docker:latest \
  docker compose -f main.yaml -f extend.yaml config
```
expected output:
```
name: test
services:
  test:
    environment:
      VARB: test
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.2
        target: 80
        published: "80"
        protocol: tcp
networks:
  default:
    name: test_default

```
actual output:
```
name: test
services:
  test:
    environment:
      VARA: test
      VARB: test
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.2
        target: 80
        published: "80"
        protocol: tcp
networks:
  default:
    name: test_default
```

### Compose Version

```Text
Docker Compose version v2.29.1
```
