### ISSUE TITLE
[BUG] env_file section is ignored on docker-compose up -d

### ISSUE THREAD

**Issue by nacesprin** [docker/compose#12035]
### Description

Docker compose ignores `env_file` section. The env variables only works if are stored in `.env` file, or are called from `docker-compose --env-file ficher.env up -d`

## scenario 1

docker-compose.yml

```
services:
  portal-asesoria-db:
    container_name: portal-asesoria-db
    image: mysql:8.0.26
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: ${MYDB} 
```

ficher.env:
`MYDB=hello`

then run:
`docker-compose --env-file ficher.env up -d`

result as expected

## scenario 2

docker-compose.yml

```
services:
  portal-asesoria-db:
    container_name: portal-asesoria-db
    env_file:
    - ficher.env
    image: mysql:8.0.26
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: ${MYDB} 
```

ficher.env:
`MYDB=hello`

then run:
`docker-compose up -d`

result:
`WARN[0000] The "MYDB" variable is not set. Defaulting to a blank string.`

## scenario 3
in any of scenario 1 and 2, if the variable is stored in `.env` file, it works, but I dont want to store in `.env` file

### Compose Version

```Text
docker compose version: not working
docker compose --version: Docker version 20.10.21, build baeda1f
docker-compose version: v2.29.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 10
  Running: 5
  Paused: 0
  Stopped: 5
 Images: 100
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-131-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.52GiB
 Name: vant-javi
 ID: K3YY:OTM4:4OZ5:2GOB:HXVF:7VU6:UEBX:LOBL:2HMB:QZ4J:DENG:R6YI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by idsulik** [comment]
When using Docker Compose, the env_file directive is used to specify environment variables **that will be made available to the service containers at runtime**. However, for environment variable interpolation within the docker-compose.yml file itself, Docker Compose uses variables **from the shell environment or an optional .env file** located in the same directory as the docker-compose.yml file.
Rename the `ficher.env` into` .env` and should work

**Comment by nacesprin** [comment]
1 - Yes, but by using `docker-compose --env-file ficher.env up -d` it is working as I need. I don't understand why variable interpolation works right in this mode, but by using `env_file` section in `docker-compose.yml` file isn't.

2 - I wonder if could be changed the base directory where is located the docker-composer.yml `.env` file in order not be mixed with the same `.env` file from symfony (which is the framework I am using in the same directory)

Thanks @idsulik .

**Comment by ndeloof** [comment]
environment variables in your container (set by either `environment` or `env_file`) != variable interpolation in compose.yaml

When you set:
```yaml
    environment:
      MYSQL_DATABASE: ${MYDB} 
```
Compose tries to resolve variable `MYDB` from your local os.Env + default `.env` file (or the one your pointed to with `-- env-file`). 
If you want to directly set container's environment from a file; just set:

ficher.env
```
MYSQL_DATABASE=FOO
```
compose.yaml
```
services:
  portal-asesoria-db:
    container_name: portal-asesoria-db
    env_file:
    - ficher.env
    # No environment section needed here
```

Closing this issue as "works as designed"

**Comment by aorith** [comment]
It would be great if compose allowed an override of the currently hardcoded `.env` file outside of the services section and directly in the yaml specification.

```yaml
# Same as 'docker compose --env-file default.env'
env_file: default.env

services:
  frontend:
    image: example/webapp
    ports:
    - "443:8043"
    networks:
    - front-tier
    env_file: frontend.env

networks:
  front-tier: {}
```

**Comment by ndeloof** [comment]
@aorith how would this differ vs just having the `default.env` content in `.env` file ?

**Comment by aorith** [comment]
Indeed, you're right, technically, it would be the same, but I see some practical use cases:

- It's more explicit and discoverable than a single `.env` file, it could even have an option to enforce its presence (like service's env files):

```yml
env_file:
  # Host-specific variables:
  # DATA_PATH --> path to the data volume on this host
  # ...
  - path: ./host.env
    required: true

services:
  app:
    image: example/app
    volumes:
      - ${DATA_PATH}/app:/data
    # Local to this service
    env_file: ./app.env
```

- Being present in the compose YAML helps less experienced docker/linux users (hidden files) and avoids extra documentation in the project's README 😅

- Allows the presence of multiple compose files in the same directory, each one with its own env files (to be fair you already can do that with the `--env-file` argument, but again having it directly in the YAML avoids that friction):

```
.
├── compose-cpu.yml
├── compose-gpu.yml
└── env
    ├── cpu
    │   ├── app.env
    │   └── default.env
    └── gpu
        ├── app.env
        ├── app2.env
        └── default.env
```

- The `.env` file can be reserved for other applications, avoiding overloading that file when required since since it's so commonly used

Of course, this is only minor QOL and most things can be achieved by other means already, like using the special syntax `${REQUIRED_ENV_VAR:?}` for variables that are mandatory instead of a required env file in the YAML. Still, I think it would be useful and (probably) easy to implement.
