### ISSUE TITLE
Allow Compose behaviour to match CLI and create networks without being used or requiring defined services

### ISSUE THREAD

**Issue by DocFX** [docker/compose#12058]
*(Note: I hope this is the correct repository to submit this ^^)*

## Description

Simple use example case: 
- generic Compose YAML files for different services, regardless of environment and network config, only mentioning its same network attachment reference.
- needing to create or drop services YAML file by YAML file, on demand, attached to the same created network reference
- use Compose with multiple files: network definition, then file 1 services definition, file 2 services definition, etc. Whatever the needs.

To this day, the only way  to achieve this is to mix CLI and Compose:
1. create the network with CLI `docker network create`
2. build/up with Compose from CLI, using files with services referencing this entry.

This mixes responsibilities between CLI and Compose, while both of them pretending to be able to do the same (more or less, including overloading parameters).
Also, currently, Compose checks for network entries being used by the Compose file defined services to effectively create them, giving the expected `WARNING: Some networks were defined but are not used by any service: [...]` message.

## Proposed solution

- Add a parameter that dodges **both** service dependency check on networks (all of them or none current behaviour if not used) and the minimum 1 service root element definition.
- Add a parameter that forces recreation of networks referenced in given list of arguments **ONLY** if `--force-recreate` is affected by final behaviour choices (current behaviour: compliant with this solution, no changes needed).

Could be (following current arguments syntax choices):
- `--force-networks`
- `--always-recreate-networks`

## Example expected behaviour

Using these three progressively completed sample files:

`network_compose_without_services.yaml`
```yaml

name: your_compose_name

networks:
  any_network_definition:
    ipam:
      driver: default
      # ... or whatever config you want to provide explicitely or none
      config:
        - subnet: 10.1.0.0/16
```

`network_compose_with_services.yaml`
```yaml

name: your_compose_name

networks:
  any_network_definition:
    ipam:
      driver: default
      # ... or whatever config you want to provide explicitely or none
      config:
        - subnet: 10.1.0.0/16

services:
  dummy-service:
    image: hello-world:latest
```

`network_compose_with_services_used.yaml`
```yaml

name: your_compose_name

networks:
  any_network_definition:
    ipam:
      driver: default
      # ... or whatever config you want to provide explicitely or none
      config:
        - subnet: 10.1.0.0/16

services:
  dummy-service:
    image: hello-world:latest
    networks:
      any_network_definition:
```

### Current

Using network definition only:

```bash
docker compose -f "network_compose_without_services.yml" up --force-recreate --build -d

# no service selected
```

```bash
docker network ls

NETWORK ID     NAME                        DRIVER    SCOPE
xxxxxxxxxxxx   bridge                      bridge    local
xxxxxxxxxxxx   host                        host      local
xxxxxxxxxxxx   none                        null      local
```

Using network definition AND service definition:

```bash
docker compose -f "network_compose_with_services.yml" up --force-recreate --build -d

# WARNING: Some networks were defined but are not used by any service: any_network_definition.
```

```bash
docker network ls

NETWORK ID     NAME                        DRIVER    SCOPE
xxxxxxxxxxxx   bridge                      bridge    local
xxxxxxxxxxxx   host                        host      local
xxxxxxxxxxxx   none                        null      local
```

Using network definition AND service definition AND attaching at least that one service to the network:

```bash
docker compose -f "network_compose_with_services_used.yml" up --force-recreate --build -d

# ✔ Network any_network_definition_any_network_definition     Created    
# ✔ Container any_network_definition_dummy-service-1          Created   
```

```bash
docker network ls

NETWORK ID     NAME                        DRIVER    SCOPE
xxxxxxxxxxxx   bridge                                                             bridge    local
xxxxxxxxxxxx   host                                                               host      local
xxxxxxxxxxxx   none                                                               null      local
xxxxxxxxxxxx   any_network_definition_any_network_definition                      bridge    local
```

### Feature expected

```bash
docker compose -f "network_compose_without_services.yml" up --force-recreate --build --force-networks -d

 ✔ Network any_network_definition_any_network_definition Created    
```

*Note: could be, as currently done, `Created` or `Recreated`.*

```bash
docker network ls

NETWORK ID     NAME                        DRIVER    SCOPE
xxxxxxxxxxxx   bridge                                                             bridge    local
xxxxxxxxxxxx   host                                                               host      local
xxxxxxxxxxxx   none                                                               null      local
xxxxxxxxxxxx   any_network_definition_any_network_definition                      bridge    local
```

**Note: this doesn't offer any possible BC break, yay.**
