### ISSUE TITLE
[BUG] using `docker compose run --watch` my app is restarting more than once after every file change

### ISSUE THREAD

**Issue by adiberk** [docker/compose#12087]
### Description

I have a docker compose file that uses a watch configuration.  sync+restart
Everything works as expected, except I see that after every single save, my app restarts more than once which while isn't the end of the world is a bit annoying.

Here is my compose file
```
services:
  lev-backend:
    container_name: backend
    build:
      context: .
      args:
        ENV: dev
      ssh: [ default ]
    image: backend
    stdin_open: true
    init: true
    tty: true
    command: "gunicorn -c python:config --bind=0.0.0.0:7680 place:app --log-level=debug"
    env_file:
      - .env
    ports:
      - "7680:7680"
    volumes:
      # - .:/app
      - ./tests:/app/tests
      - ~/.ssh:/root/.ssh
    external_links:
      - postgres:db
      - redis
    networks:
      - default
      - infra
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
```

Ideally after every save it should only restart once

### Steps To Reproduce

Run a flask app behind gunicorn. Create a watch config, then run docker compose up --watch

### Compose Version

```Text
latest (2.29.2)
```

### Docker Environment

```Text
Client:
 Version:    27.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1-desktop.1
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.29.2
    Path:     /opt/homebrew/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/adiberkowitz/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.11.0
    Path:     /Users/{NAME}/.docker/cli-plugins/docker-scout

Server:
 Containers: 15
  Running: 7
  Paused: 0
  Stopped: 8
 Images: 38
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.0-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.753GiB
 Name: docker-desktop
 ID: ab6ce1f7-db39-41fc-a60d-14189dc3146a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/{NAME}/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```
