### ISSUE TITLE
Running "docker compose" within subdirectory below docker-compose.yml will leed into "variable is not set" messages

### ISSUE THREAD

**Issue by sh3bang** [docker/compose#12124]
### Description

when i am running a docker command in my home directory where also my docker-compose.yml is placed everything is fine
```
[paul@xps-9310 ~]$ docker compose ps
NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS
```

when i am calling same command within subdirectory of my home directory a lot of warnings apear and i dont know why:
```
[paul@xps-9310 Projekte]$ docker compose ps
WARN[0000] The "pbkdf2" variable is not set. Defaulting to a blank string. 
WARN[0000] The "YtP7EbGs196" variable is not set. Defaulting to a blank string. 
WARN[0000] The "tFECP7wm" variable is not set. Defaulting to a blank string. 
WARN[0000] The "pbkdf2" variable is not set. Defaulting to a blank string. 
WARN[0000] The "YtP7EbGs196" variable is not set. Defaulting to a blank string. 
WARN[0000] The "tFECP7wm" variable is not set. Defaulting to a blank string. 
WARN[0000] The "pbkdf2" variable is not set. Defaulting to a blank string. 
WARN[0000] The "YtP7EbGs196" variable is not set. Defaulting to a blank string. 
WARN[0000] The "tFECP7wm" variable is not set. Defaulting to a blank string. 
WARN[0000] The "pbkdf2" variable is not set. Defaulting to a blank string. 
WARN[0000] The "YtP7EbGs196" variable is not set. Defaulting to a blank string. 
WARN[0000] The "tFECP7wm" variable is not set. Defaulting to a blank string. 
NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS 
```

### Compose Version

```Text
2.29.2
```

### Docker Environment

```Text
Client:
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.29.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 2
  Paused: 0
  Stopped: 8
 Images: 10
 Server Version: 27.1.2
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353.m
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.6-10-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.07GiB
 Name: xps-9310
 ID: 88c7c114-d370-4953-a3ca-b3c9d62f130a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

My docker-compose.yml don't use any environment variables

**Comment by idsulik** [comment]
@sh3bang could you please share the docker compose content?

**Comment by sh3bang** [comment]
```
name: web
services:
  nginx:
    container_name: nginx
    build: ~/Projekte/.container/nginx
    environment:
      TZ: Europe/Berlin
    networks:
      develop:
        aliases:
          - coupon
          - leserservice
          - aua
          - ep
          - ivv
          - tl
          - mgt
          - events
          - deduu
    volumes:
      - ~/Projekte/:/home/paul/Projekte/
      - ~/Projekte/.container/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php7-drupal
      - php7-ep
      - php8
  memcached:
    container_name: memcached
    image: memcached:1.4.33
    environment:
      TZ: Europe/Berlin
    networks:
      develop:
    volumes:
      - ~/Projekte/.container/memcached/memcached.conf:/etc/memcached.conf
  php7-drupal:
    container_name: php7-drupal
    build: ~/Projekte/.container/php7-drupal
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal output_dir=/home/paul/Projekte/
      TZ: Europe/Berlin
    networks:
      develop:
    volumes:
      - ~/Projekte/:/home/paul/Projekte/
      - ~/Projekte/.container/php7-drupal/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ~/Projekte/.container/php7-drupal/memcache.ini:/usr/local/etc/php/conf.d/memcache.ini
      - ~/Projekte/.container/php7-drupal/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /home/paul/Projekte
    extra_hosts:
     - host.docker.internal:host-gateway
    depends_on:
      - mariadb
      - memcached
  php74-drupal:
    container_name: php74-drupal
    build: ~/Projekte/.container/php74-drupal
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal output_dir=/home/paul/Projekte/
      TZ: Europe/Berlin
    networks:
      develop:
    volumes:
      - ~/Projekte/:/home/paul/Projekte/
      - ~/Projekte/.container/php74-drupal/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ~/Projekte/.container/php74-drupal/memcache.ini:/usr/local/etc/php/conf.d/memcache.ini
      - ~/Projekte/.container/php74-drupal/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /home/paul/Projekte
    extra_hosts:
     - host.docker.internal:host-gateway
    depends_on:
      - mariadb
      - memcached
  php7-ep:
    container_name: php7-ep
    build: ~/Projekte/.container/php7-ep
    environment:
      TZ: Europe/Berlin
    networks:
      develop:
    volumes:
      - ~/Projekte/:/home/paul/Projekte/
      - ~/Projekte/.container/php7-ep/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ~/Projekte/.container/php7-ep/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ~/.ssh/:/home/paul/.ssh:ro
    working_dir: /home/paul/Projekte
    extra_hosts:
     - host.docker.internal:host-gateway
    depends_on:
      - mariadb
  php8:
    container_name: php8
    build: ~/Projekte/.container/php8
    environment:
      TZ: Europe/Berlin
      XDEBUG_CONFIG: client_host=host.docker.internal output_dir=/home/paul/Projekte
      PHP_IDE_CONFIG: serverName=coupon.internal
    networks:
      develop:
    volumes:
      - ~/Projekte/:/home/paul/Projekte/
      - ~/Projekte/.container/php8/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ~/Projekte/.container/php8/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /home/paul/Projekte
    extra_hosts:
     - host.docker.internal:host-gateway
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      TZ: Europe/Berlin
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_ROOT_PASSWORD: root
    networks:
      develop:
    volumes:
      - mariadb:/var/lib/mysql
  solr:
    container_name: solr
    image: typo3solr/ext-solr:11.5.2
    networks:
      develop:
#  mysql55:
#    container_name: mysql55
#    image: mysql:5.5.62
#    environment:
#      TZ: Europe/Berlin
#      MYSQL_USER: test
#      MYSQL_PASSWORD: test
#      MYSQL_ROOT_PASSWORD: root
#    networks:
#      develop:
#    volumes:
#      - ~/Projekte/.container/mysql55/myopt.cnf:/etc/mysql/conf.d/myopt.cnf
#      - mysql55:/var/lib/mysql
networks:
  develop:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.5.1.0/24
         gateway: 10.5.1.1
volumes:
  mysql55:
  mariadb:
    driver: local
    driver_opts:
      type: btrfs
      o: subvol=/@mariadb
      device: /dev/nvme0n1p10
```

**Comment by xoldd** [comment]
Can confirm this behavior for the same docker compose version. The environment variables listed in the `services.<service_identifier>.environment` field in `compose.yaml` file aren't being read by docker compose while its processing the compose files so their values can't be used directly in them, it leads to docker compose substituting empty strings in their place of usage. Though these environment variables are present with proper values within the container service at runtime.
```
# compose.yaml
services:
  node_server:
    environment:
      - MAPPED_PORT=${MAPPED_PORT:-5000}
    ports:
      - ${MAPPED_PORT}:5000
```
On running `docker compose up` against the compose file shown above, it complains that `MAPPED_PORT` is not set and makes use of empty string `""` for substituting its value in the `ports` map field. Though It is accessible in the `node_server` service at runtime, I checked it manually by running `echo $MAPPED_PORT` inside the container service.
