### ISSUE TITLE
[BUG] problem with variable interpolation with config file into HOME dir

### ISSUE THREAD

**Issue by rino1** [docker/compose#12152]
### Description

```
+ docker compose -f extended1.yml run --rm test
GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-musl)
/tmp/tmp.data20241157
```

OK

```
+ docker compose -f extended2.yml run --rm test
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/xxx/tmp/tmp.data20241157
```

Why?

To note that `/home/xxx` is inserted before `/tmp/tmp.data20241157`

Why?

### Steps To Reproduce

```
+ echo ${XXX-NOT-SET}
NOT-SET

+ echo $HOME
/home/xxx

+ mkdir /tmp/tmp.data20241157

+ pwd && tree
/tmp/tmp.VuxVHSi4EI
    ├── basic.yml
    ├── extended1.yml
    └── extended2.yml

+ cat basic.yml 
services:
    test:
        image: bash
        command: bash -c "bash --version | grep release && ls -d ${XXX:-/tmp/tmp.data20241157}"
        volumes:
            - type: bind
              source: ${XXX:-/tmp/tmp.data20241157}
              target: ${XXX:-/tmp/tmp.data20241157}
              bind:
                create_host_path: false

+ cat extended1.yml
services:
    test:
        extends:
            file: basic.yml
            service: test

+ cat extended2.yml
services:
    test:
        extends:
            file: $HOME/basic.yml
            service: test
```

To note

```
+ diff basic.yml $HOME/basic.yml && echo Files are identical
Files are identical

+ diff extended1.yml extended2.yml
4c4
<             file: basic.yml
---
>             file: $HOME/basic.yml
```

### Compose Version

```
+ lsb_release -a | grep Descr
Description:	Ubuntu 24.04.1 LTS

+ bash --version | grep release
GNU bash, versione 5.2.21(1)-release (x86_64-pc-linux-gnu)

+ docker compose version
Docker Compose version v2.29.0
```

### Docker Environment

```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.0
    Path:     /home/xxx/.docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-45-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.657GiB
 Name: MY-PC
 ID: 2f3be2ff-461b-400a-9dc7-67650870d8fb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by jhrotko** [comment]
Hello, @rino1 

I can't reproduce the issue with the latest version. Could you show me the results for:
`docker compose -f extended1.yml config`
and 
`docker compose -f extended2.yml config` ?

**Comment by rino1** [comment]
Sorry for the delay

```
+ docker compose -f extended1.yml config
name: tmpqbs4rauey5
services:
  test:
    command:
      - bash
      - -c
      - bash --version | grep release && ls -d /tmp/tmp.data20241157
    image: bash
    networks:
      default: null
    volumes:
      - type: bind
        source: /tmp/tmp.data20241157
        target: /tmp/tmp.data20241157
        bind: {}
networks:
  default:
    name: tmpqbs4rauey5_default
+ docker compose -f extended2.yml config
name: tmpqbs4rauey5
services:
  test:
    command:
      - bash
      - -c
      - bash --version | grep release && ls -d /tmp/tmp.data20241157
    image: bash
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/rino/tmp/tmp.data20241157
        target: /tmp/tmp.data20241157
        bind: {}
networks:
  default:
    name: tmpqbs4rauey5_default
```

**Comment by jhrotko** [comment]
Hello @rino1,
I am having issues in reproducing your issue. I don't understand how `$HOME/basic.yml` works for your example given your steps to reproduce. This is the file structure you gave:
```
+ pwd && tree
/tmp/tmp.VuxVHSi4EI
    ├── basic.yml
    ├── extended1.yml
    └── extended2.yml
```
... and 
```
echo $HOME
  /home/xxx
```
I will assume your have another file in `$HOME/basic.yml` besides in the `tmp` location. Without adding `$HOME/basic.yml` it doesn't even work because it cannot find the file. And even if I add it I still have the expected output 

```
➤ docker compose -f extends2.yml config
name: tmpdata20241157
services:
  test:
    command:
      - bash
      - -c
      - bash --version | grep release && ls -d /tmp/tmp.data20241157
    image: bash
    networks:
      default: null
    volumes:
      - type: bind
        source: /tmp/tmp.data20241157
        target: /tmp/tmp.data20241157
        bind: {}
networks:
  default:
    name: tmpdata20241157_default
```
