### ISSUE TITLE
Env files parsing

### ISSUE THREAD

**Issue by present-g** [docker/compose#12174]
We still have a problem with different parsing of env files in `docker compose` and `docker run`

Files:

`.env.test`
```bash
TEST_VAR='{"key": "value"}'
```

`test.Dockerfile`
```dockerfile
FROM ubuntu

CMD echo "$TEST_VAR"
```

`test.docker-compose.yaml`
```yaml
services:
  service:
    build:
      dockerfile: test.Dockerfile
    env_file: .env.test
    image: test-image
```

Execution:

`docker compose -f test.docker-compose.yaml up --build` => `{"key": "value"}`
`docker run --env-file .env.test test-image` => `'{"key": "value"}'`

We need unified results, otherwise, apps may not work correctly

Docker version 27.1.1, build 6312585
Docker Compose version v2.29.1-desktop.1

_Originally posted by @present-g in https://github.com/docker/compose/issues/2854#issuecomment-2383417633_

**Comment by ndeloof** [comment]
Docker Compose .env file parser is not strictly equivalent to the one used by `docker run`, because the former manages variable interpolation while the latter just consider values as raw string, including quotes.

There's no workaround for this. A possible fix would be to give you an option to explicitly request env file to be loaded without compose to manage values:
```yaml
services:
  service:
    env_file: 
      path: .env.test
      format: raw # default is to parse with interpolation
```
