### ISSUE TITLE
[BUG] strange interaction between create_host_path in bind mounts and mount commands

### ISSUE THREAD

**Issue by sprat** [docker/compose#12176]
### Description

There a strange interaction between `create_host_path` in bind mounts and services performing `mount` commands.

I get a `Error response from daemon: error while creating mount source path '/var/storage': mkdir /var/storage: file exists` with the following compose yaml file at the moment the `file` service starts, but only when the `storage_mount` service happens to create mountpoints.

But, if I omit the `create_host_path: true` in the second service, I also get an error: `Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/storage`.

There's a contradiction between the 2 situations, it seems to be a bug.

### Steps To Reproduce

Here is a "minimal" example demonstrating the problem:
```yaml
services:
  storage_mount:
    image: sprat/mergerfs:latest
    command:
      - /media/data*
      - /storage
      - -o
      - cache.files=partial,dropcacheonclose=true,category.create=mfs,func.getattr=newest,minfreespace=500M
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - type: bind
        source: /var/storage
        target: /storage
        bind:
          create_host_path: true
          propagation: shared

  files:
    image: alpine
    command: sleep infinity
    depends_on:
      storage_mount:
        condition: service_started
    volumes:
      - type: bind
        source: /var/storage
        target: /storage
        bind:
          create_host_path: true
          propagation: shared
```

### Compose Version

Docker Compose version v2.29.5

### Docker Environment

```
Client:
 Version:           27.2.1-rd
 API version:       1.45 (downgraded from 1.47)
 Go version:        go1.22.7
 Git commit:        cc0ee3e
 Built:             Tue Sep 10 15:42:54 2024
 OS/Arch:           windows/amd64
 Context:           default

Server:
 Engine:
  Version:          26.1.5
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       411e817ddf710ff8e08fa193da80cb78af708191
  Built:            Fri Jul 26 17:51:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.17
  GitCommit:        3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc:
  Version:          1.1.14
  GitCommit:        2c9f5602f0ba3d9da1c2596322dfc4e156844890
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Anything else?

Nope
