### ISSUE TITLE
Unexpected behavior with `docker compose down`

### ISSUE THREAD

**Issue by rojvv** [docker/compose#12196]
I have a compose file with 3 services:

```yaml
services:
    foo-api:
    bar-api:
    baz-api:
```

If I accidentally type `fooapi` with `docker compose down`, like this:

```shell
docker compose down fooapi
```

Then all services go down.

It must error instead. Or is this an intended behavior? Please enlighten me.
