### ISSUE TITLE
Variable interpolation doesn't give container environment variable default value when `.env` file didn't exists and shell environment variable is not set

### ISSUE THREAD

**Issue by afifurrohman-id** [docker/compose#12202]
### Description

Variable interpolation doesn't give container environment variable default value when `.env` file didn't exists and shell environment variable is not set.

when you have compose like this
```yaml
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}

```
and doesn't have a `.env` file and doesn't set any POSTGRES_* env in shell you will be have a warning: `WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string`.

why default value is not work in this case?

### Steps To Reproduce

- compose.yaml:
```yaml
services:
  db:
    container_name: postgres
    image: postgres:16.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}

```
- make sure doesn't have .env in current directory and also `POSTGRES_*` environment variable
- `docker compose up -d`

### Compose Version

Docker Compose version v2.29.7

### Docker Environment

lient: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 58
  Running: 37
  Paused: 0
  Stopped: 21
 Images: 31
 Server Version: 27.3.1
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.792GiB
 Name: foo-bar
 ID: b2b48662-aae9-415d-ad86-52e27957892a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
