### ISSUE TITLE
possible network docker bug without firewall (firewalld, iptables, ufw)

### ISSUE THREAD

**Issue by miavi** [docker/compose#12215]
Good day for all

I've been doing some tests on several servers (Redhat with firewalld, Ubuntu with ufw)

If I run a container, for example nginx with the following parameters in docker-compose

Create an alias, to connect vhost to a process running on the host locally, As you can see, the network is in bridge mode and the port forwarding is from 1080 on the host to 80 on the container, and from 1443 on the host to 443 on the container.

```
ports:
 - "0.0.0.0:1080:80"
 - "0.0.0.0:1443:443"
networks:
    - nginxnet
extra_hosts:
         host.docker.nginx: host-gateway


networks:
  nginxnet:
      external:false
      driver: bridge
      driver_opts:
              com.docker.network.enable_ipv6: "false"
```

On the host I have a python process that starts a service on the 8008

If inside the container I throw the following curl

```
curl http://host.docker.nginx:8008"
```

some result when executing

```
nc -vz host.docker.nginx 8008
or
nc -vz host.docker.nginx 22 (for example)
```

It returns an established connection, that is, I access a service on the host, from a container (all this with the firewalld, ufw disabled or with the default ACCEPT policy)

Under the hood, one of the advantages of docker is not the complete isolation of the container content from the host.
If the container was in network_mode: host, it would work when running as a local service (then curl should point to localhost, not the docker0 gw), but being bridged...
