### ISSUE TITLE
[BUG] "docker-compose config" consumes huge amounts of memory with broken config

### ISSUE THREAD

**Issue by ahollmann** [docker/compose#12235]
### Description

docker-compose config with the following config consumes huge amounts of memory. I had to SIGTERM it with ctrl-c in order not to run out of memory.

The config is obviously broken as `services:` is missing.

I'm using `docker-compose config` to verify if the config is correct so it seems to be valid use case.

Version used: Docker Compose version v2.29.7

```
x-healthcheck: &healthcheck
  healthcheck:
    test: [ "CMD", "wget", "--quiet", "--spider", "--timeout=1", "http://localhost:9000/health/live" ]
    start_period: 20s
    start_interval: 1s
    interval: 30s
    timeout: 2s
    retries: 5


  egress-service:
    <<: *healthcheck
```

### Steps To Reproduce

Create compose.yaml with folling input

```
x-healthcheck: &healthcheck
  healthcheck:
    test: [ "CMD", "wget", "--quiet", "--spider", "--timeout=1", "http://localhost:9000/health/live" ]
    start_period: 20s
    start_interval: 1s
    interval: 30s
    timeout: 2s
    retries: 5


  egress-service:
    <<: *healthcheck
```

run: docker-compose config

### Compose Version

Docker Compose version v2.29.7

### Docker Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

**Comment by idsulik** [comment]
@ahollmann Hi! I think the reason is the recursive alias. the `egress-service` is located inside the `healthcheck` alias and the `egress-service` uses the `healthcheck` alias

**Comment by ahollmann** [comment]
@idsulik Thanks. This seems to be the case.

Could the yaml parser detected cycles?

The `include:` feature checks for cycles and reports them:

```
include cycle detected:
/home/user/compose.yaml
 include /home/user/compose.yaml
```

**Comment by caseywebdev** [comment]
This fix broke references for services that are prefixed with the name of a preceding service.

docker-compose.yaml
```yaml
services:
  a: &a
    image: alpine
  a2: *a
```

```sh
$ dc config
cycle detected at path: services.a2
```

Switch the order and see that since the `services.a-test` prefix hasn't been seen at the point of `services.a`, it's fine:

docker-compose.yaml
```yaml
services:
  a2: &a
    image: alpine
  a: *a
```

```sh
$ dc config
...
services:
  a:
    image: alpine
    networks:
      default: null
  a2:
    image: alpine
    networks:
      default: null
...
```

The fix I believe would be to check the visited path plus a dot, so that at `services.a2.` in the example would not match the prefix check for `services.a.`
