### ISSUE TITLE
x-initialSync should always copy files and directories when --watch is passed

### ISSUE THREAD

**Issue by mvhatch** [docker/compose#12254]
### Description

Running `docker compose up --watch <service>` does not copy files or directories when the file/directory is modified before image creation, even when setting `x-initialSync: true`. Why not just copy the files/directories without checking its modified timestamp?

**Comment by ndeloof** [comment]
`x-initialSync` is an experimental extension (as the tag name suggests). Actual behavior is subject to changes.
We only sync files which aren't up-to-date with image as such a copy can impact a large number of files and can slow down initial start for no reason.
Can you please clarify your usage? Why would you need to sync files which are already up-to-date in built image ?

**Comment by mvhatch** [comment]
I have a monorepo with dozens of services. I have a single `compose.yml` file with a top-level anchor the defines some common attributes for a service, including a docker image. This docker image only provides some common utilities and dependencies, but it does _not_ copy any files from the monorepo. Instead, I'd like to specify a `develop` attribute for each service in my `compose.yml`, and watch a subset of files in my monorepo. 

So to answer your question:
> Why would you need to sync files which are already up-to-date in built image ?

Because there are no files in my built image. This seems to be a fairly common pattern (see thread [here](https://github.com/docker/compose/issues/11102#issuecomment-2442038839) asking for the same thing)

Does `docker compose cp` not copy the files a user requests because it could be a large number of files? Can you allow end users to copy a large number of files w/ `x-InitialSync` in the same vein? Alternatively, could you allow `docker compose --watch` to watch a subset of files, even if some of those files are already being bind-mounted?

**Comment by ndeloof** [comment]
> Because there are no files in my built image

Does this mean you can't run `docker compose up` with this image, without an extra step to copy content ?

Example on https://github.com/docker/compose/issues/11102 based on Traeffic demonstrate this misconception. `watch` should be used to make development iteration simpler and faster, but application _should_ be able to run without. A workaround is to add a Dockerfile to add required files, so that image you run has required content:
```yaml
services:
  traefik:
    build:
      dockerfile-inline: | 
        FROM: traefik:v2.10.7
        COPY ./traefik /etc/traefik
    develop:
      watch:
        - action: sync+restart
          path: ./traefik
          target: /etc/traefik
```

**Comment by mvhatch** [comment]
> Does this mean you can't run docker compose up with this image, without an extra step to copy content ?

Not entirely the case. Our Dockerfile has a volume section that uses env var interpolation (e.g. `${APP_HOST_MOUNT}`) that is properly set when executing `make run`. This bind mounts the developer's filesystem into the container. However, `make watch` sets the value to  `/dev/null` (because `docker compose watch` is unable to watch anything under a directory that is bind mounted) and then copies the contents if the filesystem into the docker container.

It's just a little annoying to do this hack, and I was hoping to get this functionality directly from `x-initialSync: true`.

**Comment by mmx86** [comment]
My use case is iIm syncing nginx configs directory from two different sources: service related and dev environment related. Second one is not synced initially.
```
    develop:
      watch:
        - action: sync+restart
          path: ./authz-proxy/nginx/
          target: /etc/nginx/
        - action: sync+restart
          path: ./dev/authz-proxy/nginx/
          target: /etc/nginx/
          x-initialSync: true
```
