### ISSUE TITLE
`depends_on` `post_start_completed_successfully`

### ISSUE THREAD

**Issue by stormshield-gt** [docker/compose#12279]
### Description

Since https://github.com/docker/compose/pull/12166 we have the `post_start` hook. A use case I have for this is to run some initialization code after the container starts. It will be great that other services than depend on the initialization code only start when it's completed successfully.
I don't know if it's planned but maybe we could have something like this:

```yaml
depends_on:
  db:
    condition: post_start_completed_successfully
```

**Comment by idsulik** [comment]
@stormshield-gt hi! Have you tried to start containers using `--wait` option? 
`docker compose up --wait`

**Comment by idsulik** [comment]
> It will be great that other services than depend on the initialization code only start when it's completed successfully.
it should work in this way not). 

```
services:
  app1:
    image: alpine
    command: echo 'app1 is completed'
    depends_on:
      - app2
  app2:
      image: alpine
      command: ["sh", "-c", "sleep 10 && echo 'app2 is completed'"]
      post_start:
        - command: ["sh", "-c", "sleep 5 && echo 'app2 post start hook executed'"]
```

output:
```
[+] Running 2/0
 ✔ Container tmp-app2-1  Created                                                                                                                                                                                                0.0s 
 ✔ Container tmp-app1-1  Created                                                                                                                                                                                                0.0s 
Attaching to app1-1, app2-1
app2-1 ->  | app2 post start hook executed
app1-1     | app1 is completed
app1-1 exited with code 0
app2-1     | app2 is completed
app2-1 exited with code 0
```
