### ISSUE TITLE
[BUG] x-app extra_hosts merging is failing

### ISSUE THREAD

**Issue by IgorIgnatevSky** [docker/compose#12273]
### Description

in the latest version of compose merging extra_hosts for x-app definition is broken, as a result with duplicates instead of merging compose starting to fail with the error 
```
extra_hosts array items[0,3] must be unique
```
broken version v2.29.7-desktop.1
working version v2.29.2-desktop.2

### Steps To Reproduce

eq 2 docker compose files
```
x-app:
  &app-common
  extra_hosts:
    - "host.docker.internal:host-gateway"
    - "app.local.site.com:host-gateway"
    - "api.local.site.com:host-gateway"
  image: app:latest

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    <<: *app-common
    cap_add:
      - "SYS_PTRACE"
```
```
x-app:
  &app-common
  extra_hosts:
    - "host.docker.internal:host-gateway"
    - "app.local.site.com:host-gateway"
    - "api.local.site.com:host-gateway"
    - "test.local.site.com:host-gateway"
  image: app:latest

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    <<: *app-common
    cap_add:
      - "SYS_PTRACE"
```

run 
```
docker compose -f docker-compose.yml -f docker-compose.test.yml config
```

result with v2.29.2-desktop.2 extra_hosts succesfully merged
```
name: composetest
services:
  app:
    build:
      context: /Users/myusername/temp/composetest
      dockerfile: docker/php/Dockerfile
      target: dev
    cap_add:
      - SYS_PTRACE
    extra_hosts:
      - api.local.site.com=host-gateway
      - app.local.site.com=host-gateway
      - host.docker.internal=host-gateway
      - test.local.site.com=host-gateway
    image: app:latest
    networks:
      default: null
networks:
  default:
    name: composetest_default
x-app:
  extra_hosts:
    - host.docker.internal:host-gateway
    - app.local.site.com:host-gateway
    - api.local.site.com:host-gateway
    - test.local.site.com:host-gateway
  image: app:latest
```

but with version v2.29.7-desktop.1
```
validating /Users/myusername/temp/composetest/docker-compose.test.yml: services.app.extra_hosts array items[0,3] must be unique
```

### Compose Version

Docker Compose version v2.29.7-desktop.1

### Docker Environment

Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1-desktop.1
    Path:     /Users/myusername/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7-desktop.1
    Path:     /Users/myusername/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/myusername/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/myusername/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/myusername/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/myusername/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/myusername/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/myusername/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/myusername/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.14.0
    Path:     /Users/myusername/.docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 18
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.653GiB
 Name: docker-desktop
 ID: 535eb28f-cc02-45ef-9e4a-699ebf2dceac
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/myusername/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
