### ISSUE TITLE
[BUG] Cannot properly list variables with numbers in the key

### ISSUE THREAD

**Issue by MikaelElkiaer** [docker/compose#12285]
### Description

While the variables are correctly interpolated, it does not display them properly when listing them with `docker compose config --variables`.
When using environment variables that contain numbers in the key - e.g. `${X2}`, it will stop parsing the name once the digit is reached.

### Steps To Reproduce

1. Using a simple config:
    ```yaml
    services:
      test:
        image: alpine
        environment:
          X: ${WORKS}
          Y: ${ALSO_WORKS:-with-default}
          Z: ${BROKEN_1}
          ZZ: ${ALSO_BROKEN_1:-with-default}
    ```
2. Running `docker compose config --variables`

The output is:

```
NAME                REQUIRED            DEFAULT VALUE       ALTERNATE VALUE
ALSO_WORKS          false               with-default        
BROKEN_             false                                   
ALSO_BROKEN_        false                                   
WORKS               false                                   
```

Note that the output for other commands still works as expected:

<details><summary>`docker compose config`</summary>

```yaml
WARN[0000] The "WORKS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BROKEN_1" variable is not set. Defaulting to a blank string. 
name: compose-variables-with-numbers
services:
  test:
    environment:
      X: ""
      "Y": with-default
      Z: ""
      ZZ: with-default
    image: alpine
    networks:
      default: null
networks:
  default:
    name: compose-variables-with-numbers_default
```
</details> 

<details><summary>`docker compose config --no-interpolate`</summary>

```yaml
name: compose-variables-with-numbers
networks:
  default:
    name: compose-variables-with-numbers_default
services:
  test:
    environment:
      X: ${WORKS}
      "Y": ${ALSO_WORKS:-with-default}
      Z: ${BROKEN_1}
      ZZ: ${ALSO_BROKEN_1:-with-default}
    image: alpine
    networks:
      default: null
```

</details> 

### Compose Version

```Text
Docker Compose version v2.29.7
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 34
  Running: 29
  Paused: 0
  Stopped: 5
 Images: 40
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-26-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.13GiB
 Name: czc2208rnd.alb.is.keysight.com
 ID: 496991a1-af57-45ad-bb84-407b4ebe1a5e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
