### ISSUE TITLE
[BUG] mount nfs volume in docker-compose.yml issue

### ISSUE THREAD

**Issue by volpx** [docker/compose#12308]
### Description

It might be a bug since i cannot find solution online.
Mounting nfs share directly to a container works when using `docker run` but not when using a compose file with `docker compose`.

### Steps To Reproduce

1. Debian bookworm 
2. I have the following `docker-compose.yml` which mounts a nfs share volume directly in the container:
```
name: hello

services:
  hello:
    image: alpine:latest  # Example image, replace with your desired image
    command: tail -f /dev/null  # Keeps the container running
    volumes:
      - my_nfs_volume:/mnt/nfs  # Mount the NFS share to /mnt/nfs in the container

volumes:
  my_nfs_volume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,rw,nfsvers=4.1"  # NFS options: rw, nolock, and soft mount
      device: ":/immich"  # NFS server IP and share path
```
3. doing `docker compose up -d` gives:
`Error response from daemon: error while mounting volume '/var/lib/docker/volumes/hello_my_nfs_volume/_data': failed to mount local volume: mount :/immich:/var/lib/docker/volumes/hello_my_nfs_volume/_data, data: addr=192.168.1.100,nolock,soft: permission denied
`

4. However, not using the compose file and running directly
`docker run -it --name try --mount 'type=volume,source=nfs_try,target=/mnt/nfs,volume-driver=local,volume-opt=type=nfs,"volume-opt=o=addr=192.168.1.100,rw,nfsvers=4.1",volume-opt=device=:/immich' alpine:latest`
works fine and i can access the files in the share from the container shell.

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.29.7
```

### Docker Environment

```Text
$ docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 6
  Paused: 0
  Stopped: 8
 Images: 10
 Server Version: 27.3.1
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-26-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.41GiB
 Name: [hostname]
 ID: 39ef1582-be9b-4190-805c-3ddf8bb44e79
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by ndeloof** [comment]
Your `docker run` command isn't equivalent to `docker compose up` as it uses the `--mount` flag.
Can you please try to use `docker volume create ...` to create the NFS volume, then use `docker run -v <volume>:<target>`

**Comment by ndeloof** [comment]
compose equivalent would be:
```yaml
(...)
    volumes:
      - source: ./web/dist
        target: /usr/share/nginx/html
        volume:
          <driver and options> # this is not supported by the spec, seems nobody asked for it 😅
```
