### ISSUE TITLE
[BUG] docker compose up --watch with sync+restart ends up disconnecting from watch

### ISSUE THREAD

**Issue by torarnv** [docker/compose#12317]
### Description

Similar to https://github.com/docker/compose/issues/11773 I'm seeing `docker compose up --watch` disconnecting when the container is restarted:

```
❯ docker compose up --watch
[+] Running 1/0
 ✔ Container caddy-caddy-1  Running                                                        0.0s
        ⦿ Watch enabled
Attaching to caddy-1
         ⦿ Syncing and restarting service "caddy" after 1 changes were detected
caddy-1  | 2024/11/23 00:42:30.609	INFO	shutting down apps, then terminating	{"signal": "SIGTERM"}
caddy-1  | 2024/11/23 00:42:30.609	WARN	exiting; byeee!! 👋	{"signal": "SIGTERM"}
caddy-1  | 2024/11/23 00:42:30.609	INFO	http	servers shutting down with eternal grace period
caddy-1  | 2024/11/23 00:42:30.609	INFO	admin	stopped previous server	{"address": "localhost:2019"}
caddy-1  | 2024/11/23 00:42:30.609	INFO	shutdown complete	{"signal": "SIGTERM", "exit_code": 0}
         ⦿ service "caddy" restarted
caddy-1 exited with code 0
         ⦿ Syncing and restarting service "caddy" after 1 changes were detected
caddy-1  | 2024/11/23 00:42:39.434	INFO	shutting down apps, then terminating	{"signal": "SIGTERM"}
caddy-1  | 2024/11/23 00:42:39.434	WARN	exiting; byeee!! 👋	{"signal": "SIGTERM"}
caddy-1  | 2024/11/23 00:42:39.434	INFO	http	servers shutting down with eternal grace period
caddy-1  | 2024/11/23 00:42:39.434	INFO	admin	stopped previous server	{"address": "localhost:2019"}
caddy-1  | 2024/11/23 00:42:39.434	INFO	shutdown complete	{"signal": "SIGTERM", "exit_code": 0}
caddy-1 exited with code 0
         ⦿ Watch disabled

❯
```

```
services:
  caddy:
    image: torarnv/caddy
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"

    develop:
      watch:
        - action: sync+restart
          path: ./Caddyfile
          target: /etc/caddy/Caddyfile
```

Likely because it temporarily sees that there are no services running.

Adding a keep-alive workaround service "fixes" the issue:

```
dummy-watch-workaround:
  image: alpine:latest
  init: true
  command: ["sh", "-c", "while true; do sleep 2; done"]
```

### Compose Version

```Text

```

### Docker Environment

```Text

```

**Comment by ndeloof** [comment]
I tried to reproduce without success.

I'm using:
```yaml
services:
  app1:
    build:
      dockerfile_inline: FROM nginx
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /tmp
```

Can you please give it a try?

**Comment by torarnv** [comment]
@ndeloof  this still reproduces for me:

```
services:
  caddy-reproducer:
    image: caddy:2.9.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    develop:
      watch:
        - action: sync+restart
          path: .
          target: /tmp
```

```
❯ docker compose up --watch                                                                                                                                                                                                                                 8s
[+] Running 1/1
 ✔ Container caddyrepo-caddy-reproducer-1  Recreated                                                                                                                                                                                                      0.2s
        ⦿ Watch enabled
Attaching to caddy-reproducer-1
caddy-reproducer-1  | {"level":"warn","ts":1742049446.3041916,"msg":"failed to set GOMAXPROCS","error":"open /sys/fs/cgroup/cpu/cpu.cfs_quota_us: no such file or directory"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3048794,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3058498,"msg":"adapted config to JSON","adapter":"caddyfile"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3072276,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
caddy-reproducer-1  | {"level":"warn","ts":1742049446.3081517,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3084567,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000145480"}
caddy-reproducer-1  | {"level":"warn","ts":1742049446.308958,"logger":"http","msg":"HTTP/2 skipped because it requires TLS","network":"tcp","addr":":80"}
caddy-reproducer-1  | {"level":"warn","ts":1742049446.308987,"logger":"http","msg":"HTTP/3 skipped because it requires TLS","network":"tcp","addr":":80"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3090036,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3100202,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3100362,"msg":"serving initial configuration"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3114846,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/data/caddy"}
caddy-reproducer-1  | {"level":"info","ts":1742049446.3122306,"logger":"tls","msg":"finished cleaning storage units"}
                    ⦿ Syncing and restarting service "caddy-reproducer" after 1 changes were detected
caddy-reproducer-1  | {"level":"info","ts":1742049452.269159,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
caddy-reproducer-1  | {"level":"warn","ts":1742049452.2692258,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
caddy-reproducer-1  | {"level":"info","ts":1742049452.2692566,"logger":"http","msg":"servers shutting down with eternal grace period"}
caddy-reproducer-1  | {"level":"info","ts":1742049452.269483,"logger":"admin","msg":"stopped previous server","address":"localhost:2019"}
caddy-reproducer-1  | {"level":"info","ts":1742049452.2694945,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}
caddy-reproducer-1 exited with code 0
```
