### ISSUE TITLE
Watch: sync+reload mode

### ISSUE THREAD

**Issue by torarnv** [docker/compose#12318]
### Description

Sometimes the container supports explicit reloads of the config. E.g. Caddy can do `caddy reload --config /etc/caddy/Caddyfile`

In this mode the container doesn't need to be restarted, it's enough to do sync+reload (not sync+restart).

Would be nice if there was a `sync+reload` mode where a custom reload command could be provided.

Not having to restart the container would mitigate issues like https://github.com/docker/compose/issues/12317

**Comment by ndeloof** [comment]
For your use-case, we could introduce:
```yaml
      watch: 
        - path: ./webapp/html
          action: sync+exec
          target: /var/www
          exec: <command to run in container by docker exec ...>
```

note: A comparable use-case could require to send a signal to container, typically SIGHUP to force a reset/reconfiguration of the service. Container's entrypoint could catch such a signal to run a custom command
