### ISSUE TITLE
Make Docker overlay network use a custom overlay network as the default for eth0 instead of the ingress network.

### ISSUE THREAD

**Issue by seqwait** [docker/compose#12323]
### Description

how to Make Docker overlay network use a custom overlay network as the default for eth0 instead of the ingress network.
```

version: '3.8'
services:
  app:
    image: praqma/network-multitool
    environment:
      DUBBO_IP_TO_REGISTRY: "{{.Service.Name}}"
      JAVA_OPTS: "-Xms512M -Xmx2048M"
      RUN_OPTS: "--spring.profiles.active=prod --app.name=app"
    ports:
      - target: 18081
        published: 18081
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      my_overall:
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.my.app == yes"
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first

networks:
  my_overall:
    external: true
    name: my_overall
    attachable: true

```

**Comment by ndeloof** [comment]
I'm not sure I understand what you're asking for.
Using a simple example:
```yaml
services:
  test:
    image: alpine
    networks:
      - test

networks:
  test: {}
```

I can get container's `eth0` to be attached to the expected network:
```
$ docker compose run test ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:18:00:02  
          inet addr:172.24.0.2  Bcast:172.24.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:260 (260.0 B)  TX bytes:0 (0.0 B)
```
