### ISSUE TITLE
[BUG] `depends_on` is NOT ignored when extending from a service

### ISSUE THREAD

**Issue by LennyN95** [docker/compose#12360]
### Description

According to the documentation, the `depends_on` declaration should not be derived when extending a service:

> volumes_from and **depends_on are never shared between services that use extends**. These exceptions exist to avoid implicit dependencies; you always define volumes_from locally. This ensures that the dependencies between the services are clearly visible when reading the current file. The local definition also ensures that changes to the referenced file do not break anything.
https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/

However, if you extend a service that depends on a service that is not declared in the compose file, an error is issued:

> service "aaa" depends on undefined service "bbb": invalid compose project

I **didn't expect an error** because according to the documentation `depends_on` should never be shared between services with extends.

### Steps To Reproduce

compose.yaml

```yaml
name: setup

services:
   aaa:
      depends_on:
          bbb:
             condition: service_healthy
   bbb:
```

compose2.yaml
```yaml
name: setup

services:
   aaa:
      extends:
         file: compose.yaml
         service: aaa
```

run command:
```bash
docker compose -f compose2.yaml up -d
```

### Compose Version

```Text
Docker Compose version v2.30.3-desktop.1
```

### Docker Environment

```Text

```

### Anything else?

I reduced the configuration to only the parts causing the problem.

**Comment by idsulik** [comment]
Here's what I got - `service "aaa" has neither an image nor a build context specified: invalid compose project`. 

compose.yaml
```
name: setup

services:
  aaa:
    depends_on:
      bbb:
        condition: service_healthy
  bbb:
```

compose.yaml
```
name: setup

services:
  aaa:
    extends:
      file: compose.yaml
      service: aaa
```

![Image](https://github.com/user-attachments/assets/6eaa7554-33bc-452a-be3f-849176ed7c64)
