### ISSUE TITLE
`extends` to not require separate file

### ISSUE THREAD

**Issue by imrawa** [docker/compose#1237]
Just found out about the `extends` feature recently added and has helped to cut down a lot of repeated configuration. Would it be possible to alter it such that if `file` is not defined then search for the service within the current file.

E.g.

```
app:
  environment:
    - A=X
    - B=Y
  volumes:
    - /var/log:/var/log
    -/etc/localtime:/etc/localhost:ri
  restart: on-failure

application:
  extends:
    service: app
  volumes_from:
    - otherapp
  links:
    - db:db
```

This should still be backwards compatible with how it currently works.
