### ISSUE TITLE
[BUG] `depends_on` stripped for extended services

### ISSUE THREAD

**Issue by stormshield-fabs** [docker/compose#12402]
### Description

When a service uses both `extends` and `depends_on`, the `depends_on` map is stripped in the rendered configuration.

### Steps To Reproduce

Run `docker compose config` with the following file

```yaml
services:
  service_a:
    image: alpine:latest
  
  service_b:
    extends: service_a
    depends_on:
      service_a:
        condition: service_completed_successfully
```

Docker 27.4.0 (compose 2.31.0):

```yaml
name: docker
services:
  service_a:
    image: alpine:latest
    networks:
      default: null
  service_b:
    depends_on:
      service_a:
        condition: service_completed_successfully
        required: true
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: docker_default
```

Docker 27.4.1 (compose 2.32.1):

```yaml
name: docker
services:
  service_a:
    image: alpine:latest
    networks:
      default: null
  service_b:
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: docker_default
```

(note the missing `depends_on`)

### Compose Version

```Text
Docker Compose version v2.32.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-49-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.01GiB
 Name: REDACTED
 ID: e6b3efa0-3763-471b-96a3-9166fee1ce35
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

This might be related to https://github.com/docker/compose/issues/12360 and https://github.com/compose-spec/compose-go/pull/718
