### ISSUE TITLE
Scale a container specifying ports

### ISSUE THREAD

**Issue by thalescm** [docker/compose#1241]
Currently the `docker-compose scale` command creates random ports for the new containers.

Is there a way to specify a port for the new containers?

**Comment by awarddev** [comment]
I'm wondering the same thing.

**Comment by arthurtsang** [comment]
in your docker-compose.xml, 

```
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432:5432
```

it will bind to 5432, however, note that you can't have more than one instance on the same node for obvious reason.

**Comment by mandb** [comment]
I think what would be valuable here is the ability to do:

```yaml
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432+:5432
```

Thus allowing the scale=4 to create 4 instances exposed on 5432, 5433, 5434, 5435, but all routing to their internal ports.  The reasons for this over a separate linked haproxy instance are many.

Naming convention and definitions here is open to improvement obviously.
