### ISSUE TITLE
[BUG] Since 2.32.1 volumes_from is ignored when used in an 'extends' file to extend service with content in another file

### ISSUE THREAD

**Issue by calebgcooper** [docker/compose#12417]
### Description

Tested with Since 2.31.0 and this issue is not present.

When a separate file is used to extend a service and volumes_from is used in that seperate file it is ignored.

### Steps To Reproduce

Sample compose file:
```
[root@apps1-cwd.devops Ϯ test]$ cat docker-compose.yml 
x-source-image: &source-image 'gitlab-registry.cwd.supportlabs.dell/mediawiki/min/source:1.43.0'

services:
  source:
    image: *source-image

  php:
    extends:
      file: extras.yml
      service: php
    image: php:8.3.14-fpm-alpine3.21
    container_name: php

  web-server:
    image: nginx:1.27.3-alpine3.20
    container_name: web
    volumes_from:
      - source
[root@apps1-cwd.devops Ϯ test]$ 
```

Sample extended services file:
```
x-source-image: &source-image 'gitlab-registry.cwd.supportlabs.dell/mediawiki/min/source:1.43.0'

services:
  source:
    image: *source-image

  php:
    volumes_from:
      - source
```

If I do `docker-compose up -d` (version 2.31.0) and check mounts for 'php' service we can see 4 volumes where are all defined in the Docker file of the 'source' image:
```
[root@apps1-cwd.devops Ϯ test]$ docker inspect -f '{{json .Mounts }}' php | jq 
[
  {
    "Type": "volume",
    "Name": "520ecd4efecf28f2824df0fd77532a2beb4096597ced08d81bd045be90ffe8f4",
    "Source": "/var/lib/docker/volumes/520ecd4efecf28f2824df0fd77532a2beb4096597ced08d81bd045be90ffe8f4/_data",
    "Destination": "/var/www/html",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "volume",
    "Name": "cbd625fe686e6e3ff36eda0f755395f9b60e3047e0bb2daceac417dbd7b57a02",
    "Source": "/var/lib/docker/volumes/cbd625fe686e6e3ff36eda0f755395f9b60e3047e0bb2daceac417dbd7b57a02/_data",
    "Destination": "/wiki-shared/vars",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "volume",
    "Name": "c6d678248efdcbf873a5780fa1c8d742c8fd412f333ae79bfb6e2f9ef1fa492e",
    "Source": "/var/lib/docker/volumes/c6d678248efdcbf873a5780fa1c8d742c8fd412f333ae79bfb6e2f9ef1fa492e/_data",
    "Destination": "/build-scripts",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "volume",
    "Name": "dcf640e0d6f129e583034b70458b94476df027c6107c18d21e7a506a492dc874",
    "Source": "/var/lib/docker/volumes/dcf640e0d6f129e583034b70458b94476df027c6107c18d21e7a506a492dc874/_data",
    "Destination": "/tmp",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```

If I do `docker compose up -d`  (version 2.32.1)  and check mounts there are zero volumes listed:
```
[root@apps1-cwd.devops Ϯ test]$ docker inspect -f '{{json .Mounts }}' php | jq 
[]
[root@apps1-cwd.devops Ϯ test]$
```

However for the 'web' service with volumes_from in the same file I see all the volumes:
```
[root@apps1-cwd.devops Ϯ test]$ docker inspect -f '{{json .Mounts }}' web | jq 
[
  {
    "Type": "volume",
    "Name": "60647d8d550dc9f1036b1a78c589e5cf8c572afb63bb3eff7cb61eeb60f2def6",
    "Source": "/var/lib/docker/volumes/60647d8d550dc9f1036b1a78c589e5cf8c572afb63bb3eff7cb61eeb60f2def6/_data",
    "Destination": "/wiki-shared/vars",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "volume",
    "Name": "5a62f63c2f7e08d668066923e6b09992c597f273d024b00c4bc01ebe8d17fa18",
    "Source": "/var/lib/docker/volumes/5a62f63c2f7e08d668066923e6b09992c597f273d024b00c4bc01ebe8d17fa18/_data",
    "Destination": "/build-scripts",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "volume",
    "Name": "023c0e1a6151065bea1ad999a4d463da9b35e41b2f89a0385c920d1f8efcdec8",
    "Source": "/var/lib/docker/volumes/023c0e1a6151065bea1ad999a4d463da9b35e41b2f89a0385c920d1f8efcdec8/_data",
    "Destination": "/tmp",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "volume",
    "Name": "edf983a26f5063666ebd012cf41edd7d515ca81acec43ac44c3ffac665a3e64a",
    "Source": "/var/lib/docker/volumes/edf983a26f5063666ebd012cf41edd7d515ca81acec43ac44c3ffac665a3e64a/_data",
    "Destination": "/var/www/html",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
[root@apps1-cwd.devops Ϯ test]$ 
```

### Compose Version

```Text
- source
[root@apps1-cwd.devops Ϯ test]$ docker compose version
Docker Compose version v2.32.1
[root@apps1-cwd.devops Ϯ test]$ docker-compose version
Docker Compose version v2.31.0
[root@apps1-cwd.devops Ϯ test]$
```

### Docker Environment

```Text
[root@apps1-cwd.devops Ϯ test]$ docker info
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 70
  Running: 42
  Paused: 0
  Stopped: 28
 Images: 32
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-427.35.1.el9_4.x86_64
 Operating System: Rocky Linux 9.5 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.09GiB
 Name: apps1-cwd.devops.supportlabs.dell
 ID: a3889f80-73ea-4e51-a48d-f69b8cc07881
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
