### ISSUE TITLE
[BUG] `depends_on` no longer repected while extending another service

### ISSUE THREAD

**Issue by arbaes** [docker/compose#12414]
### Description

With latest Docker Compose version (2.32.1), it seems that the `depends_on` sections are completely ignored if the service is using the `extend` section

### Steps To Reproduce

**Config**

The following files:

`docker-templates.yml`
```yml
version: "3"

services:
    tpl:
        environment:
            # Some stuff
        volumes:
            # Some other stuff
```

`docker-compose`
```yml
services:
    dns:
        image: psitrax/powerdns
        healthcheck:
            test: ["CMD", "pdns_control", "rping"]
            interval: 1s
            retries: 5

    service_a:
        extends:
             file: "docker-templates.yml"
             service: tpl
        depends_on:
            dns:
                condition: service_healthy
```

**Command**
`docker compose config`

This will completely ignore the `depends_on` section on `service_a` as long as the `extends` section is present

### Compose Version

```Text
Docker Compose version 2.32.1
```

### Docker Environment

```Text
Client:
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.32.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 5
  Paused: 0
  Stopped: 4
 Images: 142
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88aa2f531d6c2922003cc7929e51daf1c14caa0a.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.12.4-zen1-1-zen
 Operating System: EndeavourOS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 19.4GiB
 Name: G2-ARE
 ID: XDSS:5JF4:RHWW:XKEW:MGIK:2AYO:X6JL:YXR6:SUUS:4USC:SL5O:A3J3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Anything else?
I can confirm I don't have the issue by downgrading to `Docker Compose version 2.32.0`
