### ISSUE TITLE
[BUG] `depends_on` is ignored when service `extends` from file in v2.32.0

### ISSUE THREAD

**Issue by yariksheptykin** [docker/compose#12434]
### Description

As of compose v2.32.0 `depends_on` on the extending service has no effect. When a service is extending another service declared in a separate file and additionally declares `depends_on` configuration, the `depends_on` is being silently dropped. When replacing `depends_on` with `links` configuration both `links` and `depends_on` are defined on the extending service.

Here is a toy example.

`cat extend-me.yaml`:
```yaml
services:
  nginx:
    image: nginx
```

`cat compose.yaml`:
```yaml
services:
  webserver:
    extends:
      service: nginx
      file: ./extend-me.yaml
    depends_on:
      - app

  explicit-link:
    extends:
      service: nginx
      file: ./extend-me.yaml
    depends_on:
      - app
    links:
      - app

  app:
    image: php
```

```shell
docker compose version
Docker Compose version v2.32.0
```

```shell
docker compose config webserver
name: it-depends
services:
  webserver:
    image: nginx
    networks:
      default: null
networks:
  default:
    name: it-depends_default
```

Note the missing `depends_on` in the output. The configuration for the `explicit-link` correctly lists the dependency:

```shell
docker compose config explicit-link 
name: it-depends
services:
  app:
    image: php
    networks:
      default: null
  explicit-link:
    depends_on:
      app:
        condition: service_started
        restart: true
        required: true
    image: nginx
    links:
      - app
    networks:
      default: null
networks:
  default:
    name: it-depends_default
```

Same example with another compose build:

```shell
docker compose version
Docker Compose version v2.31.0-desktop.2
```

```shell
docker compose config webserver
name: it-depends
services:
  app:
    image: php
    networks:
      default: null
  webserver:
    depends_on:
      app:
        condition: service_started
        required: true
    image: nginx
    networks:
      default: null
networks:
  default:
    name: it-depends_default
```

Note the v2.31.0 desktop build does list the `depends_on` as expected.

### Compose Version

```Text
v2.32.0
```

### Docker Environment

```Text

```
