### ISSUE TITLE
[BUG] Cannot override extra_hosts

### ISSUE THREAD

**Issue by dcendents** [docker/compose#12431]
### Description

This is the exact same issue I reported that came back: https://github.com/docker/compose/issues/9361
It started from version 2.24.6 onwards.

Overriding `extra_hosts` does not work, both values get added.

### Steps To Reproduce

With the following `compose-bug/common_config.yml`:
```yaml
services:
  common_config:
    extra_hosts:
      - "extra3.domain.org:10.0.0.3"
      - "extra4.domain.org:10.0.0.4"

  test_config:
    extra_hosts:
      - "extra3.domain.org:192.168.1.103"
      - "extra4.domain.org:192.168.1.104"
```

And the following `compose-bug/docker-compose.yml`:
```yaml
services:
  app:
    image: busybox
    extra_hosts:
      - "extra1.domain.org:10.0.0.1"
      - "extra2.domain.org:10.0.0.2"

  app2:
    image: busybox
    extends:
      file: common_config.yml
      service: common_config
```

and the following `compose-bug/docker-compose.override.yml`:
```yaml
services:
  app:
    extra_hosts:
      - "extra1.domain.org:192.168.1.101"
      - "extra2.domain.org:192.168.1.102"

  app2:
    image: busybox
    extends:
      file: common_config.yml
      service: test_config
```

`docker compose config` version `2.32.1` gives me the following output:

```yaml
name: compose-bug
services:
  app:
    extra_hosts:
      - extra1.domain.org=10.0.0.1
      - extra1.domain.org=192.168.1.101
      - extra2.domain.org=10.0.0.2
      - extra2.domain.org=192.168.1.102
    image: busybox
    networks:
      default: null
  app2:
    extra_hosts:
      - extra3.domain.org=10.0.0.3
      - extra3.domain.org=192.168.1.103
      - extra4.domain.org=10.0.0.4
      - extra4.domain.org=192.168.1.104
    image: busybox
    networks:
      default: null
networks:
  default:
    name: compose-bug_default
```

While with older version `2.24.5` I was getting:

```yaml
name: compose-bug
services:
  app:
    extra_hosts:
      - extra1.domain.org=192.168.1.101
      - extra2.domain.org=192.168.1.102
    image: busybox
    networks:
      default: null
  app2:
    extra_hosts:
      - extra3.domain.org=192.168.1.103
      - extra4.domain.org=192.168.1.104
    image: busybox
    networks:
      default: null
networks:
  default:
    name: compose-bug_default
```

### Compose Version

```Text
Docker Compose version v2.32.1

Command 'docker-compose' not found, but can be installed with:
sudo snap install docker          # version 27.2.0, or
sudo apt  install docker-compose  # version 1.29.2-1
See 'snap info docker' for additional versions.
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 371
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-130-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: ************
 ID: 941e0fef-8390-4e09-9850-64b984bf8422
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.17.0.0/16, Size: 16
   Base: 172.20.0.0/14, Size: 20
   Base: 172.24.0.0/13, Size: 20
   Base: 192.168.0.0/16, Size: 24
```

**Comment by ndeloof** [comment]
To replace a list content in an override file, use `!override`:

```yaml
services:
  app:
    extra_hosts: !override
      - "extra1.domain.org:192.168.1.101"
      - "extra2.domain.org:192.168.1.102"
```
