### ISSUE TITLE
[BUG] `depends_on` a service from `include` disappears in the final rendered compose YAML

### ISSUE THREAD

**Issue by outsinre** [docker/compose#12447]
### Description

I have an `include` directive to include a common service `postgres`, and `depends_on` the included `postgres`. I need the `postgres` service to run first.

However, in the final rendered `docker compose convert`, the `depends_on` disappears.

### Steps To Reproduce

1. `mg-compose.yaml`

    ```yaml
    name: mg

    include:
    - path:
      - pg-compose.yaml
    
    x-environment: &env
      VAR_DEMO: foo
    
    services:
      kong-migrations:
        image: kong/kong-gateway:3.8.1.0
        depends_on:
          postgres:
            condition: service_healthy
            restart: false
        extends:
          file: shared-env-compose.yaml
          service: shared-env
        environment:
          <<: *env
          KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
        entrypoint: ""
        command: |-
          /bin/bash -c "
            kong migrations bootstrap -v"
        restart: no
    ```

2. `pg-compose.yaml`

    ```yaml
    name: pg
    
    services:
      postgres:
        image: postgres:latest
        ports:
        - "5432"
        volumes:
        - postgres-data:/var/lib/posgresql/data
        environment:
          POSTGRES_USER: pg
          POSTGRES_PASSWORD: pg
          POSTGRES_DB: pg
          PGPASSWORD: pg
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "pg"]
          interval: 5s
          timeout: 10s
          retries: 10
        restart: on-failure
    
    volumes:
      postgres-data:
    ```

3. `shared-env-compose.yaml`

    ```yaml
    name: shared-env
    
    services:
      shared-env:
        environment:
          BAR: baz
    ```

4. Rendered Compose YAML `docker compose -f mg-compose.yaml convert`.

   The `depends_on` disappears from the output.

    ```yaml
    name: mg
    services:
      kong-migrations:
        command:
          - /bin/bash
          - -c
          - |2-
              kong migrations bootstrap -v
        entrypoint: []
        environment:
          BAR: baz
          KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
          VAR_DEMO: foo
        image: kong/kong-gateway:3.8.1.0
        networks:
          default: null
        restart: "no"
      postgres:
        environment:
          PGPASSWORD: pg
          POSTGRES_DB: pg
          POSTGRES_HOST_AUTH_METHOD: scram-sha-256
          POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
          POSTGRES_PASSWORD: pg
          POSTGRES_USER: pg
        healthcheck:
          test:
            - CMD
            - pg_isready
            - -U
            - pg
          timeout: 10s
          interval: 5s
          retries: 10
        image: postgres:latest
        networks:
          default: null
        ports:
          - mode: ingress
            target: 5432
            protocol: tcp
        restart: on-failure
        volumes:
          - type: volume
            source: postgres-data
            target: /var/lib/posgresql/data
            volume: {}
    networks:
      default:
        name: mg_default
    volumes:
      postgres-data:
        name: mg_postgres-data
    x-environment:
      VAR_DEMO: foo
    ```

### Compose Version

```Text
~ $ docker compose version
Docker Compose version 2.32.1

~ $ docker-compose version
Docker Compose version 2.32.1
```

### Docker Environment

```Text
~ $ docker info
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    colima
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /opt/homebrew/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.32.1
    Path:     /opt/homebrew/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 20
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-50-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.738GiB
 Name: colima
 ID: 51e846b0-facd-4405-817c-639bc55c24f8
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: kongbot
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Not sure related to https://github.com/compose-spec/compose-spec/issues/554.
