### ISSUE TITLE
Docker-compose not accepting 'extends' option in docker-compose.yml file

### ISSUE THREAD

**Issue by sunnysingh1985** [docker/compose#1245]
Given a "docker-compose.yml":

```yml
web:
 extends:
  file: common.yml
  service: webapp
```
and another "common.yml":
```yml
webapp:
 image: ubuntu
```
Executing 'docker-compose ps' throws following error:

```sh
$ docker-compose ps
$ Unsupported config option for web service: 'extends'
```
