### ISSUE TITLE
[BUG] depends_on not working for services defined using extends in v2.32

### ISSUE THREAD

**Issue by paul-mcculloch** [docker/compose#12460]
### Description

depends_on seems to have no effect when specified in a service which uses extends. I expect to be able to define a service using extends and to be able to specify which other services should be started by compose. 

### Steps To Reproduce

1. Create a compose.yml:
```
services: 
  redis1:
    image: "redis:alpine"
   mybase:
    image: "redis:alpine"
    depends_on:
#    	This should be ignored in #services which extend mybase per the documentation
        - redis2

  extenddepend:
    extends: 
        service: mybase
    depends_on:
            - redis1

```
2. run `docker compose -f compose.yml config extenddepend`
3. The output will include:
```
services:
  extenddepend:
    image: redis:alpine
    networks:
      default: null
```
i.e. the `depends_on: redis1` is ignored.

The dependency is also ignore if `run extenddepend` or `up extenddepend` are invoked

Compare this with the behavior in 2.31.0 where `docker compose -f compose.yml config extenddepend` includes:
```
services:
  extenddepend:
    depends_on:
      redis1:
        condition: service_started
        required: true
      redis2:
        condition: service_started
        required: true
    image: redis:alpine
    networks:
      default: null
```
I think this behavior is wrong too. The docs (https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/#exceptions-and-limitations) state "depends_on are never shared between services using extends", so I would expect only a dependency on redis1.

### Compose Version

```Text
Docker Compose version v2.32.1
docker-compose not present
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.4.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.3
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.32.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.4.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-51-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.756GiB
 Name: ubuntu-22-docker-1
 ID: 2b90efc9-71d2-45ec-a96e-bed56bb0d22f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

docker was installed via apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin on Ubuntu 22.04.5 under VirtualBox
