### ISSUE TITLE
[BUG] image not matching windows version does not run correctly even when specifying isolation: hyperv

### ISSUE THREAD

**Issue by asdkant-bf** [docker/compose#12481]
### Description

I am attempting to run a windows image not matching the host OS version. I enabled Hyper-V, and am passing `isolation: hyperv` in the service section of the compose file.

when I use `docker run` directly it works (the host is Server 2022):
```powershell
docker run -it --isolation=hyperv mcr.microsoft.com/windows/nanoserver:ltsc2019 cmd
```

but when running this compose (taken from an example):
```yaml
version: '2.4'
services:
  traefik:
    image: stefanscherer/traefik-windows
    command: --docker.endpoint=npipe:////./pipe/docker_engine --logLevel=DEBUG
    ports:
      - "8080:8080" # Please read: https://docs.traefik.io/configuration/api/#security
      - "443:443"
      - "80:80"
    isolation: process # workaround for https://github.com/containous/traefik/issues/4409
    volumes:
      - .:C:/etc/traefik
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

  whoami1:
    image: stefanscherer/whoami
    isolation: hyperv
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:whoami.docker.local"

  whoami2:
    image: stefanscherer/whoami
    isolation: hyperv
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:whoami.docker.local"

#  portainer:
#    image: portainer/portainer
#    labels:
#      - "traefik.backend=portainer"
#      - "traefik.frontend.rule=Host:portainer.yourdomain.com"

networks:
  default:
    external:
      name: nat
```

I get `no matching manifest for windows/amd64 10.0.20348 in the manifest list entries`

### Steps To Reproduce

1. Write a compose file with a service using an image based on an older OS version image, and add the `isolation: hyperv` line on the service's section
2. start the compose project

### Compose Version

```Text
`Docker Compose version v2.30.1`
```

### Docker Environment

```Text
Client:
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.18.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.30.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 27.3.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Microsoft Windows Server Version 21H2 (OS Build 20348.3091)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: ARKAICONP01
 ID: c5e7eabd-7116-4beb-92a9-ac9b1b5c8316
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine-
```

### Anything else?

the tooling was installed using [stevedore](https://github.com/slonopotamus/stevedore) (shouldn't make a difference but I thought it was worth pointing out)
