### ISSUE TITLE
Question regarding include and interpolation behaviour

### ISSUE THREAD

**Issue by MikaelElkiaer** [docker/compose#12496]
I am trying to do a nested Docker Compose set-up in order to configure which stacks to include.

I was hoping to do this with a set-up outlined like so:

```bash
λ tree -a
.
├── docker-compose.yaml
├── .env
└── nested
    ├── docker-compose.a.yaml
    ├── docker-compose.b.yaml
    └── .env
```

with contents:

```yaml
---
# ./.env
_ENABLED=""
_DISABLED="/dev/null"
B_IMAGE=b:root
INCLUDE_A=$_ENABLED
INCLUDE_B=$_ENABLED
---
# ./docker-compose.yaml
include:
  - env_file:
      - nested/.env
    path:
      - ${INCLUDE_A:-./nested/docker-compose.a.yaml}
      - ${INCLUDE_B:-./nested/docker-compose.b.yaml}
---
# ./nested/.env
A_IMAGE=a:nested
B_IMAGE=b:nested
---
# ./nested/docker-compose.a.yaml
services:
  a:
    image: ${A_IMAGE}
---
# ./nested/docker-compose.b.yaml
services:
  b:
    image: ${B_IMAGE}
```

I have noticed a couple of things when running this.
It works as expected (disregard non-existant images) when running `docker compose` commands.
I can even output the config:
```bash
λ docker compose config
name: compose-nested-env
services:
  a:
    image: a:nested
    networks:
      default: null
  b:
    image: b:root
    networks:
      default: null
networks:
  default:
    name: compose-nested-env_default
```

However, when outputting config I notice two things:

1. The root `.env` takes precedence over `./nested/.env` as can be seen by `.services.b.image`.
2. I cannot run `docker compose config --variables` - this yelds the following error:
    ```bash
    open /home/me/Repositories/GitHub/_chaos/compose-nested-env/${INCLUDE_A+./nested/docker-compose.a.yaml}${INCLUDE_A-/dev/null}: no such file or directory
    ```

So, could someone clarify how this is intended to work?
I would like to understand my 2 observations.

Note: I was also hoping for a better mechanism of enabling/disabling, but this was the best I could come up with.
