### ISSUE TITLE
Is "...Migrated sysctl xxx to DriverOpts..." purely information or pointing towards outdated compose syntax?

### ISSUE THREAD

**Issue by kelvtech-co-uk** [docker/compose#12508]
A container service named 'matter' includes `sysctls: net.ipv6.conf.eth0.accept_ra_rt_info_max_plen: 64`, when bring up the associated stack the below is shown.

"matter Migrated sysctl "net.ipv6.conf.eth0.accept_ra_rt_info_max_plen" to DriverOpts{"com.docker.network.endpoint.sysctls":"net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen=64"}"

I'm struggling to locate any documentation or discussion on this topic to understand if this is just informational or whether I should be taking a corrective action?

Thanks

**Comment by ndeloof** [comment]
this message doesn't come from Docker Compose.
Can you please attach a larger output so we better understand the context and potential culprits?

**Comment by ndeloof** [comment]
seems this comes from docker engine: https://github.com/moby/moby/blob/e273a5635a1f2859ef754aa5d69b33f91c729681/docs/api/version-history.md?plain=1#L106

**Comment by kelvtech-co-uk** [comment]
Thank you @ndeloof , that indeed was it.  So I replaced the sysctls stanza with a driver_opts key/value pair underneath the network stanza, so something like...

```
    networks:
      iot:
        ipv4_address: x.x.x.x
        driver_opts:  
          com.docker.network.endpoint.sysctls: net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen=64
```

And this produced the same working container but without the ambiguous message.
