### ISSUE TITLE
Include Project Name in Default Network Alias for Services

### ISSUE THREAD

**Issue by bibelwort** [docker/compose#12500]
Hello Docker Compose Team,

I would like to propose a feature that enhances how Docker performs DNS lookups for service names. Currently, when defining services in multiple projects using a common external network, we should to give unique names to services despite them corresponding to different projects. Otherwise this can easily lead to undesired routing issues when a DNS lookup returns multiple target containers from different projects.

**Proposal:**

To improve network discovery and avoid naming conflicts, I propose that the project name be included as part of the default network alias for services, just like it already happens with container names and their hostnames. This would ensure that services are uniquely identifiable and make it easier to manage services across multiple projects.

**Example:**

Given the following `docker-compose.yml` files for Project A and Project B:

**Project A - `docker-compose.yml`:**
```yaml
version: '3.8'

name: 'projectA'

services:
  web-app:
    image: app1
    networks:
      - shared-net

networks:
  shared-net:
    external: true
```

**Project B - `docker-compose.yml`:**
```yaml
version: '3.8'

name: 'projectB'

services:
  web-app:
    image: app2
    networks:
      - shared-net

networks:
  shared-net:
    external: true
```

Currently, for example, if we try to connect to the apps from an NGINX proxy container in the same shared network using the service name 'web-app', NGINX can route a request to any of them. To avoid this, we need to specify exactly the hostname of the needed container, which is not convenient and we potentially lose the advantages of the replication feature.

The alternative would be to have the following default network aliases for service discovery: `projectA-web-app` and `projectB-web-app`.

Indeed, we could name the services uniquely by adding (for example) the project names as prefixes from the start. But if we did this, the automatic names for created containers would be like these: `projectA-projectA-web-app-1` and `projectB-projectB-web-app-2`, which is not ideal. Yes, we could avoid such prefixes, but usually, it is very hard to give a unique, convenient name for common auxiliary services like databases, web servers, cache services, etc.

We could specify custom network aliases as well, but first, it adds extra configuration lines, and second, it does not override the default unsuitable aliases.

**Conclusion:**

Adding the project name to the default network alias for services would significantly enhance service management and help avoid ambiguity in DNS lookups. This would also make the naming hierarchy more straightforward and align with the naming scheme for containers. I believe this feature would especially benefit many users who manage multiple projects within a shared network, such as those building homelabs or local development environments.

Thank you for considering this proposal.

Best regards, Alex
