### ISSUE TITLE
allow optional gpu reservation in docker-compose.yaml

### ISSUE THREAD

**Issue by alita-moore** [docker/compose#12514]
### Description

I have a compose file that I use for development
```yaml
services:
workstation: 
    ...
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
```
I do development from inside the dev container. I allow this container to have access to the gpu. But I am running this on AWS EC2, so to save money I often want to run the container without a gpu. The following config works when there is no gpu:
```yaml
services:
workstation: 
    ...
    deploy:
      resources:
        reservations:
            devices:
              - driver: nvidia
                count: 0
                capabilities: [gpu]
```
However, if I forget to set this to 0 my container fails to start on the new machine without a GPU.

Is there a way to allow for the container to use the GPU if one is available, and if one is not then it will run as if the count were set to 0?

This would make it easier to use gpu in our development environment because we wouldn't have to remember to change the count value before changing the machine type.
