### ISSUE TITLE
`extends` on a service from a file with `include`

### ISSUE THREAD

**Issue by polarathene** [docker/compose#12533]
### Description

```yaml
# includes/base.yaml
services:
  example:
    image: alpine
```

```yaml
# includes/with-hello.yaml
services:
  example:
    environment:
      HELLO: ${WORLD:-world}
    command: '/bin/sh -c "echo $${HELLO}"'
```

---

This `include` works if the latter invalid section is removed:

```yaml
# compose.include.yaml

# Composed service from modular snippets:
include:
  - path:
      - includes/base.yaml
      - includes/with-hello.yaml

# Invalid (service name cannot be found):
services:
  my-variant:
    extends:
      service: example
```

The extend attempt is invalid as `include` hasn't been processed/resolved when the `extends` logic runs? Yet it's valid to use `depends_on: [example]`, that feels a tad inconsistent.

Attempting to workaround that I assumed a separate compose file that extends `compose.include.yaml` to get merged `example` service to target might work:

```yaml
# compose.yaml

# Invalid (service name cannot be found):
services:
  my-service:
    extends:
      file: compose.include.yaml
      service: example
```

This also fails. Perhaps the `extends.service` logic is failing because it only understands to check a YAML file for `services.<NAME>` exists, which occurs without resolving `include`? While `depends_on` is working presumably as a later stage/step once the compose config is fully generated?

---

I attempted to try another approach with variable interpolation on the service name key and pair that with `include.path.env_file` to have a dynamic service name to avoid the conflicting/overlapping service name if using multiple `include` entries instead of `extends.service`. That doesn't work as variable interpolation isn't available for YAML keys.

Similarly fragments and extensions are locked to the scope of the same YAML document, so I cannot leverage `include` or merge (multiple CLI `-f`) to share modular config in a DRY manner.

`include` is great, for layering multiple compose configs into a single document which I wanted for demonstrating permutations/variants to demonstrate various features for a service. It is rather dependent upon the same service name however, which wouldn't be an issue if `extends` were compatible in a way that the composed `include` service could be imported under a different service name, using `env_file` of `include` to adjust the dynamic configuration differences (_or overriding via `extends`_).

It would seem that you'd need to use separate `compose.yaml` files instead and start each separately, which is a bit more work when you need say `networks.default` shared between them, requiring the network to be managed separately (_or have one define it, while the other uses external_).

With this limitation around the service name, I don't think I can easily use `environment` / `configs` of services with `includes`, but would need to use `env_file` / `volumes` instead to refer to external files of the same content as that would avoid the dependency on service name.

**Comment by polarathene** [comment]
A more real-world example of what I was trying:

```yaml
# includes/base.yaml

services:
  dms:
    image: ${WITH_IMAGE:-ghcr.io/docker-mailserver/docker-mailserver:latest}
    hostname: mail.example.test
```

Due to `file.yaml` having two variants of it's own, this may be better as separate YAML files, but the overall intent was for the auth component to be interchangeable (LDAP is a more verbose config alternative).

```yaml
# includes/auth/file.yaml

services:
  dms:
    configs:
      - source: dms-accounts-${WITH_ACCOUNT_DOMAIN:-example}
        target: /tmp/docker-mailserver/postfix-accounts.cf

configs:
  dms-accounts-example:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
      jane.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

  # Same as above, only change is `example.test` => `remote.test`:
  # Presumably while `include` can use ENV for dynamic config, the resource still needs a unique name
  # if multiple variants would be merged.
  dms-accounts-remote:
    content: |
      john.doe@remote.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
      jane.doe@remote.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```


```yaml
# includes/features/getmail.yaml

services:
  dms:
    environment:
      ENABLE_GETMAIL: 1
      # Reduce the polling frequency to 1 minute for quicker testing:
      GETMAIL_POLL: 1
    configs:
      - source: getmail-jane
        target: /tmp/docker-mailserver/getmail/jane.cf

configs:
  # Basic getmail config to retrieve mail from an account at another mail server via IMAP credentials:
  getmail-jane:
    content: |
      [retriever]
      type = SimpleIMAPSSLRetriever
      server = mail.remote.test
      username = jane.doe@remote.test
      password = secret

      [destination]
      type = MDA_external
      path = /usr/lib/dovecot/deliver
      allow_root_commands = true
      arguments = ("-d","john.doe@example.test")
```

An alternative feature similar to `getmail.yaml` that would be interchangeable:

```yaml
# includes/features/fetchmail.yaml

services:
  dms:
    environment:
      ENABLE_FETCHMAIL: 1
      # Reduce the polling frequency to 10 seconds for quicker testing:
      FETCHMAIL_POLL: 10
    configs:
      - source: fetchmail
        target: /tmp/docker-mailserver/fetchmail.cf

configs:
  # Basic fetchmail config to retrieve mail from an account at another mail server via IMAP credentials:
  fetchmail:
    content: |
      poll 'mail.remote.test' proto imap
        user 'jane.doe@remote.test'
        pass 'secret'
        is 'john.doe@example.test'
        no sslcertck
```


**NOTE:** Opted to treat `include` as a new key for `extends` here.
- This still won't be valid due to `configs` which isn't part of `extends` feature scope.
- Expressing the equivalent with `include` would be extra YAML files, which would look a bit more awkward.

```yaml
# compose.yaml

# A composition of modular snippets instead of 
services:
  dms:
    extends:
      service: dms
      include:
        - path:
            - includes/base.yaml
            - includes/auth/${WITH_AUTH:-file}.yaml
            - includes/features/${WITH_FEATURE:-getmail}.yaml

  # Another instance of DMS to act as a third-party MTA for this example:
  remote-mta:
    hostname: mail.remote.test
    extends:
      service: dms
      include:
        - env_file: remote.env
          path:
            - includes/base.yaml
            - includes/auth/${WITH_AUTH:-file}.yaml
```

```env
# remote.env

# NOTE: This file is required as `env_file` doesn't support inlined content,
# nor any `environment` equivalent supported.

WITH_ACCOUNT_DOMAIN=remote
```

```yaml
# compose.override.yaml

# NOTE: Certs were provisioned only once via a separate `compose.yaml`.
# Various images could produce the files (eg: certbot, traefik, caddy, smallstep/step-ca)
volumes:
  custom-certs:
    name: tls-remote-test
    external: true

services:
  # If needed to support verifying TLS connection, add private CA to trust store:
  dms:
    configs:
      - source: dms-trust-custom-ca
        target: /tmp/docker-mailserver/user-patches.sh
    volumes:
      - custom-certs:/srv/custom-certs:ro

  # Configure with TLS support:
  remote-mta:
    environment:
      SSL_TYPE: manual
      SSL_CERT_PATH: /srv/custom-certs/remote.test/cert.pem
      SSL_KEY_PATH: /srv/custom-certs/remote.test/key.pem
    volumes:
      - custom-certs:/srv/custom-certs/:ro

configs:
  dms-trust-custom-ca:
    content: |
      #!/bin/bash
      cp /srv/custom-certs/ca/cert.pem /usr/local/share/ca-certificates/smallstep-ca.crt
      update-ca-certificates
```

---

This example above was derived from:
- Layered Getmail [compose example](https://github.com/orgs/docker-mailserver/discussions/4344#discussioncomment-12062008) that only uses `include`. Less granular than above, didn't require a separate `compose.override.yaml`.
- An earlier [single file compose example](https://github.com/docker-mailserver/docker-mailserver/blob/85793988d6d81ec21e19ccab96070fcd1f3d6208/demo-setups/fetchmail-compose.yaml) for fetchmail.

Rather than the single file approach, as I add more examples I thought it'd be nicer to modularize, but that gets a bit more complicated with more than one instance of the service in an example. Users could then use `docker compose config` to get a single file that they could use as a base which was an additional bonus to modular config, and we could leverage this for our test suite.

This is probably niche, so feel free to close. It might be better suited to leaning on other tooling focused on templating.
