### ISSUE TITLE
Watch: Support Path Pattern Matching

### ISSUE THREAD

**Issue by davidgfitzgerald** [docker/compose#12544]
# Request

It would be nice if the [watch](https://docs.docker.com/reference/compose-file/develop/#watch) `path` attribute behaved like the `ignore` attribute. For example, `path` could accept wildcards such as `*`.

At the very least it would help to have some more detail in the API documentation adding that (at least for the time being) pattern matching does not work on `path`.

Reference: https://docs.docker.com/reference/compose-file/develop/

# Example

I would like the convenience of being able to do this:

```yaml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
        watch:
        - action: rebuild
          path: frontend/*.json
        - action: rebuild
          path: frontend/*.js
```

instead of the verbose (yet explicit):

```yaml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
        watch:
        - action: rebuild
          path: frontend/jsconfig.json
        - action: rebuild
          path: frontend/package-lock.json
        - action: rebuild
          path: frontend/package.json
        - action: rebuild
          path: frontend/eslint.config.js
        - action: rebuild
          path: frontend/svelte.config.js
        - action: rebuild
          path: frontend/tailwind.config.js
        - action: rebuild
          path: frontend/vite.config.js
```

## Nice To Have

Bonus points for allowing multiple `path` entries in a single `rebuild` action:

```yaml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
        watch:
        - action: rebuild
          path: frontend/*.json frontend/*.js
```

Currently, passing a space separated list is silently interpreted as a single path. So, the below example (misleadingly) does not match `frontend/package.json` nor `frontend/vite.config.js`

```yaml
        - action: rebuild
          path: frontend/package.json frontend/vite.config.js
```

**Comment by jhrotko** [comment]
I created a POC in these branches:
- [compose](https://github.com/jhrotko/compose/tree/feature-wild-star-watch-path)
- [compose-go](https://github.com/jhrotko/compose-go/tree/feature-wild-star-watch-path)

in these branches the implementation is under the `path` which can now receive a string or a list of strings and also validates the `*` pattern matching. 

If you want to try, clone the fork change to the branch (do this for compose and compose-go) and in `go.mod` in compose you will have this line

```
replace github.com/compose-spec/compose-go/v2 v2.4.8 => ../compose-go
```

make sure it is pointing to the right compose-go (my fork/branch)

and in `/compose` run `make build`

now you can give it a try :)

in your `compose.yml` you can write something along the lines

```
...
develop:
      watch:
        - path: api/*.txt
          action: rebuild
        - path: 
             - FILE1
             - FILE2
           target: /app/api/
           action: restart
```

**Comment by ndeloof** [comment]
On https://github.com/docker/compose/pull/12584 I proposed to keep using a single `path` as base to monitor filesystem for changes, and introduce a dedicated `include` attribute so one can declare patterns to restrict which actual file changes should be considered by action:
```yaml
    develop:
        watch:
        - action: rebuild
          path: frontend
          include:
            - *.json
            - *.js
```
