### ISSUE TITLE
Compose services not respecting condition: service_healthy on reboot/daemon restart

### ISSUE THREAD

**Issue by dodancs** [docker/compose#12589]
### Description

I have a syslog container, that should start before all other containers, and only after it is healthy, other containers should start.

Other containers depend on the syslog container, specifying condition `service_healthy`, and their logging options are set to use the syslog server in the container, whose port is mapped on the host on 127.0.0.1:5514.

When using `docker compose up -d`, everything starts fine, but after a reboot, all containers depending on the syslog container fail to start because: `failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:5514: connect: connection refused` - which is caused by the `condition: service_healthy` not being respected when the host is rebooted or the docker daemon is restarted.

### Steps To Reproduce

`docker-compose.yml`:
```yaml
# vim:syntax=yaml

services:
  syslog:
    build: .
    restart: always
    environment:
      TZ: "Europe/Bratislava"
    ports:
      - "127.0.0.1:5514:514"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "20"

  traefik:
    restart: always
    container_name: test-traefik-1
    depends_on:
      syslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:5514"
        syslog-facility: daemon
        tag: "{{.Name}}"
    image: traefik:latest
    environment:
      TZ: "Europe/Bratislava"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

`Dockerfile`:
```dockerfile
FROM alpine:3.19

RUN apk add --no-cache \
    glib \
    pcre \
    eventlog \
    openssl \
    tzdata \
    syslog-ng

RUN mkdir -p /etc/syslog-ng/conf.d /var/run/syslog-ng

VOLUME ["/var/run/syslog-ng", "/etc/syslog-ng/conf.d"]

EXPOSE 514/udp 514/tcp 601/tcp 6514/tcp

ENTRYPOINT ["/usr/sbin/syslog-ng"]
CMD ["-F", "-f", "/etc/syslog-ng/syslog-ng.conf"]

HEALTHCHECK --interval=5s --timeout=1s --start-period=3s --retries=3 CMD syslog-ng-ctl stats || exit 1
```

1. Create the `docker-compose.yml` and `Dockerfile` files
2. Start the services: `docker compose up -d`
3. Make sure they started (they should, and the `syslog` container should be healthy)
4. Restart the docker daemon: `systemctl restart docker`
5. See the `syslog` container (`health: starting`) and the `traefik` container (`Exited (128) 15 seconds ago`)
6. After inspecting the `traefik` container, see State -> Error (`docker inspect test-traefik-1 | jq '.[].State.Error'`)

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.33.0
$ docker-compose version
Docker Compose version v2.33.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 19
 Server Version: 28.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-53-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.06GiB
 Name: T14s
 ID: 4d1d2e63-3f91-4a9f-be4d-2adcab0399bc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

https://forums.docker.com/t/docker-compose-project-does-not-start-properly-upon-reboot-service-restart/146857
