### ISSUE TITLE
Ability to define services started by the default profile

### ISSUE THREAD

**Issue by mrleblanc101** [docker/compose#12661]
### Description

Be this `docker-compose.yml`:
```yml
services:
  reverse-proxy:
    ...
  nuxt:
    ...
    profiles: [internal]
  simulator:
    ...
    profiles: [internal]
```

## Currently

When I run `docker compose up`, only services not assigned to any profile will be started.
```sh
Started services: `reverse-proxy`.
```

When I run `docker compose --profile internal up`, only services assigned to this profile will be started.
```sh
Started services: `nuxt`, `simulator`.
```

## Wanted

When I run `docker compose up`, all services should be started.
```sh
Started services: `reverse-proxy`, `nuxt`, `simulator`.
```
When I run `docker compose --profile internal up`, the `reverse-proxy` service should be excluded.
```sh
Started services: `nuxt`, `simulator`.
```

## Workaround

There is currently a workaround, but it's not very intuitive.
You need to use a profile named `''` (empty string) like this in your `docker-compose.yml`.

This will allow you to define exactly what is started when the `--profile` flag is omited from `docker compose up`, while also allowing you to exclude a specific service when using `docker compose --profile internal up`

```yml
services:
  reverse-proxy:
    ...
    profiles: ['']
  nuxt:
    ...
    profiles: ['', internal]
  simulator:
    ...
    profiles: ['', internal]
```

## Proposal

My proposal has 2 steps:
1. I believe the syntax could be improved by replacing the empty string with the keyword `default`, and running `docker composer up` without the `--profile` argument should start all container that have the default profile. 
We could keep the current behavior if no `default` is defined in the `profiles` array of any services.
This would result in a `docker-compose.yml` file like this:

```yml
services:
  reverse-proxy:
    ...
    profiles: [default]
  nuxt:
    ...
    profiles: [default, internal]
  simulator:
    ...
    profiles: [default, internal]
```

2. Improving the documentation. Whether this is implemented or not, it would be a good idea to add this to the documentation as including and excluding services is relatively common.

**Comment by ndeloof** [comment]
> I want my specific profile to start less service than the default profile

Sorry, this is **not** how profiles have been designed.. If you want to run a few services that are not the default application architecture, you have to name those explicitly in your command `docker compose up SERVICES`.
I'm closing this issue as "not planned"

**Comment by mrleblanc101** [comment]
@ndeloof But I can make it work like so:
```
services:
  reverse-proxy:
    ...
    profiles: ['']
  nuxt:
    ...
    profiles: ['', internal]
  simulator:
    ...
    profiles: ['', internal]
```
My proposal would just make this behavior clearer by changing `""` to `default` and it could be documented...
