### ISSUE TITLE
[BUG] `Overlay` and `host` network in the same time broken in version 28.0.4

### ISSUE THREAD

**Issue by isatis07** [docker/compose#12678]
### Description

We have a setup with one of the workers on remote sites that needs access to both the local network in `host` mode and the `overlay` network. We identified that in version `5:27.5.1-1~ubuntu.24.04~noble`, everything works fine. However, after upgrading to version `5:28.0.4-1~ubuntu.24.04~noble`, this setup stopped working — the container restarts in a loop. 

We're seeing the following error message : `starting container failed: failed to set up container networking: container sharing network namespace with another container or host cannot be connected to any other network`

For now, we've had to roll back to the previous version.

Do you have any idea what might be causing this?

## Mini-lab env : 

* One master on Ubuntu 24.04.2 LTS [Kernel `6.8.0-56-generic`
* One worker on Ubuntu 24.04.2 LTS [Kernel `6.8.0-56-generic`
* The last available docker version are installed on both machine `5:28.0.4-1~ubuntu.24.04~noble` 

`docker-compose.yml`
```yml
services:
  ubuntu-01:
    image: my-ubuntu-app:latest
    command: sleep infinity
    networks:
      - back
      - outside

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.Hostname==worker-01]

  ubuntu-02:
    image: my-ubuntu-app:latest
    command: sleep infinity
    networks:
      - back

networks:
  back:
    driver: overlay
    internal: true
  outside:
    name: "host"
    external: true
```

`dockerfile.yml`
```yml
FROM ubuntu:22.04

RUN apt update
RUN apt install -y net-tools iputils-ping

RUN apt-get clean

CMD ["bash"]

```
Command :
```bash

# Master
docker swarm init 

# Worker
docker swarm join --token <master-tocken> <Ip>:<port>

# Master 
docker build -t my-ubuntu-app:latest . 
docker stack deploy -c docker-compose.yml my_stack
docker service ps my_stack_ubuntu-01
```

### Compose Version

```Text
Docker Compose version v2.34.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 1
  Paused: 0
  Stopped: 10
 Images: 18
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: kyc5r64oyabpdn7twa8p70jrv
  Is Manager: false
  Node Address: 10.110.1.4
  Manager Addresses:
   10.110.0.105:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 753481ec61c7c8955a23d6ff7bc8e4daed455734
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-56-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 9.604GiB
 Name: swissdotnet
 ID: ce0d87f6-82c0-4c9a-bba2-7f10f5424d13
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```
