### ISSUE TITLE
[BUG] [v2.34] Dependencies from `depends_on` are incorrectly merged when using `extends`

### ISSUE THREAD

**Issue by pranay-jain-notable** [docker/compose#12677]
### Description

In the latest version v2.34, Docker compose does not handle `depends_on` correctly when extending a service. This seems to be a regression, because I have been able to verify this functionality work correctly in v2.32, but it fails in the newest version. 

The documentation states the following regarding the expected behavior:
> `volumes_from` and `depends_on` are never shared between services using `extends`. These exceptions exist to avoid implicit dependencies; you always define `volumes_from` locally. This ensures dependencies between services are clearly visible when reading the current file. Defining these locally also ensures that changes to the referenced file don't break anything.

In the latest version (v2.34), this is not working as expected, and instead the dependency list gets merged. 

### Steps To Reproduce

I tested out an example with 2 simple docker compose configs.
File _docker-compose.base.yml_
```
services:
  db:
    image: postgres:latest

  app:
    image: nginx:latest
    depends_on:
      - db
```

File _docker-compose.test.yml_
```
services:
  stateless_app:
    extends:
      file: docker-compose.base.yaml
      service: app
  depends_on: []
```

Now, when I run `docker compose -f docker-compose.test.yml config`, I get the following error:
```
service "stateless_app" depends on undefined service "db": invalid compose project
```
This is likely happening because the `depends_on` list for `stateless_app` gets merged with that of `app`, which is incorrect behaviour.

However, testing the same example on v2.32, I get the following output for `docker compose -f docker-compose.test.yml config`:

```
name: test-docker-compose
services:
  stateless_app:
    image: nginx:latest
    networks:
      default: null
networks:
  default:
    name: test-docker-compose_default
```
This is the correct, expected behavior. 

### Compose Version

```Text
2.34.0
```

### Docker Environment

```Text

```

**Comment by glours** [comment]
Hello @pranay-jain-notable 
[We removed the `extends` restrictions](https://github.com/compose-spec/compose-go/pull/728) in `compose-go` library. 
As `depends_on` is a list, it will now be merged with the original definition so you have to explicitly `!reset` the value as [explain in the documentation](https://docs.docker.com/reference/compose-file/merge/#reset-value)

Declaring your test compose file like this will do what you expect
```yaml
services:
  stateless_app:
    extends:
      file: docker-compose.base.yaml
      service: app
    depends_on: !reset []
```
