### ISSUE TITLE
[BUG] docker compose doesnt pull from local repository

### ISSUE THREAD

**Issue by Darkyere** [docker/compose#12686]
### Description

With the upcoming rate limiting pr. 1 april i have decided to set up a docker registry on my lan for my machines.
However when using docker compose it doesnt use the registry.
docker image pull however works.
This is my setup

docker-compose.yaml

```
version: '3'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./registry-cache:/var/lib/registry  # Map host directory to container storage
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
```

config.yml

```
version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  cache:
    blobdescriptor: inmemory
  delete:
    enabled: true  # Enable this if you want to allow image deletion
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
```

/etc/docker/daemon.json

```
{
  "registry-mirrors": ["http://10.0.0.105:5000"]
}
```

### Steps To Reproduce

1. Setup docker:2 registry as  docker-compose file
2. create config.yml
3. create or edit /etc/docker/daemon.json
4. go to a folder with a docker-compose.yaml file and do a `docker-compose up -d `, files do not end up in registry cache

### Compose Version

```Text
Docker Compose version v2.34.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 23
  Running: 23
  Paused: 0
  Stopped: 0
 Images: 22
 Server Version: 28.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-1020-raspi
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.748GiB
 Name: rpi5-ubuntu-lts
 ID: 5e6f3cf9-ea96-41d0-90c1-af4a1d33ecbd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Registry Mirrors:
  http://127.0.0.1:5000/
 Live Restore Enabled: false
```
