### ISSUE TITLE
[BUG] mac_address does not work

### ISSUE THREAD

**Issue by warlordattack** [docker/compose#12687]
### Description

I would like to have fixed mac adresses for my containers in particular those with mvlan networks.
Unfortunatly it does not work.

### Steps To Reproduce

With : 
C_AD_MAC="10:42:C0:A8:32:CF"
C_AD_NUM=201
NET_TFK="192.168.60"
NET_LAN="192.168.50"  
C_AD_HOST=adg

This runs without error but does not give me fixed mac address : 
docker-compose.yml : 

```
services:
  srv_adguard: 
    extends:
      file: ../_common/puid.yml
      service: all

    container_name: ${C_AD}
    image: ${C_AD_IMG}
    volumes:
      - ${REP_APPDATA}/${C_AD}/conf:/opt/adguardhome/conf:rw
      - ${REP_APPDATA}/${C_AD}/work:/opt/adguardhome/work:rw
    cap_add:
      - NET_ADMIN   # failed to sufficiently increase receive buffer size
      - NET_RAW     # POST 192.168.50.201 /control/dhcp/set_config: enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: listen packet 8a:86:9f:c4:ea:55: socket: operation not permitted
    
    mac_address: ${C_AD_MAC}
    hostname: ${C_AD_HOST}
    networks:
      mvlan:
        ipv4_address: ${NET_LAN}.${C_AD_NUM}   # 201
      proxy:
        ipv4_address: ${NET_TFK}.${C_AD_NUM}
networks: 
  mvlan: 
    external: true
  proxy: 
    external: true
```

This gives me an error : 
ERROR: The Compose file '/mnt/timeshift/mydocker/code/sec-adguard/docker-compose.yml' is invalid because:
services.srv_adguard.networks.mvlan contains unsupported option: 'mac_address'
ERROR: The Compose file '/mnt/timeshift/mydocker/code/sec-adguard/docker-compose.yml' is invalid because:
services.srv_adguard.networks.mvlan contains unsupported option: 'mac_address'

docker-compose.yml : 
```
services:
  srv_adguard: 
    extends:
      file: ../_common/puid.yml
      service: all

    container_name: ${C_AD}
    image: ${C_AD_IMG}
    volumes:
      - ${REP_APPDATA}/${C_AD}/conf:/opt/adguardhome/conf:rw
      - ${REP_APPDATA}/${C_AD}/work:/opt/adguardhome/work:rw
    cap_add:
      - NET_ADMIN   # failed to sufficiently increase receive buffer size
      - NET_RAW     # POST 192.168.50.201 /control/dhcp/set_config: enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: listen packet 8a:86:9f:c4:ea:55: socket: operation not permitted
    
    #mac_address: ${C_AD_MAC}
    hostname: ${C_AD_HOST}
    networks:
      mvlan:
        ipv4_address: ${NET_LAN}.${C_AD_NUM}   # 201
        mac_address: ${C_AD_MAC}
      proxy:
        ipv4_address: ${NET_TFK}.${C_AD_NUM}
        mac_address: ${C_AD_MAC}
networks: 
  mvlan: 
    external: true
  proxy: 
    external: true
```

Commands : 
```
    echo "---- +MVLAN ----"
    # ip-range(29) : 7 adresses 192.168.50.200-207
    # parent : enp6s18 (ubuntu) / ens18 (rocky) / eth0 (autres)
    docker network create -d macvlan \
    --gateway=192.168.50.1 \
    --subnet=192.168.50.0/24 \
    --ip-range=192.168.50.200/29 \
    --opt parent=enp6s18 \
    mvlan
    #--opt com.docker.network.driver.mtu=9216 \

    echo "---- +PROXY ----"
    docker network create \
    --gateway 192.168.60.1 \
    --subnet 192.168.60.0/24 \
    --opt com.docker.network.driver.mtu=9216 \
    proxy


    #echo "---- UP D FORCE RC ---------------"
    sudo docker-compose --file $f --env-file $e down         # down
    sudo docker-compose --file $f --env-file $e up -d --force-recreate  # up -d
```

puid.yml : 

```
services:
  all:
    extends:
      file: ../_common/all.yml
      service: all
      
    user: "${PUID}:${PGID}"
```

all.yml : 
```
services:
  all:
    restart: ${C_ALL_RESTART}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    logging:
      driver: ${LOG_DRIVER}
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_LABEL_ENABLE}"
    
    # docker sock : 1. - user: ${PUID}:${PGID} # UID/GID disabled
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock:rw
    security_opt: # 2. SELinux disabled
      - label=disable # 3. - label=disable added
```

### Compose Version
```
doge@px-mint:~$ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.12.3
OpenSSL version: OpenSSL 3.0.13 30 Jan 2024
```

### Docker Environment
```
doge@px-mint:~$ docker version
Client: Docker Engine - Community
 Version:           28.0.4
 API version:       1.48
 Go version:        go1.23.7
 Git commit:        b8034c0
 Built:             Tue Mar 25 15:07:16 2025
 OS/Arch:           linux/amd64
 Context:           desktop-linux
```

### Linux version
```
doge@px-mint:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 22.1
Release:        22.1
Codename:       xia
```
