### ISSUE TITLE
[BUG] !reset prevents value override when used with extends

### ISSUE THREAD

**Issue by matiboux** [docker/compose#12681]
### Description

Related to this other issue, but going further:
- #11937

Placing a `!reset` in a compose file should remove all previous value and let the user define another value afterwards as an override.

However, this does not work when placed in a compose file that is included using `extends`: placing a `!reset` here incorrectly removes all values from the config, even those set after the `!reset`.

This is a problem in complex configurations which would benefit from refactoring for common configuration.

---

### Creating two files:

`test/base.yml`

```yaml
services:
  init:
    image: alpine:latest
    command: "sleep infinity"
  test:
    extends: { service: init }
    command: !reset null
    command: "echo 'Hello World'"
```

`test/compose.yml`

```yaml
services:
  init:
    extends:
      file: base.yml
      service: init
  test:
    extends:
      file: base.yml
      service: test
```

<details>
<summary>Command to quickly create the files</summary>

```sh
cat <<'TEST_SETUP' | sh
# Create the test/ directory
mkdir -p test
# Create the base.yml file
cat <<'EOF' > test/base.yml
services:
  init:
    image: alpine:latest
    command: "sleep infinity"
  test:
    extends: { service: init }
    command: !reset null
    command: "echo 'Hello World'"
EOF
# Create the compose.yml file
cat <<'EOF' > test/compose.yml
services:
  init:
    extends:
      file: base.yml
      service: init
  test:
    extends:
      file: base.yml
      service: test
EOF
TEST_SETUP
```
</details>

### Then, running config

Base is expected to work fine:

```sh
docker compose -f test/base.yml config
```

```
name: test
services:
  init:
    command:
      - sleep
      - infinity
    image: alpine:latest
    networks:
      default: null
  test:
    command:
      - echo
      - Hello World
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: test_default
```

But when used with `extends`, it actually does not:

```sh
docker compose -f test/compose.yml config
```

```
name: test
services:
  init:
    command:
      - sleep
      - infinity
    image: alpine:latest
    networks:
      default: null
  test:
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: test_default
```

The `command` is missing from the `test` service.

<details>
<summary>Diff</summary>

```diff
 name: test
 services:
   init:
     command:
       - sleep
       - infinity
     image: alpine:latest
     networks:
       default: null
   test:
-   command:
-     - echo
-     - Hello World
     image: alpine:latest
     networks:
       default: null
 networks:
   default:
     name: test_default
```
</details>

---

## Case 2

This is a very similar case, but more in line with my actual use case.
In this case, I want to extends build configuration but remove unrelevant environment variables.

### Creating two files:

`test/base.yml`

```yaml
services:
  init:
    image: alpine:latest
    command: "sleep infinity"
    environment:
      NAME: init
      INIT: true
      SECRET: secret
  test:
    extends: { service: init }
    environment: !reset []
    environment:
      NAME: test
      TEST: true
```

`test/compose.yml`

```yaml
services:
  init:
    extends:
      file: base.yml
      service: init
    environment:
      EXTRA: extra-init
  test:
    extends:
      file: base.yml
      service: test
    environment:
      EXTRA: extra-test
```

<details>
<summary>Command to quickly create the files</summary>

```sh
cat <<'TEST_SETUP' | sh
# Create the test/ directory
mkdir -p test
# Create the base.yml file
cat <<'EOF' > test/base.yml
services:
  init:
    image: alpine:latest
    command: "sleep infinity"
    environment:
      NAME: init
      INIT: true
      SECRET: secret
  test:
    extends: { service: init }
    environment: !reset []
    environment:
      NAME: test
      TEST: true
EOF
# Create the compose.yml file
cat <<'EOF' > test/compose.yml
services:
  init:
    extends:
      file: base.yml
      service: init
    environment:
      EXTRA: extra-init
  test:
    extends:
      file: base.yml
      service: test
    environment:
      EXTRA: extra-test
EOF
TEST_SETUP
```
</details>

### Then, running config

Base is, again, expected to work fine:

```sh
docker compose -f test/base.yml config
```

```
name: test
services:
  init:
    command:
      - sleep
      - infinity
    environment:
      INIT: "true"
      NAME: init
      SECRET: secret
    image: alpine:latest
    networks:
      default: null
  test:
    command:
      - sleep
      - infinity
    environment:
      NAME: test
      TEST: "true"
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: test_default
```

But when used with `extends`, it actually does not:

```sh
docker compose -f test/compose.yml config
```

```
name: test
services:
  init:
    command:
      - sleep
      - infinity
    environment:
      EXTRA: extra-init
      INIT: "true"
      NAME: init
      SECRET: secret
    image: alpine:latest
    networks:
      default: null
  test:
    command:
      - sleep
      - infinity
    environment:
      EXTRA: extra-test
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: test_default
```

The `EXTRA` environment variable is there, but the `NAME` and `TEST` variables are missing from the `test` service.

<details>
<summary>Diff</summary>

```diff
 name: test
 services:
   init:
     command:
       - sleep
       - infinity
     environment:
+      EXTRA: extra-init
       INIT: "true"
       NAME: init
       SECRET: secret
     image: alpine:latest
     networks:
       default: null
   test:
     command:
       - sleep
       - infinity
     environment:
+      EXTRA: extra-test
-      NAME: test
-      TEST: "true"
     image: alpine:latest
     networks:
       default: null
 networks:
   default:
     name: test_default
```
</details>

### Compose Version

```Text
Docker Compose version v2.32.4-desktop.1
Docker Compose version 2.34.0
```

### Docker Environment

```Text
Docker version 27.5.1, build 9f9e405
Docker version 28.0.1, build 068a01e
```
