### ISSUE TITLE
[BUG] Env_file property isn't interpreted when profiles property is used

### ISSUE THREAD

**Issue by cphalpin** [docker/compose#12693]
### Description

When a service has profiles set its env_files aren't used. Values set in the env files don't exist in the container.

### Steps To Reproduce

With these config files:

docker-compose.yml
```yaml
services:
  app:
    image: alpine
    env_file:
      - test.env
  other-app:
    image: alpine
    profiles:
      - profile
    env_file:
      - test.env
```

test.env
```yaml
VAR=val
```

`docker compose config app` yields
```
name: test
services:
  app:
    environment:
      VAR: val
    image: alpine
    networks:
      default: null
networks:
  default:
    name: test_default
```

`docker compose config other-app` yields
```
name: test
services:
  other-app:
    profiles:
      - profile
    env_file:
      - /home/cphalpin/code/test/test.env
    image: alpine
    networks:
      default: null
networks:
  default:
    name: test_default
```

`docker compose run --rm app sh -c 'echo $VAR'` yields
```
val
```

`docker compose run --rm other-app sh -c 'echo $VAR'` yields
```

```

### Compose Version

```Text
Docker Compose version 2.34.0
```

### Docker Environment

```Text
Client:
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.34.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 6
  Paused: 0
  Stopped: 9
 Images: 564
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1a43cb6a1035441f9aca8f5666a9b3ef9e70ab20.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.13.8-2-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.27GiB
 Name: canute
 ID: 2476f880-71be-467d-a6ef-b5ec09a4cb4e
 Docker Root Dir: /home/docker
 Debug Mode: false
 Username: cphalpin
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```
