### ISSUE TITLE
[BUG] docker compose build seems not use mirror

### ISSUE THREAD

**Issue by cloverzrg** [docker/compose#12705]
### Description

I'm reporting an issue with the docker compose build command not using the mirror settings. I'm located in China, where connecting to the official default mirror is not possible, so a mirror is usually configured. Recently, I've encountered a problem where building an image with docker compose build seems to ignore the mirror settings when pulling images, and it just hangs. However, building with docker build . works fine using the same Dockerfile. Please refer to the screenshot.

### Steps To Reproduce

1. in the server that cannot access docker.io, add mirror in `/etc/docker/daemon.json`
2. add compose.yml, and Dockerfile
3. run `docker compose build`

```
services:
  postgres17:
    container_name: postgres
    build: .
    environment:
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxxxx
      PGDATA: /data/postgres
    volumes:
       - ./data:/data/postgres
    ports:
      - "4513:5432"
    user: "999:999"
    networks:
      - traefik-net
    restart: unless-stopped

networks:
  traefik-net:
    name: traefik-net
    external: true
```

```
# pgvecto-rs
FROM tensorchord/pgvecto-rs-binary:pg17-v0.4.0-amd64 AS pgvecto-rs-binary

FROM postgres:17
RUN sed -i.bak \
    -e 's|http://deb.debian.org/debian|http://mirrors.aliyun.com/debian|g' \
    -e 's|http://deb.debian.org/debian-security|http://mirrors.aliyun.com/debian-security|g' \
    /etc/apt/sources.list.d/debian.sources

# pgvector
RUN apt update && apt install -y postgresql-17-pgvector

# pgvecto-rs
COPY --from=pgvecto-rs-binary /pgvecto-rs-binary-release.deb /tmp/vectors.deb
RUN apt-get install -y /tmp/vectors.deb && rm -f /tmp/vectors.deb


CMD ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", "search_path=\"$user\", public, vectors", "-c", "logging_collector=on"]
```

### docker build .

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/d6e55c9f-55f5-4894-8523-4a27258df990" />

### docker compose build

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/c805a59b-4584-4bee-8513-652d8f298fd1" />

### Compose Version

```Text
docker compose version:
Docker Compose version v2.34.0

docker-compose version:
zsh: command not found: docker-compose
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-56-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 14
 Total Memory: 31.34GiB
 Name: ubuntu20230505
 ID: 04e17e9b-2029-4f0f-912b-0f25eadc0c45
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Registry Mirrors:
  https://docker-mirror.gz2.<mydomain>.com/
 Live Restore Enabled: false
```
