### ISSUE TITLE
[BUG] Compose `secrets`/`configs` does not set the correct `chmod`

### ISSUE THREAD

**Issue by matzeeable** [docker/compose#12717]
See https://github.com/moby/moby/issues/49404 for original issue description.

Already fixed in spec by @ndeloof: https://github.com/compose-spec/compose-go/pull/738

```sh
$ dcker -v
Docker version 28.0.4, build b8034c0
$ docker compose version
Docker Compose version v2.34.0
```

`docker-compose.yml`:

```yml
services:
    my-container:
        image: alpine:latest
        configs:
            - source: my-config
              target: /my-entry.sh
              mode: 0755
              uid: "1000"
              gid: "1000"

configs:
    my-config:
        file: my-config.txt
```

When I run `docker compose config` I get the `mode` as non-octal representation as output as `string`:

```yml
$ docker compose config
name: devowl-wp
services:
  my-container:
    configs:
      - source: my-config
        target: /my-entry.sh
        uid: "1000"
        gid: "1000"
        mode: "0755"
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: devowl-wp_default
configs:
  my-config:
    name: devowl-wp_my-config
    file: /home/mg/devowl-wp/my-config.txt
```

I am using `docker stack deploy` to deploy a stack from a `docker-compose.yml` file. For this, I am using the following mechanism which fails due to a typing error:

```sh
$ docker stack deploy my-test -c <(docker compose config)
services.my-container.configs.0.mode must be a number
```

### Expected behavior

`docker compose config` needs to output the `mode` as octal-number representation:

```yml
      - source: my-config
        target: /my-entry.sh
        uid: "1000"
        gid: "1000"
        mode: 0755 # -> leading zero without quotes
```

### Workaround

Save the `docker compose config` in a variable, use `yq` to place a marker for the leading zero and use `sed` to replace it accordingly:

```yml
$ resolvedConfig=$(docker compose config)
$ resolvedConfig=$(echo "$resolvedConfig" | yq -y '.services |= with_entries(if .value.configs != null then .value.configs |= map(if .mode != null then .mode |= ("MY_ZERO_MARKER" + (tonumber | tostring)) else . end) else . end)')
$ resolvedConfig=$(echo "$resolvedConfig" | sed 's/mode: MY_ZERO_MARKER/mode: 0/g')
$ echo "$resolvedConfig"

name: devowl-wp
services:
  my-container:
    configs:
      - source: my-config
        target: /my-entry.sh
        uid: '1000'
        gid: '1000'
        mode: 0755
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: devowl-wp_default
configs:
  my-config:
    name: devowl-wp_my-config
    file: /home/mg/devowl-wp/my-config.txt
```
