### ISSUE TITLE
[BUG] Pull=missing always pulls latest image

### ISSUE THREAD

**Issue by fire015** [docker/compose#12726]
### Description

Whenever I run:

`docker compose up -d --pull=missing`

It will try to pull the latest image despite `phpmyadmin:latest` already downloaded.

I have specified in my compose yaml file: `image: phpmyadmin`

Is this the intended behavior? Image is not missing so the pull flag is confusing....

Mac / Docker Desktop 4.40.0 (187762) / Engine: 28.0.4 / Compose: v2.34.0-desktop.1

### Compose Version

```Text

```

### Docker Environment

```Text

```

**Comment by ndeloof** [comment]
I can't reproduce. After initial pull, `--pull=missing` (which is the default value) doesn't trigger image pull

Please check `docker image inspect phpmyadmin`

**Comment by fire015** [comment]
@ndeloof I find this happens when I switch projects. So 2 yaml files in different folders with different name but same image.

**Comment by ndeloof** [comment]
Can you please try to reproduce with a minimal example, or share your compose files for further analysis ?

**Comment by fire015** [comment]
Theres definitely some sort of time cache behind this, if I re-run the up and down command across different projects it won't pull after the first time. But after maybe 24 hours it will try and pull.

```
name: project1

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80

volumes:
  mysql:
```

$ docker compose up -d --pull=missing
[+] Running 2/2
 ✔ db Pulled                                                                                                                                                                                         2.9s
 ✔ phpmyadmin Pulled


$ docker compose down -t 0
[+] Running 3/3
 ✔ Container project1-phpmyadmin-1  Removed                                                                                                                                                          0.2s
 ✔ Container project1-db-1          Removed                                                                                                                                                          

Up again will not pull, but if you try this 24 hours later it will.
