### ISSUE TITLE
Support merging of extensions ("x-something")

### ISSUE THREAD

**Issue by apollo13** [docker/compose#12724]
### Description

It would be great if two compose files like this:
```
services:
  nginx1:
    image: nginx:latest

x-test:
  test: 123
```

```
services:
  nginx2:
    image: nginx:latest

x-test:
  abc: 123
```

would result in a merged `x-test` extension when used via `docker compose config -f file1.yaml -f file2.yaml`. Currently the result is:
```
services:
  nginx2:
    image: nginx:latest

x-test:
  abc: 123
```

and I'd love to see:
```
services:
  nginx2:
    image: nginx:latest

x-test:
  test: 123 # This is different
  abc: 123
```

Is the current behavior on purpose or would you be open to a MR to "fix" the current behavior?
