### ISSUE TITLE
Support flexible Secrets naming convention

### ISSUE THREAD

**Issue by bhidalgo-apolitical** [docker/compose#12744]
### Description

Docker Compose’s secrets feature is excellent for injecting private data into containers, but its design is inflexible when different services need the same secret name to reference distinct values.

This can be easily sorted by adding custom steps inside the Dockerfile to handle that logic/rename the variable, but in a complex setup where there are many moving pieces, updating the Dockerfile may end up in a waterfall of changes.

An example of what I'm referring to as secrets setup being rigid could be like this:

```yaml
secrets:
  NX_CLOUD_ACCESS_TOKEN_FRONTEND:
    environment: NX_CLOUD_ACCESS_TOKEN_FRONTEND
  NX_CLOUD_ACCESS_TOKEN_BACKEND:
    environment: NX_CLOUD_ACCESS_TOKEN_BACKEND

services:
  backend-service:
    build:
      secrets:
        - NX_CLOUD_ACCESS_TOKEN_BACKEND
  frontend-service:
    build:
      secrets:
        - NX_CLOUD_ACCESS_TOKEN_FRONTEND
```

In our example use-case we have multiple services running via Tilt and using Nx Cloud for distributed caching. It happens that backend and frontend projects point to different Nx Cloud projects for caching, but they need the variable set as `NX_CLOUD_ACCESS_TOKEN`, but there's no way to dynamically add the values to it.
As you can see from above, the build process will fail as the variable `NX_CLOUD_ACCESS_TOKEN` is not set - and there's no way to dynamically add different values to it.

Therefore adding something like `mountName` or `secretName` to the `secrets` key, would add the flexibility to keep values in different secrets but have them mounted with a different name. E.g:

```yaml
secrets:
  NX_CLOUD_ACCESS_TOKEN_FRONTEND:
    environment: NX_CLOUD_ACCESS_TOKEN_FRONTEND
    mountName: NX_CLOUD_ACCESS_TOKEN
  NX_CLOUD_ACCESS_TOKEN_BACKEND:
    environment: NX_CLOUD_ACCESS_TOKEN_BACKEND
    mountName: NX_CLOUD_ACCESS_TOKEN

services:
  backend-service:
    build:
      secrets:
        - NX_CLOUD_ACCESS_TOKEN_BACKEND
  frontend-service:
    build:
      secrets:
        - NX_CLOUD_ACCESS_TOKEN_FRONTEND

## Within the Dockerfile it can be mounted as NX_CLOUD_ACCESS_TOKEN
RUN --mount=type=secret,id=NX_CLOUD_ACCESS_TOKEN \
	NX_CLOUD_ACCESS_TOKEN=$(cat /run/secrets/NX_CLOUD_ACCESS_TOKEN)
```

Our setup is very specific, but I can think of instances in which people may need to also have different values added to a same variable so the same Dockerfile can be reused for multiple scenarios -- one quick example would be staging vs prod envs when testing locally

**Comment by glours** [comment]
Hey @bhidalgo-apolitical 
Did you try to make the configuration on the service build definition directly, you should be able to do this by defining the target of the secret, like this
```
secrets:
  NX_CLOUD_ACCESS_TOKEN_FRONTEND:
    environment: NX_CLOUD_ACCESS_TOKEN_FRONTEND
  NX_CLOUD_ACCESS_TOKEN_BACKEND:
    environment: NX_CLOUD_ACCESS_TOKEN_BACKEND

services:
  backend-service:
    build:
      secrets:
        - source: NX_CLOUD_ACCESS_TOKEN_BACKEND
          target: NX_CLOUD_ACCESS_TOKEN
  frontend-service:
    build:
      secrets:
        - source: NX_CLOUD_ACCESS_TOKEN_FRONTEND
          target: NX_CLOUD_ACCESS_TOKEN
```

[here an example of the Compose e2e test](https://github.com/docker/compose/blob/b45ca82791d47531d91dc8f240aebed6d4f1790e/pkg/e2e/fixtures/build-test/secrets/compose.yml)

Let me know if this is a valid solution for your use case.
