### ISSUE TITLE
[BUG] Bind mounts not working when using DOCKER_HOST variable for Windows Containers

### ISSUE THREAD

**Issue by 0xff8** [docker/compose#12750]
### Description

I am trying to start windows containers using docker compose from linux host on remote windows machine using SSH. When I run docker compose up command , remote windows host fails to run containers, since the local current path gets prepended to the volume.
```
Error response from daemon: invalid mount config for type "bind": invalid mount path: '/builds/projects/windows-docker/C:\Users\test-user\results' mount path must be absolute
```
What I have tried so far:
- added `platform: windows/amd64` to docker-compose.yaml
- added export DOCKER_DEFAULT_PLATFORM=windows/amd64
- Tried Unix-like path //C/Users/<YourUserName>/results (not working, although compose client stops adding current path to the volume name)
 - Tried to add a slash in front of the path /C:\Users\<YourUserName>\results (not working, remote windows machine complains that the path must be absolute)
### Steps To Reproduce

1. Set DOCKER_HOST variable to `ssh://user@windows-host/`
1. From linux host run `docker compose up`
2. compose.yaml:
```yaml
services:
  node:
    platform: windows/amd64
    image: ${IMAGE}
    volumes:
      - type: bind
        source: C:\Users\<YourUserName>\results
        target: C:\Results
    restart: unless-stopped
    stdin_open: true
    tty: true
```

### Compose Version

```Text
Docker Compose version v2.35.0
```

### Docker Environment

```Text
Server: Docker Engine - Community
 Engine:
  Version:          28.0.1
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       bbd0a17
  Built:            Wed Feb 26 10:40:47 2025
  OS/Arch:          windows/amd64
  Experimental:     false
```

### Anything else?

If possible - suggest some hack / other method
