### ISSUE TITLE
[BUG] npipe bind type not supported in compose versions above v2.34.0 (Windows)

### ISSUE THREAD

**Issue by vivekvenugopalan** [docker/compose#12778]
### Description

Hi,

I am a beginner in Docker concepts and hence please pardon my lack of knowledge.

**The Error:**
`services.traefik.volumes.0.type services.traefik.volumes.0.type must be one of the following: "bind", "volume", "tmpfs", "cluster", "image"`

**The Details:**
We are using the following code in the docker-compose.yml:

```
volumes:
      - source: \\.\pipe\docker_engine\
        target: \\.\pipe\docker_engine\
        type: npipe
      - ./traefik:C:/etc/traefik
```
This works fine with Docker Compose Versions up to v2.34.0 but fails in versions v2.35.0 and v2.35.1 with the following error:

`services.traefik.volumes.0.type services.traefik.volumes.0.type must be one of the following: "bind", "volume", "tmpfs", "cluster", "image"`

### Steps To Reproduce

Use Volume type as npipe in docker-compose.yml file:

```
volumes:
      - source: \\.\pipe\docker_engine\
        target: \\.\pipe\docker_engine\
        type: npipe
      - ./traefik:C:/etc/traefik
```

### Compose Version

```Text
Docker Compose version v2.35.0
```

### Docker Environment

```Text
Client:
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 28.1.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Microsoft Windows Server Version 1809 (OS Build 17763.7136)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 32GiB
 Name: N20-IT-SIDW106D
 ID: d5b5ff8b-fbba-4187-86e2-b3172aaa3637
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Anything else?

We are tying to setup the Sitecore XM Cloud repo using the containerized approach: https://github.com/sitecorelabs/xmcloud-foundation-head

The scripts for docker setup is available in the following directory: https://github.com/sitecorelabs/xmcloud-foundation-head/tree/main/local-containers
