### ISSUE TITLE
[BUG] Docker compose v2.35.1 volume regression with tmpfs

### ISSUE THREAD

**Issue by nevergone** [docker/compose#12772]
### Description

Hello,

I found a bug that didn't appear before (2.35.0 still worked fine), but 2.35.1 is broken.

### Steps To Reproduce

I have a MySQL service (docker-compose.yml)

```
  mysql:
    image: nevergone/mariadb:11.6-latest
    env_file:
      - env/debug.txt
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'foobar'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./conf/mysql/mysql_server.cnf:/etc/mysql/conf.d/my.cnf
      - ./log/mysql:/var/log/mysql
    networks:
      - default
    restart: always
```

Sometimes I put its contents on tmpfs because speed is more important than permanent storage of data (docker-compose.mysql-tmpfs.yml):

```
services:
  mysql:
    tmpfs:
      - /var/lib/mysql
```

In 2.35.1 version, the error message:

```
$ docker compose -f docker-compose.yml -f docker-compose.mysql-tmpfs.yml up -d
[+] Running 1/3
 ✔ Network foobar_default    Created                                                                                                                                              0.1s 
 ⠙ Container foobar-mysql-1  Creating                                                                                                                                             0.1s 
Error response from daemon: Duplicate mount point: /var/lib/mysql
```

### Compose Version

```Text
Docker Compose version v2.35.1

(Linux x86-64 host)
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 25
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-24-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.23GiB
 Name: t470-never
 ID: f74b7734-d449-42dc-a120-6caeffc3ccc8
 Docker Root Dir: /mnt/data/var__lib__docker
 Debug Mode: false
 Username: nevergone
 Experimental: false
 Insecure Registries:
  192.168.1.104:5000
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
v2.35.0 was using the `mount` API for bind-mounts, which make it actually override the volume definition with the tmpfs one. Still, this conflict should not have been left without a warning, as configuration is incorrect: you can't declare both a volume and a tmpfs for same target path in container. As v2.35.0 reverted this to prefer the legacy `bind` API (to restore backward compatibility in some corner cases) this conflict is detected by docker engine.

We should get this checked by Compose, before any attempt to create container.

**Comment by nevergone** [comment]
What solution do you recommend? I have found that if I don't use mysql volumes, the data is lost when the container is stopped and removed.
However, if you need to perform fast operations on a larger database, tmpfs greatly improves performance.

I've been using this configuration for several years, and it has never reported any warnings or errors.

**Comment by ndeloof** [comment]
Use `volume` with long syntax in your override file to set a tmpfs mount:
```yaml
services:
  mysql:
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
```
