### ISSUE TITLE
[BUG] ANSI escape color formatting lost on multiple lines in logs

### ISSUE THREAD

**Issue by ras0q** [docker/compose#12789]
### Description

When a service outputs text with ANSI escape codes for color formatting across multiple lines, `docker compose logs` only preserves the color for the first line.
Subsequent lines are displayed without the indended color.

```yaml
# compose.yaml
services:
  app:
    image: bash
    command: echo -e "\\e[31m This line is RED.\\n This line is also RED.\\n This span is ... \\e[34m BLUE."
```

Expected|Actual
-|-
![Image](https://github.com/user-attachments/assets/b81d3dce-f929-45da-bb20-6cc34249d7c3)|![Image](https://github.com/user-attachments/assets/e86476e2-2789-4c9f-af7d-fd210f869269)

### Compose Version

```Text

```

### Docker Environment

```Text

```
