### ISSUE TITLE
[BUG] Referring to another service's image in `additional_contexts` fails if profiles are different.

### ISSUE THREAD

**Issue by liarokapisv** [docker/compose#12791]
### Description

I would expect the following to work, practically using `test-a` as a `build-only` helper:

```yaml
services:
  test-a:
    profiles: ["do-not-run"]
    build:
      dockerfile_inline:
        FROM scratch
  test-b:
    build:
      dockerfile_inline:
        FROM base-image
      additional_contexts:
        base-image: service:test-a
```

It appears that the `service:test-a` resolution doesn't work if the services belong to different profiles.
Removing the `profiles: ["do-not-run"]` line makes the example build properly.

### Compose Version

```Text
Docker Compose version 2.35.1
```

### Docker Environment

```Text
Client:
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /nix/store/mmr7gyz1m6rilqiiwhrdgfczad24jd0v-docker-plugins/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.35.1
    Path:     /nix/store/mmr7gyz1m6rilqiiwhrdgfczad24jd0v-docker-plugins/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: refs/tags/v2.0.4
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.14.3
 Operating System: NixOS 25.05 (Warbler)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.66GiB
 Name: veritas-framework-13-amd-7840u
 ID: f438dcd8-b652-4874-a69b-806e653339a9
 Docker Root Dir: /home/docker-root
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: true
```
