### ISSUE TITLE
Watch different command/entrypoint

### ISSUE THREAD

**Issue by zoriya** [docker/compose#12835]
### Description

When running with `docker compose watch`, i want my service to start their dev servers (those that support hotreloading & watch files)

When running with `docker compose up`, i want services to use their prod server (that will not start a file watcher & so on)

I was hoping to find something like `services.app.develop.entrypoint` or `services.app.develop.command`

Potential example:
```yaml
services:
  web:
    build: .
    command: npm start
    develop:
      command: npm dev
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
```
