### ISSUE TITLE
[BUG] Why does the env file allow colon as separator  between key and value

### ISSUE THREAD

**Issue by veekxt** [docker/compose#12841]
### Description

docker compsoe file:
```
services:
  env-test:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m main
    env_file:
      - .env
```
.env file:
```
env1 = env1
env2: env2
env3 = env3

```
notice the `env2: env2`

`docker compose config` get:
```
name: dc_env
services:
  env-test:
    build:
      context: /home/marco/src/test/dc_env
      dockerfile: Dockerfile
    command:
      - python
      - -m
      - main
    environment:
      env1: env1
      env2: env2
      env3: env3
    networks:
      default: null
networks:
  default:
    name: dc_env_default

```
the env2 is valid.

docker compose version: `Docker Compose version v2.35.1`

If colons can be used, why aren't they mentioned in the documentation?
