### ISSUE TITLE
Ability to only create the container, and not run it

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#1284]
This would be useful for data-only container.

So something like this would be useful:

```
mysql-data:
  image: arungupta/mysql-data-container
  create-only: true
mysqldb:
  image: mysql:latest
  volumes-from: mysqld-data
  environment:
    MYSQL_DATABASE: sample
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: supersecret
```

**Comment by funkyfuture** [comment]
are you aware that you don't need data-containers if you use *compose* since defined volumes will persist when you recreate a service?

**Comment by arun-gupta** [comment]
Aren't those defined volumes specific to a container only though? And not shareable across containers?

**Comment by ibnesayeed** [comment]
I think it is a good idea to have data container that will allow mounting external storage into specified volumes in one place and rest of the containers can link from the data container and use those volumes. This will also be helpful if you run multiple instances of containers other than data container, in that case individual instances will not try to remount any volumes specified.

On the other hand, I can have a data container that has default command as simple as `echo Hello Data`, it will execute and exit immediately after printing `Hello Data` in the log. This will make sure that the image. Although I do think that a `create-only: true` or `spin: false` style config will be a plus for other reasons.

**Comment by funkyfuture** [comment]
> Aren't those defined volumes specific to a container only though? And not shareable across containers?

nope, they can be used them with the `volumes_from`-key. eg:
```yaml
web:
  …
  volumes:
    - /uploads
    - /home/foo/config:/config

backup:
  …
  volumes_from:
    - web
```

@ibnesayeed with the `extend`-key you can use a dumb container without havin to repeat the main ingredients and just declare the volumes in question.
