### ISSUE TITLE
Allow ENV variables in docker-compose.yml

### ISSUE THREAD

**Issue by mattes** [docker/compose#1287]
docker-compose.yml
```
web:
  image: some-image
  volumes:
    - $PWD:/home/web
```

It would be really cool if ``env`` variables would get replaced with their actual values during ``docker-compose up``.
