### ISSUE TITLE
Yaml Anchor Can't Deal List

### ISSUE THREAD

**Issue by hrbust-liu** [docker/compose#12873]
### Description

example follow yaml. I expect volumes list merged
```
x-common_volumes:
  &common_volumes
  - ${TEST_DIR:-./}:${TEST_DIR:-/test_dir}
  - ${LOG_DIR:-./}:${LOG_DIR:-/log_dir}

services:
  server:
    image: xxx:${TAG:-latest}
    volumes: 
      - *common_volumes
      - ${SERVER_DIR:-./server_dir}:/server_dir
```
