### ISSUE TITLE
[BUG] docker compose not working with variables from .env file whose values have #

### ISSUE THREAD

**Issue by sawyna** [docker/compose#12881]
### .env file
```
DB_HOST="host.docker.internal"
DB_PORT=5432
DB_USER=db_user
DB_PASSWORD=something#afterhash
DB_NAME=db_name
```

### docker-compose.yml
```
services:
  supertokens:
    container_name: test-supertokens
    environment:
      ACCESS_TOKEN_VALIDITY: 3600
      POSTGRESQL_DATABASE_NAME: ${DB_NAME}
      POSTGRESQL_HOST: ${DB_HOST}
      POSTGRESQL_PORT: ${DB_PORT}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_USER: ${DB_USER}
      POSTGRESQL_TABLE_NAMES_PREFIX: st_
      REFRESH_TOKEN_VALIDITY: 144000
    image: supertokens/supertokens-postgresql:5.0-5.0
    networks:
      - services
    ports:
      - 30001:3567
```

## What's happening?

The above setup is failing with the exception `com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping`.

## What did I try?

```
DB_PASSWORD="something#afterhash" 
DB_PASSWORD='something#afterhash'
```

## What's working?

`DB_PASSWORD=something\#afterhash`

Escaping the hash in the value seems to work. As per the [documentation](https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#env-file-syntax), `VAR="VAL"` should also work. I'm not sure why it doesn't.

It feels weird to have to escape the `#` within the value. 

What's more weird is that the quotes around DB_HOST's value work when the # is escaped in the password. But it doesn't work when the # is not escaped. It throws the same marked yaml exception but on the DB_HOST.

### Compose Version

```Text
Docker Compose version v2.31.0-desktop.2
```

### Docker Environment

```Text
Client:
 Version:    27.4.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.5.1
    Path:     /Users/yash/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2-desktop.1
    Path:     /Users/yash/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0-desktop.2
    Path:     /Users/yash/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/yash/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Beta) (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/yash/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/yash/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/yash/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/yash/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/yash/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/yash/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.1
    Path:     /Users/yash/.docker/cli-plugins/docker-scout

Server:
 Containers: 9
  Running: 6
  Paused: 0
  Stopped: 3
 Images: 24
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.654GiB
 Name: docker-desktop
 ID: a49e31a0-5543-4115-ac2c-7f3c6aa72cae
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/yash/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```
