### ISSUE TITLE
[BUG] build failing to check already built dependencies

### ISSUE THREAD

**Issue by israelglar** [docker/compose#12928]
### Description

I'm running the code that's on `main` . Because of #12925 it now [produces bake targets for all services](https://github.com/docker/compose/commit/213c03f99afc516b76bdf46f60769d3fa7015359)

This now causes all depedencies to be in the expected built images and causes an error.

### Steps To Reproduce

```yaml
services:
  main:
    build:
      dockerfile_inline: |
        FROM alpine
    entrypoint: ["echo", "Hello from main"]
    depends_on:
      - dep1

  dep1:
    build:
      dockerfile_inline: |
        FROM alpine
    entrypoint: ["echo", "Hello from dep1"]
```
first run `docker compose dep1` 
then run  `docker compose main` - this will build the image but exit with an error `build result not found in Bake metadata for service dep1`

### Compose Version

```Text
Commit 213c03f
```

### Docker Environment

```Text

```
