### ISSUE TITLE
[BUG] docker compose up with --wait and a provider exits as soon as provider is done

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/compose#12953]
### Description

I would expect all the services to be up and running before exiting.

### Steps To Reproduce

Use the following compose file:
```yaml
services:
  docker-model-runner:
    provider:
      type: model
      options:
        model: ai/smollm2:135M-Q4_K_M

  backend:
    image: nginx
    depends_on:
      - docker-model-runner
```
and then `docker compose up --wait`: the compose command will exit almost immediately, before the actual backend service is up and running. 

### Compose Version

```Text

```

### Docker Environment

```Text

```
