### ISSUE TITLE
[BUG] depends_on fails on 2.37

### ISSUE THREAD

**Issue by lobbin** [docker/compose#12979]
### Description

After we got an update from 2.36.2 to 2.37.3 our builds suddenly started to fail. Seems related to depends_on not being properly applied.

### Steps To Reproduce

With this compose under 2.36.2, bootstrap waits for tools to finalize before starting with bootstrap. On 2.37.3 both of them starts in parallell, which bootstrap failing due to tools taking longer time to complete.

```
secrets: {}
services:
  tools:
    build:
      args:
      - VERSION=0.1.dev1
      context: <path>
      dockerfile: <path>/Dockerfile
    image: <another path>:0.1.dev1
  bootstrap:
    build:
      context: /tmp/tmpwhp_cl07/bootstrap
      dockerfile: /tmp/tmpwhp_cl07/bootstrap/Dockerfile
      secrets: []
    depends_on:
    - tools
    image: <path>:<version>

```

### Compose Version

```Text
➜ docker compose version
Docker Compose version v2.37.3
```

### Docker Environment

```Text
➜ docker info
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.37.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.167.4.8-WSL2
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.49GiB
 Name: <name>
 ID: <id>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Anything else?

Can't share the Dockerfile, but any content should work. However, for the problem to be visible, the dependent bootstrap image Dockerfile should dependent on the tools image.

**Comment by ndeloof** [comment]
`depends_on` without much details implies `condition: service_started`,  seems you rely on `condition: service_completed_successfully` to enforce dependent service only if started after the "init" container stopped.

I guess this only worked with a previous version by chance, as `tools` service was fast enough to execute before `bootstrap` actually starts

**Comment by lobbin** [comment]
@ndeloof Here's a better example. This works as (we) expect in 2.36 but fails in 2.37. Are you saying that we are using this wrong?

> compose.yaml
```
services:
  tools:
    build:
      dockerfile: Dockerfile-tools
    image: local-tools:1.0
  bootstrap:
    build:
      dockerfile: Dockerfile-bootstrap
    depends_on:
    - tools
    image: local-bootstrap:1.0
```

> Dockerfile-tools
```
FROM alpine
RUN sleep 5s
```

> Dockerfile-bootstrap
```
FROM local-tools:1.0
```
