### ISSUE TITLE
[BUG] 2.37 multiple issuels - progress env ignored, logs fails

### ISSUE THREAD

**Issue by p-mcgowan** [docker/compose#12980]
### Description

`2.37.3-1~ubuntu.22.04~jammy`

issue1: 
BUILDKIT_PROGRESS=plain stopped working (if this is intentional I missed the notes). --progress=plain still works as expected.

issue2:
`docker compose logs` fails with 
`Error response from daemon: configured logging driver does not support reading`
which previously showed a warning but logged all others.

repro compose yml and dockerfile

```yaml
name: compose-test

services:
  test1:
    container_name: test1
    build:
      context: .
      args:
        what: test1
    depends_on:
      - test2
    init: true
    command: sh -c 'while true; do sleep 10; echo test1; done'

  test2:
    container_name: test2
    build:
      context: .
      args:
        what: test1
    init: true
    command: sh -c 'while true; do sleep 10; echo test1; done'
    logging:
      driver: none
```
```dockerfile
FROM busybox

ARG what
RUN echo test $what
```

![Image](https://github.com/user-attachments/assets/9c19990d-fceb-4ca6-b7cf-123f19ff94ca)

### Steps To Reproduce

1. ubuntu, docker-compose-plugin/jammy 2.37.3-1~ubuntu.22.04~jammy amd64
2. copy test files from above
3. `BUILDKIT_PROGRESS=plain docker compose up -d --build --force-recreate`
4. `docker compose logs -f`

### Compose Version

```Text
v2.37.3 (no docker-compose)
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    28.3.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.36.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 58
 Server Version: 28.3.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-142-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31GiB
 Name: acrbot
 ID: 32EJ:KZDO:3JOJ:2QN5:6KUX:NLAA:2PU7:GYLO:X4RS:IYZG:FBZT:DZZ3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: acrontum
 Experimental: false
 Insecure Registries:
  registry.test:5000
  repos.acrontum.net:4567
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```
