### ISSUE TITLE
Only one data volume container can be started

### ISSUE THREAD

**Issue by hesonglin006** [docker/compose#1306]
I used the command `docker-compose scale datacontainer=3`,I found there is only datacontainer_3 can be started,why? I will be appreciated for your response!

**Comment by christianbundy** [comment]
Can you share `docker-compose.yml` or something so that we can reproduce the problem?

**Comment by hesonglin006** [comment]
Of cource,thank you.this is the `docker-compose.yml`:
```  
datacontainer: 
  image: debian:wheezy  
  volumes:  
   - /www:/usr/share/nginx/html:ro  
```  
Then if I use the command `docker-compose scale datacontainer=3`,The output will be:  
```  
Creating composetest_datacontainer_1...
Creating composetest_datacontainer_2...
Creating composetest_datacontainer_3...
Starting composetest_datacontainer_1...
Starting composetest_datacontainer_2...
Starting composetest_datacontainer_3...
Removing composetest_datacontainer_1...
Removing composetest_datacontainer_2...
Removing composetest_datacontainer_3...  
```  
I don't know why it is only the last datacontainer can be started.thx again.

**Comment by nayyden** [comment]
Hi, it seems to me that the containers just exits.
By default, the image `debian:wheezy` will exit as there isn't default service to run, unless you change the default command.

**Comment by nayyden** [comment]
I just tried it with a long command:

``` yaml
datacontainer: 
  image: debian:wheezy  
  volumes:  
   - /www:/usr/share/nginx/html:ro
  command: bash -c "while true; do echo "hello"; sleep 2; done;"
```
Output:
``` bash
$~ docker-compose scale datacontainer=3
Creating developer_datacontainer_2...
Creating developer_datacontainer_3...
Starting developer_datacontainer_1...
Starting developer_datacontainer_2...
Starting developer_datacontainer_3...

$~ docker-compose  ps
          Name                         Command               State   Ports 
--------------------------------------------------------------------------
developer_datacontainer_1   bash -c while true; do ech ...   Up            
developer_datacontainer_2   bash -c while true; do ech ...   Up            
developer_datacontainer_3   bash -c while true; do ech ...   Up

```
