### ISSUE TITLE
Service in extends option should be optional

### ISSUE THREAD

**Issue by aanm** [docker/compose#1361]
I think it would be better if the service option to be optional.
`compose` would look through extends' file and find if there's a service with the same name of the service where the extends option is.
```yml
#docker-compose.yml
web:
  extends:
    file: common-services.yml
    #service: web
  environment:
    - DEBUG=1
  cpu_shares: 5
```
```yml
#common-services.yml
web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - "/data"
```
