### ISSUE TITLE
Improve Compose extends and make it less verbose and more powerful.

### ISSUE THREAD

**Issue by Vad1mo** [docker/compose#1380]
Currently compose extends is very verbose.

We use extends in the way that we have a base file and then for each environment we replace the significant parts that we want to override or have different.

In the current state of extends if you want to achieve the same you need almost rewrite everything.
Look at out actual example and how verbose it is. There are only two lines that matter.
## common.yaml 
````yaml
elasticsearch:
  image: zinvoice/elasticsearch
  hostname: elasticsearch
  restart: always
  dns: 172.17.42.1
  ports:
    - "9200:9200"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /data/elasticsearch:/opt/elasticsearch/data/elasticsearch

logstash:
  image: zinvoice/logstash
  hostname: logstash
  dns: 172.17.42.1
  restart: always
  ports:
    - "5000:5000"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

kibana:
  image: zinvoice/kibana
  hostname: kibana
  dns: 172.17.42.1
  restart: always
  ports:
    - "5601:5601"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

logspout:
  image: zinvoice/logspout
  hostname: logspout
  command: logstash://logstash.docker:5000
  restart: always
  dns: 172.17.42.1
  ports:
    - "8003:8000"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

doorman:
  image: zinvoice/doorman
  hostname: doorman
  restart:  always
  dns: 172.17.42.1
  ports:
    - "8085:8085"
```

## child.yaml
```yaml
elasticsearch:
  extends:
    file: ../common.yml
    service: elasticsearch

logstash:
  extends:
    file: ../common.yml
    service: logstash

kibana:
  extends:
    file: ../common.yml
    service: kibana

logspout:
  extends:
    file: ../common.yml
    service: logspout

doorman:
  environment:
    - DOORMAN_GITHUB_APPID=xxxxxxxx
    - DOORMAN_GITHUB_APPSECRET=xxxxxx
  links:
    - nginxtrusted
  extends:
    file: ../common.yml
    service: doorman
````

With the new extends feature one would add a global_extends/import like this:

## extended_child.yaml
```yaml
global_extends: 
 - common.yaml
 - extra.yaml 

doorman:
  environment:
    - DOORMAN_GITHUB_APPID=xxxxxxxx
    - DOORMAN_GITHUB_APPSECRET=xxxxxx
```
Thats it. 

## Advantages
1. A less verbose code is easy to maintain and understand
2. You can add remove service in the base.yaml without adding/removing entries in the children. (Missing a container in Prod because someone forgot to ad it as into the prod.yaml.
3. You can aggregate services into one.
4. The configuration can be easily created by CI or or maintained by an application.
5. You have a nice overview what gets set and you can check in this in a repo.
6.  This will make #1377 and #495 obsolete and 75 +1er happy :) 

## Main featues

- append nodes that are declared in parent yaml
- modify/overwrite nodes declared in parent
- add new nodes
- the only thing you can't do is to removed nodes
see examples in https://github.com/docker/compose/issues/1380#issuecomment-119202857

**Comment by dnephin** [comment]
I think this is very similar to what I proposed in #318 , and it's a feature I'm still very interested in. There's a bunch of complexity with something like this, so it's taking a while to get there, but I think we're getting closer.

**Comment by aanm** [comment]
Also https://github.com/docker/compose/issues/1361, but I agree, the optimal would be `docker-compose up --extends ../common.yml` and that's it, all the merge would be automagical since the services' names would be the same in `../common.yml` and `docker-compose.yml`

**Comment by Vad1mo** [comment]
indeed #318 and #1361 has the same intention. @dnephin I am wondering why it is such a complex task? Does this go beyond [merging two yaml files](http://stackoverflow.com/questions/823196/yaml-merge-in-pythonhttp://stackoverflow.com/questions/823196/yaml-merge-in-python) into one tree.

**Comment by aanm** [comment]
@Vad1mo Don't forget that `extends` merge both configuration depending on each option. For example:
> In the case of build and image, using one in the local service causes Compose to discard the other, if it was defined in the original service.

(@Vad1mo  you have a malformed link on the previous comment)

**Comment by andrerom** [comment]
The format might need some work, here is format used in [Symfony framework](https://github.com/symfony/symfony-standard/tree/2.7/app/config "Link to Symfony standard distrobution config files"), addopted a bit to make it relevant:
```yml
# Any config blocks imported here can be selectively be changed below
# wouldn't normally have one file per service/container, this is simplified example
imports:
    - { resource: parameters.yml }
    - { resource: rails.yml }
    - { resource: mysql.yml }


# Additional concept: Service alias
# http://symfony.com/doc/current/components/dependency_injection/advanced.html#aliasing
db:
    alias: mysql

# Additional concept: parameters, don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
# typically in separate file parameters.yml
parameters:
    app_env: prod

rails:
  links:
    - db
  environment:
      RACK_ENV: "%app_env%"


```

**Comment by Vad1mo** [comment]
@andrerom 
There is a conceptual difference between extends and import. Import is for composing and orchestrating services together to create something new/big out of small peaces. 
Example: Frontend + backend + db merged together into one service file to start everything together. 

On the other side extends means you want to extend or modify/override the behavior of the services you already have in place. You extend something for a specific situation.
Example: add/change port or set env var. of prod.

**Comment by andrerom** [comment]
I agree, but then what you imply is that your global_extends does not really import any of the services, so your example would need to be extended so you define all services again (with a `extends.service` part, but you are saving the `extends.file` part). So your example to me looks more like an import, where you redefine part of the doorman service, exactly like imports does in my example.

**Comment by erichonkanen** [comment]
@Vad1mo @andrerom I am new to docker/compose etc and working on a new microservice based project... I'm running into issue where I wanted to have a top level repo with just a docker-compose.yml that orchestrates all the pieces together e.g.
```
Example: Frontend + backend + db merged together into one service file to start everything together.
```
It seems that the current extends implementation doesnt support links from child compose files so I'm wondering if what you guys are talking about applies to this case (a master compose.yml that ties all the services together and individual compose.yml files within each service that is decoupled mostly and can have links etc)

Just curious thx!

**Comment by Vad1mo** [comment]
@erichonkanen what you describe was initially not in my intention but the proposal would also allow this kind of behavior.

**Comment by aanand** [comment]
@erichonkanen What you describe is something we've talked about before - see #758 - and which we should continue to explore.

**Comment by erichonkanen** [comment]
@aanand ok so I see the proposed new `includes` property, for e.g. microservice project where you have a bunch of services that communicate over rest etc, would you only need to include each of the services and then run compose up (which would build all the services and their containers etc)?

e.g. would this be how to do it?

```
project-config:
    include:
        content-service:
            url: '/path/to/compose.yml'
        other-service:
            url: '/path/to/other/compose.yml'
```
Also would this be able to pull from a git repo or dockerhub image that contains a docker-compose.yml?

Thanks!

**Comment by aanand** [comment]
I'd like to think more about "global extends". It would be a much less verbose solution to the problem of configuring an app for multiple environments, which is one of the primary things users are asking for better ways to do.

Let's imagine the simplest possible implementation: you can import all services from a **single** Compose file, and can then add new services and reconfigure imported ones.

**base.yml**

```yaml
web:
  build: .
  links:
    - db

db:
  image: postgres
```

**docker-compose.yml**

```yaml
EXTENDS: base.yml

web:
  ports:
    - "8000:8000"
  volumes:
    - .:/code
```

**production.yml**

```yaml
EXTENDS: base.yml

frontend:
  image: registry.mycompany.com/reverse-proxy
  ports:
    - "80:8000"
  links:
    - web

web:
  image: registry.mycompany.com/webapp
```

I'm a bit scared of this feature because of the amount of implicit-ness, but it seems to be the only sensible way to avoid the huge amount of boilerplate currently needed to make small changes to a large file.

As for extending multiple files (as in @Vad1mo's example), the potential for confusion there seems much greater. What use cases would it serve?

**Comment by erichonkanen** [comment]
@aanand I am wondering if the use case of a microservice based architecture is a use case? Currently Im working on a new project using both docker and microservices for the first time... compose is a neat and convenient tool but the one thing I wish it had were the ability to decouple extended services/repos more cleanly, aka not have to put the links in the top level docker-compose.yml.

Something like this would be sweet:

# orchestrate.yml
```
service-content:
  import:
    file: ../service-content/docker-compose.yml

service-auth:
  import:
    file: ../service-auth/docker-compose.yml

service-accounting:
  import:
    file: ../service-accounting/docker-compose.yml
```

# service-content/docker-compose.yml
```
web-db:
  image: postgres:latest

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - web-db
```

Which would make containers prefixed by the top-level import name e.g. `service-content_web-db_1`

What are your thoughts on something like this? Right now we are definining everything in the orchestrate.yml file which works but it couples everything to that file/repo whereas it'd be ideal to allow each service to define it's own config/build/link instructions etc...

**Comment by andrerom** [comment]
@aanand I think this would work.

In my use case, what I need is to be able to setup a app cble of using several different services depending on config.

examples: using postgres instead of mysql in one specific setup and configure app container for this with env variable + optionally adding memcache or redis as caching with again injecting env for this to app container. + optionally adding solr and inject app config for it + being able to do what you showed above, adding varnish/reverse-proxy, again injecting config to app for that so it can purge cache.

This is why I was thinking `import` as it essentially allows the misc services to be defined separately, and the misc combinations import and configure as they seem fit. But I think it can work with what you propose also, with base being the small and the more complex setups gradually extending it.

**Comment by aanand** [comment]
@erichonkanen That's an interesting idea - creating multiple tiers of nesting - but based on your example I think we're now talking about a different feature entirely. It sounds a bit more like what @dnephin proposed in #318, where multiple independently-runnable apps are brought together.

**Comment by erichonkanen** [comment]
@aanand ok yeah that makes sense, I was thinking about it more and it seems slightly different

**Comment by aanand** [comment]
@andrerom your suggestion sounds a lot like Compose's existing `extends` option. What are the primary differences, as you see it?

**Comment by aanand** [comment]
Important note: the global `EXTENDS` option lets you extend files with links in, as opposed to the single-service `extends` option, which doesn't let you extend services that link to others.

(The same applies to the other types of inter-service dependency, `volumes_from` and `net: container`)

**Comment by Vad1mo** [comment]
@aanand regarding your https://github.com/docker/compose/issues/1380#issuecomment-117729685 

as in my first question  multiple extends would allow to combine services allowing to deploy a smaller set of services on the developers machine for example or you could deploy only subset of services to a machine. Multiple extends is IMHO not a top priority for us. 
Top Priority for us is to reduce the current verbose boilerplate code which is too error prone. Currently  each litte change  need a modification in multiple files.

**Comment by scottbelden** [comment]
@aanand Would your proposal allow for services that extend a base file to have a different name? For example, I would like to have a basic "connection" setup and all my services could use that connection.

conn.yml
```yml
conn:
  links:
    - db
    - mq

db:
  image: postgres

mq:
  image: rabbitmq
```

serviceA.yml
```yml
EXTENDS: conn.yml

serviceA:
  # somehow specify to use the conn links
  image: imageA
```

serviceB.yml
```yml
EXTENDS: conn.yml

serviceB:
  # somehow specify to use the conn links
  image: imageB
```

**Comment by Vad1mo** [comment]
@scottbelden in the child compose file you could basically 
* extend nodes declared in parent
* modify or overwrite nodes declared in parent  
* add new nodes
* the only thing you can't do is to removed nodes

**Comment by andrerom** [comment]
> @andrerom your suggestion sounds a lot like Compose's existing extends option. What are the primary differences, as you see it?

@aanand you are right, combination of service and global extends will allow it without to much boilerplate.

**Comment by dnephin** [comment]
@aanand I see this feature as basically the same idea as #318.  The terminology is a bit different, but the goals and implementation are basically identical.

`EXTENDS` would just be a more restrictive version of "include" or "import". `EXTENDS` forces you to have a chain of files, where as import would let you pull in unrelated things into a single composition (instead of trying to force them into some hierarchy). It's basically inheritance vs composition, and I always opt for composition.

**Comment by erichonkanen** [comment]
maybe this is superficial but why the all caps `EXTENDS`? any alternatives? also I like the idea of composition via include/import

**Comment by Vad1mo** [comment]
@dnephin full ack for your https://github.com/docker/compose/issues/1380#issuecomment-118205945 the goal is the same the approach is different. The only advantage there might in favor of EXTENDS might be the ability to cope better with override conflicts and cycles. 

Bu to be honest in the meantime I don't care what is "the" best solution. Anything (#318, #1380 or #1377)  better then the status quo would already improve the situation by a magnitude for many here.

Its ok for me to close this proposal and move to #318

**Comment by aanand** [comment]
@dnephin I agree there's a lot of overlap (and that composition usually beats inheritance), but how would #318 serve the use case of wanting to make small changes to an app's configuration to tailor it to a particular environment? Do you have any ideas for syntax/semantics there?

**Comment by Vad1mo** [comment]
finally, I see it that main difference between this proposal and #318.

- append/extend content in nodes that are declared in parent yaml
- modify/overwrite nodes declared in parent

Here are the two examples that of the above features: 

### parent.yaml
```yaml
doorman:
  image: zinvoice/doorman
  hostname: doorman
  dns: 172.17.42.1
  ports:
    - "8085:8085"
````

### append.yaml
```yaml
global_extends: 
 -  parent.yaml

doorman:
  restart: always
````

### overwrite.yaml
```yaml
global_extends: 
 -  parent.yaml

doorman:
  hostname: doorman_prod
````

@dnephin can this be achieved with #318 ?

**Comment by dnephin** [comment]
We already have a way to extend services, so if we were to add a way to include other compositions, it seems like it would be possible to continue using the existing mechanism for extension of services.

**Comment by Vad1mo** [comment]
but the current way is quite verbose. As you can see from my initial proposal you basically double your code base just to make some modifications. I am not sure if the current extends could be modified in a way to reduce the verbosity and adding the appen/modify functionality.

**Comment by aanm** [comment]
@Vad1mo Why isn't the @aanand proposal of having a "GLOBAL" keyword good enough?

**Comment by Vad1mo** [comment]
@aanm you mean from his https://github.com/docker/compose/issues/1380#issuecomment-117729685 ?

**Comment by dnephin** [comment]
@Vad1mo includes are just a different model. You wouldn't have the same configuration.  `common.yaml` would actually have links between things, you wouldn't need `extended_child.yaml` at all.  All you'd have to do would be create a new doorman service and have it link to the appropriate services in `common.yaml`

**doorman.yaml**

```yaml

include: common.yaml

doorman:
  image: zinvoice/doorman
  hostname: doorman
  restart:  always
  dns: 172.17.42.1
  ports:
    - "8085:8085"
  environment:
    - DOORMAN_GITHUB_APPID=xxxxxxxx
    - DOORMAN_GITHUB_APPSECRET=xxxxxx
  links:
    - nginxtrusted
```

If you need some other variation of dooman, you'd create `doorman-prod.yaml` and include `common.yaml` again. This is where the comparison between composition vs inheritance comes in. You're no longer inheriting things, you're breaking them up into components and sharing them that way.
