### ISSUE TITLE
docker run working directory option

### ISSUE THREAD

**Issue by theronic** [docker/compose#144]
Please add an option in fig.yml to mount the working directory like with `docker run -w /path/to/workdir <image> <command>`, which is also specified in a Dockerfile with:

```
WORKDIR /path/to/workdir
```

Something like this in fig.yml:

```
web:
  - image: my-image
  - command: my-command
  - workdir: /path/on/container
```
