### ISSUE TITLE
trouble running docker inside container booted via boot2docker

### ISSUE THREAD

**Issue by hackerhasid** [docker/compose#1443]
I posted a [question to SO](https://stackoverflow.com/questions/30377285/error-running-docker-inside-docker) about this. But to summarize:

1. Attempting to start the docker service within a container run via docker-compose fails to start docker (errors below)
  * I run `docker-compose run web /bin/bash` and then at the resulting prompt I type `service docker start`)
2. Running the same container manually and then starting docker inside of that container succeeds
 * I get the image name from `docker images` and then run `docker run --privileged=true -ti IMAGE_NAME /bin/bash ` then at the resulting prompt I type `service docker start`

Here's the log (/var/log/docker.log) from attempting to start `docker` within the container started by docker-compose:

> time="2015-05-21T12:40:23Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors"
time="2015-05-21T12:40:23Z" level=error msg="There are no more loopback devices available."
time="2015-05-21T12:40:23Z" level=info msg="+job serveapi(unix:///var/run/docker.sock)"
time="2015-05-21T12:40:23Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2015-05-21T12:40:23Z" level=fatal msg="Shutting down daemon due to errors: error intializing graphdriver: loopback mounting failed"```

Here's the relevant `docker-compose.yml`:

```
db:
  image: postgres
  ports:
    - "5432"
redis:
  image: redis
  ports:
    - "6379"
web:
  privileged: true
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  environment:
    - A=B
  ports:
    - "3001:3000"
  links:
    - db
    - redis
```
