### ISSUE TITLE
up does not establish links to running subset of service

### ISSUE THREAD

**Issue by pangloss** [docker/compose#1520]
If I have a basic docker compose compose config as follows, and run `docker-compose up -d db`, then later run `docker-compose up -d --no-recreate api`, the api container does not appear to actually be linked to the db, and none of the expected environment variables are present in the api instance.

```yaml
data:
  build: docker/api-data/
db:
  build: docker/db/
  volumes_from:
    - data
api:
  build: .
  links:
    - db:db
  volumes:
    - ./:/app
  volumes_from:
    - data
```
