### ISSUE TITLE
Compose doesn't collaborate with Swarm when 1 service has 2 dependencies

### ISSUE THREAD

**Issue by jpetazzo** [docker/compose#1528]
## What I do

`docker-compose up` with the following `docker-compose.yml` file, against a 4-nodes Swarm cluster:

```yaml
hasher:
  image: jpetazzo/dockercoins_hasher:1433781053
  ports: ['8002:80']
redis: {image: redis}
rng:
  image: jpetazzo/dockercoins_rng:1433781053
  ports: ['8001:80']
webui:
  image: jpetazzo/dockercoins_webui:1433781053
  links: [redis]
  ports: ['8000:80']
  volumes: ['webui/files/:/files/']
worker:
  image: jpetazzo/dockercoins_worker:1433781053
  links: [rng, hasher, redis]
```

## What I expect

The app comes up (with all containers on the same node, since `redis`, `rng`, and `hasher` are all dependencies of `worker`).

## What I see

Swarm places `redis`, `rng`, and `hasher` on random nodes. If at least two containers end up on different nodes,  I get the following error:

```
Unable to find a node fulfilling all dependencies: --link=dockercoins_hasher_1:dockercoins_hasher_1 --link=dockercoins_hasher_1:hasher --link=dockercoins_hasher_1:hasher_1 --link=dockercoins_redis_1:dockercoins_redis_1 --link=dockercoins_redis_1:redis --link=dockercoins_redis_1:redis_1 --link=dockercoins_rng_1:dockercoins_rng_1 --link=dockercoins_rng_1:rng --link=dockercoins_rng_1:rng_1
```

## Possible resolutions

- run a full dependency resolution and submit appropriate placement constraints to Swarm
- say that it's Not Our Problem, By Design©

**Comment by aanand** [comment]
Swarm is supposed to co-schedule linked containers. I've not confirmed that it was still doing so since 0.2.0, though - what version are you using?

**Comment by timfallmk** [comment]
@aanand @jpetazzo I can confirm that scheduling seems to properly schedule linked containers on 0.2.0+

**Comment by jpetazzo** [comment]
Have you tried when there are 2 dependencies?

I don't understand how that could work without Swarm passing and explicit
placement constraint.

**Comment by aanand** [comment]
Right, I see the issue. If C depends on both A and B, but A and B are independent, Swarm won't know that it needs to co-schedule all three.

I think this should be solved in the long term by adding a "multi-create" command to the Docker API, so that Swarm can take all scheduling constraints into consideration (ping @shykes and @vieux, with whom I vaguely recall discussing this before).

Short-term, perhaps we should recommend that people set an affinity constraint. It can be done based on Compose's labels, e.g.

```yaml
a:
  image: me/a

b:
  image: me/b
  environment:
    - "affinity:com.docker.compose.service==a"

c:
  image: me/c
  links:
    - a
    - b
  environment:
    - "affinity:com.docker.compose.service==a"
```

Except there's no guarantee that `a` will be spun up before `b`. Hmmmm.
