### ISSUE TITLE
Show warning when failing to limit memory

### ISSUE THREAD

**Issue by poc7667** [docker/compose#1546]
My server has **2GB** mem

I launched **2 containers** in the server with docker-compose

Although I set the memory limiti, but it seems not work

![](https://i.imgur.com/J3tpbBT.png)
# docker-compose

```
hub:
  mem_limit: 256m
  image: selenium/hub
  ports:
    - "4444:4444"
test:
  mem_limit: 256m
  build: ./
  links:
    - hub
  ports:
    - "5900"      
```
