### ISSUE TITLE
registry: s3 storage

### ISSUE THREAD

**Issue by c0rnflex** [docker/compose#1557]
Hiya,
I'm trying to set up a new registry container with an S3 storage backend.

I went by the guidance at 
https://github.com/docker/distribution/blob/master/docs/deploying.md
and
https://github.com/docker/distribution/blob/master/docs/configuration.md

But I get 
> Unsupported config option for storage service: 's3'

Here's my docker-compose.yml:
```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
storage:
    s3:
        accesskey: awsaccesskey
        secretkey: secretkey
        region: region
        bucket: bucket
        encrypt: true
        secure: true
        v4auth: true
        chunksize: 5242880
        rootdirectory: /s3/object/name/prefix
```

**Comment by aanand** [comment]
I think you've conflated two different configuration files.

1. `docker-compose.yml` should list just the containers you want to run. It doesn't know anything about registry storage, etc.

    ```yaml
    registry:
      restart: always
      image: registry:2
      ports:
        - 5000:5000
    ```

2. Your can specify storage options in your registry configuration file. I'm not very familiar with the registry, so I'm not sure what the file should be called, how to get it inside the container etc.

    ping @dmp42 - can you shed some light here? I can't make it out from the docs.

**Comment by dmp42** [comment]
@aanand yes, there is some confusion here.

@c0rnflex take a look at:
https://github.com/docker/distribution/blob/master/docs/deploying.md#using-compose

Using compose lets you specify registry settings through *environment variables*. For example: REGISTRY_HTTP_TLS_CERTIFICATE

These settings are indeed documented in the configuration file for the registry, but the yml file used by the registry is not the same thing as the compose.yml file.

Hope that clarifies.

**Comment by aanand** [comment]
@dmp42 am I right in thinking the following Compose file would do what @c0rnflex needs?

```yaml
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE_S3_ACCESSKEY: awsaccesskey
    REGISTRY_STORAGE_S3_SECRETKEY: secretkey
    REGISTRY_STORAGE_S3_REGION: region
    REGISTRY_STORAGE_S3_BUCKET: bucket
    REGISTRY_STORAGE_S3_ENCRYPT: true
    REGISTRY_STORAGE_S3_SECURE: true
    REGISTRY_STORAGE_S3_V4AUTH: true
    REGISTRY_STORAGE_S3_CHUNKSIZE: 5242880
    REGISTRY_STORAGE_S3_ROOTDIRECTORY: /s3/object/name/prefix
```
