### ISSUE TITLE
relative path in extends work's not as expected

### ISSUE THREAD

**Issue by TwentySixer** [docker/compose#1564]
Our idea was to bundle some configuration settings in a config.yml

```yaml 
web:
  volumes:
   - ../development:/srv    
   - ../logs:/logs        
```
and extend the services in docker-compose.yml like that
```yaml
hal1:
  build: phpBuild/
  extends:
    file: config.yml
    service: web
  restart: always
  command: supervisord
```
but this is not working.
For absolute path in config.yml it work's. 

Both files are in the same directory.
