### ISSUE TITLE
docker-compose does not detect volume (file) as entrypoint

### ISSUE THREAD

**Issue by fer2d2** [docker/compose#1574]
Hi,

I have the following docker-compose structure:

*docker-compose-common.yml*
```
symfony:
  hostname: symfony-common
  dns:
    - "xxx.xxx.x.xxx"
  build: symfony/
  restart: always
  volumes:
    - ./symfony/code:/var/www
    - ./symfony/start.sh:/start.sh
    - ./symfony/test.sh:/test.sh
    - ./symfony/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
    - ./symfony/supervisord/conf:/etc/supervisor/conf.d
  working_dir: /var/www
  entrypoint: /start.sh
  environment:
    DEV_HOST: vdeveloper.lan
    TERM: xterm
  user: devel
```

*docker-compose.yml*
```
symfony:
  extends:
    file: docker-compose-common.yml
    service: symfony
  hostname: symfony
  volumes:
    - ./symfony/initialize.sh:/initialize.sh
  environment:
    DEV_HOST: vfer2d2.lan
  expose:
    - "1025"
    - "4730"
  ports:
    - "127.0.0.1:22:22"
    - "0.0.0.0:1080:1080"
  user: devel
```

With docker-compose *1.2.x* and docker *1.6.x* I was able to use as entrypoint a file mounted as a volume. Now when I run `docker-compose up` with docker-compose *1.3.0* and docker *1.7.0* I get this error:

```
Cannot start container 98726ff530a2b28b362e0f4f735c938929de9e2d907914460283c9422717e30a: [8] System error: exec: "\"/start.sh\"": stat "/start.sh": no such file or directory
```

Running the docker's command counterpart it works:
```
docker run --volume `pwd`/symfony/start.sh:/start.sh --entrypoint /start.sh b7ca1da5fba6
```

I have tested this error using several docker images (redis, mongodb, custom...) and the error persists.
