### ISSUE TITLE
`rm` reports that it will delete services that aren't defined in the current file

### ISSUE THREAD

**Issue by soulrebel** [docker/compose#1596]
Hello, 
I have a `data.yml` that declares various data containers that should not be deleted in normal circumstances.

In the main `docker-compose.yml` these containers are referenced by name in `volumes_from`.

With this setup under 1.2 `docker-compose rm` deletes only containers from `docker-compose.yml`. 
Since 1.3 it tries to delete also the data containers, and this breaks my deploy.

I think that the yml file should be used to restrict the containers found by the label lookup, unless some specific command line option is given.

As a workaround, is there another way to prevent deletion of data containers?

**Comment by aanand** [comment]
I don't fully understand your setup. Could you paste your `data.yml` and `docker-compose.yml`?

**Comment by soulrebel** [comment]
Example data.yml
```
dbdata:
    image: busybox
    volumes:
        - "/var/lib/postgresql/data"
    command: true
```

Example docker-compose.yml:
```
db:
    image: postgres
    volumes_from:
        - mycompose_dbdata_1

app:
    image: myregistry/myapp
    links:
        - db
    ports:
        - "80:8080"
```

`docker-compose rm` should delete only db and app. To delete data you should need to add `-f data.yml`. 

I think this setup is quite clean and will be even better once we have support for custom container names.

**Comment by aanand** [comment]
So I can't reproduce the behaviour you're seeing, but I've found one, possibly two bugs:

1. `docker-compose rm` says that it's going to remove the data container, and then doesn't. I agree with you that it shouldn't remove it, but it doesn't seem to be doing that.
2. `docker-compose ps` lists the data container. Arguably a bug, but I think it might actually be a good thing.

In both cases, we should make sure to codify the correct behaviour in the test suite.

Can you confirm whether or not you get the same behaviour with the following config + commands?

**data.yml**:

```yaml
dbdata:
    image: busybox
    volumes:
        - "/var/lib/postgresql/data"
    command: true
```

**docker-compose.yml**:

```yaml
db:
    image: busybox
    command: top
    volumes_from:
        - 1596_dbdata_1
```

```
$ docker-compose -f data.yml up -d
Creating 1596_dbdata_1...

$ docker-compose ps
    Name        Command   State    Ports
----------------------------------------
1596_dbdata_1   true      Exit 0
```

```
$ docker-compose up -d
Creating 1596_db_1...

$ docker-compose ps
    Name        Command   State    Ports
----------------------------------------
1596_db_1       top       Up
1596_dbdata_1   true      Exit 0
```

```
$ docker-compose kill
Killing 1596_db_1...

$ docker-compose rm -f
Going to remove 1596_db_1, 1596_dbdata_1
Removing 1596_db_1...

$ docker-compose ps
    Name        Command   State    Ports
----------------------------------------
1596_dbdata_1   true      Exit 0
```
