### ISSUE TITLE
Add an "includes" to the docker-compose.yml DSL

### ISSUE THREAD

**Issue by parabuzzle** [docker/compose#1599]
We have `extends` which is awesome, but I would like to flip it the other way around with an `includes` operator. Would it be possible to do something like this:

```yaml
# web-common.yml
web: 
  image: nginx
  ports: 
    - "80:80"
```

```yaml
# db-common.yml
db:
  image: postgres
  ports: 
    - "5432:5432"
```

```yaml
# redis-common.yml
db:
  image: redis
  ports: 
    - "6379:6379"
```

```yaml
# production-compose.yml
includes:
  - db-common.yml
  - redis-common.yml
  - web-common.yml
```

```yaml
# development-compose.yml
includes:
  - db-common.yml
  - redis-common.yml

web: 
  extends:
    file: web-common.yml
    service: web
  command: bundle exec rails s -p 80 -b 0.0.0.0 thin
```

I may have missed this in the docs, but I don't see anything in the docs that explains how to do something like this, and I think it would be super useful and would reduce the amount of repeated config in projects.
