### ISSUE TITLE
Host 'xxx.xxx.xxx.xxx' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by hardikj** [docker/compose#1614]
I get the following error when my rails app try to connect to mysql
'Host 'xxx.xxx.xxx.xxx' is not allowed to connect to this MySQL server'
What am I doing wrong?

docker-compose.yml
```
db:  
  image: "mysql:5.5"
  volumes:
    - /var/lib/mysql/:/var/lib/mysql/
  expose:
    - 3306
web:
  image: "railsapp:dockerfile"
  command: /bin/bash -l -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/home/railsApp
  ports:
    - "3000:3000"
  links:
    - "db:db"
```
