### ISSUE TITLE
docker-compose run with isolated sets of services?

### ISSUE THREAD

**Issue by geeknam** [docker/compose#1630]
I have the following setup:

```yml
db:
  image: postgres:latest

app:
  ...
  links:
    - db
```

When I try to run `docker-compose run app testcommand` twice, it reuses the db container. Is it possible to make app create another db container?

What I'm after is:
- app_run_1 ---> db_1
- app_run_2 ---> db_2

I'm trying to isolate the services in order to run tests concurrently.
