### ISSUE TITLE
Default to current file in Compose extends

### ISSUE THREAD

**Issue by viranch** [docker/compose#1657]
I think it would be a lot more convenient if the `file` parameter in the `extends` block would default to the current file instead of throwing `KeyError`. Example:

```yml
base:
  image: nginx
web:
  extends:
    service: base
```

I would also suggest defaulting the `service` parameter to same as that its defined in if `file` is not missing. Example:

production.yml:
```yml
web:
  image: nginx
```
docker-compose.yml:
```yml
web:
  extends:
    file: production.yml
```

I do realize that the latter may be a little counter-intuitive, but I think the first part could be done.
