### ISSUE TITLE
Pulling an image for a service also pulls images for dependent services

### ISSUE THREAD

**Issue by viranch** [docker/compose#1764]
I'm not sure if this a bug or is it intentional. Consider the following docker-compose.yml:

```yml
db:
  image: mysql

web:
  image: nginx
  links:
    - db:database
```

Now when I do a `docker-compose pull web` it also pulls the `mysql` image. This may not be desired in a production system. Pulling both images probably makes sense if `mysql` is not present, but if its present and I want to upgrade just `nginx`, compose should not force me to pull `mysql` also.

Neither can I find a workaround similar to `--no-deps` for the `up` command.
