### ISSUE TITLE
Feature Request: Pass environment variables as CLI arguments when executing a docker build

### ISSUE THREAD

**Issue by maysale01** [docker/compose#1802]
If you have any tasks inside your Dockerfile that require environment variables specified in the docker-compose file, they will not be found. An easy solution would be to have environment variables passed in as arguments to the docker build command, i.e. 

docker-compose.yml
```
dev:
  build: .
  environment:
    - RACK_ENV=development
    - SESSION_SECRET=12345
```
    
As executed by `docker-compose`:
    `docker build . -eRACK_ENV=development -eSESSION_SECRET=12345`
