### ISSUE TITLE
docker-compose ignores the global settings of log-driver

### ISSUE THREAD

**Issue by mahnunchik** [docker/compose#1863]
/etc/default/docker 
```
DOCKER_OPTS='
-H tcp://0.0.0.0:2376
-H unix:///var/run/docker.sock
--storage-driver aufs
--tlsverify
--tlscacert /etc/docker/ca.pem
--tlscert /etc/docker/server.pem
--tlskey /etc/docker/server-key.pem
--label provider=generic
--log-driver=syslog
'
```

docker-compose.yml
```yml
web:
  build: ./
  ports:
    - "80:80"
  links:
    - db:DB
db:
  image: mariadb:latest
```

Following command starts application with default `json-file` log-driver:
```
$ docker-compose up -d
```
Despite the global specified `syslog` log-driver.

```bash
$ docker -v
Docker version 1.8.1, build d12ea79
$ docker-compose -v
docker-compose version: 1.4.0

```
