### ISSUE TITLE
net container:<service> option should combine host option

### ISSUE THREAD

**Issue by tarlabs** [docker/compose#1880]
```yaml
redis:
  image: redis
  ports:
   - 6380:6379
  net: container:mysql
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
```

I expected the port mapping to still work which doesn't. Also docker-compose ps doesn't list any port for redis as such.
