### ISSUE TITLE
`dockerfile` and `image` shouldn't be allowed in combination

### ISSUE THREAD

**Issue by aanand** [docker/compose#1908]
A file like this should result in a validation error:

```yaml
web:
  image: myimage
  dockerfile: Dockerfile.alt
```

This should also be documented.
