### ISSUE TITLE
Entrypoint should be allowed to be a string

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1997]
### Entrypoint as string

```yaml
web:
    image: alpine:edge
    entrypoint: 'sh'
```

`Service 'web' configuration key 'entrypoint' contains an invalid type, it should be an array`

I think string should be valid.
