### ISSUE TITLE
Error message for oneOf validation isn't bubbling up fine enough detail

### ISSUE THREAD

**Issue by mnowster** [docker/compose#2002]
(reported by @dnephin)

### Duplicate strings in command

```yaml
web:
    image: alpine:edge
    command: ['sh', 'sh']
```

`Service 'web' configuration key 'command' contains an invalid type, ...`

If I do the same thing with `entrypoint`, I get a better error message `Service 'web' configuration key 'entrypoint' value ['sh', 'sh'] has non-unique element`, but it's still an error
