### ISSUE TITLE
Problem with relative paths in volumes in Windows

### ISSUE THREAD

**Issue by alexandrev** [docker/compose#2050]
I'm using the docker-compose version 1.5.0 with the pull-request https://github.com/docker/compose/pull/1957. When I'm trying to start a group of containers which one of them has a relative path in the volume section like this:

 volumes:
  - "./data:/var/run/docker.sock"

I'm getting this error:

b'invalid mode for volumes-from: /var/run/docker.sock'

**Comment by dnephin** [comment]
This error suggests it's using `volumes_from` not `volumes`, could you post your full `docker-compose.yml` ?

**Comment by alexandrev** [comment]
Of course. I've been trying different posiblities. This is the full one right now.

centosjava:
 build: base
bw6agent:
 build: bw6
 links:
  - "ambassador:tea"
 ports:
  - "9091:9091"
  - "5050:5050"
  - "9090:9090"
  - "8079:8079"
 hostname: bw6agent
tea:
 build: tea
 links:
  - "ambassador:bw6agent"
 ports:
  - "8777:8777"
 hostname: tea
ambassador:
 image: cpuguy83/docker-grand-ambassador
 volumes:
  - "./data/docker.sock:/var/run/docker.sock"
 command: "-name tibcobw6_bw6agent_1 -name tibcobw6_tea_1"

**Comment by christianbundy** [comment]
@alexandrev You can use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) with `yaml` [syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) to format your code.

```yaml
centosjava:
  build: base
bw6agent:
  build: bw6
  links:
    - "ambassador:tea"
  ports:
    - "9091:9091"
    - "5050:5050"
    - "9090:9090"
    - "8079:8079"
  hostname: bw6agent
tea:
  build: tea
  links:
    - "ambassador:bw6agent"
  ports:
    - "8777:8777"
  hostname: tea
ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "./data/docker.sock:/var/run/docker.sock"
  command: "-name tibcobw6_bw6agent_1 -name tibcobw6_tea_1"
```

**Comment by alexandrev** [comment]
Thanks a lot @christianbundy and sorry for don't do it this way at first.

**Comment by msamblanet** [comment]
I am seeing a similar issue on a ```docker-compose up -d```

```yaml
connect:
  image: anvilresearch/connect:0.1.55
  links:
    - redis:redis
  volumes:
    - ./connect/config:/opt/connect/config:ro
    - ./connect/email:/opt/connect/email:ro
    - ./connect/protocols:/opt/connect/protocols:ro
    - ./connect/providers:/opt/connect/providers:ro
    - ./connect/public:/opt/connect/public:ro
    - ./connect/views:/opt/connect/views:ro
  restart: always

nginx:
  #build: nginx
  image: anvilresearch/nginx
  links:
    - connect:connect
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./nginx/certs:/etc/nginx/certs:ro
    - ./nginx/logs:/var/log/nginx
  ports:
    - "80:80"
    - "443:443"
  restart: always

redis:
  image: anvilresearch/redis
  volumes:
    - ./redis/data:/data
  restart: always
```

Resulting error for me:
```
compose.service.ConfigError: Volume c:\Users\msamblanet\Documents\anvil\connect\config:/opt/connect/config:ro has incorrect format, should be external:internal[:mode]
```

I specifically installed using: ```pip install --upgrade git+https://github.com/aanand/fig.git@fb304981536722ef42c9688b0688d4be048ccfd1```

That commit is (as of right now) the last commit on #1957
