### ISSUE TITLE
question: container writes files that appear on host as owned by root

### ISSUE THREAD

**Issue by rosskevin** [docker/compose#2060]
I'm looking for some pointers/docs/references to understand a bit more about how to setup docker-compose so that the container doesn't write files on the host owned by root.

Dockerfile
```
FROM atlashealth/ruby:2.2.2
...
COPY . /project
WORKDIR /project
```

My compose container runs a rails test suite, which writes files to the `target` directory.  On the ubuntu host, these appear as owned by `root`, though the container was executed as a non-privileged `apps` user:
 ```
# On the host
$ ls -la target/test-reports/
total 8
drwxr-xr-x 2 root root 4096 Sep 15 17:44 .
drwxr-xr-x 3 root root 4096 Sep 15 17:44 ..
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec2.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec3.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec4.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec5.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec6.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec7.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec8.xml
-rw-r--r-- 1 root root    0 Sep 15 17:44 rspec.xml
```

Everything within the mounted dir and above are owned by `apps`:

```
drwxr-xr-x 17 apps apps  4096 Sep 16 06:00 .
drwxr-xr-x  9 apps apps  4096 Aug 24 15:24 ..
drwxr-xr-x 16 apps apps  4096 Aug 27 06:00 app
drwxr-xr-x  5 apps apps  4096 Sep 12 06:00 config
drwxr-xr-x  6 apps apps  4096 Sep  9 20:14 db
drwxr-xr-x  3 root root  4096 Sep 15 17:44 target
```

Since I am running as the host user `apps`, I wouldn't expect files to materialize as `root`.  What do I need to read to get a better understanding?

**Comment by rosskevin** [comment]
Perhaps even more confusing, how is the container writing on the host filesystem when I have used `COPY`?  I expected to have to extract the contents of `target` from the container, and was surprised to see them on the host system already...

**Comment by ljrittle** [comment]
Please report some details from your docker-compose.yml ?  Can you give the
exact clause you used to start the service?  For example if used `volumes`
to over-mount /project that could explain what you are seeing.

**Comment by rosskevin** [comment]
No volumes used...ugh...yes there is.

I can't believe I missed that.  Must have been left over from my learning process.

```yaml
---
web:
  build: "."
  working_dir: "/project/spec/dummy"
  ports:
  - 3000:3000
  volumes:
  - ".:/project"
  links:
  - db
  - elasticsearch
  volumes_from:
  - gems-2.2.2
  environment:
  - GEM_HOME=/gems/2.2.2
  - RAILS_ENV=test
  command: >
    bash -c "
    echo 'Bundling gems' && bundle install --jobs 4 --retry 3
    && echo 'Clearing logs and tmp dirs' && bundle exec rake log:clear tmp:clear
    && echo 'Check and wait for database connection' && bundle exec docker-rails-db-check
    && echo 'DB rebuild' && bundle exec rake db:rebuild_test[true,8] "
db:
  image: library/mysql:5.7.6
  ports:
  - 3306:3306
  environment:
  - MYSQL_ALLOW_EMPTY_PASSWORD=true
elasticsearch:
  image: library/elasticsearch:1.7
  ports:
  - 9200:9200
```

That explains why files are written to the host.  This much makes sense.  Now I need to figure out how to either a) get permissions right, or b) I'll remove the shared volume and copy out the contents.
