### ISSUE TITLE
Global env variables

### ISSUE THREAD

**Issue by analytically** [docker/compose#210]
I'd be great to be able to declare 'global' env variables, that are set for all containers.

**Comment by shin-** [comment]
@dnephin @aanand bump - with the introduction of the new format, is this something we're still considering?

**Comment by dnephin** [comment]
Now that we support environment variable interpolation these variables can be provided outside of the compose file. There's still an open issue about providing defaults, or reading values from a file, which I think are more appropriate now, so we can close this I think.

env_file and extends can also be used to solve this problem.

**Comment by sw-carlin** [comment]
@dnephin Even with the interpolation we have to list all the environment variables that we want to pull in, for each service that needs them. That can lead to a lot of repetition in the docker-compose.yml.

**Comment by jpic** [comment]
@sw-carlin agreed

**Comment by mcobzarenco** [comment]
Is there a workaround for this or does one have to specify the variable individually for all containers?

**Comment by EatPrilosec** [comment]
> Is there a workaround for this or does one have to specify the variable individually for all containers?

as of 2024, top level elements that start with `x-` seem to be ignored, so this is what i do:

Maps have the advantage, and if you mix keys and maps, you need a(n array) key anchor and a map anchor (anchor = yaml global var.)




```
Version: "3.6"

x-userpid: 
  Map:  &userpidMap    ### notice anchor placement
    PUID: 1000
    PGID: 1000
  Key:
    - &PUID "PUID=1000"
    - &PGID PGID=1000

x-tz:
  Map:
    TZ: &TZM "America/New_York"
  Key: 
    - &TZK "TZ=America/New_York" 


services:
  MapExample:
    environment:
      TZ: *TZM
      <<: *userpidMap ### double LT sign merges yaml maps
    
  KeyExample:
    environment:
      - *TZK
      - *PUID
      - *PGID
 ```
