### ISSUE TITLE
Add support for --build-args

### ISSUE THREAD

**Issue by kismet010** [docker/compose#2111]
As this docker/docker#15182 functionality has been merged, it would be great to manage with Compose

I.e.:

Dockerfile with default variables
```
ARG vhost=default.com
RUN echo $vhost > ...
```

Overriding through docker-composer.yml
```
web:
  build: ...
  arguments:
    - vhost: dev.com
```

Or an hierarchy of extended environments
```
production:
  extends: web
  arguments:
    - vhost: my-final-domain.com
```

**Comment by dnephin** [comment]
I've been wanting to make a change to the build config, something like this:

```yaml

web:
  build:
    context: .
    dockerfile: dockerfiles/path/Dockerfile
    arguments:
      arg1: ...
```

**Comment by dnephin** [comment]
I created a proposal for this configuration change at #2163

**Comment by smboykin** [comment]
+1 on this feature request

**Comment by snelis** [comment]
+1 on passing environment variables onto the build step via compose

**Comment by lsborg** [comment]
+1

**Comment by Silex** [comment]
+1

**Comment by marcellodesales** [comment]
I'm stuck at Compose right now... :( Please please add this support...

I can sucessfully build with the the --build-arg because I need the HTTP_PROXY on my build servers... :(

```sh
[root@pppdc9prda2x npmo-docker-compose]# docker build --build-arg HTTP_PROXY=$HTTP_PROXY -t configure -f ./configure.Dockerfile .
Sending build context to Docker daemon 141.8 kB
Step 1 : FROM node:4-onbuild
# Executing 3 build triggers...
Step 1 : COPY package.json /usr/src/app/
 ---> Using cache
Step 1 : RUN npm install
 ---> Using cache
Step 1 : COPY . /usr/src/app
 ---> 52f129b79095
Removing intermediate container 00cb3b4651d4
Step 2 : CMD npm run configure
 ---> Running in 7d0642695c58
 ---> db140f15fe39
Removing intermediate container 7d0642695c58
Successfully built db140f15fe39
```

Build from compose
----

I still get a build stuck trying to connect to resources... I would propose:

```
  build_args:
    - HTTP_PROXY=$HTTP_PROXY
```

```yml
licenseData:
  image: busybox
  volumes:
    - .license.json:/usr/src/app/.license.json

configure:
  build: .
  dockerfile: configure.Dockerfile
  build_args:
    - HTTP_PROXY=$HTTP_PROXY
  volumes_from:
    - "licenseData"
  environment:
    - HTTP_PROXY=$HTTP_PROXY
```

The build just hangs...

```sh
[root@pppdc9prda2x npmo-docker-compose]# docker-compose -f configure.yml up
Starting npmodockercompose_licenseData_1
Building configure
Step 1 : FROM node:4-onbuild
# Executing 3 build triggers...
Step 1 : COPY package.json /usr/src/app/
 ---> Using cache
Step 1 : RUN npm install
 ---> Running in ba76ce5f09f6
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v4.2.2
npm WARN package.json npmo-docker@1.0.0 No repository field.
npm WARN package.json npmo-docker@1.0.0 No README data
npm WARN package.json npmo-docker@1.0.0 No bin file found at ./bin/npme-docker-compose.js
npm info preinstall npmo-docker@1.0.0
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/chalk
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/inquirer
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/lodash
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/mustache
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/request
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/yargs
npm info attempt registry request try #1 at 9:59:27 PM
npm http request GET https://registry.npmjs.org/standard
```
