### ISSUE TITLE
"variable is not set. Substituting a blank string." being shown when env variables from links used in directives

### ISSUE THREAD

**Issue by shrikrishnaholla** [docker/compose#2123]
I'm working with master (which is currently at dabf1e8657674014a5bc89f99edbf2fe0629bb71), and while building or starting, I'm getting the above warning, and those commands won't work

Ex: I am using a service

```yaml
rcli:
  image: redis:latest
  links:
    - redis
  command: >
     sh -c 'redis-cli -h "$REDIS_PORT_6379_TCP_ADDR" -p "$REDIS_PORT_6379_TCP_PORT"'
```

Here, since the env variable `REDIS_PORT_6379_TCP_ADDR` is obtained because of linking, and it's non-existent when building, or before starting the `redis` service, I can't use this service. It substitutes the value with an empty string.

```
The REDIS_PORT_6379_TCP_ADDR variable is not set. Substituting a blank string.
The REDIS_PORT_6379_TCP_PORT variable is not set. Substituting a blank string.
```

**Comment by shrikrishnaholla** [comment]
This is also reproducible if the `CMD` directive in the `Dockerfile` uses any env variable

```
CMD fluentd --gemfile /etc/fluent/Gemfile -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

Seems like command string is being evaluated or something by `compose` or `docker-py`, and that is being done prematurely

**Comment by villlem** [comment]
This is due https://github.com/docker/compose/issues/1377. For your case double `$`
On the other note
`$REDIS_PORT_6379_TCP_ADDR` - using those env is deprecated.

**Comment by dnephin** [comment]
I think maybe we should document this error explicitly, I suspect a few more people will hit this on release.

It should only apply to variables in the config though, not the `Dockerfile`.

**Comment by shrikrishnaholla** [comment]
@dnephin My bad. It's not hitting Dockerfile. I had replicated the command in the `command` section in `docker-compose.yml`, which was causing the error

**Comment by shrikrishnaholla** [comment]
@villlem 
> `$REDIS_PORT_6379_TCP_ADDR` - using those env is deprecated.

What is the recommended way? I'm using whatever I read in the [docs](https://docs.docker.com/userguide/dockerlinks/#environment-variables)

**Comment by villlem** [comment]
@shrikrishnaholla: Docker populate /etc/host inside container with names from link and also do not change ports. But documentation is confusing. 

See https://docs.docker.com/compose/env/ for details.

I would just remove port and replace address with name from `/etc/hosts`
```
rcli:
  image: redis:latest
  links:
    - redis
  command: >
     sh -c 'redis-cli -h redis '
```
This should also works. I'm not on computer with docker right now
```
rcli:
  image: redis:latest
  links:
    - redis
  command: redis-cli -h redis
```
