### ISSUE TITLE
Unknown device

### ISSUE THREAD

**Issue by HonzaMac** [docker/compose#2190]
What can I do with this?

for command: `docker-compose up` `docker-compose ps` and etc.
I got:
`Unknown device fc48c30df78ed5876fbfa9bfb5d0193ec883ab1082762a0cf3d077b29716d40f`

docker-compose version: 1.4.2
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

**Comment by christianbundy** [comment]
What operating system are you using? Are you using a VM?

**Comment by dnephin** [comment]
Please include your `docker-compose.yml` to help debug this issue.

**Comment by HonzaMac** [comment]
Operating system is EC2 on amazon.
`Linux ip-172-31-27-72 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

The change was, that I upgraded kernel and after restart it stopped work.
Even if I simplify docker-composer to just one recor (with redis as dependency) I got same error.

So there should be way, how to upgrade to new kernel... ?

```
gateway:
  extends:
    file: ../svc-podracer/docker-compose.yml
    service: service
  env_file: .env
  links:
   - redis:redis

connection:
  extends:
    file: connection/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis


jpsearch:
  image: tutum.co/leleto/jp-bin:master
  env_file: .env
  command: search -g /etc/jp.d/tutum.json
#  command: config
  restart: always
  links:
    - redis:redis

jpdata:
  image: tutum.co/leleto/jp-bin:master
  env_file: .env
  command: data -g /etc/jp.d/tutum.json
  #command: config
  restart: always
  links:
    - redis:redis

mail:
  extends:
    file: mail/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

marketplace:
  extends:
    file: marketplace/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

payment:
  extends:
    file: payment/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

price:
  extends:
    file: price/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

traffic:
  extends:
    file: traffic/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

user:
  extends:
    file: user/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

reservation:
  extends:
    file: reservation/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

render:
  extends:
    file: render/docker-compose.yml
    service: service
  env_file: .env
  links:
    - redis:redis

redis:
  image: redis
  ports:
     - "6379:6379"
```
