### ISSUE TITLE
Can't limit memory in docker-compose

### ISSUE THREAD

**Issue by terehru** [docker/compose#2252]
My config:

```
resize:
  mem_limit: 4096m
  extends:
    file: compose-common.yml
    service: thumbor

tplate:
  extends:
    file: compose-common.yml
    service: tplate
  links:
    - resize

haproxy:
  mem_limit: 2048m
  image: tutum/haproxy
  environment:
    BALANCE: "leastconn"
  links:
    - tplate
  ports:
    - 8080:80
    - 1936:1936
```

Starting:
```
docker-compose -f compose-prod.yml up -d
```

See stats:
```
docker stats $(docker ps|grep -v "NAMES"|awk '{ print $NF }'|tr "\n" " ")
```

```
CONTAINER              CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
wwwtplate_haproxy_1    0.31%               0 B/67.59 GB        0.00%               6.538 MB/6.562 MB
wwwtplate_resize_1     101.24%             0 B/67.59 GB        0.00%               2.033 MB/2.075 MB
wwwtplate_tplate_1     0.00%               0 B/67.59 GB        0.00%               2.347 MB/5.71 MB
wwwtplate_tplate_10    0.00%               0 B/67.59 GB        0.00%               223.6 kB/880.5 kB
wwwtplate_tplate_11    0.00%               0 B/67.59 GB        0.00%               165.7 kB/530.9 kB
wwwtplate_tplate_12    0.00%               0 B/67.59 GB        0.00%               152 kB/448.2 kB
wwwtplate_tplate_13    0.00%               0 B/67.59 GB        0.00%               160.6 kB/529.5 kB
wwwtplate_tplate_14    0.00%               0 B/67.59 GB        0.00%               155.2 kB/526.7 kB
wwwtplate_tplate_15    0.00%               0 B/67.59 GB        0.00%               152.5 kB/518.8 kB
wwwtplate_tplate_16    0.00%               0 B/67.59 GB        0.00%               202.3 kB/645.2 kB
wwwtplate_tplate_2     0.00%               0 B/67.59 GB        0.00%               137.4 kB/279.7 kB
wwwtplate_tplate_3     0.00%               0 B/67.59 GB        0.00%               139.9 kB/279 kB
wwwtplate_tplate_4     0.00%               0 B/67.59 GB        0.00%               134.7 kB/280 kB
wwwtplate_tplate_5     0.00%               0 B/67.59 GB        0.00%               136 kB/281.5 kB
wwwtplate_tplate_6     81.54%              0 B/67.59 GB        0.00%               383 kB/12.22 kB
wwwtplate_tplate_7     64.61%              0 B/67.59 GB        0.00%               137.7 kB/279.6 kB
wwwtplate_tplate_8     66.33%              0 B/67.59 GB        0.00%               139.5 kB/279.9 kB
wwwtplate_tplate_9     38.14%              0 B/67.59 GB        0.00%               145.4 kB/13.76 kB
```

So here you see empty MEM USAGE and no limit.
docker-compose version: 1.4.0
