### ISSUE TITLE
"[8] System error: not a directory" when trying to mount file 

### ISSUE THREAD

**Issue by divyakumarjain** [docker/compose#2268]
I am trying to mount a file into a container but i am getting error ""

Following is my docker-compose.yml

```yml
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
```

As per following discussion https://github.com/docker/docker/issues/13276 have moved everything in c:/Users/${userid} folder. Also to share i am using rancheros instead of standard boot2docker.

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64
```
