### ISSUE TITLE
Add support for setting container hostname

### ISSUE THREAD

**Issue by sheax0r** [docker/compose#228]
I haven't found a way to use fig to specify the hostname of a Docker container. I think this would be useful to have. Configuring could be something like this:

``` yml
test:
  image: busybox
  hostname: mycomputer.somewhere.com
  run: hostname
```

Output would be something like this:

```
> fig up test
test_1 | mycomputer
fig_test_1 exited with code 0
```
