### ISSUE TITLE
Container volume masks host volume in the compose file

### ISSUE THREAD

**Issue by mekanixdk** [docker/compose#2308]
I have a little snippet in `docker-compose.yml` like:

```
volumes:
  - ${HOST_PATH}:/container/path
```
If I change the value of `HOST_PATH` any subsequent `up` or `build`, the container will still mount the volume with the *old* value of `HOST_PATH`.

Is this because `volumes` is not a run time option like `docker -v` or is this a bug?

**Comment by aramalipoor** [comment]
You're right it's only used when creating the container, I think using `up --force-recreate` flag will create a new container with new volumes.

**Comment by dnephin** [comment]
I can't reproduce this issue with master .What version of docker-compose are you running?

Here's what I ran:

```yaml
web:                                                                                                                                                                                                                                                                              
  image: 'alpine:edge'                                                                                                                                                                                                                                                            
  volumes:                                                                                                                                                                                                                                                                        
    - '${HOST_PATH}:/contents'                                                                                                                                                                                                                                                    
  command: 'ls /contents'   
```

```
HOST_PATH=`pwd`/examples docker-compose up
# Prints the list of files in examples

HOST_PATH=. docker-compose up
# Prints a different list of files in the current directory
```

**Comment by mekanixdk** [comment]
I was using 1.5.0 RC1 and RC2. I can see that 1.5.0 have just been released. I will try that with your example above.

My container looks like this:
```
mysql:
  container_name:
    dungbeetle_mysql
  image:
    mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: password
  expose:
    - "3306"
  ports:
    - "3306:3306"
  volumes:
    - ${DUNGBEETLE_MYSQL_DATA}:/var/lib/mysql
  hostname: database
```
