### ISSUE TITLE
NoCredentialProviders

### ISSUE THREAD

**Issue by deacix** [docker/compose#2329]
I get this error:
"Failed to initialize logging driver: NoCredentialProviders: no valid providers in chain"
if i try to start a stack with awslogs driver. Single docker container call like this:

docker -D run --rm -it \
  --log-driver=awslogs \
  --log-opt awslogs-region=eu-central-1 \
  --log-opt awslogs-group=docker-log \
  --log-opt awslogs-stream=hello-world hello-world

works fine.

docker-compose yml log config:

```
log_driver: "awslogs"
log_opt:
    awslogs-region: eu-central-1
    awslogs-group: docker-log
    awslogs-stream: hello-world
```
