### ISSUE TITLE
docker-compose up: ERROR: Cannot start container: failed to update store for object type *libnetwork.endpointCnt

### ISSUE THREAD

**Issue by jeron-diovis** [docker/compose#2356]
Mac OS X 10.10.5

```
$ docker-compose up
Pulling redis (redis:2.8)...
2.8: Pulling from library/redis

1d53ee5b1800: Pull complete
74872ba2a3b0: Pull complete
b73eb536e646: Pull complete
733ba5d512e3: Pull complete
00b5a1f6aeae: Pull complete
65b0d3a3cd30: Pull complete
a46a54050037: Pull complete
344888176fa7: Pull complete
2380915c0807: Pull complete
f454f845714a: Pull complete
b04e3558e7f0: Pull complete
e25f48bc0233: Pull complete
acaeeb5be8f7: Pull complete
bdccb64d4c06: Pull complete
96288bc75a66: Pull complete
47130e6037f2: Pull complete
ca6553f7ffad: Pull complete
Digest: sha256:2e89addcd3b13e473e4302c202c0171f8e83f4d31af3bbcd8d6c3f68a31fde7c
Status: Downloaded newer image for redis:2.8
Creating rejum_redis_1
ERROR: Cannot start container 6f546315c9ad94337c201b95b22668549d27423b850c366a30de66c46a9c7372: 
failed to update store for object type *libnetwork.endpointCnt: Key not found in store
```

Didn't find any info about this error, can you explain what this means and what to do?

Do I need to show my `docker-compose` file?

**Comment by dnephin** [comment]
It would be good to share your `docker-compose.yml` to help debug this.

**Comment by jeron-diovis** [comment]
Here it is:
```yml
data:
    image: mediasapiens/python2-jum:1.8
    volumes:
        - .:/web
        - uploads:/uploads
        - static:/static
    links:
        - db:db
    environment:
        - DJANGO_SETTINGS_MODULE=settings.docker
    command: /bin/bash -c 'cd /web && pip install -r requirements.txt && fab run_data'

ask:
    image: mediasapiens/python2-jum:1.8
    volumes_from:
        - data
    links:
        - db:db
        - smtp:smtp
        - redis:redis
    ports:
        - "9900:9000"
    expose:
        - "9000"
    environment:
        - PY_AUTORELOAD=true
        - VENDOR_SLUG=ask
        - DJANGO_SETTINGS_MODULE=settings.docker
    command: /bin/bash -c "cd /web && pip install -r requirements.txt && fab runit"


indola:
    image: mediasapiens/python2-jum:1.8
    volumes_from:
        - ask
    links:
        - db:db
        - smtp:smtp
        - redis:redis
    ports:
        - "9901:9000"
    expose:
        - "9000"
    environment:
        - PY_AUTORELOAD=true
        - VENDOR_SLUG=indola
        - DJANGO_SETTINGS_MODULE=settings.docker
    command: /bin/bash -c "cd /web && pip install -r requirements.txt && fab runit"


celerybeat:
    image: mediasapiens/python2-jum:1.8
    links:
        - redis:redis
        - smtp:smtp
        - db:db
    volumes_from:
        - ask
    environment:
        - DJANGO_SETTINGS_MODULE=settings.docker
    command: /bin/bash -c 'cd /web && pip install -r requirements.txt && fab celerybeat'


celery:
    image: mediasapiens/python2-jum:1.8
    links:
        - redis:redis
        - smtp:smtp
        - db:db
    volumes_from:
        - ask
    environment:
        - DJANGO_SETTINGS_MODULE=settings.docker
        - C_FORCE_ROOT=1
    command: /bin/bash -c 'C_FORCE_ROOT=1 && cd /web && pip install -r requirements.txt && fab celeryd'


redis:
    image: redis:2.8
    expose:
        - "6379"


smtp:
    image: catatnight/postfix
    environment:
        - maildomain=localhost
        - smtp_user=user:pwd


db:
    image:
        mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=test37
    expose:
        - 3306


client:
    image: mediasapiens/npm
    volumes:
        - client:/client
        - static:/static
    command: /bin/bash -c "cd /client && npm install && npm start"
```
