### ISSUE TITLE
Need support for dashes in environment variable names

### ISSUE THREAD

**Issue by bmoo** [docker/compose#2370]
The Java spring-boot library accepts core config through a standardized set of environment variables. Spring boot provides a mechanism to convert their properties to environment, [see here](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html#howto-change-the-location-of-external-properties). Some of these standard spring properties have dashes in them.

These properties worked under previous versions of compose but are no longer allowed in 1.5. Running a compose file like this

```
app:
  build: .
  expose:
   - "80"
  links:
    - db:db
  environment:
    - SERVER_PORT=80
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
    - SPRING_DATASOURCE_USERNAME=username
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
    - SPRING_JPA_HIBERNATE_DDL-AUTO=none
```

Now fails with the error 

`Service 'app' configuration key 'environment' contains unsupported option: 'SPRING_JPA_HIBERNATE_DDL-AUTO'`
