### ISSUE TITLE
Fig using /bin/bash as a command

### ISSUE THREAD

**Issue by jayd3e** [docker/compose#238]
I have an app that could potentially have a few different commands run within it, and all of them are required for development purposes.  Is there a way I can have fig just launch to a bash process?  Something like:

``` yaml
web:
  build: .
  command: /bin/bash
  links:
   - db
   - redis
db:
  image: orchardup/postgresql
redis:
  image: orchardup/redis
```
