### ISSUE TITLE
Improve variable interpolation, required flag and default value.

### ISSUE THREAD

**Issue by aramalipoor** [docker/compose#2441]
As first proposed in #1377 I think it would be very useful to have a way to set a variable as required, and  also set some default value.

```yaml
web:
   image: org/app:${VERSION?} # Required
```
Or
```yaml
web:
   image: org/app:${VERSION:latest} # Default Value
```

**Comment by majidgolshadi** [comment]
:+1:

**Comment by dustinblackman** [comment]
:+1:

**Comment by armab** [comment]
:+1:

**Comment by valeriangalliat** [comment]
:+1:

**Comment by mseashor** [comment]
:+1:

**Comment by shane-axiom** [comment]
+1, defaults for environment variables would be great. Simple syntax this would be great:

    mycontainer:
      image: ubuntu:latest
      ports:
        - ${THEPORT:8080}:8080

**Comment by bennycornelissen** [comment]
:+1:

**Comment by plouc** [comment]
I'm working on a project where people have heterogeneous env, I'm working on OSX and some are using Ubuntu, when using docker-machine with virtualbox provider, I have to put the full path to make Volume works:

```yaml
myservice:
  volumes:
    - ${HOST_VOLUME_PATH}/src:/src
```

The problem is now people who don't use virtualbox have to define the value, it should be great if we could  have a default value:

```yaml
myservice:
  volumes:
    - ${HOST_VOLUME_PATH:.}/src:/src
```

In other words :+1:

**Comment by obazoud** [comment]
:+1:

**Comment by jlrigau** [comment]
:+1:

**Comment by scasagrande-d2l** [comment]
+1

**Comment by leogamas** [comment]
:+1:

**Comment by roll** [comment]
:+1:

**Comment by asilluron** [comment]
:+1:

**Comment by digitalLumberjack** [comment]
:+1:

**Comment by hadim** [comment]
This feature is a must have. Any devs from the docker-compsose team working on it ? If not I could propose a PR.

**Comment by dnephin** [comment]
While having defaults would be really nice, we haven't decided on any implementations yet.

I (personally) think it's more likely we go with something like #2636 for default values. It supports more use-cases, and doesn't require us to invent new syntax for defaults.

**Comment by marcellodesales** [comment]
I'd like to see the same implementation as https://docs.docker.com/engine/reference/builder/#environment-replacement Right now, I'd like the ability to switch from 2 different implementations for the log driver.

Given the following Base implementation:

```yml
intuitive-syslog:
  log_driver: "syslog"
  labels:
    - net.c.d.datacenter: ${DATA_CENTER}
    - net.c.d.env: ${NPMO_ENV}
    - net.c.d.hostname: ${HOSTNAME}
    - net.c.d.role: ${NPMO_ROLE}

intuitive-json:
  log_driver: "json"
  labels:
    - net.c.d.datacenter: ${DATA_CENTER}
    - net.c.d.env: ${NPMO_ENV}
    - net.c.d.hostname: ${HOSTNAME}
    - net.c.d.role: ${NPMO_ROLE}
```

I'd like to run the syslog driver by default and select the regular logs while debugging.

```yml
mycouch:
  extends:
    file: base.yml
    service: intuitive-${LOG_DRIVER:-syslog}
  build: roles/couchdb
  restart: always
  ports:
    - "5984"
  log_opt:
    syslog-tag: "mycouch"

myredis:
  extends:
    file: base
    service: intuitive-${LOG_DRIVER:-syslog}
  image: redis
  restart: always
  expose:
    - "6379"
  log_opt:
    syslog-tag: "myredis"
```

I'm getting the following error:

```
docker-compose -f services/new1.yml ps
ERROR: Invalid interpolation format for "extends" option in service "myredis": "intuitive-${LOG_DRIVER:-syslog}"
```
