### ISSUE TITLE
File sync issues with `docker/compose` image on Virtualbox/boot2docker

### ISSUE THREAD

**Issue by simonvanderveldt** [docker/compose#2442]
There are known issues with Alpine based images when used together with Virtualbox Shared folders which have shared folders/files not or only partially updating inside the container.

See the experiences @dduportal had with his docker-compose image in dduportal-dockerfiles/docker-compose#7 and dduportal-dockerfiles/docker-compose#7

I ran into the same issues again when using the `docker/compose` image.
Switched to @dduportal's [`dduportal/docker-compose`](https://hub.docker.com/r/dduportal/docker-compose/) image solved these issues.
Can we work together on this and create an official fully working image?

FYI I'm not sure where the actual issue originates, it's somehow a combination of Virtualbox shared folders with an Alpine based image. I wouldn't be surprised if Virtualbox is to blame, but since switching to another base OS like Debian solves the issues I think that would be the smart thing to do right now.

**Comment by dduportal** [comment]
For info, i'm currently trying to rollback to go from debian base image to alpine one.

The old behavior are not here (you can tests from here : https://github.com/dduportal-dockerfiles/docker-compose/tree/alpine-base ) but i'm running in strange new one when doing my inception tests (bats container that test docker-compose images).

@simonvanderveldt : can you provide here more detailed informations on the problem you face with the current compose official image ?

**Comment by dnephin** [comment]
It seems very strange that this would be related to alpine linux.  The original bug is definitely in VirtualBox.

**Comment by simonvanderveldt** [comment]
First of all, sorry, bit of a long comment below, it's kinda difficult to find the exact cause so trying to be as thorough and complete as possible.

@dnephin Agreed, it shouldn't matter what runs inside the container but it appears to be the case that it does. Very strange.

I use the `run.sh` script from this repo, only changed the entrypoint to `sh` and add a `set -x` to display the actual arguments for this issue.
This is te `docker-compose.yml` I start with:
```
consul:
  image: gliderlabs/consul-server:0.5
  command: -bootstrap -config-dir /etc/consul.d -data-dir /data/consul -ui-dir /ui -client 0.0.0.0
  volumes:
   - ./consul.json:/etc/consul.d/services.json
  ports:
   - "8300:8300"
   - "8301:8301"
   - "8301:8301/udp"
   - "8302:8302"
   - "8302:8302/udp"
   - "8400:8400"
   - "8500:8500"
   - "8600:8600"
   - "8600:8600/udp"
   - "53:8600"
   - "53:8600/udp"
postgres:
  image: postgres:9.4
  links:
   - consul
```
Now start the compose container and `cat docker-compose.yml`
```
dev ❯ compose                                                                                                                                                                                                                               
+ VERSION=1.5.0
+ IMAGE=docker/compose:1.5.0
+ '[' -z tcp://192.168.99.102:2376 ']'
+ '[' -S tcp://192.168.99.102:2376 ']'
+ DOCKER_ADDR='-e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH'
++ pwd
++ pwd
+ VOLUMES='-v /Users/simon/dev:/Users/simon/dev'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n /Users/simon ']'
+ VOLUMES='-v /Users/simon/dev:/Users/simon/dev -v /Users/simon:/Users/simon'
++ pwd
+ exec docker run --rm -ti -e DOCKER_HOST -e DOCKER_TLS_VERIFY -e DOCKER_CERT_PATH -v /Users/simon/dev:/Users/simon/dev -v /Users/simon:/Users/simon -w /Users/simon/dev --entrypoint sh docker/compose:1.5.0

/Users/simon/dev # cat docker-compose.yml
consul:
  image: gliderlabs/consul-server:0.5
  command: -bootstrap -config-dir /etc/consul.d -data-dir /data/consul -ui-dir /ui -client 0.0.0.0
  volumes:
   - ./consul.json:/etc/consul.d/services.json
  ports:
   - "8300:8300"
   - "8301:8301"
   - "8301:8301/udp"
   - "8302:8302"
   - "8302:8302/udp"
   - "8400:8400"
   - "8500:8500"
   - "8600:8600"
   - "8600:8600/udp"
   - "53:8600"
   - "53:8600/udp"
postgres:
  image: postgres:9.4
```
Now if I remove the `postgres` service and the `ports` and `volumes` section from the `consul` service it works as it should.
But if I rename `postgres` to `somethingelse` the changes won't propagate inside the compose container. There it still shows `postgres`.
If I remove the `ports` from the `consul` service `docker-compose.yml` inside the container still contains a part of them:
```
/Users/simon/dev # cat docker-compose.yml
consul:
  image: gliderlabs/consul-server:0.5
  command: -bootstrap -config-dir /etc/consul.d -data-dir /data/consul -ui-dir /ui -client 0.0.0.0
  volumes:
   - ./consul.json:/etc/consul.d/services.json
  ports:
   - "8300:8300"
   - "8301/Users/simon/dev #
```
(note the 2nd half of the `"8301:8301"` port mapping missing)

Now if I add some rows to the `somethingelse` service the `ports` section from the `consul` service will grow with the same amount of rows inside the container
```
consul:
  image: gliderlabs/consul-server:0.5
  command: -bootstrap -config-dir /etc/consul.d -data-dir /data/consul -ui-dir /ui -client 0.0.0.0
  volumes:
   - ./consul.json:/etc/consul.d/services.json
somethingelse:
  image: postgres:9.4
  links:
   - consul
```
And inside the container
```
/Users/simon/dev # cat docker-compose.yml
consul:
  image: gliderlabs/consul-server:0.5
  command: -bootstrap -config-dir /etc/consul.d -data-dir /data/consul -ui-dir /ui -client 0.0.0.0
  volumes:
   - ./consul.json:/etc/consul.d/services.json
  ports:
   - "8300:8300"
   - "8301:8301"
   - "8301:830/Users/simon/dev #
```

Note that I tried this with Virtualbox's `Use host I/O cache` option `on` (default) and `off`, which didn't make a difference.
Also note the `run.sh` script does a nested bind mount in this case since `$PWD` is below `$HOME`. I tried only bind mounting `$HOME` but that doesn't make a difference.

If I switch to @dduportal's debian based image I have none of these issues.
@dduportal just tried your `alpine-base` and it has the same issue.
