### ISSUE TITLE
Using gelf log driver and lose the ability to `fig run <container> bash`

### ISSUE THREAD

**Issue by glenbot** [docker/compose#2448]
Im using `gelf` logging in my docker-compose file and I lose the ability to use `fig run <container> bash` because it gives the error "Error attaching: configured logging reader does not support reading". An example config is:

```
my_container:
  image: link-to-image
  log_driver: "gelf"
  log_opt:
    gelf-address: udp://0.0.0.0:12201
    gelf-tag: my_container
```

I understand that I lose the ability to use `docker-compose logs` or `docker-compose logs my_container` but I would expect `docker-compose run my_container bash` to let me into the container as I am overriding the CMD line manually.

```
docker-compose version: 1.5.1
Docker version 1.9.0, build 76d6bc9
```

**Comment by dnephin** [comment]
Please include some sample output as well. It should help identify where the error is coming from.

Does a `docker run` with the same logging args work?

**Comment by glenbot** [comment]
Here is the last few lines of logging when I run `fig --verbose run <name> bash`:

```
compose.cli.verbose_proxy.proxy_callable: docker attach_socket <- (u'003c3c488855b23b7446964c7c8e0b1a182f8faceb2fd754891138b2f31e1c36', {'stream': 1, 'stderr': 1, 'logs': 1})
compose.cli.verbose_proxy.proxy_callable: docker attach_socket -> <socket object, fd=6, family=1, type=1, protocol=0>
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'003c3c488855b23b7446964c7c8e0b1a182f8faceb2fd754891138b2f31e1c36')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [],
 u'Config': {u'AttachStderr': True,
             u'AttachStdin': True,
             u'AttachStdout': True,
             u'Cmd': [u'bash'],
             u'CpuShares': 0,
             u'Cpuset': u'',
             u'Domainname': u'',
             u'Entrypoint': None,
...
compose.cli.verbose_proxy.proxy_callable: docker start <- (u'003c3c488855b23b7446964c7c8e0b1a182f8faceb2fd754891138b2f31e1c36')
compose.cli.verbose_proxy.proxy_callable: docker start -> None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'003c3c488855b23b7446964c7c8e0b1a182f8faceb2fd754891138b2f31e1c36')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [],
 u'Config': {u'AttachStderr': True,
             u'AttachStdin': True,
             u'AttachStdout': True,
             u'Cmd': [u'bash'],
             u'CpuShares': 0,
             u'Cpuset': u'',
             u'Domainname': u'',
             u'Entrypoint': None,
...
compose.cli.verbose_proxy.proxy_callable: docker resize <- (u'003c3c488855b23b7446964c7c8e0b1a182f8faceb2fd754891138b2f31e1c36', width=169, height=37)
                                                                                                                                                      compose.cli.verbose_proxy.proxy_callable: docker resize -> None
                                            Error attaching: configured logging reader does not support reading
                                                                                                               Error attaching: configured logging reader does not support reading
         compose.cli.verbose_proxy.proxy_callable: docker wait <- (u'003c3c488855b23b7446964c7c8e0b1a182f8faceb2fd754891138b2f31e1c36')
```

And if I run `docker run -it --log-driver="gelf" --log-opt "gelf-address=udp://0.0.0.0:12201" <name> bash` it goes into the container just fine with no error.

Let me know if you need any more output.

**Comment by decisio-build** [comment]
Just bumping the issue, any thoughts on what could be causing this?

**Comment by pedros007** [comment]
I am also getting a message "Error attaching: configured logging reader does not support reading" when I run `docker-compose run web rake db:create` in a terminal.  The "Error attaching" message is the only thing printed to stderr/stdout.  I do _not_ see the message with `docker-compose up`.  I have a logstash listening on 12201 forwarding to Elasticsearch and it does include the output from `rake db:create`.

I'm using docker-1.9.0 and docker-compose 1.5.1. 

```
db:
  image: mdillon/postgis
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
    tag: postgresql
web:
  build: web/
  environment:
    RAILS_ENV: development
  links:
    - db
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
    tag: rails
```

**Comment by glenbot** [comment]
@dnephin This might make it easier to test for you. Here is my greylog config:

```
graylog:
  image: graylog2/allinone
  environment:
    GRAYLOG_PASSWORD:
    GRAYLOG_USERNAME: admin
    GRAYLOG_TIMEZONE: US/Central
    GRAYLOG_RETENTION: "--time=168 --indices=30"
    GRAYLOG_NODE_ID: staging
    GRAYLOG_SERVER_SECRET:
    ES_MEMORY: 16g
  ports:
    - "172.16.5.1:9000:9000"
    - "172.16.5.1:12201:12201"
    - "172.16.5.1:12201:12201/udp"
  volumes:
    - /data/graylog/var/opt/graylog/data:/var/opt/graylog/data
    - /data/graylog/var/log/graylog:/var/log/graylog
    - /data/graylog/opt/graylog/plugin:/opt/graylog/plugin
```
