### ISSUE TITLE
docker-compose 1.5.1 "contains an invalid type, it should be an array"

### ISSUE THREAD

**Issue by opyate** [docker/compose#2463]
Test:

```
# in terminal 1, run a service like a database
docker run --rm --name first postgres

# in terminal 2
cat <<EOF > docker-compose.yml
second:
  image: busybox
  external_links:
   - first:uno
EOF
docker-compose run --rm second /bin/sh
```

Which will give you a BusyBox shell, and `env` shows the `UNO_*` env vars.

**However**, change the YAML to the following **VALID** YAML (e.g. try [this linter](http://www.yamllint.com/) or [this one](https://github.com/nodeca/js-yaml)), and it will not work with `docker-compose 1.5.1` (via `DockerToolbox-1.9.1a.pkg`).

```
second:
  image: busybox
  external_links: {first: uno}
```

**Comment by dnephin** [comment]
It is valid yaml, but it is not a valid Compose file.  `{}` is an object, not an array. You need:

```yaml
second:
  image: busybox
  external_links: [{first: uno}]
```

**Comment by opyate** [comment]
Obvious in retrospect, thanks!

**Comment by opyate** [comment]
@bfirsh just checking if a PR introducing this feature is a good idea or not: for keys that require an array (like `external_links`), also get them to support an object.

This makes the YAML file clearer if one mostly has arrays of one item.

Before:

```
foo:
  image: busybox
  environment:
   - "PORT:9000"
  external_links:
   - "bar:quux"
```

After:

```
foo:
  image: busybox
  environment: "PORT:9000"
  external_links: "bar:quux"
```
