### ISSUE TITLE
Proposal: Specify networks in the Compose file

### ISSUE THREAD

**Issue by aanand** [docker/compose#2478]
Related issues: #2470, #2476

Users should be able to specify networks in the Compose file, other than the default network, which are created on-demand. This would be useful for specifying drivers and parameters, as well as for creating multiple networks to lock down reachability between services, e.g. for security reasons.

This necessitates new Compose file syntax in the form of a new top-level key for specifying networks, and a new service-level key for specifying multiple networks to join. I propose `networks` and `publish`:

```yaml
networks:
  front:
    driver: my-custom-driver
    options: # driver-specific options
      foo: "a"
      bar: "b"
  back:
    driver: my-custom-driver

services:
  nginx:
    image: username/nginx
    publish:
      - front

  web:
    image: username/web
    publish:
      - front
      - back

  db:
    image: username/db
    publish:
      - back
```

This creates a 2-network, 3-service app where `nginx` can talk to `web` and `web` to `db`, but `nginx` cannot talk directly to `db`.

### `networks`: mapping or list?

If networks are specified as a mapping, it works really well in the case where you're specifying a driver/options. But in the (probably common) case where you just want a network and the default driver, it'd be kind of a pain to have to specify anything more than the name. Trouble is, specifying *just* the name is kind of weird/awkward with a mapping.

Let's suppose the `back` network in the example above doesn't need to specify a driver or options:

```yaml
networks:
  front:
    driver: my-custom-driver
    options:
      foo: "a"
      bar: "b"

  back: {}

  # Or allow nulls?
  back:
```

Conversely, we could use a list instead:

```yaml
networks:
  - name: front
    driver: my-custom-driver
    options:
      foo: "a"
      bar: "b"

  - name: back

  # Or allow just a string?
  - back
```

We now need to check for duplicate names, but perhaps that's OK.

### Default network

- If the user explicitly defines networks, should we still create a default network?

- If a service specifies networks to connect to with `publish`, should it also connect to the default network?

- Could we somehow support changing the name of the default network with this syntax, as requested in #2470?

### Aliases

Networking plans to support aliases under which a container can join a network (https://github.com/docker/libnetwork/issues/737), so Compose should support those. Perhaps via colon syntax:

```yaml
web:
  publish:
    - front:web-app
    - back
```

Or we could use mapping syntax, but then we run into a similar problem with the "no alias" case as described previously with the `networks` key:

```yaml
web:
  publish:
    front: web-app
    back:
```

Arguably this isn't so bad, since we already permit something similar with entries in `environment`.

### Overriding with multiple Compose files

If `docker-compose.yml` and `docker-compose.override.yml` both specify networks, how should we handle networks that are defined in both files? Should a latterly-defined network completely replace the configuration for a previously-defined network with the same name, or should we do some level of merging of keys? If so, how deeply should we merge it - should we descend into sub-keys of `options`, for example?

**Comment by aanand** [comment]
ping @mavenugo @dave-tucker

**Comment by dnephin** [comment]
I like this, but I think there are some considerations missing:

1. (related to #2415) publish is effectively the same option as `net`. If we add the `publish` option there are going to be conflicting configurations between them. Should we maybe just use `net` for this? If we don't, how do we handle conflicting configuration?  My preference would be to just use `net`.

2. How do we address name uniqueness (to support multiple isolated environments on the same host). Right now everything is namespaced, but if we allow the addition of network names, we won't be able to run multiple copies of the environment on the same host (named volumes has the same issue).  Since network names are not unique, maybe there is a way we can get label support added to network names?  Otherwise do we need to prefix these networks with the project name (like we used to do with container names) ?

> Could we somehow support changing the name of the default network with this syntax ?

We could allow for a new key in the networks section `default: True`, which can only be set on one network. If it's set, we use that as the default network, and use the name defined. If it's not set, we continue to create a default network with default settings, even if it might happen that nothing uses it. If the default network is not configured we would have all containers join the network. If it is configured, we would only join containers where it explicitly uses the name in `publish` (or `net`).

> Overriding with multiple Compose files

I think this needs to be a merge at the name level. We'll want to be able to change network drivers based on environment (which would be done with an override file). Different network drivers have different options, and we don't want to merge unrelated options. But we also want to make sure that we don't have to re-define all the existing networks. (I think this is the first option you describe "a latterly-defined network completely replace the configuration for a previously-defined network with the same name").

**Comment by aanand** [comment]
> Should we maybe just use `net` for this? If we don't, how do we handle conflicting configuration? My preference would be to just use `net`.

I agree that ideally we should have one option cover it all. The problem is that, in this case, I don't think the Docker CLI's idioms map very well to the Compose file format.

The CLI gives you two ways to connect a container to a network: `docker run --net=foo` (for the default case where you only want one) and `docker network connect foo mycontainer` (for when you want to connect to multiple networks).

We could override `net` and let you provide multiple values, which would be a departure from the Docker CLI but not a huge one. If we add syntax for choosing an alias, though, that's a bigger departure.

Of course, the Docker CLI syntax for specifying an alias hasn't been decided yet, so perhaps we have an opportunity to design both in tandem.

(Aside: I should have suggested `connect` for the service-level key name instead of `publish`, since it maps roughly to `docker network connect`. But it'd be even better if we didn't need it at all.)

> Right now everything is namespaced, but if we allow the addition of network names, we won't be able to run multiple copies of the environment on the same host (named volumes has the same issue).

Yeah, this is annoying, but I think prefixing is the way to go. If people want networks/volumes with un-prefixed names, they should create them outside of Compose and just refer to them in the file, as they can already do.

> We could allow for a new key in the networks section...

This proposal sounds sensible, but I need to think about it more.

> I think this is the first option you describe "a latterly-defined network completely replace the configuration for a previously-defined network with the same name"

Yes, exactly. I agree it's probably the best option from a functionality standpoint, although it might surprise people that service config is merged and network (and volume?) config isn't.

**Comment by dnephin** [comment]
> I agree that ideally we should have one option cover it all.

With namespacing this gets even more complicated. If we put all the networks under `net`, then we need some way to say "this is a compose network", add the prefix, vs, this is an external network, don't add a prefix. Maybe this is an argument for keeping them separate (like `links` vs `external_link`).

> although it might surprise people that service config is merged and network (and volume?) config isn't.

I think there are other areas where we might want the same logic as we're proposing here. One area is the proposed "build section" from #2163. I think we'd want to completely replace everything under the `build` key, if it's overriden, because a change to one field basically invalidates the rest.

Another possible area is log-driver/log-options. Unfortunately we didn't set it up as a `logging:` section, with driver and options as fields, but if we had, I think we'd use the same logic (maybe we should)?

So considering we have other areas that would merge using this logic, I think we can document it, and the reasoning behind it.

**Comment by stephanbuys** [comment]
Perhaps an option to consider is foregoing the need for a `networks` and `services` section and to rather deduce the networks, based on what is discovered in the different `publish:` sections? For example:

```
  nginx:
    image: username/nginx
    publish:
      - front

  web:
    image: username/web
    publish:
      - front
      - back

  db:
    image: username/db
    publish:
      - back
```

Should automatically result in a `back` and `front` network.

 If you need a specific custom driver or options for a network then perhaps create a `compose-networks.yml` file (which can be overwritten as a cli option) which can then be referenced.

I agree with the suggestion to prefix the project name to the network name (and perhaps use labels if they become available), anyone used to compose won't be too surprised by that pattern.
