### ISSUE TITLE
Previous container volumes warnings even with `--force-recreate`

### ISSUE THREAD

**Issue by pandeiro** [docker/compose#2481]
When calling `docker-compose up --force-recreate`, I see warnings about volumes from previous containers being used, even though, as I understand it (per conversion w/ @dnephin on #docker-compose), this should be a non-issue.

```
WARNING: Service "frontend" is using volume "/.foo" from the previous container. Host mapping "/home/user/.foo" has no effect. Remove the existing containers (with `docker-compose rm frontend`) to use the host volume mapping.
```

**Comment by dnephin** [comment]
This is a regression in 1.5.1, which is fixed for 1.5.2 (to be released soon).


You can grab a version of master: https://dl.bintray.com/docker-compose/master/ if you'd like to try it out before the 1.5.2 release.

Related issue: #2390

**Comment by aanand** [comment]
1.5.2 is out now:

https://github.com/docker/compose/releases/tag/1.5.2

**Comment by tian2992** [comment]
I have this same issue on docker-compose version 1.5.2 
```
WARNING: Service "data" is using volume "/var/lib/postgresql" from the previous container. Host mapping "None" has no effect. Remove the existing containers (with `docker-compose rm data`) to use the host volume mapping.
```
```
docker-compose version 1.5.2, build unknown
```

**Comment by dnephin** [comment]
The warning is still there, it should only be printed when a volume is actually being masked. 

Could you include your `docker-compose.yml` and the output of a docker inspect for the container?

**Comment by jrhite** [comment]
I just upgraded and see the same thing:

`docker-compose version 1.5.2, build 7240ff3`

```
$ docker-compose -f myapp-staging.yml up -d --force-recreate web
Recreating myapp_data_1
WARNING: Service "data" is using volume "/var/lib/postgresql" from the previous container. Host mapping "None" has no effect. Remove the existing containers (with `docker-compose rm data`) to use the host volume mapping.
Recreating myapp_postgres_1
Recreating myapp_web_1
WARNING: Service "web" is using volume "/usr/src/app/myapp/ui/dist/static" from the previous container. Host mapping "None" has no effect. Remove the existing containers (with `docker-compose rm web`) to use the host volume mapping.
WARNING: Service "web" is using volume "/usr/src/app/landingpage" from the previous container. Host mapping "None" has no effect. Remove the existing containers (with `docker-compose rm web`) to use the host volume mapping.
```

docker-compose.yml:
```
web:
  restart: 'always'
  build: ./web
  expose:
    - '8000'
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/myapp/ui/dist/static
    - /usr/src/app/landingpage
  env_file: .env-staging
  command: /usr/local/bin/gunicorn -w 2 -b :8000 myapp.main:app

nginx:
  restart: 'always'
  build: ./nginx
  ports:
    - '80:80'
  volumes_from:
    - web
  links:
    - web:web

data:
  image: postgres:9.4.5
  restart: 'no'
  volumes:
    - /var/lib/postgresql
  command: 'true'

postgres:
  image: postgres:9.4.5
  restart: 'always'
  env_file: .env-staging
  ports:
    - '5432:5432'
  volumes_from:
    - data
```

and docker inspect

```
$ docker inspect myapp_web
[
{
    "Id": "048b25633e887131922f477f2bbf37127970844e9fb0c531046d8e9566343248",
    "RepoTags": [
        "myapp_web:latest"
    ],
    "RepoDigests": [],
    "Parent": "3b7740d76719a22c94d35389609c596fdfbcd17d7f6df519dea7b27e03980a9b",
    "Comment": "",
    "Created": "2016-01-05T01:26:34.043350785Z",
    "Container": "a3b1cffa49908c1a036c7250d7fbc55cbf7d0a8ec2b94e63e8701a862addc37d",
    "ContainerConfig": {
        "Hostname": "609b1a101af3",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "PYTHON_VERSION=3.4.4",
            "PYTHON_PIP_VERSION=7.1.2",
            "NODE_VERSION=5.3.0"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "cd myapp/ui \u0026\u0026 ./node_modules/.bin/gulp dist \u0026\u0026 mkdir -p /usr/local/myapp/uploads"
        ],
        "Image": "3b7740d76719a22c94d35389609c596fdfbcd17d7f6df519dea7b27e03980a9b",
        "Volumes": null,
        "WorkingDir": "/usr/src/app",
        "Entrypoint": null,
        "OnBuild": [],
        "Labels": {}
    },
    "DockerVersion": "1.9.1",
    "Author": "",
    "Config": {
        "Hostname": "609b1a101af3",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "PYTHON_VERSION=3.4.4",
            "PYTHON_PIP_VERSION=7.1.2",
            "NODE_VERSION=5.3.0"
        ],
        "Cmd": [
            "python3"
        ],
        "Image": "3b7740d76719a22c94d35389609c596fdfbcd17d7f6df519dea7b27e03980a9b",
        "Volumes": null,
        "WorkingDir": "/usr/src/app",
        "Entrypoint": null,
        "OnBuild": [],
        "Labels": {}
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 847653,
    "VirtualSize": 906856274,
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    }
}
]
```
