### ISSUE TITLE
Ability to override service command in Compose file on CLI

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#2499]
There should be an ability to override the command for one service.

For example, for the following Compose file:

```
mycouchbase:
  build: .
  ports:
    - 8091:8091
    - 8092:8092 
    - 8093:8093 
    - 11210:11210
```

`docker-compose up mycouchbase bash`

This will simplify service debugging.
