### ISSUE TITLE
Syntax for locally-declared versus externally-created entities

### ISSUE THREAD

**Issue by aanand** [docker/compose#2502]
In the next version of the Compose file format, we plan to implement support for declaring networks and volumes in the Compose file, for use by services declared in the same application (see #2421, #2478).

It's likely that, as @dnephin raises in point 2 of https://github.com/docker/compose/issues/2478#issuecomment-160784494, we'll need to prefix the names of networks/volumes with the project name so that they don't conflict with networks/volumes declared in other applications.

This raises the issue of how to refer to *locally-declared* versus *externally-created* networks/volumes. Our requirements are:

1.  I want to define a network/volume in my Compose file with a particular name, and later refer to it by that name (without having to prefix it with an unpredictable project name). It'll be defined in a block looking something like this:

    ```yaml
    networks:
      locally-defined-network:
        driver: default
    volumes:
      locally-defined-volume:
        driver: default
    ```

2.  I want to create a network/volume manually via `docker network create` or `docker volume create` with a particular name, and later refer to it by that name.

    Note that this is already possible: you can refer to an externally-created network with `net`, or an externally-created volume with `volumes`. (We're *not* obliged to carry the existing syntax over, however - we're defining a new structure for the Compose file, so it's acceptable to introduce changes as long as the old syntax continues to work for files using the old format.)

When looking at a name in `net` or `volumes`, it's **not** an acceptable solution to first check for a locally-defined entity of the appropriate type that matches the name, and fall back to assuming that it's an externally-created entity if we don't find one. As described in #2501, this is error-prone and could make the file harder to read for users who aren't fluent in the Compose file format.

I have a couple of ideas as to how we could approach it. A key question, unanswered by either, is of which case should be considered the *default* - local versus external.

### Separate keys

Instead of overloading `net` and `volumes` with two different behaviours, we could split them into separate config options (we can bikeshed the actual prefix/suffix later if we choose to go down this route):

```yaml
local_net: locally-defined-network
net: externally-created-network
local_volumes: ["locally-defined-volume:/data"]
volumes: ["externally-created-volume:/data"]
```

or, more in line with with `links` and `external_links`:

```yaml
net: locally-defined-network
external_net: externally-created-network
volumes: ["locally-defined-volume:/data"]
external_volumes: ["externally-created-volume:/data"]
```

Arguably, the example above implies that old-style volume bind mounts like `.:/code` should also live under `external_volumes`, rather than `volumes`, which feels a bit weird.

### Sigils

We could rule that one (or both?) of local and external entities should be explicitly marked with a sigil of some kind. For example:

```yaml
net: @locally-defined-network
net: externally-created-network
volumes: ["@locally-defined-volume:/data"]
volumes: ["externally-created-volume:/data"]
```

If we flip the requirement around, then perhaps the sigil should be something that makes it clear that there's an external dependency, which should stand out:

```yaml
net: locally-defined-network
net: !externally-created-network
volumes: ["locally-defined-volume:/data"]
volumes: ["!externally-created-volume:/data"]
```

(Does this imply, similarly to the `external_volumes` example, that old-style bind mounts should *also* be prefixed? I'm not sure it does.)

---

**Note:** the design problem in #2501 is closely related to this one, but there's a crucial distinction: `net` and `volumes_from` deal with not just with entities *created in different ways* (locally defined versus externally created) but with entities of *different types* (service versus container).

**Comment by dnephin** [comment]
I think _local_ should be considered the default. The Compose file should aim to encapsulate all the requirements of an application, so locally defined things should be preferred.

For host volumes (anything with a `.`, `~`, or `/` prefix) I think we can consider those _local_ as well, since they aren't referring to anything created externally.

I don't have a strong opinion on sigil vs separate keys, but I think right now I'm leaning toward separate keys because it's easier to read. There's no need to learn that some character means something special. It's also possible that docker introduces some meaning for these sigil characters, which could potential break things, or make it even more confusing.

**Comment by aanand** [comment]
Agreed on all counts. In particular, I'd like to avoid defining new mini-syntaxes where possible, since it tends to result in a lot of string-parsing headaches down the line (see: volume binds on Windows, named volumes, variable substitution...)

**Comment by shin-** [comment]
Another way we could go about it is to simply add an optional parameter `external` (or `local`) into the volume / network definition. The user would set this parameter to `true` if they want that definition to refer to an external entity.

Like such:
```yaml
services:
  ...
volumes:
  local_volume:
    driver: blah
  external_volume:
    external: true
networks:
  local_network:
    opt1: foobar
  external_network:
    external: true
```

That lets us avoid weird syntax and separate keys defining the same thing. One drawback I could see is the engine team introducing an option named external for networks or volumes somewhere down the line. If we think that's a risk, we could always namespace our key (`compose_external` ?)

**Comment by dnephin** [comment]
I like this idea. If I understand it correctly, we're effectively providing a way to alias an external volume within a compose file.  So maybe the syntax could be:

```yaml
volumes:
  mysqldata:
    external: themysqldata

services:
  database:
    volumes:
     - mysqldata:/var/run/mysql
```

The name of the volume is `themysqldata`, but within the compose file you would use the alias `mysqldata`. This gives us a way to refer to non-namespaced volumes and networks without an extra service field, or special sigil.

It also has the advantage that all the volumes and networks have to be defined in the same place. With a separate field or sigil you have to scan the entire file to find the external ones.

**Comment by shin-** [comment]
That seems sensible to me. :+1:

**Comment by dnephin** [comment]
Looking at it again, you might be right that having a second alias is unnecessary. I'd be fine with either, it's a minor detail.

**Comment by aanand** [comment]
I think this is a great idea. I agree that it'd be a minor thing to be able to refer to an external volume by a different name, but it would still be nice.

I think having an option be of the type "boolean or string" is asking for trouble given YAML's liberal definition of boolean (as we've seen with `command` and `entrypoint`), so how about "boolean or object"?

```yaml
volumes:
  vol1:
    external: true
  vol2:
    external:
      name: some-external-volume
```

Here, `vol1` points to an external volume called `vol1`, whereas `vol2` points to an external volume called `some-external-volume`.
