### ISSUE TITLE
Epic: Backwards-incompatible changes to the Compose file format

### ISSUE THREAD

**Issue by aanand** [docker/compose#2504]
In the next version of the Compose file format, we plan to make changes to the basic structure of the file (see #2421, #2478). We will preserve existing behaviour for users of the old file format.

This means we have a good opportunity to make other potentially-backwards-incompatible changes to the configuration format, as long as they only apply to files using the new version. If users are upgrading their files anyway, it's less hassle to make other required changes at that time.

Here are some proposed changes it'd be good to get in:

- [x] [Make `net` and `volumes_from`'s container/service support explicit](https://github.com/docker/compose/issues/2501)
- [x] [Move logging configuration under `logging` key](https://github.com/docker/compose/issues/2503)
- [x] [New `build` config section](https://github.com/docker/compose/issues/2163)
- [x] [Image and build together](https://github.com/docker/compose/pull/2458) - not itself backwards-incompatible, but the implied changes to override logic (`image` will no longer override `build`, and vice versa) will be.

**Comment by aanand** [comment]
Added #2458 to the list, because of the implied changes to override logic.

**Comment by simonvanderveldt** [comment]
@aanand I guess adding a key for every type of driver makes sense? So not only `logging`, but also `network` and `volume`?
If so, maybe we should aggregate then under a `drivers` key?
So we get:
```
drivers:
  network:
    driver: foo
    options: bar
  volumes:
    driver: foo
    options: bar
  logging:
    driver: syslog
    options:
      syslog-address: "tcp://192.168.0.42:123"
```

Although volume drivers could be service/container specific...
