### ISSUE TITLE
has non-unique elements

### ISSUE THREAD

**Issue by pacolotero** [docker/compose#2544]
This is my docker-compose.yml file
```
ntt-assets-data:
  image: busybox
  volumes:
    - /app/public/assets
  command: /bin/sh

ntt-gems-data:
  image: busybox
  volumes:
    - /gems
  command: /bin/sh

ntt-mongodb-data:
  image: busybox
  volumes:
    - /data/db
  command: /bin/sh

ntt-mongodb:
  image: mongo
  volumes_from:
    - ntt-mongodb-data
  command: --smallfiles

ntt-rails:
  build: rails/
  volumes_from:
    - ntt-gems-data
    - ntt-assets-data
    - ntt-gems-data
  volumes:
    - /etc/localtime:/etc/localtime:ro
  external_links:
    - ntt-mongodb:mongodb

ntt-jobs:
  build: rails/
  volumes_from:
    - ntt-gems-data
    - ntt-assets-data
    - ntt-gems-data
  volumes:
    - /etc/localtime:/etc/localtime:ro
  external_links:
    - ntt-mongodb:mongodb
  command: /bin/bash -c "eye l /eye_jobs.rb -f"

ntt-nginx:
  build: nginx/
  volumes_from: 
    - ntt-rails
    - ntt-assets-data
  external_links:
    - ntt-rails:rails
  ports:
    - 9876:80
```

When i try to start docker-compose up, I get the following error:
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'ntt-jobs' configuration key 'volumes_from' value ['ntt-gems-data', 'ntt-assets-data', 'ntt-gems-data'] has non-unique elements
Service 'ntt-rails' configuration key 'volumes_from' value ['ntt-gems-data', 'ntt-assets-data', 'ntt-gems-data'] has non-unique elements

I try to start the continer named ntt-jobs and ntt-rails with the volumes from ntt-assets-data and ntt-gems-data in top of the document
