### ISSUE TITLE
Proposal: support for args_file

### ISSUE THREAD

**Issue by mbontemps** [docker/compose#2545]
#### Motivation for this proposal
- build args have been introduced in Docker 1.9.0.
- #2163 proposes a new `build:` section in your Compose service
- builds args can be used to provide secret tokens (ssh key to clone a repository, github token...) during the build phase. These tokens should however not appear in your `docker-compose.yml` file but rather in a separate file.
#### Proposal

Introduce a `args_file:` section working the same way that `env_file:` works - but in the build phase.
##### args_file

Add build arguments from a file. Can be a single value or a list.

If you have specified a Compose file with `docker-compose -f FILE`, paths in `args_file` are relative to the directory that file is in.

Environment variables specified in `args` override these values.

``` yaml
build:
 args_file: .args

build:
  args_file:
    - ./common.env
    - ./apps/web.env
    - /opt/secrets.env
```

Compose expects each line in an env file to be in `VAR=VAL` format. Lines beginning with `#` (i.e. comments) are ignored, as are blank lines.

``` ini
# Set the secret token necessary to clone the dependencies
SECRET_TOKEN=yNxbjX
```

**Comment by aanand** [comment]
Makes sense to me.

**Comment by marcellodesales** [comment]
:+1:

**Comment by thaJeztah** [comment]
Nice idea

I'm not sure we should use `/opt/secrets.env` as an example in our documentation, given that we discourage people to use build-time args for secrets (the args are included in the history of an image, so would be visible to others)

**Comment by daef** [comment]
i'd really love args_file, i kinda expected it to be there - but i am disappoint now i've found it just got proposed

**Comment by marcellodesales** [comment]
@thaJeztah Is this planned for the next release?

**Comment by schmunk42** [comment]
> These tokens should however not appear in your docker-compose.yml file

A workaround is to use a `.env` file and ENV variables (compose 1.7+ AFAIR)

```
version: '2'
services:
  php:
    build:
      dockerfile: Dockerfile-7.0-fpm
      context: .
      args:
        - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    image: local/dmstr/php-yii2
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
```
