### ISSUE TITLE
Starting a single service from Docker Compose

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#2570]
Using the following Compose file:

```
mycouchbase:
  container_name: "db"
  image: arungupta/couchbase
  ports:
    - 8091:8091
    - 8092:8092 
    - 8093:8093 
    - 11210:11210
mywildfly:
  image: arungupta/wildfly-couchbase-javaee7
  environment:
    - COUCHBASE_URI=db
  ports:
    - 8080:8080
    - 9990:9990
```

Starting a service as `docker-compose start mycouchbase` just returns back to the prompt. `docker ps` shows no containers are started.

`docker-compose logs` shows the output as:

```
Attaching to 
```

This is non-intuitive behavior.
