### ISSUE TITLE
Proposal: Improve Port Mapping Syntax

### ISSUE THREAD

**Issue by dave-tucker** [docker/compose#2605]
In the current Docker CLI (as of 1.9) there are at least 4 ways of specifying a port mapping for `-p`
- `containerPort`
- `hostPort:containerPort`
- `hostIP:hostPort:containerPort`
- `hostIP::containerPort`

As Compose is looking to make some incompatible changes in the v2 format I would like to propose that we move away from using the `string` and to instead use a `hash`/`dictionary`

**v1**

```
ports:
  - "80"
  - "8080:80"
  - "192.168.99.100:8080:80"
  - "192.168.99.100::80"
```
- Proposed v2**

```
ports:
  - container_port: 80

  - host_port: 8080
    container_port: 80

  - host_ip: "192.168.99.100"
    host_port: 8080
    container_port: 80

  - host_ip: "192.168.99.100"
    container_port: 80
```

The new format should be:
- Easier to read
- Easier to validate as the port numbers are `int` rather than `string` and there are no separators to deal with
- Easier to document - we replace 4 different string formats with 3 keys

`container_port` is required, all other fields are optional
`host_port` defines a specific port on the host
`host_ip` specifies which IP address a port should bind to (default 0.0.0.0)

**Comment by aanand** [comment]
Linked to from https://github.com/docker/compose/issues/2504

**Comment by dnephin** [comment]
I believe there are also port ranges that can be used as both host and container port.

Repeating `port` in the keys in a `ports` section seems redundant. Could we do:

```yaml

ports:
   - host: 80-90
     container: 8080-8090
     host_ip: 192.168.99.190
```

I expect there will be users who are unhappy with this change, especially if they have many ports in their compose file.

I'd like to see us keep the minimal form for the first two string formats `80` and `80:8000`. If you need an IP or range, then you must use the mapping form. That way most users can continue to use the less-verbose, and really not difficult to parse version, and the few users who actually need to specify a host ip or port range can use the more verbose option.
