### ISSUE TITLE
Overriding volumes from extended configurations

### ISSUE THREAD

**Issue by maxcnunes** [docker/compose#2633]
Based in the example for environment variables is possible to override configurations based in the key:

https://docs.docker.com/compose/extends/#adding-and-overriding-configuration

``` bash
# original service
environment:
  - FOO=original
  - BAR=original

# local service
environment:
  - BAR=local
  - BAZ=local

# result
environment:
  - FOO=original
  - BAR=local
  - BAZ=local
```

But this same approach does not work for volumes:

``` bash
# original service
volumes:
  - /tmp/foo:/tmp/original
  - /tmp/bar:/tmp/original

# local service
volumes:
  - /tmp/bar:/tmp/local
  - /tmp/baz:/tmp/local

# result
volumes:
  - /tmp/foo:/tmp/original
  - /tmp/bar:/tmp/original
  - /tmp/bar:/tmp/local
  - /tmp/baz:/tmp/local
```

**Docker** `1.8.3`
**Compose** `1.5.2`

**Comment by dnephin** [comment]
That's right, there is no way to remove a volume from an extended service. It's incompatible with merging.

The only thing you can do is structure the services in a way that you never have to remove a volume. Starting with a base with no volumes, or minimal volumes that are always required, and add just the necessary ones.

**Comment by maxcnunes** [comment]
Sorry, actually the overriding for volumes does work. But the key is the internal path:

```yaml
# original service
volumes:
  - /tmp/original:/tmp/foo
  - /tmp/original:/tmp/bar

# local service
volumes:
  - /tmp/local:/tmp/bar
  - /tmp/local:/tmp/baz

# result
volumes:
  - /tmp/original:/tmp/foo
  - /tmp/local:/tmp/bar
  - /tmp/local:/tmp/baz
```
