### ISSUE TITLE
Can't use linked resource with log driver

### ISSUE THREAD

**Issue by chiefy** [docker/compose#2657]
I'm not sure if this is possible, but I was trying to do something like the following:

```
app:
  image: nginx
  ports: 
    - "80:80"
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://logstash:12201"
  links:
    - logstash

logstash:
  image: logstash
  expose:
    - "12201/udp"  
```

Currently this won't work, I assume because the log driver tries to initialize before any linking is done?

**Comment by dnephin** [comment]
Correct, it doesn't work because the log driver urls needs to be accessible by the daemon, not by the container. The `logstash` alias is never provided to the daemon. With the upcoming changes to how DNS works in docker 1.10 there might be some way to get this to work, I'm not sure.

This is a duplicate of #2182, however I think the description does a better job of demonstrating the problem, so maybe we should keep this one and close the other.

**Comment by chiefy** [comment]
thanks @dnephin I figured as much after I kept getting DNS errors.

**Comment by dnephin** [comment]
@mavenugo, @mrjana, @dave-tucker

Now that docker 1.10 is using an embedded DNS server, is there any way that the daemon could query that DNS server itself to support this use-case?

**Comment by dnephin** [comment]
ping @mavenugo again.  This seems to be a common request/issue (just had another question about it in IRC).

Is there any way the engine can use a name like `service.network` to access this service?

**Comment by lucj** [comment]
Hi, do you have any update on that one ?

**Comment by dave-tucker** [comment]
@dnephin I believe it's technically possible, but it's not a planned feature AFAIK.

What's the use case for running an instance of a log server per application?
As a workaround, you can use `--net=host`, for example:

```
app:
  image: nginx
  ports: 
    - "80:80"
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"

logstash:
  image: logstash
  net: host
  expose:
    - "12201/udp"  
```

In the v2 format, you can even use `depends_on` to make sure that the `logstash` container is started first.
