### ISSUE TITLE
New field `network_mode` for v2 format

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2701]
Currently we support `host`, `bridge` and `none` as special cases in the list of networks, and we don't support `net: container:...` or `net: service:...`.

The new `network_mode` field would be a single scalar string value which supports any of the above, and we would remove this support from the  `networks` field.

**Comment by aanand** [comment]
It occured to me, while implementing this, that it's perfectly fine for a container to join both the `bridge` network and custom networks, so we should still allow `bridge` as a special value in `networks`.

Other values should definitely go in `network_mode` though (including `host` and `none`, because those can't be combined with other networks).

**Comment by dnephin** [comment]
I think we could also make `bridge` a network mode, and allow `network_mode: bridge` with any `networks:` value, but disallow a `networks:` value if `network_mode:` is anything else?

I think specifying `network_mode: bridge` is probably pretty rare, since it's the default in all cases I believe.

Would that work?

**Comment by ibuildthecloud** [comment]
I don't understand this change.

1) Why deviate from the Docker CLI here?  I find this very confusing.  Does v2 not support `net:`??

2) What does network_mode service mean?  If I have service A and service B with network mode service:A, and I scale A=2, B=3, what does that mean?  How are these things scheduled?

**Comment by ibuildthecloud** [comment]
Okay, I found the answer to 1), but 2) I'm still confused on.

**Comment by aanand** [comment]
`network_mode: service` and `scale` won't interact well, much as is the case with `volumes_from`. There's no clean solution there without revisiting the Docker API design to facilitate the creation of co-scheduled groups of containers.

**Comment by kierr** [comment]
I have a setup where I'm using `network_mode: service:vpn`, using a container as an OpenVPN client for other containers outgoing connections. However doing this, they obviously all have the same internal IP.

Since the containers also need to communicate internally, I want to create a separate internal network, but when doing so I get `ERROR: 'network_mode' and 'networks' cannot be combined`.

Is there a way to achieve both a separate internal network while pushing everything through the OpenVPN client container, using a combination of `networks` and `network_mode` with the v2 format?

**Comment by dnephin** [comment]
I haven't tried it myself, but I think you might be able to set `networks` on the `vpn` service (since that one doesn't use a `network_mode`, and everything else using its network stack would be on the same network.  

If you mean "the containers using `network_mode:` need to communicate internally" they would all just use localhost I believe.

**Comment by kierr** [comment]
Thanks for the input @dnephin. The problem is that this is a Selenium Grid setup, with one `hub`, and many `nodes` that listen on the same port, pointed towards the `hub`.

I want the nodes to all go through the VPN, but with my current configuration, I am limited to one single unscalable node since all nodes are on `127.18.0.2`. Also, automatic `/etc/hosts` entries don't seem to work... but I think that might be an unrelated issue.

Essentially, I need to create a `network` that has all its traffic pushed through the OpenVPN container... and then set it in `networks` on the nodes only, with the others communicating internally on the default network.

I hope I've made some sense, I'm new to compose so it might not have - if so, seeing the `docker-compose.yml` might clarify:

```
version: '2'
services:
  vpn:
    image: dperson/openvpn-client
    restart: always
    cap_add:
      -  NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn:/vpn
      - ./resolv.conf:/etc/resolv.conf
    dns: 8.8.4.4
    command: -f
  hub:
    image: selenium/hub
    restart: always
    network_mode: service:vpn
    volumes:
      - ./hub.json:/opt/selenium/config.json
    depends_on:
      - vpn
  nginx:
    image: dperson/nginx
    restart: always
    command: -w "http://172.18.0.2:4444/;/"
    ports:
      - 4444:80
    links:
      - vpn
  firefox:
    image: selenium/node-firefox
    restart: always
    network_mode: service:vpn
    volumes:
      - ./node.json:/opt/selenium/config.json
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=172.18.0.2
      - HUB_PORT_4444_TCP_PORT=4444
```

Brief notes:
- I have a resolv.conf volume because using `dns` doesn't set DNS, without it resolv.conf contains `127.0.0.11`.
- Each `/etc/hosts` has only a 'self' entry, using the container ID rather than the container name. (huh?)

Perhaps a docker veteran such as yourself could be kind enough as to point out the much simpler and cleaner way to achieve what I'm trying here, surely there's a better way?

PS. I don't mean to hijack, but this does still revolve around the v2 network_mode format, and there doesn't seem to be a better place for it.
