### ISSUE TITLE
[1.6.0] Extra volumes are created when using new compose file format

### ISSUE THREAD

**Issue by anadale** [docker/compose#2709]
I have __docker-compose.yml__ file in folder __nowsd__:
```yml
version: 2
volumes:
  data:
    driver: local
  ugc:
    driver: local
services:
  web:
    image: busybox
    volumes:
      - data:/var/log
      - ugc:/var/ugc
```
_$_ __docker-compose up__
```
Starting nowsd_web_1
Attaching to nowsd_web_1
nowsd_web_1 exited with code 0
```
_$_ __docker volume ls__
```
DRIVER              VOLUME NAME
local               nowsd_data
local               data
local               ugc
local               nowsd_ugc
```

You can see that two extra unscoped volumes has been created. When I inspect container nowsd_web_1 i can see that volumes _data_ and _ugc_ are attached to container instead of _nowsd_data_ and _nowsd_ugc_ respectively.
