### ISSUE TITLE
[Feature request] docker-compose validate

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#2732]
Can we get a command which just runs the yaml validation and outputs any errors?

**Comment by dnephin** [comment]
Yes! it already exists as `docker-compose config` in 1.6 (RC 1 is out now). You can run it with `-q` if you want to hide the config.

**Comment by schmunk42** [comment]
Awesome! One thing I noticed:

From my `docker-compose.yml`

```
  environment:
    - YII_ENV=dev
    - YII_DEBUG=1
    - constraint:node==yo
```

Output with `docker-compose config`

```
    environment:
      YII_DEBUG: '1'
      YII_ENV: dev
      constraint:node: =yo
```

@dnephin I can't reuse the output, should the syntax be like that, looks wrong with `=yo`?
