### ISSUE TITLE
`docker-compose pull` should pull base images for built containers

### ISSUE THREAD

**Issue by Yajo** [docker/compose#2742]
Say you have a `docker-compose.yml` like:

```
one:
  image: python
two:
  build: .
```

And a `Dockerfile` like:

```
FROM ruby
...
```

I'd expect `docker-compose pull` to pull both `python` and `ruby` images. Only `python` is currently pulled.
