### ISSUE TITLE
Volumes with slashes in the name do not run

### ISSUE THREAD

**Issue by jacobtomlinson** [docker/compose#2837]
I'm trying to use the [netshare volume plugin](https://github.com/gondor/docker-volume-netshare) with a v2 docker compose file.

In netshare the volume name is the same as the network location to be mounted, e.g `docker volume create -d cifs --name someserver.example.com/path/to/mount`. When trying to set this name in compose using the following format I get an error message.

``` yaml
version: '2'

services:
  # Services are here

volumes:
  someserver.example.com/path/to/mount:
    driver: cifs

```

```
ERROR: Validation failed in file './docker-compose.yml', reason(s):
volumes value Additional properties are not allowed ('someserver.example.com/path/to/mount' was unexpected)
```

Am I doing something wrong?

**Comment by kuhnroyal** [comment]
You might be able to do something like this as a workaround:

```
docker volume create -d cifs --name someserver.example.com/path/to/mount
```

```
version: '2'

services:
  # Services are here

volumes:
  data:
    external: true
        name: someserver.example.com/path/to/mount
```

**Comment by dnephin** [comment]
Yes, I think you'll have to use external name if that's the case. Good suggestion.

**Comment by rbayliss** [comment]
Unfortunately, this still doesn't work.  I've got a volume that was created using 
`docker volume create -d nfs --name 192.168.99.1/Users/foo/Sites`
and the following block in docker-compose.yml:
```
volumes:
  sites:
    name: "192.168.99.1/Users/foo/Sites"
```
I'm still getting:
```
ERROR: Validation failed in file './docker-compose.yml', reason(s):
volumes.sites value Additional properties are not allowed ('name' was unexpected)
```

**Comment by kuhnroyal** [comment]
You are missing the `external` part.

**Comment by rbayliss** [comment]
Yeah I have `external: true` in my actual file, just forgot to put it in the comment above.

**Comment by chmielot** [comment]
Using the netshare plugin I mounted my nfs directory like this:
`docker run -it -p 80:80 --volume-driver=nfs -v 192.168.99.1/Users/me/code:/var/www/html`

Then I ran:
`docker volume create -d nfs --name 192.168.99.1/UsersUsers/me/code`

Adapting it to docker-compose I ended up with something like this, which works perfectly:
```
services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - "data:/var/www/html"
        links:
            - db

volumes:
    data:
        external:
            name: "192.168.99.1/Users/me/code"
```
