### ISSUE TITLE
compose silently ignore networks when extends or multiple compose files

### ISSUE THREAD

**Issue by dmaumenee** [docker/compose#2839]
Compose 1.6 silently ignore the "networks" option when the service extends from another one.

This version 2 docker file :
```YAML
version: '2'
services:
  foo:
    image: busybox
    command: echo foo
  bar:
   extends: foo
   command: echo bar
   networks:
      - mynetwork
networks:
  mynetwork:
```

Results in the following resolved config after loading:
 
```YAML
networks:
  mynetwork: {}
services:
  bar:
    command: echo bar
    image: busybox
  foo:
    command: echo foo
    image: busybox
version: '2.0'
volumes: {}
```

The "bar" container is not attach to "mynetwork".
