### ISSUE TITLE
Compose should allow creating an external network if it doesn't exist

### ISSUE THREAD

**Issue by ErikGrimes** [docker/compose#2846]
I have a database shared by multiple applications, each application and related services is defined in a separate compose file. Currently I have to create the external network by hand or have an additional script which makes sure the network exists and then calls docker-compose up.  I'd like the option within the compose file to create the external network for me if it doesn't exist.

**Comment by dnephin** [comment]
If the network was created by Compose it wouldn't be external!

What about something like this:

Create a project to start the database and a network for the database, let's say the project name is `shareddb`. To start the database (and create the network) you would run `docker-compose -p shareddb up d`.

Now in any project that uses the db you can join the network on any services that use it:

```yml

version: '2'

networks:
  database:
    external:
       name: shareddb_default

services:
  web:
    ...
    networks:
      - default
      - database
```

That way you don't have do create anything by hand or write any new scripts, and the distinction between external and internal is maintained.
