### ISSUE TITLE
Host is not reachable

### ISSUE THREAD

**Issue by piotrantosik** [docker/compose#2872]
From logs:
```nginx_1       | nginx: [emerg] host not found in upstream "php:9000" in /etc/nginx/conf.d/upstream.conf:1```

Container ```nginx``` not see ```php``` and none other - eg. I can't connect from ```php``` to ```redis```.
Previously, i used links, however i trying to solve the problem of circular dependency. I need connection between nginx <=> php

docker-compose.yml
```
version: '2'

services:
    application:
        build: docker/code
        volumes:
            - ./:/var/www/app
        tty: true

    db:
        image: mysql:5.6
        ports:
            - 3306:3306

    php:
        build: docker/php
        ports:
            - 9000:9000
        volumes_from:
            - application

    redis:
      image: redis:3.0
      ports:
          - 6379:6379

    nginx:
        build: docker/nginx
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - application
        volumes:
            - ./var/logs/nginx/:/var/log/nginx

```

docker-compose version
```
docker-compose version 1.6.0, build d99cad6
docker-py version: 1.7.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

docker version
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:10:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:10:32 2016
 OS/Arch:      linux/amd64
```

**Comment by dnephin** [comment]
When you remove links the order that containers start is undefined, so likely what's happening is that the nginx containers are starting before the php container.

You can test this out by running `up` multiple times:
```
docker-compose up -d
sleep 2
docker-compose up -d
sleep 2
docker-compose up -d
```

After the second or third attempt you should see it connect.

To solve this problem, you could try adding a `depends_on` to nginx to have it depends on php.
Another option is to use a tool to wait for the service to be ready before lanching nginx, https://github.com/jwilder/dockerize is one example of this.

**Comment by piotrantosik** [comment]
Thanks for help @dnephin i checked both solutions, but no result.
I simplify yml for test:

docker-compose.yml:
```yml
version: '2'

services:
    application:
        build: docker/code
        volumes:
            - ./:/var/www/app
        tty: true

    redis:
        image: redis:3.0
```

application dockerfile:

```
FROM debian:jessie

RUN apt-get update && apt-get install -y \
    telnet

VOLUME /var/www/app
```

I run containers with ```docker-compose up -d```
```docker-compose ps``` return:
```
        Name                      Command             State    Ports   
----------------------------------------------------------------------
members_application_1   /bin/bash                     Up               
members_redis_1         /entrypoint.sh redis-server   Up      6379/tcp 
```

Then i check if redis is accessible from application ```docker exec -it members_application_1 env TERM=xterm bash```:
```bash
$ telnet redis 6379
telnet: could not resolve redis/6379: Name or service not known
```

A mistake in the config or is a bug? All hosts should be accessible between containers.
