### ISSUE TITLE
How to share mysql root password env with web container in v2 config?

### ISSUE THREAD

**Issue by aramalipoor** [docker/compose#2910]
In v1 we would simply link two containers and access the linked container env variables, we would do,

``` yml
web:
  links:
    - db

db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: mypass
```

Then access mysql's env in `web` entrypoint.sh,

``` sh
set_parameter "database_password" ${DB_ENV_MYSQL_ROOT_PASSWORD}
```

How we're supposed to do this when using v2, besides passing that as env directly to web?

**Comment by dnephin** [comment]
```yaml
web:
  links:
    - db
  environment:
     MYSQL_PASSWORD: mypass

```
