### ISSUE TITLE
docker-compose 1.6 on windows - Container command not found

### ISSUE THREAD

**Issue by kimptoc** [docker/compose#2924]
Hi,

I have a compose file like so:

```
printversion:
  image: jruby:1.7.24-onbuild
  command: -v
server:
  image: jruby:1.7.24-onbuild
  volumes:
    - .:/app/jruby-drb-test
  command: scripts/drb_server.rb
client:
  image: jruby:1.7.24-onbuild
  volumes:
    - .:/app/jruby-drb-test
  command: scripts/drb_client.rb
  links:
    - server
  environment:
    - runs
    - message_size
```

However this gives an error when running it 'up'
```
$ docker-compose up
Starting dockerjrubywebricktester_server_1
Container command not found or does not exist.
```

I have a similar compose file (https://github.com/kimptoc/docker-jruby-drb-tester) that works on OSX/Linux - is this a Windows issue perhaps?

Thanks in advance,
Chris

**Comment by aanand** [comment]
It looks like the volume isn't mounting correctly, resulting in `/app/jruby-drb-test` being empty, and therefore `/app/jruby-drb-test/scripts/drb_server.rb` not existing.

1. Are you working from somewhere within your home directory? If not, volume mounts from the current directory won't work.
2. If you are, it could be the case that Compose isn't setting the right mount path - could you paste the output of `docker inspect dockerjrubywebricktester_server_1`?
3. Finally, it's possible that Machine/VirtualBox aren't mounting your home directory properly. What's the output of `docker run -v /c:/c busybox ls -l /c`?

**Comment by kimptoc** [comment]
Thanks @aanand - I was using my own Dockerfile build, which setup the /app/jruby-drb-test/ directory.  It won't exist in the jruby image - doh.

Will review it in the morning :+1:

**Comment by kimptoc** [comment]
Hmm - doh - never realised that mounts had to be below my home directory. 

This is my compose file now
```
server:
  image: jruby:1.7.24
  volumes:
    - .:/home
  command: ruby scripts/drb_server.rb
```

Which fails to find my script, due to the mounting issues

Trying the "ls /c", its not mounting anything. But given your point 1), I guess thats expected.
```
$ docker run -v /c:/c busybox ls -l /c
ls: /c: No such file or directory
```

But mounting my home directory does work:
```
$ docker run -v /c/Users/kimptonc:/c busybox ls -l /c
total 14727
-rwxrwxrwx    1 1000     staff        71914 Jun 12  2015 1.txt
-rwxrwxrwx    1 1000     staff        71914 Jun 12  2015 2.txt
...
```

This now works:
```
printversion:
  image: jruby:1.7.24
  command: ruby -v
server:
  image: jruby:1.7.24
  volumes:
    - .:/home
  working_dir: /home
  command: ruby scripts/drb_server.rb
client:
  image: jruby:1.7.24
  volumes:
    - .:/home
  working_dir: /home
  command: ruby scripts/drb_client.rb
  links:
    - server
  environment:
    - runs
    - message_size
```
