### ISSUE TITLE
Unsupported config option: depends_on

### ISSUE THREAD

**Issue by nottrobin** [docker/compose#2931]
Even though the [latest release](https://github.com/docker/compose/releases) mentions `depends_on` ([documented here](https://docs.docker.com/compose/compose-file/#depends-on)):

> There's a new depends_on option for specifying dependencies between services.

I can't get it to work:

``` bash
$ docker-compose --version
docker-compose version 1.6.0, build d99cad6
$ docker-compose up
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Unsupported config option for web: 'depends_on'
```

Here's the relevant section of my `docker-compose.yml`:

``` yaml
web:
  build: .
  ports:
    - "8010:5000"
  links:
    - db
  depends_on:
    - db-ready
```

**Comment by Mirabis** [comment]
You must specify version: '2' on top of the compose file :)

**Comment by nottrobin** [comment]
Ah thanks @Mirabis. I found the [upgrade guide](https://docs.docker.com/compose/compose-file/#upgrading). I'm testing that out now. I'll close this once I've confirmed everything works as expected.

**Comment by manjitkumar** [comment]
@Mirabis @nottrobin I faced the same error while building an image using ansible-container. Here's my container.yml file.

```yml
version: "2"
services:
  redis:
    image: redis:3.2
  mandalore_api:
    image: python:2.7
    ports:
      - "9000:9000"
      - "8001:8001"
    links:
      - redis
    depends_on:
      - redis
    command: []
    dev_overrides:
      environment:
        - "DEBUG=1"

registries:
  local:
    url: https://docker-hub.local.io
    namespace: local

```
