### ISSUE TITLE
abort-on-container-exit does not work as expected

### ISSUE THREAD

**Issue by rbann** [docker/compose#2940]
```
> uname -a
Linux mycomputername 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> docker -v
Docker version 1.10.1, build 9e83765
> docker-compose -v
docker-compose version 1.6.0, build d99cad6
```
According to the docs https://docs.docker.com/compose/reference/up/,
`--abort-on-container-exit` should
> Stop all containers if any container was stopped.

docker-compose.yml:
```
version: "2"

services:
    loop1:
        image: ubuntu:latest
        command: bash -c 'for i in {1..5}; do echo $$i && sleep 1; done'
        stop_signal: SIGKILL

    loop2:
        image: ubuntu:latest
        command: bash -c 'for i in {1..10}; do echo $$i && sleep 1; done'
        stop_signal: SIGKILL
```

After `docker-compose up --abort-on-container-exit` both containers start sending log messages.
When `loop1` exits, documentation suggests that `loop2` will also be stopped. This does not happen, which can be confirmed by executing `docker-compose ps` shortly after `loop1` exits.

An other issue which may be related:
When hitting `Ctrl-C` after `docker-compose up` I would expect this:
```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dockercompose_loop1_1 ... done
Stopping dockercompose_loop2_1 ... done
```
This is only happening occasionally, most of the time I get this instead:
```
^CERROR: Aborting.
```
Also, the containers remain up.

**Comment by dnephin** [comment]
The `Ctrl-c` issue is unrelated, it is #2904

**Comment by dnephin** [comment]
I believe the issue you're seeing is #2904.

Are you able to try out 1.6.0 with a `pip` install to confirm ?

**Comment by rbann** [comment]
Yes, the `ctrl-c` issue disappears with pip installing compose.
More interesting is the first part of the story. I may have misunderstood the docs, but the `--abort-on-container-exit` flag should result in actually stopping the 'other' containers when one exits, not just deattach.
I have created a PR for this, (https://github.com/docker/compose/pull/2956) but it mysteriously fails on a seemingly unrelated test.

**Comment by dnephin** [comment]
This was added in #2130, and I realize now that there is no end-to-end test for it. I can confirm this is a bug, it should stop other services.

I'm really surprised this went unnoticed for so long, thanks for the report and the PR.

**Comment by rbann** [comment]
OK, I'm looking at the comments on the PR.
One more thing, where the desired behavior is not clear to me.
With the following `docker-compose.yml`:

```yml
version: "2"

services:
    loop1:
        image: busybox
        command: error

    loop2:
        image: busybox
        command: top
```

`docker-compose up` exits:

```
> docker-compose up
Creating playground_loop2_1
Creating playground_loop1_1
ERROR: Container command not found or does not exist.
> docker-compose ps
       Name          Command    State     Ports 
-----------------------------------------------
playground_loop1_1   error     Exit 127         
playground_loop2_1   top       Up
```

Each of the following can be correct in this case (maybe should be documented in a more clear way):

1. Current behavior: exiting, but leaving the other containers up in an orphaned way.
2. Exiting and also stopping other containers.
3. Staying attached to the running containers if `--abort-on-container-exit` was **not** given, exiting otherwise.

IMO any of 2. or 3. is better than the current 1.

Thanks.
