### ISSUE TITLE
Bug: extended services are not overriden

### ISSUE THREAD

**Issue by gagoman** [docker/compose#2944]
Good day.

Sample case:
- `docker-compose.yml`
  
  ```
  version: '2'
  
  services:
      echo:
          image: alpine
          entrypoint: [echo]
          command: ['Hello, world!']
  
     hello-world:
         extends:
             service: echo
  ```
- `docker-compose.prod.yml`
  
  ```
  version: '2'
  
  services:
     echo:
        command: ['Not so friendly']
  ```

Outputs for `hello-world`:
- `docker-compose up hello-world`
  
    `Hello, world!`
- `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up hello-world`
  
  `Hello, world!` (`Not so friendly` was expected)

While outputs for `docker-compose up echo` are ok

**Versions**:
- Docker `1.10.1`
- Compose `1.6.0`

**Comment by dnephin** [comment]
The behaviour of extends + multiple files is not well defined. 

What's happening here is that `extends` is being expanded to 

```yml

extends:
    file: docker-compose.yml
    service: echo

```

Given that expanded syntax, I think the current behaviour makes sense, however I'm not sure it's obvious with the short form.

**Comment by Webokage** [comment]
I have the same issue with dns_search option, how am I suppose to deal with that ?

Extended file :
```yaml
version: '2'
services:
    front:
        image: nginx:1.9
        dns_search: "test"
```

Global file :
```yaml
version: '2'
services:
    my_front:
        extends:
            file: ./docker-compose.test.yml
            service: front
        dns_search: "test2"
```
```bash
$ docker-compose run other_service ping test2
ping: unknown host
```

**Comment by gagoman** [comment]
@dnephin I understand this.

Nonetheless,

definition like

````
version: '2'

services:
   echo:
      extends:
           service: echo
           file: docker-compose.yml
      command: ['Not so friendly']
````

in `docker-compose.prod.yml` leads to `Circular reference`, so merge is broken
