### ISSUE TITLE
Need Help on how to run tests

### ISSUE THREAD

**Issue by devotox** [docker/compose#2976]
My docker setup involves everything in its own container which has an nginx container sitting in front of it and reverse proxying to a database container running postgres, an api container running node, 2 frontend containers. 

The problem im having is that i am not able to run the tests on my API as it depends on the host name being correct but it cannot connect to that hostname within itself in the container. 

Would i need to set up a link from the api container to the nginx container. (I already have a link from the nginx container to the api container). and if so how would i do this in a way that i can still use the right host in my config file for the tests

**Comment by dnephin** [comment]
With the v2 compose format you should be able to connect to the service name from within the service container. So the `api` should be able to use `api` as the hostname.  Is that what you mean?

**Comment by devotox** [comment]
Not exactly I need it to be able to hit the host intranet.doctify.local.com
and for that to somehow route to the host which will then route back to the
nginx container. This is so we can test our api endpoints from the aspect
of how they would get hit by a user

**Comment by dnephin** [comment]
By "host" do you mean container?  You can use links to create aliases, to make any container appear as if it had that hostname. 

For example, this works:

```
version: '2'
services:
  nginx:
    image: alpine:3.3
    command: sleep 200
 
  testdriver:
    image: alpine:3.3
    command: ping -c 10 intranet.doctify.local.com
    links:
      - 'nginx:intranet.doctify.local.com'
```

The tests would run in`testdriver`.
