### ISSUE TITLE
docker-compose host-ip value should defaults to the --ip value of docker daemon

### ISSUE THREAD

**Issue by bbinet** [docker/compose#2999]
If we don't specify host ip address when declaring the ports in the compose file, like:

```
ports:
  - "8000:8000"
```

docker-compose will assume the host ip address to use is `0.0.0.0`, but if we run the docker daemon with the `--ip=<default-ip>` option, it should use `<default-ip>` instead.

See in the [docker daemon documentation](https://docs.docker.com/engine/reference/commandline/daemon/):
`--ip=0.0.0.0                           Default IP when binding container ports`

The `--ip=<default-ip>` option is correctly taken into account when running a container directly with `docker run`, but when I want to run it through `docker-compose`, it does not work and we have to force host ip value for all services in the docker-compose.yml file like:

```
ports:
  - "10.0.0.1:8000:8000"
```

**Comment by dnephin** [comment]
Seems strange, because we just pass these values on to the API, and I would have expected the engine to handle it, but maybe it's actually the docker-cli which is doing the work here. If that's the case, the correct fix might be to have the engine do it instead of the client.

Needs more investigation.

**Comment by dato** [comment]
As far as I can see, when a version 2 YAML definition does not specify what networking to use, docker-compose creates a `projectname_default` network instead of using the default.

These `projectname_default` networks do not have _host_binding_ipv4_ set, even if the daemon was started with e.g. `--ip=192.168.17.1`:

```
# Default ‘bridge’ network
$ docker network inspect bridge  |  grep host_binding_ipv4
    "com.docker.network.bridge.host_binding_ipv4": "192.168.17.1", 

# docker-compose-created ‘example_default’ (see YAML below)
$ docker network inspect example_default | grep host_binding_ipv4 || echo not present
not present
```

_example_default_ was created by docker-compose for a very simple file:

```yaml
version: "2"

services:
  test:
    image: busybox
    command: sleep 60

    ports:
      - "7560:8080"
```

One simple workaround is to specify `network_mode: default` in services defined in docker-compose.yml.

**Comment by papey** [comment]
`network_mode: default` is not a workaround. You just destroy projects isolation when using this default mode.

**Comment by jabenninghoff** [comment]
I found a better workaround for this issue: create a new network bound to a specific IP, and instruct compose to use the external network:
`docker network create -o "com.docker.network.bridge.host_binding_ipv4"="192.168.17.1" bridge2`

Use the following `docker-compose.yml`:
```
version: "3"
services:
  test:
    image: busybox
    command: sleep 60

    ports:
      - "7560:8080"
    networks:
      - bridge2

networks:
  bridge2:
    external: true
```
I use compose v3, this may also work on v2.

**Comment by SteveEasley** [comment]
An alternate approach:

docker_compose.yml
```
version: '3'
services:
  web:
   image: nginx
   ports:
     - "${MY_DOCKER_IP:-127.0.0.1}:8080:80"```

By default, this will start the container so its not viewable externally (bound to 127.0.0.1).

If you want to expose it externally just run `export MY_DOCKER_IP=0.0.0.0` then restart your container with `docker-compose up -d --force-recreate`.

**Comment by arthurhenrique** [comment]
Changed to:
```yml
ports:
    - "0.0.0.0:8080:8080"
``` 
and it's works. 

@SteveEasley , Do you see some problem with that alteration?

**Comment by SteveEasley** [comment]
@arthurhenrique 0.0.0.0 is the default value. The point of this issue is how NOT to bind 0.0.0.0 (all interfaces).

**Comment by wrfly** [comment]
Same issue here...

**Comment by wrfly** [comment]
Add `network_mode: "bridge"` can solve this, for example:

```yaml
version: "2"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    network_mode: "bridge"
```

Because by default, docker-comose will create a new network and attach the containers to that network, and the network's IP address is not configured whitch is default "0.0.0.0".

**Comment by magodo** [comment]
What about just specify the driver option in compose like below:

```
    networks:
      foo_network:
        driver_opts:
          com.docker.network.bridge.host_binding_ipv4: "1.2.3.4"
```
