### ISSUE TITLE
`dockerfile` service value documentation wrongly states it doesn't work with `image`

### ISSUE THREAD

**Issue by triccardi-systran** [docker/compose#3019]
[`dockerfile` doc](https://docs.docker.com/compose/compose-file/#dockerfile) hasn't been updated with Compose File v2 format:

> Using dockerfile together with image is not allowed. Attempting to do so results in an error.

This is wrong for v2 format, it does work:
```yaml
version: '2'
services:
  app:
    image: redis
    build:
      dockerfile: Dockerfile
      context: .
```

```shell
$ docker-compose config
networks: {}
services:
  test:
    build:
      context: /xxx
      dockerfile: Dockerfile
    image: redis
version: '2.0'
volumes: {}

```
