### ISSUE TITLE
[service level networks key] contains an invalid type, it should be an array

### ISSUE THREAD

**Issue by schuppo** [docker/compose#3046]
I can't find the syntax error in my `docker-compose.yml`. Under `services:` it has (beneath others): 

```yml
  elasticsearch:
    image: elasticsearch:latest
    networks:
       log:
         aliases:
           - elasticsearch
```

When I  run `docker-compose up elasticsearch` I get:
`
ERROR: Validation failed in file './docker-compose.yml', reason(s):
services.elasticsearch.networks contains an invalid type, it should be an array
`

Do you have any clue?

I use `docker-compose version 1.7.0dev, build 77cf67b` due to #271 on MacOSX
