### ISSUE TITLE
Support docker --ip option in docker-compose.yml files

### ISSUE THREAD

**Issue by daniel-smith-kaazing** [docker/compose#3064]
As we work with a lot of OEMs our support and QA test scenarios often involve sets of hosts/VMs/containers that need to know each other's IP on startup. Further it would greatly simplify setup of these scenarios if the IP of each container could be fixed on startup. Please add support for the docker run --ip option in Docker compose.

**Comment by aanand** [comment]
As I understand it, the IP address is a property of a container's connection to a specific network. So it should probably be a sub-property of the config dictionary under `networks`:

```yaml
web:
  build: .
  networks:
    foo:
      ip: 1.2.3.4
    bar:
      ip: 5.6.7.8
```
