### ISSUE TITLE
Version 2 of the docker-compose.yml cause slowdowns in the reverse lookup

### ISSUE THREAD

**Issue by Lughino** [docker/compose#3072]
I'm on a OSX machine and I'm having a resolution of slowdowns problems hostname of the linked containers.

If you use the IP address connects immediately.
My specific case is this:

``` yml
version: '2'

services:
  web:
    build: ./app
    volumes:
      - "./app:/src/app"
    ports:
      - "80:3000"
    links:
      - "db:mongodb"
    command: nodemon -L app/bin/www

  db:
    image: mongo
    command:
      - --smallfiles
    ports:
      - "27017:27017"
```

When the client connects from the web container to the mongodb container (`mongodb://mongodb:27017/dockertest`) takes exactly 30 seconds.

If I remove the version 2 is connected immediately to the mongodb containers with the same settings.
