### ISSUE TITLE
Docker daemon crash, when using docker-compose up

### ISSUE THREAD

**Issue by S-YOU** [docker/compose#3093]
Following up on this issue in docker repo https://github.com/docker/docker/issues/20997
Detail info are posted in the issue too, using docker-compose 1.6.2

Following trigger docker daemon crashed everytime
```
version: '2'
services:
    app:
        image: myproject
```

But `docker run myproject` works fine, never experience crash yet.

Or, `myproject` is the problem?
