### ISSUE TITLE
Composefile v2: ERROR: 'network_mode' and 'networks' cannot be combined

### ISSUE THREAD

**Issue by ggsenger** [docker/compose#3105]
It is not possible to use `network_mode` to join the `bridge` network (as suggested in https://github.com/docker/compose/issues/3012)
in case the container needs to join both the `bridge` network and a custom network.
This use case was also discussed here https://github.com/docker/compose/issues/2701

I am using docker-compose version 1.6.0, build d99cad6 and Docker version 1.10.2, build c3959b1.

Example docker-compose.yml

```
version: '2'

services:
  debian:
    image: debian:wheezy
    network_mode: "bridge"
    networks:
      - custom
networks:
  custom:
    external:
      name: customnetwork
```
Any help with this problem would be greatly appreciated.

**Comment by dnephin** [comment]
Can you tell us more about why you need to explicitly join the bridge network?

**Comment by Anonymooseable** [comment]
Shouldn't this be possible by adding the predefined bridge network as an external one in the compose file?
```
networks:
  bridge:
    external:
      name: bridge
  custom: [...]
```
And adding `bridge` to the debian service's networks? (Not sure if this would work, but it's what I would try).
