### ISSUE TITLE
compose doesn't take node constraints into account when creating networks in a swarm

### ISSUE THREAD

**Issue by derkork** [docker/compose#3146]
I have the following compose file:

```
version: '2'
services:
  loadbalancer:
    image: some.registry/loadbalancer
    environment:
      - DOCKER_HOST=tcp://localhost:3375
      - constraint:node==epsilon
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:44304:44304"

networks:
  default:
    driver: bridge

```

Now I launch this one on my docker swarm:

```
root@epsilon:/home/vagrant# docker-compose -f /opt/compose/loadbalancer/docker-compose.yml up
Creating network "loadbalancer_default" with driver "bridge"
Creating loadbalancer_loadbalancer_1
ERROR: network loadbalancer_default not found

```

So I wondered why that might be. So i checked the networks

```
root@epsilon:/home/vagrant# docker network ls
NETWORK ID          NAME                         DRIVER
195abbbe800c        epsilon/bridge               bridge              
d0ceb15f253c        alpha/none                   null                
5848b4344156        alpha/host                   host                
51b9fa03feeb        alpha/bridge                 bridge              
57dfc8f865f9        alpha/loadbalancer_default   bridge              
f4808456bc30        epsilon/host                 host                
72af6e4e6913        epsilon/docker_gwbridge      bridge              
175b77a7ce31        alpha/docker_gwbridge        bridge              
e29f50c47110        beta/bridge                  bridge              
9d4c94a8d7a8        epsilon/none                 null           
```

So even the composefile specifically said that the application must run on the `epsilon` node, the network was created on the `alpha` node. And that's why compose didn't find it. 

I would expect that compose creates the network on the node that will actually run the container.

**Comment by aanand** [comment]
Setting aside Compose, I don't actually know if it's possible to specify a node (or any scheduling constraints) when creating a network. @vieux?

Is it a requirement that your app's network uses the `bridge` driver and exists on a single node (instead of using the default `overlay` driver and existing on all nodes)? What's the use case?

**Comment by derkork** [comment]
The app should reside on a single specific node because it's our load balancer and we need a fixed IP/Port to map the DNS names to. We don't need a overlay network for this, the `bridge` network would be sufficient. Also I had problems when creating one overlay network per app (got some 409 errors about network conflicts) so I figured I'd try a simpler approach using the the `bridge` network. 

Didn't work either. Right now I worked around the issue by creating an `overlay` network manually (through `docker network create`) and instructing compose to use that network instead of dynamically creating one. This approach seems to work though technically a `bridge` network would suffice, but I when I created a `bridge` network named `my_bridge` on `epsilon` and instruct compose to use that it complains about that `my_bridge`  doesn't exist. I guess it's because docker prepends the node name to the network for bridge networks (so the name becomes `epsilon/my_bridge`) while it doesn't do that for `overlay` networks. So i resorted to use one `overlay` network I manually created and connecting all containers to that even though they don't use the `overlay` network to communicate with each other.

**Comment by aanand** [comment]
This might work:

```yaml
networks:
  my_bridge:
    external:
      name: epsilon/my_bridge
```

Does the load balancer *need* a network of its own, though? If not, you can set `network_mode: bridge` and it'll just use `epsilon/bridge`.

**Comment by derkork** [comment]
It doesn't need an _own_ network. I'll give `network_mode` a shot.

**Comment by derkork** [comment]
Using network mode doesn't work as intended:

```
root@epsilon:/home/vagrant# docker-compose -f /opt/compose/backend/docker-compose.yml up -d
Creating backend_backend_1
ERROR: network brigde not found

```


Compose file is 

```
version: '2'
services:
  backend:
    image: theta:443/backend
    environment:
      - ENV=ptelocal
    network_mode: brigde
    ports:
      - "29819"
```

**Comment by aanand** [comment]
You'e got a typo: it should be `bridge`, not `brigde`.

**Comment by mujiburger** [comment]
I have a slightly different take on the same basic problem.  I need a user defined bridge on each node.  `network_mode: bridge` doesn't work for me because I need to be able to access the related container by hostname and the default bridge doesn't provide any hostname resolution.

If I use compose to create the network, it only creates it on one node.  When I go to scale the service out to other nodes, scale doesn't create the network on subsequent nodes and I get a `network not found` error.:
```
swarm:~/test$ cat docker-compose.yml
version: '2'
services:
  test:
    image: redis
    environment:
      - "affinity:container!=test_test*"
    networks:
      - testnet
networks:
  testnet:
    driver: bridge

swarm:~/test$ docker-compose up -d
Creating network "test_testnet" with driver "bridge"
Creating test_test_1

swarm:~/test$ docker-compose scale test=2
Creating and starting 2 ... error

ERROR: for 2  network test_testnet not found

swarm:~/test$ docker network ls
NETWORK ID          NAME                                   DRIVER
16e38fd03e3e        docker2/docker_gwbridge   bridge
190b08979c6c        docker2/bridge            bridge
93c26372be2c        docker2/none              null
d7c06a5c8af0        docker1/none              null
b95728a2cc57        docker1/bridge            bridge
15974d79db83        docker2/host              host
8dd2889c85a2        docker1/docker_gwbridge   bridge
62eb312da8d1        docker1/host              host
0c8893efa483        docker1/test_testnet      bridge
```

I tried to take network creation out of compose and create the bridge network on each node using `docker network create <node_name>/<network_name>` and ended up with a real mess.  When I run compose, it creates duplicate bridge networks on a single node for every run of compose up.  It can't connect the container to the network and fails with "ERROR: No such network: <network_name>.  Then it can't figure out how to clean up all the duplicate networks, fails to bring the networks down and I have to manually remove each duplicate network by network id instead of name.  I think the bug in this workaround is probably philosophically related to docker/swarm#1356 and #2280.  Swarm shouldn't let compose create duplicate bridge networks any more than it should allow compose to created duplicate overlay networks.  I've included more detailed information about this part of the problem in docker/swarm#1356.

If I set external_name without referencing the node, (`name: <network_name>` instead of `name: <node name>/<network name>`) I get the `declared as external, but not found` error.  I can't use multiple external names so there is no way for me to reference every node.

**Comment by derkork** [comment]
@aanand thanks, I fixed the typo and now it works using the default bridge network, which is basically what I wanted to achieve.

**Comment by nejtr0n** [comment]
I've got the same issue.
But container have to be connected to internal overlay network and to host bridge. 
Any ideas, how to make it with compose?
My compose:

 

```
haproxy1:
  container_name: haproxy1
  image: nejtr0n/haproxy
  volumes:
   - /root/compose/cloud/haproxy/haproxy.ctmpl:/templates/haproxy.ctmpl
  ports:
   - "${EXT_IP}:80:80"
   - "${EXT_IP}:443:443"
  networks:
   ferma:
    aliases: 
     - gw_front
   gw: {}
  environment:
    - "constraint:cluster_id==1"
    - "CONSUL_URL=sd:8500"

networks:
  ferma:
    external:
      true
  gw:
    driver: bridge
```

haproxy have constrain to node 1, but network gw creating on node 2
