### ISSUE TITLE
Ability to create internal networks missing

### ISSUE THREAD

**Issue by CthulhuDen** [docker/compose#3190]
I cannot find a way to specify in the docker-compose file (even v2) that a network must be internal (as if it was created with `docker network create --internal ...`).

**Comment by nejtr0n** [comment]
Same problem

**Comment by m4h3** [comment]
I did find a way to break connectivity by disabling the masquerading. But this is only disabling masquerading, packets are still going to the external network (with a bad src ip address).

```
  internal:
    driver_opts:
      com.docker.network.bridge.Internal: "true"
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
```
