### ISSUE TITLE
services with 'depends_on' cannot be extended

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/compose#3220]
Will this be supported in the future releases ?

**Comment by gingerlime** [comment]
... Not sure if this achieves the same results as `extends`, but you can use yml references to avoid copy&pasting and keeping this DRY inside your `docker-compose.yml`, e.g.

```yml
web: &web
  image: your_image
  depends_on:
    - db
  ...
web1:
  <<: *web
```

**Comment by aanand** [comment]
What are you trying to do that requires both `extends` and `depends_on`? Can it be done with [multiple Compose files](https://docs.docker.com/compose/extends/#/multiple-compose-files) instead?

**Comment by gingerlime** [comment]
I'm personally only experimenting and considering options at this stage.

I'm trying to build a zero-time rolling upgrade based on [this pattern](https://github.com/vincetse/docker-compose-zero-downtime-deployment).

Perhaps multiple compose files can also be used in this case, but I haven't tried it yet. Thanks for suggesting it.

**Comment by intellent** [comment]
Why has this been closed? May I cite the [official documentation](https://docs.docker.com/compose/extends/) here:

> Note: links, volumes_from, and depends_on are never shared between services using extends. These exceptions exist to avoid implicit dependencies—you always define links and volumes_from locally. This ensures dependencies between services are clearly visible when reading the current file. Defining these locally also ensures changes to the referenced file don’t result in breakage.

I interpret this as follows: Extending services with depends_on should work, but you have to redefine your dependencies locally. Which would totally make sense to me.

Basically all my services use depends_on and networks for orchestration since links are not recommended anymore. This renders the extends mechanism useless for me.

**Comment by krasi-georgiev** [comment]
i think I managed to achieve the same effect by using multiply compose files with the -f option

**Comment by intellent** [comment]
@krasi-georgiev You’re right. However, IMHO the current behavior renders the extends mechanism useless in a lot of cases. This could not be the intention, could it?

**Comment by krasi-georgiev** [comment]
I don't know , some of the devs should answer that

**Comment by mlovic** [comment]
I've been wondering the same thing. I had the same interpretation of the docs as @intellent. The documentation doesn't seem to match behaviour. 

Regarding @aanand's suggestion of using multiple compose files, that could work, but I think `extends` would fit much better in situations where services only slightly differ, or the same app/codebase takes on different "roles". For example:

```
web_app:
  depends_on:
    - db
  command: puma -C config/puma.yml
  ...
worker:
  extends:
    service: web_app
  command: sidekiq -C config/sidekiq.yml
```
for a Rails worker process

or
```
...
admin:
  extends:
    service: web_app
  environment:
      - ADMIN_MODE=true
```
for an Admin instance

Please let me know if there's anything I'm missing, thanks!
