### ISSUE TITLE
Partial services started/exited when images in other service is not available

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#3225]
Tried to start a multi-container application using `docker-compose.yml`:

```
version: "2"
services:
  db:
    container_name: "db"
    image: arungupta/oreilly-couchbase
    ports:
      - 8091:8091
      - 8092:8092 
      - 8093:8093 
      - 11210:11210
  web:
    image: arungupta/oreilly-wildfly
    depends_on:
      - db
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
```

Got the error:

```
docker-compose up -d
Creating network "hellojavaee_default" with the default driver
Pulling db (arungupta/oreilly-couchbase:latest)...
Pulling repository docker.io/arungupta/oreilly-couchbase
ERROR: Error: image arungupta/oreilly-couchbase not found
```

Built the image, and then tried the command again. This gave the error:

```
docker-compose up -d
Creating db
ERROR: Conflict. The name "/db" is already in use by container 1eea595a71f84e47a5b889951e950534f1b1d949666fb85a577795f0423a8a1b. You have to remove (or rename) that container to be able to reuse that name.
```

If one of the service could not be started then the containers started by other services are exited. But this does not allow to run the `docker-compose up -d` command again.
