### ISSUE TITLE
Add duplicate hosts with extra_hosts

### ISSUE THREAD

**Issue by ebuildy** [docker/compose#3230]
Consider docker-compose.yml (1.6):

```
  dns:
    image: quay.io/jpillora/dnsmasq-gui:latest
    ports:
    - "9053:53/udp"
    - "9053:53"
    - 8080:8080
    extra_hosts:
      - "rabbitmq: 172.28.0.3"
      - "rabbitmq: 172.28.0.4"
```

I would like to achieve a DNS round-robin for "rabbitmq", but after docker-compose up dns, here the /etc/hosts content:

```
127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.28.0.4  rabbitmq
172.28.5.0  c74fcb1f34ef
```

I guess extra_hosts entries are de-duplicated?

**Comment by aanand** [comment]
Yeah, looks like `docker run` with multiple `--add-host` args for the same host works as expected, so we should update Compose accordingly.

**Comment by ramyaa** [comment]
So @aanand , we cannot have duplicate entries for the same host is it? Is there any workaround for the above scenario? Basically I would want to map multiple IPs for same domain (when I use the domains, I would use different ports and that would take care of fetching the correct service.)

Thanks
Ramya

**Comment by pikanji** [comment]
My workaround is to add dummy host name in the host list to make them differ.
My case was to set host name for ip4 and ip6.
```
extra_hosts:
  - "my-domain.com:127.0.0.1"
  - "my-domain.com:::1"
```
I changed it to like below, and it worked.
```
extra_hosts:
  - "localhost4 my-domain.com:127.0.0.1"
  - "localhost6 my-domain.com:::1"
```

**Comment by ijc** [comment]
I just tried this and it seems fixed:
```console
$ cat > 3230.yaml
  dns:
    image: quay.io/jpillora/dnsmasq-gui:latest
    ports:
    - "9053:53/udp"
    - "9053:53"
    - 8080:8080
    extra_hosts:
      - "rabbitmq: 172.28.0.3"
      - "rabbitmq: 172.28.0.4"
$ docker-compose -f 3230.yaml up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Pulling dns (quay.io/jpillora/dnsmasq-gui:latest)...
latest: Pulling from jpillora/dnsmasq-gui
c0cb142e4345: Pull complete
a3ed95caeb02: Pull complete
f8fbc029fb18: Pull complete
1783c2a76161: Pull complete
f245b4af4b62: Pull complete
b333f755f71a: Pull complete
Digest: sha256:b9fa9c9b6f7e468e98df24b106679ae03a87083b2ce9109fe09ce6b0bf0f030e
Status: Downloaded newer image for quay.io/jpillora/dnsmasq-gui:latest
Creating compose_dns_1 ... done

$ docker-compose -f 3230.yaml exec dns sh -l
962151ea4691:/# cat /etc/hosts 
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
 172.28.0.3	rabbitmq
 172.28.0.4	rabbitmq
172.17.0.6	962151ea4691
```

**Comment by rfgamaral** [comment]
@ijc This is not working for me with `version: '2.2'`. My use case is similar to the user above, set 1 hostname for an IPv4 and IPv6 addresses.

**Comment by dgtlmoon** [comment]
For performing round-robbin type dns @pikanji  @ijc I can confirm that what @rfgamaral writes is true, your solution does NOT work

@aanand @ebuildy maybe some mismatch in expectations here? round-robbin type resolution doesnt work (probably not a docker issue, because docker-compose is only adding entries to /etc/hosts and not giving an actual DNS server for this suggested solution)

```
version: '2'
services:

  browser-squid:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: python
    command: sleep 400
    extra_hosts:
      - "test:222.222.222.222"
      - "test:111.111.111.111"
```

```
root@4468192e501d:/# ping test
PING test (222.222.222.222) 56(84) bytes of data.
root@4468192e501d:/# ping test
PING test (222.222.222.222) 56(84) bytes of data.
root@4468192e501d:/# ping test
PING test (222.222.222.222) 56(84) bytes of data.

root@4468192e501d:/# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
222.222.222.222 test
111.111.111.111 test
172.18.0.2      4468192e501d
```




Versions

```
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.21.0, build unknown
```
