### ISSUE TITLE
compose-file network documentation seems to be wrong

### ISSUE THREAD

**Issue by Hendrik-H** [docker/compose#3238]
On https://docs.docker.com/compose/compose-file/#networks networks are specified as:
```yml
networks:
  - some-network
  - other-network
```
Using `docker-compose version 1.6.2, build 4d72027` and a version 2 file I get this error:
```
ERROR: In file './docker-compose.yml', network must be a mapping, not an array.
```

The correct syntax seems to be:
```yml
networks:
  some-network:
  other-network:
```

**Comment by aanand** [comment]
It's confusing, but there are two different `networks` keys:

- `networks` at the top-level of the Compose file. This must always be a mapping.
- `networks` inside a service definition. This can be a mapping or an array.

Here's an example:

```yaml
version: "2"

services:
  web:
    build: .
    networks:
      - foo

networks:
  foo:
```
