### ISSUE TITLE
Misleading error message for volumes_from

### ISSUE THREAD

**Issue by gittycat** [docker/compose#3260]
Issue #3144 shows a sample where docker can't tell whether we're trying to mount a volume from a service or a container: 

```
    volumes_from:
      - vault
```

However, the error message states that `vault` is neither a services nor a container.

```
ERROR: Service "app" mounts volumes from "vault", which is not the name of a service or container.
```

which is incorrect. Vault is a container in this case and the following works.

```
    volumes_from:
      - container:vault
```

This kind of incorrect error message makes me lose quite a lot of time. The error messages should instead say something like
"ERROR: Service "app" mounts volumes from unknown "vault". "vault" is either not a service or container or it is a container in which case you need to use "container:vault" for the name.

**Comment by cordoval** [comment]
I am running into this now and i have added the container: part without luck

```
version: '2'

networks:
  h_main:
    external: true

services:
  importer:
    container_name: importer
    image: h/imports3
    env_file:
      - /data/deploy.env
    networks:
      - h_main
    volumes_from:
      - container:data
```
maybe because data is a data container?
