### ISSUE TITLE
Missing environment variables and Link references in HostConfig when linking containers

### ISSUE THREAD

**Issue by MichaelHindley** [docker/compose#3268]
As per https://docs.docker.com/v1.9/compose/env/
![image](https://cloud.githubusercontent.com/assets/1016639/14276487/5957bfb0-fb1f-11e5-8f0f-75d42c9b730c.png)

Using this file

``` yml
version: '2'

services:
    legacyBackend:
        image: someimage:latest
        volumes:
            - /var/www/backend
        ports:
            - "8100:80"
            - "8101:81"
            - "3315:3306"
        tty: true

    app:
        image: anotherimage:latest
        links:
            - legacyBackend
        volumes:
            - /var/www/app
        ports:
            - "8104:4200"
        tty: true

```

I would expect `$APP_PORT` to be a available env variable inside the legacyBackend service, and I would expect `$LEGACYBACKEND_PORT` to be available inside the app service.

![image](https://cloud.githubusercontent.com/assets/1016639/14276613/d3edf05a-fb1f-11e5-9838-1860e166f722.png)

Which as you can see in the image above, is not the case.

You can however ping the `app` service:

![image](https://cloud.githubusercontent.com/assets/1016639/14276641/ece60a20-fb1f-11e5-9166-6744697a6e9b.png)

But you cant echo it to get a IP:

![image](https://cloud.githubusercontent.com/assets/1016639/14276678/0d42dbae-fb20-11e5-97b3-34c5074efb0e.png)

Listing the env variables:

![image](https://cloud.githubusercontent.com/assets/1016639/14276781/7883d620-fb20-11e5-970f-8211b7bc5322.png)

Using inspect, the "Links" value is null, alltough they are clearly defined in docker-compose.yml and they work with the ping command:

![image](https://cloud.githubusercontent.com/assets/1016639/14277009/833a0c8c-fb21-11e5-908f-55fc36693662.png)

I'm not sure how I can get a linked containers network address when the documented env variables are not available. A common use case is for REST based mobile apps, where you need to `sed` config files with correct ip's in a local environment setup.
