### ISSUE TITLE
Strange behavior with fig/seems to work fine with docker

### ISSUE THREAD

**Issue by pmlopes** [docker/compose#328]
Hi,

I've a simple container where i want to check some logging functionality, here is my Docker file:

```
FROM ubuntu:14.04
MAINTAINER Paulo Lopes "my@email"
ADD syslog_tester /bin/syslog_tester
CMD /bin/syslog_tester
```

My fig.yml is:

```
app:
  build: .
  volumes:
    - /dev/log:/dev/log
```

and for the sake of it the syslog_tester source code is:

```
#include <syslog.h>

int main() {
  openlog("docker-syslog-tester", LOG_PID, LOG_USER);
  syslog(LOG_INFO, "Sample log message");
  closelog();
  return 0;
}
```

Now i build the container as usual:

```
sudo fig build
```

and if i run it from docker:

```
sudo docker run -v /dev/log:/dev/log logging_app
```

always works, however if i do:

```
sudo fig up
```

about 50% of the time i get:

```
Recreating logging_app_1...
Cannot start container d3a0422f77c1cadcc2b14ebaa7418864d292eca732e6ae487f5779981a7e8223: stat /var/lib/docker/aufs/mnt/14dc4061f945e9293c5817624a65c94aade73d547e5b3e0cbd6cb15f228c9c45/dev/log: no such file or directory
```

my fig version is 0.5.0 and docker 1.1.1 on ubuntu 14.04 64bit

**Comment by Glideh** [comment]
Not sure it is related but I seem to have the issue (Debian, docker 1.8.1, docker-compose 1.4.0).

```
$ docker run --volume /absolute/path/to/my/app/:/app/ python:2.7.8\
    cat /app/requirements.txt

Django==1.7.6
Pillow==2.4.0
argparse==1.2.1
django-annoying==0.7.9
django-appconf==0.6
django-avatar==2.0
django-bootstrap-form==3.1
...
```

```
$ cat Dockerfile

FROM python:2.7.8
RUN cat /app/requirements.txt
```

```
$ cat docker-compose.yml

web:
    build: .
    volumes:
        - .:/app/
```

```
$ docker-compose build

Building web...
Step 0 : FROM python:2.7.8
 ---> 481b175a31db
Step 1 : RUN cat /app/requirements.txt
 ---> Running in bf9e87fc1630
cat: /app/requirements.txt: No such file or directory
```

**Comment by dnephin** [comment]
These are not equivalent. The `Dockerfile` is wrong, you never add files. The equivalent `docker-compose.yml` would be:

```yaml
web:
  image:  python:2.7.8
  volumes:
    - /absolute/path/to/my/app/:/app/
  command: cat /app/requirements.txt
```

**Comment by Glideh** [comment]
This works
```yml
web:
    image: python:2.7.8
    volumes:
        - .:/app/
    command: cat /app/requirements.txt
```

This does not
```
$ docker run --volume .:/app/ python:2.7.8 cat /app/requirements.txt
```
