### ISSUE TITLE
docker-compose Issue with Volumes based on Docker Machine Root (`/`)

### ISSUE THREAD

**Issue by jamiejackson** [docker/compose#3285]
* Windows 7 host
* Boot2Docker version 1.10.3, build master : 625117e - Thu Mar 10 22:09:02 UTC 2016
* Docker version 1.10.3, build 20f81dd
* docker-compose version 1.6.2, build e80fc83
* docker-machine version 0.6.0, build e27fb87

I'm running `docker-compose up -d` with the following:

```yaml
cadvisor:
  image: google/cadvisor
  ports:
    - "8080:8080"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
```

This yields:
```
C:\www\nmc_docker>docker-compose up -d
Recreating d3a4e7a0de45_d3a4e7a0de45_d3a4e7a0de45_d3a4e7a0de45_d3a4e7a0de45_d3a4e7a0de45_nmcdocker_cadvisor_1
←[31mERROR←[0m: Invalid volume spec "ro": volumeabs: Invalid volume destination path: 'ro' mount path must be absolute.
```

The equivalent `docker run` works from both Windows and in an SSH session in the docker machine.

I'm brand-new to docker-machine & docker-compose, so I might be doing something wrong.

**Comment by dnephin** [comment]
I think what's happening is that `"/:/rootfs:ro"` if confusing our parsing of windows paths.

If you're using `docker-compose` on windows, you should use host paths that contain `c:\` or the appropriate drive. Can you try `c:\:/rootfs:ro` and see if that works?

If you're trying to point VM paths, I think you might need to run Compose from the VM.

**Comment by jamiejackson** [comment]
> If you're using docker-compose on windows, you should use host paths that contain c:\ or the appropriate drive. Can you try c:\:/rootfs:ro and see if that works?

I think that's incorrect. On Windows and Mac hosts, I don't believe you are ever to specify actual host paths, but rather paths on the docker machine (VM). I know that there are implicit vbox shares, `/c/Users` and `/Users/<username>` for Windows and OSX, respectively, but these paths are only available to containers by virtue of their existence (mounts) on the docker machine.

> If you're trying to point VM paths, I think you might need to run Compose from the VM.

Compose doesn't run in boot2docker, as far as I know.

I have limited experience with docker-machine, but I do know that when I've specified these volume mounts for other containers in `docker-compose.yml`, the first path is on the *docker machine*, not the Windows host.

For example, in the following, `/nmc/src` is not a path on the *host*; rather, it's a path on the *docker machine* (VM), and it works as expected.

```yml
php:
  image: nmcteam/php56
  volumes:
    - /nmc/src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - /nmc/src:/var/www
  expose:
    - 9000
  links:
    - db
```

**Comment by jamiejackson** [comment]
Sorry, I think I'm wrong about at least part of my reply. I'll come back to this after I get to the office.

**Comment by jamiejackson** [comment]
> I think what's happening is that "/:/rootfs:ro" is confusing our parsing of windows paths.

I think you're right. I think it thinks the first `/` is to interpreted as a Windows path. I *think* that should be considered a bug, as it makes `/` behave differently than all other paths. It seems to make it impossible to create a volume from the docker machine root (as cadvisor seems to want).

To clarify the current behavior with some examples:

| Argument | Shows/Works in Container? | Resulting Source | Resulting Target | Notes |
|---|-----|----|----|---|
| `"c:/:/tmp/c_colon_slash"` | true | docker_machine:`/c` | docker_container:`/tmp/c_colon_slash` | Of course since the real mount is from host:`c:\Users` to docker_machine`:/c/Users`, so no siblings directories of `Users` are available, but the mechanism still makes sense to me.  |
| `"/:/tmp/slash"` | false | N/A | N/A | This doesn't seem to make sense. How else would one mount the docker machine's root to the docker container (as cadvisor seems to want)? |
| `"/c/:/tmp/slash_c_slash"` | true | docker_machine:`/c` | docker_container:`/tmp/slash_c_slash` | The behavior is the same as that of `"c:/:/tmp/c_colon_slash"`. This makes sense. |
| `"/tmp:/tmp/slash_tmp"` | true | docker_machine:`/tmp` | docker_container: `/tmp/slash_tmp` | This is straightforward and expected. |

**Comment by jamiejackson** [comment]
> If you're using docker-compose on windows, you should use host paths that contain `c:\` or the appropriate drive. Can you try `c:\:/rootfs:ro` and see if that works?

The backslash has to be escaped, so `c:\\:/rootfs:ro` does yield a docker container volume (at `/rootfs`), but of course I don't want the host's root as the source; instead, I want the docker machine's (VM's) root.

**Comment by jamiejackson** [comment]
I think I have an workaround hack. If I specify `/../` instead of `/`, I seem to get the behavior I want.

This works:

```yaml
cadvisor:
  image: google/cadvisor
  ports:
    - "8081:8080"
  volumes:
    - "/../:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
```

However, I think that `/` *ought* to work.
