### ISSUE TITLE
How to tell nginx to look up a container's IP dynamically so it can be restarted without needing to also restart nginx container?

### ISSUE THREAD

**Issue by blah238** [docker/compose#3314]
I am using Compose 1.7.0-rc2 and the V2 compose file format. No explicit network defined, just the default networking.

I have a backend container running Node.js and an Nginx container set up to proxy_pass requests to the backend container.

This all works fine except if I restart the backend container. Then it seems the backend's IP changes, but Nginx continues to use the old IP.

I have gone down the rabbit hole of trying to figure out how to get Nginx to resolve the IP dynamically, but the complexity skyrockets quickly, and nothing specific to V2 compose files has apparently been written.

Is there a **simple** and up-to-date way of accomplishing this apparently monumental task?

**Comment by dnephin** [comment]
I believe this is a known issue with nginx. It caches the DNS queries when it starts and never tries them again. This is why people have been developing alternative proxies/load balancers for use with containers. One example is https://github.com/containous/traefik

**Comment by blah238** [comment]
Thanks for the tip @dnephin, it looks interesting. At first glance it doesn't seem to support serving static files though. I suppose there is probably something else to fill that gap as well though.

**Comment by blah238** [comment]
Well this is the simplest thing I could come up with. Not dynamic or scaleable in any way, I just set a static IP for the backend:

```yml
version: '2'
services:
  backend:
    command: node app.js
    networks:
      app_net:
        ipv4_address: 172.18.0.2
  nginx:
    build: ./nginx
    ports:
     - "80:80"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
```

Now restarting the backend doesn't require restarting Nginx as well.

Hoping for a nicer pattern in the future!
