### ISSUE TITLE
when using multiple networks, can't bind ports publicly

### ISSUE THREAD

**Issue by choobs-dev** [docker/compose#3318]
I setup a bunch of different web services in diffferent docker-compose.yml, and now I'm trying to put a reverse proxy in front of them using nginx as a compose service. To connect them together I'm using networks (external) and external links. The problem is that the nginx service is not responding on ports 80/443 publicly, however if I add a second nginx service inside the same docker-compose.yml I can answer on nginx1 proxy to nginx2 and then proxy to my external services.

Here is my docker-compose.yml:
```yml
version: '2'
services:
  lb:
    restart: always
    image: nginx:alpine
    volumes:
      - ./lb.conf:/etc/nginx/conf.d/default.conf
      - ./lb-nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - nginx:frontend
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/certs:ro
    networks:
      - default # required or you won't be able to talk to the outside
      - minio
      - pinba
      - registry
    external_links:
      - "minio_minio_1:minio"
      - "pinba_pinboard_1:pinboard"
      - "registry_registry-ui_1:registry-ui"
networks:
  minio:
    external:
      name: minio_default
  pinba:
    external:
     name: pinba_default
  registry:
    external:
      name: registry_default
```

***This is the part not working as I expected:***
```yml
    networks:
      - default # required or you won't be able to talk to the outside
```

The version above works, but if I try to remove ``lb`` and add ``ports`` *80/433* to ``nginx``, I can't access the services publicly.

Also I tried with ``ufw`` enabled and disabled.

------------------------------------------------------------------------------------------------------------------------------

My docker version:
```
Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

Docker compose version:
```
docker-compose version 1.7.0rc1, build 1ad8866
docker-py version: 1.8.0-rc2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

Running on Ubuntu 14.04.4 LTS
```
Linux dev-ubuntu-1 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
