### ISSUE TITLE
Unable to over ride project name concatination to network name from within docker-compose.yml

### ISSUE THREAD

**Issue by ljones-cbnl** [docker/compose#3323]
If I set up a network using the "docker network" cli command:
```
docker network create --subnet=192.168.2.0/24 --gateway=192.168.2.254 \
--ip-range=192.168.2.0/24 -o "com.docker.network.bridge.name"="house_lan" house_lan
```

I get a network called "house_lan".

If I try and simulate this command with docker-compose.yml entries:

```
networks:
  house_lan:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "house_lan"
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          iprange: 192.168.2.0/24
          gateway: 192.168.2.25
```
I get a network called "dockernetworking2_house_lan" which is to be expected given docker-composes scaling features. The directory in this instance is docker-networking-2. 

How do I over ride this project naming feature to create a named network, is there a network_name item similar to the services container_name or some other way of ensuring the network name has no project attached to the front?

**Comment by dnephin** [comment]
You can use `external: name: ...` https://docs.docker.com/compose/compose-file/#external-1

However, you will be responsible for creating it. Compose will not manage external networks.

**Comment by ljones-cbnl** [comment]
You have confirmed that docker-compose has not got all of the use case solutions that I can perform with the other docker commands. 
As you say, I can use a separate OS trigger to run the above docker network command and have a named network and then declare that named network external in all of my docker-compose.yml files.
```
networks:
  house_lan:
    external:
      name: house_lan
```
I would have liked to be able to create this named bridge in a single docker command at container instantiation and then have other compose container know about it, without having to resort to OS scripts to extract it out of inspect commands.

Thank you for your response. If you think that this could become a feature request then leave it open, otherwise your response has confirmed my understanding and the issue can be closed.

**Comment by ljones-cbnl** [comment]
OK, as an update I have worked around my problem by making my project house1, in other words storing my files in a directory called house1 and using the following config:
```
networks:
  lan:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "house1_lan"
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
          iprange: 192.168.2.0/24
          gateway: 192.168.2.254
```
Then I can link to it in other containers using:
```
services:
  redis:
    restart: always
    container_name: redis
    image: redis
    networks:
      house1_lan:
        ipv4_address: 192.168.2.3

networks:
  house1_lan:
    external:
      name: house1_lan
```

Thank you for your help you can close this issue.
