### ISSUE TITLE
Add support for docker run --group-add option

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#3328]
For container to access host docker daemon, I use to bind mount `/var/run/docker.sock` and `docker` executable. But then I also need to add `docker` group to the container user so it can access the socket. For this purpose I use docker run `--group-add` option, but can't find how to do the same with docker-compose.

**Comment by pwFoo** [comment]
Any 	schedule to add "--group-add" to docker-compose?

**Comment by Knetic** [comment]
I needed this too for shared volumes with different users, and took a crack at it with PR #3709.

**Comment by pwFoo** [comment]
Thanks, @Knetic !
I'll follow #3709

**Comment by arno01** [comment]
It was merged and is available in 1.9.0-rc4 https://github.com/docker/compose/releases :-]
I think this issue can be closed.

**Comment by psoares** [comment]
I couldn't get this to work. The documentation seems wrong : it displays a snippet like this : 

```yaml
version: '2'
services:
    image: alpine
    group_add:
      - mail
```
Running docker-compose with this returns `Unsupported config option for services: 'group_add'`

I tried this too : 
```yaml
version: '2'
services:
    myservice:
        image: alpine
        group_add:
          - mail
```
Running docker-compose with this returns `Unsupported config option for services.myservice: 'group_add'`

Is the option available somehow and the bug is just in the documentation ?
