### ISSUE TITLE
Use volume as temporary(not persist)

### ISSUE THREAD

**Issue by bernex** [docker/compose#3344]
Hi! I'm using docker-compose, I wanna start mysql with volume(hello for example). And I wanna drop all changes after stopping.... For running tests. I make changes stop & start - changes here. How to do it?

```
localdb2:
  image: mysql:5.6.27
  volumes:
     - hello:/var/lib/mysql
```
