### ISSUE TITLE
Multiple nodes constraint fails

### ISSUE THREAD

**Issue by nejtr0n** [docker/compose#3353]
Hello.
I have 2 nodes with same label "all=all":

```
/usr/bin/docker daemon -H tcp://10.0.0.2:2375 -H unix:///var/run/docker.sock --cluster-store=consul://10.0.0.2:8500 --cluster-advertise=10.0.0.2:2376 --label dc=dc1 --label phy=phy1 --label cluster_id=2 --label all=all --dns=10.0.0.2
/usr/bin/docker daemon -H tcp://10.0.0.3:2375 -H unix:///var/run/docker.sock --cluster-store=consul://10.0.0.3:8500 --cluster-advertise=10.0.0.3:2376 --label dc=dc1 --label phy=phy2 --label cluster_id=3 --label all=all --dns=10.0.0.3
```

When im runnig container with constraint all=all,
it only appears on one node.

```
 registrator:
  command: -internal consul://consul:8500
  image: gliderlabs/registrator:master
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock:ro"
  networks:
   - ferma
  environment:
   - "constraint:all==all"
```

```
Docker version 1.11.0, build 4dc5990
Docker-compose version 1.7.0, build 0d7bf73 
Swarm version 1.1.3 (7e9c6bd)
```
