### ISSUE TITLE
Docker Compose Reschedule problems

### ISSUE THREAD

**Issue by vfarcic** [docker/compose#3378]
Is the new Swarm reschedule feature working with Docker Compose? If it is, what should be the syntax?

I tried the following:

``` bash
docker-compose \
    -f docker-compose-demo.yml \
    -p books-ms \
    up -d app

docker-compose \
    -f docker-compose-demo.yml \
    -p books-ms \
    scale app=3

docker-machine rm -f swarm-node-2

docker logs swarm-agent-master
```

The logs output is:

```
time="2016-04-26T01:50:41Z" level=info msg="Removed Engine swarm-node-2" 
time="2016-04-26T01:50:41Z" level=info msg="Rescheduled container 25384fd14b052c67066c4073ca990205c402c3c6450cae642a624b78c0f1eb62 from swarm-node-2 to swarm-node-1 as 554576586a25ed1e1cb2282e9139e84e38b8d8b9704db92c7fd7d9d53a200f78" 
time="2016-04-26T01:50:41Z" level=info msg="Container 25384fd14b052c67066c4073ca990205c402c3c6450cae642a624b78c0f1eb62 was running, starting container 554576586a25ed1e1cb2282e9139e84e38b8d8b9704db92c7fd7d9d53a200f78" 
time="2016-04-26T01:50:41Z" level=error msg="Failed to start rescheduled container 554576586a25ed1e1cb2282e9139e84e38b8d8b9704db92c7fd7d9d53a200f78: 500 Internal Server Error: service endpoint with name booksms_app_3 already exists\n" 
time="2016-04-26T01:51:02Z" level=error msg="HTTP error: No such container booksms_app_4" status=404 
```

The compose file is in https://gist.github.com/vfarcic/02cf5809efe84b82c9ca73180b50c66f .

**Comment by vfarcic** [comment]
This is probably the same problem as docker/swarm#2133.

**Comment by igrcic** [comment]
Hi Viktor,

i was just testing the same feature here. I have copied the config snippet from your dockerfile

```yaml
    environment:                                                                                                                                                                                                                                                                                                                                                            
      - reschedule=on-node-failure                                                                                                                                                                                                                                                                                                                                          
    labels:                                                                                                                                                                                                                                                                                               
      com.docker.swarm.reschedule-policies: "[\"on-node-failure\"]
```
It is working as it should for me:
```
time="2016-05-23T09:40:13Z" level=error msg="Flagging engine as unhealthy. Connect failed 3 times" id="..." name=host1
time="2016-05-23T09:40:13Z" level=info msg="Rescheduled container ...from host1 to host2 as new_id" 
time="2016-05-23T09:40:18Z" level=info msg="Removed Engine host1" 
```

```
l$ docker --version                                                                                                                                                                                                                                                                                                                      
Docker version 1.11.1, build 5604cbe

Server Version: swarm/1.2.2
```
