### ISSUE TITLE
No variable substitution on top level networks name

### ISSUE THREAD

**Issue by overmike** [docker/compose#3443]
It is great to have variable substitution in compose file, but is that possible to have a pre-defined docker network as an variable in top level networks declaration?

e.g. this compose file doesn't work, this gives service using undefined network
```
version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    networks:
      - ${front}

  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - ${back}
volumes:
  redis-data:
    driver: local
networks:
  ${back}:
    driver: external
  ${front}:
    driver: external
```

**Comment by bechtoldt** [comment]
It would be great to be able to use variables in all key definitions, so far it works for values only, therefor I have to replace ``{{ }}`` constants using ``ed`` manually before running docker-compose..


```
  {{ CONTAINER_NAME_PREFIX }}-smtp_int_out:
    image: registry.de:5000/org/generic_smtp_int_out:${CONTAINER_SMTP_INT_OUT_IMAGE_TAG}
    tty: true
    volumes_from:
      - {{ CONTAINER_NAME_PREFIX }}-rsyslog
    container_name: {{ CONTAINER_NAME_PREFIX }}-smtp_int_out
    networks:
      buildslaves_private:
        aliases:
          - smtp-int-out.{{ CONTAINER_DOMAIN }}
```
