### ISSUE TITLE
"extends:" command requires "file:" when reading from stdin

### ISSUE THREAD

**Issue by dansteen** [docker/compose#3456]
Given the following config file:

```
version: '2'
services:
  # spin up our app
  org-api.app.local:
    image: org-api:composer
    volumes:
      - ./logs:/var/log/orgs

  build-org-api.app.local:
    extends: org-api.app.local
    image: org-api:composer
    build:
      context: .
      args:
        - VAULT_TOKEN
        - APP_VERSION
```

This works:
```
 docker-compose -f /tmp/test build
```

But this:
```
cat /tmp/test |docker-compose -f - build
```
results in the following error:
```
ERROR: Invalid 'extends' configuration for build-org-api.app.local: you need to specify a 'file', e.g. 'file: something.yml'
```

Thanks!
