### ISSUE TITLE
If multiple networks are specified port mapping fails

### ISSUE THREAD

**Issue by rizotas** [docker/compose#3484]
Here’s an example Compose file defining two custom networks:

basic.yml

```
version: '2'

services:
  proxy:
    build: ./proxy
    networks:
      - front
  app:
    build: ./app
    networks:
      - front
      - back
  db:
    image: postgres
    networks:
      - back

networks:
  front:
    external:
      name: front_network
  back:
    external:
      name: back_network
```

basic.dev.yml

```
version: '2'

services:
app:
   ports:
     - "80:8080"
```

When `docker-compose -f basic.yml -f basic.dev.yml up` is executed, the mapping no works
but, when `create` and later `start` are executed, the mapping works.... or maybe not

**Comment by vr** [comment]
looks like ports mapping don't work when you use "external" networks definition, i experience this too

**Comment by aanand** [comment]
I'm trying to reproduce, and I've started by reducing the case. This YAML file works fine for me - I can access nginx `localhost:8000`.

```yaml
version: '2'

services:
  app:
    image: nginx
    ports:
      - "8000:80"
    networks:
      - front
      - back

networks:
  front:
    external:
      name: front_network
  back:
    external:
      name: back_network
```

Does it work for you too?
