### ISSUE TITLE
pull requires valid build path

### ISSUE THREAD

**Issue by tanmayambre** [docker/compose#3513]
```
docker-compose version
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

```

I have a docker-compose file 

```
version: '2'
services:
    xyzservice:
    image: xxx-image
    container_name: xxx_container
    build:
      context: ./somecontext
      dockerfile: Dockerfile.xxx
    networks:
      - some-network

```

When I want to build the image using `docker-compose build`, I understand that the **_Dockerfile.xxx**_ is absolutely required.

But if I just want to pull the image using `docker-compose pull` why is the **Dockerfile.xxx** required?

I get the following error on pull command

```
ERROR: build path ./somecontext either does not exist, is not accessible, or is not a valid URL.
```

**Comment by shin-** [comment]
You don't need the `build` section if you're just going to pull the image. Your compose file should be

```yaml
version: '2'
services:
    xyzservice:
    image: xxx-image
    container_name: xxx_container
    networks:
      - some-network

```

**Comment by tanmayambre** [comment]
Thanks,
My scenario is the developer requires the buildpath to build & push the container while if someone wants to just run the container without build just pulling mage using same compose file.

**Comment by fvanderbiest** [comment]
This issue is annoying for our [use case](https://github.com/georchestra/georchestra/blob/16.12/docs/docker.md) where the compose file is used both to build and run the app. Valid build paths should **not** be required to run `docker pull` IMO.

**Comment by jeserkin** [comment]
@shin- does what if I am getting it without `build` section?
My `docker-compose.yml` is as follows:
```yml
version: "3"
services:
  app:
	image: busybox
    networks:
      - backend
  db:
    #image: postgres
	image: busybox
    networks:
      - backend

networks:
  backend:
    # Use a custom driver which takes special options
    driver: bridge
```
