### ISSUE TITLE
Build path issue with multiple docker-compose.yml files

### ISSUE THREAD

**Issue by pszczekutowicz** [docker/compose#3530]
Hi

I have following example structure of project:

``` bash
.
├── app1
│   ├── docker-compose.yml
│   ├── service1
│   │   └── Dockerfile
│   └── service2
│       └── Dockerfile
└── app2
    ├── docker-compose.yml
    └── service3
        └── Dockerfile
```

with files:

app1/docker-compose.yml

``` yml
version: '2'
services:
  service1:
    build:
      context: ./service1
    image: service1
  service2:
    build:
      context: ./service2
    image: service2

networks:
  default:
    driver: bridge
```

app2/docker-compose.yml

``` yml
version: '2'
services:
  service3:
    build:
      context: ./service3
    image: service3

networks:
  default:
    driver: bridge
```

all Dockerfiles contents looks like this:

```
FROM alpine:latest
```

When I try to run following command:

``` bash
docker-compose -f app1/docker-compose.yml -f app2/docker-compose.yml  config
```

I get:

``` bash
ERROR: build path /path/to/project/app1/service3 either does not exist, is not accessible, or is not a valid URL.
```

I expect that context for service3 is taken from app2/service3.

I use:

``` bash
$ docker-compose -v
docker-compose version 1.7.1, build 0a9ab35
```

``` bash
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**Comment by johnharris85** [comment]
I'd need to do a little more checking, but compose files are not equal here. Passing multiple doesn't mean "do all of these things independently", it means "take this _primary_ definition, and apply overrides". Therefore my guess would be that context is taken from the primary, and it's trying to 'merge' `service3` in `app2/docker-compose.yml` into `app1/docker-compose.yml` before running compose _using app1's context_ (as it's the 'primary'). 

This is intended behavior right now I believe (as I said, primary and overrides, rather than independent siblings).

**Comment by shin-** [comment]
What @johnharris85 wrote is correct!
Related to #3219

**Comment by pszczekutowicz** [comment]
Thank you for information. According to [context documentation](https://docs.docker.com/compose/compose-file/#context) which says that relative path is interpreted as relative to the location of the Compose file I was expecting that it is relative to Compose file in which it is defined or at least relative to its first occurrence (as service3 is defined in app2/docker-compose.yml and does not exists in app1/docker-compose.yml).

Do you think it may be possible do add some ability to change that behavior? I can imagine predefined variable `${DIRNAME}` which will contain path to current Compose file. It will allow to keep current behavior and allow to force location of context.

app2/docker-compose.yml
```
version: '2'
services:
  service3:
    build:
      context: ${DIRNAME}/service3
    image: service3

networks:
  default:
    driver: bridge
```
