### ISSUE TITLE
Feature: inline file

### ISSUE THREAD

**Issue by pierreozoux** [docker/compose#3538]
I create a [lot of compose file](https://github.com/indiehosters/) that I hope are useful for the community.
I'd like to find a way for docker to officially ship these compose files.

There is one issue that IMHO is blocking us of doing so, is the ability to ship a file in docker-compose.
Indeed, what distinguish a `piwik` from an `ownCloud` from a `WordPress` compose file is only the nginx configuration.

There are 3 way that I know to ship this configuration:
## The first option: a file on the host:

```
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
```
## The second option: the current inline way:

```
web:
  image: nginx
  volumes:
    - ./data:/var/www/html
  command: |
    bash -c 'bash -s <<EOF
      cat > /etc/nginx/nginx.conf <<EON
        daemon off;
        user www-data;
        events {
          worker_connections 768;
        }
        http {
          gzip on;
          gzip_disable "msie6";
          include /etc/nginx/mime.types;
          server {
            listen 80;
            root /var/www/html;
            index index.html;
          }
        }
    EON
    nginx
    EOF'
```

A bit dirty
## The 3rd way: inline file

```
web:
  image: nginx
  volumes:
    - ./data:/var/www/html
  files:
    -   owner: root:root
        path: /etc/nginx/nginx.conf
        permissions: '0644'
        content: |
         user www-data;
          events {
            worker_connections 768;
          }
          http {
            gzip on;
            gzip_disable "msie6";
            include /etc/nginx/mime.types;
            server {
              listen 80;
              root /var/www/html;
              index index.html;
            }
          }
```

And so, I'm sure you see the value to have a proper way to add inline file.

The syntax could be similar to what [cloudinit](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#writing-out-arbitrary-files) does.

With this, it would become easier to ship one compose file with everything included to get started an app!

**Comment by bweston92** [comment]
Would also help not over-engineering something. I have to use Docker configs for snippets of configuration when really it would be easier/portable in a single YAML file.


So for [configs](https://docs.docker.com/compose/compose-file/#short-syntax
) you could have something as follows:

```
version: '3.3'
services:
  postgresql:
    image: postgresql
    configs:
      - target: /redis_config
        uid: '103'
        gid: '103'
        mode: 0440
        content: |
        cat <<EOF > /etc/postgresql
          myconfig: $(YOU)
          value: $(CAN) 
          other: $(TEMPLATIZE)
        EOF
```

**Comment by Fridus** [comment]
@shin- Hi, any solution ?

**Comment by shin-** [comment]
@Fridus Check out https://github.com/docker/app !

**Comment by ijc** [comment]
Issue grooming: I think I agree with @shin- that this sounds more like a docker-app thing.

**Comment by adams-family** [comment]
+1

I'd like that, too!

**Comment by brunocascio** [comment]
Me too here :(

**Comment by MrBuddyCasino** [comment]
Inline files would also make it much easier to run docker compose on a remote host. Since docker app isn't a thing anymore, maybe reconsider closing this issue?

**Comment by wauwau0977** [comment]
Would like that too... k8s offers that as well, would like to see it in docker compose.

**Comment by dmckernanacv** [comment]
Bumping this, hard to believe it's not a thing, would be extremely useful.

**Comment by ezk84** [comment]
+1. This would be useful.

**Comment by Mimikoo** [comment]
Any info on this?

**Comment by srstsavage** [comment]
https://github.com/compose-spec/compose-spec/issues/346

**Comment by bergkvist** [comment]
This is available in `Docker Compose version 2.23.1` now.

```yml
name: config-inline
services:
  service:
    image: ubuntu
    entrypoint: cat
    command: /path/to/config.txt
    configs:
      - source: config.txt
        target: /path/to/config.txt
configs:
  config.txt:
    content: |
      strawberry fields forever
```

Output:
```
$ docker-compose up
[+] Building 0.0s (0/0)                                                                   docker:default
[+] Running 2/0
 ✔ Network config-inline_default      Created                                                       0.0s 
 ✔ Container config-inline-service-1  Created                                                       0.0s 
Attaching to service-1
service-1  | strawberry fields forever
service-1 exited with code 0
```
