### ISSUE TITLE
multiple affinity constraints not honored

### ISSUE THREAD

**Issue by nicolaka** [docker/compose#3544]
when I have multiple swarm affinity constraints with same key, compose is not passing all of them as envs but instead using the last one on entered.

docker-compose.yml sample:

```
version: "2"

services:
 app:
  image: busybox
  command: /bin/sh
  environment:
   - affinity:container!=consul
   - affinity:container!=nginx
```

docker-compose --verbose up -d :

```
u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/sh'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'affinity:container!=nginx'],
             u'Hostname': u'0d5c1a7ad103',
```

**Comment by nicolaka** [comment]
Docker engine requires env keys to be unique and therefore this is by design. Providing multiple envs with same key will result in overwriting the value.

**Comment by carlochess** [comment]
I think that the solution might be [this](https://github.com/google/re2/wiki/Syntax). 

```
version: "2"

services:
 app:
  image: busybox
  command: /bin/sh
  environment:
   - "affinity:container!=(*consul*|*nginx*)"
```
