### ISSUE TITLE
Add a description field to services

### ISSUE THREAD

**Issue by pyros2097** [docker/compose#3628]
I would be nice to have a description field in the services so that users can just read the docker-compose yml and understand what each service does. Something like this,

``` yml
version: '2'
services:
   prodDBUI:
    description: To access the production db
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
   cleanImages:
    description: To cleanup artifacts left by docker
    image: pyros2097/web
    command: clean.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Right now I need to document what these services do in a separate readme.

**Comment by shin-** [comment]
Why not use comments?

**Comment by pyros2097** [comment]
Yes I'm using comments right now but then it just looks bad, like a hacky way of doing it.
```yml
version: '2'
services:
   prodDBUI:
    # description: To access the production db
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
   cleanImages:
    # description: To cleanup artifacts left by docker
    image: pyros2097/web
    command: clean.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by pyros2097** [comment]
And maybe when you do a `docker-compose run` it should list all the services with their descriptions it would make it more cli friendly.

**Comment by johnharris85** [comment]
Why not use labels for this, in fact there's even an example in the docs for it:

`labels:
  com.example.description: "Accounting webapp"`

Can then be displayed using `inspect` etc...

https://docs.docker.com/v1.8/compose/yml/#labels

**Comment by pyros2097** [comment]
Yeah I guess thats the only to do it for now. But I don't think its gonna look that pretty and was thinking of something more like graphql or graphiql where everything is self documenting.
I guess the this is how it would look,
```yml
version: '2'
services:
   prodDBUI:
    labels:
      - To access the production db
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
   cleanImages:
    labels:
       - To cleanup artifacts left by docker
    image: pyros2097/web
    command: clean.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
