### ISSUE TITLE
config breaks volumes_from

### ISSUE THREAD

**Issue by lindt** [docker/compose#3666]
I do have several compose files. My goal is to combine them using "docker-compose config". The problem is, that docker-compose does not understand its own created file after that.

Given a compose file with a service using a volume_frmo

``` yml
version: '2'
services:
  first:
    image: ubuntu
    volumes_from:
      - second
  second:
    image: ubuntu
    volumes:
      - /data
```

When running 'docker-compose config'
Then the output will be

``` yml
networks: {}
services:
  first:
    image: ubuntu
    volumes_from:
    - service:second:rw
  second:
    image: ubuntu
    volumes:
    - /data:rw
version: '2.0'
volumes: {}
```

But "service:second:rw" is an invalid volume spec

```
ERROR: for second  b'Invalid volume spec "rw": volumeabs: Invalid volume destination path: \'rw\' mount path must be absolute.'
ERROR: Encountered errors while bringing up the project.
```

**Comment by shin-** [comment]
Fixed in recent versions as far as I can tell:

```yaml
$ cat docker-compose.yml 
version: '2'
services:
  www1:
    image: nginx
    environment: ['A=C']
    volumes:
      - /mkdir
  www2:
    image: nginx
    volumes_from:
      - www1
$ docker-compose config | docker-compose -f - up
Creating compose_www1_1 ... done
Creating compose_www1_1 ... 
Creating compose_www2_1 ... done
Attaching to compose_www1_1, compose_www2_1
...
```
