### ISSUE TITLE
Docker compose pull should not pull image that's overrided with build option

### ISSUE THREAD

**Issue by heroandtn3** [docker/compose#3673]
**Scenario:** I have two compose files

The base one is `docker-compose.yml`:

``` yml
version: '2'

services:
  webapp:
    image: hello-world
  redis:
    image: redis:latest
```

The extended one is `docker-compose.override.yml` to override `webapp` service with `build` option:

``` yml
version: '2'

services:

  webapp:
    extends:
      file: docker-compose.yml
      service: webapp
    build:
      context: .
  redis:
    extends:
      file: docker-compose.yml
      service: redis
```

The command I run:

```
docker-compose -f docker-compose.override.yml pull
```

**Actualy result:** both `hello-world` and `redis` images are pulled

**Expected result:** only `redis` image is pulled because the `hello-world` image is eventually built later with `docker-compose build`.

**Comment by lindt** [comment]
You defined both. The image and how it's built.
build is just used, if there is no pre-built image available.

**Comment by heroandtn3** [comment]
I realize that if I have both `build` and `image` in the same docker compose file, the image is still pulled:

```yml
version: '2'

services:

  webapp:
    build:
      context: .
    image: hello-world1
  redis:
    image: redis:latest
```

I do not see any reason to pull `hello-world1` image on `docker-compose pull` command. Furthermore, the image `hello-world1` is used for local usage only so I will have unwanted error `Error: image library/hello-world1 not found`.

I suggest to not pull service image whenever the `build` option is provided.
