### ISSUE TITLE
docker-compose bundle warnings

### ISSUE THREAD

**Issue by mavencode01** [docker/compose#3680]
I'm trying out the `docker-compose bundle` command but am getting some bunch of WARNINGS below:

WARNING: Unsupported key 'container_name' in services.master - ignoring
WARNING: Unsupported key 'volumes_from' in services.config - ignoring
WARNING: Unsupported key 'volumes' in services.config - ignoring
WARNING: Unsupported key 'container_name' in services.config - ignoring
WARNING: Unsupported key 'links' in services.keycloak - ignoring

Now, when I deploy the generated bundle, the services / containers doesn't work and I feel the WARNINGS are kind of errors that my docker-compose file isn't compatible with the new bundle file requirements. I can fix the warnings on container_name, but not sure how I would fix the warnings on volume_from, volumes and  links in my compose file.

How do I fix the warning message and Is there any sort of reference for the new `docker-compose bundle` command ?

Here is my docker-compose file:

```
version: "2"

services:

  master:
    container_name: "citus_master"
    image: "citusdata/citus:5.1.0"
    ports: 
    - "5432:5432"
    labels: 
    - "com.citusdata.role=Master"

  worker:
    image: "citusdata/citus:5.1.0"
    ports: 
    - "5433:5432"
    labels: 
    - "com.citusdata.role=Worker"

  config:
    container_name: "citus_config"
    image: "citusdata/workerlist-gen:0.9.0"
    volumes: 
    - "/var/run/docker.sock:/tmp/docker.sock"
    volumes_from: 
    - "master"

  keycloak:
    image: "jboss/keycloak-postgres"
    links: 
    - "master:postgres"
    ports: 
    - "8080:8080"
    environment: 
    - KEYCLOAK_USER=admin 
    - KEYCLOAK_PASSWORD=password 
    - POSTGRES_DATABASE=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_PORT_5432_TCP_ADDR=postgres
    - POSTGRES_PORT_5432_TCP_PORT=5432

  pgweb:
    image: "sosedoff/pgweb"
    ports: 
    - "8081:8081"
```

**Comment by johnharris85** [comment]
Bundles are still experimental right now. They are intended to represent 'portable' deployable services. I don't know, but my guess is that those things won't be supported as they are things that tend to tie containers to either a specific host or a specific number of instances or a specific topology.

'container_name' - Only really works for one instance
'volumes_from' - Not portable / topology-specific
'volumes' - Only one that makes sense to include, named volumes using some distributed storage driver (flocker etc...)
'links' - Are deprecated, docker native networking supersedes this.

**Comment by mavencode01** [comment]
@johnharris85 thanks!

**Comment by rayjohnson** [comment]
Bummed that volumes is missing.  Makes it not useable for a good 1/3 of our current apps.  Would also like to see it support the new global swarm mode.  (Think deploying something like cadvisor or other monitoring stacks.)

**Comment by RRAlex** [comment]
It seems like pretty much everything is missing right now (especially security configurations!), at least on our docker-compose.yml :
```
aliases
cap_add
cap_drop
container_name
cpu_shares
depends_on
ipv4_address
links
mem_limit
networks
read_only
restart
volumes
``
So I'm really not sure how one is supposed to use docker swarm in practice except for launching a single service by hand.
Has anyone seen a complex example working? Or more importantly, are all the arguments to `docker run` being ported to `docker services`?

**Comment by Vanuan** [comment]
It looks like volumes are supported in `docker service create` (though with some new syntax, `--mount`).

But how does it work exactly? Do I have to use some global/network filesystem? Or consistency is not important? Or docker should support replicated filesystem itself? Or docker would just error out when I try to scale service with volumes? How does it move to another host if it goes down?

These questions need to be answered before we expect `docker-compose bundle` to magically work with volumes.

**Comment by Vanuan** [comment]
Here's some interesting discussion: https://forums.docker.com/t/docker-1-12-swarm-storage-options-with-dab-distributed-application-bundles-on-gce/16204/3

**Comment by Vanuan** [comment]
Also related to https://github.com/docker/docker/issues/24089

**Comment by RRAlex** [comment]
Has anyone seen a Roadmap showing from which future version will the bundle feature actually become usable fully?

... so people can migrate to pure swarm setup, including all the security options.

**Comment by jamshid** [comment]
Found this issue because I'm also unable to use docker compose and swarm to deploy containers that require systemd. 

```
Ignoring unsupported options: cap_add, devices, privileged, security_opt, tmpfs
```
When will stack/bundle/dab/whatever support systemd containers, which require `cap_add` and `tmpfs`? 

Ref https://github.com/docker/docker/issues/28614#issuecomment-261724902
```
    cap_add:
      - SYS_ADMIN
    tmpfs: /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - container=docker
```

PS: `devices` would also be very useful especially if the value could somehow be made specific on each swarm node.
