### ISSUE TITLE
driver_opts should support the same commands as docker volume create --opt

### ISSUE THREAD

**Issue by DJviolin** [docker/compose#3715]
I have the following `docker-compose.yml`:

``` yaml
version: '2'

services:
  app:
    build: ./app
    container_name: myapp
    volumes:
      #- "../app:/root/www/myapp:rw"
      - myapp:/root/www/myapp:rw

volumes:
  myapp:
    #driver: local
    driver_opts:
      o: uid=500,gid=500
      device: ../app
```

I have a hard time to figure out how to attach a named volume from the host machine to the container. I following this resource: https://docs.docker.com/engine/reference/commandline/volume_create/

This throws the following error:

``` shell
ERROR: for app  no such device
ERROR: Encountered errors while bringing up the project.
```

Thank You for your help!

``` shell
core@core-1 ~ $ docker -v
Docker version 1.11.2, build 4a6e2b1
core@core-1 ~ $ docker-compose -v
docker-compose version 1.8.0-rc1, build 9bf6bc6
```

**Comment by cpuguy83** [comment]
@DJviolin The driver opts you are specifying here are not going to work. You can't create a bind mount like this, and you can't change uid/gid's on bind mounts, unfortunately.

**Comment by DJviolin** [comment]
So the `driver_opts` mentoined here is not work at all in `volumes`, just only in `networks`?

https://docs.docker.com/compose/compose-file/#/driver-opts

It is also specified for `networks` config:

https://docs.docker.com/compose/compose-file/#/driver-opts-1

I thought this is implementing the `docker volume` command?

https://docs.docker.com/engine/reference/commandline/volume_create/#/driver-specific-options

**Comment by cpuguy83** [comment]
@DJviolin driver_opts should work (I've not tried to use them with compose) for volumes... just not with these options.

**Comment by xeor** [comment]
Should this work now? I just tried a volume like this in my compose-file:

```
volumes:
  servicename:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.1.2.3,rw"
      device: ":/data/servicename"
```

but it gives me an error;

```

ERROR: for servicename  Cannot create container for service servicename: no such file or directory
ERROR: Encountered errors while bringing up the project.
```


Should this work now?

```
Client:
 Version:      1.12.2-rc1
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by mferrier** [comment]
I'm trying to do the same thing and wondering if it's actually not possible to pass the same `--opt` style options to the volume definition in docker-compose or what?

Is there a list of the accepted `driver_opts` for volume definitions? The docker-compose volume [docs](https://docs.docker.com/compose/compose-file/) refer to the `docker volume create` [docs](https://docs.docker.com/engine/reference/commandline/volume_create/) which refer to the `mount` [docs](http://man7.org/linux/man-pages/man8/mount.8.html), but clearly not all the same options that can be passed to `docker volume create` work with volume `driver_opts` in docker-compose. 

e.g. with 
```
volumes:
  app_volume:
    driver: local
    driver_opts:
      type: nfs
      proto: tcp
```

`ERROR: create format_app_volume: invalid option key: "proto"`

Is the only option to create the volume with `docker volume create` and then use `external` ?

**Comment by cpuguy83** [comment]
@mferrier `proto` is not a supported opt, you would need `o` with a csv list, just like `mount -o`
e.g.
```yaml
volumes:
  app_volume:
  driver_opts:
    type: nfs
    device: /export/path
    o: proto=tcp,addr=1.2.3.4

**Comment by xeor** [comment]
Should docker-compose using `volumes` do exactly the same as `docker volume create` in this case?

I'm getting this error:
```sh
$ docker-compose up
Starting backup_borg_1

ERROR: for borg  Cannot start service borg: invalid argument
ERROR: Encountered errors while bringing up the project.
```

Using a `docker-compose` like this, for testing:
```yml
version: '2'

services:
  borg:
    image: alpine
    command: sleep 10000
    volumes:
      - backupdata:/data

volumes:
   backupdata:
     driver_opts:
       type: nfs
       device: :/docker/backup
       o: addr=10.1.2.3,rw
```

However, creating the volume manually and mounting it with a normal `docker run` works.
```
docker volume create --driver local --opt type=nfs --opt o=addr=10.1.2.3,rw --opt device=:/docker/backup --name backupdata
```
Including a `docker-compose` like this after the creation of the volume;

```yml
volumes:
  backupdata:
    external: true
```

Using docker and docker-compose on osx. dockerd is on `CentOS 7`
`docker-compose version 1.9.0, build 2585387`

```
Client:
 Version:      1.13.0-rc2
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.12.3
 API version:         1.24
 Minimum API version:
 Go version:          go1.6.3
 Git commit:          6b644ec
 Built:
 OS/Arch:             linux/amd64
 Experimental:        false
```

Should this have worked? Or does docker-compose behave differently? Bug? How can I provide more info?

If I look at the container docker-compose creates (if I look at `docker-compose --verbose up` output), the `docker inspect` > `mounts` stanza looks the same as the container that works.

**Comment by dschu-lab** [comment]
I'm currently experiencing the same error as @xeor and don't know how to solve this.

**Comment by denhams** [comment]
I'm also seeing the same problem:

```
version: '2'

services:
  apache:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-debug
    volumes:
      - ./:/var/www/app
      - ./docker/apache/app.conf:/etc/httpd/conf.d/app.conf
      - image_store:/var/www/betslip/shared/storage/images
volumes:
    image_store:
        driver_opts:
            type: nfs
            o: 10.172.48.39,rw
            device: /var/whus/images
```
This gives:

ERROR: for apache  Cannot start service apache: invalid argument
ERROR: Encountered errors while bringing up the project.

**Comment by cpuguy83** [comment]
@denhams This is because the options you've supplied are not valid.
Specifically: `o: 10.172.48.39,rw` should be something like `o: addr=10.172.48.39,rw` and `device` needs to be `device: :/var/whus/images`... this is just due to how the nfs kernel module parses this.

Also not really related since `version: '2'` is not supported by docker, only compose.

**Comment by xeor** [comment]
@cpuguy83: your suggestions is what I am trying, see previous comment. I have the same problem as well

**Comment by Routhinator** [comment]
I've tried all the suggestions here and tried to make heads or tails of the docs without success. Can mounting NFS currently be achieved?

**Comment by mferrier** [comment]
I also tried all the suggestions here with no luck. I was trying to get it working for sharing source for local development, so if it helps anyone else, I eventually got it working by:
1. Going back to Docker Machine (from Docker for Mac)
1. Using [docker-machine-nfs](https://github.com/adlogix/docker-machine-nfs) to automatically share the directory to the docker machine, which in turn automatically shares its nfs mounts with any containers run on it, including those from the host OS.

**Comment by Routhinator** [comment]
I tried a number of things and noted that all of the suggestions here result in the same failure:

    ERROR: for registry  Cannot start service registry: {"message":"error while mounting volume '/var/lib/docker/volumes/routhio_registry-data-auth/_data': error while mounting volume with options: type='nfs' device='192.168.50.200:/mnt/datastore-1TB/docker-registry/auth' o='': invalid argument"}

This was attemped with:

```
  registry-data-auth:
    driver: local
    driver_opts:
      type: nfs
      device: 192.168.50.200:/mnt/datastore-1TB/docker-registry/auth
```
AND

```
  registry-data-auth:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.50.200,rw
      device: ":/mnt/datastore-1TB/docker-registry/auth"
```

AND

```
  registry-data-auth:
    driver: nfs
    driver_opts:
      device: 192.168.50.200:/mnt/datastore-1TB/docker-registry/auth
```

All three resulted in the exact same failure message, even when forcing recreate, leading me to believe that the : is not required on device. I also not that o='' is blank everytime and never passes the rw argument.

For those stuck I worked around this by using https://github.com/ContainX/docker-volume-netshare to add an NFS driver to docker. Then a mount can be achieved easily with:

```
  registry-data-auth:
    driver: local
    driver_opts:
      type: nfs
      device: 192.168.50.200:/mnt/datastore-1TB/docker-registry/auth
```

**Comment by bioffe01** [comment]
`docker volume create --name trac_volume --opt o=bind --opt device=/trac/ `
with 
```
trac_volume:
     external: true
```
works fine

```
  trac_volume:
     driver_opts:
       device: :/trac
       o: o=bind
```

Doesn't work, like for everyone else. Clearly a problem.

**Comment by mahnunchik** [comment]
Does not work:

```
version: '3'
services:
  web:
    build: .
    volumes:
      - uploads:/uploads

volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      device: ./uploads
      o: bind
```

**Comment by m0onspell** [comment]
Same configuration as @mahnunchik, doesn't work. 
Now I have no idea how to share mounted volume between multiple containers,  when we don't have `volumes_from` option.
And there's no working example for doing that. Anywhere.

**Comment by tomfotherby** [comment]
For reference, we have managed to share a mounted volume between multiple containers. It works on Linux and mac hosts. The extract from our `docker-compose.yml` is pretty similar to the above examples, i.e.

```
version: '2.0'
services:
  mysql:
    image: ourcompany/mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver_opts:
      type: none
      device: $PWD/mysql_data
      o: bind
```

(I did notice that `$PWD` works better than `./` (you would think they are the same!).)

```
$ docker -v
Docker version 17.05.0-ce, build 89658be
$ docker-compose -v
docker-compose version 1.14.0, build c7bdf9e
```

**Comment by m0onspell** [comment]
@tomfotherby 
`It works on Linux and mac hosts.` - `Build, Ship, and Run Any App, Anywhere`
I am working in Windows environment. Then I also have to deploy my app to Linux.
I've tried this setup with full and relative paths, on Windows it always errored with `no such file or directory`.

**Comment by krebstar01** [comment]
docker volume create --name my_new_volume --opt type=none --opt device=$PWD/dir/with/important/host/files --opt o=bind

docker run -d -t -i --name=my_new_container -v my_new_volume:/etc/my/dir:ro  test/built-image:v1

Here I create a volume (a simple mount to some host files, in a directory)

Note that I have used "ro" for the directory inside my container.

The results are that the host dir permissions are changed to root and the host directory is set as readonly. 

This is obviously not at all desired!

**Comment by xrobau** [comment]
As this is high in the google results for trying to get stack/compose to work with NFS, there are a couple of things I discovered as I ventured down this rabbit hole.

1. Volumes are *not* updated if you change the definition. This is probably a bug.  This is why @Routhinator did not see any changes. You need to 'docker volume rm VOLUMENAME'. It'll then be created with the correct settings.
2. You need to be using 3.2 or higher
3. NFS works.  It's just amazingly awful to setup.  Here is a fully working example:

```
version: "3.2"

services:
  ubuntu:
    image: ubuntu:16.04
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: ubunt
        target: /nfs
        volume:
          nocopy: true
volumes:
  ubnt:
    driver_opts:
      type: "nfs"
      o: "addr=10.40.0.199,nolock"
      device: ":/docker/ubnt"

```
This assumes that your NFS server is on 10.40.0.199, and it has a export '/docker/ubnt' (or just '/docker' with a subdirectory of 'ubnt'). That NFS volume will be mounted inside the container, as expected.

THIS IS NOT RELEVANT TO THIS BUG. This is just here to help people avoid what I just spent the morning figuring out. 8)

**Comment by raysbudo** [comment]
I have a slightly different problem I can get the volumes to work on a stand alone docker server in Linux mapping the volume as -v /data/files/website1:/data/files/website1. but when I try to do this on a swarm the services don't connect or return an error " cannot be an absolute path, even when I use a --mount syntax --mount type=bind, src=/data/files/website1,target=/data/files/website1.  The bind seems to work but my ontainer cannot acess the files which I replicate across all my hosts.  I thought that as long as the path existed I should be able to connect,  even from a  docker service.  Again, this works as a stand alone but not as a servie how can I resolve my problem.  the directory holds all the files I need and update regularly to run my website

**Comment by Bessonov** [comment]
activity occurs

**Comment by Bessonov** [comment]
The stale bot is one of the best ways to disrespect the community.

**Comment by Bessonov** [comment]
The stale bot is one of the best ways to disrespect the community.

**Comment by yukihiko-shinoda** [comment]
Won't it good idea to Docker support uid/gid mapping for NFS mount or bind mount?

Regarding container's operations for host's files as specific user's one keeps user identity space **`loosely coupled'**,
and solves any problems in the development environment.

In Vagrant, `map_uid` / `map_gid` option worked well for us.
[NFS - Synced Folders | Vagrant by HashiCorp](https://www.vagrantup.com/docs/synced-folders/nfs#nfs-global-options)

In Developing inside a Container with Visual Studio Code,
the permission of created file will be `root:root` even in host.
These files can't handle by Git in host.
Should we also use root user as default in host?

When we create and specify new user for development inside container,
Maybe we'll face permission problems inside container
since container is designed with container's own user/group permission.

I know one more alternative way that complete development inside container,
however we still need rich explorer and Git client in host PC.

cf. [Developing inside a Container using Visual Studio Code Remote Development](https://code.visualstudio.com/docs/remote/containers#_system-requirements)

Even if only `userns-remap` was supported in Docker Desktop, it would be help.
[Isolate containers with a user namespace | Docker Documentation](https://docs.docker.com/engine/security/userns-remap/#enable-userns-remap-on-the-daemon)
[WSL 2: userns-remap not working / daemon.json not picked up · Issue #6897 · docker/for-win](https://github.com/docker/for-win/issues/6897)

**Comment by Bessonov** [comment]
die bot die

**Comment by lucasteinke** [comment]
I love how this has been open since 2016. Commenting to prevent double notifications from the bot, which is indeed

> one of the best ways to disrespect the community.

**Comment by ndeloof** [comment]
I was not aware of this issue (there's so much from project legacy...) but afaict most users here are trying to bind mount a folder into a service container, and get confused by the "volume" terminology. There's also many questions/reported issues mixed here, so hard to tackle them all at once (better open dedicated issues)

Docker CLI flags use a poorly named flags `--volume (-v)`but:
- a "volume" is an opaque storage managed by daemon, 
- a "bind mount" let you select a host path to be mounted into container's filesystem

basically, https://github.com/docker/compose/issues/3715#issuecomment-311902611 should just be:
```yaml
services:
  mysql:
    image: ourcompany/mysql:5.7
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
```

> Volumes are not updated if you change the definition. This is probably a bug

Yes indeed, while this could be detected, but not sure volume should be re-created without at least a warning (data would be lost!)

Due to the large number of unrelated comments that make it impossible to give a single answer, I'll beg your pardon and close this issue. Please, please create a fresh new issue if there's a specific topic that hasn't been addressed and would deserve further investigations / but fixes / answers / better documentation (can give a reference to a specific comment from this long issue)

**Comment by Tarekdu13** [comment]
Got same issue but the solutions proposed before don't work me, i got a compose file with those specifications:
i have those informations:
docker-compose version 1.29.2
Docker info:
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3.1
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:

name-me:
    container_name: name-me
    image: image:1.0
    tty: true
    volumes:
      - name_vol:/app/front
volumes:
  name_vol:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/front
      o: bind

**Comment by ndeloof** [comment]
@Tarekdu13 Docker Compose v1 will be End of Life in a few months, you should migrate to Docker Compose v2

**Comment by Tarekdu13** [comment]
@ndeloof same when i updated, compose and docker.
docker-compose version
`Docker Compose version v2.16.0`
```
docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
`Error response from daemon: failed to mount local volume: mount /home/me/app/front:/var/lib/docker/volumes/docker_name_vol/_data, flags: 0x1000: no such file or directory`

**Comment by ndeloof** [comment]
@Tarekdu13 any reason you declare an explicit volume and don't just use:
```yaml
name-me:
    container_name: name-me
    image: image:1.0
    tty: true
    volumes:
      - ./front:/app/front
```

**Comment by Tarekdu13** [comment]
When i do so, my volume gets crushed, and the container gets empty, so the solution that make sense is to bind the volume from /var/lib/ into my PWD file, for development purpose.

**Comment by msingh0101** [comment]
my rabbit hole led me here..and not suprisingly, still doesnt seem like any good option to mount windows file system path and set driver options.  
is there any updates on how to do this? nothing i tried above works

**Comment by DJviolin** [comment]
In the following years I developed my own solution for this problem, which is consistent in every project that I use.

I spinning up Compose projects with shell scripts and injecting environment variables from `.env` file, just like in a Laradock project. My addition is the shell scripts, which can store dynamic values read from the linux system, two of them is user and group ids.

In `./bin/env_variables.sh` I have this:

```sh
#!/bin/sh

set -e

# These are only used in shell scripts, don't need to export
DIR=$( cd "$(dirname $0)" && pwd )

# Always needed, but need to export for Ansible
export ABS_PATH=$( cd "$DIR/.." && pwd )

# Needed for volumes
export UID=$(id -u)
export GID=$(id -g)

# Magic happens here
set -a && . $ABS_PATH/.env && set +a
```

I'm spinning up my Docker Compose project with this script in `./bin/compose.sh`:

```sh
#!/bin/sh

set -e

DIR=$( cd "$(dirname $0)" && pwd )
. $DIR/env_variables.sh

usage_fn() {
    cat <<- EOF
    ####################################################
    Run Docker Compose project
        Usage: $0 up|stop|down|prune
    ####################################################
    EOF
}

up_fn() {
    echo "$0: Start Docker Compose project"
    docker compose \
        --env-file $ABS_PATH/.env \
        --file $ABS_PATH/docker-compose.yml \
        up --detach $SERVICES
}

# ...

case "$1" in
    up)
        up_fn
        ;;
    # ...
    *)
        usage_fn
        echo "$0: unknown argument provided => $1\n"
        exit 1
        ;;
esac
```

So I expose UID and GID to the Docker container with this `docker-compose.yml`:

```yaml
services:
  my-app:
    build:
      context: ./src/my-app
      args:
        UID: ${UID}
        GID: ${GID}
    # ...
```

And use it as an argument only in the build process to create an user with the same user and group ids just like the host user:

```Dockerfile
FROM debian:bookworm-slim

ARG UID
ARG GID

RUN set -e \
    && groupadd --gid $GID containerised-user \
    && useradd --gid containerised-user --create-home --shell /bin/sh --uid $UID containerised-user \
    # ...
```

If the user and group ids are matching on the host and quest, the username differences doesn't matter between the two. So the host user can be Linus and the guest user's name can be Nvidia.

This is an old trick, probably as old as Docker itself, but unfortunately still no better way. This works with WSL, too.
