### ISSUE TITLE
Container command '/w/w' not found or does not exist ( 1.8.0dev, build 619bf4c ) from bash 

### ISSUE THREAD

**Issue by sh0umik** [docker/compose#3758]
I am gettig this error after I upgrading composer to latest beta because recently i faced this problem 
`AttributeError: 'ProjectError' object has no attribute 'msg'` in 1.7.1 and found in here that , this issue has been solved and merged to master. Now in the same project i get the following error when i try to execure docker-compose via bash 
```
ERROR: for test-db  Cannot start service test-db: Container command '/w/w' not found or does not exist.

ERROR: for test-token  Cannot start service test-token: Container command '/w/w' not found or does not exist.
ERROR: Encountered errors while bringing up the project.
```

Strange, however if I open terminal then cd to that directory and run `docker-compose build` then no error occurs

**Comment by johnharris85** [comment]
Can you post your compose file please?

**Comment by sh0umik** [comment]
```
test-db:
  container_name: test-db
  image: postgres
  hostname: test-db.test.local
  environment:
    - POSTGRES_PASSWORD=test
    - POSTGRES_USER=test
    - POSTGRES_DB=test_auth
  volumes:
    - /mnt/postgresql_data/test/data:/var/lib/postgresql/data

test-token:
  container_name: test-token
  hostname: test-token.test.local
  image: bitnami/redis
  environment:
    - REDIS_PASSWORD=test
  volumes:
    - /mnt/redis_data:/bitnami/redis/data

test-api:
  container_name: test-api
  hostname: test-api.test.local
  build: .
  ports:
    - "443:443"
  links:
    - test-db
    - test-token
```
