### ISSUE TITLE
use services from remote compose file

### ISSUE THREAD

**Issue by tjamet** [docker/compose#3813]
Hi,

Having distinct repositories for our frontend and backend, we would like, to be able to reference, in frontend compose file, services exposed in the backend compose file without having to handle the dependencies (databases, volumes, configuration, ...) of the backend.

sample frontend compose file:
```
version: "2"
services:
  - public:
    - image: public
    - depends_on:
      - backend
  - private:
    - image: private
    - depends_on:
      - backend
```
sample backend compose file:
```
version: "2"
services:
  - db:
    - image: our_database
  - backend:
    - image: backend
```

To tackle our issue, we currently do the following:
```
curl -o docker-compose.backend.yml https://our.server.local/backend/docker-compose.yml
docker-compose -f docker-compose.backend.yml -f docker-compose.yml up -d
```

Would there be an option (or intent to implement it) to describe this natively within the compose file?

**Comment by nikname** [comment]
I'm in the same situation as you. At the moment I'm using [external_links](https://docs.docker.com/compose/compose-file/#/external-links), so your frontend compose file would become:

```
version: "2"
services:
  - public:
    - image: public
    - external_links:
      - <backend container name>:<backend alias>
  - private:
    - image: private
    - external_links:
      - <backend container name>:<backend alias>
```

Note that

> If you’re using the version 2 file format, the externally-created containers must be connected to at least one of the same networks as the service which is linking to them

Because the docker compose file creates his own network, you must add these lines to your frontend compose file:

```
networks:
  <backend project name>_default:
    external: true
```

After starting both docker compose files you can test with (curl is required):

```docker exec <frontend container name> curl <backend alias>:<exposed port>```

I'm aware that this is an "hard-coded" solution (and most probably not the best one) but it works. I hope this helps in finding a better solution. Other solutions are welcome!
