### ISSUE TITLE
Compose YML v2 multiple DNS with Consul issues

### ISSUE THREAD

**Issue by nursejason** [docker/compose#3877]
We upgraded to v2 YML to statically assign an IP to Consul, with which we can assign to all containers, and not have to worry about the IP changing between startups. The network is defined as such:

``` YML
networks:
  consul:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
```

Then our Consul Agent is given the static IP

``` YML
  consul-agent:
    image: "gliderlabs/consul-agent"
    networks:
      consul:
        ipv4_address: "172.16.238.99"
    hostname: "node-${DOCKER_MACHINE_NAME}"
    command: ["-config-file", "/etc/consul/conf.json", "-join", "${CONSUL_IP}", "-advertise", "${HOST_IP}", "-client", "0.0.0.0"]
```

When working with a service that uses ONLY Consul for DNS, everything seems to function fine.

``` YML
  my-service-1:
    depends_on:
      - consul-agent
    image: my_image_1
    dns:
      - "172.16.238.99"
```

However, if a service uses Consul AND other DNS servers, it's unable to resolve past the first one.

``` YML
  my-service-2:
    depends_on:
      - consul-agent
    image: my_image_2
    dns:
      - "172.16.238.99"
      - "yy.yy.yy.yy"
      - "xx.xx.xx.xx"
```

Using Compose 1.8.0 and Docker 1.10.3
Latest version of Consul iirc. 
Switching the YML to v1 and getting rid of the networks magically fixes everything, and I'm a bit stumped.

**Comment by nursejason** [comment]
Was hoping someone else had seen something similar, but alas. I've done some further testing to try and isolate the issue. I removed the networks that the Consul agent was on, and simply used v2 yml. This also yields the same issue as described above. 

```yml
 consul-agent:
    image: "gliderlabs/consul-agent"
    hostname: "node-${DOCKER_MACHINE_NAME}"
    command: ["-config-file", "/etc/consul/conf.json", "-join", "${CONSUL_IP}", "-advertise", "${HOST_IP}", "-client", "0.0.0.0"]

  my-service-1:
    depends_on:
      - consul-agent
    image: my_image_1
    dns:
      - "172.16.238.99"
```
It definitely has something to do with the way that DNS was changed in compose v2, but I have no idea why it would cause DNS lookup to fail after reaching a server that doesn't have the entry.

**Comment by parknicker** [comment]
Stumbled across this when I ran into the exact same issue. Still can't figure out how to resolve it from the Docker side but would love to figure out how at some point. I tried using both the default compose bridge network and a user defined network and saw the same behavior with both, even though the Docker docs seem to indicate that using the default network keeps the old behavior with /etc/resolv.conf. There seemed to be no difference between the two to me, in both cases the only nameserver entry in /etc/resolv.conf was 127.0.0.11. I could totally be misunderstanding how it's supposed to work though.

I solved for now by passing a recursor argument to Consul. If the DNS requests can't be resolved by consul it will forward the DNS request on to whatever is passed as a recursor (can be more than one).

https://www.consul.io/docs/agent/options.html#recursor

Here's a trimmed down docker-compose.yml:

```
consul:
  command: "consul agent -dev -dns-port=53 -recursor=8.8.8.8 -client=0.0.0.0"
  environment:
    - CONSUL_ALLOW_PRIVILEGED_PORTS=
  expose:
    - 53/udp
  image: consul
  networks:
      default:
        ipv4_address: 172.20.0.2
  ports:
    - 8500:8500

app:
  build: .
  depends_on:
    - consul
  dns:
    - 172.20.0.2

 networks:
    default:
      ipam:
        config:
          - subnet: 172.20.0.0/24
            gateway: 172.20.0.1 

```
