### ISSUE TITLE
docker-compose run does not honor container_name

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#3884]
`docker-compose run` does not seem to honor `container_name` attribute in Docker Compose file.

Here is the Compose file:

```
version: '2'

services:
  db:
    image: arungupta/oreilly-couchbase
    container_name: db
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
```

`docker-compose up -d` shows the container name with `docker ps` correctly as `db`. 

But running the container as `docker-compose run --service-ports -d db` uses the container name as `<project>_<service>_run_x`. So, for the first run this value is `sample_db_run_1`. For the second run, this is `sample_db_run_2`, and so on.
