### ISSUE TITLE
ipv6_address broken

### ISSUE THREAD

**Issue by peterthomassen** [docker/compose#3988]
I am using docker 1.12.1 on Ubuntu 16.04, and docker-compose 1.8.1. The Compose file from https://docs.docker.com/compose/compose-file/#ipv4-address-ipv6-address does not run correctly: The `ipv6_address` setting seems to be ignored. I tried on various machines.

For reference, I created `docker-compose.yml` with the following content:

```
version: '2'

services:
  app:
    image: busybox
    command: ifconfig
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
```

Now, running `docker-compose up` produces

```
Creating network "tmp_app_net" with driver "bridge"
Creating tmp_app_1
Attaching to tmp_app_1
app_1  | eth0      Link encap:Ethernet  HWaddr 02:42:AC:10:EE:0A  
app_1  |           inet addr:172.16.238.10  Bcast:0.0.0.0  Mask:255.255.255.0
app_1  |           inet6 addr: fe80::42:acff:fe10:ee0a/64 Scope:Link
app_1  |           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
app_1  |           RX packets:4 errors:0 dropped:0 overruns:0 frame:0
app_1  |           TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
app_1  |           collisions:0 txqueuelen:0 
app_1  |           RX bytes:520 (520.0 B)  TX bytes:90 (90.0 B)
app_1  | 
app_1  | lo        Link encap:Local Loopback  
app_1  |           inet addr:127.0.0.1  Mask:255.0.0.0
app_1  |           inet6 addr: ::1/128 Scope:Host
app_1  |           UP LOOPBACK RUNNING  MTU:65536  Metric:1
app_1  |           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
app_1  |           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
app_1  |           collisions:0 txqueuelen:1 
app_1  |           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
app_1  | 
tmp_app_1 exited with code 0
```

The IPv6 address is not assigned. That seems to be a bug, either in `ipv6_address` itself, or there is some required configuration step missing from the documentation.

For further information, here's what I already tried:
1. Starting the docker daemon with `--ipv6`
2. Starting the docker daemon with `--ipv6 --fixed-cidr-v6="2001:3984:3989::/64"`
   - Note that `docker run -it busybox ifconfig` actually gives me an IPv6 address here (from the `--fixed-cidr` subnet which is assigned to the default `bridge` network)
3. Using my actual IPv6 subnet instead of the one from the code example, and repeating 2. with this subnet

**Comment by shin-** [comment]
I suppose this is related to #3430

**Comment by f-andrey** [comment]
IPv6 and docker need ip6tables rules and `ip -6 neigh add proxy` if you planing local access (another host you network)

about such
```
-A FORWARD -i eth0 -j DOCKER-PUB
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
```

with each container
```
ip -6 neigh add proxy 2001:3984:3989::10 dev eno1
```

note that IPv6 containers will be available globally

**Comment by peterthomassen** [comment]
@f-andrey iptables etc. has nothing to do with the missing *assignment* of the IPv6 address, right?

**Comment by f-andrey** [comment]
Sorry, my distraction, did not pay attention docker-compose

I still decided not to deal with the automatic creation of the network and create them manually. And used as external
```
docker network create --subnet=172.16.238.0/24 --gateway=172.16.238.1 --ipv6 --subnet=2001:3984:3989::/64 -o "com.docker.network.bridge.enable_icc"="true" -o "com.docker.network.bridge.enable_ip_masquerade"="false" -o "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0" -o "com.docker.network.bridge.name"="docker1" -o "com.docker.network.driver.mtu"="1500" app_net
```

**Comment by shin-** [comment]
#3994

**Comment by peterthomassen** [comment]
@f-andrey Thanks, this is a suitable workaround. I ended up using `docker network create --subnet=172.16.2.0/24 --gateway=172.16.2.1 --ipv6 --subnet=<myV6Network/subnet> dockerbridge`

**Comment by peterthomassen** [comment]
@shin- #3994 was merged for 1.9.0, and also appears in the change log. However, the result of running `docker-compose up` with the above Dockerfile (which is still the same in the docs!) is unchanged, i.e. the IPv6 address is missing, despite the fix.

I thought your fix addresses this issue. Can you elaborate? Thanks!

**Comment by shin-** [comment]
@peterthomassen Sorry for the confusion. You will need to add `enable_ipv6` in your network definition going forward. I'll look into getting the documentation updated.

```yaml
version: '2'

services:
  app:
    image: busybox
    command: ifconfig
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
```

**Comment by shin-** [comment]
With the docs change merged, I'll go ahead and close this. Let me know if you're still encountering issues.

**Comment by akomakom** [comment]
Although "enable_ipv6: true" does work in docker-compose file version 2.1, it does not work in 3.x 
Any advice regarding enabling IPv6 in current versions?
   
   
       ERROR: The Compose file './docker-compose.yml' is invalid because:
       networks.app_net value Additional properties are not allowed ('enable_ipv6' was unexpected)

**Comment by valentin2105** [comment]
I'm also blocked with compose 2.1 for IPv6, any idea how to solve this ?

**Comment by shoonoise** [comment]
@akomakom @valentin2105 
try to:
```
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
```

**Comment by valentin2105** [comment]
@shoonoise With Version '3.2' : 
 ```
bash-4.3# ip -6 addr
bash-4.3#
```
Not any IPv6 ..

**Comment by M15terHyde** [comment]
I'm using compose version 3.9 and may have re-encountered this issue. I need ipv6 addresses for testing. My tests keep failing to find the IPv6 I (thought I) gave. Running the image by itself gets an IPv6 on a random subnet. As soon as I run that image as a compose service there is no more IPv6 address. I am using "hostname -I" to verify this.

I have used the workaround above of creating the network on the command line instead of the compose file and it has worked. Ex: 
```docker network create --subnet=172.16.2.0/24 --gateway=172.16.2.1 --ipv6 --subnet=2001:db8:1::/64 --opt com.docker.network.bridge.enable_ip_masquerade=true test1-net ```
My question is though, why doesn't this work natively inside the compose file? Was it something I did incorrectly or has this issue resurfaced?

docker-compose.yml
```
version: "3.9"


# Declare new services
services:
  
  server:
    build:
      context: ..
      dockerfile: ./test1/server.Dockerfile
    networks:
      test1-net:
        ipv6_address: 2001:db8:1::10
    ports:
      - "8080"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  
  client:
    build:
      context: ..
      dockerfile: ./test1/client.Dockerfile
    networks:
      test1-net:
        ipv6_address: 2001:db8:1::11
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0


# Declare new networks
networks:
  test1-net:
    name: test1-net
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    external: false
    ipam:
      driver: default
      config:
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1


```

Docker config (shouldn't be important because I get ipv6 in standalone containers)
```
{
  "debug": false,
  "experimental": true,
  "features": {
    "buildkit": true
  },
  "fixed-cidr-v6": "2001:db1:1::/64",
  "insecure-registries": [
    "172.26.90.130:5000"
  ],
  "ipv6": true,
  "registry-mirrors": []
}
```

docker inspect network settings on the container running as a service:
```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9e730e676102dfeb504f17c99dd6113f08c571a00d8e7bc3052986bf539b692b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/9e730e676102",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "test1-net": {
                    "IPAMConfig": {
                        "IPv6Address": "2001:db8:1::11"
                    },
                    "Links": null,
                    "Aliases": [
                        "test1_client_run_de94b8603a30",
                        "324d40cb1404"
                    ],
                    "NetworkID": "9ab94f2930484cd26df3d6bbdf9ec2c15e150e922f76e0cdc2c1afa2cb56b784",
                    "EndpointID": "f9962ac3b01f72a2e09dff87dd0ffa671d286e1073dc1f3e1151ad52adfd6b5e",
                    "Gateway": "172.28.0.1",
                    "IPAddress": "172.28.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:1c:00:02",
                    "DriverOpts": null
                }
            }
        }
```
