### ISSUE TITLE
Environment variables not handled in docker-compose.yml when in detached mode.

### ISSUE THREAD

**Issue by lordjabez** [docker/compose#3995]
I use a couple environment variables in my `docker-compose.yml` file. When I run `docker-compose up`, these variables are populated as expected, but if I run in detached mode, I get warnings that they are missing.

I'm running v1.8.0 on Mac OS.

**Comment by shin-** [comment]
Do you have a reproducible case? I tried with [1] but the output is identical whether I do `docker-compose up` or `docker-compose up -d`

[1]
```yaml
version: '2'
services:
  app:
    command: env
    image: busybox
    ports:
      - 8080:80
    environment:
      - FOO=bar
      - BAR=baz
```

**Comment by lordjabez** [comment]
I wasn't clear. The issue is with variables defined in the shell being used in the compose file. For example:

```
version: '2'
services:
  app:
    command: env
    image: busybox
    ports:
      - 8080:80
    environment:
      - FOO=${BAR}
```

Now try

```
export BAR=baz
# Variable is properly inserted into compose file:
docker-compose up
# Variables do not get included in compose file:
docker-compose up -d
```
