### ISSUE TITLE
fig.yml: Add 'autostart: false' option

### ISSUE THREAD

**Issue by docwhat** [docker/compose#400]
I have some things that are maintenance related, e.g. database optimization or analysis.

I would like to be able to tell fig not to run them automatically during `fig up` but only when using `fig run <app>`.

Example:

``` yaml
maintenance:
  image: my-mysql
  link: db:mysql
  autostart: false

db:
  image: my-mysql
  ....
```
