### ISSUE TITLE
Values for logging are not merged while using "extends"

### ISSUE THREAD

**Issue by xanderbo** [docker/compose#4000]
- common.yml
```
version: '2'
services:
  common:
    network_mode: "mynetwork"
    environment:
      - PRODUCTION=true
    restart: on-failure:5
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-central-1"
        awslogs-group: "MY_LOGGING"
```
- docker-compose.yml
```
webapp:
    extends:
      file: common.yml
      service: common
    image: some/image:latest
    container_name: webapp
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        awslogs-stream: "webapp"
```

After running `docker-compose up -d` I get:
```
Creating webapp
ERROR: for webapp  Cannot create container for service webapp:
unknown log opt 'awslogs-stream' for json-file log driver
```

All other values are inherited correctly (i.e. network_mode, environment and restart). Is this expected behaviour?
In real `docker-compose.yml` I have ~10 services, all of them have common logging driver (awslogs), the same region and logging group. The only difference is this "awslogs-stream".
Do I really have to repeat the same section (logging) for every service?
