### ISSUE TITLE
context not passed to extends service

### ISSUE THREAD

**Issue by veqryn** [docker/compose#4050]
Context is not being passed, or is not being respected, by a service that extends another service.

Example directory structure of a simplified example project:

```
.
./shared/docker-compose.yml
./main/docker-compose.yml
./containerdefs/blarg/Dockerfile
./data
./docker-compose-shared.yml (symlinked to ./shared/docker-compose.yml)
./docker-compose-main.yml (symlinked to ./main/docker-compose.yml)
```

Contents of ./shared/docker-compose.yml:

```
version: '2'
services:
  blarg:
    build:
      context: .
      dockerfile: ./containerdefs/blarg/Dockerfile
    command: ls /project
    volumes:
      - .:/project
```

Contents of ./main/docker-compose.yml:

```
version: '2'
services:
  blarg:
    extends:
      file: ./shared/docker-compose.yml
      service: blarg
    build:
      context: .
```

If I run `docker-compose --file ./docker-compose-shared.yml up`, the blarg container will successfully mount the whole project directory and output its contents with `ls`.

If I run `docker-compose --file ./docker-compose-main.yml up`, the blarg container will not mount the project directory, and will instead mount the contents of the `./shared/` directory.

This is despite purposefully setting the build context on my extended container in the `main` version.

**Comment by veqryn** [comment]
Or to use an example without symlinks:

```
.
./shared/docker-compose.yml
./containerdefs/blarg/Dockerfile
./data
./docker-compose-main.yml
```

Contents of ./shared/docker-compose.yml:
```
version: '2'
services:
  blarg:
    build:
      context: .
      dockerfile: ./containerdefs/blarg/Dockerfile
    command: ls /project
    volumes:
      - .:/project
```

Contents of ./docker-compose-main.yml:
```
version: '2'
services:
  blarg1:
    extends:
      file: ./shared/docker-compose.yml
      service: blarg
    build:
      context: .
  blarg2:
    build:
      context: .
      dockerfile: ./containerdefs/blarg/Dockerfile
    command: ls /project
    volumes:
      - .:/project
```

blarg2 will correctly list the contents of the project, including the "data" file

blarg1 will incorrectly list the contents of the ./shared directory, despite overwriting the context
