### ISSUE TITLE
All network links not available when using docker-compose run

### ISSUE THREAD

**Issue by johanbrandhorst** [docker/compose#4052]
Hi,

It appears that when using `docker-compose run --rm --service-ports master` where my `master` container depends on another container, which itself needs a network connection with the `master` container, the last connection is not created. It appears network connections are only made available for explicit dependencies (using `depends_on`), and only one-way.

Note that when use with `docker-compose up` all expected network connections are created.

Here is an example docker-compose (v2) which when used with `docker-compose run master` creates a network from `master` to `slave`, but not from `slave` to `master`.

``` yaml
version: '2'
networks:
    internal:
        driver: bridge
services:
    slave:
        command: "ash -c 'sleep 1; ping master'"
        image: busybox
        networks:
            - internal
    master:
        command: "ping slave"
        depends_on:
            - slave
        image: busybox
        networks:
            - internal
```

When this is run with `docker-compose up`:

``` bash
$ docker-compose up                                                                                                                                  
Creating network "my_internal" with driver "bridge"                                                                                                                    
Creating my_slave_1                                                                                                                                                    
Creating my_master_1                                                                                                                                                   
Attaching to my_slave_1, my_master_1                                                                                                                                
master_1  | PING slave (172.19.0.2): 56 data bytes                                                                                                                        
master_1  | 64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.064 ms                                                                                                          
slave_1   | PING master (172.19.0.3): 56 data bytes                                                                                                                       
slave_1   | 64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.146 ms                                                                                                          
master_1  | 64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.126 ms                                                                                                          
slave_1   | 64 bytes from 172.19.0.3: seq=1 ttl=64 time=0.127 ms                                                                                                          
master_1  | 64 bytes from 172.19.0.2: seq=2 ttl=64 time=0.143 ms                                                                                                          
slave_1   | 64 bytes from 172.19.0.3: seq=2 ttl=64 time=0.153 ms                                                                                                          
master_1  | 64 bytes from 172.19.0.2: seq=3 ttl=64 time=0.058 ms                                                                                                          
slave_1   | 64 bytes from 172.19.0.3: seq=3 ttl=64 time=0.130 ms                                                                                                          
master_1  | 64 bytes from 172.19.0.2: seq=4 ttl=64 time=0.157 ms                                                                                                          
slave_1   | 64 bytes from 172.19.0.3: seq=4 ttl=64 time=0.142 ms
^CGracefully stopping... (press Ctrl+C again to force)                                                                                                                    
Stopping my_master_1 ... done                                                                                                                                          
Stopping my_slave_1 ... done 
```

Same thing run with `docker-compose run --rm --service-ports master`:

``` bash
$ docker-compose run --rm --service-ports master                                                                                                     
Creating network "my_internal" with driver "bridge"                                                                                                                    
Creating my_slave_1                                                                                                                                                    
PING slave (172.19.0.2): 56 data bytes                                                                                                                                    
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.090 ms                                                                                                                      
^C                                                                                                                                                                        
--- slave ping statistics ---                                                                                                                                             
26 packets transmitted, 1 packets received, 96% packet loss                                                                                                               
round-trip min/avg/max = 0.090/0.090/0.090 ms                                                                                                                             
$ docker logs my_slave_1                                                                                                                          
ping: bad address 'master'   
```

Obviously I can't create dependency cycles using `depends_on` or `links`. Is there any way to get the expected result with `docker-compose run`?

**Comment by johnculviner** [comment]
Experiencing the same issue here. Not sure if there is a way around this but this is totally killing my CI/CD Karma + Selenium plans for Docker....

**Comment by johanbrandhorst** [comment]
@johnculviner the workaround is to run something like

```
docker-compose up -d
while [[ $(docker inspect -f '{{.State.Running}}' <container_name>) != "false" ]]; do
    echo "Waiting for job to finish";
    sleep 2;
done
exit $(docker inspect -f '{{.State.ExitCode}}' <container_name>)
```

**Comment by johnculviner** [comment]
@johanbrandhorst thanks for that! I ended up going this route which worked great for isolated bi-directional container communication. Hope this helps someone setup something similar:

```
version: '2'
services:
  my-app-under-test:
    image: my-app-image
    networks:
      - my-app-bridge
    command: "sleep infinity" #keeps the container alive for 2 way networking to work, test is ran with docker-compose exec
  selenium-chrome:
    image: selenium/standalone-chrome
    networks:
      - my-app-bridge
    environment:
        - SCREEN_WIDTH=1024
        - SCREEN_HEIGHT=768
networks:
  my-app-bridge:
    driver: bridge
```

and then running this command (or something similar) to kick of the tests and get stdout/err as I need.

```
docker-compose exec -T my-app-under-test npm test
```

**Comment by johanbrandhorst** [comment]
@johnculviner your solution is better than mine, thanks for your response :+1: . I didn't know about `docker-compose exec` until now!

**Comment by drFabio** [comment]
Is there anyway to do that with run without the sleep?
Of doing something like:

1. Run some container with run
2. Run another container with run that will link or use the network to the first one

**Comment by paunin** [comment]
Any updates or workarounds here, guys. That's really sad :(

**Comment by kingbuzzman** [comment]
Agreed. I've come to the same hack independently (the `docker-compose.yml` -- `sleep infinity` and then `docker-compose exec ...`), but i would like the thing to work as one would expect it to run (`docker-compose run ...`).

**Comment by Vanuan** [comment]
Had the same issue (#5147)
It is reported that network aliases should be used with run:

```
version: '2'
networks:
    internal:
        driver: bridge
services:
    slave:
        command: "ash -c 'sleep 1; ping master'"
        image: busybox
        networks:
            internal:
               aliases:
                 - slave
      
    master:
        command: "ping slave"
        depends_on:
            - slave
        image: busybox
        networks:
            internal:
               aliases:
                 - master
      
```
