### ISSUE TITLE
'./docker-compose.yml' service 'version' doesn't have any configuration options. 

### ISSUE THREAD

**Issue by harshsanghani** [docker/compose#4053]
Hello All,

I got the same error and I have tried many solution but I can not get out of this, Can you please help me?

I got this error :- 

In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

docker-compose.yml file :- 

``` yaml
version: '2'
services:
    frontend-server:
    image: node:4
    volumes:
      - ./app:/app:rw
    ports:
      - "3000:3000"
    privileged: true
    command: "/app/run.sh"
```
