### ISSUE TITLE
command clause, how it works?

### ISSUE THREAD

**Issue by PaulWeb** [docker/compose#4054]
I have config:

```
version: '2'
services:
    db: 
        image: "mysql/mysql-server:5.6"
        environment:
         - MYSQL_ROOT_PASSWORD=password
    server:
        image: "php:5.6-apache"
        command: a2enmod vhost_alias 
        ports:
         - "80:80"
        links:
         - db:mysql
```

I want to enable vhost_alias  for apache2, but command doesn't execute. I'm trying example from documentation, from stackoverflow: bash -c and e.t.c

Could you explain how it works and give me tip how to execute command like **a2enmod vhost_alias** without prepare dockerfile?

**Comment by shin-** [comment]
What do you see when you run `docker-compose up`? What leads you to believe the command isn't being executed?

**Comment by PaulWeb** [comment]
logs:
db_1      | 2016-10-22 10:06:19 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1      | 2016-10-22 10:06:19 0 [Note] mysqld (mysqld 5.6.34) starting as process 1 ...
server_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
server_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
server_1  | [Sat Oct 22 10:06:20.374205 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.27 configured -- resuming normal operations
server_1  | [Sat Oct 22 10:06:20.374348 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**and apache2 modules list without vhost_alias**

# apache2ctl -M
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 setenvif_module (shared)
 status_module (shared)
#

**Comment by shin-** [comment]
I'm going to assume you want to configure your server first, and run it afterwards. In which case, you do need to have a `Dockerfile` for the first part - I'm not sure why you wouldn't want that.

Dockerfile:
```
FROM php:5.6-apache
RUN a2enmod vhost_alias
```

Now if you build this image using `docker build -t paulweb/server .` and then run `docker run paulweb/server apache2ctl -M`, you should be able to see the vhost_alias module enable as well.

Your docker-compose.yml then needs to be modified like so:
```yaml
version: '2'
services:
    db: 
        image: "mysql/mysql-server:5.6"
        environment:
         - MYSQL_ROOT_PASSWORD=password
    server:
        build:
          context: .
        ports:
         - "80:80"
        links:
         - db:mysql
```

HTH!
