### ISSUE TITLE
networks option for build

### ISSUE THREAD

**Issue by philtay** [docker/compose#4095]
The --network option for `docker build` has been [recently merged](https://github.com/docker/docker/pull/27702). Please support it in Compose too. Something like this:

``` yaml
build:
  context: ./dir
  networks:
    - some-network
    - other-network
```

**Comment by shin-** [comment]
Thank you for the suggestion - we'll look into it as we get closer to the 1.13 Engine release.

**Comment by philtay** [comment]
1.13.0-rc1 has been released. Any thoughts on this? Thanks

**Comment by dreyks** [comment]
actually 1.13 is already released with the `--network` flag for build. anything new for this issue?

**Comment by gustavosbarreto** [comment]
+1

**Comment by eyz** [comment]
I would like this our environment as well. We have some services are that required during the build process, that should be linked to the building containers for abstraction.

**Comment by brunolm** [comment]
https://stackoverflow.com/a/47545276/340760

```
version: '3.4'
services:
  my_image:
    build:
      context: .
      network: host
```
