### ISSUE TITLE
Proposal: exec shortcuts

### ISSUE THREAD

**Issue by mathroc** [docker/compose#4096]
I'd like to propose a new feature to simplify using `docker-compose exec`.

In some case it could be an alternative #1896

docker-compose.yml example:

```yml
version: "2"
services:
  my_service:
    image: my/service
shortcuts:
  backup:
    service: my_service
    entrypoint: rsync /some/thing
    command: ssh://some.where/
    privileged: true|false
    user: <username>
```

and usage:

```bash
docker-compose sc backup
docker-compose sc backup ssh://some.where.else/
```

or maybe (if `@backup` is not a valid service name)

```bash
docker-compose exec @backup
docker-compose exec @backup ssh://some.where.else/
```
