### ISSUE TITLE
build-args / env during build

### ISSUE THREAD

**Issue by strarsis** [docker/compose#4119]
I want to use env variables - but only for build.
The most elegant approach available now is using build-args.
Edit: The issue was in the Dockerfile, not in the docker-compose.yml and was unrelated.

````
version: '2'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: http://127.0.0.11:3128
        https_proxy: http://127.0.0.11:3128
````
