### ISSUE TITLE
Is it possible to specify the volume's name in docker-compose.yml?

### ISSUE THREAD

**Issue by stolus** [docker/compose#4135]
I know docker will pick up the name as `folder_name + "_"+ volume_key`
But is there any way to specify the name all by myself ? like this?
```
volumes:
      redis_data:
          name: my_redis_data
          driver: local
      mongo_data:
          driver: local
```
