### ISSUE TITLE
env_file with regexps (Feature)

### ISSUE THREAD

**Issue by brunocascio** [docker/compose#4174]
Hi,

What do you think about the ability to add env_files with regexp?

Example:

```
pepe:
    image: pepe
    volumes:
      - mongo_data_dev:/data/db
    env_file:
      - .env.development
      - .env.development.*
```

It should match with the files `.env.development` and for example `env.development.customized` 

Thanks
