### ISSUE TITLE
Support mount point in volumes section of compose file

### ISSUE THREAD

**Issue by yashgt** [docker/compose#4188]
I can define a service with a volume section as:
```yaml
my_server_1:
  image: yashgt/proc1
  volumes:
    - serverlog:/log
```
At the top level I have :
```yaml
volumes:
  serverlog:
    driver: local
```

The physical files go to /var/lib/.... If I want to the files to go to a fixed location on the VM, I need to provide it under the volumes sections of the service as :
```yaml
my_server_1:
  image: yashgt/proc1
  volumes:
    - /mydata/serverlog:/log
```

For each new service that wants to write to the same directory, I need to repeat the path:
```yaml
my_server_2:
  image: yashgt/proc1
  volumes:
    - /mydata/serverlog:/log
```
It will help if we are allowed to provide the path at the top level volume definition such as :
```yaml
volumes:
  serverlog:
    driver: local
    path : /mydata/serverlog
```

**Comment by shin-** [comment]
Hi,

A named volume and a host folder mount are two different things, even if they use similar syntaxes. It seems your issue would be better solved using variable substitution: https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by vaclav-doubek** [comment]
Slightly late but I recommend to try Local Persist Plugin. That's do exactly what do you need.
https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins

Top volumes definitions then look like:

```yaml
volumes:
  my-volume:
    driver: local-persist
    driver_opts:
      mountpoint: /data/local-persist/data
```
