### ISSUE TITLE
what's the different between 'driver' and 'network_model' in yaml?

### ISSUE THREAD

**Issue by suliangxd** [docker/compose#4195]
what's the different between 'driver' and 'network_model' in yaml file?

**Comment by aanand** [comment]
Docker Engine comes with several network drivers out of the box - e.g. `bridge`, `overlay`. You can choose a driver when defining a custom network, e.g.

    $ docker network create --driver=overlay mynetwork

You can then start a container that's connected to that network:

    $ docker run --net=mynetwork ...

Alternatively, you can connect the container to one of the 3 out-of-the-box networks:

    $ docker run --net=bridge ...
    $ docker run --net=host ...
    $ docker run --net=none ...

OR, you can re-use the network stack of another container:

    $ docker run --net=container:abc123 ...

In Compose, the `driver` key is used when [defining a custom network](https://docs.docker.com/compose/networking/#/specifying-custom-networks), much like the `--driver` argument to `docker network create. Here's what that looks like:

```yaml
version: '2'
networks:
  mynetwork:
    driver: overlay
services:
  web:
    networks: ["mynetwork"]
```

The `network_mode` key is used if you want to connect a service to one of the default networks, or another service/container's network stack. This is similar to the `--net` argument to `docker run`. You **can't** combine this with a custom network.

```yaml
version: '2'
services:
  web:
    network_mode: bridge
```

These are the [permitted values for `network_mode`](https://docs.docker.com/compose/compose-file/#networkmode):

```yaml
network_mode: "bridge"
network_mode: "host"
network_mode: "none"
network_mode: "service:[service name]"
network_mode: "container:[container name/id]"
```
