### ISSUE TITLE
false variable-not-set WARNING when variable is set via --env

### ISSUE THREAD

**Issue by erikj** [docker/compose#4205]
Using variable substitution and format versions 1 and 2 (I don't have 2.1 available), a false variable-not-set `WARNING` and erroneous *'Defaulting to a blank string'* message are output when variable is set via `-e` / `--env` and `run` and `up` are invoked.

_E.g._

```yaml
version: "2"

services:
  app:
    image: alpine
    environment:
      FOO: "${FOO}" # and same results for $FOO and ${FOO}, quoted and unquoted
```
```sh
$ echo $FOO # nothing up this sleeve
=>
$ docker-compose run -e "FOO=BAR" app sh
=> WARNING: The FOO variable is not set. Defaulting to a blank string.
/ # echo $FOO
=> BAR
```

Experiencing this w/ **Compose** versions `1.7.1` and `1.9.0`.

Expected result: no `WARNING` about variable not being set when variable is set via `-e`.

**Compose** is an awesome tool, thanks!

**Comment by shin-** [comment]
Thanks for the report - we'll look into it!

**Comment by Kriegslustig** [comment]
@shin are you sure that this is actually a bug? It seems like expected behaviour to me. The warning is shown while `docker-compose` does variable substitution. These variables are have no direct relation to environment variables inside the  container. Here's an example illustrating the difference:

```
version: "2"

services:
  app:
    image: alpine
    environment:
      FOO: "${TEST}"
```

Setting the container environment variable directly:
```
$ docker-compose run -e 'FOO=BAR' app sh -c 'echo FOO=$FOO'
=> WARNING: The TEST variable is not set. Defaulting to a blank string.
FOO=BAR
```

Setting it through a docker-compose environment variable:
```
$ TEST=BAR docker-compose run app sh -c 'echo FOO=$FOO'
FOO=BAR
```

Which is totally correct IMO.
