### ISSUE TITLE
/etc/hostname content mismatch when using docker-compose

### ISSUE THREAD

**Issue by JoyceBabu** [docker/compose#4217]
When I use 

```bash
$ docker run -ti --rm -h test.example.com ubuntu bash
root@test:/# hostname       
test.example.com
root@test:/# hostname -s
test
root@test:/# hostname -d
example.com
root@test:/# hostname -f
test.example.com

root@test:/# cat /etc/hostname
test.example.com
```

But when using docker compose, I am getting

```bash
$ docker exec -ti test bash
root@test:/# hostname       
test.example.com
root@test:/# hostname -s
test
root@test:/# hostname -d
example.com
root@test:/# hostname -f
test.example.com

root@test:/# cat /etc/hostname
test
```

**docker-compose.yml**
```yml
version: "2"
services:
    test:
        container_name: test 
        image: ubuntu
        hostname: test
        domainname: example.com
        tty: true
        stdin_open: true
```
<hr>
I am getting the same output even when using

``` yml
hostname: test.example.com
```
instead of 
```yml
hostname: test
domainname: example.com
```
