### ISSUE TITLE
Outgoing network firewall configuration

### ISSUE THREAD

**Issue by jrmoserbaltimore** [docker/compose#4246]
As an addendum to Docker issue https://github.com/docker/docker/issues/29407

In the event the above feature is implemented, corresponding update to `docker-compose` should provide a `firewall` section:

```
wordpress:
  image: wordpress:fpm
  firewall:
    outgoing:
      - ":state:established,related:accept"
      - "dns.example.com:udp:53:accept"
      - "!10.0.0.0/8:tcp:80,443,21:accept"
      - "::reject"
```
