### ISSUE TITLE
`docker-compose logs` returns inconsistent logs

### ISSUE THREAD

**Issue by bitliner** [docker/compose#4263]
I run in a terminal `docker-compose up`

and it prints to console the log entries for all contains.

But if in another terminal I run `docker-compose logs api` to print log entires of one single container, then it prints to the console some more entry that it was not printed in the first terminal.

This creates quite enough confusion to me, and it makes me think that docker-compose is not a reliable tool.

**Comment by shin-** [comment]
Hi,

Thank you for taking the time to file a report. Could you provide more information? 

- What version of Compose are you running? 
- What version of Docker are you running?
- What OS are you running on? 
- What is the service's configuration? 
- Is there an apparent pattern in the lines that seem to be missing from the `up` logs?

**Comment by bitliner** [comment]
`docker-compose version 1.8.1, build 878cff1`
`Docker version 1.12.2, build bb80604`
`Darwin stos-mbp.home 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64`

docker-compose.yml

```
version: '2'
services:
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
  api:
    image: node:6-alpine
    command: node /myapp.js
    environment:
      - REDIS_HOST=redis
    ports:
      - 4018:3018
    links:
      - "redis:redis"
    volumes:
      - "${PWD}/packages/:${PWD}/packages/"
    depends_on:
      - redis
  worker1:
    image: node:6-alpine
    command: node worker1.js
    environment:
      - REDIS_HOST=redis
    links:
      - "redis:redis"
    volumes:
      - "${PWD}/packages/:${PWD}/packages/"
    depends_on:
      - redis
    restart: on-failure
```

Regarding the apparent pattern in the lines that seem to be missing, it looks like
