### ISSUE TITLE
--force-recreate should removes the old container

### ISSUE THREAD

**Issue by brunocascio** [docker/compose#4273]
I'm trying to recreate the containers after to rebuild an image (using `docker-compose up -d --build --force-recreate`) and I seem that it does not work properly. Now, I'm using `docker-compose down && docker-compose up -d` but would be cool if I can recreate them without the `down` command.

```
version: '2.1'

services:
  wordpress:
    build: .
    image: fbt-wpsite:${VERSION:-latest}
    volumes:
      - ./uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
    env_file: .env
    environment:
      - VIRTUAL_HOST=$DOMAIN
      - VIRTUAL_PORT=9000
    restart: unless-stopped

  mysql:
    image: mariadb
    volumes:
      - ./.mysql:/var/lib/mysql
    env_file: .env
    restart: unless-stopped

  server:
    image: jwilder/nginx-proxy
    ports:
      - ${PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
```

Dockerfile:

```
FROM wordpress:4-php7.0-apache

COPY ./plugins /var/www/html/wp-content/plugins
COPY ./theme /var/www/html/wp-content/themes/fbt
```

**Comment by shin-** [comment]
Hi @brunocascio,

What about it seems to "not work properly"? What challenges are you encountering?

**Comment by brunocascio** [comment]
Hi @shin- 

The container is created from the old image instead of the new building image.

**Comment by shin-** [comment]
Oh, I see! Do you get the results you expect if you do `docker-compose build && docker-compose up -d --force-recreate` instead?

**Comment by brunocascio** [comment]
@shin- 

Nop, I need to run `down` as well.

This is my bash script (it works):

```
cd www \
        && git pull origin qa \
        && docker-compose build \
        && docker-compose down \
        && docker-compose up -d
```

but using

```
cd www \
        && git pull origin qa \
        && docker-compose build \
        && docker-compose up -d --force-recreate
```

doesn't work.

**Comment by Umkus** [comment]
I'm currently having the same issue.

`docker-compose up -d --force-recreate` recreates the container from the image which it was run with originally, and not with the updated one (pulled just a minute ago). Only a `docker-compose down` actually forces the creation of container from the new image.

Image building is not involved at all in my case.

I tried to create a reproducing scenario in smaller scale, but strangely it worked. Must be an edge case somewhere...

**Comment by Umkus** [comment]
So, my issue is the following:
Right after the `docker-compose pull` I am getting different results if I run the same command on a new container (`docker run`) and in a just recreated container (`docker-compose up -d --force-recreate` and then `docker exec`). 

I can run `docker-compose up -d --force-recreate` all day, but will only have container created out of the more recent image if I explicitly remove that container first.

@shin- 
Could you please confirm that this is an error case?

**Comment by Umkus** [comment]
Turns out this was due to the volume definition in `Dockerfile`, as discussed in #2127. After removing the `VOLUME` clause the `--force-recreate` started working again.

**Comment by mauricios** [comment]
@Umkus I'm using `Docker version 18.06.1-ce, build e68fc7a` and I can use the following command to recreate anonymous volumes:

```bash
docker-compose up -d --build --force-recreate --renew-anon-volumes db
```

It seems the flag `--renew-anon-volumes` was recently added

**Comment by ijc** [comment]
Sounds like this was fixed via the addition of that new flag? Closing on that basis, please reopen if I got the wrong end of the stick.

**Comment by ZEB1CLJ** [comment]
I am having the same issue with a jenkins container.
My `docker compose` command is:
```
docker compose \
    --file Dockercompose.yaml \
    --progress plain \
    up \
    --detach \
    --build \
    --force-recreate
```
For the sake of completeness, my `Dockerfile.yaml` looks like this:
```
services:
  jenkins-autoconfigured:
    image: jenkins:jcasc
    network_mode: host
    container_name: jenkins-autoconfigured
    build:
      dockerfile: ./Dockerfile
      context: .
      network: host
      args:
        - JENKINS_ADMIN_ID=admin
        - JENKINS_ADMIN_PASSWORD=admin
```

I've noticed that the following changes to the `Dockerfile` (not shown here) have absolutely no effect on the container:
- changes in files used by the `COPY` instruction 
- changes to environment variables exported using the `ENV` directive

As others have previously stated, I have to manually remove the containers if I want docker compose to recreate them properly. (By the way: what **exactly** does `recreate` do? Does it delete the container or not?)
