### ISSUE TITLE
Make non-default .env-File available in networks-section

### ISSUE THREAD

**Issue by BlkChockr** [docker/compose#4286]
Hi guys, 

I just noticed one can specify a .env-file for services, but not under "networks".

Why is that? I have an .env file which includes the subnet for my application and would like to use it as a variable for a network.

Example:

```
networks:
  example:
    env_file:
      - ./docker/dev.env
    driver: bridge
    ipam:
      config:
      - subnet: ${PROJECT_NETWORK}
```

It works when using the default `.env` in the root folder of the project, though.

**Comment by akalipetis** [comment]
@BlkChockr `.env` files expose variables that can be substituted inside the `docker-compose.yaml` file - this includes every section. In your example, if you have a `PROJECT_NETWORK=foo` in your `.env` file, you'll have the following result:

```
networks:
  example:
    env_file:
      - ./docker/dev.env
    driver: bridge
    ipam:
      config:
      - subnet: foo
```

The `env_file` directive is for services only, since it describes the environment that will be exposed **inside** the container.
