### ISSUE TITLE
Docker inter-container linking using compose script.

### ISSUE THREAD

**Issue by kvramana** [docker/compose#4295]
I have a docker-compose.yml script with two services in it. The first service is a NODEJS service and second service is a HAPROXY service that fronts NODEJS service.  

My versions are: 

- Docker version 1.12.5, build 7392c3b
- docker-compose version 1.9.0, build 2585387

The inter-container linking from HAPROXY to NODEJS is not working and here is the docker-compose.yml script:
```
version: '2'

services:
  # The NODEJS service for application.
  svc_nodejs:
    image: node:6.9.2-alpine
    volumes:
      - $PWD:/code
#    ports:
#      - 7777:7777 # Don't give a port mapping container, so Docker can be scaled out with its dynamic port assignment.
    command: npm install
    entrypoint:
      - node
      - /code/server.js

  # The HAPROXY service to provide high-availability, load balancing and proxying to NODEJS service.
  svc_haproxy:
    image: dockercloud/haproxy
    depends_on:
      - svc_nodejs
    links:
      - svc_nodejs
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
#    volumes:
#      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 80:80
```

Please let me know if i am missing any steps.

Thanks,
Venky.

**Comment by shin-** [comment]
I would avoid using `links` in favor of connecting both services to the same network instead. Something like this:
```
version: '2.1'
services:
  svc_nodejs:
    ...
    networks:
      - hanet
  svc_haproxy:
    ...
    networks:
      - hanet
networks:
  hanet: {}
```

Let me know if that helps.

**Comment by kvramana** [comment]
Nope it did not help, and i see this error when i try to UP services:

> svc_haproxy_1  | INFO:haproxy:Haproxy is running using legacy link, loading HAProxy definition from environment variables: unable to connect to docker daemon ('Connection aborted.', error(2, 'No such file or directory'))
> svc_haproxy_1  | INFO:haproxy:dockercloud/haproxy PID: 7
> svc_haproxy_1  | INFO:haproxy:=> Add task: Initial start - Legacy Mode
> svc_haproxy_1  | INFO:haproxy:=> Executing task: Initial start - Legacy Mode

Given below is my docker-compose.yml:
```
version: '2.1'

networks:
  hanet: {}

services:
  # The NODEJS service for application.
  svc_nodejs:
    image: node:6.9.2-alpine
    volumes:
      - $PWD:/code
#    ports:
#      - 7777:7777 # Don't give a port mapping container, so we Docker can dynamically assign a port.
    command: npm install
    entrypoint:
      - node
      - /code/server.js
    networks:
      - hanet

  # The HAPROXY service to provide high-availability, load balancing and proxying to NODEJS service.
  svc_haproxy:
    image: dockercloud/haproxy
    depends_on:
      - svc_nodejs
#    links:
#      - svc_nodejs
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
#    volumes:
#      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 80:80
    networks:
      - hanet

```

**Comment by kvramana** [comment]
Did compose 2.1 version, networks work for anyone using (any) haproxy? Or this is a bug?

**Comment by kvramana** [comment]
@shin- do you have any more suggestions, perhaps this is a bug?

**Comment by kvramana** [comment]
@aanand hi, can you help with this issue?

**Comment by kvramana** [comment]
Running docker CLI for nodejs and haproxy successfully links them:
```
docker run -d -p 7777:7777 -v $PWD:/code   --name svc_nodejs  node:6.9.2-alpine node /code/server.js
docker run -d -p 80:80  --link svc_nodejs --name svc_haproxy dockercloud/haproxy:1.6.2
```

But the same nodejs and haproxy can't be linked from within compose script!!

**Comment by shin-** [comment]
Please see the instructions [here](https://hub.docker.com/r/dockercloud/haproxy/) for running HAProxy with Compose v2.
Here's an updated Compose file that should work:
```yaml
version: '2.1'

networks:
  hanet: {}

services:
  # The NODEJS service for application.
  svc_nodejs:
    image: node:6.9.2-alpine
    volumes:
      - $PWD:/code
    ports:
      - 7777
    command: npm install
    entrypoint:
      - node
      - /code/server.js
    networks:
      - hanet

  # The HAPROXY service to provide high-availability, load balancing and proxying to NODEJS service.
  svc_haproxy:
    image: dockercloud/haproxy
    depends_on:
      - svc_nodejs
    links:
      - svc_nodejs
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - hanet
```
