### ISSUE TITLE
extends not supported in version 3 schema

### ISSUE THREAD

**Issue by chaosk** [docker/compose#4315]
I'm running Docker 1.13.0-rc4 and current master (545153f117a0be523eeaaed05b2458700a9e856d) of Compose.

I tried to deploy a stack using following docker-compose.yml file:
```
version: "3"
services:
  base:
    image: hello-world
  extending:
    extends: base
    labels:
      - "label=test"
```

Got following in response:
```
$ docker stack deploy --compose-file ./docker-compose.yml test
Compose file contains unsupported options:

extends: Support for `extends` is not implemented yet. Use `docker-compose config` to generate a configuration with all `extends` options resolved, and deploy from that.
```

I found an issue about it in Docker's repo (docker/docker#29304) and attempted to run the command given by the error message, which resulted in:
```
$ docker-compose config
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.extending: 'extends'
```

**Comment by shin-** [comment]
cc @dnephin

**Comment by chaosk** [comment]
I've been wondering, wouldn't adding [compose/config/config_schema_v2.1.json#L124-L140](https://github.com/docker/compose/blob/e063c5739fedeb56450075920451e3fd8b57a826/compose/config/config_schema_v2.1.json#L124-L140) to config_schema_v3.0.json work? I tried doing that locally and it generated output correctly, but I guess it could be breaking other uses.

**Comment by lemats** [comment]
Note for others struggeling with this issue:

Regarding to the docs:
"extend" is NOT yet supported with a version 3 compose file.


https://docs.docker.com/compose/compose-file/#extends
> This option is not yet supported when deploying a stack in swarm mode with a (version 3) Compose file. Use docker-compose config to generate a configuration with all extends options resolved, and deploy from that.

**Comment by viztastic** [comment]
Do we know which version of docker 'extends' will be supported in compose v3? Even if just Indicative?

**Comment by byrnedo** [comment]
I've tried the `docker-compose config` command and it says the same error.
Resorted to perl: https://gist.github.com/byrnedo/7ac5e461ba0866299fdd94899bebdbd9

**Comment by nicodmf** [comment]
+1 for supporting extend in v3

**Comment by ABitMoreDepth** [comment]
Would it be a lot of effort to support the use of `extends` when using docker-compose not in swarm mode?

I use extends to manage production, development and test setups and would like to continue doing so outside of swarm mode, but eventually use `docker stack deploy` with the production variant.  I can probably use @byrnedo's script above to achieve the latter, but I'm blocked running `docker-compose up` on a v3 file containing extends... :/

**Comment by nicodmf** [comment]
This is the same for me, extends is a really usefull option, which for know cause a hole in hour workflow deployment

**Comment by willseward** [comment]
The docs seem a bit misleading ATM:

> Note: This option is not yet supported when deploying a stack in swarm mode with a (version 3) Compose file. Use docker-compose config to generate a configuration with all extends options resolved, and deploy from that.

**Comment by artheus** [comment]
@willseward I strongly agree with you on this. `docker-compose config` should obviously be able to use the extends configuration keyword even when using version 3, according to the documentation.

It's a very ugly hacky solution to do what I'm forced to do right now:
```bash
$ docker-compose config | sed "s#version: '2\.1'#version: '3'#g"
```

**Comment by shouze** [comment]
@dnephin @shin- @vdemeester can I contribute to add back support of extends for v3.x?

What have to be done? I've quickly looked & I guess that this project has to be patched, but at least https://github.com/aanand/compose-file too.

**Comment by shouze** [comment]
@dnephin ok so I've seen you've moved aanand/compose-file to https://github.com/docker/docker/commit/f5af9b9738892b5988f987ce5fbce6e31a10e768 so docker-compose & docker repos needs to be patched in fact.

**Comment by arun-gupta** [comment]
What was the reason for removing `extends` from v3?

**Comment by shouze** [comment]
@arun-gupta I guess it's because a lot of docker-compose files parsing is also now done in go in docker engine source code and it's not have been ported from python ATM cc @dnephin right?

If yes, the question is to know if it's planned to bring it back or no. Would be nice to also know - if it's a deprecation - if another mecanism is planned to merge some properties from some kind of abstract services (which is the main use case of extends for everyone I guess).

**Comment by jkirkby91-2** [comment]
found this issue, for the same reason as others have already mentioned.

I've upgraded to docker-compose v3 to take advantage of some new docker-swarm features, but now extends is no longer supported? WHY!!

It is such a useful option for writing clean dockerfiles and managing services in different environments. 

+1 for bringing this back

**Comment by Richard-Mathie** [comment]
@arun-gupta welcome to how the docker dev's roll out new features, depreciating old sensible functionality for new stuff which hasn't been released yet. Its like a great wet fish in the face, This morning I was all like

> yay finally compose 3 adds deploy so I can use it with swarm instead of loads of bash scripting.

20 seconds later

> what they removed "extents"....whyyyyyy... there is no god!

**Comment by Electron-libre** [comment]
Damned I just spent the day to build a nice extend layout for our services.
Hopefully I do not need the v3 features and will be able to downgrade to the 2.1.

I feel less confident now to justify the time invested in our docker stuff :( 
I hope it wont get worse

**Comment by tmornini** [comment]
This page of the documentation:

    https://docs.docker.com/compose/compose-file/compose-versioning/

Is also rather misleading in the section "Upgrading Version 2.x to 3.x"

There is zero mention of extends being removed. :-(

**Comment by Electron-libre** [comment]
I am working on documentation fix.

**Comment by willseward** [comment]
I really believe that with the swarm inter-compatibility, the `extends` key becomes more important than ever

**Comment by shin-** [comment]
At the end of the day, this is dependent on Docker Engine supporting the feature -as a result, I created docker/docker#31101 to track that possibility. Please voice your concerns there if this feature is important to your project!

**Comment by willseward** [comment]
Thanks @shin-. I would even be happy if `docker-compose config` would flatten the files. Then I could use the resulting compose file with Swarm.

Maybe something like this?

```
docker-compose config -f docker-compose.yml -f docker-compose.prd.yml | docker stack deploy --
```

That'd be acceptable...

**Comment by shouze** [comment]
@willseward yes should be cool & a great 1st step probably... but couldn't address a last issue (which was a very kind feature): abstract services.

I don't know if you have some but personally - and I'm not the only one - I have this kind of configs very often in some `common-services.yml` files (that I use like that `docker-compose config -f common-services.yml -f docker-compose.yml`)

```yml
services:
    some_service-abstract:
        build:
            context: .
        environment:
            - SOME_VAR
        image: vendor/service:tag
        networks:
            - somenet
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:17110"
                env: SOME_VAR

    some_service:
        extends:
            file: ./common-services.yml
            service: some_service-abstract
        environment:
            - LISTEN_ON_PORT=8888
        expose:
            - "8888"
        command: server
        networks:
            - some_other_net

    some_service-worker:
        extends:
            file: ./common-services.yml
            service: some_service-abstract
        command: worker_cmd
        networks:
            - some_other_net_take_two
```

So basically @shin- @vdemeester @dnephin what are recommandations for this use case?
Do you recommend to duplicate that in every service & every service env? Is there any other tricks?
```yml
        build:
            context: .
        environment:
            - SOME_VAR
        image: vendor/service:tag
        networks:
            - somenet
        logging:
            driver: gelf
            options:
                gelf-address: "udp://127.0.0.1:17110"
                env: SOME_VAR
```
