### ISSUE TITLE
v2.1: Healthcheck condition overridden by additional compose file.

### ISSUE THREAD

**Issue by Billiam** [docker/compose#4355]
Adding a docker-compose.override.yml causes the `service_healthy` under depends_on.condition to be replaced with the default `service_starting` value instead.

### docker-compose.yml
```yml
version: '2.1'

services:
  main:
    image: alpine
    command: /usr/bin/top
    depends_on:
      secondary:
        condition: service_healthy

  secondary:
    image: alpine
    command: /usr/bin/top
    healthcheck:
      test: exit 1
```

```shell
$ docker-compose --version
docker-compose version 1.10.0, build 4bd6f1a
$ docker-compose config
networks: {}
services:
  main:
    command: /usr/bin/top
    depends_on:
      secondary:
        condition: service_healthy
    image: alpine
  secondary:
    command: /usr/bin/top
    healthcheck:
      test: exit 1
    image: alpine
version: '2.1'
volumes: {}
```

But, after adding a docker-compose.override.yml:

### docker-compose.override.yml
```yml
version: '2.1'

services: {}
```

```shell
$ docker-compose config
networks: {}
services:
  main:
    command: /usr/bin/top
    depends_on:
      secondary:
        condition: service_started
    image: alpine
  secondary:
    command: /usr/bin/top
    healthcheck:
      test: exit 1
    image: alpine
version: '2.1'
volumes: {}
```

**Comment by shin-** [comment]
Thanks for the report. Will be fixed by #4350

**Comment by alejandrogalera** [comment]
It's very nice to be able to use

```
services:
  main:
    image: alpine
    command: /usr/bin/top
    depends_on:
      secondary:
        condition: service_healthy
```
Unfortunately, this is not compatible with the possiblitity to set service name in depends_on section parametrizable.

For example, I can do:
```
service:
  myservice:
    image...
    depends_on:
    - ${DB_TYPE}

  sqlserver:
    image...
    
  oracle:
    image...
```

Both options are possible with this version 1.29.0 docker-compose.

Unfortunately, I cannot do:
```
service:
  myservice:
    image...
    depends_on:
      ${DB_TYPE}
        condition: service_healthy
```

I'd like very much to be able to parametrize service name with env var in .env, for example.

**Comment by alejandrogalera** [comment]
It's very nice to be able to use

```
services:
  main:
    image: alpine
    command: /usr/bin/top
    depends_on:
      secondary:
        condition: service_healthy
```
Unfortunately, this is not compatible with the possiblitity to set service name in depends_on section parametrizable.

For example, I can do:
```
service:
  myservice:
    image...
    depends_on:
    - ${DB_TYPE}

  sqlserver:
    image...
    
  oracle:
    image...
```

Both options are possible with this version 1.29.0 docker-compose.

Unfortunately, I cannot do:
```
service:
  myservice:
    image...
    depends_on:
      ${DB_TYPE}
        condition: service_healthy
```

I'd like very much to be able to parametrize service name with env var in .env, for example.
