### ISSUE TITLE
docker-compose run: healthcheck not detecting if one of the services failed to start

### ISSUE THREAD

**Issue by cmaftuleac** [docker/compose#4420]
Basically I have the following docker-compose file
By default tests run a noop, and manually I run them using:
    docker-compose run tests runtest_command.sh

It works fine, the tests service wait for the app to start, and so on.
But if there is an error in starting of the 'app' service and is has failed to start, then the 'tests' service starts anyway, not regarding to the fact that 'app' container is dead.

```
version: '2.1'

volumes:
  mavencache: {}

services:
  schema:
    build: schema
    links:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=dbpassword123
      - MYSQL_DATABASE=pvwebdb
    depends_on:
      mysqldb:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile.pvweb
    volumes:
      - mavencache:/root/.m2
    ports:
      - "5005:5005"
      - "8585:8585"
      - "8586:8586"
    links:
      - schema
    healthcheck:
      test: "curl -f http://localhost:8585/login"
      interval: 1s
      retries: 120
    depends_on:
      mysqldb:
        condition: service_healthy

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - mavencache:/root/.m2
    links:
      - app
    depends_on:
      app:
        condition: service_started
      mysqldb:
        condition: service_healthy

  mysqldb:
    build:
      context: .
      dockerfile: Dockerfile.mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=dbpassword123
    ports:
      - "3306:3306"
    healthcheck:
      test: "nc -z localhost 3306"
      interval: 1s
      retries: 120

```
