### ISSUE TITLE
Unsupported config option 'healthcheck' with version 2.1 syntax

### ISSUE THREAD

**Issue by bperel** [docker/compose#4440]
Using the following docker-compose.yml:
```yaml
version: '2.1'
services:
  db:
    image: "<my_image>"
    healthcheck:
      disable: true
```

I get the following error when running docker-compose up :

```bash
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.db: 'healthcheck'
```

According to [the documentation](https://docs.docker.com/compose/compose-file/#version-21), "healthcheck" should be supported with the currently installed versions:

```bash
$ docker --version
Docker version 1.13.0, build 49bf474
```

```bash
$ docker-compose --version
docker-compose version 1.9.0, build 2585387
```
