### ISSUE TITLE
Docker stack deploy does not support systemd containers (cap_add, tmpfs)

### ISSUE THREAD

**Issue by jamshid** [docker/compose#4441]
Nobody *wants* to run systemd in a container, but it's necessary because not all software is docker-ready, or docker is being used to simulate a production system.  

It's great that docker 1.13 can now deploy a docker-compose.yml to swarm, but the limited configuration support means systemd containers will not run. `docker stack deploy` reports:
```
Ignoring unsupported options: cap_add, devices, privileged, security_opt, tmpfs
```

When will stack/bundle/dab/whatever support systemd containers, which require `cap_add` and `tmpfs`? 

```
    cap_add:
      - SYS_ADMIN
    tmpfs: /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - container=docker
```
Ref https://github.com/docker/docker/issues/28614#issuecomment-261724902

PS: `devices` would also be very useful especially if the value could somehow be made different on different swarm nodes.
