### ISSUE TITLE
docker-compose network ipam config values are not allowed

### ISSUE THREAD

**Issue by minmay** [docker/compose#4474]
It seems as though either the documentation is wrong, or there is a problem with reading the networks ipam config properties.

Docker Version 1.13.1-beta42 (15350)
Channel: beta
2ffb2b4915
```
version: '3'
...
networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.0.0/24
          gateway: 172.28.0.255
          aux_addreses:
            db: 172.28.0.1
            ui: 172.28.0.5
```
```
$docker-compose up
The Compose file './docker-compose.yml' is invalid because:
networks.test.ipam.config value Additional properties are not allowed ('aux_addreses', 'ip_range', 'gateway' were unexpected)
```
