### ISSUE TITLE
The project name should be configurable

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#45]
Ideally in `fig.yml` (how do we have general config in there? maybe we need a top level `services` key?), but maybe in a separate `.fig-project` file or something.

**Comment by mikehaertl** [comment]
+1 

Any news on this? There was an interesting suggestion by @jderusse here, which i like very much:
https://github.com/docker/compose/issues/745#issuecomment-74028861

**Comment by jderusse** [comment]
The problem with your proposals, is that you'r mixing project configuration and service declaration. it's less readable and adding a keyword (projet or .project) can break backward compatibility.

I realy thinks it's time for docker-compose to improve it schema by adding a top level structure wich contains services. 
```
containers:
  web:
    ...
  db:
    ...
```

With such structure, we'll be able to improve the schema like
```yaml
schema-version: 1.1
project_name: foo
containers:
  web:
    ...
  db:
    ...
```
or 
```yaml
schema-version: 2.0
project: 
  name: foo
  default_env_file: ./bar
containers:
  web:
    ...
  db:
    ...
```

Notice the property schema-version which help us keep backword compatibilities with schema evolutions.
And to keep BC with current schema, in compose/project.py::from_config
```
    @classmethod
    def from_config(cls, name, config, client):
        if 'schema-version' not in config or not isinstance(config['schema-version'], basestring)
            config = {
                'schema-version': '1.0',
                'containers': config
            }
        dicts = []
        for service_name, service in list(config.containers.items()):
            if not isinstance(service, dict):
                raise ConfigurationError('Service "%s" doesn\'t have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.' % service_name)
            service['name'] = service_name
            dicts.append(service)
        return cls.from_dicts(name, dicts, client)
```

If I've time, i'll work on a patch proposal in the nexts days.

**Comment by yegortokmakov** [comment]
I have two projects that are using docker compose, one dependent on the other. For this use-case it will be great to have something like dependent projects:

```yaml
schema-version: 2.0
project: 
  name: foo
  default_env_file: ./bar
require:
  project2:
    config: PATH | URL
    services:
      - serv1
      - serv2
    detached: true
containers:
  web:
    ...
  db:
    ...
```

I am posting it there because it seems like relative to #1233 
Does it makes sense? If yes, I will make it based on @jderusse code.
