### ISSUE TITLE
Support expanded port syntax

### ISSUE THREAD

**Issue by dnephin** [docker/compose#4502]
See https://github.com/docker/docker/pull/30476

```yaml
version: "3.1"
services:
  nginx:
    image: nginx
    ports:
      - mode: host
        target: 80
        published: 9005
```
