### ISSUE TITLE
Add support for declaring Docker 1.13 Secrets in compose file

### ISSUE THREAD

**Issue by lsapan** [docker/compose#4510]
The support for compose with `docker stack deploy` in 1.13 is *absolutely wonderful*. It would be just that much more wonderful if we didn't need to do a ton of these after deploying:

```
docker service update --secret-add DB_USER web
docker service update --secret-add DB_PASS web
docker service update --secret-add AWS_ACCESS_KEY_ID web
docker service update --secret-add AWS_SECRET_ACCESS_KEY web

docker service update --secret-add DB_USER celery
docker service update --secret-add DB_PASS celery
docker service update --secret-add AWS_ACCESS_KEY_ID celery
docker service update --secret-add AWS_SECRET_ACCESS_KEY celery

...etc
```
Granted these can somewhat be combined, but it's still cumbersome.

Something like this would be amazing:
```
version: '3'
services:
    web:
        ...
        deploy:
            ...
            secrets:
                - DB_USER
                - DB_PASS
                - AWS_ACCESS_KEY_ID
                - AWS_SECRET_ACCESS_KEY
```

**Comment by brettmc** [comment]
The official documentation hasn't caught up yet, but you can do this with compose file version 3.1 and docker engine v1.13.1. The secret can be based on a file, or a secret that has already been created on the swarm via `docker secret create`
The accepted answer for this stack overflow question explains it well: http://stackoverflow.com/questions/42139605/how-do-you-manage-secret-values-with-docker-compose-v3-1

Here's an example of using a secret, `my_secret`, that's been created on the swarm via `docker secret create`:
```yaml
version: '3.1'
secrets:
  my_secret:
    external: true
services:
  my_service:
    image: ...
    secrets:
      - my_secret
```

**Comment by lsapan** [comment]
Perfect, thanks a ton!

**Comment by ksachdev1** [comment]
I have a question on the documentation and the way above example is listed. While I understand everywhere we say that create a separate "secret" block and then under the service, create the secret block and proceed. I did not create a separate secret block and simply added the following under my service
 secrets:
      - source: "nginx_key_ext"
        target: "nginx.key"
      - source: "nginx_crt_ext"
        target: "nginx.crt"

After I did this, since I already had created external secrets with names "nginx_key_ext" and "nginx_crt_ext", the secrets got mounted with the target names. So why should I go for creating a separate secret block? What am I losing by doing above? Secondly, if I do above but remove the quotes, things don't work. Can a good document be shared on this?

**Comment by japrogramer** [comment]
where is the official documentation for this features? I need to know how fine grain the control is
could i do
```
myservice:
    secrets:
        - source: secret-settings
           target: /app/conf/settings
           mode: 0444
```
is that the correct syntax?
