### ISSUE TITLE
Feature request: creating attachable networks in compose file

### ISSUE THREAD

**Issue by andrewmilson** [docker/compose#4515]
It would be nice to create attachable networks from the Docker Compose file instead of having to create the network through the Docker CLI.

```
networks:
  my-network:
    driver: overlay
    attachable: true
```
