### ISSUE TITLE
docker secret long syntax 'permission denied'

### ISSUE THREAD

**Issue by roneichiarandi** [docker/compose#4527]
This is my compose file to run a test.

```
version: "3.1"

services:
  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=<secret-path>
      - MYSQL_PASSWORD_FILE=<secret-path>
      - MYSQL_USER=user
      - MYSQL_DATABASE=database
    secrets:
      - source: mysql_root_password
        target: mysql_root_password
        mode: 0400
      - source: mysql_password
        target: mysql_password
        mode: 0400

  site:
    image: php:7.1-fpm-alpine
    volumes:
      - ./site:/var/www/html
    ports:
      - 9000:9000
    networks:
      - network
    depends_on:
      - db
    secrets:
      - source: mysql_password
        target: wp_mysql_password
        mode: 0400

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./site:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - network
    depends_on:
      - site

networks:
  network:

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true

volumes:
  db-data:
```

The mysql container logging the error when I use with `mode = 0400`

```
stack_db.1.hgthk2aj50i2@moby    | /usr/local/bin/docker-entrypoint.sh: line 37: /run/secrets/mysql_root_password: Permission denied
```

And up normally when I change the mode to 0777

It's correct?

Thanks
