### ISSUE TITLE
docker-compose run fails for running network_mode=host services

### ISSUE THREAD

**Issue by SpComb** [docker/compose#4548]
For a `network_mode: host` service,

```yaml
version: '2'
services:
  redis:
    image: redis
    network_mode: host
```

```
$ docker-compose version
docker-compose version 1.11.1, build 7c5d5e4
docker-py version: 2.0.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
$ hostname
localhost
$ docker-compose run --rm redis hostname
localhost
```

The `docker-compose run` command fails if the service is running:

```
$ docker-compose up -d redis
Starting composetest_redis_1
$ docker-compose run --rm redis hostname
ERROR: Cannot create container for service redis: Conflicting options: host type networking can't be used with links. This would result in undefined behavior
$ docker-compose stop redis         
Stopping composetest_redis_1 ... done
$ docker-compose run --rm redis hostname
localhost
```

It looks like `docker-compose --verbose run` tries to do some `--link` trickery against the running container, but this is not compatible with the `--net host`:

```

compose.cli.verbose_proxy.proxy_callable: docker create_host_config -> {'Binds': [],
 'Links': ['composetest_redis_1:composetest_redis_1',
           'composetest_redis_1:redis',
           'composetest_redis_1:redis_1'],
 'LogConfig': {'Config': {}, 'Type': u''},
 'NetworkMode': 'host',
 'PortBindings': {},
 'VolumesFrom': []}

ERROR: compose.cli.main.main: Cannot create container for service redis: Conflicting options: host type networking can't be used with links. This would result in undefined behavior
```

Possibly related:  #2480

**Comment by sivabudh** [comment]
I'm also running into the exact same problem. Here are my versions:

```
docker-compose version 1.11.2, build dfed245
Docker version 17.03.1-ce, build c6d412e
```

and here's the gist of my `docker-compose.yml` file: 

(some part redacted)

```
version: '3'

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: DockerfileBackend
    image: 123456.ecr.some-region.amazonaws.com/some-repo:latest
    environment:
      - DATABASE_URL=postgres://postgres:P@ssw0rd@localhost:5432/some_db
    volumes:
      - ./frontend_assets/static_files:/code/static_files
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --worker-class gevent app.config.wsgi:application --log-level=INFO
    ports:
      - "8000:8000"
    network_mode: "host"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: DockerfileFrontend
    image: 123456.dkr.ecr.some-region.amazonaws.com/frontend-repo:latest
    volumes:
      - ./frontend_assets:/code/frontend_assets
```

With this `docker-compose.yml`, the error will happen when the `backend` container is already running **and** we attempt to execute another `docker run` command related to `backend`.

Here's a concrete example. Assuming that **`backend`** is already running, this is the behavior:

```
# When running `frontend` container, there's no problem
docker-compose run frontend cp -rf /code/static_files/ /code/frontend_assets/
# But once you run the `backend` container while there's already one running...
docker-compose run backend python manage.py collectstatic --noinput
```
You will immediately see this error:
```
ERROR: Cannot create container for service backend: Conflicting options: host type networking can't be used with links. This would result in undefined behavior
```

**Comment by usmanm** [comment]
Running into the same issue. There should be a way to bypass the automatic linking that compose is trying to do. The workaround that @sivabudh describes isn't really ideal if the command being run in the second step takes a non-trivial amount of time.

**Comment by sivabudh** [comment]
Agreed with @usmanm on his comments. Fortunately, my app update takes roughly 6 seconds, and we are lucky that our apps can have daily maintenance windows.

**Comment by mroutis** [comment]
This is still relevant :+1:

**Comment by damouse** [comment]
Same issue.

**Comment by tomholub** [comment]
Encountered here too

**Comment by rhoerbe** [comment]
Same issue

**Comment by rhoerbe** [comment]
likewise

**Comment by rhoerbe** [comment]
The reason turned out to be a misleading error message in my case. An instance of the container was in restart mode, and docker compose got confused (I have not links, but network_mode=host)

**Comment by thomas-profitt** [comment]
This is still reproducible in docker-compose version 1.22.0, build f46880f.

`docker-compose run some-container any-command`, where `some-container` is any container that's got `network_mode: host` and is currently `Restarting` or `Up`.

**Comment by nathantsoi** [comment]
same here. this is a problem when i bring up an array of services with `docker-compose up`, one or more of which is designed to be interactive and i need to run `docker-compose run [interactive service] bash -l` to enter that particular container

**Comment by DavidGamba** [comment]
The same problem occurs during `docker-compose build`, `docker build --network host ...` works properly.

**Comment by artm** [comment]
@nathantsoi `docker-compose run ...` does not enter the container, it makes a new container with the same settings. To "enter" a running container you would use `docker-compose exec`.

**Comment by hholst80** [comment]
Two and a half years later, we still have the same problem.

```
$ docker-compose version
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
$ cat docker-compose.yml
version: '2'

services:
  foo:
    image: debian
    command: sleep 99999
    network_mode: host
  bar:
    image: debian
    command: sleep 99999
    network_mode: host
$ docker-compose up -d
docker-compose_bar_1 is up-to-date
docker-compose_foo_1 is up-to-date
$ docker-compose run --rm bar echo hello world
ERROR: Cannot create container for service bar: b"conflicting options: host type networking can't be used with links. This would result in undefined behavior"
$ 
```

**Comment by rhoerbe** [comment]
The problem does not go away by doing nothing, then flagging it as stale, and finally closing the ticket. Bugs need to be fixed, not managed

**Comment by PawelAdamczuk** [comment]
I encountered the same problem.

**Comment by traviswaelbro** [comment]
I am also encountering the same problem on a container with `network_mode: host`.

**Comment by shomeax** [comment]
Got same issue. Trying to run a one-off command to service previously started via `docker-compose` with `network_mode: host` fails with error.
```
# docker-compose --version
docker-compose version 1.25.0, build 0a186604
#  docker-compose run webserver ps
ERROR: Cannot create container for service webserver: conflicting options: host type networking can't be used with links. This would result in undefined behavior
```

**Comment by penkong** [comment]
with 
`docker build -t <image name> --network=host`
it work fine but with docker-compose up --build does not work.
all top hints already tried.

**Comment by matthew-nm** [comment]
Adding my comment to prevent bot from marking as stale. I encountered this issue as well.

`Docker version 19.03.8, build afacb8b`
Had container "up" after `docker-compose up -d`.
Attempted to execute `docker-compose run <service> <command>` and obtained same error message as OP.

Had to bring down container that was "up" before executing `run` command.

**Comment by Skydev0h** [comment]
I workarounded it (at least for openvpn) by creating a sibling container with -cmd prefix without network mode host.
Can be useful to execute commands that modify attached volume and do not require other quirks.

Example:
```yaml
version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    network_mode: host
    pid: host
  openvpn-cmd:
    image: kylemanna/openvpn
    container_name: openvpn-cmd
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
```

And instead of `docker-compose run --rm openvpn easyrsa build-client-full my.client.com` I do `docker-compose run --rm openvpn-cmd easyrsa build-client-full my.client.com`.

**Comment by ivictbor** [comment]
Workaround works but I am using run to prevent downtime. After switching to host mode due to performance considerations run command is useless.

**Comment by MichaelMackus** [comment]
You should be able to also do this if your command is simple enough:

```docker run -it $(docker-compose images -q SERVICE) COMMAND```

Where SERVICE is the service in question in your docker-compose.yml file and COMMAND is the command you want to run. You'll have to add all the relevant args to docker run manually, though.

It would be nice to be able to run services with host mode networking, even if the networking part were disabled.

**Comment by JanJamaszyk-FlyNow** [comment]
I am also seeing the same issue in a different use-case, is there any way to disable the links docker-compose creates automatically?
What is the way forward on this issue? It is open since 3 years, is there any way we can escalate this?

**Comment by bierzorutas** [comment]
Same problem here ... unbelievable how after years this is still present...

**Comment by rkmfl** [comment]
Have you tried changing the version in the docker-config.yml to **3.4**?

```
version: "3.4"
#...trimmed...
network_mode: host
```

This appears to have fixed several issues for me, including the host-mode.

**Comment by chrisawad** [comment]
using version 3.7 and just came across this also

**Comment by MichaelAkvo** [comment]
This is also happening in https://github.com/akvo/akvo-rsr where `network_mode: service:main_network` is being used.

```sh
$ docker-compose up -d
Creating akvo-rsr_rsr-memcached_1 ... done
Creating akvo-rsr_rsrdbhost_1     ... done
Creating akvo-rsr_mainnetwork_1   ... done
Creating akvo-rsr_web_1           ... done
Creating akvo-rsr_reports_1       ... done
Creating akvo-rsr_nginx_1         ... done
$ docker-compose run --rm web echo lol
Starting akvo-rsr_mainnetwork_1 ... done
ERROR: Cannot create container for service web: conflicting options: container type network can't be used with links. This would result in undefined behavior
```

**Comment by Dens49** [comment]
Still relevant. I wanted to use docker-compose run in order to prevent downtime. So having two container of that service running at the same time was my goal.
The workaround of @MichaelMackus works but you have to make sure to set up the docker run command properly which is way more error prone.
Would be nice to be able to keep it all in docker-compose.

**Comment by ndeloof** [comment]
Docker compose v2 doesn't suffer this limitation
```
$docker compose version
Docker Compose version v2.4.1
$ docker compose run --rm redis hostname
docker-desktop
```

**Comment by glours** [comment]
I close the issue, Compose v2 works as expected and Compose v1 is end-of-life
Tested with @hholst80 sample
```shell
> bat compose.yaml
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: compose.yaml
       │ Size: 152 B
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ services:
   2   │   foo:
   3   │     image: debian
   4   │     command: sleep inf
   5   │     network_mode: host
   6   │   bar:
   7   │     image: debian
   8   │     command: sleep inf
   9   │     network_mode: host
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> docker compose up -d
[+] Running 3/3
 ⠿ foo Pulled                                                                                                                                                                                                                            5.6s
   ⠿ cfc947b533a3 Pull complete                                                                                                                                                                                                          3.2s
 ⠿ bar Pulled                                                                                                                                                                                                                            5.6s
[+] Running 2/2
 ⠿ Container issue-4548-foo-1  Started                                                                                                                                                                                                   0.4s
 ⠿ Container issue-4548-bar-1  Started
```

**Comment by SeLub** [comment]
Docker Compose version v2.10.2 

**Error response from daemon: conflicting options: host type networking can't be used with links. This would result in undefined behavior** 


```
  api:
    image: grabli
    restart: on-failure
    container_name: api
    build:
      context: .
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3001
    ports:
      - 3001:3001
    links:
      - mqtt
    depends_on:
      - mqtt
      - googleOauth2
    **network_mode: host**

```

**Comment by ndeloof** [comment]
@simwai `version` in compose file is unrelated (and obsolete)
I can't reproduce issue using latest docker compose release, please provide a reproduction example if you do

**Comment by hholst80** [comment]
Works just fine with latest Compose spec and Docker Engine 26.1.0:

```yaml
# cat compose.yaml 
services:
  foo:
    image: debian
    command: sleep inf
    network_mode: host
  bar:
    image: debian
    command: sleep inf
    network_mode: host
```
