### ISSUE TITLE
"volumes_from: service" fails silently if the service has no containers

### ISSUE THREAD

**Issue by dnephin** [docker/compose#455]
Example:

``` yaml

foo:
    build: .
    volumes_from:
        - configs

configs:
    build: ./configs
    volumes:
        - /etc/something
```

If I run

```
fig run foo
```

The volume is not mounted, without any warnings. This is because it tries to iterate over the containers for `configs`, and none exist yet, so it just skips it and continues.

```
fig up
fig run foo
```

This works.

I propose that if there is a `volumes_from` a service, and there are no containers for that services, it should at lease raise a warning, but possibly error.
