### ISSUE TITLE
config does not validate broken subnets

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#4552]
docker-compose 1.11.2

Broken config, due to missing variable - no error during `config`
```
networks:
  default:
    ipam:
      config:
      - subnet: ''
      driver: default
```

On `docker-compose up`

```
ERROR: Invalid subnet  : invalid CIDR address:
```

Should be thrown already during validation.

**Comment by tilakpatidar** [comment]
This can be fixed by adding a regex pattern for the subnet in config_schema. 
In pull request, a new version of config_schema should be created or the previous version should be updated? I am a beginner need some help.

**Comment by dgageot** [comment]
Here's a full compose file to reproduce the issue:

```
version: '2.1'

services:
  test:
    image: busybox

networks:
  default:
    ipam:
      config:
      - subnet: ''
      driver: default

```
