### ISSUE TITLE
No environment variable interpolation in secrets definitions

### ISSUE THREAD

**Issue by MrHash** [docker/compose#4584]
The following example `secrets` configuration seems to fail to interpolate environment variables provided by a `.env` file.
```
version: "3.1"
secrets:
  couchdb.json:
    file: ${SECRETS_DIR}/couchdb.json
```
