### ISSUE TITLE
Build args from env_files

### ISSUE THREAD

**Issue by fc-arny** [docker/compose#4618]
How use variables from env_file as a build arguments?

I have 2 env_files - .**env** (in repo) and **.env.local** (out of repo).
My docker-compose.yml

```yaml
version: "3"

services:
  app:
    image: "app"
    build:
      context: .
      args:
        VARIABLE: $VARIABLE
    env_file:
      - ./.env
      - ./.env.local
    command: bundle exec puma
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
...
```

Dockerfile
```
FROM ruby:2.3-slim
ARG VARIABLE
...
```

**$VARIABLE** defined in **.env** file and redefined for production in **.env.local**, but when i build image $VARIABLE=(value from .env.file)

```
docker-compose build app
```

Thanx for help.

**Comment by shin-** [comment]
You seem to be confusing host environment and container environment. See this [disambiguation page](https://docs.docker.com/compose/environment-variables/)

**Comment by shin-** [comment]
As this has been answered multiple times before (see for example #4001), I'm going to close this ticket.

**Comment by arielnmz** [comment]
It's still unclear how to pass variables from files declared in `env_file`  to `ARG` to be used at build-time. E.g. this doesn't work for me:

dev.env:

```
FOO=foo
```

docker-compose.dev.yml:

```
version: "3.8"
services:
  lib:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    env_file:
      - dev.env
```

Dockerfile.dev:

```
ARG FOO

RUN echo $FOO
```

Echo prints nothing during build:

    docker compose -f docker-compose.dev.yml build lib --progress plain

**Comment by dm17** [comment]
@arielnmz did you figure it out?

**Comment by arielnmz** [comment]
@dm17 Nope. Apparently there's no way around it, you'd have to provide `arg` variables separately...

**Comment by dm17** [comment]
> @dm17 Nope. Apparently there's no way around it, you'd have to provide `arg` variables separately...

That was unclear to me to before basically debugging it. Now I understand that you can set args: in compose files. And then you can set ARG *on the line before the line you need to use it* (except for some cases) in Dockerfiles. *However* - in the cases you need to us the variable at run time of the image that Dockerfile produces: you need to use both ARG and also ENV in the Dockerfile.

**Comment by abjrcode** [comment]
This shouldn't have been closed. It's build time arguments that might be secrets such as NPM tokens or what not and has nothing to do with runtime environment variables

**Comment by shadiramadan** [comment]
I have some build args like an npm auth token for a private registry.  I want that to just be sourced from a file and not need people to export it to the shell every time.

Agree on re-opening.

Something like a `file` key similar to `env_file` under `build` would be ideal.

**Comment by onionhammer** [comment]
Seems like an obvious gap in the spec, but it's being ignored?

**Comment by guidopetri** [comment]
@shin- any opinion here? I'm also in need of a `arg_file` or similar and found this issue, it's disappointing that it got closed.

**Comment by robertlagrant** [comment]
@shin- should it be possible to use env_file variables as explictly passed build args? E.g.
```yaml
services:
  my_service:
    build:
      context: .
        args:
          MY_VAR: ${MY_VAR}
    env_file:
      - env_file.env
```

Where env_file.env looks like this:
```
MY_VAR=very_important_config
```

**Comment by christianlittle7** [comment]
@shin- 
This really should be re-opened. We can use `docker compose --env-file <file> up -d' to load args in for that use case, but I don't understand why I can't load vars the same way for a docker compose build?

Seems like an extremely necessary feature

**Comment by n4t4l** [comment]
I would love this feature. Currently there's the need to keep track of enviroment variables in the production enviroment, local enviroment, the docker-compose file AND pass args as envvars one by one in the Dockerfile. It's so easy to make a mistake somewhere.

**Comment by Fedcomp** [comment]
Surprised it's still an issue in 2025. Just faced it.
You can use .env file but cannot provide your own env (???)

**Comment by rennokki** [comment]
For @Fedcomp, @n4t4l, @christianlittle7 and for anyone else wondering, this can be done easy with some bash.

You can do something like this:

```bash
cat Dockerfile | grep '^ARG ' | awk '{print $2}' | cut -d'=' -f1 | sort -u | awk '{print "--build-arg " $1}' | tr '\n' ' '
```

What this does is the following:

- Looks for `ARG <variable>` in your Dockerfile
- Takes all the values and deduplicates them
- Creates a long `--build-arg <variable>` chain for all of your Dockerfile `ARG`s.

For example:

```dockerfile
FROM scratch

ARG VARIABLE
ARG AWS_REGION
```

The command will create: `--build-arg VARIABLE --build-arg AWS_REGION`.

Incorporate this into your build command:

```bash
docker-compose build app $(cat Dockerfile | grep '^ARG ' | awk '{print $2}' | cut -d'=' -f1 | awk '{print "--build-arg " $1}' | tr '\n' ' ')
```

I think it's beautiful because if you pass `env_file` or `environment` in your compose file, they will be pulled automatically, even if they are `--build-arg VARIABLE` and not `--build-arg VARIABLE=some_value`, so no need to parse the variables yourself.

Unfortunately, I found no cleaner way to do so. Best way I think would be to use [Taskfile](https://taskfile.dev) as alternative to `Makefile` that has a better learning curve, or use [varlock](https://varlock.dev) to make the envfiles more manageable.

Bonus: not related to the problem, but you can mark `.env.local` optional:

```yaml
version: "3"

services:
  ...
  env_file:
    - path: .env
      required: true
    - path: .env.local
      required: false
...
```

This way, you can have `.env.local` in local, not required by default, and keep one docker compose file for all environments (as anyone can use `.env.local` to overwrite the defaults).

**Comment by Fedcomp** [comment]
@rennokki There is always workarounds, the point was to support it at docker compose level for simplicity.

> I think it's beautiful

It's complex thing to solve simple issue, complex things are prone to break. Whenever you will have to escape/double escape all that - you will have a bad time :)

**Comment by rennokki** [comment]
True, a simple `args_file` in style of `env_file` would have simplified things 100x

I think I was just in a manic episode. 😅

**Comment by mike-kasianov** [comment]
Ok comrades, I spend half of my life trying to figure out how to pass a variable from .env file to build args and here is a secret.
It's literally a secret.

`docker-compose.yml`
```yaml
services:
  my_service:
    build:
      context: .
      dockerfile: test_ssh.Dockerfile
      secrets:
        - ssh_key
      env_file:
        - .env
secrets:
  ssh_key:
    file: ${SSH_KEY_PUB_PATH}
```

`.env`
```
SSH_KEY_PUB_PATH=beer.pub
```

`test_ssh.Dockerfile`
```
FROM windows_xp:sp2

RUN --mount=type=secret,id=ssh_key \
    SSH_KEY_PUB=$(cat /run/secrets/ssh_key) && \
    echo $SSH_KEY_PUB >> /root/.ssh/authorized_keys
```

It works as expected.

But! There is one more hard prone moment related to the build cache.

1. Update `.env` with `SSH_KEY_PUB_PATH=whiskey.pub` and run `docker compose up -d --build --force-recreate my_service`. The  value of `authorized_keys` remains the same (beer.pub).

2. Update `.env` with `SSH_KEY_PUB_PATH=whiskey.pub` and  change `SSH_KEY_PUB_PATH` to `SSH_KEY_PUB_PATH_1` in the Dockerfile and run `docker compose up -d --build --force-recreate my_service`. The  value of `authorized_keys` changes to whiskey.pub.
But when you revert `SSH_KEY_PUB_PATH_1` to `SSH_KEY_PUB_PATH` back it uses a cache version from the previous step (beer.pub). 

So to avoid any of these problems just rebuild the image with `docker compose build --no-cache`.
