### ISSUE TITLE
Support build --network

### ISSUE THREAD

**Issue by cjbottaro** [docker/compose#4665]
`docker build` supports `--network` option (note, this is different from `docker run`'s `--net` option).

Request extending docker-compose yaml spec to include the following:
```yaml
build:
  context: .
  network: host
```

Thanks.
