### ISSUE TITLE
volumes vs volumes_from in v3 question

### ISSUE THREAD

**Issue by whitecolor** [docker/compose#4673]
There is a case: 20 named volumes, one service installs dependencies on them, other multiple services use/attach those volumes, how this should be implemented in compose version 3?

```yaml
version '2'

volumes:
  - node_modules
  - nested_node_modules
  - another_nested_node_modules
  # .. then another 20 common volumes

services:
   deps-install:
     volumes:
        - node_modules: /app/node_modules
        - nested_node_modules: /app/nested/node_modules
     # then 20 mappings to named volumes

  # then go multiple packages that use all the volumes 
  # that `deps-install` service installs dependencies on on
   package1-service:
       volumes_from: 
           - deps-install

   package20-service:
       volumes_from: 
           - deps-install 
```

What should be done in  `v3`?

```yaml
version '3'

volumes:
  - node_modules
  - nested_node_modules
  - another_nested_node_modules
  # .. then another 20 common volumes

services:
   deps-install:
     volumes:
        - node_modules: /app/node_modules
        - nested_node_modules: /app/nested/node_modules
     # then 20 mappings to named volumes

  # then go multiple packages that use all the volumes 
  # that `deps-install` service installs dependencies on on
   package1-service:
     volumes:
        - node_modules: /app/node_modules
        - nested_node_modules: /app/nested/node_modules
     # then 20 mappings to named volumes

   package2-service:
     volumes:
        - node_modules: /app/node_modules
        - nested_node_modules: /app/nested/node_modules
     # then 20 mappings to named volumes

```

To each service I need to add 20 named volumes mappings instead of one `volumes_from`?
