### ISSUE TITLE
group_add doesn't work in version 3

### ISSUE THREAD

**Issue by Agrosis** [docker/compose#4700]
`group_add` in the Docker Compose reference file is supposed to work on version 3 according to https://docs.docker.com/compose/compose-file/#groupadd, but when I have the following config:

```
version: '3'
services:
  logs:
      ...
      group_add: 
        - adm
```

I get the following error:

```
ERROR: The Compose file './docker-compose.production.yml' is invalid because:
Unsupported config option for services.logs: 'group_add'
```

NOTE: `group_add` works fine when I specify version 2.1.

Version Info:
```
→ docker version
dClient:
 Version:      17.03.0-ce-rc1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce-rc1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   ce07fb6
 Built:        Mon Feb 20 10:12:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

→ docker-compose version
docker-compose version 1.11.1, build 7c5d5e4
docker-py version: 2.0.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by Agrosis** [comment]
Also, I'd like to note the example for `group_add` might be wrong.

```
version: '2'
services:
    image: alpine
    group_add:
      - mail
```

A service name isn't specified.
