### ISSUE TITLE
docker-compose network ipam additional properties are not allowed 

### ISSUE THREAD

**Issue by ColinHuang** [docker/compose#4708]
Encounter this issue in the v1.12 & v1.11:

    ERROR: The Compose file './docker-compose.yml' is invalid because:
    networks.test.ipam value Additional properties are not allowed ('driver_opts' was unexpected)

It has been resolved at docker-py: docker/docker-py#1165

networks part in docker-compose.yml:

```yml
  networks:
    internal:
      driver: bridge
      internal: true
      ipam:
        driver: default
    onlyoffice:
      driver: qnet
      ipam:
        driver: qnet
        driver_opts:
          iface: DEFAULT_NIC
```

**Comment by shin-** [comment]
Share your `docker-compose.yml` please.

**Comment by ColinHuang** [comment]
networks part in docker-compose.yml:

```
  networks:
    internal:
      driver: bridge
      internal: true
      ipam:
        driver: default
    onlyoffice:
      driver: qnet
      ipam:
        driver: qnet
        driver_opts:
          iface: DEFAULT_NIC
```

**Comment by shin-** [comment]
`driver_opts` should be in the network section, not the `ipam` section. Like so:

```yaml
  networks:
    internal:
      driver: bridge
      internal: true
      ipam:
        driver: default
    onlyoffice:
      driver: qnet
      ipam:
        driver: qnet
      driver_opts:
        iface: DEFAULT_NIC
```
