### ISSUE TITLE
Injecting UID and GID

### ISSUE THREAD

**Issue by sourcerer-mike** [docker/compose#4725]
So I have this in my docker-compose.yml

```
services:
  php:
    build: php:7.1-apache
    ports:
      - "8000:80"
    environment:
      - "APACHE_RUN_USER=${UID}"
      - "APACHE_RUN_GROUP=${GID}"
```

And in my bash UID and GID are set. But then ...

```
$ docker-compose up -d
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
```

So I need to do:

```
export UID=$UID
export GID=$GID
```

Can this be bypassed somehow?
I was hoping for docker to look up this variable.
