### ISSUE TITLE
Feature: Dynamically generated configuration

### ISSUE THREAD

**Issue by joernheissler** [docker/compose#4741]
Hi,
small feature suggestion:
It would be nice if the configuration (docker-compose.yaml) could be created dynamically on the fly.
Currently I've got a script that dumps the file to the file system, and docker-compose loads it.
I'd like it if docker-compose could run my script directly to get the configuration.
Two ways to do it:
- when docker-compose.yaml file is executable, it's executed and the output loaded with yaml.load.
- add a new .env / CLI environment variable for the purpose.

Cheers

**Comment by alwaysastudent** [comment]
We have a requirement to generate the docker-compose.yml file from a smaller template, since we all they have to deal with just the project name, the service name, the path of the web-api that they are exposing. Also we don't want our devs to be meddling with the docker-compose.yml files that would go to production.
Hence the requirement is we should be able to templatize a standard docker-compose.yml in such a way that people can add new services and abstract the rest of things out to a common file.

Something small like below we prescribe a `search` is the project and have defined two services in `search-front`  and `search-back`,

```
search :
 search-front
    web-path:/search/front/
    image:images.docker.com/search-front:1.0.1
 search-back
    web-path:/search/back/
    image:images.docker.com/search-back:1.0.5
```

should get extrapolated into a real compose file

```
networks:
  default:
    external:
      name: proxy_network
services:
  search-front:
    environment:
      var1: some-standard-env-variable
      var2: some-standard-env-variable
    healthcheck:
      interval: 15s
      retries: 3
      timeout: 3s
      test: ["CMD", "bash","-c" , "curl -f http://localhost:8080/health || exit 1"]
    image: images.docker.com/search-front:1.0.1
    labels:
      traefik.backend: search-front
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: PathPrefix:/search/front/
      traefik.port: '8080'
    volumes:
    - /host/path1:/path1
    - /host/path2:/path2
 search-back:
    environment:
      var1: some-standard-env-variable
      var2: some-standard-env-variable
    healthcheck:
      interval: 15s
      retries: 3
      timeout: 3s
      test: ["CMD", "bash","-c" , "curl -f http://localhost:8080/health || exit 1"]
    image: images.docker.com/search-back:1.0.1
    labels:
      traefik.backend: search-back
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: PathPrefix:/search/back/
      traefik.port: '8080'
    volumes:
    - /host/path1:/path1
    - /host/path2:/path2
```
We should be able to get the scaffolding separated out to an abstract project and abstract services
