### ISSUE TITLE
Is it possible to have build-only service?

### ISSUE THREAD

**Issue by rivaros** [docker/compose#4744]
Suppose I have the following config (simplified):

```
  src:
    build:
      context: deploy/src
    image: myname/base

  fpm:
    build:
      context: deploy/fpm
    image: myname/fpm
```

Dockerfile for fpm is located in deploy/fpm, Dockerfile for src is located in deploy/src
Dockerfile for myname/fpm image extends from myname/base image 

```
FROM myname/base
```

Therefore I need to include both services (src & fpm), and make containers from them.
Is it possible to specify that src service is for build only.
So it first builds myname/base image and then myname/fpm image.

If I omit src it will not be able to find myname/base image since it was not build yet.

**Comment by shin-** [comment]
See my answer to a similar question in #4489

**Comment by rivaros** [comment]
@shin- thank you but it's more like "we don't support it/was not designed to do that etc". running 2 commands - this is obvious, but not nice. Have you tried any other tools like dobi?

**Comment by shin-** [comment]
I have used dobi. It's a great tool, written by @dnephin who has been a Compose maintainer for a while, so I highly recommend trying it out.

**Comment by n0099** [comment]
And if you are using build-only service to achieve extending Dockerfile, also try [`build.additional_context`](https://stackoverflow.com/questions/36362233/can-a-dockerfile-extend-another-one/79348510#79348510).

**Comment by n0099** [comment]
> ```yaml
>   some-service-build-on-test:
>     build:
>       args:
>         COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
> ```
and

> ```Dockerfile
> ARG COMPOSE_PROJECT_NAME
> FROM ${COMPOSE_PROJECT_NAME}-test-build-only
> ```

can be simplified with [`services.*.build.dockerfile_inline`](https://docs.docker.com/reference/compose-file/build/#dockerfile_inline):
```yaml
  some-service-build-on-test:
    build:
      dockerfile_inline:
        # syntax=docker/dockerfile:1
        FROM ${COMPOSE_PROJECT_NAME}-test-build-only
```
