### ISSUE TITLE
Relative path to env_file

### ISSUE THREAD

**Issue by mdeboer** [docker/compose#4764]
I have a problem with my .env file when it's not in the same folder as the docker-compose file. When I place it in a subfolder and reference it, it will simply say the variables are undefined and will default to a blank string. When I remove the .env file it says it can't find the .env file, so it finds the file but doesn't do anything. When I move the .env file to the same directory as the docker-compose file and update it's path or create a symlink instead, all works fine.

Apparently docker-compose has issues with loading env files that are not in the same directory as the docker-compose file.

Currently I "fixed" this by symlinking the .env file as it's shared with a Laravel project in a subfolder.

My docker-compose file (simplified):

```
version: '3'

services:
  mysql:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql/data
    env_file:
      - ./api/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql_data:
```

**Comment by shin-** [comment]
This has been answered previously:
#4001
#4618 
etc.

See the disambiguation page: https://docs.docker.com/compose/environment-variables/

**Comment by lebadapetru** [comment]
Hey @shin- , i have the exact problem.
I read the official doc(https://docs.docker.com/compose/env-file/), and the topics you posted but that didn't answered my question. As OP said, if the .env file is in a different path than the docker-compose.yml's path it doesn't work.

`version: '3.7'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - ./app:/usr/src/app
  nginx:
    image: nginx:1.15.3-alpine
    restart: always
    volumes:
      - ./app:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php`

Inside ./app/ i have my symfony application with its own .env and i want the env vars used for building the images to be put in the same .env, to make it work i have 2 x .env, one in docker-compose dir and one in my app dir

**Comment by mathieurousseau** [comment]
I am also confused.
I read the "disambiguation" page. Which is very clear with example saying that you can configure your own env files.
But when I configure an env_file, I can't see the environment variables from inside my docker container.

**Comment by mdeboer** [comment]
Afaik the environment variables are imported in the application but you can't use them in your docker-compose file (like you did with NGINX_PORT. Use a separate .env file for that in the same directory and load that from the application if you really really need it.

**Comment by syerad** [comment]
Is there an update regarding that issue?
Afaik it's still not possible to set a relative path in the `env_file` option.

**Comment by nk9** [comment]
Relative paths _are_ accepted in `env_file`, they are even used in the [documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file). Note that PWD is the directory that the `docker-compose` file is in, if you are running it from the command line with `-f`. And, of course, you can load the `env_file` just fine and still not be able to access the variables it declares elsewhere in the `docker-compose` file for the reasons discussed above.

**Comment by Elvincth** [comment]
Now the relative paths are accepted in env_file, by specifiying your docker-compose.yml to version 3.9 


```
version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
        - ./apps/backend/.env <--- works
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    restart: unless-stopped
```

**Comment by jxramos** [comment]
So in the yml file `env_file` is a relative path rooted at the location of the yml file and must navigate to wherever the file is in the filesystem

So if given the following file locations
```
projX/subdir/docker-compose.yml
envs/my_vars.env
```

Then we'd have
```yml
  foooo:
    env_file:
      - ./../../envs/my_vars.env
```

How is the behavior when using `--env-file` at the command line? Would one do
```bash
# relative to cwd
docker-compose -f projX/subdir/docker-compose.yml --env-file ./envs/my_vars.env up
```
or rather
```bash
# relative to yml
docker-compose -f projX/subdir/docker-compose.yml --env-file ./../../envs/my_vars.env
```
?
