### ISSUE TITLE
Adding external secrets results in invalid yml produced by config 

### ISSUE THREAD

**Issue by gligoran** [docker/compose#4779]
This is the same issue as #4348 and #3429, but for secrets.

Running `docker-compose config` with this yml:

```
version: "3.1"

services:
  s1:
    image: someimage
    secrets:
      - secret1
      - secret2

secrets:
  secret1:
    external: true
  secret2:
    external: true

```

produces this:

```
networks: {}
secrets:
  secret1:
    external: true
    external_name: secret1
  secret2:
    external: true
    external_name: secret2
services:
  s1:
    image: someimage
    secrets:
    - source: secret1
    - source: secret2
version: '3.1'
volumes: {}
```

Trying to use this with `docker stack deploy` then produces this error:

> external_name Additional property external_name is not allowed

I tried this with docker 1.12.0 and 1.13.0-rc1 with the same result.
