### ISSUE TITLE
Subdirectory env_file

### ISSUE THREAD

**Issue by serazoli** [docker/compose#4782]
Hi
Where I should place the env_file if I run docker-compose from a subfolder?
- if I place same folder as docker-compose.yml then I get warring message that `"WARNING: The APP_ROOT variable is not set. Defaulting to a blank string."`
- if I place the subfolder where I run the docker-compose command then I get error that `"ERROR: Couldn't find env file: /home/xxxxx/xxxxx/xxxxx/.env"`
- if I place both folder (beside the docer-compose.yml and the subfolder) then working well
It is OK that the env_file must be present in two folder?
In the docker-compos file I use the following
`env_file: .env`
I try with docker-compose version 1.11.2, build dfed245 and docker-compose version 1.13.0-rc1, build 38af513
Sorry my bad Englis
Thaks
Zoli

**Comment by shin-** [comment]
https://github.com/docker/compose/issues/4764#issuecomment-297509975

**Comment by serazoli** [comment]
Hi
I read the comments and documentation which you linked but I think that here have other situation. 
I have the following folder structure (relevant files and folders only)

```
lamp2 (folder)
    docker (folder)
    local (folder)
        srv (folder)
    .env (file)
     docker-compose.yaml (file)
```
the content of docker-compose.yaml
```
version: '3'

services:

  apache:
    env_file: .env
    build:
      context: ./docker/apache
    image: zero/apache
    ports:
      - ${HOST_HTTP_PORT}:80/tcp
    volumes:
      - ${APP_ROOT}:/var/www/html/
      - ${CONF_PREFIX}/apache/mpm.conf:/etc/apache2/conf.d/mpm.conf
    tmpfs:
      - /run:rw,noexec,nosuid,size=65536k
    environment:
      FCGI: php:9000
    depends_on:
      - php

  php:
    env_file: .env
    build:
      context: ./docker/php
    image: zero/php
    volumes:
      - ${APP_ROOT}:/var/www/html/
      - ${CONF_PREFIX}/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ${CONF_PREFIX}/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis

  redis:
    env_file: .env
    image: redis:3-alpine
    volumes:
      - ${REDIS_VOLUME}:/data
    tmpfs:
      - /run:rw,noexec,nosuid,size=65536k

volumes:
  db:
  redis:
```
If I run eg. `docker-compose up -d` from `lamp2` folder where found the docker-compose.yaml and .env files everything is ok.
```
$ docker-compose up -d
Creating network "lamp2_default" with the default driver
Creating lamp2_redis_1 ... 
Creating lamp2_redis_1 ... done
Creating lamp2_php_1 ... 
Creating lamp2_php_1 ... done
Creating lamp2_apache_1 ... 
Creating lamp2_apache_1 ... done
```
If I run eg. `docke-compose logs` from `lamp/local/srv ` then I get the following message
```
$ docker-compose logs
WARNING: The APP_ROOT variable is not set. Defaulting to a blank string.
WARNING: The CONF_PREFIX variable is not set. Defaulting to a blank string.
WARNING: The HOST_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDIS_VOLUME variable is not set. Defaulting to a blank string.
ERROR: The Compose file './../../docker-compose.yaml' is invalid because:
services.apache.ports is invalid: Invalid port ":80/tcp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```
If I move the `.env ` file to the `lamp2/local/srv` and run `docke-compose logs` from `lamp2/local/srv ` then I get the following message
```
$ docker-compose logs
ERROR: Couldn't find env file: /home/xxxxx/xxxxx/lamp2/.env
```
If the `.env` file found in both folders (in lamp2 and in lamp2/local/srv) the `docker-compose logs` command works well from the `lamp2/local/srv` folder.

How I need modify the docker-compos.yaml that `docker-compose logs` command works from `lapm2\local\srv` folder and I do not have to copy the `.env` file also to the `lamp2/local/srv`
Thanks 
Zoli
