### ISSUE TITLE
Cannot create container for service cassandra: b'invalid port specification: "None"'

### ISSUE THREAD

**Issue by sean-Unity** [docker/compose#4810]
I get this error when calling `docker-compose up cassandra` from the following docker-compose.yml:

```
version: '2'
services:

  cassandra:
    container_name: cassandra
    image: cassandra:2.2.7
    mem_limit: 1000m
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra
```
```
Creating cassandra ... error

ERROR: for cassandra  Cannot create container for service cassandra: b'invalid port specification: "None"'
```
This error happens with compose `1.13.0, build 1719ceb` on GNU/Linux. Switching to `1.11.2, build dfed245` resolves this error.
