### ISSUE TITLE
Question:  Are docker-compose secrets supported on Windows Containers?

### ISSUE THREAD

**Issue by JonJam** [docker/compose#4829]
Hi,

I am trying to get secrets working with a service using Docker for Windows with Windows Containers, my top level compose file (Can add overrides if necessary) below:

version: '3.1'

secrets:
  web_connectionstring:
    file: .\docker-secrets\web_connectionstring

services:
  web:
    image: jonjam/web:latest
    secrets:
      - web_connectionstring

When I build I get the following error:
Cannot create container for service web: invalid volume spec "/run/secrets/web_connectionstring": invalid volume specification: '\run\secrets\web_connectionstring'

Hence my question are secrets supported on Windows Containers? Or am I missing something.

**Comment by shin-** [comment]
It's still a work in progress on the engine's end: https://github.com/moby/moby/pull/32208

After that, there'll probably be more work needed for `docker-compose` to support it, so it might not come simultaneously (but if you deploy with `docker stack deploy` instead, it will be available)

cc @dnephin

**Comment by JonJam** [comment]
@shin- Thanks a lot for confirming this 👍.

I spent a lot of time today trying to work out what I was doing wrong. As Windows Containers become more mainstream, it might be good idea on docker documentation to state whether a feature is supported with Windows containers.

**Comment by caphrim007** [comment]
@shin- I think i am receiving the same error, but it looks (on my end) like the secrets are just not being translated to their unix-y paths.

here's a snippet from `docker-compose config`
```
secrets:
  clouds.yaml:
    file: C:\Users\tim\f5-ansible\devtools\secrets\clouds.yaml
....
    secrets:
    - source: cloudsyaml
      target: clouds.yaml
    volumes:
    - /c/Users/tim/f5-ansible:/here:rw
version: '3.3'
```

Note that the volumes are translated fine, just the secrets are not. This is with `COMPOSE_CONVERT_WINDOWS_PATHS=1` set.

Am I seeing the same thing that @JonJam is seeing?
