### ISSUE TITLE
Feature Request: Access to composer environment variables

### ISSUE THREAD

**Issue by oliveiraev** [docker/compose#4838]
I have several applications that share the same docker-compose.yaml boilerplate. The **unique** difference is the application name.

I would love to replace all my ```$application_name``` occurrences with ```$COMPOSE_PROJECT_NAME```.

**Comment by shin-** [comment]
I'm not sure I understand the request. Can you elaborate on what you mean? Do you want Compose to populate the container's environment with a `COMPOSE_PROJECT_NAME` variable?

**Comment by oliveiraev** [comment]
For my own use case, the best scenario would be if ```COMPOSE_PROJECT_NAME``` was exposed at ```docker-compose.yaml``` level, so we could do things like
```
version: "3"
services:
    nginx:
        image: nginx:stable-alpine
    volumes:
        - .:/var/www/$COMPOSE_PROJECT_NAME
```
but, once ```COMPOSE_PROJECT_NAME``` is available at ```docker-compose.yaml``` level, I think that automagically we could also do
```
[...]
        environment:
            - $COMPOSE_PROJECT_NAME
```
when relevant to populate container's environment.
