### ISSUE TITLE
Documentation on endpoint mode

### ISSUE THREAD

**Issue by webfrank** [docker/compose#4843]
Which is the correct syntax in docker-compose.yaml v3 to support endpoint-mode dnsrr?

**Comment by shin-** [comment]
You're right that it's missing from the documentation, and that's because it hasn't yet made it to a stable release - it was added in Compose file format 3.2.
```yaml
version: '3.2'
services:
  foo:
    deploy:
      endpoint_mode: dnsrr
    ...
```
