### ISSUE TITLE
Runing with -v drops all the volume definitions in the docker-compose.yml file

### ISSUE THREAD

**Issue by ionelmc** [docker/compose#4847]
Eg, if I have this service:
```
services:
 test:
  image: ubuntu
  volumes: 
  - ${PWD}:/foo
```

And I run `docker-compose run -v /x:/y test` the `/foo` volume will no longer be mounted.

This can't be intentional behavior can it? It's too surprising (nor it is documented).
