### ISSUE TITLE
Unable to declare named volumesx in v3

### ISSUE THREAD

**Issue by italomaia** [docker/compose#4879]
This doesn't work:

```
version: '3'
volumes:
  - ux-data:/home/user/volumes/ux-data
```

Nor this:

```
version: '3.2'
volumes:
  common_code:
    - type: volume
    - source: /tmp/path
```

The error message is the same in both cases: must be a mapping not an array
