### ISSUE TITLE
docker-compose create fails due to not creating networks

### ISSUE THREAD

**Issue by mbentley** [docker/compose#4961]
When running a `docker-compose create`, it fails due to the networks not being created:

```
$ docker-compose create
Creating temp_test1_1 ...
Creating temp_test1_1 ... error

ERROR: for temp_test1_1  Cannot create container for service test1: Error: No such network: temp_test-overlay
ERROR: Cannot create container for service test1: Error: No such network: temp_test-overlay
```

My `docker-compose.yml`
```
version : "2"

services:
  test1:
    image: dtr.demo.dckr.org/official/alpine:latest
    command: ping 127.0.0.1
    networks:
      - test-overlay
    volumes:
      - test1:/data

  test2:
    image: dtr.demo.dckr.org/official/alpine:latest
    command: ping 127.0.0.1
    networks:
      - test-overlay
    volumes:
      - test1:/data

networks:
  test-overlay:

volumes:
  test1:
    driver: local
  test2:
    driver: local
```

Is this expected behavior to not create the necessary resources for a `create` to run successfully?

**Comment by friism** [comment]
weird, it works for me:

```
PS C:\code\repros\compose-networktest> docker-compose create
Pulling test1 (alpine:latest)...
latest: Pulling from library/alpine
43d680a959df: Pull complete
Digest: sha256:b09306f2dfa3c9b626006b2f1ceeeaa6fcbfac6037d18e9d0f1d407260cb0880
Status: Downloaded newer image for alpine:latest
Creating composenetworktest_test1_1 ...
Creating composenetworktest_test1_1 ... done
Creating composenetworktest_test2_1 ...
Creating composenetworktest_test2_1 ... done
PS C:\code\repros\compose-networktest> cat .\docker-compose.yml
version : "2"

services:
  test1:
    image: alpine
    command: ping 127.0.0.1
    networks:
      - test-overlay
    volumes:
      - test1:/data

  test2:
    image: alpine
    command: ping 127.0.0.1
    networks:
      - test-overlay
    volumes:
      - test1:/data

networks:
  test-overlay:

volumes:
  test1:
    driver: local
  test2:
    driver: local
```
