### ISSUE TITLE
docker-compose build multiple tags

### ISSUE THREAD

**Issue by Puneeth-n** [docker/compose#4976]
I was wondering if it is possible to build docker images using docker-compose file with multiple tags?

```
version: '2.2'

services:
    foo:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                CT_TAG: 6.10
            labels:
                com.example.description: "Accounting webapp"
        image: foo:baz
        image: foo:bar
```

This will only tag the image as `foo:bar` and not `foo:baz`

**Comment by shin-** [comment]
No, that is not currently possible.

**Comment by dirkschneemann** [comment]
See [this answer on StackOverflow](https://stackoverflow.com/a/47327980/2545732) for a couple of possible work-arounds to this issue.

**Comment by Puneeth-n** [comment]
@dirkschneemann Thanks. I ended up writing a small script to do it.

**Comment by mixja** [comment]
@Puneeth-n - you can do this natively in docker-compose as follows:

```
services:
  # build is your actual build spec
  build:
    image: myrepo/myimage
    build:
      context: .
    ...
    ...
  # these extend from build and just add new tags statically or from environment variables or 
  version_tag:
    extends: build
    image: myrepo/myimage:v1.0
  some_other_tag:
    extends: build
    image: myrepo/myimage:${SOME_OTHER_TAG}
```
