### ISSUE TITLE
Container stops immediately with docker-compose but runs fine with Docker.

### ISSUE THREAD

**Issue by mansing2** [docker/compose#5016]
I have two services and each service calls dockerfile which has microsoft/windowsservercore as a base image.
When I run docker-compose up on windows, the containers are getting stopped immediately however same yaml file on linux keeps containers running. is there any known issue on windows? 

my docker-compose.yml file is:
```
version: '3'

networks:
  default:
    external:
      name: nat

services:
  awi-service:
    env_file:
      - awi-box.env
    image: awi-box:12.0.0
    ports:
    - 8080:8080
    depends_on:
    - ae-service
    

  ae-service:
    env_file:
      - ae-box.env
    image: ar-box:12.0.0
    ports:
    -  2217:2217
    -  2218:2218
```

**Comment by shin-** [comment]
Did you check the logs of your services? What is their exit code? Does `docker-compose --verbose up` give you any additional information?

**Comment by mansing2** [comment]
Sorry for the delay in reply. The exit code is 0. Both the containers are getting exited with code 0.  When I run containers for the images given above in compose file manually using docker run then those containers remain up and running. 

```
D:\Compose_Test>docker logs --details 9ce72c60d698

 Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
 -------  ------    -----      -----     ------     --  -- -----------
      39       4     3812       3124       0.02    960  29 cmd
 Microsoft Windows [Version 10.0.14393]
 (c) 2016 Microsoft Corporation. All rights reserved.

 C:\tomcat7\webapps\awi\config>


D:\Compose_Test>docker logs --details 88ec90b8142b

 Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
 -------  ------    -----      -----     ------     --  -- -----------
       0       1      276         64       0.00   6524  28 UCYBSMgr
 Microsoft Windows [Version 10.0.14393]
 (c) 2016 Microsoft Corporation. All rights reserved.

 C:\automic\ServiceManager\bin>
```

Looking at above container log, everything looks fine. 

This is usually happens when the command does not have any long running process and container exits after the execution but in this case I have something that keep containers running.

**Comment by shin-** [comment]
I see. Can you share the output of the `docker-compose --verbose up` command?

**Comment by mansing2** [comment]
[docker-compose_verboselog.txt](https://github.com/docker/compose/files/1147575/docker-compose_verboselog.txt)

**Comment by mansing2** [comment]
After I have added stdin_open: true and tty: true to compose file, I can see the container is up and running.

**Comment by shin-** [comment]
I'm not sure what causes the discrepancy, although it's likely there would be some slight differences between how Windows containers operate vs how Linux containers operate, so I'll chalk it up to that. If the solution you've outlined is satisfactory for you, I'll go ahead and close.

**Comment by nxmohamad** [comment]
I experienced this same issue as well. I can run it using docker run just fine but docker-compose up gives exit code 0 for one of my services.
I'm using a macbook and what made it work was EITHER `stdin_open: true` or `tty: true`. 

My docker-compose.yml:
```
komuniki-mongo:
  image: mongo
  container_name: "komuniki-mongo"
  volumes:
    - ./temp/mongo_backups:/data/db/mongo_backups
  ports:
    - '27017:27017'

app:
  mem_limit: 300m
  memswap_limit: 1g
  container_name: "komuniki"
  build: .
  volumes:
    - .:/home/nodejs/app
    - ./node_modules:/home/nodejs/app/node_modules
  ports:
    - '7000:7000'
  links:
    - komuniki-mongo:mongo
```

[verbose log.txt](https://github.com/docker/compose/files/1524978/verbose.log.txt)

Would be great to know the root cause of this.
