### ISSUE TITLE
Disable Docker's embedded DNS (IPv6)

### ISSUE THREAD

**Issue by valentin2105** [docker/compose#5029]
Hi,

I'm trying to use Docker-compose in a IPv6 only network topology but today, it seem impossible. 

With Docker only, I'm able to give a **fixed-cidr-v6** and an **IPv6 DNS** that allow me to run container without using any IPv4 (the DNS is passed in the resolv.conf) and everything is routed. 

With Docker-compose (v2.1 or newer), I can use dual-stack (v4/v6) for containers and describe which IPv6 for each container but I can't use it on IPv6 only due of :

The Docker embedded DNS ( 127.0.0.11 ) 

```
root@8b9a37581c7a:/# cat /etc/resolv.conf
nameserver 127.0.0.11
nameserver 2405:f400::12
```

My question, 

Is this possible to disable totally this IPv4 embedded DNS using Docker-compose ?

Thanks a lot by advance.

**Comment by shin-** [comment]
According to [this](https://github.com/moby/moby/issues/19474#issuecomment-173090398), the embedded DNS is only enabled for user-defined networks (which Compose creates by default). It is possible to ensure services only use the default `bridge` network as such:

```yaml
version: '2.2'
services:
  svc1:
   ...
   network_mode: bridge
  svc2:
    ...
    network_mode: bridge
  ...
```

**Comment by valentin2105** [comment]
Hi @shin- 

Thanks for this tips, but It's not allow be to declare my IPv6 Address like I do it with docker-compose's network like this : 

```
version: '2.1'

services:

  nginx-dev:
    image: toto/web:dev
    container_name:toto-nginx_dev
    restart: always
    networks:
      toto:
        ipv6_address: 2404:f12:c::10


networks:
  toto_dev:
    driver: bridge
    enable_ipv6: True
    ipam:
      driver: default
      config:
        - subnet: 2404:f12:c::/112
```
