### ISSUE TITLE
Include an "order" key in the "update_config"

### ISSUE THREAD

**Issue by akalipetis** [docker/compose#5033]
When updating a Docker service, the following option exists:

```
      --update-order string                Update order ("start-first"|"stop-first")
```

This can be used to create rolling update deployments, even if a service has just one replica.

I propose adding the following keys to the Docker Compose spec, which will allow for these updates to work with `docker deploy -c`.

```yml
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
```

I would be happy to contribute the needed code to [docker/docker-ce](https://github.com/docker/docker-ce) if that's something we'd like to have in the spec.
