### ISSUE TITLE
services.db.volumes must be a list

### ISSUE THREAD

**Issue by ackris** [docker/compose#5065]
Hi Docker Team

I am following this [example](https://docs.docker.com/datacenter/ucp/2.1/guides/user/services/) to deploy a stack of votingapp services. 

I have used weave-net plugin for networking and created named volume 'db-data'. 

This is my `docker version`:
```
Client:
 Version:      17.03.2-ee-5
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Thu Jul 20 00:22:52 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ee-5
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Thu Jul 20 00:22:52 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

`OS: Ubuntu 16.04 VM in VirtualBox`

This is my docker-compose.yml with weave-net networking. 

```
version: "3"
services:
 redis:
  image: redis:alpine
  ports:
   - "6379"
  networks:
   - weavenet
  deploy:
   replicas: 2
   update_config:
    parallelism: 2
    delay: 10s
   restart_policy:
    condition: on-failure
 db:
  image: postgres:9.4
  volumes: db-data:/var/lib/postgresql/data
  networks:
   - weavenet
  deploy:
   placement:
    constraints: [node.role==manager]
 vote:
  image: manomarks/examplevotingapp_vote
  ports:
   - 5000:80
  networks:
   - weavenet
  depends_on:
   - redis
  deploy:
replicas: 6
   update_config:
    parallelism: 2
   restart_policy:
    condition: on-failure
 result:
  image: manomarks/examplevotingapp_result
  ports:
   - 5001:80
  networks:
   - weavenet
  deploy:
   replicas: 2
   update_config:
    parallelism: 2
    delay: 10s
   restart_policy:
   condition: on-failure
 worker:
  image: manomarks/examplevotingapp_worker
  networks:
   - weavenet
  deploy:
   mode: replicated
   replicas: 2
   labels: [APP=VOTING]
   restart_policy:
    condition: on-failure
    delay: 10s
    max_attempts: 3
    window: 120s
   placement:
    constraints: [node.role == worker]
 visualizer:
 image: manomarks/visualizer
  ports:
   - "8080:8080"
  stop_grace_period: 1m30s
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
networks:
 weavenet:
  driver: weave
volumes:
 db-data:
```
Whenever I try to deploy a stack with `docker stack deploy --compose-file docker-compose.yml VotingApp`, I am getting `services.db.volumes must be a list.` 

I don't know whether this is an error or warning. But I am unable to proceed further. Need your help in resolving this. 

I have browsed for solutions in Google, GH Issues and StackOverflow. Not much luck so far. 

**PS**: I am new to docker.
