### ISSUE TITLE
[1.15.0] Nested extends cause services to not be discovered

### ISSUE THREAD

**Issue by marcelmfs** [docker/compose#5067]
It seems 1.15 re-introduced something that was fixed before in https://github.com/docker/compose/issues/2719 - Downgrading to 1.14 "fixes" this issue.

**Comment by shin-** [comment]
@marcelmfs Can you share the Compose files you're using when seeing this issue?

**Comment by bigorn0** [comment]
@shin- This is somehow the same as reported in https://github.com/docker/compose/issues/5070 

The behaviour appears only if there are multiple layers of extension. For instance having this simple base `docker-compose-extended.yml` file
```
version: "2.2"
services:
   test:
     image: nginx:latest

   test-custom:
     extends: test
     environment:
       - TEST="blah"
```
extended in two ways in the following `docker-compose.yml` : 

If it extends directly the root service it works
```
version: "2.2"
services:
   test2:
     extends:
       file: ./docker-compose-extended.yml
       service: test
     ports:
       - 8081:80
```
leads to
```
Creating network "testcompose15_default" with the default driver
Creating testcompose15_test2_1 ...
Creating testcompose15_test2_1 ... done
Attaching to testcompose15_test2_1
```

whereas when extending `test-custom`service which is already extending `test` :  
```
version: "2.2"
services:
   test2:
     extends:
       file: ./docker-compose-extended.yml
       service: test-custom
     ports:
       - 8081:80
```
leads to the reported error:
```
┌─[test-compose15][]
└─▪ docker-compose up
ERROR: Cannot extend service 'test' in /Workspace/test-compose15/docker-compose-extended.yml: Service not found
```

I suspect it's related to this commit but I still need to test:
https://github.com/docker/compose/commit/e52f019ac89cda861720aca3c1f25de58e1acf11
