### ISSUE TITLE
Extends parameter does not work after 1.15.0 update

### ISSUE THREAD

**Issue by ioaoue** [docker/compose#5070]
When a service from file `a.yml` extends a service from file `b.yml` which extends another service from file `b.yml`, docker-compose throws an error:
<code>
ERROR: Cannot extend service 'test' in b.yml: Service not found
</code>

Issue introduced in commit: 6ff6528d45ea2fe6cc511dff75250995f9913c9b
Example: https://github.com/ioaoue/docker-compose-extends-issue

**Comment by kudos** [comment]
I'm seeing similar:

```
ERROR: Circular reference:
  celery-worker in /Users/jonathan/snipped/docker-compose.yml
  extends celery-worker in /Users/jonathan/snipped/docker-compose.base.yml
  extends website-django in /Users/jonathan/snipped/docker-compose.base.yml
  extends website-django in /Users/jonathan/snipped/docker-compose.base.yml
```
**docker-compose.base.yml**
```
version: "2"
services:
  website-django:
    build: ./
  celery-worker:
    extends: website-django
    command: celery worker -A udemy.task_queue
```

**docker-compose.yml**
```
version: "2"
services:
  website-django:
    extends:
      file: docker-compose.base.yml
      service: website-django
    ports:
        - "8000:8000"
    volumes:
      - django-sync:/app:nocopy
  celery-worker:
    extends:
      file: docker-compose.base.yml
      service: celery-worker
    volumes:
      - django-sync:/app:nocopy
```

This doesn't actually seem like a circular reference to me at all, and it works fine on 17.06.
