### ISSUE TITLE
retries contains an invalid type, it should be a number

### ISSUE THREAD

**Issue by junneyang** [docker/compose#5109]
1. my .env:
`RETRIES=3`

2. my docker-compose.yaml:
```
    healthcheck:
      test: nc -v -w 5 -z localhost ${AUTH_SERVER_PORT}
      interval: ${INTERVAL}
      timeout: ${TIMEOUT}
      retries: ${RETRIES}
```

3. when docker-compose config, it says:

`retries contains an invalid type, it should be a number`

how to solve this problem, thanks very much!
