### ISSUE TITLE
Volumes not being mounted when build option is specified

### ISSUE THREAD

**Issue by zoran119** [docker/compose#5159]
Is it possible to share the host directory while specifying a Dockerfile for a service?

For example, this doesn't mount the volume:

```
version: '2'
services:
    test:
        container_name: test
        hostname: test
        build: ./test
        volumes:
            - .:/src
        ports:
            - "80:80"
```

but this does (specifies `image` instead of `build`):

```
version: '2'
services:
    test:
        container_name: test
        hostname: test
        image: nginx
        volumes:
            - .:/src
        ports:
            - "80:80"

```
Is this expected?
