### ISSUE TITLE
Array form of #labels produces unmarshal error

### ISSUE THREAD

**Issue by borlander** [docker/compose#5183]
Consider the following docker-compose.yml: 
```
version: '2.1'
services:
  labels_as_array:
    build:
      context: .
      labels:
        - "com.example.description=Description"
        - "com.example.department=Department"
        - "com.example.label-with-empty-value"
```
which is canonical sample from [reference v2](https://docs.docker.com/compose/compose-file/compose-file-v2/#labels)

The Dockerfile for the sample is irrelevalt and is simply ```FROM busybox```

However, running `docker-compose up`, produces:
```
$ docker-compose -v
docker-compose version 1.16.0-rc1, build 9bea70a
$ docker-compose up
Building labels_as_array
ERROR: json: cannot unmarshal array into Go value of type map[string]string
```

Note that the same sample is also listed for v3 [here](https://docs.docker.com/compose/compose-file/#labels), but changing the version to `'3.3'` in the sample above does not help.

**Comment by shin-** [comment]
Thanks for the report! I don't think it will change anything, but you might want to try with the stable release (1.16.1) as well.

In the meantime, the workaround would be to use the dictionary notation, i.e.
```yaml
version: '2.1'
services:
  labels_as_array:
    build:
      context: .
      labels:
        com.example.description: "Description"
        com.example.department: "Department"
        com.example.label-with-empty-value:
```
