### ISSUE TITLE
Docker-compose up very slow. docker-compose run fast as it used to be [LINUX]

### ISSUE THREAD

**Issue by Annihilator708** [docker/compose#5215]
To see more information please check out the issue on stack overflow:
https://stackoverflow.com/questions/46405633/docker-compose-up-very-slow-but-docker-compose-run-on-linux-very-fast

**Comment by Annihilator708** [comment]
The issue is because of buffered logs. You should either change

`CMD ["/usr/bin/python", "run.py"]`
to

`CMD ["/usr/bin/python", "-u", "run.py"]`
Or you should update your docker-compose.yml

```
version: "3"
services:
  docker-build:
    build: ./
    ports:
    - "4242:5000"
    environment:
      - "PYTHONUNBUFFERED=1"
```
PS: Taken from http://tarunlalwani.com/post/why-delayed-output-python-docker/
