### ISSUE TITLE
Volume Mapping removes parent directory

### ISSUE THREAD

**Issue by artemartemov** [docker/compose#5216]
Hello,

I am having an issue with volume mapping a local dir to a docker container. 

I have a basic flat-file cms that I am spinning up using docker-compose. When I add a volume line to docker-compose.yml the folder that I am mapping replaces the entire directory instead of the folder itself. 

When I do not have the volume line, everything works as intended - but the local directory isn't synced. 

Here is my DockerFile:
```
FROM php:7-apache

RUN set -xe \
    && mkdir -p /usr/src/grav/.unpacked \
    && apt-get update && apt-get install -y libpng12-0 git unzip libpng12-dev --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install gd zip \
    && a2enmod rewrite

RUN groupadd -r grav --gid=1000 \
    && useradd -r -g grav -d /var/www/html --uid=1000 grav

ENV GRAV_URL "https://getgrav.org/download/core/grav/1.3.3"

RUN set -xe \
    && curl -fSL -o /usr/src/grav/grav.zip "$GRAV_URL" \
    && unzip /usr/src/grav/grav.zip -d /usr/src/grav/.unpacked \
    && rm /usr/src/grav/grav.zip \
    && mv /usr/src/grav/.unpacked/*/* /usr/src/grav \
    && mv /usr/src/grav/.unpacked/*/.[!.]* /usr/src/grav \
    && rm -rf /usr/src/grav/.unpacked \
    && chown -R www-data:www-data /usr/src/grav \
    && cd /usr/src/grav \
        && bin/gpm selfupgrade -y \
        && bin/gpm install -y admin git-sync

ENV UID_GRAV=1000
ENV GID_GRAV=1000

VOLUME [ "/var/www/html" ]

COPY ./docker-entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]
CMD [ "apache2-foreground" ]
```

Here is my docker-compose.yml:
```yaml
version: '3'
services:

  grav:
    build: .
    image: grav
    container_name: gravdocker
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: gravlocal.docker
    volumes:
      - ${PWD}/user:/var/www/html/user
```

and here is the docker-entrypoint.sh:
```bash
#!/bin/sh
set -e

if [ -z "$(ls -A /var/www/html)"]; then
	cp -a /usr/src/grav/. /var/www/html/
	chown -R www-data:www-data /var/www/html
        if [ "$GRAV_REVERSE_PROXY" = "true" ]; then
		sed -i "s/reverse_proxy_setup:\sfalse/reverse_proxy_setup: true/g" \
		system/config/system.yaml
	fi
fi

exec "$@"
```

**Comment by shin-** [comment]
You can't have a host mount inside another volume. You should remove the `VOLUME [ "/var/www/html" ]` line in your Dockerfile.

**Comment by artemartemov** [comment]
@shin- I removed those files and am still seeing the user directory overriding the entire `/html` dir.

Even with this no luck:
```yaml
volumes:
      - type: bind
        source: ./user
        target: /var/www/html/user
```
