### ISSUE TITLE
Allow image to be reused inside docker-compose

### ISSUE THREAD

**Issue by imaia** [docker/compose#5255]
I would like to be able to reuse a image compiled for a service defined in a docker-compose inside the same docker-compose. Example:

```
version: '3.2'
services:
  app:
    build: ./app
    image: myapp
  app2:
    image: myapp
    command: sh -c "echo 'non default command'"
```

This would be quite useful for some scenarios, like task schedulers (celery, rq).
