### ISSUE TITLE
Getting 'order' was unexpected in deploy stanza

### ISSUE THREAD

**Issue by byrnedo** [docker/compose#5258]
https://github.com/docker/cli/pull/360
```
version: "3.4"
services:
...
        deploy:
            resources:
                limits:
                    memory: 128M
            replicas: 1
            update_config:
                parallelism: 1
                order: start-first
```

Docker Compose version:
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
