### ISSUE TITLE
not setting env variables shouldn't trigger a warning when building

### ISSUE THREAD

**Issue by aduermael** [docker/compose#5290]
Environment variables aren't used during the build phase. 
So I think the `docker-compose build` command shouldn't display a warning if those are not set.

Sample `docker-compose.yml`:

```yml
version: "3.1"

services:
  foo: 
    build:
      context: .
    environment:
      BAR: ${BAR}
```

```shell
$ docker-compose build
WARNING: The BAR variable is not set. Defaulting to a blank string.
```
It's useful though to see that warning when using `docker-compose run`.
