### ISSUE TITLE
Docker compose/swarm issue in bridge networking

### ISSUE THREAD

**Issue by bergtwvd** [docker/compose#5385]
I have a multi-node composition (v3) and I use Swarm standalone for scheduling.
The composition has an overlay network for all containers to use, and a bridge network for two containers (A and B) that use multi-cast to communicate.

Since the composition is created by docker-compose in steps (i.e. first network, then containers) the containers A and/or B may end up on another host than the node with the bridge network. See also issue https://github.com/docker/swarm/issues/2799.

How can this be made to work?

**Comment by shin-** [comment]
Sounds to me like you should take steps to ensure the network is available on every node in your swarm. Unfortunately, that is not something Compose can do for you.

**Comment by bergtwvd** [comment]
This option is really a no-op.  With this I have to create a bridge net on every node and for every potential instance of the composition. A composition may be instantiated multiple times in the cluster. In my case the composition is a distributed, cloud based simulation.

A snippet of the composition is as follows. From what I can tell from the verbose log output:

* Compose creates the bridge network (and Swarm places it somewhere in the cluster)
* Compose create the container (and Swarm places it somewhere in the cluster, without taking into account that the container has an affinity with the bridge network)
* Compose attaches the container to the bridge net (which may fail !)

So the issue is the result of the interaction between Compose and Swarm for bridge networks.
The container - bridge network affinity information is in the composition, but is not used by either Compose or Swarm.

````
version: '3'

services:
 ServiceA:
  image: imageA
  links:
  - ServiceB
  depends_on:
  - ServiceB
  networks:
  - bridgenet
  
 ServiceB:
  image: imageB
  networks:
  - bridgenet
  
networks:
 bridgenet:
  driver: bridge
````
