### ISSUE TITLE
Support the "consistency" option in long syntax format for volumes

### ISSUE THREAD

**Issue by lmakarov** [docker/compose#5388]
I did not find an example for the [consistency](https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-mount-consistency-for-macos) option used with the **long syntax format** in [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/#long-syntax-3) docs.

Looks like it is not yet supported.

```
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
```

**Short syntax**

```yaml
version: "3.3"

services:
  web:
    image: nginx
    volumes:
      - ${PROJECT_ROOT}:/var/www:rw,cached
```

```
$ docker-compose config
services:
  web:
    image: nginx
    volumes:
    - /Users/leonid/Work/Labs/docksal/demo:/var/www:rw,cached
version: '3.3'
```

```
$ docker inspect demo_web_1
...
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/leonid/Work/Labs/docksal/demo",
                "Destination": "/var/www",
                "Mode": "rw,cached",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
...
```

> `"Mode": "rw,cached"`

```
$ /Applications/Docker.app/Contents/MacOS/com.docker.osxfs state
Exported directories:
 - /Users to /Users (nodes_/Users table size: 8)
 - /Volumes to /Volumes (nodes_/Volumes table size: 0)
 - /private to /private (nodes_/private table size: 0)
 - /tmp to /tmp (nodes_/private/tmp table size: 0)
Container-mounted directories:
 - /Users/leonid/Work/Labs/docksal/demo into 5b47358f24a178ceb11543109c0ad467181f783430a7e7fae620bdb87641f87f (state=cached)
```

> `(state=cached)`

**Long syntax**

```yaml
version: "3.3"

services:
  web:
    image: nginx
    volumes:
      - type: bind
        source: ${PROJECT_ROOT}
        target: /var/www
        read_only: false
        consistency: cached
```

```
$ docker-compose config
services:
  web:
    image: nginx
    volumes:
    - /Users/leonid/Work/Labs/docksal/demo:/var/www:rw
version: '3.3'
```

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/leonid/Work/Labs/docksal/demo",
                "Destination": "/var/www",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

> `"Mode": "rw",`

```
$ /Applications/Docker.app/Contents/MacOS/com.docker.osxfs state
Exported directories:
 - /Users to /Users (nodes_/Users table size: 8)
 - /Volumes to /Volumes (nodes_/Volumes table size: 0)
 - /private to /private (nodes_/private table size: 0)
 - /tmp to /tmp (nodes_/private/tmp table size: 0)
Container-mounted directories:
 - /Users/leonid/Work/Labs/docksal/demo into ad5c57007849125a4ccdc4fcda6964a42eeddab9084b00a5a2cea8361942e132 (state=default)
```

> `(state=default)`

**Comment by shin-** [comment]
cc @dnephin

**Comment by kbluescode** [comment]
@lmakarov - it doesn't support `consistency`, but it does support the `propagation` method via the driver config of a given volume. As of 1.16 this worked fine, but I'm running into issues in 1.18.

Example:
```
services:

  service1:
    image: alpine:3.4
    volumes:
      - type: bind
        bind:
          propagation: cached
        source: ./folder_to_mount
        target: /app
```
