### ISSUE TITLE
JSON schema missing network config options

### ISSUE THREAD

**Issue by thecjharries** [docker/compose#5437]
1. [The official docs](https://docs.docker.com/engine/reference/commandline/network_create/#specify-advanced-options) show `docker network` is capable of specifying the `subnet`, `gateway`, and a few other things.
2. `network` supports [`subnet`, `gateway`, and a few other other things](https://github.com/docker/compose/blob/1.17.1/compose/network.py#L121).
3. [The schema](https://github.com/docker/compose/blob/1.17.1/compose/config/config_schema_v3.5.json#L412) only [defines `subnet`](https://github.com/docker/compose/blob/1.17.1/compose/config/config_schema_v3.5.json#L421) and explicitly states [there are no `additionalProperties`](https://github.com/docker/compose/blob/1.17.1/compose/config/config_schema_v3.5.json#L423).
4. This `docker-compose.yml`

    ```yaml
    version: '3'

    services:
      illustrate_network_issue:
        image: alpine:latest
        networks:
          broken_config:

    networks:
      broken_config:
        ipam:
          driver: default
          config:
            - subnet: '10.47.0.0/24'
              gateway: '10.47.0.254'
    ```
    leads to this error:
    ```bash
    $ docker-compose up
    ERROR: The Compose file './docker-compose.yml' is invalid because:
    networks.broken_config.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
    ```
