### ISSUE TITLE
Docker-compose does not refresh container's volume content

### ISSUE THREAD

**Issue by gitowiec** [docker/compose#5463]
I am running Debian 9 host and using `Docker version 17.09.1-ce, build 19e2cf6` and `docker-compose version 1.17.0, build ac53b73`. This is the content of my `docker-compose.yml`

```
 version: '3'

 services:
    product-service:
        build: ./product
        volumes:
            - ./product:/user/src/app
        ports:
            - 5001:80
```

And here is `product/Dockerfile`
```
FROM python:3-onbuild
COPY . /usr/src/app
CMD ["python", "api.py"]
```

I build and run this container with `docker-compose up --build`,  when I change `api.py` (eg add content to array returned from get method) and save, docker-compose does not refresh the volume content on `product-service` container.

My text editor is sublime3 ( "atomic_save": false), I tried KWrite, same problem occurs. 
I also connected to bash on running container using `docker exec -it dockertests_product-service_1 /bin/bash` and echoed `api.py` file - it didn't contain the change made on host.

I just recreate this short (12 minutes) tutorial about docker-compose https://www.youtube.com/watch?v=Qw9zlE3t8Ko , all this files are examples from tutorial.

Please provide some ideas how to debug this issue.
