### ISSUE TITLE
add env_blueprint_file feature

### ISSUE THREAD

**Issue by Bamieh** [docker/compose#5477]
Hello,

There is a nice feature in the [dotenv npm package](https://www.npmjs.com/package/dotenv) which is the option to provide a blueprint for the `.env` file. the purpose of the blueprint is to validate missing environment variables in the .env file before running, providing a catch net to catch missing env variables before spinning the component.

Possible Implementations:

```
services:
  service-name:
    env_file:
      - ./.env
    env_blueprint_file:
      - ./.env.blueprint
```
or

```
services:
  service-name:
    env_file:
      - ".env:.env.blueprint"
```
also auto detecting the blueprint of the env file is a possiblity (by trying to fetch `env_file_name.blueprint`).

Cheers!
