### ISSUE TITLE
docker-compose failed recognizing files over version 2.0 

### ISSUE THREAD

**Issue by ailjushkin** [docker/compose#5491]
I faced with issue when docker-compose says me that it does not support 3.4 version of docker-compose file. 

It does not work with 3.3 also. 
And also does not work with 2.3. 

It works only with version: "2.0". 

Please look behind to find my installed versions:

> 
> sudo docker-compose up -d
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> 
> docker-compose --version
> docker-compose version 1.17.1, build 6d101fb
> 
> docker --version
> Docker version 17.09.1-ce, build 19e2cf6

**Comment by shin-** [comment]
Can you share your Compose file as well?

**Comment by ailjushkin** [comment]
```
version: '3.4'

networks:
  portal_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.20.0/24

services:
  registry:
    image: consul:0.9.3
    ports:
      - "8500:8500"
      - "8300:8300"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0 -raft-protocol=3"
    environment:
        - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network

  uat:
    image: reportportal/service-authorization:3.3.0
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400
      - RP_MONGO_HOST={{ groups.report_portal_service }}
      - RP_MONGO_PORT=27017
      - RP_MONGO_DB_NAME=reportportal
      - RP_MONGO_USER=user
      - RP_MONGO_PASSWORD=password
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network

  gateway:
    image: fabiolb/fabio:1.5.2-go1.9
    ports:
      - "9998:9998" # GUI/management
      - "8080:9999" # HTTP exposed
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=registry:8500
      - FABIO_REGISTRY_CONSUL_REGISTER_NAME=gateway
      - FABIO_PROXY_ADDR=:9999;rt=300s;wt=300s
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network

  index:
    image: reportportal/service-index:3.1.1
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/
      - RP_CONSUL.ADDRESS=registry:8500
    depends_on:
       - registry
       - gateway
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network

  api:
    image: reportportal/service-api:3.3.1
    environment:
      - RP_PROFILES=docker
      - RP_ISSUE_ANALYZER_DEPTH=10
      - JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
      - RP_MONGO_HOST={{ groups.report_portal_service }}
      - RP_MONGO_PORT=27017
      - RP_MONGO_DB_NAME=reportportal
      - RP_MONGO_USER=user
      - RP_MONGO_PASSWORD=password
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network

  ui:
    image: reportportal/service-ui:3.3.2
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - RP_CONSUL.ADDRESS=registry:8500
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network

  jira:
    image: reportportal/service-jira:3.3.0
    environment:
      - RP_PROFILES=docker
      - RP_MONGO_HOST={{ groups.report_portal_service }}
      - RP_MONGO_PORT=27017
      - RP_MONGO_DB_NAME=reportportal
      - RP_MONGO_USER=user
      - RP_MONGO_PASSWORD=password
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - portal_network
```
