### ISSUE TITLE
Ability to specify dockerfile name

### ISSUE THREAD

**Issue by bpinto** [docker/compose#552]
I would like to be able to simulate this same command in fig `docker build - < Dockerfile.development`, but `build` does not expect a dockerfile, am I missing something?

**Comment by haydenk** [comment]
https://docs.docker.com/compose/compose-file/#/build

```
build: ./dir

build:
  context: ./dir
  dockerfile: Dockerfile-alternate
  args:
    buildno: 1
```

Apparently, it's available now.
