### ISSUE TITLE
Environment variables fail to be expanded 

### ISSUE THREAD

**Issue by cristim** [docker/compose#5534]
I'm using the following config file (some parts were taken out for simplicity):

```
---
version: '2'
services:
  toolbox:
    environment:
      - "USER=${USER}"
    volumes:
      - "${HOME}/.toolbox:/home/${USER}/.toolbox"
```

I noticed this after updating docker-compose to 1.18.0, build 8dd22a9
```
$ docker-compose config

services:
  toolbox:
    environment:
      USER: ''
    volumes:
    - /root/.toolbox:/home/.toolbox:rw
version: '2.0'
```
Previously, with version 1.17.1, build 6d101fb it was like expected:
```
$ docker-compose config
services:
  toolbox:
    environment:
      USER: myuser
    volumes:
    - /home/myuser/.toolbox:/home/myuser/.toolbox:rw
version: '2.0'
```

**Comment by shin-** [comment]
Looks like you're running as root in the first excerpt? I'm not sure that's a Compose issue.

**Comment by yangm97** [comment]
I’m having the same issue, it works on my machine (docker-compose version 1.17.1, build 6d101fb) but not on my CI (docker-compose version 1.18.0, build 8dd22a9).

`docker-compose -f docker-compose.yml -f docker-compose.env.yml config > docker-compose.deploy.yml`

`docker-compose.yml`
```
version: '3.3'

services:
  botrouter:
    environment:
      - BOTS
    image: ${IMAGE:-botrouter}:${TAG:-latest}
    labels:
      - "traefik.backend=production-bot-router"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: bot.synko.com.br"
      - "traefik.port=80"
    restart: always
```

`docker-compose.env.yml`

```
version: '3.3'

services:
  botrouter:
    labels:
      traefik.backend: "${ENV}-bot-router"
      traefik.frontend.rule: “Host: ${ENV}.bot.synko.com.br"
```
