### ISSUE TITLE
security_opt and seccomp

### ISSUE THREAD

**Issue by coventry** [docker/compose#5574]
I'd like to make a `docker-compose.yml` containing something like this:

```yaml
services:
  desktop:
    security_opt:
      - seccomp:"./chrome.json"
```

This would correspond to the `docker run` option `--security-opt seccomp:./chrome.json`, where [`chrome.json` is this seccomp profile](https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json).

Is there any way to give the `seccomp` key an arbitrary JSON string?
