### ISSUE TITLE
docker-compose.yml ignores "scale:" option for version 3

### ISSUE THREAD

**Issue by beephotography** [docker/compose#5586]
This works:
```
version: '2.2'
services:
    template:
      image: tutum/hello-world
      scale: 2
```

This doesn't work
```
version: '3'
services:
    template:
      image: tutum/hello-world
      scale: 2
```

but I didn't find any documentation about it on https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

**Comment by ghsatpute** [comment]
The `scale` is deprecated you can find the details [here](https://docs.docker.com/compose/reference/scale/)

You can use: `docker-compose up --scale template=2`

**Comment by shin-** [comment]
`scale` was never added to v3, as it already has `deploy.replicas`.

**Comment by spiderpug** [comment]
The documentation states

> This only takes effect when deploying to a swarm with docker stack deploy, and is ignored by docker-compose up and docker-compose run.

It's a shame it's missing in v3. Now we have to update all our `up` calls? I'm using this a lot with docker-compose only, no swarm or w/e.

The [migration guide](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) should be updated accordingly. There's no hint that `scale` was removed! 

ref #5589

**Comment by beephotography** [comment]
Thank you for clarification, @ghsatpute but @spiderpug is right, there's no hint that `scale` was removed.

Furthermore, if I follow the `up` link to https://docs.docker.com/compose/reference/up/ I can find the following description for `--scale`:

```
    --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the `scale`
                               setting in the Compose file if present.
```

Thus, I would understand that setting `scale` in the compose file is still possible!

**Comment by decoomanj** [comment]
In v2 I've used "scale" to scale up some services during the start of my development setup. I'm not interested in using Swarm for that. What is the recommended way to get this behaviour back? I don't want to fall back to defining one service three times or use the CLI to scale.

**Comment by decoomanj** [comment]
in v2 I don't have secrets...

**Comment by decoomanj** [comment]
Ok, I'll give the compatibility mode a try. Thanks for the hint @shin- !

**Comment by decoomanj** [comment]
For people looking for a quick migration:

1. Update your version to 3+
2. Replace scale by     

>     deploy:
>      replicas: 3
3. Run `docker-compose --compatibility ...`

Hope this helps :-)

**Comment by Cirilo17** [comment]
Unfortunately this doesn't seem to work with 
``` deploy:
  replicas: 0 ```

**Comment by Cirilo17** [comment]
Unfortunately this doesn't seem to work with:
```
deploy: 
  replicas: 0
```

**Comment by hendisantika** [comment]
Me too @Cirilo17 .

It doesn't work for me neither.
```
WARNING: Some services (demo) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
```
Here's my docker-compose.yml file
```
version: '3'
services:
  demo:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: demoweb
    ports:
      - 8080
    networks:
      - network1
#    deploy:
#      replicas: 3
#      mode: replicated

networks:
  network1:

```

**Comment by mrampant-nist** [comment]
@hendisantika as @decoomanj mentioned, it does work, you just have to use the `--compatibility` flag when using `docker-compose`:
i.e. in your case `docker-compose --compatibility up -d`

**Comment by hendisantika** [comment]
Ooo... ya. It's working now with that command.
Thank You @mrampant-nist

**Comment by espoelstra** [comment]
`--compatibility` is awesome, thanks to the devs who put it in and the helpful folks who outlined its usage here.

**Comment by Leland-Takamine** [comment]
It seems like `deploy.replicas: 0` no longer works with version `1.27.0`: #7735

**Comment by nflaig** [comment]
@Leland-Takamine isnt there a better way to disable a service?

**Comment by darkguy2008** [comment]
`--compatibility` is no better than using `--scale`, it's still an extra CLI argument we don't want. Why such an useful feature (in my use case) has been removed from the YML file in favor of something more complicated and cumbersome? (Instead of just letting it be and let us pick which one we want to use...)

**Comment by adamlacoste** [comment]
The compatibility mode documentation also warns explicitly against against its own use in production environments.  Specifying `scale` in the compose was a useful feature for users who don't use Swarm.  I can't understand why it was removed.

**Comment by hinorashi** [comment]
guys, the `scale` works now, even without the `--compatibility` flag, I think it maybe thanks to the [compose-spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md) 🐧 

Just upgrade you `compose` to `1.27+` and remove the top-level `version` element.

**Comment by sudomann** [comment]
@hinorashi  using the `scale` directive in my docker compose file actually worked with `version: '3.9'` at the top.

**Comment by pouyanh** [comment]
using `deploy.replicas` now works for me just by running `docker-compose up -d` (no swarm)

setting `scale` warns: "\`scale\` is deprecated. Use the \`deploy.replicas\` element`" but it still works as expected and creates multiple containers

I've tested these 4 scenarios and results was same:
* no version element
* version: "3"
* version: "3.8"
* version: "3.9"

Test env:
* OS: Arch Linux
* Docker Compose version 2.1.1
* Docker Client Version: 20.10.10
* Docker Server Engine Version: 20.10.10

docker-compose.yml:
```yaml
version: "3"
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 4
```

@hinorashi I'm using [https://github.com/pouyanh/autodns](https://github.com/pouyanh/autodns) to reach my scaled containers randomly by setting `environment.HOSTNAME`:
```yaml
version: "3"
services:
  pg:
    image: postgres:latest
    networks:
      default:
        aliases:
          - rdb.test.me

  pgadmin:
    image: dpage/pgadmin4:latest
    deploy:
      replicas: 3
    environment:
      HOSTNAME: rdba.test.me

      PGADMIN_DEFAULT_EMAIL: user@test.me
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
```
