### ISSUE TITLE
Can't pass Environment variables from docker-compose.yml to Dockerfile

### ISSUE THREAD

**Issue by MatthewBooth** [docker/compose#5600]
This is a huge oversight. I'm not sure when the use-case would be that you want some variables within your project that build cannot access.

I'm running Laravel, which of course uses .env files. docker-composer passes these along nicely and the system runs.

Until I want to build an image and then composer (php) cannot generate autoload files because it can't find the .env file and therefore can't build an image.

TL;DR
My project needs some .env values and the Dockerfile has no way of knowing about them.

**Comment by shin-** [comment]
Compose is not a build tool, and has no vocation to become one. That being said, it should be simple enough to pass those variables you need as build args and declare them as `ENV` variables in your `Dockerfile`, like so:

*docker-compose.yml*
```yaml
version: '2.3'
services:
  foobar:
    build:
      context: .
      args:
        FOO: ${FOO}
        BAR: ${BAR}
```

*Dockerfile*
```dockerfile
FROM busybox:latest
ARG FOO
ARG BAR
ENV FOO $FOO
ENV BAR $BAR
...
```
