### ISSUE TITLE
`run` does not honor `depends_on`

### ISSUE THREAD

**Issue by dustinfarris** [docker/compose#5608]
I think #2833 needs to be reopened.

**Comment by shin-** [comment]
Please share at least your Compose file and the output of the `docker-compose version` command.

**Comment by dustinfarris** [comment]
Example here: https://github.com/dustinfarris/hello_world/tree/docker

### docker-compose.yml

```yml
version: "3"
services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  web:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=prod
      - PORT=80
      - DATABASE_URL=ecto://postgres:postgres@postgres/hello_world_prod
    ports:
      - "80:80"
```

Running the web service does not seem to start the postgres container first, unless I build the whole thing first.

This does not work:

```
docker-compose run web mix ecto.create
```

This works:

```
docker-compose build
docker-compose run web mix ecto.create
```
