### ISSUE TITLE
mysqli::real_connect(): (HY000/1045): Access denied for user 'test_user'@'<internal IP>'

### ISSUE THREAD

**Issue by JustinTBrown** [docker/compose#5628]
Hi, I'm having an issue orchestrating containers. I am unable to remotely access the database service from the web service. It seems that using the **web** container name for the remote user's host name does not correctly resolve to the appropriate IP.

If I create a mysql user with an explicit IP (eg. 172.18.0.3) as the host name, then the **database** service allows connections from that user. If I do the same thing but with the container name (eg. web) as the host name, then the **database** service does _not_ allow connections from that user.

This is the error: `[Warning] mysqli::real_connect(): (HY000/1045): Access denied for user 'ss_user'@'172.18.0.3' (using password: NO)`

Here is my docker-compose.yml:

```
version: '3'
services:
  web:
    image: brettt89/silverstripe-web
    container_name: web
    working_dir: /var/www
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html

  database:
    image: mysql
    container_name: database
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions

volumes:
  db-data:
```

If it helps, this is a Silverstripe CMS project. The needed db credentials are provided by a .env file:

```
# Environment
SS_ENVIRONMENT_TYPE="dev"

# DB credentials
SS_DATABASE_SERVER="database"
SS_DATABASE_USERNAME="ss_user"
SS_DATABASE_PASSWORD=""
SS_DATABASE_NAME="ss_database"
```

**Comment by shin-** [comment]
> If I create a mysql user with an explicit IP (eg. 172.18.0.3) as the host name, then the database service allows connections from that user. If I do the same thing but with the container name (eg. web) as the host name, then the database service does not allow connections from that user.

Sorry, I'm having a bit of trouble making sense of that part. Shouldn't the hostname you want to connect to be `database`, not `web`?

**Comment by JustinTBrown** [comment]
I believe in mysql this is the host that the user is expected to be connecting *from*. Often it's localhost, but in cases where external connections are expected it needs to be set to a wildcard (%), domain, or IP.

Just to check, I changed the user's host to **database** and also to 172.18.0.**2** (which is the IP of the **database**) service, but both settings produced the same error.

In my particular case, the connection is permitted if I use 172.18.0.3 (the IP of the **web** service), or if I use %, but for no other settings.

Hopefully that makes a bit more sense 😬

**Comment by JustinTBrown** [comment]
If it helps, this [issue](https://github.com/docker-library/mysql/issues/275#issuecomment-292208567) is what let me know I could use a wildcard (%) to allow connections to mysql from any IP address. I still need to figure out if this is a secure way of doing things.

**Comment by shin-** [comment]
Okay, I see what you mean now - thanks for clarifying.

The issue at hand is that [MySQL does reverse DNS lookup](https://serverfault.com/questions/363122/how-does-mysql-determine-the-hostname-of-its-clients) to figure out whether the hostname attempting to connect matches the one configured for the user, but the way the [default DNS](https://github.com/moby/moby/issues/20847#issuecomment-191850085) works in Docker, only a single PTR record will be returned for a given IP address, which will not be the same value as the `container_name` you provide. [1]

If I were you, I would set a static IP for the web service and limit connections based on that IP [2]. If you need to scale in the future, you can configure the network to only assign a certain range of IP addresses and validate connections based on that range.

[1] The way it is implemented currently, the PTR record for a container's IP address seems to be `<container_name>.<network_name>` - but I wouldn't rely on this.

[2] e.g.
```yaml
version: '3'
services:
  web:
    image: brettt89/silverstripe-web
    container_name: web
    working_dir: /var/www
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    networks:
      backend:
        ipv4_address: 172.16.100.99

  database:
    image: mysql
    container_name: database
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
    networks:
      backend:

volumes:
  db-data:
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24
```
