### ISSUE TITLE
docker/compose:latest not found

### ISSUE THREAD

**Issue by basickarl** [docker/compose#5707]
https://hub.docker.com/r/docker/compose/

States to install you do:
```
docker pull docker/compose
````

The latest tag does not exist so this is incorrect.
```
km@Karls-MBP ~ $ docker pull docker/compose
Using default tag: latest
Error response from daemon: manifest for docker/compose:latest not found
```

**Comment by shin-** [comment]
Please refer to the "This image" paragraph on that page:

> ## This image
>
> The `docker/compose` image on DockerHub is designed to be used with the [`run.sh` script](https://raw.githubusercontent.com/docker/compose/master/script/run/run.sh) available on the official GitHub repository. You can also refer to the section called ["Install as a container"](https://docs.docker.com/compose/install/#install-as-a-container) in the installation docs.

**Comment by basickarl** [comment]
I was hoping to use this in my gitlab-ci.yml file.

```
.dind: &dind
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script: 
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose
    - docker-compose --version

Test Docker Compose:
  <<: *dind
  stage: Test
  script:
    - docker-compose -f docker-compose.test.yml build job1
    - docker-compose -f docker-compose.test.yml down
    - docker-compose -f docker-compose.test.yml up --remove-orphans --force-recreate --abort-on-container-exit
```
As you can see I'm currently using the `docker:latest` image. I was hoping to replace it with this so I don't need to install docker compose everytime the template is used, but since you need to run a script for this however this probably won't work.

**Comment by shin-** [comment]
@basickarl You can download https://raw.githubusercontent.com/docker/compose/master/script/run/run.sh and use it in place of the `docker-compose` command.

**Comment by basickarl** [comment]
If I do as you say it will fail (and did fail) due to the `run.sh ` file not being available in the `docker:latest` image.
```
.dind: &dind
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2

Test Docker Compose:
  <<: *dind
  stage: Test
  script:
    - run.sh -f docker-compose.test.yml build job1
    - run.sh -f docker-compose.test.yml down
    - run.sh -f docker-compose.test.yml up --remove-orphans --force-recreate --abort-on-container-exit
```
