### ISSUE TITLE
Permissions are not overwritten in tmpfs subdirectory of volume directory

### ISSUE THREAD

**Issue by Kwadz** [docker/compose#5729]
Let's assume this docker-compose.yml:

```
version: '3'

services:
  website:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    tmpfs:
      - /var/www/html/app/cache/

```

Expected behaviour: the permission of `/var/www/html/app/cache/` should be 1777 (the default _tmpfs-mode_).
