### ISSUE TITLE
Configuring volumes to share host directory with container based on windows image does not work for me

### ISSUE THREAD

**Issue by DawidSadlik** [docker/compose#5777]
Hi
I'm trying to configure volumes sharing host (windows Server 2016) directory with container running from windows server core based image. I can't figure it how to properly define source path. Can anybody provide example of such configuration?

**Comment by shin-** [comment]
Should look something like this:
```yaml
- type: bind
  source: C:\my\path\here
  target: C:\container\path
```

In the future please direct questions like this one to our [forums](https://forums.docker.com).
