### ISSUE TITLE
ERROR: for behat_tests  Cannot start service behat_tests: linux mounts: Duplicate mount point '/dev/shm'

### ISSUE THREAD

**Issue by blackandred** [docker/compose#5797]
Hello, I can still reproduce the issue: https://github.com/docker/compose/pull/4761

When I have this appended to a service:
```yaml
    shm_size: 1G
    tmpfs: /dev/shm:rw,nosuid,nodev,noexec,relatime,size=1G
```

Docker-compose syntax version: 2

When I scale up the container, then an error appears.
At least two different Linux setups are affected.
On other twos it does not appear.

One of problematic setup: `docker-compose version 1.17.0, build ac53b73, Ubuntu 16.04`

Thanks for your time.

**Comment by shin-** [comment]
@blackandred Are you able to provide more details about your configuration? I wasn't able to reproduce the issue with the following Compose file:

```yaml
version: '2'
services:
  foo:
    shm_size: 1G
    tmpfs: /dev/shm:rw,nosuid,nodev,relatime,size=1G
    image: alpine
    command: top
```
