### ISSUE TITLE
Making extension fields valid anywhere in `docker-compose.yaml`

### ISSUE THREAD

**Issue by wesrice** [docker/compose#5806]
I've run into a scenario where I think it would be ideal to be able to add `x-*` extension fields to service definitions in my `docker-compose.yaml` file, like so:

```yaml
version: "3.4"

services:
  foo:
    build: ...
    ports: 
      - ...
    x-meta:
      my_var_1: ...
      my_var_2: ...
  bar:
    build: ...
    ports: 
      - ...
    x-meta:
      my_var_1: ...
      my_var_2: ...
```

I realize that I can "lift" my `x-meta` info to a valid state, like so:

```yaml
version: "3.4"

x-meta:
  services:
    foo:
      my_var_1: ...
      my_var_2: ...
    bar:
      my_var_1: ...
      my_var_2: ...

services:
  foo:
    build: ...
    ports: 
      - ...
  bar:
    build: ...
    ports: 
      - ...
```

However, I'm not a fan of this method because my `x-meta` structure has to shadow the services definitions object. In complex environments with many service definitions, the effort to maintain parity amongst the two constructs grows. I don't want to overstate this additional effort as a task that is super complex or anything, but frankly it is just a bit inconvenient.

Any thoughts on the possibility of making extension fields valid anywhere within `docker-compose.yaml`?
