### ISSUE TITLE
Compose `pull` should pull `cache_from` images

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/compose#5861]
## Description of the issue

It would be awesome if `docker-compose pull` also pulled `cache_from` images! Otherwise, I have to make a separate `docker pull` command.

## Context information (for bug reports)

```
PS> docker-compose version
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

```
PS> docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

## Steps to reproduce the issue

1. Create a Compose manifest with a `build` / `cache_from` option.
2. Use `docker-compose pull` or `docker-compose build --pull`

### Observed result

The `cache_from` images are not pulled and no "Using cache" messages are printed.

### Expected result

The `cache_from` images should be pulled and we should see "Using cache" messages printed.

**Comment by shin-** [comment]
I don't think that's desirable, at least not as the default. I'm sure there's many cases where pulling the `cache_from` image would take longer than rebuilding without it, not to mention the cases where the `cache_from` image isn't actually available remotely. It would break a lot of the current user expectation around the feature, which also matches the Docker CLI (`docker build --cache-from A .` never attempts to pull `A`).

**Comment by jimmiebtlr** [comment]
Any workarounds for this or updates?

**Comment by AnthonyMastrean** [comment]
We just run the pull separately before the Compose build. So, master is tagged latest and the branch is tagged by its name. So, we cache-from master and master or branch, respectively. Here's a chunk of our GitLab CI config (hopefully the automatic variables are self-explanatory).

```yaml
build:
  stage: build
  script:
    - docker image pull "$CI_REGISTRY_IMAGE" || true
    - docker image build --cache-from "$CI_REGISTRY_IMAGE" --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" --tag "$CI_REGISTRY_IMAGE" .
    - docker image push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker image push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-other:
  stage: build
  script:
    - docker image pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" || docker image pull "$CI_REGISTRY_IMAGE" || true
    - docker image build --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" --cache-from "$CI_REGISTRY_IMAGE" --pull --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker image push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker image push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  except:
    - master
    - tags
```
