### ISSUE TITLE
Cannot mix Windows and Linux containers in docker-compose.yml

### ISSUE THREAD

**Issue by KevM** [docker/compose#5872]
Attempting to mix windows and linux containers in a single `docker-compose.yml` does not work. 

## Description of the issue

With the release of compose 1.21.0 I was expecting to be able to mix windows and linux containers. 

## Context information (for bug reports)

```
Windows 10 Version 1709 (OS Build 16299.371)
Docker Engine: 18.04.0-ce-win62 (17151)
Machine: 0.14.0
Compose: 1.21.0
```
Output of "docker-compose config"
```
services:
  mssql:
    image: microsoft/windowsservercore
  nginx:
    image: nginx-alpine
    platform: linux
version: '2.4'
```

## Steps to reproduce the issue

1. Switch to Windows containers 
2. Run `docker-compose up`

### Observed result

```
Creating network "test_default" with the default driver
Pulling mssql (microsoft/windowsservercore:)...
latest: Pulling from microsoft/windowsservercore
ERROR: cannot download image with operating system "windows" when requesting "linux"
```

### Expected result

Containers to be started.

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Using Edge install of Docker for Windows.

**Comment by KevM** [comment]
> Is that possible? AFAIK you can't run windows & linux containers on the same machine at the same time

It is a great question. I don't see this limitation documented anywhere. [The FAQ](https://docs.docker.com/engine/faq/) states: 

> Does Docker run on Linux, macOS, and Windows?
>You can run both Linux and Windows programs and excutables in Docker containers. The Docker platform runs natively on Linux (on x86-64, ARM and many other CPU architectures) and on Windows (x86-64).

Is the `--platform` command line switch there to discriminate which image to pull from the registry? I was under the assumption that it was there to do that and target the correct Docker environment.

**Comment by shin-** [comment]
Based on what I'm seeing here: https://github.com/moby/moby/issues/35303

You might want to try setting the `platform` explicitly for both services. Let me know if that solves the issue.

**Comment by KevM** [comment]
@shin- Thanks for assistance.

Added the platform entry for the windows service:
```yml
services:
  mssql:
    image: microsoft/windowsservercore
    platform: windows
  nginx:
    image: nginx-alpine
    platform: linux
version: '2.4'
```
Still failing with a slightly different error message: 
```
> docker-compose up
Creating network "test_default" with the default driver
Pulling mssql (microsoft/windowsservercore:)...
ERROR: invalid platform: invalid platform os "windows"
```

Note: I do have an environment variable set `DOCKER_DEFAULT_PLATFORM=linux` if I switch it to be `windows` I get the same error.

**Comment by KevM** [comment]
Good news! After updating to Windows 10 **1809** the following compose file is working:

**Note: The image `nginx-alpine` was not working. Switching to `nginx` works. ** 
```
version: '2.4'

services:
  mssql:
    image: microsoft/windowsservercore
    platform: windows
  nginx:
    image: nginx
    platform: linux
```
