### ISSUE TITLE
giving tmpfs options with volumes syntax

### ISSUE THREAD

**Issue by jouve** [docker/compose#5907]
## Description of the issue

I see 2 ways of mounting a tmpfs in docker-compose:

``` yml
tmpfs:
  - /my/mount/point
```

``` yml
volumes:
  - type: tmpfs
    target: /my/mount/point
```

Now if I want to give options for the mount point, I can do it with the first syntax:
``` yml
tmpfs:
  - /my/mount/point:exec,size=1G
```

but I can't do it with the other syntax (or it's not documented):
``` yml
      - type: tmpfs
        target: /var/tmp/portage
        ???
```

## Context information (for bug reports)

Output of "docker-compose version"
```
docker-compose version 1.21.0, build 5920eb0
docker-py version: 3.2.1
CPython version: 3.6.3
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```
Output of "docker version"
```
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:21:20 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:19:27 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
Output of "docker-compose config"
``` yml
services:
  toto:
    image: alpine:3.7
    tmpfs:
    - /var/tmp/portage:exec,size=1G
version: '2.3
```

**Comment by shin-** [comment]
https://docs.docker.com/compose/compose-file/compose-file-v2/#long-syntax

**Comment by jouve** [comment]
@shin- Then how do you give "exec" ? 

Is there a hidden/undocumented keyword like for size ?

```
 - type: tmpfs
   target: /target/dir
  tempfs:
    size: 1G
    ??? exec ???
```

**Comment by glensc** [comment]
With docker-compose-1.26.2 the `o: exec` worked, but `docker-compose-1.28.2` does not allow it anymore.

**Comment by glensc** [comment]
The long syntax worked with docker-ce-19.03.5-1.x86_64.rpm but after upgrade to docker-ce-19.03.14-1.x86_64 it stopped working as well. "noexec" just appeared in mounts, not under my control.

solution is to go back to plain old short syntax:

```yml
    tmpfs:
      - /home/builder/rpm/BUILD:exec,nosuid,nodev,size=$TMPFS_SIZE
```

**Comment by mpeter50** [comment]
The response of @shin- was unhelpful, the documentation does not detail the `driver_opts` usage for the local driver.

This is how I could define a tmpfs volume in the top level volumes section:
```yml
volumes:
    my_temp_volume:
        driver: local
        driver_opts:
            type: tmpfs
            o: size=1G
            device: tmpfs

services:
    [...]
    volumes:
      - my_temp_volume:/tmp
```

The result is a volume printed like this by running `mount` on the Docker host system:
```
tmpfs on /var/lib/docker/volumes/project_my_temp_volume/_data type tmpfs (rw,relatime,size=1048576k,inode64)
```
