### ISSUE TITLE
fig scale - not creating links

### ISSUE THREAD

**Issue by STOIE** [docker/compose#595]
Hi there,

First, here is my fig.yml:

```
web:
  image: web:latest
  links:
   - "db"
  ports:
   - "80"
db:
  image: db:latest
```

I am trying to run the following (hope you can get a simple understanding of my example):

```
fig scale web=1 db=3
```

This is how fig starts the containers:

```
prefix_db_1
prefix_db_2
prefix_db_3
prefix_web_1
```

However, if I "docker exec -t -i prefix_web_1 /bin/bash" and run "cat /etc/hosts" on the container I can't see any db links.

Where as, if I simply run "fig -d up", I can see the db references in /etc/hosts. But, it only starts up the following:

```
prefix_db_1
prefix_web_1
```

...as expected.

Anyone able to help, I think this is a bug?!?

Thanks,
Aaron.

**Comment by hanzheng** [comment]
any progress here?

**Comment by jmervine** [comment]
I was able to use this workaround for my use case, where it's an image I'm building that I want to scale and link in to a proxy server (nginx in this case):

```yaml
# where directory is "foobar"
app0:
    build: .
app1:
    image: foobar_app0
app2:
    image: foobar_app0
nginx:
    build: .
    links:
    - app0
    - app1
    - app2
```
