### ISSUE TITLE
Docker-toolbox - ERROR: No containers to start

### ISSUE THREAD

**Issue by IkumiMashiba** [docker/compose#5962]
## Description of the issue
ERROR: for db  Cannot start service db: cgroups: cannot find cgroup mount destination: unknown
ERROR: No containers to start

## Context information (for bug reports)
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

```
docker-compose version 1.21.2, build a1334711
```

```
Docker version 18.03.0-ce, build 0520e24302
```

```
docker-machine.exe version 0.14.0, build 89b8332
```

other.
I tried but the result was the same.
docker-compose 1.19.0
docker-compose 1.20.1

## Steps to reproduce the issue
1.docker-compose up -d ... done
2.docker-compose stop ... done
3.docker-compose start ... error

### Stacktrace / full error message
ERROR: for db  Cannot start service db: cgroups: cannot find cgroup mount destination: unknown
ERROR: No containers to start

## Additional information
Win10 1709 Enterprise x64
Memory 8G
Oracle VirtualBox 5.2.8

This will succeed
```
docker-machine restart
docker-compose start
```

**Comment by IkumiMashiba** [comment]
![docker-compose](https://user-images.githubusercontent.com/12806774/40034111-6249b1d4-5836-11e8-8add-aadef5e7a60b.png)

**Comment by shin-** [comment]
Please share your Compose file.

**Comment by IkumiMashiba** [comment]
docker-compose.yml

```
version: '3'

services:
  db:
    container_name: db
    build:
      context: ./maria10.3
      dockerfile: Dockerfile
    image: xiaoqiong:db
    volumes:
      - xiaoqiong-mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: JST-9
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "sales_ledger"

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      TZ: JST-9
    depends_on:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "8080:80"
    environment:
      TZ: JST-9
      PMA_HOST: db
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:3.2
    volumes:
       - xiaoqiong-redis:/data
    ports:
      - "6379:6379"
    environment:
      TZ: JST-9
    command: redis-server
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    image: xiaoqiong:web
    volumes:
      - /c/Users/i-mashiba/workspace/xiaoqiong:/var/www/html
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: JST-9
    depends_on:
      - db
      - redis

  sphinx:
    container_name: sphinx
    build:
      context: ./sphinx
      dockerfile: Dockerfile
    image: aimiliya:sphinx
    volumes:
      - /c/Users/i-mashiba/workspace/aimiliya:/var/www/html
    privileged: true
    ports:
      - "928:80"
    environment:
      TZ: JST-9
    depends_on:
      - db
      - redis

volumes:
  xiaoqiong-mariadb:
    driver: local
  xiaoqiong-redis:
    driver: local
```
