### ISSUE TITLE
exit-code-from reports wrong exit code

### ISSUE THREAD

**Issue by djui** [docker/compose#5966]
## Description of the issue

The feature flag `--exit-code-from` does not always cause `docker-compose up` to exit with the specified service's exit code. An example scenario:

The composition is service *A* and *B*. *B* fails during startup, *A* gets shutdown due to the implicit ` --abort-on-container-exit`. The recorded exit code for *A* is `143` however the `docker-compose up` command exits with `0`.

```
$ docker-compose up --exit-code-from a
:
project_b_1 exited with code 1
Aborting on container exit...
Stopping project_a_1  ... done

$ echo $?
0

$ docker ps -a
CONTAINER ID        IMAGE             COMMAND   CREATED             STATUS                       PORTS       NAMES
bcf51d98a528        project_a         "cmd-a"   2 minutes ago       Exited (143) 12 seconds ago              project_a_1
f5c80933c38d        project_b         "cmd-b"   2 minutes ago       Exited (1) 12 seconds ago                project_b_1
```

## Context information (for bug reports)

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

```
networks:
  backend: {}

services:
  a:
    build: .
    depends_on:
      b:      
    init: true
    networks:
      backend: null
    ports:
    - 5000:5000/tcp
  b:
    image: b
    init: true
    networks:
      backend: null
version: '2.3'
```

## Steps to reproduce the issue

1. Define two services _a_ and _b_ in `docker-compose.yml`.
2. Let service _b_ crash/exit on startup.
3. Start composition using docker-compose up --exit-code-from a`.

### Observed result

Exit code is `0`.

### Expected result

Exit code `!0` (here likely: `143` or even better what the service _actually_ reported)

### Stacktrace / full error message

-

## Additional information

MacOS 10.13.4, Official Docker installer.
