### ISSUE TITLE
Allow to pass dockerfile from stdin

### ISSUE THREAD

**Issue by caub** [docker/compose#6042]
Similarly to 

```bash
docker build -t foobar -f-<<EOF
FROM some-image
EOF
```
or
```bash
echo 'FROM some-image' | docker build -t foobar -f-
```
I'd like to be able to do in a `docker-compose.yml`:

```yml
version: '3.1'
services:
  foobar:
    build:
      context: ../foobar
      dockerfile: /dev/stdin
```
and run 
```bash
echo 'FROM some-image' | docker-compose -f config/docker-compose.yml up --build -
```
