### ISSUE TITLE
Windows password change is not reconized

### ISSUE THREAD

**Issue by Kelvin-Meyer** [docker/compose#6064]
## Description of the issue
After changing my windows password docker runs into problems.

## Context information (for bug reports)
It would be nice if docker could give a warning that there is something wrong with the password instead of a driver programming issue.

https://github.com/docker/compose/issues/3277

```
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017```

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false```

```
version: '2'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
    - C:\dev\gitlab\X/build/www:/usr/share/nginx/html
    - C:\dev\gitlab\X/site.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "19192:19192"

```

## Steps to reproduce the issue
1. Start nginx (in my case)
2. Confirm the workings
3. Change windows password
4. Reboot
4. Start nginx again

### Observed result
![image](https://user-images.githubusercontent.com/11310940/42328696-f65c7b9e-803c-11e8-8f2f-ddae712c4ee7.png)

### Expected result
![image](https://user-images.githubusercontent.com/11310940/42329027-ce30d4ac-803d-11e8-8e79-2a2ad1cb6c8e.png)

## Additional information
Interesting behavior BTW I've changed my password back to the password it was before and docker automatically worked again. Does it store it in plain text?

OS version / distribution, `docker-compose` install method, etc.
Windows 10
