### ISSUE TITLE
Is it possible to pass ENV variables in docker-compose.yml at key "build.args"?

### ISSUE THREAD

**Issue by pedrofurtado** [docker/compose#6066]
Is it possible to pass ENV variables (from .env file) in `docker-compose.yml` with a structure like this below?

```yaml
version: '3'

services:
  somename:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - "MY_ARG=${MY_ENV_VAR}"
```
