### ISSUE TITLE
Forward application container port to multiple host ports is not working.

### ISSUE THREAD

**Issue by kwk** [docker/compose#609]
Hello,

I want to use fig but there's a problem with port forwarding.

With pure docker you can forward an container application's port (e.g. `5000`) to multiple host ports by writing:

```
docker run \
  -p 10.1.2.3:111:5000 \
  -p 10.1.2.3:222:5000 \
  myimage
```

This should create the two host ports `111` and `222` on the IP `10.1.2.3`. Both forward to the container's port `5000`.

When I write this piece of code in my `fig.yml`, only the `222` will be created:

``` yaml
    foo:
      image: myimage
      ports:
        - "10.1.2.3:111:5000"
        - "10.1.2.3:222:5000"
```

Is this by design or is this a bug?
