### ISSUE TITLE
when using docker-compose, meet a strange problem. please help me

### ISSUE THREAD

**Issue by yanwenwu** [docker/compose#6196]
## Description of the issue
when using docker-compose run nginx container, The nginx container is already listening on port 80, but I can't access it through a browser. But if you start the nginx container through the docker command, you can actually access it. I don't know where the problem is, please give me some advice.
## Context information (for bug reports)

```
docker-compose version 1.19.0, build 9e633ef
```

```
Docker version 18.06.1-ce, build e68fc7a
```

```
version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./log/nginx:/etc/nginx/log/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/error.log:/var/log/nginx/error.log:rw
    restart: always
    ports:
      - "80:80"
    links:
      - php72:php72
    container_name: nginx
```

## Steps to reproduce the issue

1. docker-compose up -d, start container
2. visit the website
3. Refusing the request, telnet ip 80, is also rejected

### Stacktrace / full error message
no error
```
(if applicable)
```

## Additional information
docker ps, result:
```
228964a29c5e        nginx:latest        "nginx -g 'daemon of…"   17 minutes ago      Up 14 minutes       0.0.0.0:80->80/tcp                  nginx
91f98e46886f        dockerlnmp_php72    "docker-php-entrypoi…"   2 hours ago         Up 14 minutes       0.0.0.0:9000->9000/tcp              php
e33568b522e6        mysql:latest        "docker-entrypoint.s…"   2 hours ago         Up 14 minutes       0.0.0.0:3306->3306/tcp, 33060/tcp   mysql
b09790235aa9        redis:latest        "docker-entrypoint.s…"   2 hours ago         Up 14 minutes       0.0.0.0:6379->6379/tcp              redis
```
netstat -anp| grep 80
```
tcp6       0      0 :::80                   :::*                    LISTEN      7080/docker-proxy 
```
firewall-cmd --permanent --zone=public --list-ports
```
443/tcp 80/tcp
```
OS version / distribution, `docker-compose` install method, etc.
centos7+, pip install
