### ISSUE TITLE
Proposal: Make env_file and secrets file compatible

### ISSUE THREAD

**Issue by jvitor83** [docker/compose#6211]
## Make [env_file](https://docs.docker.com/compose/env-file/) and [secrets](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose) file compatible

Then we can use something like:
```
version: "3.5"

services:

  helloworld:
    image: tutum/hello-world
    ports:
      - 80:80
    env_file:
     - /run/secrets/my_secret
    secrets:
      - my_secret

secrets:
  my_secret:
    file: ./my_secret.txt
```
and get the environment variable like `my_secret=secret_value`

> Or maybe something like `env_secret:` _(just like `env_file:`)_?

**Comment by shin-** [comment]
Hi @jvitor83 

I believe there is some confusion here. `env_file` entries are evaluated when the configuration is parsed, and are files located on your host machine, not inside the container. Hence, your hypothetical Compose file could be rewritten as:

```yaml
version: "3.5"
services:
  helloworld:
    image: tutum/hello-world
    ports:
      - 80:80
    env_file:
     - ./my_secret.txt
    secrets:
      - my_secret
secrets:
  my_secret:
    file: ./my_secret.txt
```

and work as intended.

**Comment by jvitor83** [comment]
Hi @shin- 
In my test it didn't create the variable `my_secret`:
```
version: "3.5"
services:
  helloworld:
    image: tutum/hello-world
    ports:
      - 8081:80
    environment:
      eee: aaa
    env_file:
     - ./my_secret.txt
    secrets:
      - my_secret
    entrypoint: printenv
secrets:
  my_secret:
    file: ./my_secret.txt
```
