### ISSUE TITLE
Unable to create file volumes in compose in Docker for Windows 

### ISSUE THREAD

**Issue by pdavis68** [docker/compose#6242]
## Description of the issue

I am under the impression, from looking at various examples of docker-compose.yml files, that I should be able to map a file directly using `volumes` in my .yml files. That functionality doesn't appear to be working correctly (or I'm possibly not understanding how it should work maybe?).

## Context information (for bug reports)

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
services:
  alpine:
    entrypoint: ls -al /data
    image: alpine:latest
    volumes:
    - ./temp.dat:/data/temp.dat:rw
version: '3.0'
```

## Steps to reproduce the issue

Using this docker-compose.yml, run docker-compose up
```
version: '3'
services:

  alpine:
    image: alpine:latest
    
    volumes:
        - ./temp.dat:/data/temp.dat
        
    entrypoint: ls -al /data
```

### Observed result

Starting dirproblem_alpine_1 ... done
Attaching to dirproblem_alpine_1
alpine_1  | total 8
alpine_1  | drwxr-xr-x    3 root     root          4096 Sep 30 22:00 .
alpine_1  | drwxr-xr-x   25 root     root          4096 Sep 30 22:00 ..
alpine_1  | drwxr-xr-x    2 root     root            40 Sep 30 22:05 temp.dat

### Expected result

temp.dat would be a file, not a directory.

## Additional information

I have the file temp.dat in the directory with my docker-compose.yml file and it is the directory from which I'm running `docker up`

I've been trying to set up wikijs and a bunch of their examples using docker-compose, show files being mapped. For example, the config.yml file in this examples:
https://github.com/Requarks/wiki/blob/master/tools/docker-compose.yml

**Comment by shin-** [comment]
A few thoughts:

1. Did you give Docker Desktop access to the drive you're working on? See the docs on [Shared Drives](https://docs.docker.com/docker-for-windows/#shared-drives)
2. It's weird that your host path doesn't get expanded in the output of `docker-compose config`. Is that the actual output or did you tweak it?
3. You might have an easier time diagnosing it if you use the mount syntax instead, which will error out if the file/folder doesn't exist locally instead of creating an empty folder, e.g.

```yaml
version: '3.4'
services:

  alpine:
    image: alpine:latest
    
    volumes:
        - type: bind
          source: ./temp.dat
          target: /data/temp.dat
        
    entrypoint: ls -al /data
```
should show you an error message like
```
$ docker-compose up
Creating network "repro6242_default" with the default driver
Pulling alpine (alpine:latest)...
latest: Pulling from library/alpine
4fe2ade4980c: Already exists
Creating repro6242_alpine_1_fa613170d443 ... error

ERROR: for repro6242_alpine_1_fa613170d443  Cannot create container for service alpine: invalid mount config for type "bind": bind mount source path does not exist: /home/joffrey/work/tests/compose/repro6242/temp.dat

ERROR: for alpine  Cannot create container for service alpine: invalid mount config for type "bind": bind mount source path does not exist: /home/joffrey/work/tests/compose/repro6242/temp.dat
ERROR: Encountered errors while bringing up the project.
```

**Comment by pdavis68** [comment]
1. Yes, I have my C and F drives shared with docker.

2. I'm not sure which path you're referring to, exactly. I believe everything is a copy and paste from what I had.

3 I tried doing the bind mount.

From what I'm actually trying to accomplish, and based on your post, I have the following in my docker-compose.yml :

```
version: '3.4'
services:

  wikidb:
    image: mongo:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: expassword 
      
    volumes:
        - /mongo/data/db:/data/db
        - type: bind
          source: ./data/mongod.conf
          target: /data/mongod.conf
        
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '1081:3000'
    environment:
      WIKI_ADMIN_EMAIL: pdavis68@gmail.com
    volumes:
      - type: bind
        source: ./data/config.yml
        target: /var/wiki/config.yml        
      - type: bind
        source: ./logs
        target: /logs
```

I am running from the directory: F:\docker\wikijs

Inside wikijs is a "data" sub-directory with a mongod.conf file. So the full path would be: F:\docker\wikijs\data\mongod.conf

When I run `docker-compose up` with the bind mount, I get the following:

ERROR: for ffdde0a98ca3_wikijs_wikidb_1  Cannot create container for service wikidb: invalid mount config for type "bind": bind mount source path does not exist: /f/docker/wikijs/data/mongod.conf

ERROR: for wikidb  Cannot create container for service wikidb: invalid mount config for type "bind": bind mount source path does not exist: /f/docker/wikijs/data/mongod.conf
