### ISSUE TITLE
After many docker-compose down and up I have problems in the network

### ISSUE THREAD

**Issue by vncoelho** [docker/compose#6305]
In several Linux distributions we are having this problem with Docker-compose.

We create several containers and use `down` and `up -d` many times.
The containers are all connected between them, no network is used.

The only solution is to use `service docker restart ` in order to reestabilish normal communication between the swarm.

**Comment by shin-** [comment]
Hi @vncoelho ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with the Docker Engine, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.

**Comment by vncoelho** [comment]
This was not a support.

It was a bug and described properly, not very well, but you could had taken some little time.
As I said, I use the `docker-compose`.

Networks are defined in the `docker` engine.

I am not used to the structure of the docker to understand who is the responsible for cleaning the docker service after the `down` of the compose.

**Comment by vncoelho** [comment]
@shin, this issue is still not solved.
I also opened it here.
I suggested it to be reopened until you are sure where the problem is.

https://github.com/docker/for-linux/issues/630

**Comment by vncoelho** [comment]
I will reproduce it here for clarity:



* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one



### Expected behavior
Docker should create several containers and after being stopped the containers should again be created and operate normally.

### Actual behavior
We have a swarm of container initialized with docker-compose and everything normally in most of the time.

But, sometimes, after creating, stopping and deleting containers, the containers can not see each other when initialized.

Then, the only solution is to use `service docker restart`.

We already discussed this at docker-compose, but they said the problem was with docker itself.

### Steps to reproduce the behavior

Basically, starting and stopping docker-compose with some containers:
`(cd docker-compose-eco-network; docker-compose up -d)`
`(cd docker-compose-eco-network; docker-compose down)`

```
# ================================================================================
# ========== WELCOME TO THE NEOCOMPILER ECO NEO BLOCKCHAIN MICROSERVICE  =========
# ================================================================================
version: "3.7"
services:
# ================================================================================
# ================== OPEN CONTAINER WITH NEO-CLI CONSENSUS NODES AND RPC =========
  eco-neo-csharp-node1-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node1-running"
    privileged: true
    ports: # config1.json
      - "20333:20333"
      - "30333:30333"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config1.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/configs/plugins/rpcNep5Tracker.json:/opt/node/neo-cli/Plugins/RpcNep5Tracker/config.json
      - ./neo-cli/configs/plugins/rpcSystemAssetTracker.json:/opt/node/neo-cli/Plugins/RpcSystemAssetTracker/config.json
      - ./neo-cli/wallets/wallet1.json:/opt/node/neo-cli/wallet1.json
      - ./logs-neocli-node1:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 1
      NUMBER_SERVER: 1
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/20333
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  eco-neo-csharp-node2-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node2-running"
    privileged: true
    ports: #config2.json
      - "20334:20334"
      - "30334:30334"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config2.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/configs/plugins/rpcNep5Tracker.json:/opt/node/neo-cli/Plugins/RpcNep5Tracker/config.json
      - ./neo-cli/configs/plugins/rpcSystemAssetTracker.json:/opt/node/neo-cli/Plugins/RpcSystemAssetTracker/config.json
      - ./neo-cli/wallets/wallet2.json:/opt/node/neo-cli/wallet2.json
      - ./logs-neocli-node2:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 1
      NUMBER_SERVER: 2
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/20334
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  eco-neo-csharp-node3-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node3-running"
    privileged: true
    ports: #config3.json
      - "20335:20335"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config3.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/wallets/wallet3.json:/opt/node/neo-cli/wallet3.json
      - ./logs-neocli-node3:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 0
      NUMBER_SERVER: 3
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/20335
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  eco-neo-csharp-node4-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-node4-running"
    privileged: true
    ports: #config4.json
      - "20336:20336"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config4.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/wallets/wallet4.json:/opt/node/neo-cli/wallet4.json
      - ./logs-neocli-node4:/opt/node/neo-cli/Logs
    environment:
      IS_CONSENSUS: 1
      IS_RPC: 0
      NUMBER_SERVER: 4
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/20336
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  eco-neo-csharp-noderpc1-running:
    image: eco-neo-csharp-node:latest
    container_name: "eco-neo-csharp-noderpc1-running"
    privileged: true
    ports: #config1RPC.json
      - "20337:20337"
      - "30337:30337"
    volumes:
      - ./neo-cli/configs/protocol.json:/opt/node/neo-cli/protocolNeoCompiler.json
      - ./neo-cli/configs/config1RPC.json:/opt/node/neo-cli/config.json
      - ./neo-cli/configs/plugins/simplePolicyConfig.json:/opt/node/neo-cli/Plugins/SimplePolicy/config.json
      - ./neo-cli/configs/plugins/appLogConfig.json:/opt/node/neo-cli/Plugins/ApplicationLogs/config.json
      - ./neo-cli/configs/plugins/rpcSecurity.json:/opt/node/neo-cli/Plugins/RpcSecurity/config.json
      - ./neo-cli/configs/plugins/statesDumper.json:/opt/node/neo-cli/Plugins/StatesDumper/config.json
      - ./neo-cli/configs/plugins/rpcNep5Tracker.json:/opt/node/neo-cli/Plugins/RpcNep5Tracker/config.json
      - ./neo-cli/configs/plugins/rpcSystemAssetTracker.json:/opt/node/neo-cli/Plugins/RpcSystemAssetTracker/config.json
      - ./neo-cli/getIncStorage.sh:/opt/getIncStorage.sh
    depends_on:
      - eco-neo-csharp-node1-running
    environment:
      IS_CONSENSUS: 0
      IS_RPC: 1
      NUMBER_SERVER: 5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30337"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# ================== OPEN CONTAINER WITH NEO-CLI CONSENSUS NODES AND RPC =========
# ================================================================================

# ================================================================================
# ======================= THANKS FOR CREATING ME =================================
# ================================================================================
```

**Output of `docker version`:**

```
Docker version 18.09.3, build 774a1f4
```

We have been having this problem for a long time with different versions.

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 241
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-46-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53GiB
Name: xxxxx
ID: 74PL:NAIU:UI7J:PBMD:P4QL:DALW:3BM6:TRPL:I347:GETD:Z3OI:4I2S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: xxxx
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

We tested in DigitalOcean and physical. The problem happens in both in at different versions.
