### ISSUE TITLE
Incorrect environment variable warnings during `exec`

### ISSUE THREAD

**Issue by DomHudson** [docker/compose#6350]
## Description of the issue
Compose warns of unset environment variables when running `exec` in an existing container even if the environment variables are already set.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Output of `docker version`**
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      TEST_VARIABLE: ''
    image: mysql:5.7.22
version: '3.2'
```

**Ouput of `cat docker-compose.yml`**

```
version: '3.2'

services:

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      TEST_VARIABLE: ${TEST_VARIABLE}
```

## Steps to reproduce the issue

1. Copy the contents above into a `docker-compose.yml` file.
2. Start the service with `TEST_VARIABLE=test docker-compose up -d`.
3. Exec any command into the `db` container, for example: `docker-compose exec db bash`

### Observed result
The system warns me with `WARNING: The TEST_VARIABLE variable is not set. Defaulting to a blank string.`
Running `env` in the container shows that the variable is present:
```
$ root@5b357d005cff:/# env
...
TEST_VARIABLE=test
...
```

### Expected result
I only expect to see this warning if the environment variable was not supplied when the services were started. The warning claims that the variable is not exported.

## Additional information

![peek 2018-11-18 14-10](https://user-images.githubusercontent.com/10864294/48673683-d8575500-eb3b-11e8-9116-dba82fa2b926.gif)

**Comment by shin-** [comment]
Hi @DomHudson , thanks for the report!

Compose is warning you when a variable used in your service definition can't be found *in the environment where Compose is executed*. As such, because `TEST_VARIABLE` is not defined on your host, this is behaving as expected.
That said, in the context of the `exec` command, we can probably infer that the variable's absence will not affect the result, and it might make sense to suppress these warnings there.

**Comment by DomHudson** [comment]
Hi @shin- thanks for the response! Okay that makes sense; I do agree that suppressing it in this case makes sense help if possible as it can be a bit misleading.

**Comment by milhomem** [comment]
Hey guys, I've just upgraded to
`docker-compose -v
docker-compose version 1.23.2, build 1110ad01`

And it seems that it's buggy because it was working on
`docker-compose -v
docker-compose version 1.22.0, build f46880f`

I guess that my issue is related to using a relative path in the `--project-directory` option and `docker-compose` is not able to find the `.env` file. It works when I change it to a full path.

Here is how I've reproduced it:
```
test $ pwd
/tmp/test
test $ docker-compose -v
docker-compose version 1.22.0, build f46880f
test $ docker-compose --project-directory test up -d
test-env is up-to-date
```
```
test $ docker-compose -v
docker-compose version 1.23.2, build 1110ad01
test $ docker-compose --project-directory test up -d
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
Recreating test-env ... done
test $ docker-compose --project-directory /tmp/test up -d
Recreating test-env ... done
```
```
test $ cat .env
MYSQL_ROOT_PASSWORD=root

test $ cat docker-compose.yml
version: '3'

services:
  test-env:
    container_name: test-env
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
```
