### ISSUE TITLE
network problem

### ISSUE THREAD

**Issue by Goatmaster** [docker/compose#6360]
Hey,

I have a server with three network interfaces (eth0, eth1, eth2). Now I want to run two container with help of docker-compose (nginx, php). The nginx should only be available with the ip of eth1 but when I start the container with the _docker-compose up -d_ command the nginx is available on all three ip's (eht0, eth1, eht2).

I created the docker network before.
```
docker network create -d bridge -o parent=eth1 eth1
```

Here is my docker-compose.yml fiel.
```
version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - eth1

    php:
        build: .
        container_name: php
        volumes:
            - ./code:/code
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - eth1

networks:
  eth1:
    external: true
```

Docker and docker-compose version
```
docker -v
Docker version 17.06.0-ce, build 02c1d87
```
```
docker-compose -v
docker-compose version 1.23.1, build b02f1306
```

Any ideas how to fix this problem?

**Comment by shin-** [comment]
Hi @Goatmaster 

You should be able to resolve this by removing the `ports` entry of your `web` service, which intentionally exposes the 80 port on 0.0.0.0 (all interfaces). If you omit it, port 80 will still be accessible through `eth1`, but won't be exposed on other interfaces.

Let me know if that helps!

**Comment by Goatmaster** [comment]
> 
> 
> Hi @Goatmaster
> 
> You should be able to resolve this by removing the `ports` entry of your `web` service, which intentionally exposes the 80 port on 0.0.0.0 (all interfaces). If you omit it, port 80 will still be accessible through `eth1`, but won't be exposed on other interfaces.
> 
> Let me know if that helps!

If I remove the ports section. I cannot reach the webserver on any interface.

**Comment by shin-** [comment]
Sorry, looking at this again, I think the issue is that you're trying to use the `bridge` driver for your networks when what you actually need is a [`macvlan` network](https://docs.docker.com/network/macvlan/)

**Comment by Goatmaster** [comment]
I still haven't found a solution for my problem. Nobody else who can help me?

**Comment by Goatmaster** [comment]
I also tried now with another docker-compose.yml file but this also doesn't work for me.

```
version: '2.1'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
          outside:
            ipv4_address: 192.168.1.153

networks:
  outside:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.1.0/24
```

Can not reach the nginx on the defined ip address.

**Comment by ijc** [comment]
You don't say in your original post whether your 3 Ethernet devices are on the same subnet or not, but I wonder if you might be suffering from the issue where Linux will sometimes reply to connections for a specific IP address even if they don't arrive via the appropriate/corresponding interface.

I think (although my memory is very fuzzy) that the `arp_filter` sysctl is the tunable for this behaviour. Some refs:
- https://unix.stackexchange.com/questions/31096/sysctl-parameter-for-correct-arp-response
- https://wiki.openvz.org/Multiple_network_interfaces_and_ARP_flux (esp. "A More Complex Case" which I think is close to what you describe)
- https://robertlathanh.com/2009/08/two-subnetworks-on-one-lan-and-linux-arp_filter/

**Comment by Goatmaster** [comment]
Yes I tried it with only one physical connection that is working as bridge. Just wanted to check if it maybe is working with that options. But still the same I cannot reach the nginx on the ip of the host itself either on the ip given in the docker-compose file.

The host system (CoreOS or PhotonOS) is running on a vmware esxi server. Are there some setting I have to do on the host system itself?

**Comment by ijc** [comment]
> Yes I tried it with only one physical connection that is working as bridge.

The number of physical interfaces which are used for bridging (vs being just normal interfaces) is not relevant to the arp filtering issue I described. If you have more than one physical interface (in any configuration) then the links I provided should help.

> Are there some setting I have to do on the host system itself?

You've now used `host` here to mean 2 different things (either the system running Docker or the system running vmware), which is rather confusing.

It sounds like you *maybe* are expecting things bound to addresses on the Docker "host" IP to be somehow visible on the vmware "host" IP address. Those are effectively two independent systems with two separate network stacks so this wont work (maybe vmware has forwarding options, but you would need to ask vmware support about that).

It's also unclear to me now which system you are running your testing from (one of the hosts, some other machine?) and whether or not you have setup your external routing arrangements such that external connections to the container are being directed to the right place.

I think in order to reduce misunderstandings and confusion it would be best if you were to provide full repro steps, including at least:
* the `docker-compose.yml` file you are currently using
* any setup you are doing before hand (`docker network create` etc)
* the resulting network setup on your Docker host (e.g. the output of  `ifconfig -a` and the output of `route -n`)
* the commands you are running to bring up the stack
* the commands you are running to test things are behaving as you expect (e.g. various `curl` invocations), be sure to be precise here about which system those commands are run on (docker host vs vmware host vs a different client machine).

**Comment by Goatmaster** [comment]
Sorry for confusing you.

I am using CoreOS as the docker host system. The CoreOS itself is running on a VMware Cluster.

My goal is to run multiple web server container with different ip addresses (not the one of the CoreOS either the one of VMware) on the CoreOS.

So my first idea was to add another network adapter with a static ip address to the CoreOS. Than I added the network adapter to the docker networks.

```
docker network create -d bridge -o parent=eth1 eth1
```

My problem with that solution is that the web server is also reachable through the ip address of the CoreOS itself. If I now want to add a third network adapter to run another docker nginx instance on it there is an error that says that the ports are already in use.

Here is the docker-compose.yml file I used for that try.

```
version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - eth1

    php:
        build: .
        container_name: php
        volumes:
            - ./code:/code
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - eth1

networks:
  eth1:
    external: true
```

Now another idea was to use the bridge function and let all run on one network adapter. But when I tried this I can not reach the web server through any ip address.

I used this docker-compose.yml file for the solution.

```
version: '2.1'

services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
          outside:
            ipv4_address: 192.168.1.153

networks:
  outside:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.1.0/24
```

For starting both of the solutions I used the following command.

```
docker-compose up -d
```

The thing why I mentioned VMware was another idea of me that maybe on the VMware Cluster itself I have to make some special network settings.

I hope you can understand the problem better now.
