### ISSUE TITLE
Feature, evaluate command in fig.yml

### ISSUE THREAD

**Issue by florentvaldelievre** [docker/compose#638]
Hi,

It would be nice to have fig evaluate commands like this:

```yaml
data:  
  volumes:
    - /var/logs/`hostname`:/logs
 environment:
   - json: `cat ~/docker/zookeeper/env.json`
```

PS: at the moment, i can't use fig as i run my container like this:

```bash
docker run -e json="$(cat ~/docker/zookeeper/env.json)"  -v /var/logs/`hostname`:/logs
```

**Comment by dnephin** [comment]
environment interoplation is now support, so you can evaluate things in the environment and have them available in the config.

```
data:  
  volumes:
    - /var/logs/${HOSTNAME}:/logs
 environment:
   JSON:
```

set `HOSTNAME` and `JSON` in the environment that runs `docker-compose`
