### ISSUE TITLE
Cannot override arrays with empty arrays in depends_on in docker-compose

### ISSUE THREAD

**Issue by jacekjab** [docker/compose#6426]
## Description of the issue
I have 2 docker-compose files configured like that:
docker-compose.yml
```
version: '3.7'

services:
  webapp:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: myimage
    depends_on:
      - db
      - ui
...
```
docker-compose.test.yml
```
version: '3.7'

services:
  webapp:
    depends_on: []
```
However when running with overriden configuration services db and ui are still being created.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

## Steps to reproduce the issue

1. docker-compose -f docker/docker-compose.yml -f docker/docker-compose.test.yml run webapp /bin/bash

### Observed result
```
Creating db_1 ... done
Creating ui_1 ... done
root@462118f09023:myservice $
```
### Expected result
```
root@462118f09023:myservice $
```
Dependant images are not created.
