### ISSUE TITLE
Tag based filtering

### ISSUE THREAD

**Issue by willis7** [docker/compose#6438]
**Is your feature request related to a problem? Please describe.**
Yes. I want the ability to run combinations of containers in different situations. The examples below give some context.

**Describe the solution you'd like**
This is borrowed from Ansible:

> If you have a large playbook, it may become useful to be able to run only a specific part of it rather than running everything in the playbook. Ansible supports a “tags:” attribute for this reason.
When you execute a playbook, you can filter tasks based on tags in two ways:
> * On the command line, with the --tags or --skip-tags options
> * In Ansible configuration settings, with the TAGS_RUN and TAGS_SKIP options

```yaml
web:
  image: example/my_web_app:latest
  links:
    - db
    - cache
    - messaging
  tags:
    - test
    - dev

db:
  image: postgres:latest
  tags:
    - test
    - dev

cache:
  image: redis:latest
  tags:
    - cache

messaging:
  image: rabbitmq:latest
```

_Example 1_
`docker-compose -f docker-compose.yml --tags test --tags cache up -d`
In this example, `web`, `db` and `cache` will run, but not `messaging`.

_Example 2_
`docker-compose -f docker-compose.yml --skip-tags cache up -d`
In this example, `web`, `db` and `messaging` will run, but not `cache`.

_Example 3_
`docker-compose -f docker-compose.yml up -d`
Everything will run in this example.

**Describe alternatives you've considered**
https://docs.docker.com/compose/extends/#example-use-case

The above link provides an example of `extends` which is really neat, and to some extends achieves the same, but also comes with the tax of managing many files.  Having the information in one place is a lot more desirable for most engineers.

**Additional context**
Naiively, I think this could be an easy change. There is some dependency on the user "getting it right", but documentation will help here.

There will be subtleties with features such as `links` and how they are handled if flags are set. I also don't know the project well enough to say if this would be easy to integrate extends.

If this is something the team thinks is valuable, I would be happy to attempt this with some direction.
