### ISSUE TITLE
Volume not mounted

### ISSUE THREAD

**Issue by joeyhub** [docker/compose#6477]
```
version: "3"
services:
  a:
    build: docker/app
    image: app
  b:
    image: app
    entrypoint:
      - bash
      - file1.sh
    volumes:
      - /app
  c:
    restart: always
    image: app
    entrypoint:
      - bash
      - file2.sh
    volumes:
      - /app
    depends_on:
      - c
```

I'm losing my mind here because c happily mounts app and finds the entry point there but not b. Latest docker/docker-compose.
