### ISSUE TITLE
container is up-to-date reports to stderr

### ISSUE THREAD

**Issue by MartinMuzatko** [docker/compose#6482]
## Description of the issue

Hello! We are using compose to roll out our updates.

We found that when running compose, some lines are output to stderr and some to stdout, but it is hard to tell why something is an error or not. This inadvertently broke our roll-out process, because we `try/catch` the execution of compose.

I used this script here to check what is stdout and stderr: https://superuser.com/questions/453598/determine-if-output-is-stdout-or-stderr

**Steps to reproduce:**

``` bash
> $ { { BRANCH_NAME=master docker-compose -f docker/docker-compose-onBox.yml up -d; } 2>&3 | sed 's/^/STDOUT: /'; } 3>&1 1>&2 | sed 's/^/STDERR: /'
STDERR: The VERSION variable is not set. Defaulting to a blank string.
STDERR: sicon_mqtt is up-to-date
STDERR: sicon_db is up-to-date
STDERR: sicon_backend is up-to-date
STDERR: sicon_services is up-to-date
```

stopped `sicon_mqtt` to test

``` bash
> $ { { BRANCH_NAME=master docker-compose -f docker/docker-compose-onBox.yml up -d; } 2>&3 | sed 's/^/STDOUT: /'; } 3>&1 1>&2 | sed 's/^/STDERR: /'
STDERR: The VERSION variable is not set. Defaulting to a blank string.
STDERR: Starting sicon_mqtt ...
Starting sicon_mqtt ... done
sicon_backend is up-to-date
STDERR: sicon_services is up-to-date
```

Maybe here is the problem, I have no idea about python, but this looks like this ALWAYS raises an exception and thus report to stderr?

https://github.com/docker/compose/blob/8f5f7e72be829fbcaad0a29a891deaf30c572f1e/compose/service.py#L570-L574

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Output of `docker version`**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
> $ docker-compose config -f docker/docker-compose-onBox.yml
Validate and view the Compose file.

Usage: config [options]

Options:
    --resolve-image-digests  Pin image tags to digests.
    -q, --quiet              Only validate the configuration, don't print
                             anything.
    --services               Print the service names, one per line.
    --volumes                Print the volume names, one per line.

```

It says nothing else? :S

### Observed result

regular status logs get written to STDERR

### Expected result

Unless the container can't start or the compose file is malformed, there should be no stderr for succesful container status updates.

## Additional information

Windows 10 - WSL Ubuntu
Maybe related: https://github.com/docker/compose/issues/3267

**Comment by ulyssessouza** [comment]
Your line `docker-compose config -f docker/docker-compose-onBox.yml` is incorrect.
The `-f docker/docker-compose-onBox.yml` comes first, then the `config`. Could you please post the output?

**Comment by MartinMuzatko** [comment]
``` yml
WARNING: The BRANCH_NAME variable is not set. Defaulting to a blank string.
WARNING: The VERSION variable is not set. Defaulting to a blank string.
networks:
  sicon-network: {}
services:
  backend:
    container_name: sicon_backend
    depends_on:
    - db
    - mqtt
    environment:
      BRANCH_NAME: ''
      DB_HOST: sicon_db
      MQTT_HOST: sicon_mqtt
      MQTT_PORT: 1883
      SYSTEM_TYPE: onBox
      VERSION: ''
    image: 'registry.exa.sicon.io/sicon/backend:'
    networks:
      sicon-network: null
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 1194:1194/tcp
    restart: always
    volumes:
    - status:/opt/gps/sicon/services/status:rw
    - config:/opt/gps/sicon/server/config:rw
    - datapool:/opt/gps/sicon/data/datapool:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /c/Users/Martin Muzatko/dev/bitbucket/sicon/docker/backend/sicon_stick:/media/sicon_stick:rw
  db:
    container_name: sicon_db
    environment:
      MARIADB_DATABASE: sicon
      MARIADB_PASSWORD: ml+scuYD
      MARIADB_ROOT_PASSWORD: ml+scuYD
      MARIADB_USER: sisyphos
    image: 'registry.exa.sicon.io/sicon/database:'
    networks:
      sicon-network: null
    ports:
    - 3306:3306/tcp
    restart: always
    volumes:
    - datapool:/opt/gps/sicon/data/datapool:rw
  mqtt:
    container_name: sicon_mqtt
    image: toke/mosquitto
    networks:
      sicon-network: null
    ports:
    - 1883:1883/tcp
    - 9001:9001/tcp
    restart: always
  services:
    container_name: sicon_services
    depends_on:
    - backend
    image: 'registry.exa.sicon.io/sicon/services:'
    network_mode: host
    privileged: true
    restart: always
    volumes:
    - status:/opt/gps/sicon/services/status:rw
    - config:/opt/gps/sicon/server/config:rw
    - /etc/network:/etc/network:rw
    - /etc/hostname:/etc/hostname:rw
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
version: '3.0'
volumes:
  config: {}
  datapool: {}
  status: {}
```
