### ISSUE TITLE
Is there a way to extend docker-compose with entrypoints to check container status?

### ISSUE THREAD

**Issue by 2XL** [docker/compose#6499]
is ther a way to add a custom script entrypoint that can perform custom status or health checks, its run periodically to check container status, for instance `mysql is up and running`, mainly for during startup, instead of using restart:always or restart on fail...
```yaml

web:
  depends_on:
     db:
       status: running # <- boolean, 

db:
 health_check:
  - running:
        entrypoint: script_to_check_if_db_is_running.sh
        interval: 1 # seconds
  
```
