### ISSUE TITLE
Tilde paths not expanded properly when installing and using compose as container

### ISSUE THREAD

**Issue by jelovac** [docker/compose#6506]
## Description of the issue

When using docker-compose (which was installed as a container) paths specified for the Docker volumes in docker-compose.yml are not expanded properly when using Tilde character.

Instead of taking the home directory of the current user which is executing the docker-compose command the path is expanded for the user `root`.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
```

**Output of `docker version`**
```
Docker version 18.09.1, build 4c52b90
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  web-server:
    image: xxx
    volumes:
    - /root/Code/myApp:/var/www/html:rw
version: '3.0'
```

Output when running docker-compose installed using standard linux install
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

```
services:
  web-server:
    image: xxx
    volumes:
    - /home/myUsername/Code/myApp:/var/www/html:rw
version: '3.0'
```

## Steps to reproduce the issue

1. Install docker-compose using container (https://docs.docker.com/compose/install/#install-as-a-container)
2. Create docker-compose.yml which holds simple service which has a volume mounted with tilde in it's path
3. Start the composition

### Observed result

Tilde is expanded to point a path to home directory of the root user.

### Expected result

Tilde should be expanded to point to a path to home directory of the current user running docker-compose.

## Additional information

OS Kubuntu 18.04, docker-compose installed as container
Docker installed from official Docker repository for Ubuntu: 
```
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
```
