### ISSUE TITLE
Host network documentation example broken

### ISSUE THREAD

**Issue by wvxvw** [docker/compose#6507]
Example on this page: https://docs.docker.com/compose/compose-file/#network-configuration-reference doesn't work.  It produces: `networks.hostnet value Additional properties are not allowed ('name' was unexpected)`.

```
docker-compose version 1.23.2, build 1110ad0
```

This is the newest available from `pipy.org`.

**Comment by redochka** [comment]
make sure your yml file is well formatted. I had the issue when due to wrong indentation of `ports` and `networks`. which should be on the same level as `deploy`.

Copy paste the `docker-compose.yml` example works.

**Comment by omegazeng** [comment]
@wvxvw 
HOST OR NONE
Use the host’s networking stack, or no networking. Equivalent to docker run --net=host or docker run --net=none. Only used if you use docker stack commands. If you use the docker-compose command, use network_mode instead.

eg:

https://github.com/prometheus/node_exporter

```yaml
version: "3"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v0.18.1
    command: --path.rootfs=/host
    restart: always
    hostname: node-exporter
    volumes:
      - '/:/host:ro,rslave'
    pid: host
    network_mode: host
```
