### ISSUE TITLE
Implement condition or wait command to start service when other stop

### ISSUE THREAD

**Issue by kenorb** [docker/compose#6522]
**Is your feature request related to a problem? Please describe.**

Currently there is no reliable method to wait another service to exit. You can use `depends_on`, however it doesn't wait for the service to finish.
 
**Describe the solution you'd like**

The `docker` command have the following `wait` command:
```
$ docker wait --help

Usage:	docker wait CONTAINER [CONTAINER...]

Block until one or more containers stop, then print their exit codes
```
which can be used.

I believe introduction some `wait` command along with `depends_on` can solve the problem.

Another method is to implement negation to `service_healthy`, e.g.

```
service1:
    depends_on:
      service2:
        condition: !service_healthy
```
or `service_not_healthy` or `service_stopped` (as opposed to `service_started`)?

I think the better way is to extend `condition` with extra values which can make it possible.

But I've read [docs page](https://docs.docker.com/compose/compose-file/#depends_on) and it reads that "Version 3 no longer supports the condition form of `depends_on`", so I'm confused.

**Describe alternatives you've considered**

```
version: '3'
services:
  main:
    image: bash
    depends_on:
     - test01
     - test02
    command: bash -c "sleep 2 && until ! ping -qc1 test01 && ! ping -qc1 test02; do sleep 1; done &>/dev/null"
    networks:
      intra:
        ipv4_address: 172.10.0.254
  test01:
    image: bash
    hostname: test01
    command: bash -c "ip route && sleep 10"
    networks:
      intra:
        ipv4_address: 172.10.0.11
  test02:
    image: bash
    hostname: test02
    command: bash -c "ip route && sleep 20"
    networks:
      intra:
        ipv4_address: 172.10.0.12
networks:
  intra:
    driver: bridge
    ipam:
      config:
      - subnet: 172.10.0.0/24
```

**Additional context**

Related posts:
- [Docker Compose wait for container X before starting Y](https://stackoverflow.com/q/31746182/55075)
- [How to start service when not healthy?](https://stackoverflow.com/q/54660990/55075)
