### ISSUE TITLE
Concurrent docker-compose run creates duplicate networks

### ISSUE THREAD

**Issue by kutschkem** [docker/compose#6532]
## Description of the issue
Running docker-compose run concurrently creates duplicate networks.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Output of `docker version`**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     true

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```

networks:
  overlay: {}
services:
  math:
    build:
      args:
        HTTPS_PROXY: ''
        HTTP_PROXY: ''
        NO_PROXY: ''
        http_proxy: http://127.0.0.1:3128
        https_proxy: http://127.0.0.1:3128
        no_proxy: ''
      context: /home/uidq3479/Jenkins/workspace/XCitDevelopment_PR-316-QYCPM5NMJ                  543XLKNMCKWDKGLUGP5NYQDMMDGROP6UD5EBLILTF5A@2
      dockerfile: tests/eclipseProject/projects/math/build/autogen/algos/math/ma                  th/docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2k
    image: math:x86_64
    networks:
      overlay: null
  math_publisher:
    build:
      args:
        HTTPS_PROXY: ''
        HTTP_PROXY: ''
        NO_PROXY: ''
        http_proxy: http://127.0.0.1:3128
        https_proxy: http://127.0.0.1:3128
        no_proxy: ''
      context: /home/uidq3479/Jenkins/workspace/XCitDevelopment_PR-316-QYCPM5NMJ                  543XLKNMCKWDKGLUGP5NYQDMMDGROP6UD5EBLILTF5A@2
      dockerfile: tests/eclipseProject/projects/math/build/autogen/algos/math/ma                  thPublisher/docker/Dockerfile
    deploy:
      resources:
        limits:
          memory: 5k
    image: math_publisher:x86_64
    networks:
      overlay: null
  matrix1:
    build:
      args:
        HTTPS_PROXY: ''
        HTTP_PROXY: ''
        NO_PROXY: ''
        http_proxy: http://127.0.0.1:3128
        https_proxy: http://127.0.0.1:3128
        no_proxy: ''
      context: /home/uidq3479/Jenkins/workspace/XCitDevelopment_PR-316-QYCPM5NMJ                  543XLKNMCKWDKGLUGP5NYQDMMDGROP6UD5EBLILTF5A@2
      dockerfile: tests/eclipseProject/projects/math/build/autogen/algos/matrix/                  matrix1/docker/Dockerfile
    image: matrix1:x86_64
    networks:
      overlay: null
  matrix2:
    build:
      args:
        HTTPS_PROXY: ''
        HTTP_PROXY: ''
        NO_PROXY: ''
        http_proxy: http://127.0.0.1:3128
        https_proxy: http://127.0.0.1:3128
        no_proxy: ''
      context: /home/uidq3479/Jenkins/workspace/XCitDevelopment_PR-316-QYCPM5NMJ                  543XLKNMCKWDKGLUGP5NYQDMMDGROP6UD5EBLILTF5A@2
      dockerfile: tests/eclipseProject/projects/math/build/autogen/algos/matrix/                  matrix2/docker/Dockerfile
    image: matrix2:x86_64
    networks:
      overlay: null
  matrix_viz:
    build:
      args:
        HTTPS_PROXY: ''
        HTTP_PROXY: ''
        NO_PROXY: ''
        http_proxy: http://127.0.0.1:3128
        https_proxy: http://127.0.0.1:3128
        no_proxy: ''
      context: /home/uidq3479/Jenkins/workspace/XCitDevelopment_PR-316-QYCPM5NMJ                  543XLKNMCKWDKGLUGP5NYQDMMDGROP6UD5EBLILTF5A@2
      dockerfile: tests/eclipseProject/projects/math/build/autogen/algos/matrix/                  matrixViz/docker/Dockerfile
    image: matrix_viz:x86_64
    networks:
      overlay: null
version: '3.0'

```

## Steps to reproduce the issue

1. create a docker-compose.yml with a network
2. concurrently run `docker-compose run <service name>`
3. check `docker network ls` for duplicate network names

### Observed result

NETWORK ID          NAME                DRIVER              SCOPE
8d97f92b9624        bridge              bridge              local
2203251f0fff        host                host                local
77624bfff3ea        docker_overlay      bridge              local
b9b9e14e609e        docker_overlay      bridge              local
72411ace1f2d        none                null                local

### Expected result

NETWORK ID          NAME                DRIVER              SCOPE
8d97f92b9624        bridge              bridge              local
2203251f0fff        host                host                local
77624bfff3ea        docker_overlay      bridge              local
72411ace1f2d        none                null                local

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
