### ISSUE TITLE
docker-compose should warn when it will not expose any ports

### ISSUE THREAD

**Issue by trajano** [docker/compose#6534]
**Is your feature request related to a problem? Please describe.**

Related to #4799 

What I discovered was if I defined and set up a server to only connect to `internal` only networks the `ports` that I specified to expose are not exposed.

**Describe the solution you'd like**

I would like to see a warning that when the service will not be exposed because all their networks are internal.

**Describe alternatives you've considered**

Crying and swearing at docker-compose

**Additional context**

`The service '%s' will not have any ports exposed as it is only associated with networks that are internal only.`

https://stackoverflow.com/a/54830863/242042

**Comment by jcsirot** [comment]
Thank you for the report. Could you send a minimal `docker-compose.yml` example describing your use-case?

**Comment by trajano** [comment]
```
version: "3.7"
services:
  config:
    image: spring-boot-config
    ports:
      - 3100:8080
    networks:
      - ljbackend
networks:
  ljbackend:
    internal: true
    attachable: false
```
