### ISSUE TITLE
Scale attribute ignored when set to 0

### ISSUE THREAD

**Issue by kudos** [docker/compose#6545]
## Description of the issue

I want some containers scaled down completely by default and only scaled up when needed. I can't set a container to scale 0 via the `docker-compose.yml` file, but I _can_ do this by passing `--scale busybox=0` to the up command.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0-rc1, build 0f3d4dda
docker-py version: 3.7.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  busybox:
    command: sleep 10000
    image: busybox
    scale: 0
version: '2.4'

```

## Steps to reproduce the issue

1. Create a docker-compose.yml with the following contents

```
version: "2.4"

services:
  busybox:
    image: busybox
    cmd: sleep 10000
    scale: 0
```

2. Run `docker-compose up -d`

### Observed result

Docker compose creates and starts a single container.

### Expected result

Docker compose should output nothing.
