### ISSUE TITLE
docker-compose often takes a long time to do anything 

### ISSUE THREAD

**Issue by Mossop** [docker/compose#6552]
## Description of the issue

docker-compose takes a long time to run some functions that I would expect to be very fast. For example, the last time I timed running `docker-compose --help` it took three and a half minutes before outputting the help and finishing. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0-rc1, build 0f3d4dda
docker-py version: 3.7.0
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:47:20 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  web:
    driver: bridge
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      web: {}
    ports:
    - 80:80/tcp
    - 443:443/tcp
    restart: always
    volumes:
    - /srv/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    - /src/docker/nginx/hosts.d:/etc/nginx/hosts.d:ro
    - /srv/docker/nginx/certificates:/etc/nginx/certificates:ro
    - /srv/docker/nginx/logs:/var/log/nginx:rw
    - /srv/www:/srv/www:rw
version: '3.0'
```

## Steps to reproduce the issue

1. Run `time docker-compose --help`

### Observed result

See help output followed by:
```
real	3m33.025s
user	0m0.692s
sys	0m0.127s
```

### Expected result

See help output almost immediately.

### Stacktrace / full error message

No error message displayed

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Ubuntu 18.10 running on a standard digital ocean droplet. Installed using the method recommended.
