### ISSUE TITLE
Volume fs-xxxx .specifies nonexistent driver efs

### ISSUE THREAD

**Issue by loretoparisi** [docker/compose#6591]
In my docker-compose configuration I mount AWS `EFS` volumes

```yaml
volumes:
      - fs-xxxxxx:/root
```

Since few days I'm getting the error `Volume fs-xxxx .specifies nonexistent driver efs`. According to the exception 

```python
except NotFound:
            raise ConfigurationError(
                'Volume %s specifies nonexistent driver %s' % (volume.name, volume.driver)
            )
```

here https://github.com/docker/compose/blob/7ae632a9ee7530fcf81e212baa3e588f477ea862/compose/volume.py#L161

I'm getting a `Volume fs-xxxx .specifies nonexistent driver efs` error while initializing the containers.
Looking at the `initialize` code there could be different root causes of this (maybe in `volume.create()` or maybe `check_remote_volume_config`, etc.), and assumed that it is not a `ConfigurationError`, how to check which is the exact cause that raises that exception?

**Comment by jcsirot** [comment]
Hello @loretoparisi Were you able to create a minimal docker-compose.yml file triggering that behavior?

**Comment by loretoparisi** [comment]
@jcsirot more or less it is like this

```yaml
version: '2'

volumes:
  fs-xxxxx:
    driver: efs

services:
  my_container_name:
    image: my_image_id
    container_name: my_container_name
    ports:
      - "3000:3000"
    networks:
      - my_net
    volumes:
      - mydisk/mountpoint
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
    restart: always
    environment:
      - NODE_ID
    entrypoint: "start"
networks:
  my_net:
```
