### ISSUE TITLE
Restart/Reconnect containers connected via 'network_mode: service' automatically when main service is restarted

### ISSUE THREAD

**Issue by DavHau** [docker/compose#6626]
**Is your feature request related to a problem? Please describe.**
When running the following docker-compose.yml:
```
version: "3.7"

services:
  
  mother:
    image: alpine
    command: "sleep 999999"
    restart: always

  child:
    image: alpine
    command: "sleep 888888"
    network_mode: "service:mother"
```
If the mother container is restarted for any reason (crash / manual restart), the child container loses its network forever.
```
$ docker-compose restart mother
$ docker-compose exec child ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```
The child container is fully disconnected from the world. It will not reattach to mother's network. It will be unable to communicate with other containers and the internet. Does it make any sense at all to continue running the child container in this state?

**Describe the solution you'd like**
Whenever a service is restarted which has other services connected to it via 'network_mode: service', then reconnect those other services or restart them if reconnecting is technically unfeasible.

**Describe alternatives you've considered**
A workaround using a healthcheck and autoheal is described here: https://github.com/docker/compose/issues/6329#issuecomment-452874796

In discussions of other issues related to 'network_mode: service' it is suggested to use a user defined network instead. But as far as i know there are container compositions which require 'network_mode: service', for example when putting multiple containers behind a vpn. Please correct me if I'm wrong.
