### ISSUE TITLE
Failed to specify custom IPAM config for macOS Mojave: Host unreachable

### ISSUE THREAD

**Issue by iggyster** [docker/compose#6629]
## Description of the issue

I have created a docker-compose configuration for macOS Mojave. It makes a general network for services using IPAM custom config. But, the host is unreachable through address: `192.168.11.1`. I have tried different IPs (`172.16.0.1`, `10.6.0.1`) but all unavailable.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
```

**Output of `docker version`**
```
Docker version 18.09.2, build 6247962
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  general:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.11.0/24
      driver: default
services:
  nginx:
    build:
      context: /Users/iggyster/projects/ddi/premier/notifications-demo/build/dev/nginx
    depends_on:
    - php
    expose:
    - '7000'
    - '442'
    networks:
      general: null
    ports:
    - 7000:80/tcp
    - 442:443/tcp
    volumes:
    - /Users/iggyster/projects/ddi/premier/notifications-demo:/var/www/demo:cached
    - /Users/iggyster/projects/ddi/premier/notifications-demo/var/log/nginx:/var/log/nginx:rw
  node:
    environment:
      NODE_ENV: development
    expose:
    - '8080'
    image: node:8
    networks:
      general: null
    user: node
    volumes:
    - /Users/iggyster/projects/ddi/premier/notifications-demo:/var/www/demo:cached
    working_dir: /var/www/demo
  php:
    build:
      args:
        INSTALL_XDEBUG: "true"
      context: /Users/iggyster/projects/ddi/premier/notifications-demo/build/dev/php
    depends_on:
    - postgres
    - rabbit-mq
    expose:
    - 9000
    networks:
      general: null
    volumes:
    - /Users/iggyster/projects/ddi/premier/notifications-demo/build/dev/php/php.ini:/usr/local/etc/php/php.ini":rw
    - /Users/iggyster/projects/ddi/premier/notifications-demo:/var/www/demo:cached
    working_dir: /var/www/demo
  postgres:
    environment:
      PGUSER: premier-admin
      POSTGRES_DB: ws
      POSTGRES_PASSWORD: Wenh6bexNMr!LLX!vmLv
      POSTGRES_USER: premier-admin
    image: postgres:11
    networks:
      general: null
    ports:
    - 5436:5432/tcp
    volumes:
    - /Users/iggyster/projects/ddi/premier/notifications-demo:/var/www/demo:rw
    - /Users/iggyster/projects/ddi/premier/notifications-demo/.data:/var/lib/postgresql:rw
    - /Users/iggyster/projects/ddi/premier/notifications-demo/var/log/postgresql:/var/log/postgresql:rw
  rabbit-mq:
    environment:
      RABBITMQ_DEFAULT_PASS: JBq%&=m6UKEax(&k
      RABBITMQ_DEFAULT_USER: premier-admin
      RABBIT_HOST: 127.0.0.1
      RABBIT_PASSWORD: JBq%&=m6UKEax(&k
      RABBIT_PORT: '5673'
      RABBIT_USER: premier-admin
    expose:
    - '5673'
    image: rabbitmq:3.8-rc
    networks:
      general: null
    ports:
    - 15673:15672/tcp
    - 5673:5673/tcp
version: '3.0'
```

### Nginx Dockerfile & configs

**Dockerfile**

```
FROM nginx:1.15

RUN apt-get update -yqq && apt-get install -yqq nginx

ADD nginx.conf /etc/nginx/
ADD server.conf /etc/nginx/conf.d/

RUN echo "upstream php-upstream { server php:9000; }" > /etc/nginx/conf.d/upstream.conf \
    && rm /etc/nginx/conf.d/default.conf

RUN usermod -u 1000 www-data

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80 443
```

**nginx.conf**
```
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
  worker_connections  2048;
  multi_accept on;
  use epoll;
}

http {
  server_tokens off;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 15;
  types_hash_max_size 2048;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log off;
  error_log off;
  gzip on;
  gzip_disable "msie6";
  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
  open_file_cache max=100;
}

daemon off;
```
**server.conf**
```
server {
    server_name 127.0.0.1 demo.lm;
    root /var/www/demo/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
```

### PHP Dockerfile

**Dockerfile**
```
FROM php:7.2-fpm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        apt-utils \
        libzip-dev zip unzip && \
        docker-php-ext-configure zip --with-libzip && \
        # Install the zip extension
        docker-php-ext-install zip && \
        php -m | grep -q 'zip' \
    && rm -rf /var/lib/apt/lists/*

RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer

# Install PDO PGSQL for PHP
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && docker-php-ext-install -j$(nproc) pdo pdo_pgsql pgsql

# Install & configure PHP extensions
RUN docker-php-ext-configure gd \
     --with-jpeg-dir=/usr/lib \
     --with-freetype-dir=/usr/include/freetype2 && \
     docker-php-ext-install gd && docker-php-ext-install pcntl

ADD demo.ini /etc/php7/php-fpm.d/
ADD demo.ini /etc/php7/cli/conf.d/

ARG INSTALL_XDEBUG=false

# Install the xdebug extension
RUN if [ ${INSTALL_XDEBUG} = true ]; then \
  pecl install xdebug-2.7.0 \
  && docker-php-ext-enable xdebug \
;fi

# Copy xdebug configuration for remote debugging
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN sed -i "s/xdebug.remote_autostart=0/xdebug.remote_autostart=1/" /usr/local/etc/php/conf.d/xdebug.ini && \
    sed -i "s/xdebug.remote_enable=0/xdebug.remote_enable=1/" /usr/local/etc/php/conf.d/xdebug.ini && \
    sed -i "s/xdebug.cli_color=0/xdebug.cli_color=1/" /usr/local/etc/php/conf.d/xdebug.ini

COPY ./demo.ini /usr/local/etc/php/conf.d

# Create an alias for Symfony console
RUN echo 'alias sf="bin/console"' >> ~/.bashrc
```

## Steps to reproduce the issue

1. Run `docker-compose up -d`
2. Try to connect via any client to `192.168.11.1:7000`

### Observed result

The host `192.168.11.1` via port `7000` is unreachable. The same `docker-compose` was tested on another machine and it works, here is another machine configs:
```
OS: Ubuntu v.16.04
docker-compose version 1.19.0, build 9e633ef
Docker version 17.05.0-ce, build 89658be
```

### Expected result

The host `192.168.11.1` should be reachable via port `7000`

### Stacktrace / full error message

No error messages.

## Additional information

OS: `macOS Mojave v.10.14.3`
`docker-compose` installed with Docker Desktop for Mac according to the official installation [documentation](https://docs.docker.com/compose/install/#install-compose-on-macos)
