### ISSUE TITLE
The "docker-compose up -d" fails on Windows 10 with PermissionError

### ISSUE THREAD

**Issue by jni-heyloyalty** [docker/compose#6688]
## Description of the issue
Docker container fails to start up on Windows 10 due to the error  
PermissionError: [WinError 5] Access is denied
[14316] Failed to execute script docker-compose

Permissions has been checked and double checked on the folder.
Windows containers are used.

However, I have also tried Linux containers and shared C drive respectively 
from Settings in Docker for Windows and even resetting and re-apply 
the shared drives.

I am logged in with an Azure AD account which has administrative privileges
to the computer, but I did also try in the context of local admin with the same
result.

I did also try to install it on a virtual drive, but still with the same result.

## Context information (for bug reports)
PermissionError, Windows 10, docker-compose up -d

**Output of `docker-compose version`**
```
PS C:\src\project> docker-compose --version
docker-compose version 1.24.0, build 0aa59064
```

**Output of `docker version`**
```
PS C:\src\project> docker --version
Docker version 19.03.0-beta3, build c55e026
```

**Output of `docker info`**
```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0-beta1)
  buildx: Build with BuildKit (Docker Inc., v0.2.0-tp)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.0-beta3
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows 10 Pro Version 1809 (OS Build 17763.437)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.61GiB
 Name: DESKTOP-AE2BUF4
 ID: 7c1f308f-69c5-4bc9-9ee2-c385bb235f9d
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 31
  System Time: 2019-05-06T17:51:23.101966+02:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Output of `docker-compose config`**
```
PS C:\src\project> docker-compose config
services:
  api:
    build:
      context: C:\src\project
      dockerfile: app.docker
    depends_on:
      beanstalk:
        condition: service_started
      database:
        condition: service_started
    environment:
      BEANSTALK_HOST: beanstalk
      BEANSTALK_PORT: '11300'
      DB_HOST: database
      DB_PORT: '3306'
    links:
    - database
    - elasticsearch
    - beanstalk
    volumes:
    - C:\src\project:/var/www:rw
    working_dir: /var/www/api
  api_web:
    build:
      context: C:\src\project
      dockerfile: api.docker
    depends_on:
      api:
        condition: service_started
    ports:
    - 8084:80/tcp
    volumes_from:
    - service:api:rw
    working_dir: /var/www
  beanstalk:
    image: c4tech/beanstalkd
    ports:
    - 11302:11300/tcp
  client:
    build:
      context: C:\src\project
      dockerfile: client.docker
    volumes:
    - C:\src\project:/var/www:rw
    working_dir: /var/www/client
  client_web:
    build:
      context: C:\src\project
      dockerfile: web.docker
    depends_on:
      client:
        condition: service_started
    ports:
    - 8088:80/tcp
    volumes_from:
    - service:client:rw
    working_dir: /var/www
  database:
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    image: mysql:5.7
    ports:
    - 33062:3306/tcp
    volumes:
    - /var/lib/mysql
  elasticsearch:
    image: elasticsearch:1.7.3
    mem_limit: 4000000000
    ports:
    - 9404:9200/tcp
    volumes:
    - /usr/share/elasticsearch/data
    - C:\src\project\elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
  redis:
    image: redis:5.0.4
    ports:
    - 7113:6379/tcp
version: '2.1'
volumes:
  data: {}
```

## Steps to reproduce the issue
1. Starting PowerShell as Administrator
2. Executing the command "docker-compose up -d"

### Observed result
```
PS C:\src\project> docker-compose up -d
Building client
[14316] Failed to execute script docker-compose
```

### Expected result
```
Exptected to start up without errors as it does on Ubuntu
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 360, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-packages\docker\api\build.py", line 159, in build
  File "site-packages\docker\utils\build.py", line 30, in tar
  File "site-packages\docker\utils\build.py", line 49, in exclude_paths
  File "site-packages\docker\utils\build.py", line 214, in rec_walk
  File "site-packages\docker\utils\build.py", line 184, in rec_walk
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\src\\project\\System Volume Information'
```

Please note that the path "C:\src\project" exists but "C:\src\project\System Volume Information" does not. The path "\\\\?\\C:\\src\\project\\System Volume Information" is generated by docker-compose.

## Additional information
- Windows 10
- Docker Desktop for Windows 
https://docs.docker.com/docker-for-windows/install/

**Output of `docker inspect`**
```
PS C:\src\project> docker inspect project_data
[
    {
        "CreatedAt": "2019-05-06T16:09:39+02:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "project",
            "com.docker.compose.version": "1.24.0",
            "com.docker.compose.volume": "data"
        },
        "Mountpoint": "C:\\ProgramData\\Docker\\volumes\\project_data\\_data",
        "Name": "project_data",
        "Options": null,
        "Scope": "local"
    }
]
```

**Output of sharing** 

Be aware that the container cannot be started prior to these steps, 
which is the core of this issue that "docker-compose up" fails.

1. Starting PowerShell as Administrator
2. Command  _docker run --rm -v c:/src/project:/var/www ls /var/www_
3. A prompt asking me to share it
4. Entering credentials for user with administrative privileges to the computer, which also is an Azure AD account

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: 
Error response from daemon: Drive sharing failed for an unknown reason.
```

I have even followed the steps described at the link below but _docker-compose up_ does still fail with a PermissionError, but shared drives work.

https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/

I did also try to uninstall docker and install it when logged in as the local administrator, but _docker-compose up_ does still fail with a PermissionError while shared drives work.

This has also been tried [Tip/Fix: Mounting volumes on Windows 10 with Docker-Compose](https://www.reddit.com/r/docker/comments/arcsnz/tipfix_mounting_volumes_on_windows_10_with/)
