### ISSUE TITLE
Static check for duplicate port request in compose file

### ISSUE THREAD

**Issue by isaacdorfman** [docker/compose#6708]
When a pod specification requests the same port twice(for example because of a change in a .env file), the "docker-compose run <service-name>" command responds with "Bind for 0.0.0.0:<Port> failed: port is already allocated" instead of responding that the problem is in the compose file.

**Comment by ulyssessouza** [comment]
Hello @isaacdorfman Thank you for the report!

Looking at the issue I have the impression that you've swapped `docker-compose up` with `docker-compose run` is that the case?
Could you please answer the questions contained in our [github bug template](https://github.com/docker/compose/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so that we fully understand the problem?

**Comment by zelahi** [comment]
So I wasn't able to reproduce this using `docker-run`.  The files I used for testing are here: https://github.com/zelahi/tools/blob/master/testing/compose-test/docker-compose.yml and these are the following scenarios I tested: 

**Scenario 1: Compose file has the same port mentioned twice:**

**Compose file:** 
```
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web_2:
    build: .
    ports:
      - "5000:5000"
```

**Command ran:** 
`docker-compose run web`

**Output:** 
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.ports value ['5000:5000', '5000:5000'] has non-unique elements
```

**Scenario 2: Initially brought up web and redis then executed a `docker-compose run` on web_2:**

**Compose file:** 
```
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web_2:
    build: .
    ports:
      - "5000:5000"
```

**Command ran:** 
```docker-compose up web redis
     docker-compose run web_2
```


**Output:** 
`No error`, Everything ran without an issue

**Scenario 3: Ran only docker-compose up:**

**Compose file:** 
```
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web_2:
    build: .
    ports:
      - "5000:5000"
```

**Command ran:** 
```docker-compose up```


**Output:** 
```
ERROR: for web_2  Cannot start service web_2: driver failed programming external connectivity on endpoint compose-test_web_2_1 (46484da229527c513cdd1ab62d1de64dc00dfe37195d826ea8113015f56e54fe): Bind for 0.0.0.0:5000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

**Scenario 4: Initially ran docker-compose up for web_1 and redis, then web_2**

**Compose file:** 
```
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  web_2:
    build: .
    ports:
      - "5000:5000"
```

**Command ran:** 
```docker-compose up web_1 redis
      docker-compose up web_2```

**Output:**
```
ERROR: for web_2  Cannot start service web_2: driver failed programming external connectivity on endpoint compose-test_web_2_1 (46484da229527c513cdd1ab62d1de64dc00dfe37195d826ea8113015f56e54fe): Bind for 0.0.0.0:5000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

So I saw this error with `docker-compose up`, however I'm not sure how to reproduce it when executing a `docker run`?
