### ISSUE TITLE
A "graceful" service start even if the logging driver service/container is not running

### ISSUE THREAD

**Issue by BentCoder** [docker/compose#6764]
Hi,

When I try to start "application" containers I get errors below. The reason is because the `monitoring_fluent_bit` container is not running yet. However, it would be nice if there was an "graceful" start option under `logging.options` so if the `monitoring_fluent_bit` container is not running/available yet, the application services should still run. Does that make sense?

Thanks

> ERROR: for app_php_1  Cannot start service app_php: failed to initialize logging driver: dial tcp 127.0.0.1:24224: connect: connection refused

> ERROR: for app_php  Cannot start service app_php: failed to initialize logging driver: dial tcp 127.0.0.1:24224: connect: connection refused
ERROR: Encountered errors while bringing up the project.

**application compose**
```yaml
version: "3.4"

services:
  app_php:
    ...
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "monitoring_fluent_bit"
        mode: "non-blocking"
        max-buffer-size: "2m"
  app_nginx:
    ...
  app_mysql:
    ...
```

**monitoring compose**
```yaml
version: "3.4"

services:
  monitoring_fluent_bit:
    image: "fluent/fluent-bit:1.0.4"
    ...
  monitoring_es:
    ...
  monitoring_kibana:
    ...
```

**Comment by chris-crone** [comment]
Hi @BentCoder,

Thanks for the suggestion. You may be able to use [`depends_on`](https://docs.docker.com/compose/compose-file/#depends_on) to work around this. Errors like that are unfortunately something that you'll encounter when working on eventually consistent systems.

**Comment by BentCoder** [comment]
I should have explained it better:disappointed:

If the logging driver is not available yet, the service should still be able to start. The reason is because, for instance, my logging drivers are **external**  services. Is there a solution to this?

**Comment by BentCoder** [comment]
I've just noticed that [I am not the only one](https://programmaticponderings.com/tag/gelf/) who picked up on it.

> Using Docker’s Fluentd logging driver, if the Fluentd container is not available on the container’s host, the container logging to Fluentd will fail (major con!)

So technically if the logging driver related service (internal or external) is not running for whatever reason, the dependent service/container should still be able to run.

As a simple solution, there can be a kind of fallback option if the logging driver related service is not running. e.g. If service X (php, nginx ...) depends on service Y (fluent, logstash ...) and if the service Y is not running then service X still starts while logging into std.

I am sure this is relatively easy solution just like non existent env variables are handled with empty values.

**Comment by bhaweshintouch** [comment]
+1 --  getting error:
docker: Error response from daemon: failed to initialize logging driver: dial tcp 150.30.1.40:24224: connect: connection refused.

it is not starting a new container when logging drive container is down.

Please help-- implement the solution as mentioned by BentCoder

**Comment by BentCoder** [comment]
Ping. Anyone interested in this issue please?

**Comment by nitper** [comment]
I believe you're looking for the [`fluentd-async-connect`](https://docs.docker.com/config/containers/logging/fluentd/#fluentd-async-connect) log option.

**Comment by BentCoder** [comment]
@nitper That solves the problem. Thank you for pointing out.

**Comment by Blobonat** [comment]
Just an update: It's now called `fluentd-async`

**Comment by pooya-mohammadi** [comment]
@Blobonat @bentcoder 
Would you mind sharing your daemon.json and your docker-compose.yml?

**Comment by Blobonat** [comment]
@pooya-mohammadi 

`daemon.json`:
```
{
  "metrics-addr" : "127.0.0.1:9323",
  "experimental" : true
}
```

`docker-compose.yml`:
```
logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:${FLUENTD_PORT}
        tag: myTag
        fluentd-async: 'true'
```
