### ISSUE TITLE
Extension fields support only one format of declaring environment variables

### ISSUE THREAD

**Issue by mcctomsk** [docker/compose#6767]
## Description of the issue
We have two formats to pass environment into container:
https://docs.docker.com/compose/compose-file/#environment

If use  `RACK_ENV: development` format and **Extension fields** in docker-compose.yml file `docker-compose up` command works, if use `- RACK_ENV=development` format and **Extension fields** in the same file the command doesn't work

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.21.2, build a133471
```

**Output of `docker version`**
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

## Steps to reproduce the issue

1. Put next `docker-compose.yml` file in `test` folder
```
version: '3.4'

x-environment: &environment
  - WEB_GLOBAL=global

x-defaults: &defaults
  restart: unless-stopped
  image: nginx:latest
  environment:
    <<: *environment
    - WEB_DEFAULTS=default

services:
  web1:
    <<: *defaults
    environment:
      <<: *environment
      - WEB_LOCAL=local
  web2:
    <<: *defaults
```
2. `docker-compose up -d `

### Observed result
```
$ docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 10, column 5
expected <block end>, but found '-'
  in "./docker-compose.yml", line 11, column 5
```
### Expected result
```
$ docker inspect test_web1_1 | grep WEB
                "WEB_GLOBAL=global",
                "WEB_LOCAL=local",
$ docker inspect test_web2_1 | grep WEB
                "WEB_GLOBAL=global",
                "WEB_DEFAULTS=default",
```
the same result as, if `docker-compose.yml` file would be next:
```
version: '3.4'

x-environment: &environment
  WEB_GLOBAL: global

x-defaults: &defaults
  restart: unless-stopped
  image: nginx:latest
  environment:
    <<: *environment
    WEB_DEFAULTS: default

services:
  web1:
    <<: *defaults
    environment:
      <<: *environment
      WEB_LOCAL: local
  web2:
    <<: *defaults
```

## Additional information
OS version:
Ubuntu 16.04.6 LTS (Xenial Xerus)

**Comment by chris-crone** [comment]
Hi @mcctomsk,

Thanks for the report. I see that you're using an older version of Compose, could you please try with the latest stable (1.24.1)?

**Comment by mcctomsk** [comment]
Version of docker-compose was updated:
```
$ docker-compose --version
docker-compose version 1.24.1, build 4667896b
````
error was changed to:
```
$ docker-compose up -d
ERROR: yaml.constructor.ConstructorError: while constructing a mapping
  in "./docker-compose.yml", line 10, column 5
expected a mapping for merging, but found scalar
  in "./docker-compose.yml", line 4, column 5
```
And I've changed yaml file to
```
version: '3.4'

x-environment:
  &environment
  - WEB_GLOBAL=global

x-defaults: &defaults
  restart: unless-stopped
  image: nginx:latest
  environment:
    <<: *environment
    - WEB_DEFAULTS=default

services:
  web1:
    <<: *defaults
    environment:
      <<: *environment
      - WEB_LOCAL=local
  web2:
    <<: *defaults
```
and got the same error, as in the first message:
```
$ docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 11, column 5
expected <block end>, but found '-'
  in "./docker-compose.yml", line 12, column 5
```
