### ISSUE TITLE
Secrets won't override

### ISSUE THREAD

**Issue by 733amir** [docker/compose#6771]
## Description of the issue

I have multiple compose files for multiple services and two environments, production and development. There are multiple secrets that each one has a `name` so I can update the version of the secret. When I use the override feature, it won't show `name` of the secret in the resulting config.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
secrets:
  test:
    file: /path/to/secrets/file
services: {}
version: '3.7'
```

## Steps to reproduce the issue

1. Create a file with the following content and name it `docker-compose.yml`:
```
version: '3.7'

secrets:
  test:
    name: test-v1
```
2. Create a file with the following content alongside `docker-compose.yml` and name it `docker-compose.override.yml`:
```
version: '3.7'

secrets:
  test:
    file: secrets/file
```
3. Run `docker-compose config`

### Observed result
```
secrets:
  test:
    file: /path/to/secrets/file
services: {}
version: '3.7'
```
### Expected result
```
secrets:
  test:
    file: /path/to/secrets/file
    name: test-v1
services: {}
version: '3.7'
```
