### ISSUE TITLE
labels ignore environment variables

### ISSUE THREAD

**Issue by jpic** [docker/compose#6833]
Given:

```
services:
  foo:
    environment:
    - BAR=test
    labels:
    - foo=${BAR}
```

Will results in:

```
WARNING: The BAR variable is not set. Defaulting to a blank string.
```

Instead of expected: label foo=test, no warning
