### ISSUE TITLE
docker-compose SSL certificate problem: self signed certificate when building from git repo

### ISSUE THREAD

**Issue by DemianTinkiel** [docker/compose#6841]
when using a gitlab HTTPS url for build in a compose file I get  SSL certificate problem: self signed certificate

```
version: '3'
services:
 foo:
    build: https://${GIT_USER}:${GIT_TOKEN}@gitlab.company_url.com/group/foo.git
    ports:
      - 8081:8081
```

If I do `git clone` with the same URL I'll get the same message unless I set the verify ssl to false, i.e. `git config --global http.sslVerify false`

However even with the same config set and the cert path set too `git config --global http.sslCAPath /home/user/Documents/ca_certs/`, in  compose, I still get the same problem.

Does compose not take the config from GIT?

  ```bash
demianT:~$ docker --version
Docker version 19.03.1, build 74b1e89
demianT:~$ docker-compose --version
docker-compose version 1.22.0, build f46880f
```
Fedora 30 5.1.19-300.fc30.x86_64
