### ISSUE TITLE
How to execute the script before the image CMD is executed

### ISSUE THREAD

**Issue by relax-admin** [docker/compose#6869]
## Known

Dockerfile
```Dockerfile
FROM golang AS builder

WORKDIR /go/src/ping-mysql
COPY . .
RUN mkdir -p /wait-for && curl -L "https://raw.githubusercontent.com/eficode/wait-for/master/wait-for" -o /wait-for/wait-for.sh
# disable cgo
ENV CGO_ENABLED=0
# build steps
RUN echo ">>> 1: go version" && go version
#RUN echo ">>> 2: go get" && go get -v -d
RUN echo ">>> 3: go install" && go install

FROM alpine
WORKDIR /go/bin/
COPY --from=builder /go/bin/ping-mysql ./ping-mysql
COPY --from=builder /wait-for/wait-for.sh ./wait-for.sh
RUN chmod +x ./wait-for.sh
EXPOSE 8080
CMD ["./ping-mysql"]

```
docker-compose.yml
```yml
version: "3"
services:
 mysql-server:
   container_name: test-mysql
   environment:
   - MYSQL_ROOT_PASSWORD=1234
   image: mysql:5.7.22
   ports:
   - 3306
   volumes:
   - ./database/mysql/:/docker-entrypoint-initdb.d
 ping-mysql-server:
   container_name: test-ping-mysql
   command: sh -c 'echo "wait mysql..." && /go/bin/wait-for.sh test-mysql:3306 -t 36000  -- ./ping-mysql'
   depends_on:
   - mysql-server
   environment:
   - MYSQL_HOST=test-mysql
   - PORT=3306
   - USER_NAME=root
   - PASSWORD=1234
   image: xiaoxinmiao/ping-mysql
   volumes: 
   - ./wait-for.sh:/go/bin/wait-for.sh
   ports:
   - 8080
```

The above code is executable

## Actual
Docker-compose's command directly **covers CMD**
` command: sh -c 'echo "wait mysql..." && /go/bin/wait-for.sh test-mysql:3306 -t 36000  -- ./ping-mysql'`

## Expect
Docker-compose command does **not cover CMD**
`command: sh -c 'echo "wait mysql..." && /go/bin/wait-for.sh test-mysql:3306 -t 36000  --'`

After executing the code below
```bash
Sh -c 'echo "wait mysql..." && /go/bin/wait-for.sh test-mysql:3306 -t 36000 --'
```
Continue to execute CMD in imaged ["./ping-mysql"]
