### ISSUE TITLE
[bug] `config --no-interpolate` returns wrong results

### ISSUE THREAD

**Issue by apollo13** [docker/compose#6871]
## Description of the issue

docker-compose 1.25 introduces a `--no-interpolate` command to the `config` subcommand. I would expect that `docker-compose config` and `docker-compose config --no-interpolate > new_compose.yml && docker-compose -f new_compose.yml config` return the same output. Sadly they dont.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0-rc2, build 661ac20e
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:20:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

Assume the following compose file:

```
version: "2.4"

services:
  whoami:
    image: ubuntu
    command: sleep infinity
    env_file: data.env
    environment:
      IN_COMPOSE: ${IN_COMPOSE}
```
and the `data.env`:
```
IN_ENV_FILE=$THIS_SHOULDNT_BE_A_VAR
```
Now `docker-compose config` correctly returns:
```
WARNING: The IN_COMPOSE variable is not set. Defaulting to a blank string.
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: ''
      IN_ENV_FILE: $$THIS_SHOULDNT_BE_A_VAR
    image: ubuntu
version: '2.4'
```
As you can see `$THIS_SHOULDNT_BE_A_VAR` is escaped correctly.
Now if you run the following sequence:
```
docker-compose config --no-interpolate > new_compose.yml
docker-compose -f new_compose.yml config
```
you will get:
```
WARNING: The IN_COMPOSE variable is not set. Defaulting to a blank string.
WARNING: The THIS_SHOULDNT_BE_A_VAR variable is not set. Defaulting to a blank string.
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: ''
      IN_ENV_FILE: ''
    image: ubuntu
version: '2.4'
```
Now all of a sudden, `$THIS_SHOULDNT_BE_A_VAR` got evaluated. The cause can be seen when viewing the intermediate file:
```
services:
  whoami:
    command: sleep infinity
    environment:
      IN_COMPOSE: ${IN_COMPOSE}
      IN_ENV_FILE: $THIS_SHOULDNT_BE_A_VAR
    image: ubuntu
version: '2.4'
```
I think `docker-compose config --no-interpolate` should replace `$` with `$$` for environment variables coming from env files.
