### ISSUE TITLE
Double expansion of vars in .env file not working

### ISSUE THREAD

**Issue by laertis** [docker/compose#6877]
Given the following simple setup

`$ tree -a`
```
.
├── .env
└── docker-compose.yml
```

`cat .env`
```
var1=A
var1prime=${var1}
```

`cat docker-compose.yml`
```
version: '3'
services:
    service1:
        image: alpine
        environment:
            - "var1=${var1}"
            - "var1prime=${var1prime}"
```

I am given the following config

`docker-compose config`
```
services:
  service1:
    environment:
      var1: A
      var1prime: $${var1}
    image: alpine
version: '3.0'
```

while I would expect `var1prime` to also have been substituted like following:
```
services:
  service1:
    environment:
      var1: A
      var1prime: A
    image: alpine
version: '3.0'
```

I know that `.env` files do not support quotes (which I've tried for expansion) but nothing is said regarding usage of other vars previous declared in the file.
The following works in unix shell:
`source .env && echo $var1prime`
```
A
```

---

My setup is Ubuntu through Windows WSL
`uname -a`
```
Linux athwlp0182 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

`docker-compose version`
```
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 2.7.15+
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
