### ISSUE TITLE
Inconsistency when using "host.docker.internal" in Linux vs macOS

### ISSUE THREAD

**Issue by pabloegpf1** [docker/compose#6880]
## Context information (for bug reports)
I am using Docker-Compose to create a postgres database and a node application. I want to pass the db host as an env variable to the web service. If I use "host.docker.internal" in macOS, the connection is established correctly. However, when running on Linux, I need to use 
```network-mode: "host" ``` 
and pass "localhost" instead.
This is a problem for me since I develop on macOS and deploy on linux servers.

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false```
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

```
version: '3'
services:
  
  web:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
    #network_mode: "host" #Comment this line if using a if using a Windows/macOS host host
    environment:
      DB_HOST: host.docker.internal # IMPORTANT: Change this to "host.docker.internal" if using a Windows/macOS host
      DB_PW: ${DB_PW}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT:-5432}
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "${DB_PORT}:5432"
```

## Steps to reproduce the issue

1. Create 2 services (postgres:alpine and node).
2. Pass "host.docker.internal" to the node app as an env variable.

### Observed result
If host is linux, "host.docker.internal" will be undefined.

### Expected result
If host is linux, "host.docker.internal" should be the host's ip address.
