### ISSUE TITLE
Is it possible to use toml as config file format instead of json or yml?

### ISSUE THREAD

**Issue by menghuu** [docker/compose#6920]
replace `docker-compose.yml`
```yml
version: '3.7'
services:
  rc_server:
    image: rc:847a181
    container_name: rc_service
    ports:
      - '7890:7890'
    volumes:
      - ./docker/rc:/rc/docker/rc
      - ./logs/rc/:/rc/logs/rc
    network_mode: host
```
with `docker-compose.toml`
```toml
version = "3.7"

[services]

  [services.rc_server]
  image = "rc:847a181"
  container_name = "rc_service"
  ports = [
    "7890:7890"
  ]
  volumes = [
    "./docker/rc:/rc/docker/rc",
    "./logs/rc/:/rc/logs/rc"
  ]
  network_mode = "host"
```

it is hard to read and write when the `docker-compose.yml` is very long

here is toml spec:[toml](https://github.com/toml-lang/toml)

some tools can convert `toml` to `yml`, like:  [yj](https://github.com/sclevine/yj) or [remarshal](https://github.com/dbohdan/remarshal), but they are not official support.
