### ISSUE TITLE
Allow using different names for each network

### ISSUE THREAD

**Issue by guludo** [docker/compose#6922]
Hi, all!

**Is your feature request related to a problem? Please describe.**
Here at work we are working on two separate projects, say project `A` and `B`. Each project is developed in a separate source repository and each contain a `docker-compose.yml` that can be used to start services in _development mode_. One of the services defined in `A`'s `docker-compose.yml` is consumed by another service in `B`.

Let's say `A`'s services are:
- `worker`
- `redis`
- `frontend`

And `B`'s are:
- `db`
- `web`

I'd like have `web` and `frontend` communicating but keep the other services of A isolated from the other services from B. Additionally, the frontend service provided by `A` is expected to have a more specific name from `B`'s perspective, say `foo-service`.

**Describe alternatives you've considered**
One way of solving this is creating a network:

```bash
docker network create my-net
```

And then adding the desired services and aliases to the network:

- `A`'s `docker-compose.override.yml`:
  ```yaml
  version: "3.7"
  services:
    frontend:
      networks:
        default: # Still use default network so that it can communicate with internal services
        my-net:
          aliases:
          - "foo-service"
  networks:
      my-net:
          external: true
  ```

- `B`'s `docker-compose.override.yml`:
  ```yaml
  version: "3.7"
  services:
    web:
      networks:
        default: # Still use default network so that it can communicate with internal services
        my-net:
  networks:
      my-net:
          external: true
  ```

With this setup, I can accomplish my goals: `web` can refer to `A`'s `frontend` by `foo-service` and successfully communicate with ti, while the other services are kept on their own network.

However, **there is something that bothers** me w.r.t. this solution: `foo-service` can still be reached by `web` via the name `frontend` and this would be problematic if `B` also had an internal service called `frontend`.

Note that I'm using `docker-compose.override.yml` because I do not want to mess with the original file.

**Describe the solution you'd like**
It would be nice to tell `docker-compose` to use a replacement name (instead of an alias) for a service in a given network. That new feature could come as new a configuration key,  `name` for example. With that, `A`'s `docker-compose.override.yml` would look like the following:

  ```yaml
  version: "3.7"
  services:
    frontend:
      networks:
        default: # Still use default network so that it can communicate with internal services
        my-net:
          name: "foo-service"
  networks:
      my-net:
          external: true
  ```
This would have the same effect as for the previous solution, but with the additional benefit of `A`'s `frontend` being only reachable by `B`'s `web` via the name `foo-service`.
