### ISSUE TITLE
compose breaks network on arm only

### ISSUE THREAD

**Issue by qdel** [docker/compose#6935]
## Description of the issue

When docker-compose up create a network, docker cannot create other networks.

## Context information (for bug reports)

Output of "docker-compose version"
```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

Output of "docker version"
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:44:44 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:38:46 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Output of "docker-compose config"
```
networks:
  super: {}
services:
  grafana:
    deploy:
      restart_policy:
        condition: on-failure
    image: grafana/grafana
    networks:
      super: null
    ports:
    - 127.0.0.1:3000:3000/tcp
    restart: unless-stopped
    volumes:
    - grafana:/var/lib/grafana:rw
  influxdb:
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      INFLUXDB_UDP_DATABASE: '"udp"'
      INFLUXDB_UDP_ENABLED: "true"
    image: influxdb
    networks:
      super: null
    ports:
    - 10.89.0.1:8086:8086/tcp
    - 10.89.0.1:8089:8089/udp
    restart: unless-stopped
    volumes:
    - influxdb:/var/lib/influxdb:rw
version: '3.0'
volumes:
  grafana: {}
  influxdb: {}
```

## Steps to reproduce the issue

1. Run docker-compose up
2. run docker network create abc (or docker-compose up another service)
3.  Error response from daemon: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-0a9b0aa29512 -j DOCKER: iptables v1.8.3 (nf_tables):  RULE_INSERT failed (Invalid argument): rule in chain FORWARD
 (exit status 4)

### Observed result

docker-compose seems to break iptables (nftables) config for further docker-compose / docker network commands.

Runned service works correctly.

Without using compose, it is possible to create multiple networks using docker network create without any problem.

### Expected result

Be able to have multiple services / manually created networks.

### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Tried with docker-compose / docker.io from debian and docker-ce from docker repository.

Scaleway C1 instance (arm)
debian 10, nftables, ufw.

Note that the bug does not reproduce on debian 10, nftables, ufw but amd64 laptop.

Note that docker let quite a lot of dirty config in this case:
- br-XXX interface still exists
- br-XXX iptables config still exists
