### ISSUE TITLE
unable to access web application from localhost:8080 running in a replica?

### ISSUE THREAD

**Issue by Cariaga** [docker/compose#6954]
i run it with 
`docker-compose --compatibility up -d`

my yml file
```
version: "3.7"
services:
  web:
    build: .
    command: npm start
    
    networks:
      - someApp
    volumes:
      - .:/usr/src/app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: '50M'
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
    driver: overlay
```
my server app.js

```
var server = app.listen(8080, function () {
  var host = server.address().address
  var port = server.address().port
  
  console.log("Example app listening at http://%s:%s", host, port)
})
```
