### ISSUE TITLE
docker-compose super slow on macOS Catalina

### ISSUE THREAD

**Issue by benlumia007** [docker/compose#6956]
when i do docker-compose up -d, it takes a while to start the process, same when i do docker-compose restart. 

in other words, there's a delay of few seconds before it begins to restart containers or stopping containers.

**Comment by glours** [comment]
Hello @benlumia007 
Can you give more details, for example the output for `docker-compose --log-level debug up -d` or `docker-compose --log-level debug restart -d`

**Comment by benlumia007** [comment]
is not about the output of docker-compose, is when i type the following

docker-compose up -d and press enter, it just delays for 5 - 10 seconds before it shows restarting or stopping

**Comment by benlumia007** [comment]
let me do some testing, i'll comment later , it just could be my eyes are deceiving me lol

**Comment by ndeloof** [comment]
Are you using https://github.com/docker/compose/blob/master/contrib/completion/bash/docker-compose for command line completion ?

**Comment by skazancev** [comment]
same problem, macos catalina (10.15 19A583), docker 2.1.0.3 (38240), docker-compose 1.24.1

**Comment by benlumia007** [comment]
so this is what it supposed to do, when you `docker-compose up -d` or `docker-compose restart`
![normal](https://user-images.githubusercontent.com/11844123/66660104-72fbcf00-ebf9-11e9-8173-0f6373518a73.gif)

but for macOS Catalina there is a delay between 
```
benlumia007@aatrox:~/WordPress$ docker-compose restart
````
delays 5 seconds, then 
```
Restarting docker-nginx   ... done
Restarting docker-phpfpm  ... done
Restarting docker-mysql   ... done
Restarting docker-mailhog ... done
benlumia007@aatrox:~/WordPress$ 
````

**Comment by glours** [comment]
Can you post the config of your compose file (without any sensitive data of course)
`docker-compose config`
Just to try to reproduce with the same kind of application (number of containers, eventually network config ...)

**Comment by benlumia007** [comment]
```
benlumia007@aatrox:~/WordPress$ docker-compose config
services:
  mailhog:
    container_name: docker-mailhog
    image: benlumia007/mailhog
    ports:
    - published: 1025
      target: 1025
    - published: 8025
      target: 8025
    restart: always
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: benlumia007/mysql:latest
    ports:
    - published: 3306
      target: 3306
    restart: always
    volumes:
    - db_data:/var/lib/mysql:rw
  nginx:
    container_name: docker-nginx
    depends_on:
    - phpfpm
    image: benlumia007/nginx:latest
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: always
    volumes:
    - /home/benlumia007/WordPress/config/nginx:/etc/nginx/conf.d:rw
    - /home/benlumia007/WordPress/certificates:/etc/nginx/certs:rw
    - /home/benlumia007/WordPress/sites:/var/www/html:rw
  phpfpm:
    container_name: docker-phpfpm
    image: benlumia007/php:7.3-fpm
    ports:
    - target: 9000
    restart: always
    volumes:
    - /home/benlumia007/WordPress/sites:/var/www/html:rw
version: '3.5'
volumes:
  db_data: {}
```
