### ISSUE TITLE
Using `${foo:?Error}` construct is expanded at too early.

### ISSUE THREAD

**Issue by hansbogert** [docker/compose#6958]
## using ${foo:?We need foo} construct is expande/triggered too early

When using multiple docker-compose files, e.g., `docker-compose -f docker-compose.yml -f docker-compose.dev.yml` and the former has a 

```
service:
  build:
    args: 
      FOO: ${foo:?Set 'foo' something}
```

 construct, and the latter docker-compose file has for example, 
```
service:
  build:
    args:
      FOO: iamhardcoded
```
Then, using docker-compose errors with:

```
docker-compose config
ERROR: Missing mandatory value for "build" option in service "service": set 'foo'
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

**Output of `docker version`**
```
docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml config 
ERROR: Missing mandatory value for "build" option in service "service":  Set FOO !

```

## Steps to reproduce the issue

1. Use https://gist.githubusercontent.com/hansbogert/575eb05444a90e69dad8fb0c742b9626/raw/b8738564518bf7c052e176333f6182e0a91448d2/docker-compose.yml and https://gist.githubusercontent.com/hansbogert/a47b8bde980375af13a3658f0a7b65fe/raw/939da84fa15e910deca30de0aac3a96417e31d0d/docker-compose.dev.yml as docker-compose files
2. run `docker-compose -f docker-compose.yml -f docker-compose.dev.yml config`

### Observed result
```
ERROR: Missing mandatory value for "build" option in service "service":  Set FOO !

```

### Expected result
```
version: '3.7'
services:
  service:
    build:
      args:
        FOO: iamhardcoded
```

## Additional information

Ubuntu 18.04.

**Comment by ndeloof** [comment]
The logic to load multiple compose file https://github.com/docker/compose/blob/master/compose/config/config.py#L386 is to parse them all with Interpolation=True then load config sections merging elements from all yaml sources. By doing so each and every file has to individually be a valid compose yaml file, so the error you encounter.

Changing this logic and evaluating potential impacts is way beyound my Python skills :)

**Comment by thaJeztah** [comment]
We should check if the docker cli has the same problem

**Comment by ndeloof** [comment]
@thaJeztah the CLI indeed does the same : load and interpolate on a per-file basis https://github.com/docker/cli/blob/master/cli/compose/loader/loader.go#L98

**Comment by thaJeztah** [comment]
Thinking what the consequences would be to "lazily" expand (after merging); from the top of my head, something like the example below could be problematic;

```yaml
networks:
  foo:
    name: ${foo:?Set 'foo' something}
```

```yaml
networks:
  foo:
    external: true
```

Actually; I don't think that should be a problem, as we don't merge properties of the individual networks (last one just overwrites the previous one) 🤔 so from that perspective, it should work.

Changing should definitely get some eyes though, because merging can be complicated, and we need to be sure we don't miss some corner-case that we didn't think about

**Comment by thaJeztah** [comment]
still an issue afaik, so don't close yet

**Comment by carlfischerjba** [comment]
A similar situation occurs within a single compose file. If I run a service from that file I get warnings about missing variables in other services even though they have no effect on the service I'm running.

```
version: "3.5"
services:
  a:
    image: busybox
    environment:
        - FOO=${FOO?Please provide FOO}
  b:
    image: busybox
    environment:
        - BAR=${BAR?Please provide BAR}
```

This should/could work but doesn't.

```
$ FOO=foo docker-compose -f /tmp/test.yml run a
ERROR: Missing mandatory value for "environment" option interpolating ['BAR=${BAR?Please provide BAR}'] in service "b": Please provide BAR
```
