### ISSUE TITLE
"env_file" not working in Windows 10

### ISSUE THREAD

**Issue by nighttiger1990** [docker/compose#6965]
## Description of the issue
I declare `env_file` property with value `deploy.env` in `docker-compose.yml`.
But when docker compose up in Windows `deploy.env` file not read

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARNING: The DB_HOST variable is not set. Defaulting to a blank string.
networks:
  notif-v2-production:
    driver: bridge
services:
  mongo-docker:
    container_name: ''
    environment:
      DB_DATABASE: ''
      DB_HOST: notif-mongodb-test
      DB_PASSWORD: ''
      DB_PORT: '27017'
      DB_USERNAME: ''
      DEBUG: '"notification-server-v2:*"'
      MESSAGE: '"THIS IS MY MESSAGE"'
    image: mongo:4.2.0
    networks:
      notif-v2-production: null
    restart: unless-stopped
    volumes:
    - D:\Project\NodeJS\notification-server-v2\data:/data/db:rw
  notification-server-v2:
    container_name: notification-server-v2
    depends_on:
    - mongo-docker
    environment:
      DB_DATABASE: ''
      DB_HOST: notif-mongodb-test
      DB_PASSWORD: ''
      DB_PORT: '27017'
      DB_USERNAME: ''
      DEBUG: '"notification-server-v2:*"'
      MESSAGE: '"THIS IS MY MESSAGE"'
    image: notification-server-v2
    networks:
      notif-v2-production: null
    ports:
    - published: 3000
      target: 3000
    restart: unless-stopped
version: '3.7'
```

## Steps to reproduce the issue

1.  `deploy.env` file same location with `docker-compose.yml`
2.  run `docker compose -f docker-compose up -d`
3.  On Windows 10, message get `The DB_HOST variable is not set. Defaulting to a blank string`
But on Centos 7 work perfectly
**Additional**: if i change `deploy.env` to `.env` Windows work perfectly 

## Additional information
My `deploy.env`
```
DB_HOST=notif-mongodb-test
DB_PORT=27017
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

MESSAGE="THIS IS MY MESSAGE"

DEBUG="notification-server-v2:*"

```

My `docker-compose.yml`
```
version: '3.7'

services:
  notification-server-v2:
    container_name: notification-server-v2
    image: notification-server-v2
    env_file: deploy.env
    ports:
      - 3000:3000
    networks: 
      - notif-v2-production
    restart: unless-stopped
    depends_on:
      - mongo-docker
  mongo-docker:
    container_name: ${DB_HOST}
    image: mongo:4.2.0
    networks: 
      - notif-v2-production
    restart: unless-stopped
    env_file: deploy.env
    volumes:
      - ./data/${DB_HOST}:/data/db
networks: 
  notif-v2-production:
    driver: bridge
```

OS version / distribution, `docker-compose` install method, etc.
