### ISSUE TITLE
docker-compose rm -v says 'No stopped containers' when that isn't true

### ISSUE THREAD

**Issue by sydneybmunizaga** [docker/compose#6968]
## Description of the issue

I have containers that are stopped. My `docker ps -a` looks like this...
``` docker ps -a
4efd8ba5b9b3        ************************/************:latest              "catalina.sh run"        27 minutes ago      Exited (137) 4 minutes ago                                       ci_api_1
92ee9901ceed        mysql:5.7.23                                                "docker-entrypoint.s…"   27 minutes ago      Exited (0) 5 minutes ago                                         ci_database_1
b6fb5f9d9389        mysql:5.7.24                                                "docker-entrypoint.s…"   47 hours ago        Exited (255) 3 hours ago     0.0.0.0:3306->3306/tcp, 33060/tcp   another_db
```

But when I run `docker-compose rm -v` I get a message in the terminal saying `No stopped containers`

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```
**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        89***************
 runc:
  Version:          1.0.0-rc8
  GitCommit:        42**********************
 docker-init:
  Version:          0.18.0
  GitCommit:        fe****

```
**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  api:
    depends_on:
    - database
    environment:
       C********_DATA_DIR: /opt/*******
    image: **************/***********:latest
    network_mode: service:database
    volumes:
    - server-config:/opt/**************
  database:
    environment:
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: <name>
    image: mysql:5.7.23
    ports:
    - 8080/tcp
  ui:
    depends_on:
    - api
    - database
    environment:
      C**********_API_ADDRESS: database:8080
    image: *************/***********:latest
    ports:
    - 80/tcp
version: '3.0'
volumes:
  server-config: {}

```
## Steps to reproduce the issue
```
1. Startup a docker container
2. Stop the docker container
3. Run `docker-compose rm -v`
4. See the error for `No stopped containers`
5. Run `docker ps -a` to see that there are containers there with the status of 'Exit', leaving you wondering what happened. 🤷🏼‍♀️
