### ISSUE TITLE
Permission denied when bind volume

### ISSUE THREAD

**Issue by MSaadatt** [docker/compose#6969]
I install docker on my new Ubuntu VPS. I create docker-compose file and deply it using docker stack command. My dockerfile is like this:
```
version: "3.7"

services:
  mariadb-server:
    image: bitnami/mariadb:10.2
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 8g
    volumes:
      - ./docker-stack/mariadb:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=7MGQ5Rk98uBE
    ports:
      - "3312:3306"
    networks:
      - network

networks:
  network:
    driver: overlay
```
I deploy it using this command:
``` docker stack deploy -c docker-compose.yml test```
But when the service start running it can't write to bind volume:
```mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied```
My OS version:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
After that I inspect the service for more details. I saw this in my service:
```
"Privileges": {
   "CredentialSpec": null,
   "SELinuxContext": null
 },
```
I've never seen it before in my other VPS running docker. SELinux is in passive mode in Ubuntu  byt default but it will appear in docker! I haven't seen any Privileges label on my another VPS.
My another VPS using this dockerfile without any permission denied problem.
I have reinstall Ubuntu many times but the problem persist!

docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: qrfebwctvsqe7asofq8c
  Is Manager: true
  ClusterID: 4arobbjz5kr231o3egih
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 
  Manager Addresses:
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-65-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.32GiB
 Name: marcoico
 ID: 5BBV:OMQQ:MDGD:BNLY:VNZR:E7WH:WUQU:SN6D:ATSC:6TKB:UIM3:OHFA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
