### ISSUE TITLE
Docker-compose does not generate an error for invalid repository names

### ISSUE THREAD

**Issue by Untiring** [docker/compose#6979]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Get an error telling you the repository name given in the docker-compose file in the 'image' section is invalid
### Actual behavior
building {servicename}
flashing cursor, no building steps being executed,
no error, ctrl+c doesn't terminate the build process. the only way to stop it by closing the terminal
### Information
when building a custom image with docker-compose I sheepishly tried to name the image with capital letters. when trying to manually build my image with the same name I noticed that this name is invalid and can only contain lowercase letters. Changed this in the docker-compose file and now it does run. An error pointing you to this mistake would have saved me quite some time.

  - Windows Version: 10 pro build 18362
  - Docker Desktop Version: 19.03.4, build 9013bf5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
Check the information section.
give your Dockerfile the following layout:
```yml
version: '3.7'
services:
  {servicename}:
    image: someName
    build:
      context: {some directory with a dockerfile}
# this will not build because of the capital letter in the image name, however it does not generate an error
```
make sure you have a basic docker file in the target directory used in the context section of the docker-compose file
start the build process by running `docker-compose up --build.`

**Comment by stephen-turner** [comment]
Moving to docker/compose repository.

**Comment by ndeloof** [comment]
Which docker engine version are you running ?
"latest version of my channel" unfortunately is not a usefull info as I don't know what was "latest" at the time your reported this issue.

I tried to run on my own Windows box:
```
#docker-compose.yml 
version: '3'

services:
  test:
    image: UPPERCASE_WONT_WORK
    build: .
```

```
C:\Users\nicolas\test>docker-compose build
Building test
ERROR: invalid reference format: repository name must be lowercase
```

docker-compose 1.24.1
docker 19.03.4
docker desktop 2.1.0.4 (stable)

Which versions are you running ?
