### ISSUE TITLE
Since 1.24.1 volumes handling is not that predictable

### ISSUE THREAD

**Issue by kiorky** [docker/compose#7003]
## Context information (for bug reports)
Since https://github.com/docker/compose/pull/6406, volumes handling is a bit unpredictable, and as things are moving, i want to be sure of the wanted behavior not to face more regressions in the future.

## Steps to reproduce the issue
From https://github.com/docker/compose/pull/6406

This config should fail
```yaml
version: "3.7"
services:
  test:
    image: ubuntu
    volumes:
    - test:/test
    - 2test:/test
volumes:
  test:
  2test:
```

**But are we agreeing than this one would never fail ?**
```yaml
version: "3.7"
services:
  test:
    image: ubuntu
    volumes:
    - test:/test
    - ./dev:/test
volumes:
  test:
```
----
Idea being the scene is to allow simple prod/dev configs should still be supported as-is:
``docker-compose.yml``
```yaml
version: "3.7"
services:
  test:
    image: ubuntu
    volumes:
    - test:/test
volumes:
  test:
```

``docker-compose-dev.yml``
```yaml
version: "3.7"
services:
  test:
    volumes:
    - ./dev:/test
```

and use it with ``docker-compose -f docker-compose.yml -f docker-compose-dev.yml``

**Comment by rumpl** [comment]
Hi @kiorky 

The first two docker-compose files will result in an error because you have duplicate mount points.

However, if you split the two compose files and pass them to compose then you will get a valid compose file because the merge will remove the volumes from the first file: 
```
$ docker-compose -f docker-compose.yml -d docker-compose-dev.yml config
services:
  test:
    image: ubuntu
    volumes:
    - /private/tmp/t/r/dev:/test:rw
version: '3.7'
volumes:
  test: {}
```

**Comment by kiorky** [comment]
Then there is another misdefined behavior, volumes (LIST type) are know to be merged during configs merge, so **are we agreeing that merge removes only matching mountpoints and merge the others ?**
``docker-compose-1-a.yml``
```yaml
version: "3.7"
services:
  test:
    image: ubuntu
    volumes:
    - test:/test
    - othermp:/test2
volumes:
  test:
  othermp:
```
``docker-compose-1-b.yml``
```yaml
version: "3.7"
services:
  test:
    volumes:
    - ./dev:/test2
```
volumes are not totally removed but merged, including ``./dev`` but overriding

**Comment by kiorky** [comment]
Then there is another misdefined behavior, volumes (LIST type) are know to be merged during configs merge, so **are we agreeing that merge removes only matching mountpoints and merge the others ?**
``docker-compose-1-a.yml``
```yaml
version: "3.7"
services:
  test:
    image: ubuntu
    volumes:
    - test:/test
    - othermp:/test2
volumes:
  test:
  othermp:
```
``docker-compose-1-b.yml``
```yaml
version: "3.7"
services:
  test:
    volumes:
    - ./dev:/test2
```
volumes are not totally removed but merged, including ``./dev`` but overriding the ``test2`` container mountpoint
