### ISSUE TITLE
Ending slash in container path volume handling is buggy

### ISSUE THREAD

**Issue by kiorky** [docker/compose#7004]
## Description of the issue
Ending slash in container path volume handling is buggy when merging configs and duplicate mountpoings paths since 1.24.1.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
>= 1.24.1
```
-----
Consider those two configs:
```yaml
version: "3.7"
services:
  test:
    image: ubuntu
    volumes:
    - prod:/prod
volumes:
  prod:
```
```yaml
version: "3.7"
services:
  test:
    volumes:
    - ./dev:/prod/
```
take care to /prod<strong>/</strong>

This will fail with **Output of `docker-compose config`**
```
ERROR: Duplicate mount points: [prod:/prod:rw, /home/kiorky/for-tests/fail3/dev:/prod:rw]
```
-----
But if you remove the **ending slash: ``/``** in the second config:
```yaml
version: "3.7"
services:
  test:
    volumes:
    - ./dev:/prod
```
It will return the expected result
```yaml
services:
  test:
    image: ubuntu
    volumes:
    - /home/kiorky/for-tests/fail3/dev:/prod:rw
version: '3.7'
volumes:
  prod: {}
```

**Comment by kiorky** [comment]
That was my original issue when i registred #7003

**Comment by jcsirot** [comment]
Hello @kiorky 
Thank you for opening this issue
Indeed docker compose behavior indeed changed between 1.23.1 and 1.24.0. We are going to investigate to understand why.

**Comment by jcsirot** [comment]
It seems that `docker-compose config` with compose 1.23.1 produced a invalid output
```
services:
  test:
    image: ubuntu
    volumes:
    - /home/jcs/for-tests/issue7004/dev:/prod:rw
    - prod:/prod:rw
version: '3.7'
volumes:
  prod: {}
```
