### ISSUE TITLE
Embedded DNS fails to resolve service names after docker-compose down

### ISSUE THREAD

**Issue by VasiliyD** [docker/compose#7015]
## Description of the issue
I have two Windows services with static IPs up and running with `docker-compose up`. And they can ping each other via service names. But if I do `docker-compose down` and then again `docker-compose up`, I can no longer ping services.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:55:51 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: "3.7"
services:
  first:
    image: nano
    networks:
      some_net:
        ipv4_address: 172.28.8.1
  second:
    image: nano
    networks:
      some_net:
        ipv4_address: 172.28.8.2
networks:
  some_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
```

Dockerfile for nano looks like this
```
FROM mcr.microsoft.com/windows/nanoserver:1809
CMD ping -t localhost
```

## Steps to reproduce the issue

1. Run docker-compose up
2. Run docker-compose down
3. Run docker-compose up again
4. Attach to the first service `docker exec -it first_1 cmd`
5. Try to ping second service `ping second`

### Observed result
C:\>ping second
Ping request could not find host second. Please check the name and try again.

### Expected result
Ping second finished successfully

## Additional information
**OS:** Windows 10 Enetrprise, v1809

If I restart docker and then `up` services again - everything works fine (services can ping each other).
Also, `docker-compose stop` doesn't break internal names resolving.
