### ISSUE TITLE
Mandatory value condition not overridden

### ISSUE THREAD

**Issue by mcovalt** [docker/compose#7018]
## Description of the issue

Overriding a mandatory variable (e.g. `${VARIABLE:?err}`) with an inline default value (e.g. `${VARIABLE:-default}`) leads to unexpected results.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:16 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:50:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
ERROR: Missing mandatory value for "environment" option in service "test": you need to set $VARIABLE
```

## Steps to reproduce the issue

1. Use the following two files:

docker-compose.yaml
```yaml
version: "3.5"

services:
  test:
    image: alpine
    environment:
      VARIABLE: ${VARIABLE?you need to set $VARIABLE}
```

docker-compose.override.yaml
```yaml
version: "3.5"

services:
  test:
    environment:
      VARIABLE: ${VARIABLE:-default}
```
2. Ensure the environment variable `$VARIABLE` is **unset**.
3. Execute `docker-compose up`

### Observed result
The `$VARIABLE` is still mandatory despite being overridden with a default.

### Expected result
The `$VARIABLE` will be set to `default`.

### Stacktrace / full error message

```
ERROR: Missing mandatory value for "environment" option in service "test": you need to set $VARIABLE
```
