### ISSUE TITLE
Compose build hangs instead of giving error message in case of uppercase image name.

### ISSUE THREAD

**Issue by pratiksanglikar** [docker/compose#7036]
## Description of the issue
Docker Compose doesn't support uppercase characters for image names, so when a user puts an uppercase character in the `docker-compose.yml` file and tries to build, `docker-compose` should give an error rather than hanging.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker-compose config`**
```
docker-compose  -f "C:\Users\nouser\source\repos\WebApplication2\docker-compose.yml" -f "C:\Users\nouser\source\repos\WebApplication2\docker-compose.override.yml" -f "C:\Users\nouser\source\repos\WebApplication2\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose14357808182777382152 --no-ansi config
services:
  webapplication2:
    build:
      context: C:\Users\nouser\source\repos\WebApplication2
      dockerfile: WebApplication2\Dockerfile
      labels:
        com.microsoft.created-by: visual-studio
        com.microsoft.visual-studio.project-name: WebApplication2
      target: base
    container_name: WebApplication2
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus
      /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646 /LogDebuggeeOutputToStdOut
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true"
      ASPNETCORE_URLS: https://+:443;http://+:80
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_FALLBACK_PACKAGES: c:\.nuget\fallbackpackages
      NUGET_PACKAGES: C:\.nuget\packages
    image: webapplication2-UPPERCASE:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath c:\.nuget\packages
        --additionalProbingPath c:\.nuget\fallbackpackages  "C:\app\bin\Debug\netcoreapp3.1\WebApplication2.dll"'
      com.microsoft.visualstudio.debuggee.killprogram: C:\remote_debugger\x64\utils\KillProcess.exe
        dotnet.exe
      com.microsoft.visualstudio.debuggee.program: '"C:\Program Files\dotnet\dotnet.exe"'
      com.microsoft.visualstudio.debuggee.workingdirectory: C:\app
    ports:
    - target: 80
    - target: 443
    volumes:
    - C:\Users\nouser\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
    - C:\Users\nouser\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
    - C:\Users\nouser\source\repos\WebApplication2\WebApplication2:C:\app:rw
    - C:\Users\nouser\onecoremsvsmon\16.5.0066.0:C:\remote_debugger:ro
    - C:\Users\nouser\source\repos\WebApplication2:C:\src:rw
    - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:c:\.nuget\fallbackpackages:ro
    - C:\Users\nouser\.nuget\packages:c:\.nuget\packages:ro
version: '3.4'
```

## Steps to reproduce the issue

1. Clone the repo - https://github.com/pratiksanglikar/docker-compose-uppercase-error.git
2. Observe in `docker-compose.yml` there are uppercase characters in service name
3. navigate to WebApplication2 directory, and run 
```
docker-compose  -f "C:\Users\nouser\source\repos\WebApplication2\docker-compose.yml" -f "C:\Users\nouser\source\repos\WebApplication2\docker-compose.override.yml" -f "C:\Users\nouser\source\repos\WebApplication2\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose14357808182777382152 --no-ansi --verbose build
```
4. Observe that `docker-compose build` command hangs

### Observed result
`docker compose build` hangs.

### Expected result
```
compose.cli.verbose_proxy.proxy_callable: docker build -> <generator object APIClient._stream_helper at 0x00000229FEB0BCA8>
compose.cli.errors.log_api_error: invalid reference format: repository name must be lowercase
```
### Stacktrace / full error message

```
docker-compose  -f "C:\Users\nouser\source\repos\WebApplication2\docker-compose.yml" -f "C:\Users\nouser\source\repos\WebApplication2\docker-compose.override.yml" -f "C:\Users\nouser\source\repos\WebApplication2\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose14357808182777382152 --no-ansi --verbose build
compose.config.config.find: Using configuration files: C:\Users\nouser\source\repos\WebApplication2\docker-compose.yml,C:\Users\nouser\source\repos\WebApplication2\docker-compose.override.yml,C:\Users\nouser\source\repos\WebApplication2\obj\Docker\docker-compose.vs.debug.g.yml
docker.utils.config.find_config_file: Trying paths: ['C:\\Users\\nouser\\.docker\\config.json', 'C:\\Users\\nouser\\.dockercfg']
docker.utils.config.find_config_file: Found file at path: C:\Users\nouser\.docker\config.json
docker.auth.load_config: Found 'credsStore' section
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/version HTTP/1.1" 200 661
compose.cli.command.get_client: docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
compose.cli.command.get_client: Docker base_url: http+docker://localnpipe
compose.cli.command.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '19.03.5', 'Details': {'ApiVersion': '1.40', 'Arch': 'amd64', 'BuildTime': '2019-11-13T07:36:50.000000000+00:00', 'Experimental': 'true', 'GitCommit': '633a0ea', 'GoVersion': 'go1.12.12', 'KernelVersion': '10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)', 'MinAPIVersion': '1.24', 'Os': 'windows'}}], Version=19.03.5, ApiVersion=1.40, MinAPIVersion=1.24, GitCommit=633a0ea, GoVersion=go1.12.12, Os=windows, Arch=amd64, KernelVersion=10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202), Experimental=True, BuildTime=2019-11-13T07:36:50.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('dockercompose14357808182777382152_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/networks/dockercompose14357808182777382152_default HTTP/1.1" 200 943
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {'Attachable': True,
 'ConfigFrom': {'Network': ''},
 'ConfigOnly': False,
 'Containers': {'a0ee74438263197bb257d5ad5d49e9d7d51d147dc851ef66c8df320f92a6dbc8': {'EndpointID': '309885ae7991e0782055d0dcc306211994ddacbd62d8b65d40f545b7247a4861',
                                                                                     'IPv4Address': '172.25.127.211/16',
                                                                                     'IPv6Address': '',
                                                                                     'MacAddress': '00:15:5d:11:7f:c2',
                                                                                     'Name': 'WebApplication2'}},
 'Created': '2019-11-19T12:25:55.9670017-08:00',
 'Driver': 'nat',
...
compose.service.build: Building webapplication2
compose.cli.verbose_proxy.proxy_callable: docker build <- (path='\\\\?\\C:\\Users\\nouser\\source\\repos\\WebApplication2', tag='webapplication2-UPPERCASE:dev', rm=True, forcerm=False, pull=False, nocache=False, dockerfile='WebApplication2\\Dockerfile', cache_from=None, labels={'com.microsoft.created-by': 'visual-studio', 'com.microsoft.visual-studio.project-name': 'WebApplication2'}, buildargs={}, network_mode=None, target='base', shmsize=None, extra_hosts=None, container_limits={'memory': None}, gzip=False, isolation=None, platform=None)
docker.api.build._set_auth_headers: Looking for auth config
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'webapplication1420190920041237.azurecr.io:443'
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'webapplication220191008014328.azurecr.io:443'
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'webapplication320191021113840.azurecr.io:443'
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'webapplication520191021114425.azurecr.io:443'
docker.auth._resolve_authconfig_credstore: Looking for auth entry for 'workerservice120191021100554.azurecr.io:443'
docker.api.build._set_auth_headers: Sending auth config ('webapplication1420190920041237.azurecr.io:443', 'webapplication220191008014328.azurecr.io:443', 'webapplication320191021113840.azurecr.io:443', 'webapplication520191021114425.azurecr.io:443', 'workerservice120191021100554.azurecr.io:443')
```
## Additional information

OS version: Microsoft Windows 10 Enterprise - 1903
Project: Default ASP.NET Core web project created in Visual Studio.
Nature of error: error occurs in both Visual Studio tools and powershell.
