### ISSUE TITLE
Raspberry crashes on docker-compose up

### ISSUE THREAD

**Issue by RSWilli** [docker/compose#7051]
## Description of the issue

I am running Manjaro ARM on my raspberry PI 3B. I tried to start the `homeassistant/raspberry3-homassistant` image from docker-compose

It did not work, and the PI froze (needed a hard reset to work again)

## Context information (for bug reports)

The issue was, that i tried to start a arm32 image on my arm64 pi, and Manjaro lacks the support for arm32

Running the image with `docker` gave this error: `standard_init_linux.go:211: exec user process caused "exec format error"` (which is totally user-unfriendly btw)

docker-compose straight up crashed the whole system instead

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.0
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Sat Nov 16 00:08:25 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       633a0ea838
  Built:            Sat Nov 16 00:07:54 2019
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  homeassistant:
    container_name: home-assistant
    environment:
      TZ: Europe/Berlin
    image: homeassistant/raspberrypi3-homeassistant:stable
    ports:
    - published: 8123
      target: 8123
    restart: always
    volumes:
    - /home/whale/hassio/config:/config:rw
version: '3.7'
```

## Steps to reproduce the issue

1. Raspberry PI with Manjaro ARM (Maybe other distros work as well)
2. `docker run --name="home-assistant" -e "TZ=Europe/Berlin" -v $PWD/config:/config -p 8123:8123 homeassistant/raspberrypi3-homeassistant:latest`
and `docker-compose up` with the given config
3. observe the difference ;)

### Observed result

docker-compose crashes the system, while docker gives an error

### Expected result

docker-compose gives an error

### Stacktrace / full error message
for docker:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
docker-compose:
no error, since Pi crashes

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Linux raspi 5.3.12-1-MANJARO-ARM #1 SMP Wed Nov 20 16:23:31 UTC 2019 aarch64 GNU/Linux

docker-compose installed through `yay -S docker-compose`
