### ISSUE TITLE
docker-compose hangs indefinitely - resources already in use

### ISSUE THREAD

**Issue by xb4r7x** [docker/compose#7063]
## Description of the issue

If we attempt to build more than one of our container sets with `docker-compose -f docker-compose.yml up` at the same time docker-compose seems to hang indefinitely. The behavior possibly seems to be alleviated if we remove `tty: true` from our `docker-compose.yml` file, but we need that to keep our containers up.

It should be noted that this behavior was not happening until we downgraded our compose file from version 3 to version 2.4 to support the `mem_limit` parameter. Things were working previously with the default 1Gb of RAM but recent application changes required that we increase the memory allotted to out containers, so we downgraded the file to 2.4, added a 3gig mem_limit, and ever since we haven't been able to build our containers. docker-compose simply hangs. Retaining the 2.4 version and removing the mem_limit parameter builds our containers successfully, but we need to be able to increase this.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Enterprise
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9e27c76fe0
 Built:             10/17/2019 23:42:50
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.10
  Git commit:       9e27c76fe0
  Built:            10/17/2019 23:41:23
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  service1:
    environment:
      dbAdminPass: '"Redacted"'
      dbAdminUser: '"Redacted"'
      dbAppPass: '"Redacted"'
      dbAppUser: '"Redacted"'
      dbName: '"databasenameGoesHere"'
      dbServer: '"databaseserver.domain.local"'
    image: nexus.domain.com:1234/repository/path/imagename
    mem_limit: 3g
    ports:
    - 80/tcp
    - 443/tcp
    - 12345/tcp
    tty: true
    volumes:
    - C:\Path\to\places:C:\to\do\stuff:rw
    - C:\Path\to\places:C:\to\do\stuff:rw
    - C:\Path\to\places:C:\to\do\stuff:rw
    - C:\Path\to\places:C:\to\do\stuff:rw
    - C:\Path\to\places:C:\to\do\stuff:rw
  redis:
    depends_on:
      service1:
        condition: service_started
    image: nexus.domain.com:123/repository/path/redis_imagename
    ports:
    - 4321/tcp
version: '2.4'
```
Information from the above output has been redacted for security reasons.

## Steps to reproduce the issue
1. run `docker-compose -f docker-compose.yml up` with different mostly identical compose files, on the same server, at the same time with `mem_limit: 3g` and `tty: true` both set.
2. Wait for compose to hang.
3. Check windows application log for `requested resource is in use` error message.
4. (optional) pull out some hair, grab a cocktail, and cry.

### Observed result
docker-compose hangs 

### Expected result
containers built and available.

### Stacktrace / full error message

**Output of `docker-compose -f docker-compose.yml --verbose up`**
```
 urllib3.connectionpool._make_request: http://localhost:None "POST
 /v1.25/containers/CONTAINERID/start HTTP/1.1" 500 None
 compose.parallel.parallel_execute_iter: Failed: ServiceName(project='CONTAINERNAME',
 Creating CONTAINERNAME ... error

 compose.parallel.feed_queue: Pending: set()
 ERROR: for CONTAINERNAME  Cannot start service SERVICENAME: 
 hcsshim::CreateComputeSystem CONTAINERID: The requested resource is in use.
(extra info: {**LOTS OF REDACTED JSON - we can probably share this privately if it's necessary for troubleshooting**})
compose.cli.main.main: Encountered errors while bringing up the project.
```

## Additional information

```
systeminfo /fo csv | ConvertFrom-Csv | select OS*, S
ystem*, Hotfix* | Format-List


OS Name             : Microsoft Windows Server Datacenter
OS Version          : 10.0.18362 N/A Build 18362
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Member Server
OS Build Type       : Multiprocessor Free
System Boot Time    : 11/25/2019, 2:55:03 PM
System Manufacturer : VMware, Inc.
System Model        : VMware Virtual Platform
System Type         : x64-based PC
System Directory    : C:\Windows\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 2 Hotfix(s) Installed.,[01]: KB4497727,[02]: KB4497464
```

We've tried quite a few things to resolve this, and have mostly gotten nowhere. Hoping this is either a bug that can be patched, or that at least we're doing something stupid and y'all know what  that might be. We've been trying to resolve this for three days to no avail. Please let me know if you need any additional information.
