### ISSUE TITLE
[Question|Feature Request] Dockerfile inside docker-compose.yml

### ISSUE THREAD

**Issue by ThaDaVos** [docker/compose#7095]
I don't know if this is possible already or even in the scope of docker compose but one feature I would love is to include Dockerfile inside the docker-compose.yaml using a block mapping. This is especially useful if you need to extend a image and only run 1 command inside, without needing the context etc.
For example, you need the PHP image and you want to enable some extensions etc.

My proposal would look as follow:
```yaml
version: '3.7'
services:
  app:
    image: php
    build: |
      FROM php AS Base
      RUN docker-php-ext-enable pdo_mysql
```
This way, one could extend on the PHP image and enable the pdo_mysql extension

**Comment by ThaDaVos** [comment]
Any news about this? I was almost about to create a new issue as I couldn't find this one, some more info (as it seems there's an template now):

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
Partially, the thing is, I need to add a single `RUN` to a existing image to run a command which sets php.ini related settings [Directus Custom Upload Limits](https://github.com/directus/docker/blob/master/examples/custom-upload-limits/Dockerfile).
I know I can just add a dockerfile especially for this, reference it in the docker-compose.yml and use it. But, it will also setup a context (while there's no need to `COPY` anything).

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
I would like to propose a solution as below to make it possible to embed small dockerfiles which need **no** context to be build inside the docker-compose.yml file:
```yaml
version: "x.x"
services:
  my-amazing-service:
    build:
      dockerfile: |
      from directus/directus:v8-apache
      RUN php-ini-add "upload_max_filesize=1G"
    ports:
      - 80
```
or even, but just a little unclear:
```yaml
version: "x.x"
services:
  my-amazing-service:
    image: directus/directus:v8-apache
    build:
      dockerfile: |
      RUN php-ini-add "upload_max_filesize=1G"
    ports:
      - 80
```

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
Creating a dockerfile and using that, but it will also setup a context, which isn't needed
