### ISSUE TITLE
Add backup/restore commands

### ISSUE THREAD

**Issue by jpic** [docker/compose#7158]
This suggestion is to add `backup` and `restore` options to docker-compose.yml. Example:

```
services:
  db:
    image: postgres
    backup: pg_dumpall -f /dump/db/pg.dump
    restore: psql < /dump/db/pg.dump
    volumes:
    - ./dump:/dump

  web:
    image: wordpress
    backup: rsync /uploads /dumps/uploads
    restore: rsync /dumps/uploads /uploads
    volumes:
    - ./dump:/dump
```

With this configuration, it makes it possible to add `backup` and `restore` commands. The responsibility to encrypt and upload backups somewhere is left to the user.
