### ISSUE TITLE
Can't mount a volume with spaces in it on Windows 10 Home

### ISSUE THREAD

**Issue by cbeust** [docker/compose#7187]
## Description of the issue

Attempting to mount a Windows path with spaces in it results in an empty directory in the container.

## Context information (for bug reports)

I've tried as many combinations as I could:

```
      -  /c/Program\ Files/PostgreSQL/11/data:/data1
      -  "c:\\Program Files\\PostgreSQL\\11\\data:/data2"
      -  c:\\Program\ Files\\PostgreSQL\\11\\data:/data3
      -  "c:/Program Files/PostgreSQL/11/data:/data4"
      -  c:/Program\ Files/PostgreSQL/11/data:/data5
      -  "c:/Program Files/PostgreSQL/11/data:/data6"
      -  "c:/Program Files/PostgreSQL/11/data:/data7"
```

and the result:

```
root@d091534751f7:/# ls -l /data?
/data1:
total 0

/data2:
total 0

/data3:
total 0

/data4:
total 0

/data5:
total 0

/data6:
total 0

/data7:
total 0
```

Mounting a volume with no spaces in it works fine.

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           19.03.1
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Wed Jul 31 15:18:18 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056dbc
  Built:            Thu Apr 11 04:50:00 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    build:
      context: C:\Users\cedri\kotlin\perry-kotlin\db
    container_name: perry-db
    image: perry-db:latest
    ports:
    - 5432:5432/tcp
    volumes:
    - /c/Program/ Files/PostgreSQL/11/data:/var/lib/postgresql/data:rw
    - /c/Program/ Files/PostgreSQL/11/data:/data1:rw
    - /c/Program Files/PostgreSQL/11/data:/data2:rw
    - /c/Program/ Files/PostgreSQL/11/data:/data3:rw
    - /c/Program Files/PostgreSQL/11/data:/data4:rw
    - /c/Program/ Files/PostgreSQL/11/data:/data5:rw
    - /c/Program Files/PostgreSQL/11/data:/data6:rw
    - /c/Program Files/PostgreSQL/11/data:/data7:rw
    - /c/Users:/users:rw
  web:
    build:
      context: C:\Users\cedri\kotlin\perry-kotlin
    container_name: perry-kotlin
    image: perry:latest
    links:
    - db
    ports:
    - 8000:9000/tcp
version: '3.0'
```
