### ISSUE TITLE
Allow Docker "label"s to be modeled as yaml objects

### ISSUE THREAD

**Issue by LookitheFirst** [docker/compose#7193]
**Is your feature request related to a problem? Please describe.**

I'm using docker-compose with the Traefik reverse proxy. To configure the integration, Traefik expects specific labels on a specific Docker service. In a docker-compose file this can look like this:

```yaml
version: '3.7'

services:
  apache:
    image: httpd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.rule=Host(`subdomain.example.com`)"
      - "traefik.http.routers.app.middlewares=app@file"
      - "traefik.http.routers.app.service=app@file"
    restart: always
```

As you can see, this can become very verbose. On some other platforms supported by Traefik one is able to write this config in a yaml-like syntax, which reduces clutter and makes this configuration much more readable

**Describe the solution you'd like**

I would like to write the label configuration like this:

```yaml
version: '3.7'

services:
  apache:
    image: httpd
    labels:
      traefik:
        enable: true
        http:
          routers:
            app:
              tls: true
              rule: "Host(`subdomain.example.com`)"
              middlewares: "app@file"
              service: "app@file"
    restart: always
```

Of course, Docker expects labels to contain text instead of objects. This is why docker-compose would have to convert this object notation to dot-notation. The generated container would **still contain the labels in dot-notation**. The object notation should **only** apply for the docker-compose.yml file.
Also this should be completely optional, so you can still define the labels the old way

**Describe alternatives you've considered**

To make the file even more readable, middle packages could also be shortened like this:

```yaml
version: '3.7'

services:
  apache:
    image: httpd
    labels:
      traefik:
        enable: true
        http.routers.app:
          tls: true
          rule: "Host(`subdomain.example.com`)"
          middlewares: app@file
          service: app@file
    restart: always
```

**Additional context**
none
