### ISSUE TITLE
“Docker-compose up” returns Traceback and UnicodeEncodeError:

### ISSUE THREAD

**Issue by paalss** [docker/compose#7206]
## Description of the issue
When I run the command “docker-compose up” in my working directory, cmd outputs a traceback list and a unicodeencode Error, instead of creating services.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 2.7.16
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  chrome:
    depends_on:
    - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: '4444'
      SCREEN_HEIGHT: '1080'
      SCREEN_WIDTH: '1920'
    image: selenium/node-chrome:3.141.59-europium
    shm_size: 2gb
  db:
    environment:
      MYSQL_DATABASE: contact_registry
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: user
    image: mariadb
    networks:
      default: null
    volumes:
    - C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing\dbInit:/docker-entrypoint-initdb.d:rw
    - persistent:/var/lib/mysql:rw
  firefox:
    depends_on:
    - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: '4444'
      SCREEN_HEIGHT: '1080'
      SCREEN_WIDTH: '1920'
    image: selenium/node-firefox:3.141.59-europium
    shm_size: 2gb
  phpmyadmin:
    environment:
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: user
    image: phpmyadmin/phpmyadmin
    networks:
      default: null
    ports:
    - 8080:80/tcp
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:3.141.59-europium
    networks:
      default: null
    ports:
    - 4444:4444/tcp
  test:
    build:
      context: C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing
      dockerfile: ./Dockerfile.codeception
    networks:
      default: null
    volumes:
    - C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing\tests:/var/www/test:rw
    - C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing\src:/var/www/html:rw
  www:
    build:
      context: C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing
      dockerfile: ./Dockerfile.www
    networks:
      default: null
    ports:
    - 80:80/tcp
    volumes:
    - C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing:/var/www/html/:rw
    - C:\Users\P├Ñl Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing\logs:/var/log/apache2/:rw
version: '3.0'
volumes:
  persistent: {}
```

## Steps to reproduce the issue

1. In Command prompt, cd into the directory which contains the docker-compose.yml file
2. Run docker-compose up -d

### Observed result
Network is successfully created, but none of the services defined in docker.compose.yml is.

### Expected result
I expect the services defined in docker-compose.yml to be created as well as the network.

### Stacktrace / full error message

```
C:\Users\Pål Stakvik\Documents\WWW-tek\kode\imt2291-lecture-notes-2020\cookies_sessions_testing>docker-compose up -d
Creating network "cookies_sessions_testing_default" with the default driver
Building www
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 367, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 158, in build
  File "site-packages\docker\api\build.py", line 341, in process_dockerfile
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 10: ordinal not in range(128)
[58348] Failed to execute script docker-compose
```

## Additional information

OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.18362 N/A Build 18362
