### ISSUE TITLE
Cannot assign dot env file to build args 

### ISSUE THREAD

**Issue by abdennour** [docker/compose#7208]
In my docker-compose

```
  build:
      context: .
      args:
        NODE_TAG: ${NODE_TAG}
        PYTHON_TAG: ${PYTHON_TAG}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION}
```

While I have `.env` file

```sh
NODE_TAG=13.7
PYTHON_TAG=3.8
AWS_CLI_VERSION=1.17.1
```

Each time I add variable in `.env`, I have to add it in `args` of docker-compose file.

I would like to comply with DRY and pass the whole `.env` file to args.

I am pretty sure many of you will get confused with env_file. However, we want to highlight aggressively that this feature request is about **building image** (`services.*.build.args`),  and NOT about **container runtime** (`services.*.env_file`)
