### ISSUE TITLE
Composable docker compose files (include another compose project)

### ISSUE THREAD

**Issue by beasteers** [docker/compose#7214]
**Is your feature request related to a problem? Please describe.**
One of my coworkers has a nice repo with multiple containers setup in a docker compose file. I'd like be able to git clone and include this file into a larger compose project without copying and pasting the entire contents of the external repo compose file (for various reasons - cleanliness, maintainability, etc.). 

Say I have a setup like this:
```bash
app1/docker-compose.yml
app2/docker-compose.yml
...
appN/docker-compose.yml
nginx-proxy/docker-compose.yml
```

I don't want to have to cd to each app and bring each up. I'd like to just say, 
```bash
cd ./a_global_entrypoint # pulls in each app, propagates env vars
docker-compose up -d
```
and have it bring up everything.

**Describe the solution you'd like**
Here's a sketch of a possible solution.
```yaml
services:
  serviceA: 
    image: ...
    ...
  
  # *** Include another compose file into this one ***
  other_project: # adds a namespace around the included services (e.g. other_project.serviceX)
    include_project: '../other_project/docker-compose.yml' 
    # project_root: # defaults to ../other_project/

    # then have some way of providing overrides for certain things...
    env: # maybe add some global env overrides
    services:
      serviceX: 
        env: ... # modify some config values
```
If you have a more versatile way to format this, I'm game, but something like this would go a long way to make docker-compose more composable. 

**Describe alternatives you've considered**
I could make a bash script for each thing I need, but that's janky and it makes it cumbersome to run different things. It takes away from the elegance of `docker-compose up`
