### ISSUE TITLE
docker-compose.yml volumes 镜像容器内的目录中的文件被清空

### ISSUE THREAD

**Issue by Y-Aron** [docker/compose#7218]
docker-compose.yml 
```
version: '3.1'
services: 
  ecology:
    restart: always
    image: e9-mysql:190902
    container_name: e9
    ports: 
      - 8080:80
    volumes:
      - ./ecology/album:/usr/local/weaver/ecology/album
    environment:
      TZ: Asia/Shanghai
```
挂载镜像目录到宿主机，使用 volumes 属性，启动后镜像容器中 /usr/local/weaver/ecology/album 目录下的所有文件被清空，这是什么原因？如何处理？
