### ISSUE TITLE
How to specify one service with two networks(one of them is "host") in docker-compose.yaml

### ISSUE THREAD

**Issue by colben** [docker/compose#7221]
# environment
- Two services: "db" and "app"
- I want "app" to run in network "app", and "db" to run in networks "app" and "host"

# issue
- I've tried to specify db service with tow networks like this:
    ```yaml
    service:
      db:
        network_mode: host
        networks:
        - app
        ...
    ```
- and it returned an error:
    ```
    ERROR: 'network_mode' and 'networks' cannot be combined
    ```

# expection
- service "db" can run with tow networks, and one of them is host network
