### ISSUE TITLE
Error: for web-dev UnixHTTPConnectionPool(Host='localhost', Port=None): Read timed out.

### ISSUE THREAD

**Issue by waxim** [docker/compose#7227]
## Description of the issue
When mounting a volume in docker-compose to a symlink'd folder that does not exist this error is returned (it seems due to a memory leak in `com.docker.osxfs`) 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3'

services:
  web-dev:
    tty: true
    environment:
      - COMPOSER_HOME=/composer
      - XDEBUG=on
      - PHP_IDE_CONFIG=serverName=api.web.io
      # Uncomment the following variables to enable and configure blackfire.
      #- BLACKFIRE_CLIENT_ID=
      #- BLACKFIRE_CLIENT_TOKEN=
      #- BLACKFIRE_SERVER_ID=
      #- BLACKFIRE_SERVER_TOKEN=
    build: ./docker/
    container_name: web-dev
    security_opt:
      - seccomp:unconfined
    ports:
      - "10080:10080" # API HTTP
      - "10443:10443" # API HTTPS
      - "13080:13080" # SEG HTTP
      - "13443:13443" # SEG HTTPS
    volumes:
      # web-Nurv
      - ./source/nurv-2.0:/var/www/html/web.dev/nurv/2.0
      - ./source/nurv-2.0/private/config/web.dev:/var/www/html/web.dev/nurv/2.0/config
      - ./source/nurv-2.0/private/config/simon:/var/www/html/web.dev/nurv/2.0/config/simon
      - ./source/nurv-2.0/private/config/routing:/var/www/html/web.dev/nurv/2.0/config/routing
      - ./source/nurv-2.0/index_dev.php:/var/www/html/web.dev/nurv/2.0/index.php

      # web-API
      - ./source/api-1.1:/var/www/html/web.dev/api/1.1
      - ./source/api-1.1/private/config/web.dev:/var/www/html/web.dev/api/1.1/config
      - ./source/api-1.1/private/config/simon:/var/www/html/web.dev/api/1.1/config/simon
      - ./source/api-1.1/private/config/routing:/var/www/html/web.dev/api/1.1/config/routing
      - ./source/api-1.1/index_dev.php:/var/www/html/web.dev/api/1.1/index.php

      # Seg-2.0
      - ./source/seg-api-2.0/2.0/api:/var/www/html/web.dev/seg/2.0/api

      # Simon
      - ./source/simon:/var/www/html/web.dev/simon

      # web-Book
      - ./source/book:/var/www/html/web.dev/book

      # Auth file
      - ./source/api-1.1/private/config/web.dev/.htpasswd:/var/www/html/web.dev/.htpasswd

      # Custom init script
      - ./docker/my_init/:/etc/my_init.d/

      # Nginx Config
      - ./docker/conf/nginx/:/etc/nginx/
      - ./docker/conf/php-fpm.d:/etc/php/7.2/fpm/pool.d/

      # PHP Config
      - ./docker/conf/php/xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
      - ./docker/conf/php/xdebug.ini:/etc/php/7.2/cli/conf.d/xdebug.ini
      - ./source/api/private/config/web.dev/opcache.blacklist:/etc/php/7.2/fpm/conf.d/opcache.blacklist
      - ./docker/conf/php/blackfire.ini:/etc/php/7.2/fpm/conf.d/20-blackfire.ini
      - ./docker/conf/php/opcache.ini:/etc/php/7.2/cli/conf.d/10-opcache.ini
      - ./docker/conf/php/custom.ini:/etc/php/7.2/fpm/conf.d/99-custom.ini
      - ./docker/conf/php/php.ini:/etc/php/7.2/fpm/php.ini
      - ./docker/conf/etc/blackfire-agent:/etc/blackfire/agent

      # SSH Config
      - ./source/.ssh:/root/.ssh_

      # Composer Cache
      - ./.composer:/composer:delegated

      # Scripts
      - ./docker/scripts:/root/scripts
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    working_dir: /var/www/html/web.dev
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
```

## Steps to reproduce the issue

1. Add a volume that maps to a symlink'd local folder that does not exist

### Observed result
`com.docker.osxfs` spikes in memory usage and maxes out all available memory, then docker-compose failes with the following error

```
Error: for web-dev UnixHTTPConnectionPool(Host='localhost', Port=None): Read timed out. 
```

### Expected result
docker compose should gracefully return an error explaining the volume could not be mounted because it does not exist. 

## Additional information

OS version / distribution, `docker-compose` install method, etc.
  Model Name:	MacBook Air
  Model Identifier:	MacBookAir8,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	1.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	1037.80.53.0.0 (iBridge: 17.16.13050.0.0,0)
