### ISSUE TITLE
Logs encoding corrupted when run service in detached mode with tty:true and then up all services.

### ISSUE THREAD

**Issue by AntonOvsyannikov** [docker/compose#7229]
## Description of the issue
I have 2 services, both tty:true, printing some utf-8 encoded string infinitely.

```
version: '3.4'
services:
  main1:
    tty: true
    image: ubuntu:18.04
    command: /bin/bash -c "while :; do echo превед; sleep 1; done"
  main2:
    tty: true
    image: ubuntu:18.04
    command: /bin/bash -c "while :; do echo превед; sleep 1; done"
```

When I start both services with `docker-compose up` everything seems ok.

```
main1_1  | превед
main2_1  | превед
main2_1  | превед
main1_1  | превед
main2_1  | превед
```

But if I start one service in detached mode first and then  do `docker-compose up` the output of services which was started in detached mode is corrupted:

```
$ docker-compose up -d main1
Creating network "compose-bug_default" with the default driver
Creating compose-bug_main1_1 ... done
$ docker-compose up 
compose-bug_main1_1 is up-to-date
Creating compose-bug_main2_1 ... done
Attaching to compose-bug_main1_1, compose-bug_main2_1
main2_1  | превед
main1_1  | ������������
main1_1  | ������������
main1_1  | ������������
main1_1  | ������������
main2_1  | превед
main1_1  | ������������
main2_1  | превед
```

```
$ docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019```
```

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
$docker-compose config
services:
  main1:
    command: /bin/bash -c "while :; do echo превед; sleep 1; done"
    image: ubuntu:18.04
    tty: true
  main2:
    command: /bin/bash -c "while :; do echo превед; sleep 1; done"
    image: ubuntu:18.04
    tty: true
version: '3.4'

```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G2022
```
