### ISSUE TITLE
Environment variables not being picked up by docker-compose

### ISSUE THREAD

**Issue by TAGC** [docker/compose#7232]
## Description of the issue

Environment variables specified for services defined in `docker-compose.yml` aren't appearing in the docker containers at run-time.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  api:
    build:
      context: C:\Projects\order-status\api
    environment:
      ASPNETCORE_ENVIRONMENT: '"Test"'
    expose:
    - '80'
  ui:
    build:
      context: C:\Projects\order-status\ui
    depends_on:
    - api
    environment:
      REACT_APP_SERVER_BASE_URL: http://api
    ports:
    - 3000:80/tcp
version: '3.0'
```

## Steps to reproduce the issue

1. Build services using `docker-compose build`.
2. Run one of the services using `docker run` and specifying the entrypoint to be "bash"
3. Run `echo $<<EXPECTED_ENVIRONMENT_VARIABLE`

### Observed result

The values specified for the environment variables aren't output.

### Expected result

The environment variables defined in the `environment` section should be output.

## Additional information

OS: Windows 10 x64
Docker compose installed via Docker Desktop.

OS version / distribution, `docker-compose` install method, etc.
