### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use

### ISSUE THREAD

**Issue by Martinnygaard** [docker/compose#7233]
## Description of the issue
I have a installed Docker on my Raspberry Pi 4.
On this docker, i followed the following guide [link](https://www.reddit.com/r/homeassistant/comments/cm4tzp/guide_for_installing_on_a_raspberry_pi4_using/) and [link](https://www.reddit.com/r/homeassistant/comments/895iw6/my_home_assistant_setup_rpi_3b_docker_compose/)

First time, everything started fine.
Then after sudo reboot, things started to happen:

I rebooted, it will fire up only these containers: 
> proxx/grafana-armv7
> lsioarmhf/organizr
> portainer/portainer
> tribunex/ha-dockermon-pi
> influxdb  

Just before the restart i also had NodeRED, Mosquitto and HomeAssistant running.

Then i tried manually start them by hitting `pi@SimpsonsHome:/opt $ docker-compose up -d`. 
> dockermon is up-to-date
> portainer is up-to-date
> influxdb is up-to-date
> Starting mosquitto ...
> organizr is up-to-date
> grafana is up-to-date
> Starting mosquitto ... error
> 
> ERROR: for mosquitto  Cannot start service mosquitto: driver failed programming external connectivity on endpoint mosquitto (a25e488206442aa55970559251babba815da2e2be10a676d77c6bd54f792f717): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use
> 
> ERROR: for mosquitto  Cannot start service mosquitto: driver failed programming external connectivity on endpoint mosquitto (a25e488206442aa55970559251babba815da2e2be10a676d77c6bd54f792f717): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use
> ERROR: Encountered errors while bringing up the project.

I used `pi@SimpsonsHome:/opt $ docker-compose down` to shut down my containers again (Note: now all of them are listed)
> pi@SimpsonsHome:/opt $ docker-compose down
> Stopping grafana   ... done
> Stopping organizr  ... done
> Stopping portainer ... done
> Stopping dockermon ... done
> Stopping influxdb  ... done
> Removing grafana   ... done
> Removing organizr  ... done
> Removing portainer ... done
> Removing dockermon ... done
> Removing influxdb  ... done
> Removing mosquitto ... done
> Removing network opt_default

then located which process that is using mosquittos address:
> pi@SimpsonsHome:/opt $ sudo lsof -i -P -n | grep 1883
> mosquitto  419 mosquitto    5u  IPv4  15595      0t0  TCP *:1883 (LISTEN)
> mosquitto  419 mosquitto    6u  IPv6  15596      0t0  TCP *:1883 (LISTEN)

then i killed the process:
>pi@SimpsonsHome:/opt $ sudo kill 419

And started ducker back up:
> pi@SimpsonsHome:/opt $ docker-compose up -d
> Creating network "opt_default" with the default driver
> Creating dockermon ... done
> Creating influxdb  ... done
> Creating organizr  ... done
> Creating portainer ... done
> Creating mosquitto ... done
> Creating grafana       ... done
> Creating homeassistant ... done
> Creating node-red      ... done

And now everything is working again.
My conclusion is that the mosquitto service does not get killed during reboot, and then it cannot start again during startup (Because old instance of Mosquitto is blocking the new instance)

**If i at this point reboot again - im rioght back at the beginning - those three containers are not starting...**

Ant idea on how to fix this?
I am out of ideas.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
pi@SimpsonsHome:/opt $ docker-compose version
docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

```

**Output of `docker version`**
```
pi@SimpsonsHome:/opt $ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:37:22 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:31:17 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683


```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
pi@SimpsonsHome:/opt $ docker-compose config
services:
  dockermon:
    container_name: dockermon
    image: tribunex/ha-dockermon-pi
    ports:
    - 8126:8126/tcp
    restart: on-failure
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /opt/dockermon:/config:rw
  grafana:
    container_name: grafana
    depends_on:
      influxdb:
        condition: service_healthy
    image: proxx/grafana-armv7
    ports:
    - 3000:3000/tcp
    restart: on-failure
    user: '1000'
    volumes:
    - /opt/grafana:/etc/grafana:rw
    - /opt/grafana:/var/lib/grafana:rw
    - /etc/timezone:/etc/timezone:ro
  homeassistant:
    container_name: homeassistant
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    devices:
    - /dev/ttyACM0:/dev/ttyACM0:rwm
    healthcheck:
      interval: 30s
      retries: 6
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:8123
      timeout: 10s
    image: homeassistant/raspberrypi3-homeassistant:latest
    network_mode: host
    restart: on-failure
    volumes:
    - /opt/homeassistant:/config:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
  influxdb:
    container_name: influxdb
    healthcheck:
      interval: 30s
      retries: 24
      test:
      - CMD
      - curl
      - -sI
      - http://127.0.0.1:8086/ping
      timeout: 1s
    image: influxdb
    ports:
    - 8086:8086/tcp
    restart: on-failure
    volumes:
    - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - /opt/influxdb:/var/lib/influxdb:rw
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
    - 1883:1883/tcp
    restart: on-failure
    user: 1000:1000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/mosquitto:/mosquitto/config:ro
    - /opt/mosquitto:/mosquitto/data:rw
  node-red:
    container_name: node-red
    depends_on:
      homeassistant:
        condition: service_healthy
      mosquitto:
        condition: service_started
    healthcheck:
      interval: 30s
      retries: 5
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:1880
      timeout: 10s
    image: nodered/node-red-docker:rpi-v8
    ports:
    - 1880:1880/tcp
    restart: "no"
    volumes:
    - /opt/node-red:/data:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  organizr:
    container_name: organizr
    environment:
      PGID: '1000'
      PUID: '1000'
    healthcheck:
      interval: 30s
      retries: 5
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1
      timeout: 10s
    image: lsioarmhf/organizr
    ports:
    - 80:80/tcp
    - 443:443/tcp
    restart: on-failure
    volumes:
    - /opt/organizr:/config:rw
    - /etc/letsencrypt:/etc/letsencrypt:ro
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
    - 9000:9000/tcp
    restart: "no"
    volumes:
    - /opt/portainer:/data:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '2.1'

```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
