### ISSUE TITLE
"docker-compose up" fail. because in ".dockerignore" have special word "英文" (UnicodeDecodeError)

### ISSUE THREAD

**Issue by we684123** [docker/compose#7236]
## Description of the issue
"docker-compose up" fail. because in ".dockerignore" have special word "英文" (UnicodeDecodeError)
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      context: C:\Users\win10\Dropbox\Github\TGbot
    ports:
    - 5984:5984/tcp
    volumes:
    - C:\Users\win10\Dropbox\Github\TGbot\data\logs:/app/logs:rw
    - C:\Users\win10\Dropbox\Github\TGbot\data\excel:/app/excel:rw
version: '3.0'
```

## Steps to reproduce the issue

1. clear all image
2. creat a folder and add 4 file "app.py"、"Dockerfile"、"docker-compose.yml"、".dockerignore"

#### app.py
```
from flask import Flask
from redis import Redis

app = Flask(__name__)
redis = Redis(host='redis', port=6379)

@app.route('/')
def hello():
    count = redis.incr('hits')
    return 'Hello World! 该页面已被访问 {} 次。\n'.format(count)

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
```

#### Dockerfile
```
FROM python:3.6-alpine
ADD . /code
WORKDIR /code
RUN pip install redis flask
CMD ["python", "app.py"]

```

#### docker-compose.yml
```
version: '3'
services:

  web:
    build: .
    ports:
     - "5000:5000"

  redis:
    image: "redis:alpine"

```
#### .dockerignore
```
英文QA bot.docx
Telegram Bot FQA.docx
README.md
debug.xlsx
.gitignore
test
```

3. use win10 cmd execution "docker-compose up"

### Observed result
is not work , but if i remove "英文QA bot.docx" (in  .dockerignore file) , is ok
### Expected result
Normal execution
### Stacktrace / full error message

```
Building tgbot
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 367, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 156, in build
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe8 in position 0: illegal multibyte sequence
[5880] Failed to execute script docker-compose
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
win10  edu 1903
docker desktop 2.2.0.3
