### ISSUE TITLE
Accept Circular dependency between containers

### ISSUE THREAD

**Issue by augnustin** [docker/compose#7239]
**Is your feature request related to a problem? Please describe.**

I have this config:

```
services:
  app:
    image: node:latest
    command: npm start
  nginx:
    image: nginx:latest
    depends_on: 
      - app
    ports:
      - 80:80
```

I set `nginx` depends on `app` since if `app` is not started, `nginx` doesn't work.

But in my local environment, I want to have an interactive console to being able to run commands in my working environment.

Hence `docker-compose run --rm --service-ports app bash` is the way to go. There, I can for instance `npm install`, `rm cache_files` etc.

But if I do that, `nginx` is not started and the port 80 is not opened. 

**Describe the solution you'd like**

I suggest to allow:

```
services:
  app:
    image: node:latest
    command: npm start
    depends_on: 
      - nginx
  nginx:
    image: nginx:latest
    depends_on: 
      - app
```

So that if `app` is started, `nginx` also is and the other way round. 

The circular dependency thing doesn't seem to be such a thing: when looking at the `depends_on` list, if it is started, do nothing, otherwise start it. There could be an issue when stopping a service, but either `docker-compose` could remember which service started the other so that children get closed in the meantime, or do nothing is also a valid solution : it is not a big deal if my DB is not shut down after I stop my app afterall.

I read somewhere that `depends_on` has to do with networking, which may have implications I don't anticipate. If there really is something blocking there, one could imagine another key like `start_with`, which would simply handle the start behavior, not the dependency one.

**Describe alternatives you've considered**

1. I can add to `docker-compose.override.yml` a port to `app`:

```
services:
  app:
   ports:
     - 80:3000
```

But then I need to switch every time I change from `docker-compose run` to `docker-compose up` (which is still very useful to be closer to prod config). This is a pain and brings much confusion.

2. Another solution is to always `docker-compose up` and then `docker-compose exec app bash` ([which is buggy](https://github.com/docker/compose/issues/7228)) to have the interactive terminal, but usually changes require a server restart, which means I need to

```
docker-compose restart app
```
in another terminal, and it closes my `docker-compose exec` session (as the container is stopped), so that's way too many actions for a simple server config change.

3. Another solution I looked for would have been to being able to have an interactive terminal when running `docker-compose up`. I looked at the `tty: true` option, but apparently it is not meant to do what I'd like: https://github.com/docker/compose/issues/5741

So I guess I need to stick with `docker-compose run`.

4. Finally, I could imagine having the following `docker-compose.override.yml`

```
services:
  app:
    depends_on: 
      - nginx
  nginx:
    depends_on: NONE
```

so that in local environment, the dependency in switched. I did open an issue to being able to remove key with overrides, but it doesn't seem to be approved for now: https://github.com/docker/compose/issues/7231

So for now, I can't find any decent solution. :disappointed:
