### ISSUE TITLE
docker-compose with buildkit does not insert container labels

### ISSUE THREAD

**Issue by sanderegg** [docker/compose#7242]
## Description of the issue
using the example from [https://docs.docker.com/compose/gettingstarted/](https://docs.docker.com/compose/gettingstarted/) with a modified compose file using in particular ```version: '3.7'``` and adding some labels in the ```build``` such as my compose file looks like this:
```
version: '3.7'
services:
  web:
    build: 
      context: ./
      labels:
        some_label: "I am the label"
    ports:
      - "5000:5000"    
  redis:
    image: "redis:alpine"
```
Basically in normal mode everything works well and the labels are added to the docker image.
In buildkit mode (with both DOCKER_BUILDKIT=1 and COMPOSE_DOCKER_CLI_BUILD=1) the labels are nowhere.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.3, build d4d1b42b
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  redis:
    image: redis:alpine
  web:
    build:
      context: /home/sanderegg/dev/github/cookiecutter-osparc-service/test
      labels:
        some_label: I am a label
    ports:
    - published: 5000
      target: 5000
version: '3.7'
```

## Steps to reproduce the issue

1. set-up he example as in [https://docs.docker.com/compose/gettingstarted/](https://docs.docker.com/compose/gettingstarted/)
2. modify the docker-compose file as above
3. enable docker buildkit and compose
4. ```
docker-compose -f docker-compose.yml build
docker inspect test_web
```

### Observed result
no labels when buildkit is enabled, labels present when compose buildkit is disabled.

### Expected result
labels should be there in both cases

### Stacktrace / full error message

```
(paste here)
```

## Additional information
ubuntu disco
OS version / distribution, `docker-compose` install method, etc.
