### ISSUE TITLE
docker-compose name resolution on windows server arbitrarily does not work 

### ISSUE THREAD

**Issue by yamac-kurtulus** [docker/compose#7250]
Hi,
I am using docker EE with compose on a Windows Server 2019 machine version 1809 on a Virtual Machine. I arbitrarily have problems accessing the containers using service names on docker-compose. I cannot use swarm because for some reason, I get BSOD at random times.

## Description of the issue
I am running compose for a number of services using 3 different environments on the same machine: `staging`, `production` and `development`. They are isolated by external networks called `staging_internal`, `production_internal`, `development_internal` respectively. Finally a traefik container defined outside of the app's docker-compose file connected to these networks handles external access (although I don't think this is relevant). 

For the sake of simplicity, i will focus on 2 services. These are named `coreservice` and `web`. Both are .net-core projects. `web` is the front-end and `coreservice` is the back-end. `web` calls `coreservice` in this fashion: `http://coreservice/foo/bar` However, it cannot resolve the container on the `production` and `staging` environment at the moment. For now, development environment using network `development_internal` resolves fine. Before this, I had the same setup but at that time, only `staging` environment was malfunctioning and the others were fine. I have deleted and recreated the networks and now the issue spreaded also to production. This seems so arbitrary. 

I have created the networks using command: `docker network create -d nat --attachable <network-name>` without specifying subnet, IP range, etc. (and i don't want to if possible). I can see the containers are correctly attached to networks both using `docker network inspect` and `docker container inspect` Also, I can ping containers on same net using IP address. 

On another attempt, I have tried specifying hostname in docker-compose, in that case my containers were able to access containers outside the network, weirdly, using IP6. This could be used as a workaround but involves setting hostnames for each environment in my appsettings.json. 

Has anyone encountered such a problem?

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
```
networks:
  default:
    external: true
    name: ${envname}_internal
	
services:
  coreservice:
    build:
      context: C:\workspace\src
      dockerfile: ./CoreService/CoreService/Dockerfile
    image: globalwebpay/coreservice:latest
  
  web:
    build:
      context: C:\workspace\src
      dockerfile: ./Web/Web/Dockerfile
    depends_on:
    - coreservice
    image: globalwebpay/web:latest	  
version: '3.7'
```

## Steps to reproduce the issue

1. Create 3 external, attachable nat networks.
2. Create 3 compose files with at least 2 services using nanoserver image, representing different environments. Default network for each should be the networks created in step 1
3. Start traefik instance and connect it to all 3 networks
4. Start compose files with different `COMPOSE_PROJECT_NAME` (or using -p option)
5. `docker exec` into app containers and ping or curl using service name
