### ISSUE TITLE
Networks not merged when trying to override settings

### ISSUE THREAD

**Issue by shiz0** [docker/compose#7271]
Hello everyone.
I stumbled upon this today, when I tried to disable IPv6 for a custom network in another project.
I hope this is the right place for this. There are similiar issues which may be related, but all marked as closed/fixed.

## Description of the issue
Networks not merged when trying to override settings, instead they are overwritten/deleted
## Context information (for bug reports)
I am trying to disable IPv6 for the networks defined here:
https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml
via override file.
**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

1.  Define networks in compose.yml (or use the one from mailcow)
```
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mailcow
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
```
2.  Create override file
```
version: '2.1'

networks:
  mailcow-network:
    enable_ipv6: false
```
3.  Run docker.compose config

### Observed result
networks:
  mailcow-network:
    enable_ipv6: false
services:
[...]

### Expected result
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mailcow
    enable_ipv6: false
    ipam:
      config:
      - subnet: 172.22.1.0/24
      - subnet: fd4d:6169:6c63:6f77::/64
      driver: default
services:
[...]

## Additional information
Tested on Ubuntu Server 18.04 LTS
