### ISSUE TITLE
Gelf driver not working

### ISSUE THREAD

**Issue by muhammedOzbilici** [docker/compose#7275]
I added logging driver info to compose.yml

```
 logging:
      driver: gelf
      options:
        gelf-address: "tcp://graylogHost:graylogPort"
```

When container trying to start and if there is some error (for example JVM argument syntax error on purpose) that causing container start failure, I can't see error logs on Graylog stream. If container runs correctly, I can see every logs on graylog stream.

Docker Community version does not support gelf driver ?

> Client: Docker Engine - Community
>  Version:           19.03.1
>  API version:       1.40
>  Go version:        go1.12.5
