### ISSUE TITLE
Docker compose creating volume from windows to linux ?

### ISSUE THREAD

**Issue by medmehdi28** [docker/compose#7285]
Hi, I am installing a mysql container and I want it to take my datas from my windows host machine.
Here is the compose file I have writed, but it doesnt recognize tha name variable:

```
version: "3.7"
services:
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - type: volume
          source: C:\ProgramData\MySQL\MySQL Server 8.0\Data\test1
          target: /var/lib/mysql/
          name: sqldata
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  sqldata:
```

Ive also tried

```
volumes:
        - C:\ProgramData\MySQL\MySQL Server 8.0\Data\test1:/var/lib/mysql/
```
Ive already enabled `$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1` to accept window's format path but I cant make it work
