### ISSUE TITLE
Allow specifying the name of the docker-compose environment file other than `.env`

### ISSUE THREAD

**Issue by kurtwheeler** [docker/compose#7289]
## Description of the issue

`.env` is a very generic filename. There's nothing about it that signifies that it is for docker-compose.

I want to have it included in my repo so that it can use sane defaults locally for environment variables that I want to configure differently in production. However in the context of the rest of my project, I don't think the name is specific enough. I'd like to name it `docker-compose.env` in my project.

However the [documentation for it](https://docs.docker.com/compose/env-file/) says 

> Compose supports declaring default environment variables in an environment file named **.env** placed in the folder where the docker-compose command is executed (current working directory).

So my question is, would it be possible to add a top level property to the docker-compose YAML file such as `envrionement-file:` that would allow specifying the name of the env file to be used? I think it would also make sense as a command line argument, although I'm less personally interested in that.

**Comment by rrdlpl** [comment]
Why is not the env_file option enough? 

https://docs.docker.com/compose/environment-variables/




```
web:
  env_file:
    - web-variables.env
```

**Comment by kurtwheeler** [comment]
I think it is! I did not manage to find that in the docs but it looks like it's what I was looking for.

Thank you!

**Comment by kurtwheeler** [comment]
Sorry, I closed this too soon.

@rrdlpl the `env_file` option controls what env file the _container_ uses, I want an option to configure what file _docker-compose_ uses. As far as I can tell it will only use env variables from a file named `.env`.

**Comment by thejimnicholson** [comment]
There also should be a way to make docker-compose **not** use an env-file, and that should be the default. Too many tool use '.env', and there is little agreement on them regarding format (whitespace vs not, etc.)

**Comment by shaunco** [comment]
+1

`env_file` should be a valid top-level section, along-side `version`, `services`, `networks`, `volumes`, `secrets`, `configs`, and extensions starting with `x-` so that multiple env files can be applied to the docker-compose rather than just the service containers, otherwise this still requires a separate `.env` file:
```yml
mongodb:
    env_file: 
      - .env.base
      - .env.local
    image: 'bitnami/mongodb:${MONGO_VERSION}'
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongodb-data:/bitnami/mongodb
    networks:
      - my-network
```

as `docker-compose` can't find `MONGO_VERSION` or `MONGO_PORT` that are defined in `.env.base` or `.env.local`.

Having this at a top-level, where is applies to the docker-compose, would allow for the following with no separate `.env`:
```yml
env_file: 
  - .env.base
  - .env.local

mongodb:
    image: 'bitnami/mongodb:${MONGO_VERSION}'
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongodb-data:/bitnami/mongodb
    networks:
      - my-network
```

Alternatively, the `env_file` section of a `service` entry should be processed before all other sections so that other sections can use environment variables from `env_file`.

**Comment by manaphp** [comment]
> There also should be a way to make docker-compose **not** use an env-file, and that should be the default. Too many tool use '.env', and there is little agreement on them regarding format (whitespace vs not, etc.)

.docker-compose is intuitive

**Comment by RafaelWO** [comment]
I would also be very interested in the feature of a top level `env_file` in a compose file, as @shaunco described it. 

The reason why I cannot use the service level `env_file` is that this "loads" all environment variables from the specified file into the container while I want a behaviour similar to the `.env` file where I can specify the required variables within the service level `environment` key.

**Comment by kiler129** [comment]
I came here with a huge surprise of how `env_file` behaves. With a bigger stack, where e.g. cross-service encryption keys need to be shared it's close to useless if it doesn't load globally.

A quick example could be a stack using a PostgreSQL database, where credentials need to be known by the app and the db itself. Look at this abbrivaited example below:

```yaml
version: "3"
services:
    teslamate:
        image: teslamate/teslamate:latest
        env_file:
            - shared_pgsql.secrets
        environment:
            - DATABASE_USER=${PG_SHARED_USER}
            - DATABASE_PASS=${PG_SHARED_PASS}
            - DATABASE_NAME=${PG_SHARED_DBNAME}
            - DATABASE_HOST=database

    database:
        image: postgres:15
        environment:
            - POSTGRES_USER=${PG_SHARED_USER}
            - POSTGRES_PASSWORD=${PG_SHARED_PASS}
            - POSTGRES_DB=${PG_SHARED_DBNAME}
        env_file:
            - shared_pgsql.secrets
```

Let's analyze our options here:
1. **Using [`env_file` on the service level](https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute)**
    - For the starters, it will *not* work in this case, in case it's not obvious. The variables are loaded directly into the container's context
    - This is somewhat confusing at first, but there's a logic behind it. It would be great if variables were usable in the `environment` and other sections within a given service as well, but it may be difficult to implement.
    - Some suggest to name variables in the same way as the container authors did. While it will make it work, it's not a solution if the same environment file is to be reused across multiple services that most likely will not use the same variable names (and why would they?)
   
3. **Using custom [`entrypoint`](https://docs.docker.com/compose/compose-file/compose-file-v3/#entrypoint) to "rename" variables**
    - With the ability to customize entrypoint is great, I see this more as a hack. A working one, indeed, but requiring custom code to be maintained.
    - This creates a porcelain scenario where we're replacing a part of a container which is usually managed by the author. In certain cases it can even put us in a no-support scenario if the container authors don't explicitly allow entrypoint overwrite.
    - This is great with 1-2 services here and there, but whenever possible I try to treat my infrastructure like [cattle not pets](https://devops.stackexchange.com/a/654)
5. **Using [`--env-file` in `docker compose`](https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-with---env-file) commands**
    - It is a solution that works great, is supported by docker officially and "the way to go". It's clean-ish as well.
    - It carries significant downside of needing to specify the `--env-file` every time a command is called. This is not only not ideal but creates a case of [tribal knowledge](https://devblogs.microsoft.com/premier-developer/tribal-knowledge-the-anti-devops-culture/), which is a dev ops antipattern.
    - You can naturally create a `docker-compose.sh` file for a given `docker-compose.yaml` stack, but again this puts us into a scenario of solving platform's shortcomings with custom scripts.
7. **Using [Docker secrets](https://docs.docker.com/engine/swarm/secrets/)**
    - I couldn't ignore this part of the Docker ecosystem, as it's ostensibly the best and recommended method of managing secret values. However, it falls short on multiple levels.
    - The assumptions imposed by Docker secrets work only if the service container was designed with secrets in mind, i.e. is able to read these secrets from **file**. Unfortunately, looking at the tools I utilize very few support that option. While this can be fixed with a custom entrypoint scripts...... see pt. 3.
    - The Docker secrets comes with another big downside: unlike environment variables file, it ~~only supports~~ forces a 1 file = 1 secret approach. This can quickly create a headache.


To me it's clear that solution presented by [@shaunco](https://github.com/shaunco) is the real one here.
