### ISSUE TITLE
Using .env behaves differently than env_file in compose file?

### ISSUE THREAD

**Issue by ravensorb** [docker/compose#7302]
I am not sure if this is a bug or a feature request.

I am using a custom env file via the env_file tag - the issue is, the variables in there are not being used within the compose file itself (they only seem to be passed to the Dockerfile)

In the following example I have a file called "portainer.env" that contains the following
```
ENV=dev
PLATFORM=linux
```
and then here is the compose file
```
version: "3.3"

services:

  portainer:
      image: portainer/portainer
      container_name: "portainer"
      restart: always
      env_file:
        - portainer.env
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data:/data
      networks:
        - web
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`) || Host(`portainer.${ENV}.${PLATFORM}.docker.home.local`)"
        - "traefik.http.routers.portainer.entrypoints=web"
        # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
        # This is not necessary if you set your default network in Traefik config/parameters
        # - "traefik.docker.network=your-traefik-network-name"

networks: 
  web:
    external: true
```
This fails saying that DEV and PLATFORM are not defined.  If I create a .env file with those variables -- everything works correctly.

So bug? or Feature Request?
