### ISSUE TITLE
docker-compose ignores credential_spec

### ISSUE THREAD

**Issue by pompi-stefana** [docker/compose#7303]
## Description of the issue
Using the credential_spec in compose file version (3.8) does not to work.
In the compose file I have the following:
```
credential_spec:
      file: file://dev_gmsa.json
```
Using docker inspect on the running container, I get `null` for security_opt:
```
"SecurityOpt": null
```

When using docker run with `--security-opt "credentialspec=file://dev_gmsa.json"` arguments, docker inspect gives the following output:
```
"SecurityOpt": [
                "credentialspec=file://dev_gmsa.json"
            ],
```
## Context information (for bug reports)
I use this setup for using Windows Authentication in a .net core app (windows containers).
It works fine with docker run but cannot get this to work with docker-compose because the credentialspec file is not being passed to the container.

**Output of `docker-compose version`**
```
docker-compose version 1.26.0-rc3, build 46118bc5
```

**Output of `docker version`**
```
Docker version 19.03.8, build afacb8b
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  gateway.api:
    build:
      context: D:\gateway
      dockerfile: Gateway.Api\Dockerfile
    credential_spec:
      file: file://dev_gmsa.json
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
    hostname: dev_gmsa
    image: gatewayapi
    ports:
    - published: 60366
      target: 80
    - target: 80
    - published: 60365
      target: 443
    - target: 443
    volumes:
    - C:\Users\user\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
    - C:\Users\user\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
version: '3.8'

```

## Steps to reproduce the issue

1. Set schema version 3.8 for compose file
2. Use docker-compose version 1.26.0-rc3 which has support for schema version 3.8
3. Specify credential_spec file in compose file
4. Build and run the container
5. Run docker inspect on the container
6. Check the value for security_opt

### Observed result
The security_opt is null.

### Expected result
security_opt should be not null, and contain a value for credentialspec (the file name specified) in compose file.

### Stacktrace / full error message
No error messages!

## Additional information
Docker desktop on Windows 10, with windows containers. docker-compose manually installed in the global path.
