### ISSUE TITLE
Docker compose wont detect change on latest version

### ISSUE THREAD

**Issue by artoodeeto** [docker/compose#7308]
## Description of the issue
On the latest version when I change a file docker-compose won't detect any changes. I resulted to downgrade from the latest to `2.2.0.0` version

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  app_network: {}
services:
  db:
    build:
      context: /Users/raphaelgako/Documents/aRtoo/dev_p/ggpo/server/db
    environment:
      API_VERSION: v1
      MYSQL_DATABASE: development_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      NODE_ENV: development
      OVERNIGHT_JWT_EXP: '''3h'''
      OVERNIGHT_JWT_SECRET: '''dis iss sikrit misig'''
      OVERNIGHT_LOGGER_FILEPATH: ./logs/route.log
      OVERNIGHT_LOGGER_MODE: FILE
      PREFIX: api
      SALT_ROUNDS: '11'
      TOKEN_EXP: '10800000'
      TYPEORM_CONNECTION: mysql
      TYPEORM_DATABASE: development_db
      TYPEORM_ENTITIES: src/models/**/*.ts
      TYPEORM_ENTITIES_DIR: src/models
      TYPEORM_HOST: db
      TYPEORM_LOGGING: "true"
      TYPEORM_MAX_QUERY_EXECUTION_TIME: '2000'
      TYPEORM_MIGRATIONS: db/migrations/**/*.ts
      TYPEORM_MIGRATIONS_DIR: db/migrations
      TYPEORM_PASSWORD: password
      TYPEORM_PORT: '3306'
      TYPEORM_SUBSCRIBERS: src/subscribers/**/*.ts
      TYPEORM_SUBSCRIBERS_DIR: src/subscribers
      TYPEORM_USERNAME: root
    networks:
      app_network: null
    ports:
    - published: 3306
      target: 3306
    restart: always
  server:
    build:
      context: /Users/raphaelgako/Documents/aRtoo/dev_p/ggpo/server
    command:
    - npm
    - run
    - dev
    depends_on:
    - db
    networks:
      app_network: null
    ports:
    - published: 8000
      target: 8000
    restart: always
    volumes:
    - /server/node_modules
    - source: /Users/raphaelgako/Documents/aRtoo/dev_p/ggpo/server
      target: /server
      type: bind
version: '3.3'
volumes:
  app_volume: {}
```

## Steps to reproduce the issue

1. Upgrade to the latest version
2. Make a change in the file
3.  Save the file
4. Docker won't load the changes

### Observed result
So on the latest version when I changed a file and run the command `docker exec -it <container ID> bash` I can see the changes, but since I'm using typescript with [ts-node-dev](https://www.npmjs.com/package/ts-node-dev) it should load or recompile my ts file but its not doing it. It's weird though because I can see it inside docker. I'm not sure if it's from `ts-node-dev` but I just downgraded docker and it was working again.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
```
OS: macOS 10.15.3
```
