### ISSUE TITLE
Addressing containers by 'hostname' attribute in Compose gives undefined behavior

### ISSUE THREAD

**Issue by FrankAtHexagon** [docker/compose#7317]
### Expected behavior

In Compose, containers addressing other containers by their `hostname` attribute will receive a DNS lookup error.

### Actual behavior

In Compose, containers addressing other containers by their `hostname` attribute behave differently depending on the host machine's network configuration. Some lookups succeed, and others fail, based on the network configuration.

### Information

I first noticed this problem when I began working from home. If my machine is connected to the corporate network via hardwired connection, the `hostname` lookup always succeeds. If my machine is connected to my home network with a VPN to the corporate network, the `hostname` lookup always succeeds. If my machine is in airplane mode, the `hostname` lookup always succeeds. If my machine is connected just to my home network, the `hostname` lookup never succeeds.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  default:
    external: true
    name: nat
services:
  rabbitmq_service:
    container_name: rabbitmq
    hostname: rabbit-test
    image: rabbitmq3_8_2:latest
    isolation: hyperV
  test-controller:
    container_name: controller
    environment:
      RabbitMQConnection: rabbit-test
    image: mytest_controller
    isolation: hyperV
    ports:
    - published: 16000
      target: 80
    - published: 16500
      target: 443
  test-reader:
    container_name: reader
    environment:
      RabbitMQConnection: rabbit-test
    image: mytest-reader
    isolation: hyperV
version: '3.5'
```

## Steps to reproduce the issue

1. Define a Docker Compose file similar to the one below:
```yaml
  version: '3.5'

  services:
    apple:
      image: apple:latest
      isolation: hyperV
      hostname: my-apple
    orange:
      image: orange:latest
      isolation: hyperV
      environment:
        - AppleConnection=my-apple
    banana:
      image: banana:latest
      isolation: hyperV
      environment:
        - AppleConnection=my-apple
```
2. Assume that the 'orange' and 'banana' containers access the environment variable `AppleConnection` in order to determine the hostname to use when accessing the 'apple' container. Note that the correct value for `AppleConnection` should be the service name `apple` instead of the defined hostname `my-apple`
3. Run the Docker Compose file

### Observed result

Depending on the network configuration of the machine, 'orange' and 'banana' may or may not be able to connect to 'apple' using the hostname `my-apple`.

### Expected result

Regardless of the network configuration of the machine, 'orange' and 'banana' will _not_ be able to connect to 'apple' using the hostname `my-apple`.

## Additional information

  - OS Version: Windows 10 Version 1909
  - Docker Desktop Version: 19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
