### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] wrong version number

### ISSUE THREAD

**Issue by lamba92** [docker/compose#7334]
## Description of the issue
I am trying to deploy a docker-compose.yml to a remote rpi4 with Docker from a Win10 Home machine with Docker Toolbox installed. It was working without problems until after a reboot of Win10 this error started appearing:
```
SSL error: HTTPSConnectionPool(host='192.168.1.158', port=2376): Max retries exceeded with url: /v1.38/networks/cassandrasparkdocker_default (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)'),))
```
The build does not even starts, this error is outputted immediately which leads me to believe that the error is on my local configuration and not on the remote host.

Also I am working with the IntelliJ IDEA Docker plugin which sets up remote hosts automatically.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
Remote Raspberry Pi 4:
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:26:27 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:24:59 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Local Win10 Home:
```
Client:
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Wed Jul 31 15:18:18 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  spark-master:
    build:
      context: D:\Progetti\cassandra-spark-docker\spark-base
    command: start-master.sh
    container_name: spark-master
    init: true
    ports:
    - published: 8080
      target: 8080
  spark-worker:
    build:
      context: D:\Progetti\cassandra-spark-docker\spark-base
    command:
    - start-slave.sh
    - spark://spark-master:8080
    container_name: spark-worker
    depends_on:
    - spark-master
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 200MB
    init: true
version: '3.7'
```

There are few other similar issues like #7334 but they asks to remove environmental variables which I do not have (at least in the Windows 10 local machine).
