### ISSUE TITLE
compose crashes on duplicate cache_from, while docker not

### ISSUE THREAD

**Issue by adaamz** [docker/compose#7342]
Hi,
why is it not possible to use 2 same images for cache_from? Standard docker has no problem with this command `TAG=latest docker build --cache-from=a:$(TAG) --cache-from=a:latest -t a:latest a`.
While when I have this compose file
```yml
version: '3.2'
services:
    a:
        build:
            cache_from:
                - a:${TAG}
                - a:latest
            context: a
            dockerfile: a/Dockerfile
         image: a:${TAG}
```
it gives me error about duplicate items in cache_from.

Can this behavior be changed?
Thanks.
