### ISSUE TITLE
Extended config build context has wrong path of current dir

### ISSUE THREAD

**Issue by holms** [docker/compose#7350]
## Description of the issue

When using config extension there's an issue finding local Dockerfile

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0-rc3, build 46118bc5

```

**Output of `docker version`**
```
Docker version 19.03.1, build 74b1e89
```
**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  aerospike:
    container_name: aerospike
    image: aerospike:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.core.rule: Host(`aerospike.docker.localhost`)
    ports:
    - published: 3000
      target: 3000
    - published: 3001
      target: 3001
    - published: 3002
      target: 3002
    - published: 3003
      target: 3003
    volumes:
    - /home/holms/Dev/contracts/setupad/app-prebid-config/aerospike/aerospike.conf:/opt/aerospike/etc/aerospike.conf:rw
  app-prebid-config:
    build:
      context: /home/holms/Dev/contracts/setupad/app-prebid-config
      dockerfile: Dockerfile
      target: dev
    cap_add:
    - SYS_PTRACE
    command: /bin/sh -c "while sleep 1000; do:; done"
    container_name: app-prebid-config
    depends_on:
    - aerospike
    - redis
    - traefik
    environment:
      AEROSPIKE_HOST: aerospike
      AEROSPIKE_PORT: 3000
    labels:
      traefik.enable: "true"
      traefik.http.routers.core.rule: Host(`app-prebid-config.docker.localhost`)
    security_opt:
    - seccomp:unconfined
    volumes:
    - /home/holms/Dev/contracts/setupad/app-prebid-config/app:/app/prebid-config:rw
    - /home/holms/Dev/contracts/setupad/app-prebid-config/app:/workspace:cached
  redis:
    container_name: redis
    image: redis:latest
  traefik:
    command:
    - --log.level=DEBUG
    - --api.insecure=true
    - --api.dashboard=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    container_name: traefik
    image: traefik:v2.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`traefik.docker.localhost`)
    ports:
    - published: 80
      target: 80
    - published: 8080
      target: 8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.7'


```

Tree  for a folder:

```
holms@debian ~/D/c/s/app-prebid-config> tree .devcontainer/
.devcontainer/
├── devcontainer.json
├── docker-compose.yml
└── Dockerfile

0 directories, 5 files
```

## Steps to reproduce the issue

1. Try this command: `docker-compose  --project-name app-prebid-config -f docker-compose.yml -f .devcontainer/docker-compose.yml  build`

### Observed result

Failing to find Dockerfile

### Expected result

Should start building docker image

### Stacktrace / full error message

```
holms@debian ~/D/c/s/app-prebid-config> docker-compose  --project-name app-prebid-config -f docker-compose.yml -f .devcontainer/docker-compose.yml  build
Building app-prebid-config
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

## Additional information

* Install RC from github to /usr/local/bin
* Using latest Debian
* This is just a standard setup which is used in vscode. 
* As you've already noticed, first config contains `target:dev`, I've tried to remove it and I still have the same error.
* Also `build context` somehow stays the local folder of a first compose config file, why it didn't override it?

**Comment by holms** [comment]
Ok I'm pretty much extremely sure that it's taking path of first config file for `build context` instead of taking CWD of the config which overrides the context. Why..?

Actually setting in extended file the path of the folder where it lies works:

```
version: '3.7'
services:
    app-prebid-config:
        build:
            context: ./.devcontainer/
            dockerfile: Dockerfile
        volumes:
            - ./app:/workspace:cached
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        command: /bin/sh -c "while sleep 1000; do:; done"

```

Also I've had to remove `target: dev` as I don't know how to set it to null. In main config I'd like to use different Dockerfile with different  target in it
