### ISSUE TITLE
logs keeps terminal  color even after end of the log.

### ISSUE THREAD

**Issue by YuseiIto** [docker/compose#7354]
## Description of the issue
When I run `docker-compose logs` on the project which puts colored logs on stdout, the later prompt also gets colored. 
 
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 201
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  default:
    external:
      name: shared
services:
  letsencrypt:
    container_name: letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/yuseiito/proxy/certs:/etc/nginx/certs:rw
    volumes_from:
    - service:proxy:rw
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    logging:
      options:
        max-file: '10'
        max-size: 5m
    ports:
    - 80:80/tcp
    - 443:443/tcp
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /home/yuseiito/proxy/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
version: '2.0'
```

## Steps to reproduce the issue

1. `docker-compose up`
2. `docker-compose logs`

### Observed result
Prompt gets colored even after the logs.

### Expected result
Default color prompt.

I think `docker-compse logs` must put `\033[0m` after end of the log(before return).

### Stacktrace / full error message
No error messages. (This is not an error. just a `bug`)

## Additional information
Linux/CentOS 7
