### ISSUE TITLE
Link container's with a network, first request always 404

### ISSUE THREAD

**Issue by MJTheOne** [docker/compose#7366]
## Description of the issue
Because I'm working on 2 API's that need to communicate with each other I've created a network between the two of them and they can ping each other by (generated) hostname just fine.

API-1 does a POST call to API-2, but **always** the first request will be a 404, swiftly after the first request the POST will be processed normally.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
```

**Output of `docker version`**
```
Docker version 19.03.8, build afacb8b
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
API-1:
networks:
  default:
    name: app-registration-network
services:
  php:
    environment:
      APP_ENV: dev
      APP_SECRET: SECRET
      IDP_API_URL: http://idp-api_web_1
      LOGINCLUSTER_URL: URL
      PHP_IDE_CONFIG: serverName=manager-api.docker
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1
    image: COMPANY_NAME/php:7.2-dev (Based on php:7.2.14-fpm-stretch)
    volumes:
    - PROJECT_DIR:/app:rw
  web:
    image: COMPANY_NAME/nginx:symfony4 (Based on nginx:1.17.6-alpine)
    ports:
    - published: 7002
      target: 80
    - published: 7402
      target: 443
    volumes:
    - PROJECT_DIR:/app:rw
version: '3.7'

API-2:
networks:
  default:
    external: true
    name: app-registration-network
services:
  php:
    environment:
      APP_ENV: dev
      APP_SECRET: SECRET
      CORS_ALLOW_ORIGIN: ^https?://localhost:?[0-9]*$$
      DATABASE_URL: MYSQL
      PHP_IDE_CONFIG: serverName=idp-api.docker
      SMS_URL: URL
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1
    image: COMPANY_NAME/php:7.2-dev (Based on php:7.2.14-fpm-stretch)
    volumes:
    - PROJECT_DIR_2:/app:rw
  web:
    image: COMPANY_NAME/nginx:symfony4 (Based on nginx:1.17.6-alpine)
    ports:
    - published: 7001
      target: 80
    - published: 7401
      target: 443
    volumes:
    - PROJECT_DIR_2:/app:rw
version: '3.7'
```

## Steps to reproduce the issue

1. Set up an API in both containers with the intent of one POSTing to the other
2. Use Postman for the POST request to API-1 (which will be transferred to API-2)
3. Profit?

### Observed result
The first request will always be a 404

### Expected result
The first request will NOT always be a 404

## Additional information

Windows 10 Pro
Version 1909
Build 18363.720
