### ISSUE TITLE
A long project name breaks networking between containers

### ISSUE THREAD

**Issue by NikolayMetchev** [docker/compose#7379]
## Description of the issue
If you specify a long project name for the `-p` parameter then the networking from one docker container to another doesn't work.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  kafka:
    container_name: kafka
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: '0'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    hostname: kafka
    image: confluentinc/cp-enterprise-kafka:latest
    ports:
    - target: 9092
  zookeeper:
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
    - target: 2181
version: '3.7'
```

## Steps to reproduce the issue
if you run `docker-compose -p mynetwork up -d` then with the given config above you can see that kafka can speak to zookeeper and comes up no problem. If however you run with the following command: `docker-compose -p mynetwork1234567890123456789012345678901234567890123456789012345678901234567890 up -d` then kafka is no longer able to connect to zookeper and dies on startup.

## Additional information

OS version / distribution, `docker-compose` install method, etc.
MacOS Catalina Version 10.15.4
