### ISSUE TITLE
WSL composer path error

### ISSUE THREAD

**Issue by Terkea** [docker/compose#7396]
## Description of the issue
I'm trying to split up my application into two docker services - frontend and backend, where my project layout looks similar to this.

```
| frontend
|  - ...
|  - Dockerfile.prod
| backend
|  - ...
|  - Dockerfile.prod
| docker-compose.yml
```

What bothers me is that when I'm running the images standalone everything works flawlessly, but when I try to throw it into the `docker-compose.yml` that error kicks in.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  backend:
    build:
      context: \\wsl$$\Ubuntu\home\terkea\django_react_template
      dockerfile: django/Dockerfile
    command: python django/manage.py runserver 0.0.0.0:8000
    container_name: django-dev
    ports:
    - 8001:8000/tcp
    volumes:
    - \\wsl$\Ubuntu\home\terkea\django_react_template:/code:rw
  frontend:
    build:
      context: \\wsl$$\Ubuntu\home\terkea\django_react_template
      dockerfile: react/Dockerfile
    container_name: react-dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
    - 3001:3000/tcp
version: '3.0'
```

### Observed result
Strange thing is that when you run just the same composer on the windows docker version it seems to be working just fine.

### Expected result
I was expecting it to create the containers and run the services.

### Stacktrace / full error message

```
Building frontend
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 351, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 148, in build
TypeError: You must specify a directory to build in path
[15892] Failed to execute script docker-compose
```

## Additional information
Windows 10 pro, WSL
