### ISSUE TITLE
NEVER HAD THIS ISSUE: "image for service has been removed"; "pull access denied" 

### ISSUE THREAD

**Issue by danielmaartens** [docker/compose#7406]
@shin- @aanand @bfirsh @mnowster 

# Description of the issue
I have always been able to run the following commands with no issue. I did not need to log in to docker or anything, but now I keep on getting this error:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/49619761/80494961-930d9880-8967-11ea-91b5-80e5d4b9e1e9.png">

This worked a couple of months ago (which was the last time I had to run these commands for this specific project). I had to recently deploy this app again on a new digital ocean server and now I get the above error with all my dockerized applications.

What exactly can cause this change in behaviour ?

***Here are the commands and relevant files:***

```
docker build -t ipic/site-new .
docker-compose up -d
```

***Relevant Files***

`docker-compose.yml`
```
version: "3.0"

services:
  ipic-site:
    container_name: ipic-site
    image: ipic/site-new:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 8080:8080
      - 80:80
```

`Dockerfile`
```
FROM php:7-fpm-alpine

RUN mkdir -p app
WORKDIR /app

RUN apk --update add wget \
  curl \
  git \
  grep \
  build-base \
  libmemcached-dev \
  libmcrypt-dev \
  libxml2-dev \
  imagemagick-dev \
  pcre-dev \
  libtool \
  make \
  autoconf \
  g++ \
  cyrus-sasl-dev \
  libgsasl-dev \
  supervisor \
  nodejs \
  npm \
  openssl \
  zip \
  unzip \
  git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN echo "Installing dependencies and setting up app... Get some coffee, this may take a while..."
RUN echo "Installing PHP extensions..."
RUN docker-php-ext-install mbstring pdo pdo_mysql >/dev/null 2>&1
RUN rm /var/cache/apk/*

COPY . /app
COPY .env /app/.env

RUN composer install
RUN npm install

RUN npm run prod

EXPOSE 80
EXPOSE 8080

CMD php artisan serve --host=0.0.0.0 --port=80
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b

```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  ipic-site:
    container_name: ipic-site
    environment:
      APP_DEBUG: "true"
      APP_ENV: prod
      APP_KEY: ''
      APP_NAME: Ipic Site
      APP_URL: http://ipicgroup.com
      AWS_ACCESS_KEY_ID: ''
      AWS_BUCKET: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ''
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      DB_CONNECTION: mysql
      DB_DATABASE: ipicgr_db1
      DB_HOST: sql2.jnb1.host-h.net
      DB_PASSWORD: d5f7y19F
      DB_USERNAME: ipicgr_1
      LOG_CHANNEL: stack
      MAIL_DRIVER: smtp
      MAIL_ENCRYPTION: 'null'
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PASSWORD: 'null'
      MAIL_PORT: '2525'
      MAIL_USERNAME: 'null'
      MIX_PUSHER_APP_CLUSTER: '"$${PUSHER_APP_CLUSTER}"'
      MIX_PUSHER_APP_KEY: '"$${PUSHER_APP_KEY}"'
      PUSHER_APP_CLUSTER: mt1
      PUSHER_APP_ID: ''
      PUSHER_APP_KEY: ''
      PUSHER_APP_SECRET: ''
      QUEUE_CONNECTION: sync
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: 'null'
      REDIS_PORT: '6379'
      SESSION_DRIVER: file
      SESSION_LIFETIME: '120'
    image: ipic/site-new:latest
    ports:
    - 8080:8080/tcp
    - 80:80/tcp
    restart: always
version: '3.0'

```

## Steps to reproduce the issue
1. run `git clone https://github.com/danielmaartens/ipic-site-laravel-vue`
2. make a copy of `env.example` and save as `.env`
2. Run `sh run.sh` in root directory.

### Observed result
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/49619761/80495609-6efe8700-8968-11ea-9740-88139c5925b3.png">

### Expected result
```
Successfully built <image id>
Successfully tagged ipic/site-new:latest
Sending build context to Docker daemon  <size>
```

Should not try to pull latest or have to log in. Should just successfully tag the built image as :latest and run the container.

## Additional information

OS: MacOS Mojave 10.14.5
