### ISSUE TITLE
Docker-compose master process memory consumption may grow indefinitely under right circumstances

### ISSUE THREAD

**Issue by rimas-kudelis** [docker/compose#7407]
## Description of the issue

I noticed today that at a certain point in time, the docker-compose master process (`docker-compose up`) was reported as consuming almost 6GB of memory, while normally its reported memory consumption is way below 1GB (e.g. around 50MB at the moment).

I suspect the reason for this was that I was running docker-compose in foreground, and at that very moment, the MySQL container was causing an insane amount of `mbind: Operation not permitted` messages (docker-library/mysql#303) being output every second (by insane I mean probably around several thousand of these messages each second).

In other words, I suspect that at least when run in foreground, docker-compose consumes more and more memory as long as containers generate output.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad0
docker-py version: 3.7.3
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:26:00 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:04:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~19.10.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  elasticsearch:
    environment:
      discovery.type: single-node
      http.cors.allow-credentials: "true"
      http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length,
        Authorization, Access-Control-Allow-Headers, Accept
      http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
      http.cors.allow-origin: '*'
      http.cors.enabled: "true"
    image: elasticsearch:7.6.2
    ports:
    - published: 9200
      target: 9200
    - published: 9300
      target: 9300
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - es-data:/usr/share/elasticsearch/data:rw
  kibana:
    image: kibana:7.6.2
    ports:
    - published: 5601
      target: 5601
  mailhog:
    environment:
      MH_STORAGE: maildir
    image: mailhog/mailhog:latest
    ports:
    - published: 8025
      target: 8025
    restart: always
    volumes:
    - /path/to/my/project/docker/mailhog/maildir:/maildir:rw,delegated
  mysql:
    cap_add:    # Added to workadound this issue
    - SYS_NICE  # Added to workadound this issue
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sylius
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: sylius
    image: mysql
    ports:
    - published: 3307
      target: 3306
    restart: always
    volumes:
    - mysql-data:/var/lib/mysql:rw
  nginx:
    build:
      context: /path/to/my/project
      target: sylius_nginx
    depends_on:
    - nodejs
    - php
    image: nordcode/nginx:project
    ports:
    - published: 80
      target: 80
    restart: always
    volumes:
    - /path/to/my/project/public:/srv/sylius/public:ro
    - public-media:/srv/sylius/public/media:ro,nocopy
    - vendor:/srv/sylius/vendor:rw,cached,nocopy
    - cache:/srv/sylius/var/cache:rw,cached,nocopy
  nodejs:
    build:
      context: /path/to/my/project
      target: sylius_nodejs
    depends_on:
    - php
    environment:
      GULP_ENV: dev
      PHP_HOST: php
      PHP_PORT: '9000'
    image: nordcode/nodejs:project
    ports:
    - published: 35729
      target: 35729
    restart: always
    volumes:
    - vendor:/srv/sylius/vendor:ro,cached,nocopy
    - /path/to/my/project/public:/srv/sylius/public:rw,delegated
  php:
    build:
      context: /path/to/my/project
      target: sylius_php
    depends_on:
    - elasticsearch
    - mysql
    - rabbitmq
    environment:
      APP_DEBUG: '1'
      APP_ENV: dev
      APP_SECRET: EDITME
      BLACKFIRE_CLIENT_ID: whatever
      BLACKFIRE_CLIENT_TOKEN: whatever
      MAILER_URL: smtp://localhost
      PHP_DATE_TIMEZONE: Europe/Vilnius
      PHP_EXTENSION_XDEBUG: '1'
      PHP_IDE_CONFIG: serverName=project.local
      PHP_INI_XDEBUG__REMOTE_PORT: '9000'
      XDEBUG_CONFIG: remote_autostart=1
    image: nordcode/php-7.4:project
    restart: always
    volumes:
    - /path/to/my/project:/srv/sylius:rw,cached
    - vendor:/srv/sylius/vendor:rw,cached,nocopy
    - cache:/srv/sylius/var/cache:rw,cached,nocopy
    - /path/to/my/project/public:/srv/sylius/public:rw,delegated
    - public-media:/srv/sylius/public/media:rw
  queuerunner:
    build:
      context: /path/to/my/project
      target: sylius_queuerunner
    depends_on:
    - mysql
    - rabbitmq
    environment:
      APP_DEBUG: '1'
      APP_ENV: dev
      APP_SECRET: EDITME
      BLACKFIRE_CLIENT_ID: whatever
      BLACKFIRE_CLIENT_TOKEN: whatever
      MAILER_URL: smtp://localhost
      PHP_DATE_TIMEZONE: Europe/Vilnius
      PHP_EXTENSION_XDEBUG: '1'
      PHP_HOST: php
      PHP_IDE_CONFIG: serverName=project.local
      PHP_INI_XDEBUG__REMOTE_PORT: '9000'
      PHP_PORT: '9000'
      XDEBUG_CONFIG: remote_autostart=1
    image: nordcode/queuerunner:project
    restart: always
    volumes:
    - /path/to/my/project:/srv/sylius:rw,cached
    - vendor:/srv/sylius/vendor:rw,cached,nocopy
    - cache:/srv/sylius/var/cache:rw,cached,nocopy
    - /path/to/my/project/public:/srv/sylius/public:rw,delegated
    - public-media:/srv/sylius/public/media:rw
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - published: 15672
      target: 15672
    restart: always
  thumbor:
    environment:
      FILE_LOADER_ROOT_PATH: /data/image
      LOADER: thumbor.loaders.file_loader
    image: apsl/thumbor
    ports:
    - published: 8000
      target: 8000
    restart: always
    volumes:
    - public-media:/data:ro,nocopy
    - thumbor-data:/data/storage:rw
version: '3.4'
volumes:
  cache: {}
  es-data: {}
  mysql-data: {}
  public-media: {}
  thumbor-data: {}
  vendor: {}
```

## Steps to reproduce the issue

1. in your container, run an application that continuously triggers `mbind: Operation not permitted` messages when running. Or perhaps just writes something into stdout repeatedly?
2. launch docker-compose in the foreground (without `-d`)
3. observe memory consumption

### Observed result

The memory consumption of docker-compose kept growing until I shut the pool down when it reached nearly 6GB

### Expected result

Memory consumption should have been limited.

### Stacktrace / full error message

N/A

## Additional information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

$ apt policy docker.io
docker.io:
  Įdiegta:    19.03.6-0ubuntu1~19.10.1
  Kandidatas: 19.03.6-0ubuntu1~19.10.1
  Versijų lentelė:
 *** 19.03.6-0ubuntu1~19.10.1 500
        500 http://lt.archive.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     19.03.2-0ubuntu1 500
        500 http://lt.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages

$ apt policy docker-compose
docker-compose:
  Įdiegta:    1.21.0-3
  Kandidatas: 1.21.0-3
  Versijų lentelė:
 *** 1.21.0-3 500
        500 http://lt.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
        500 http://lt.archive.ubuntu.com/ubuntu eoan/universe i386 Packages
        100 /var/lib/dpkg/status
```
