### ISSUE TITLE
docker-compose logs no output if using log-driver

### ISSUE THREAD

**Issue by audunsolemdal** [docker/compose#7408]
## Description of the issue

docker-compose logs does not show output when using external log-driver. I would like to access the logs from both places.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.1, build a82fef07
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    entrypoint: ping host.docker.internal
    image: alpine:latest
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
  grafana:
    environment:
      GF_EXPLORE_ENABLED: "true"
    image: grafana/grafana:master
    ports:
    - published: 3000
      target: 3000
  loki:
    image: grafana/loki:master
    ports:
    - published: 3100
      target: 3100
version: '3.7'
```

## Steps to reproduce the issue

1. docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
2. Set daemon.json config as described here https://github.com/grafana/loki/blob/v1.4.1/docs/clients/docker-driver/configuration.md#change-the-default-logging-driver
3. docker-compose up -d with the config above
4. docker-compose logs

### Observed result

From this issue https://github.com/grafana/loki/issues/1368
and this comment https://github.com/grafana/loki/issues/1368#issuecomment-606872659

`docker logs <containername>` works fine. `docker-compose logs` does not work.

### Expected result

I would expect `docker-compose logs` to be able to show output in the same fashion as `docker logs`

### Stacktrace / full error message

```
Attaching to test-container_loki_1, test-container_grafana_1, test-container_app_1
app_1      | WARNING: no logs are available with the 'loki' log driver
grafana_1  | WARNING: no logs are available with the 'loki' log driver
loki_1     | WARNING: no logs are available with the 'loki' log driver
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

CentOS 8.1, puppet module installation
