### ISSUE TITLE
multiple files: see final 

### ISSUE THREAD

**Issue by millerf** [docker/compose#7415]
Hi all,

I have been using docker-compose for complex projects that need 4 or 5 docker-compose files to work in different environments, and I am missing a feature: I would like to see the final configuration when using multiple files.

Let me give you an example:

I have `docker-compose.yml` with:
```
version: '3.3'

services:
  db:
    image: somedb:latest
    volumes:
      - data:/path-to-data

  web:
    image: someweb:latest
    volumes:
      - data:/path-to-data
```

And `docker-compose-test.yml`

```
version: '3.3'

services:
  db:
    environment: 
       - SOME_VAR: test

  web:
    environment: 
       - SOME_VAR: test
```

I would like to have a way to do :

`$> docker-compose -f docker-compose.yml -f docker-compose-test.yml view`

And get:

```

version: '3.3'

services:
  db:
    image: somedb:latest
    volumes:
      - data:/path-to-data
    environment: 
       - SOME_VAR: test
  web:
    image: someweb:latest
    volumes:
      - data:/path-to-data
     environment: 
       - SOME_VAR: test
```

Is there something like this already existing? I cannot seem to find anything close to that...
