### ISSUE TITLE
Home references (~) won't work on Linux if bind mount is specified in long form

### ISSUE THREAD

**Issue by HaraldKorneliussen** [docker/compose#7428]
## Home references (~) won't work on Linux if bind mount is specified in long form

A docker compose file with a bind mount specified in long form which has a home directory reference in it (~) will on Linux cause the service to fail with an error message that mount 
paths have to be absolute. Example docker-compose file which provokes the error:

```
version: '3.7'
services:
  failing:
    image: hello-world
    volumes:
      - type: bind
        source: ~/minimal/bound
        target: /minimal/bound
```

Using the corresponding short form

```
version: '3.7'
services:
  failing:
    image: hello-world
    volumes:
      - ~/minimal/bound:/minimal/bound
```
does work as expected, the bug solely affects the long form and (as far as I can tell) solely on Linux systems.

** Output of `docker-compose version`
```
docker-compose version 1.23.2, build 1110ad0
```

**Output of `docker version`**
```
Docker version 19.03.8, build afacb8b7f0
```

**Output of `docker-compose config`**
(See above)

## Steps to reproduce the issue

Run the minimized failing example above, on a Linux system.

### Observed result
```
Recreating minimal_failing_1 ... error

ERROR: for minimal_failing_1  Cannot create container for service failing: invalid mount config for type "bind": invalid mount path: '~/minimal/bound' mount path must be absolute

ERROR: for failing  Cannot create container for service failing: invalid mount config for type "bind": invalid mount path: '~/minimal/bound' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```

### Expected result
```
Starting bf79f74e0bb7_minimal_failing_1 ... done
Attaching to bf79f74e0bb7_minimal_failing_1
bf79f74e0bb7_minimal_failing_1 | 
bf79f74e0bb7_minimal_failing_1 | Hello from Docker!
```
...etc.

## Additional information

Output of uname -a:
```
Linux harald-desktop 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Output of python --version
```
Python 3.7.6
```
