### ISSUE TITLE
Docker-compose not adding dependent services to /etc/hosts

### ISSUE THREAD

**Issue by dmc2015** [docker/compose#7442]
## Description of the issue
Docker Compose is not adding containers/ips to '/etc/hosts/ when `depended_on` is used.
The container itself is added but not the container that it is linking to, which to me should be reversed.

## Context information (for bug reports)

Will give you this error:
`PG::ConnectionBad: could not translate host name "db" to address: Name or service not known`

If you cat `/etc/hosts` you will get something like this
```
root@bdd6f863aced:/myapp# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.21.0.3      bdd6f863aced
```

The last entry is the `web` service itself, the one I connect to and should be able to connect to my db service.  I expect an entry for the `db` service/container so I can connect to it.

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags) 
Other flags ? 
```
services:
  db:
    image: postgres
    volumes:
    - /Users/donmclamb/dev/rails/rails-docker-compose-example/rails-doc-issue2/tmp/db:/var/lib/postgresql/data:rw
  web:
    build:
      context: /Users/donmclamb/dev/rails/rails-docker-compose-example/rails-doc-issue2
    depends_on:
    - db
    ports:
    - 3000:3000/tcp
    volumes:
    - /Users/donmclamb/dev/rails/rails-docker-compose-example/rails-doc-issue2:/myapp:rw
version: '3.0'
```

## Steps to reproduce the issue

Sample app:

https://github.com/tushartuteja/rails-docker-compose-example

Recreate the issue:

- `git clone git@github.com:tushartuteja/rails-docker-compose-example.git`
- `cd rails-docker-compose-example`
- `docker-compose up --build`
- `docker ps` # get the id for the web container
- `docker exec -it {container id} /bin/bash`
- `rake db:create`
- `cat /etc/hosts`

### Observed result
```
root@bdd6f863aced:/myapp# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.21.0.3      <containers id>
```

### Expected result
```
root@bdd6f863aced:/myapp# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.21.0.3      <container name | container id if that actually works>
```

### Stacktrace / full error message
There isn't an error out side of rails not being able to locate the container by name:

```
PG::ConnectionBad: could not translate host name "db" to address: Name or service not known
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
```

## Additional information

Mac Mojave, `docker-compose`, installed with brew
