### ISSUE TITLE
Unable to set tmpfs mount in a container using stack yaml

### ISSUE THREAD

**Issue by hasanasim** [docker/compose#7456]
## Description of the issue

I am trying to replicate the docker run command
 `docker run -d -it --name test --mount type=tmpfs,destination=/dev/shm,tmpfs-size=2048000000 gcr.io/pm-scraping-staging/scrapyd:test-crawlera-cert-2 bash -c 'scrapyd --pidfile=/tmp/scrapyd.pid'`
 using a stack.yml file.
I used the example docker run with `--mount` in the docs [here](https://docs.docker.com/storage/tmpfs/#use-a-tmpfs-mount-in-a-container) to form my command.
I tried to use the examples [here](https://docs.docker.com/compose/compose-file/#volumes-for-services-swarms-and-stack-files) for my stack.yml. However the docs don't contain an example for how tmpfs should look within a docker compose file.

I'm targeting the same VM instance with both, the container spins up as expected however when running `docker exec test df -h /dev/shm` I can only get my desired output using the `docker run` command.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
```

**Output of `docker version`**
```
Docker version 19.03.2, build 6a30dfc
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

I have only included the relevant service below.
```
scrapyd:
    command: bash -c 'scrapyd --pidfile=/tmp/scrapyd.pid'
    depends_on:
    - crawlera-headless-proxy
    deploy:
      mode: global
      placement:
        constraints:
        - node.labels.ffrole == scraping-worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 10s
      update_config:
        parallelism: 5
    environment:
      FFSC_CRAWLERA_HEADLESS_PORT: 3128
      FFSC_CRAWLERA_HEADLESS_PROXY: crawlera-headless-proxy
      FFSC_GC_PROJECT: ''
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: bash -c '</dev/tcp/0.0.0.0/6800'
      timeout: 10s
    image: 'gcr.io//scrapyd:'
    logging:
      driver: gcplogs
    ports:
    - mode: host
      published: 6800
      target: 6800
    volumes:
    - target: /dev/shm
      tmpfs:
        size: 2048000000
      type: tmpfs
```

## Steps to reproduce the issue

1. (from docs) run `docker run -d -it --name tmptest --mount type=tmpfs,destination=/dev/shm,tmpfs-size=2048000000 nginx:latest`
2. run `docker exec tmptest df -h /dev/shm` to show correct size for tmpfs.
3. Set tmpfs in a stack.yml file, deploy and then run `docker exec tmptest df -h /dev/shm` to show the incorrect tmpfs size. 

### Observed result

 `docker run -d -it --name test --mount type=tmpfs,destination=/dev/shm,tmpfs-size=2048000000 gcr.io/pm-scraping-staging/scrapyd:test-crawlera-cert-2 bash -c 'scrapyd --pidfile=/tmp/scrapyd.pid'` and then `docker exec test df -h /dev/shm` returns 

``Filesystem      Size  Used Avail Use% Mounted on``
``tmpfs           2.0G     0  2.0G   0% /dev/shm``

whereas using a yml file with the service above and then `docker exec 9b81f7559532 df -h /dev/shm` returns 

``Filesystem      Size  Used Avail Use% Mounted on``
``shm              64M     0   64M   0% /dev/shm``

### Expected result
I would expect the container spun up using stack.yml to return the same for `df -h /dev/shm` as the docker run command.
``Filesystem      Size  Used Avail Use% Mounted on``
``tmpfs           2.0G     0  2.0G   0% /dev/shm``

## Additional information

The services are deployed using `docker stack deploy --prune --with-registry-auth -c stack.yml stack_name`.
VM running Ubuntu 18.04.1 LTS.

`docker inspect -f '{{ .Mounts }}' tmptest` returns `[{tmpfs   /dev/shm   true }]` for containers spun up using `docker run` and `[]` for containers spun up using stack.yml.
