### ISSUE TITLE
Is there a way to output a warning about key duplication in docker-compose.yaml?

### ISSUE THREAD

**Issue by oshiro3** [docker/compose#7465]
## Description of the issue

Currently, in the description of the docker-compose.yml file, if I register the same key in the same service definition, the value defined later will be applied. This issue cannot be detected by docker-compose's validation feature. Upon investigation, it is the specification of the `safe_load` method of the pyyaml ​​standard library, and currently pyyaml ​​does not seem to take any measures.
 https://github.com/yaml/pyyaml/issues/165

I need to manually check that the same key is not defined in the docker-compose.yml file in our project.
I would like to solve this problem with docker-compose's validation feature if possible.

The following issues have been closed, is this a resolved issue?
I would like to know if there are already cases of countermeasures.
I would also like to know if it is an issue that should be addressed in our project.
https://github.com/docker/compose/issues/5267

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
```

**Output of `docker version`**
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

## Steps to reproduce the issue

1. write compose.yaml
```
version: '3'
services:
     nginx:
        image: nginx
        environment:
            - 'testenv1=1'
        environment:
            - 'testenv2=2'
```
2. output config
```
$docker-compose config

services:
     nginx:
        environment:
            testenv1: 1
        image: nginx
```

### Expected result

```
$docker-compose config
services:
     nginx:
        environment:
            testenv1: 1
            testenv2: 2
        image: nginx
```
or
```
$docker-compose config
WARNING: environment is duplicated. ....
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
