### ISSUE TITLE
wait dependency on docker compose

### ISSUE THREAD

**Issue by sptGabriel** [docker/compose#7491]
i have this error:

`(node:51) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND ${DB_HOST}`

And then I found out that the problem was with my docker-compose basically postgres is not initialized and so I'm having this error

I tried to use the following comand:

`command: ['./wait-for-it/wait-for-it.sh', 'db:5432', '--', 'yarn', 'dev']`

but i got this error:

```
api    | internal/modules/cjs/loader.js:969
ci-api    |   throw err;
ci-api    |   ^
ci-api    |
ci-api    | Error: Cannot find module '/home/node/api/wait-for-it/wait-for-it.sh'
ci-api    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
ci-api    |     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
ci-api    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
ci-api    |     at internal/main/run_main_module.js:17:47 {
ci-api    |   code: 'MODULE_NOT_FOUND',
ci-api    |   requireStack: []
ci-api    | }
```

**my docker file:**

```
FROM node:lts-alpine

RUN mkdir -p /home/node/api/node_modules && chown -R node:node /home/node/api

WORKDIR /home/node/api

COPY ormconfig.json .env package.json yarn.* ./

USER node

RUN yarn

COPY --chown=node:node . .

EXPOSE 4000

CMD ["yarn", "dev"]
```

**my docker-compose:**

```
version: '3.7'
services:
  db-pg:
    image: postgres:12
    container_name: db-pg
    ports:
      - '${DB_PORT}:5432'
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ci-postgres-data:/data

  ci-api:
    build: .
    container_name: ci-api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db-pg
    command: ['./wait-for-it/wait-for-it.sh', 'db:5432', '--', 'yarn', 'dev']
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

volumes:
  ci-postgres-data:
```
