### ISSUE TITLE
compose file dns field not working

### ISSUE THREAD

**Issue by hacker-h** [docker/compose#7497]
# Description of the issue
The dns field does not work

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:23 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:55 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  alpine:
    command: cat /etc/resolv.conf
    container_name: alpine
    dns:
    - 1.2.3.4
    image: alpine
version: '3.7'
```

## Steps to reproduce the issue

1. use this minimal docker-compose file:
```
version: '3.7'
services:
    alpine:
        container_name: alpine
        image: alpine
        dns: 1.2.3.4
        command: cat /etc/resolv.conf
```
2. docker-compose up

### Observed result
```
Starting alpine ... done
Attaching to alpine
alpine    | nameserver 127.0.0.11
alpine    | options ndots:0
alpine exited with code 0
```

### Expected result

It should be analogue to the respective `docker run` command:
```
docker run --name alpine --dns 1.2.3.4 alpine cat /etc/resolv.conf
nameserver 1.2.3.4
```

which would result in the following `docker-compose up` output:
```
Starting alpine ... done
Attaching to alpine
alpine    | nameserver 1.2.3.4
alpine exited with code 0
```

### Stacktrace / full error message
there is no error

## Additional information

Ubuntu 19.10
Docker-Compose installed with binaries:
`https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64`
Docker installed with apt:
`apt install docker-ce`
