### ISSUE TITLE
"Missing mandatory value" error is imprecise/bloated

### ISSUE THREAD

**Issue by probablykasper** [docker/compose#7504]
When specifying a required environment variables, the error messages are imprecise/bloated.

I have a service defined like the following:
```yml
  api:
    environment:
      NODE_ENV: development
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      API_SESSION_KEY: ${API_SESSION_KEY:?}
      API_HTTP_PORT: ${API_HTTP_PORT:?}
      API_HTTPS_PORT: ${API_HTTPS_PORT:?}
      WEB_HTTP_PORT: ${WEB_HTTP_PORT:?}
      WEB_HTTPS_PORT: ${WEB_HTTPS_PORT:?}
      DB_PORT: ${DB_PORT:?}
  # ...
```

Let's say I forget to set the variable `$API_SESSION_KEY`. This is the error I receive:
```
ERROR: Missing mandatory value for "environment" option interpolating {'NODE_ENV
': 'development', 'DB_USERNAME': '${DB_USERNAME}', 'DB_PASSWORD': '${DB_PASSWORD
}', 'API_SESSION_KEY': '${API_SESSION_KEY:?API_SESSION_KEY}', 'API_HTTP_PORT': '
${API_HTTP_PORT:?API_HTTP_PORT}', 'API_HTTPS_PORT': '${API_HTTPS_PORT:?API_HTTPS
_PORT}', 'WEB_HTTP_PORT': '${WEB_HTTP_PORT:?WEB_HTTP_PORT}', 'WEB_HTTPS_PORT': '
${WEB_HTTPS_PORT:?WEB_HTTPS_PORT}', 'DB_PORT': '${DB_PORT:?DB_PORT}'} in service
 "api":
```

It doesn't say which variable is missing, it just lists all the environment variables specified in `docker-compose.yml`. It would be much easier to understand with an error like the following:
```
ERROR: Missing mandatory environment variable "API_SESSION_KEY" for option "environment" in service "api"
```

Related: #6587
