### ISSUE TITLE
Stack deploy with compose does not warn on duplicate deploy stages and ignores one.

### ISSUE THREAD

**Issue by ainsey11** [docker/compose#7513]
## Description of the issue
When using a docker compose file (Version 3.4 upwards, I didn't test any lower than 3.4), and you have a service with two deploy statements (by error) there are no warnings to display the duplicate. It then also seems to apply the latter deploy and completely ignore the first.
I am not expecting it to deal with both deploy stages, as it is clearly a configuration mistake on our part, but a warning would be useful IMO.

## Context information (for bug reports)

Compose example:
```
  servicename:
    image: "imagename:1"
    command: ["node", "index.js"]
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 2G
    deploy:
      replicas: 4
      placement:
        constraints: [node.labels.nodekind == worker]
```

**Output of `docker-compose version`**
```
using compose file version 3.4+, we also had this issue all the way up to 3.8
```

**Output of `docker version`**
```
Docker version 19.03.11, build 42e35e61f3
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
N/A as using docker stack deploy -f docker-compose.yml
```

## Steps to reproduce the issue

1. Create Compose using above example
2. run docker stack deploy test_stack -f docker-compose.yml
3. docker inspect <container_id> - note the CPU / MEM limits are not applied due to ignoring the first deploy stage

### Observed result
No warning is displayed

### Expected result
Warning / error regarding duplicate displayed

### Stacktrace / full error message
N/A
```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Ubuntu 18.04 LTS, docker swarm.
