### ISSUE TITLE
Infinite build while increasing disk usage

### ISSUE THREAD

**Issue by misterquestions** [docker/compose#7515]
# Description of the issue
When I try to execute `docker-compose build` only one service gets built but suddenly it freezes at another build of a service (which is bind-mounting a really heavy volume ~55GB) but for some reason it starts to eat disk. 

## Context information (for bug reports)

**Dockerfile**
```
FROM        ubuntu:20.04

RUN         apt-get update && \
            apt-get upgrade -y && \
            apt-get install bash libncursesw5 -y

ADD         http://nightly.mtasa.com/files/modules/64/libmysqlclient.so.16 /usr/lib

WORKDIR     /mtasa

ADD         http://linux.mtasa.com/dl/multitheftauto_linux_x64.tar.gz .
RUN         tar -xf multitheftauto_linux_x64.tar.gz && \
            rm -f multitheftauto_linux_x64.tar.gz && \
            mv multitheftauto_linux_x64/* . && \
            rm -rf multitheftauto_linux_x64

ADD         http://linux.mtasa.com/dl/baseconfig.tar.gz .
RUN         tar -xf baseconfig.tar.gz && \
            rm -f baseconfig.tar.gz && \
            mv baseconfig/* mods/deathmatch && \
            rm -rf baseconfig

RUN         mkdir mods/deathmatch/logs && \
            touch mods/deathmatch/logs/server.log && \
            ln -sf /dev/stdout mods/deathmatch/logs/server.log

COPY        ./config/acl.xml mods/deathmatch
COPY        ./config/mtaserver.conf mods/deathmatch

EXPOSE      22003/udp 22005/tcp 22126/udp

ENTRYPOINT  [ "/mtasa/mta-server64" ]
```

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.0
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Output of `docker version`**
```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7
 Built:             Mon Jun  1 21:07:47 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fd
  Built:            Mon Jun  1 21:09:02 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: something
      PMA_HOST: something
    image: mariadb:bionic
    ports:
    - published: 3306
      target: 3006
    restart: always
    volumes:
    - source: /home/misterquestions/ravens/database/config/50-server.cnf
      target: /etc/mysql/mariadb.conf.d/50-server.cnf
      type: bind
    - source: /home/misterquestions/ravens/database/store
      target: /var/lib/mysql
      type: bind
  mtasa:
    build:
      context: /home/misterquestions/ravens/mtasa
    ports:
    - protocol: udp
      published: 22003
      target: 22003
    - protocol: tcp
      published: 22015
      target: 22005
    - protocol: udp
      published: 22126
      target: 22126
    restart: on-failure
    volumes:
    - source: /home/misterquestions/ravens/mtasa/config/acl.xml
      target: /mtasa/mods/deathmatch/acl.xml
      type: bind
    - source: /home/misterquestions/ravens/mtasa/config/mtaserver.conf
      target: /mtasa/mods/deathmatch/mtaserver.conf
      type: bind
    - source: /home/misterquestions/ravens/mtasa/cache
      target: /mtasa/mods/deathmatch/resource-cache/http-client-files
      type: bind
    - source: /home/misterquestions/ravens/mtasa/databases
      target: /mtasa/mods/deathmatch/databases
      type: bind
    - source: /home/misterquestions/ravens/mtasa/resources
      target: /mtasa/mods/deathmatch/resources
      type: bind
  nginx:
    build:
      context: /home/misterquestions/ravens/nginx
    ports:
    - published: 80
      target: 80
    volumes:
    - source: /home/misterquestions/ravens/nginx/config/nginx.conf
      target: /etc/nginx/nginx.conf
      type: bind
    - source: /home/misterquestions/ravens/nginx/config/site.conf
      target: /etc/nginx/sites-available/default
      type: bind
    - source: /home/misterquestions/ravens/mtasa/cache
      target: /usr/share/nginx/html/cache
      type: bind
    - source: /home/misterquestions/ravens/mtasa/resources/[multitask]/cache/maps
      target: /usr/share/nginx/html/maps
      type: bind
  pma:
    depends_on:
    - database
    environment:
      MYSQL_ROOT_PASSWORD: something
      PMA_HOST: something
    image: phpmyadmin/phpmyadmin
    links:
    - database
    ports:
    - published: 4000
      target: 80
version: '3.8'
```

## Steps to reproduce the issue

1. Have a heavy folder (in this case /resources) 
2. Attempt to run `docker-compose build`
3. Should get stucked at building the "mtasa" service

### Observed result
Infinite growing disk usage

### Expected result
Mount folders from host into container without copying anything and build successfully.

### Stacktrace / full error message

```
no output returned since it gets stucked into some kind of infinite execution 
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
