### ISSUE TITLE
docker-compose cannot be run against docker-in-docker

### ISSUE THREAD

**Issue by blevine** [docker/compose#7529]
## Description of the issue
Running under Gitlab CI using dind as a service and docker/compose as the image docker cannot connect to docker daemon.

## Steps to reproduce the issue
Execute a Gitlab CI with a gitlab-ci.yaml as shown:

```
image:
  name: docker/compose:1.26.0

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376 ### Note: I tried many different values here including port 2375

services:
  - docker:19.03.11-dind

before_script:
  - docker info

stages:
  - test

tests:
  stage: test
  script:
    - echo "hello"
```

### Observed result
docker info returns error: 

```
Client:
  Debug Mode: false
 Server:
 ERROR: Cannot connect to the Docker daemon at tcp://docker:2376. Is the docker daemon running?
```
### Expected result
docker info command should succeeed

## Additional information

In the Docker image, the entrypoint.sh contains code to set the DOCKER_HOST env variable correctly. When using the docker image (instead of docker/compose) against dind, DOCKER_HOST gets set to tcp://docker:2376 which is why I tried that value. I also tried a number of other values none of which worked.  Is running docker/compose against dind supported?
