### ISSUE TITLE
Log level option is ignored when logging driver set to none

### ISSUE THREAD

**Issue by ryan-cahill** [docker/compose#7530]
## Description of the issue
My goal is to hide all logging pertaining to a specific container. I was able to hide all of the logging that would come from the application in the container by using the 'none' logging driver. Unfortunately, the logging was replaced with the message `WARNING: no logs are available with the 'none' log driver`, so there are still logs, and now they're even less meaningful. To try to work around this, I added the `log-level` option in the `up` command as in `docker-compose -f config.json --log-level ERROR up --build --abort-on-container-exit`, but setting the log level to `ERROR` does nothing to suppress the compose-generated warning.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  gateway:
    depends_on: []
    environment:
      DISABLE_ACCESS_LOGS: "true"
      HTTPS_METHOD: noredirect
    image: registry.architect.io/architect-nginx/proxy:latest
    logging:
      driver: none
    ports:
    - 1024:80/tcp
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
version: '3.0'
```

## Steps to reproduce the issue

1. Run the config above `docker-compose -f compose.yml --log-level ERROR up --build --abort-on-container-exit`

### Observed result
A warning `WARNING: no logs are available with the 'none' log driver` coming from the gateway container.

### Expected result
Clean logging output with no logging from the gateway container.

### Stacktrace / full error message

```
WARNING: no logs are available with the 'none' log driver
```
