### ISSUE TITLE
Why Docker Compose does not create secrets?

### ISSUE THREAD

**Issue by danilopeixoto** [docker/compose#7559]
Hi,

Why `docker-compose up -d` command does not create secrets defined in `docker-compose.yml` file automatically?

Example:

```
version: '3.5'

secrets:
  database_password:
    file: secrets/database_password

services:

...
```

Docker version: `Docker version 19.03.9, build 9d988398e7`
Docker Compose version: `docker-compose version 1.25.5, build 8a1c60f6`

Thanks.
