### ISSUE TITLE
Logs for service not shown for certain ENTRYPOINT commands.

### ISSUE THREAD

**Issue by m-murad** [docker/compose#7560]
## Description of the issue
Logs are not shown when ENTRYPOINT statement is 
```ENTRYPOINT [`reflex -r '\.go|go\.mod' -s -- sh -c 'go run main.go'`]```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  anitab-auth-net:
    driver: bridge
services:
  anitab-auth-app:
    build:
      context: /Users/murad/github/m-murad/anitab-auth
      dockerfile: dockerfile.dev
    container_name: anitab-auth-app-dev
    depends_on:
    - anitab-auth-postgres
    - anitab-auth-redis
    networks:
      anitab-auth-net: null
    ports:
    - published: 8080
      target: 8080
    volumes:
    - /Users/murad/github/m-murad/anitab-auth:/anitab-auth:rw
  anitab-auth-postgres:
    container_name: anitab-auth-postgres-dev
    environment:
      POSTGRES_DB: anitab-auth-dev
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
    image: postgres
    networks:
      anitab-auth-net: null
    restart: always
    volumes:
    - postgres-data-dev:/var/lib/postgresql/data:rw
  anitab-auth-redis:
    command: redis-server --requirepass this_is_redis_password
    container_name: anitab-auth-redis-dev
    image: redis
    networks:
      anitab-auth-net: null
    restart: always
    volumes:
    - redis-data-dev:/data:rw
version: '3.6'
volumes:
  postgres-data-dev: {}
  redis-data-dev: {}
```

## Steps to reproduce the issue

1. If the ENTRYPOINT command for `anitab-auth-app` service is ```ENTRYPOINT [`go run main.go`]``` logs are shown for the service
2. If the ENTRYPOINT command for `anitab-auth-app` service is ```ENTRYPOINT [`reflex -r '\.go|go\.mod' -s -- sh -c 'go run main.go'`]``` logs are shown for the service

### Observed result
Logs are not shown in Case 2

### Expected result
Logs should be shown in Case 2

## Additional information

OS version / distribution, `docker-compose` install method, etc.
mac OS Catalina - 10.15.4 
Docker Desktop on Mac
