### ISSUE TITLE
config and secret variable expansion

### ISSUE THREAD

**Issue by aaronovz1** [docker/compose#7566]
It would be great if the secrets and config sections of a compose file could do variable expansions with golang:

```
version: '3.8'
services:
  myapp:
    image: 127.0.0.1:6666/myapp
    build: ./myapp
    secrets:
      - source: private_key_{{.Task.Slot}}
        target: private_key

secrets:
  private_key_1:
    name: private_key_1
    file: ./keys/private_key_1
  private_key_2:
    name: private_key_2
    file: ./keys/private_key_2
  private_key_3:
    name: private_key_3
    file: ./keys/private_key_3
```

In this scenario, when scaling it would allow a service to pick a secret or config from a pool based on its task ID.
