### ISSUE TITLE
bug: network status not update correctly

### ISSUE THREAD

**Issue by ashcoll** [docker/compose#7599]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
3.7
```

**Output of `docker version`**
```
19.03.1
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

python.yaml
```yaml
version: "3.7"

services:
    python_nettest:
        image: python:3.7.4  
        networks:
            - python_net
        command: ping www.google.com
networks:
    python_net:
        driver: overlay  
        internal: true   
```

## Steps to reproduce the issue

1. `docker stack deploy -c ./python.yaml python`
2. inspect service log:  `docker service logs --no-trunc python_python_nettest`
    - log output like this: `python_python_nettest.1.0s0arjpi9qpqua1vbp6g2kje6@gentoo    | ping: www.google.com: Temporary failure in name resolution`
    - correct in this step;
3. change `python.yaml` config
    - onley modified line: `internal: false`
4. update swam , run : `docker stack deploy -c ./python.yaml python` 
4. inspect service log again
    - output is same: `python_python_nettest.1.0s0arjpi9qpqua1vbp6g2kje6@gentoo    | ping: www.google.com: Temporary failure in name resolution`
    - expect result: ping should success;
5. if step 4 is below, then ping is successed; (eg, **need remove stack before redeploy**;)
    - `docker stack rm python`
    - `docker stack deploy -c ./python.yaml python` 

## Additional information

os: linux x64
