### ISSUE TITLE
docker-compose up --scale rescales not specified service

### ISSUE THREAD

**Issue by kolbma** [docker/compose#7605]
## Description of the issue

I have multiple services (s1, s2, s3). s2 and s3 depends on s1.  
If I have scaled **s1** manually to e.g. **--scale s1=3** and afterwards call `docker-compose up --scale s2=1 s2`.  
Now the service **s1** gets also rescaled?!

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.3
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        42e35e61f352e527082521280d5ea3761f0dee50
 Built:             Wed Jun  3 13:10:57 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       42e35e61f352e527082521280d5ea3761f0dee50
  Built:            Wed Jun  3 13:09:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4
  GitCommit:        814b7956fafc7a0980ea07e950f983d0837e5578
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker-compose config`**
```
services:
  s1:
    build:
      context: /etc/docker/cfg
      dockerfile: Dockerfile.s1
    image: s1:latest
  s2:
    build:
      context: /etc/docker/cfg
      dockerfile: Dockerfile.s2
    depends_on:
    - s1
    image: s2:latest
  s3:
    build:
      context: /etc/docker/cfg
      dockerfile: Dockerfile.s3
    depends_on:
    - s1
    image: s3:latest
version: '3.4'
```

## Steps to reproduce the issue

1. docker-compose up -d --scale s1=3 s1
2. docker-compose up -d --scale s2=1 s2

### Observed result
For step 2:  
```
Stopping and removing s1_2 ... done
Stopping and removing s1_3 ... done
Starting s1_1              ... done
Starting s2_1              ... done
```

### Expected result
For step 2:
```
Starting s2_1              ... done
```

## Additional information

I know of `--no-deps` like `docker-compose up -d --no-deps --scale s2=1 s2`.  
But this wouldn't start any required **s1** instance if s1 service would be stopped before.

I think it would be more logic to simple recognize the command line on scaling.

```
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

# apk info | grep docker | while read p ; do apk search -x "$p" ; done
docker-engine-19.03.11-r0
docker-openrc-19.03.11-r0
docker-cli-19.03.11-r0
docker-19.03.11-r0
docker-doc-19.03.11-r0
docker-registry-2.7.1-r2
docker-registry-openrc-2.7.1-r2
dockerpy-creds-0.4.0-r2
docker-py-4.2.0-r0
py3-dockerpty-0.4.1-r2
docker-compose-1.25.4-r2
```
