### ISSUE TITLE
Double dollar sign evaluates to an escaped dollar sign: \$ instead of a single dollar sign: $

### ISSUE THREAD

**Issue by tomekwszelaki** [docker/compose#7606]
## Description of the issue
When using double dollar sign in an environment variable I end up with an escaped dollar sign (\$) in the variable value.

## Steps to reproduce

1. Given the following docker-compose.yml file: 
```
version: '3.3'
services:
  mssql-server-linux:
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass$$1234
    ports:
      - '1433:1433'
    image: microsoft/mssql-server-linux
```
2. When you start the container with `docker-compose up -d`
3. And access the container with `docker exec -it sql-server /bin/bash`
4. And check the environment variables with `export`
5. Then the `SA_PASSWORD` variable will have the value `Pass$1234`

### Observed result
```
declare -x SA_PASSWORD="Pass\$1234"
```

### Expected result
```
declare -x SA_PASSWORD="Pass$1234"
```

Using docker on Windows 10:

![image](https://user-images.githubusercontent.com/1482166/87529658-98899d80-c68f-11ea-886c-bf59ba41151b.png)

**Comment by thaJeztah** [comment]
if you `docker inspect` the container, what does the configuration look like for the environment variable?

**Comment by tomekwszelaki** [comment]
```
"Env": [
          "ACCEPT_EULA=Y",
          "SA_PASSWORD=Pass$1234",
          "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
```

**Comment by thaJeztah** [comment]
> ```
> "Env": [
>           "ACCEPT_EULA=Y",
>           "SA_PASSWORD=Pass$1234",
>           "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
>         ],
> ```


That looks correct. Trying with a different image (setting the environment variables should not be dependent on the image used), the output also seems to be ok;

```yaml
version: '3.3'
services:
  mssql-server-linux:
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass$$1234
    image: nginx:alpine
```

After deploying that compose-file (using docker compose `docker-compose version 1.26.2, build eefe0d31`);


```bash
docker exec -it sql-server env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=55c46152672a
TERM=xterm
ACCEPT_EULA=Y
SA_PASSWORD=Pass$1234
NGINX_VERSION=1.19.0
NJS_VERSION=0.4.1
PKG_RELEASE=1
HOME=/root
```

```bash
docker exec -it sql-server sh -c 'echo $SA_PASSWORD'
Pass$1234
```

From that output, it looks like the environment-variable is set correctly. 


I _do_ notice you're using the `microsoft/mssql-server-linux` image, which looks to be deprecated (and hasn't been updated for two years); https://hub.docker.com/r/microsoft/mssql-server-linux. The new home is mentioned to be https://hub.docker.com/_/microsoft-mssql-server

It's possible the container's entry point doesn't handle these characters correctly?
