### ISSUE TITLE
[Feature] Reference external file URL for docker config creation

### ISSUE THREAD

**Issue by jbmcfarlin31** [docker/compose#7610]
**Is your feature request related to a problem? Please describe.**
When using configs with a compose file, you can specify a `file` attribute for where the config lives. For example:
```yaml
configs:
  conf1:
    name: testconfigfile
    file: ./testconfigfile.conf
```

This is expecting that the file exists on the machine that is running docker-compose presumably. However, if you specify a url to the config file instead, it breaks as it does not follow the url but rather just appends:
```yaml
configs:
  conf1:
    name: testconfigfile
    file: "https://repo.example.com/mygroup/myproject/-/raw/master/testconfigfile.conf" 
```

**Describe the solution you'd like**
I tried looking at the documentation and searching other issues but did not find an answer.

I would like to be able to specify either by the `file` attribute or another attribute like `url` or `external_url` a URL to my configuration file. This would help with pipelines utilizing `kompose` for translating docker compose into kubernetes yaml - specifically kubernetes ConfigMaps.

This also might be an issue with `kompose` so if it is please let me know and I will open a ticket with them.

Example:
```yaml
configs:
  conf1:
    name: testconfigfile
    file: "https://repo.example.com/mygroup/myproject/-/raw/master/testconfigfile.conf"

# or
configs:
  conf1:
    name: testconfigfile
    url: "https://repo.example.com/mygroup/myproject/-/raw/master/testconfigfile.conf"

# or
configs:
  conf1:
    name: testconfigfile
    ext_url: "https://repo.example.com/mygroup/myproject/-/raw/master/testconfigfile.conf"
```
