### ISSUE TITLE
Docker restarting Host instead of container service

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [docker/compose#7611]
## Description of the issue
We are using openSUSE system and deploying our application using docker containers (several services). All this is deployed using docker-compose.yaml file. We started to have problem when we introduced limits to docker-compose file. It works as expected when the limit was reached it did fail the container but the problem was that it sent the panic signal on host level which has setting that it would restart on a crash or panic. I am confused why is it sending this signal on Host level instead of just restarting the container itself. Our containers have restart set to always as you can see below. it happens on yang-search container (service described bellow in yaml file) that has set 2GB of ram and once exceeded it would reboot the host.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build d4451659
```

**Output of `docker version`**
```
Docker version 19.03.11, build 42e35e61f352
```

**Output of `docker-compose config`**

```
version: '3'

services:

  confd:
    build:
      context: . 
      dockerfile: ./confd/Dockerfile
    ports:
      - "8008:8008"
      - "8888:8888"
    volumes:
      - ${KEY_FILE}:/a/system/yangcatalog.org.key
      - ${CERT_FILE}:/a/system/yangcatalog.org.crt
    networks:
      - confd
    healthcheck:
      test: ["CMD", "curl", "-f", "curl 'http://localhost:8008/restconf", "-u", "\"admin\":\"Y@ng_adm1n->(paSS)\"", "-i"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 5G
    restart: always

  backend:
    image: catalog_backend_api:latest
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
    volumes:
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:rw
      - ./resources/main.cf:/etc/postfix/main.cf:rw
      - ${YANG_RESOURCES}:/var/yang:rw
      - ${YANG_RESOURCES}/nginx/YANG-modules:/usr/share/nginx/html/YANG-modules:rw
      - ${YANG_RESOURCES}/nginx/compatibility:/usr/share/nginx/html/compatibility:rw
      - ${YANG_RESOURCES}/nginx/private:/usr/share/nginx/html/private:rw
      - ${YANG_RESOURCES}/nginx/results:/usr/share/nginx/html/results:rw
      - ${YANG_RESOURCES}/nginx/stats:/usr/share/nginx/html/stats:rw
      - docs:/usr/share/nginx/html/slate
      - run:/var/run/yang
      - mysql:/var/run/mysqld
      - nginx-conf:/etc/nginx:rw
    networks:
      - confd
      - mysql
      - backend
      - elasticsearch
      - rabbitmq
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "curl 'http://localhost:8008/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 4G
    restart: always

  yang-search:
    build:
      context: search
      dockerfile: Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
    volumes:
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - ${YANG_RESOURCES}:/var/yang:rw
      - run:/var/run/yang
    networks:
      - mysql
      - backend
      - elasticsearch
      - frontend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    restart: always

  yangre:
    build:
      context: yangre
      dockerfile: Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
    volumes:
      - run:/var/run/yang
      - ${YANG_RESOURCES}:/var/yang:rw
    networks:
      - frontend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G
    restart: always

  api-receiver:
    image: catalog_backend_api:latest
    command: bash -c "chown -R yang:yang /var/run/yang; service postfix start; su yang; python api/receiver.py"
    volumes:
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - ${YANG_RESOURCES}:/var/yang:rw
      - ${YANG_RESOURCES}/nginx/YANG-modules:/usr/share/nginx/html/YANG-modules:rw
      - ${YANG_RESOURCES}/nginx/compatibility:/usr/share/nginx/html/compatibility:rw
      - ${YANG_RESOURCES}/nginx/private:/usr/share/nginx/html/private:rw
      - ${YANG_RESOURCES}/nginx/results:/usr/share/nginx/html/results:rw
    networks:
      - confd
      - mysql
      - backend
      - elasticsearch
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 4G
    restart: always

  api-recovery:
    image: catalog_backend_api:latest
    command: bash -c "source bin/activate; python recovery/recovery.py --type load --protocol http --ip confd"
    volumes:
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - ${YANG_RESOURCES}:/var/yang:rw
      - run:/var/run/yang
    networks:
      - confd
      - backend
    depends_on:
      - confd
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 5G

  frontend:
    build:
      context: .
      dockerfile: web_root/Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
        - NGINX_FILES=${NGINX_FILES}
    ports:
      - "80:80"
      - "443:443"
      - "10873:873"
    volumes:
      - ${YANG_RESOURCES}/nginx/YANG-modules:/usr/share/nginx/html/YANG-modules:rw
      - ${YANG_RESOURCES}/nginx/compatibility:/usr/share/nginx/html/compatibility:rw
      - ${YANG_RESOURCES}/nginx/private:/usr/share/nginx/html/private:rw
      - ${YANG_RESOURCES}/nginx/results:/usr/share/nginx/html/results:rw
      - ${YANG_RESOURCES}/nginx/stats:/usr/share/nginx/html/stats:ro
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - webroot:/usr/share/nginx/html/admin
      - docs:/usr/share/nginx/html/slate
      - run:/var/run/yang
      - ${NGINX_LOG}:/var/log/nginx:rw
      - mysql:/var/run/mysqld
      - ${YANG_RESOURCES}:/var/yang:rw
      - ${KEY_FILE}:/a/system/yangcatalog.org.key
      - ${CERT_FILE}:/a/system/yangcatalog.org.crt
      - nginx-conf:/etc/nginx:rw
    networks:
      - mysql
      - frontend
    depends_on:
      - backend
      - yang-search
      - yangre
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2G
    restart: always

  admin-ui:
    build:
      context: admin_ui
      dockerfile: Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
    volumes:
      - webroot:/usr/share/nginx/html/admin
      - ${YANG_RESOURCES}:/var/yang:rw
    networks:
      - mysql
      - frontend
    depends_on:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 1G

  yangvalidator:
    image: yangvalidator:latest
    build:
      context: .
      dockerfile: ./bottle-yang-extractor-validator/Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
    volumes:
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - ${YANG_RESOURCES}:/var/yang:rw
      - run:/var/run/yang
    networks:
      - frontend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    restart: always

  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
      args:
        - ELASTICSEARCH_ID=${ELASTICSEARCH_ID}
        - ELASTICSEARCH_GID=${ELASTICSEARCH_GID}
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ELASTICSEARCH_LOG}:/var/log/elasticsearch
      - ${ELASTICSEARCH_DATA}:/var/lib/elasticsearch
    networks:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 10G
    restart: always

  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbitmq1"
    volumes: []
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
    networks:
      - rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    restart: always

  mariadb:
    build:
      context: mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_ID=${MYSQL_ID}
        - MYSQL_GID=${MYSQL_GID}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql:rw
      - ./conf/mariadb:/docker-entrypoint-initdb.d:ro
      - mysql:/var/run/mysqld
    networks:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
    restart: always

  sdo-analysis:
    build:
      context: .
      dockerfile: ./sdo_analysis/Dockerfile
      args:
        - YANG_ID=${YANG_ID}
        - YANG_GID=${YANG_GID}
    volumes:
      - ./sdo_analysis/bin/resources/IETF-draft-list-with-no-YANG-problem.txt:/etc/yangcatalog/IETF-draft-list-with-no-YANG-problem.txt:ro
      - ${YANG_RESOURCES}/conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - ${YANG_RESOURCES}:/var/yang:rw
      - ${YANG_RESOURCES}/nginx/YANG-modules:/usr/share/nginx/html/YANG-modules:rw
      - ${YANG_RESOURCES}/nginx/compatibility:/usr/share/nginx/html/compatibility:rw
      - ${YANG_RESOURCES}/nginx/private:/usr/share/nginx/html/private:rw
      - ${YANG_RESOURCES}/nginx/results:/usr/share/nginx/html/results:rw
    networks:
      - frontend
      - confd
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: 5G
    restart: always

volumes:
  webroot:
  run:
  mysql:
  nginx-conf:
  docs:

networks:
  frontend:
    driver: bridge
  mysql:
    driver: bridge
  confd:
    driver: bridge
  backend:
    driver: bridge
  elasticsearch:
    driver: bridge
  rabbitmq:
    driver: bridge


```

### Observed result
Restarts the whole host instead
This does not happen on Ubuntu server only on openSUSE

### Expected result
Restart container that hit the limit

## Additional information

we are starting the container using  following command
```
docker-compose --compatibility up -d
```
OS version
```
cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

some system logs just before the restart of host system
```
2020-07-15T01:01:52.246035-07:00 yang2 kernel: [34593.984456] docker0:
port 1(veth233e616)  entered disabled state
2020-07-15T01:01:52.246047-07:00 yang2 kernel: [34593.987630] device
veth233e616 left promiscuous mode
2020-07-15T01:01:52.246047-07:00 yang2 kernel: [34593.987630] docker0:
port 1(veth233e616)  entered disabled state

which show a docker container going offline and

2020-07-15T01:01:52.350376-07:00 yang2 dockerd[1029]:
time="2020-07-15T01:01:52.350137080-07:00" level=warning
msg="9524e59f32570993464aecd993ef191883e6f0aefe55765a64904e9f8d24a162
cleanup: failed to unmount IPC: umount /a/docker/lib/containers
/9524e59f32570993464aecd993ef191883e6f0aefe55765a64904e9f8d24a162/mounts/shm,
flags: 0x2: no such file or directory"
```
