### ISSUE TITLE
OCI runtime create failed: container_linux.go:349

### ISSUE THREAD

**Issue by codinghedgehog-python** [docker/compose#7615]
Hi, I'd very much welcome any assistance on this issue:

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build unknown
```

**Output of `docker version`**
```
Docker version 19.03.12, build 48a66213fe
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  tickets:
    build:
      context: /home/mark/ticket_mgr/services/tickets
      dockerfile: Dockerfile
    depends_on:
    - tickets-db
    environment:
      APP_SETTINGS: project.config.DevelopmentConfig
      DATABASE_TEST_URL: postgres://postgres:postgres@tickets-db:5432/tickets_test
      DATABASE_URL: postgres://postgres:postgres@tickets-db:5432/tickets_dev
      FLASK_APP: project.__init__.py
      FLASK_ENV: development
    ports:
    - published: 5001
      target: 5000
    volumes:
    - /home/mark/ticket_mgr/services/users:/usr/src/app:rw
  tickets-db:
    build:
      context: /home/mark/ticket_mgr/services/tickets/project/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - published: 5435
      target: 5432
version: '3.7'
```

Error output received after running `docker-compose up -d --build`

### Expected result

Project brought up correctly.

### Stacktrace / full error message

```
ERROR: for ticket_mgr_tickets_1  Cannot start service tickets: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown
```

## Additional information

It complains about `entrypoint.sh` file not being present but it is where it supposed to be. The error output is referring to line 349 but I can't really trace it down to get more insight into this, can I ?

OS:  Ubuntu 20.04
