### ISSUE TITLE
Allow overwriting the service names in the compose file

### ISSUE THREAD

**Issue by AnmSaiful** [docker/compose#7618]
**Is your feature request related to a problem? Please describe.**
In order to centralize the configuration and reuse the compose files, I'm trying to make use of environment variables as much as possible which include the service name as well.

But as long as service names are keys in the compose file, they can't be used as variables.

There are many use cases of this situation, for example using different service names of the same service type on the same network.

**Describe the solution you'd like**

I would like to propose a new **service level configuration** named `service` or `service_name` or something similar that will overwrite the service name during the build process.

Here is the `.env` file:

```bash
PROJECT_NAME=foo
NODE_VERSION=14.5.0
```

Here is the proposed `docker-compose.yml` file:

```yml
version: "3.7"
services:
    app:
        service: ${PROJECT_NAME}_app
        image: node:${NODE_VERSION}
```

The final service name will be `foo_app` instead of `app` during the build.

**Comment by dominikbraun** [comment]
> There are many use cases of this situation, for example using different service names of the same service type on the same network.

Just being curious, that's the advantage of this? The service is eventually prefixed with the project name anyway 🤔

**Comment by AnmSaiful** [comment]
@dominikbraun one of the use cases is `hostname` conflict resolution as long as service names can be used as hostnames within the network. But this can be resolved by using the `hostname` configuration.

I was not aware that the service names are prefixed with the project name as long as I could access the service names as hostnames which are not prefixed with the project name.

**Comment by dominikbraun** [comment]
Strictly speaking,
* containers of a service are prefixed with the project name - it would be odd if you couldn't run two services called `web` from two different projects at the same time.
* _inside_ a project, Docker Compose creates a network for its services, and these services can talk to each other by the name - without project prefix, as they're in the same project.

**Comment by EricHripko** [comment]
You can already do this in the following ways:

- [-p command-line flag](https://docs.docker.com/compose/reference/overview/)
- [COMPOSE_PROJECT_NAME environment variable](https://docs.docker.com/compose/reference/envvars/#compose_project_name)

As @dominikbraun described, `docker-compose` will prefix all objects it creates (containers, volumes, networks, etc.) with this name. If you don't set this via one of the methods above, it defaults to the folder name of your project.

**Comment by AnmSaiful** [comment]
@dominikbraun regarding your statement,

> inside a project, Docker Compose creates a network for its services, and these services can talk to each other by the name - without project prefix, as they're in the same project.

This is exactly what I'm talking about. How could the services talk to each other if they are from different projects, having the same service name, and sharing the same network? If this is achievable using the project prefix, then fine. Currently I'm achieving this by exclusively setting the hostname of the containers.

For my case in specific, I'm centralizing all the database services for all my projects on my development machine. So all the projects are on the same (bridge) network in order to leverage the central database.

Hope this help clarify my concerns. :-)

**Comment by dominikbraun** [comment]
Now I understand your scenario :)

> This is exactly what I'm talking about. How could the services talk to each other if they are from different projects, having the same service name, and sharing the same network?

If they're on the same network, they can communicate via container name, which is `<project>_<service>_<container_number>`. 

You can prove this like so:

Central database in `/database/docker-compose.yml`:

```yaml
services:
    mysql:
        ...
```

Web app in `/web-app/docker-compose.yml`:

```yaml
services:
    php:
        ...
```

After starting both Compose projects ...

```shell script
$ docker-compose up -f /database/docker-compose.yml -d
$ docker-compose up -f /web-app/docker-compose.yml -d
```

... you can create a network and connect the containers.

```shell script
$ docker network create --driver bridge my-net
$ docker network connect my-net database_mysql_1
$ docker network connect my-net web-app_php_1
```

Now `database_mysql_1` should be a valid hostname for the `web-app_php_1` container. Of course, this isn't ergonomic because you would have to connect the containers each time you start the Compose projects.

Fortunately, you can instruct the `web-app` services to connect to an network _outside of the project_:

Central database in `/database/docker-compose.yml`:

```yaml
services:
    mysql:
        ...
networks:
    my-net:
        driver: bridge
```

Web app in `/web-app/docker-compose.yml`:

```yaml
services:
    php:
        ...
networks:
    my-net:
        external: true
```

That should work as well.

**Comment by AnmSaiful** [comment]
@dominikbraun thank you so much for the details instruction. Let me share what I'm currently doing.

`db/docker-compose.yml`

```yml
networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  db:
    container_name: ${DB_NAMESPACE}
    hostname      : ${DB_NAMESPACE}
    ...
```

`project/app/docker-compose.yml`

```yml
networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  app:
    container_name: ${APP_NAMESPACE}
    hostname      : ${APP_NAMESPACE}
    ...
```

I'm communicating through the `hostname`.  :-)
