### ISSUE TITLE
[DOCKER-COMPOSE] [URGENT] env_file attribute not reading from nested folder

### ISSUE THREAD

**Issue by uncodable** [docker/compose#7629]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D243E875-8FFC-4B33-8179-077C2E1EE782/20200725170110

### Expected behavior
To read the env file nested in a folder and use variables.

### Actual behavior
.env file will not read on Windows nested in a folder but does work on Mac and Linux OS.

### Information
  - Windows Version: 10 Pro - Build 19041
  - Docker Desktop Version: Latest
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
1. Create a `.env` inside a folder (example /api/.env)
```
DB_NAME=api
DB_PASS=password
```
2. Create a docker-compose.yml with these contents:
```
version: '3.1'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./api/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    restart: always
```
3. Run `docker-compose up`

See errors relating to environment variables not found. This works on Mac / Linux OS just not on Windows.

**Comment by shortpoet** [comment]
Not sure if this issue is related, but I found it while searching the repo issues and figured perhaps best to ask here before making a new one.  

I encountered an issue where COMPOSE_PROJECT_NAME wasn't being read when using a custom env file specified in docker-compose. When I was using docker.env it wasn't working (didn't set container name to custom value rather used default directory). It did work when using .env. I'm guessing this is on purpose to ensure the script finds the correct file? Wondering if there's a way to get around this.  Or perhaps I'm missing something else?

Thanks in advance for your help.


My compose file:

```yaml
version: "3.4"

services:
  vcc.client:
    image: vcc.client:alpine
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile.client.alpine
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    env_file:
      - ".env"
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app
      - notused:/usr/src/app/node_modules
    networks:
      - vccnet
    command: vite
    # https://github.com/webpack/webpack-dev-server/issues/547#issuecomment-284737321
    # https://medium.com/@andyccs/webpack-and-docker-for-development-and-deployment-ae0e73243db4#.v0vhqvvjl
    # --host 0.0.0.0
    # command: webpack-dev-server --host 0.0.0.0
    entrypoint: /usr/local/bin/docker-entrypoint-client-a.sh

  vcc.server:
    image: vcc.server:alpine
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile.server.alpine
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    env_file:
      - "docker.env"
    ports:
      - 4000:4000
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - vccnet
    command: yarn start:graph

  # # https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945
  # :Z for linux
  db:
    image: postgres:12
    # restart: always
    restart: unless-stopped
    # file must end in .sql not .psql
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
      - ./sql/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql:ro
      - ./postgres-data:/var/lib/postgresql/data:Z
    env_file:
      - ".env"
    ports:
      - 5432:5432
    networks:
      - vccnet

networks:
  vccnet:

volumes:
  notused:
  postgres-data:

```

my .env file

```bash
COMPOSE_PROJECT_NAME=vcc
# https://stackoverflow.com/a/55449975/12658653
# https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal
# https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script
# https://stackoverflow.com/questions/29377853/how-to-use-environment-variables-in-docker-compose
# https://gist.github.com/Vad1mo/9ab63f28239515d4dafd
# host.docker.internal to map localhost to 0.0.0.0 and avoid port used by daemon
# POSTGRES_HOST=host.docker.internal
# linux workaround also works on windows
POSTGRES_HOST=172.17.0.1
# this is the db on the host itself
# POSTGRES_HOST=host.docker.internal

# # https://github.com/quay/clair/issues/134

# https://github.com/entropic-dev/entropic/issues/190
# https://github.com/entropic-dev/entropic/issues/190#issuecomment-499733956
# https://stackoverflow.com/a/42742217/12658653
# uses service name

# POSTGRES_HOST=db
POSTGRES_USER=test
POSTGRES_PASSWORD=test
POSTGRES_DB=kanban
POSTGRES_PORT=5432
DOCKER=1
```

container logs showing diff results:
one is vcc the other is vuejs-composition-course

```

$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
5eb651303f86        postgres:12         "docker-entrypoint.sΓÇª"   16 seconds ago      Up 15 seconds       0.0.0.0:5432->5432/tcp   vcc_db_1
c7b2666f06c1        vcc.client:alpine   "/usr/local/bin/dockΓÇª"   16 seconds ago      Up 15 seconds       0.0.0.0:8080->8080/tcp   vcc_vcc.client_1


$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
688a1637a15d        vcc.client:alpine   "/usr/local/bin/dockΓÇª"   3 seconds ago       Up 3 seconds        0.0.0.0:8080->8080/tcp   vuejs-composition-course_vcc.client_1
c5d576fd042a        postgres:12         "docker-entrypoint.sΓÇª"   52 minutes ago      Up 3 seconds        0.0.0.0:5432->5432/tcp   vuejs-composition-course_db_1

```

**Comment by narwy** [comment]
@shortpoet Sounds like it could be related. I can't find a way to get around the `.env` being in the root, i need it nested for a monolith app 🤷 had to move them all to the top level as a work around for now, not ideal :/

**Comment by uncodable** [comment]
@stephen-turner does anyone work on docker-compose anymore i see a constant backlog of issues and no replies from anyone in this repo?

**Comment by ulyssessouza** [comment]
Hello @uncodable! Thank you for the report.
I couldn't reproduce the issue on any supported platform.

From what I understood, it looks like you are mixing 2 env-file concepts in `docker-compose`.
The ones specified inside the compose file are the ones used to pass as env vars to the container. While the `./.env` and the ones passed through `--env-file` option are used for variable substitution on the compose file.

So if you don't want your env-file used for the substitution to be inside the project root, you should specify this file with the `docker-compose` command, like in:

```
$ docker-compose --env-file ./api/.env <command>
```

To check if it's working, you can use the command `config` to show the configuration to be evaluated.
```
$ docker-compose --env-file ./api/.env config
```
In your case it should output:
```yaml
services:
  database:
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    environment:
      DB_NAME: api
      DB_PASS: password
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: password
    image: mysql
    ports:
    - published: 3306
      target: 3306
    restart: always
version: '3.1'
```

Please let me know if this fixes the problem.

**Comment by uncodable** [comment]
@ulyssessouza You can pass `env_file` in the docker-compose setup (https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option) However this is not reading nested folders. There's an issue here.

**Comment by ulyssessouza** [comment]
@uncodable I'm not sure what you mean here... Are you talking about variable substitution on the compose file or to environment variables passed to the container?
For passing environment variables to the container you can use `env_file` in the compose file.
For doing variable substitution on the compose file you have to set it on `.env` in the root of the project or pass it through `--env-file` to `docker-compose`.

Which one are you talking about?

**Comment by uncodable** [comment]
@ulyssessouza You can follow the steps above in the initial issue on how to reproduce the issue, I'm talking about `env_file` within the compose file. It does not allow for nested env files through the variable but the cli commands does.

**Comment by ulyssessouza** [comment]
On my test, I just run `docker-compose config` and got the following result:

```yaml
WARNING: The DB_PASS variable is not set. Defaulting to a blank string.
WARNING: The DB_NAME variable is not set. Defaulting to a blank string.
services:
  database:
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    environment:
      DB_NAME: api
      DB_PASS: password
      MYSQL_DATABASE: ''
      MYSQL_ROOT_PASSWORD: ''
    image: mysql
    ports:
    - published: 3306
      target: 3306
    restart: always
version: '3.1'
```

So it looks like the `.env` file is properly read inside the `api` folder. Note the `environment` section that was enriched with `DB_NAME` and `DB_PASS` coming from the file. The warning messages are relative to the variables that should be substituted as values for `MYSQL_DATABASE` and `MYSQL_ROOT_PASSWORD`. But this is the variable substitution case that I was telling before.

For the `docker-compose` version, I'm using the latest.
```shell
$ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```
