### ISSUE TITLE
docker-compose cant mount a source volume thats an encfs volume

### ISSUE THREAD

**Issue by ashjas** [docker/compose#7632]
## Description of the issue
If volumes specified in docker-compose.yml are encfs volumes, docker-compose fails to mount the volume.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.21.0, build unknown
```

**Output of `docker version`**
```
Docker version 19.03.12, build 48a6621
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    image: nextcloud-client:latest
    restart: unless-stopped
    volumes:
    - /media/pi/data/EncfsEncrypted:/media/nextcloud:rw
version: '3.0'
```

## Steps to reproduce the issue

1. Create an Encfs volume
2. Try to mount this volume on any docker container

### Observed result
Cannot start service app: error while creating mount source path ‘/media/pi/data/EncfsEncrypted’: mkdir /media/pi/data/EncfsEncrypted: file exists
### Expected result
docker container starts up.
### Stacktrace / full error message

```
Cannot start service app: error while creating mount source path ‘/media/pi/data/EncfsEncrypted’: mkdir /media/pi/data/EncfsEncrypted: file exists
```
