### ISSUE TITLE
docker-compose sature tmp folder

### ISSUE THREAD

**Issue by bourasom** [docker/compose#7668]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
1.25.3
```

**Output of `docker version`**
```
19.03.12
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '2.2'
services: 
  
  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /srv/mongo:/data/db:rw      
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /srv/mysql:/var/lib/mysql:rw      
    environment:
      MYSQL_ROOT_PASSWORD: xxxxx
      MYSQL_DATABASE: xxxx
      MYSQL_USER: xxxxx
      MYSQL_PASSWORD: xxxx
    restart: unless-stopped
    cap_add: 
      - CAP_SYS_NICE # Remove the mbind error
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5" 

```

## Steps to reproduce the issue

1. start container using docker-compose -f docker-compose.yml -p docker-compose.yml up -d
2. execute lsof | grep '/tmp'

### Observed result
docker-co 23696                  root  mem       REG                8,1     49304    2066884 /tmp/_MEILKqYGK/_queue.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    363384    2066872 /tmp/_MEILKqYGK/_datetime.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     30888    2066881 /tmp/_MEILKqYGK/_opcode.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     56864    2066885 /tmp/_MEILKqYGK/_random.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     41360    2066859 /tmp/_MEILKqYGK/_bisect.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    484048    2066888 /tmp/_MEILKqYGK/_sha3.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    535080    2066860 /tmp/_MEILKqYGK/_blake2.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    115624    2066874 /tmp/_MEILKqYGK/_hashlib.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     44184    2066904 /tmp/_MEILKqYGK/grp.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    154376    2066910 /tmp/_MEILKqYGK/liblzma.so.5
docker-co 23696                  root  mem       REG                8,1     99176    2066877 /tmp/_MEILKqYGK/_lzma.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     66992    2066905 /tmp/_MEILKqYGK/libbz2.so.1.0
docker-co 23696                  root  mem       REG                8,1     76432    2066861 /tmp/_MEILKqYGK/_bz2.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    305240    2066876 /tmp/_MEILKqYGK/_json.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     72184    2066883 /tmp/_MEILKqYGK/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    245568    2066894 /tmp/_MEILKqYGK/array.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    503144    2066882 /tmp/_MEILKqYGK/_pickle.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    111696    2066897 /tmp/_MEILKqYGK/binascii.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    108656    2066925 /tmp/_MEILKqYGK/select.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    182576    2066917 /tmp/_MEILKqYGK/math.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    252664    2066890 /tmp/_MEILKqYGK/_socket.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1   2715840    2066906 /tmp/_MEILKqYGK/libcrypto.so.1.1
docker-co 23696                  root  mem       REG                8,1    442984    2066913 /tmp/_MEILKqYGK/libssl.so.1.1
docker-co 23696                  root  mem       REG                8,1    327136    2066891 /tmp/_MEILKqYGK/_ssl.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     53008    2066875 /tmp/_MEILKqYGK/_heapq.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1     35296    2066909 /tmp/_MEILKqYGK/libffi.so.6
docker-co 23696                  root  mem       REG                8,1    497168    2066871 /tmp/_MEILKqYGK/_ctypes.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    107064    2066928 /tmp/_MEILKqYGK/zlib.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1    187960    2066892 /tmp/_MEILKqYGK/_struct.cpython-37m-x86_64-linux-gnu.so
docker-co 23696                  root  mem       REG                8,1  14494896    2066911 /tmp/_MEILKqYGK/libpython3.7m.so.1.0
docker-co 23696                  root  mem       REG                8,1    105088    2066916 /tmp/_MEILKqYGK/libz.so.1

ls -lt /tmp
root@xxx:/# ls -lt /tmp
total 472
drwx------ 13 root root 4096 Aug 13 16:09 _MEICt6BSF
drwx------ 13 root root 4096 Aug 13 16:09 _MEIvRoCOP
drwx------ 13 root root 4096 Aug 13 16:09 _MEIR7WTcX
drwx------ 13 root root 4096 Aug 13 16:08 _MEIHffN7Z
drwx------ 13 root root 4096 Aug 13 16:08 _MEIP4J7W8
drwx------ 13 root root 4096 Aug 13 16:08 _MEI6XXEch
drwx------ 13 root root 4096 Aug 13 16:08 _MEIemHKUh
drwx------ 13 root root 4096 Aug 13 16:08 _MEIYFF3gt
root@xxx:/# du -hs /tmp/_MEICt6BSF
39M	/tmp/_MEICt6BSF

I end with saturation in tmp folder
### Expected result
purge tmp created folder by docker-compose
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
