### ISSUE TITLE
Add docker-compose tag <service> <tag> and allow to push a specific tag by using push command

### ISSUE THREAD

**Issue by Jokero** [docker/compose#7669]
**Is your feature request related to a problem? Please describe.**
I have several applications with their own Dockerfile within one project and in order to build, launch and test them locally I'm using docker-compose.

It seems like a good idea to reuse docker-compose commands to build, test and push images to registry from CI, so I decided to use them in Jenkinsfile. Project has package.json file with current version which is incremented during CI build. This version is used as tag for docker images.

docker-compose.yaml:
```
version: '2'

services:
  app1:
    image: my-registry.com/app1
    build:
      context: ./app1
    // other fields
  app2:
    image: my-registry.com/app2
    build:
      context: ./app2
    // other fields
  app3:
    image: my-registry.com/app3
    build:
      context: ./app3
    // other fields
```

The current CI pipeline looks as follows:
```
1) Build images
docker-compose build // generates images with "latest" tag

2) Test images
docker-compose run --rm app1 <test command> // the same for app2 and app3

3) If tests passed, increment version and use it as the next docker tag
npm version <patch/minor/major>
newVersion = readJSON('package.json').version

4) Tag and push images
composeServices = readYaml('docker-compose.yaml').services // { app1: { image: my-registry.com/app1 }, ... }
image = composeServices.app1.image // the same for app2 and app3
docker tag <image> <image>:<newVersion>
docker push <image>:<newVersion>
```
This pipeline works but I have to read compose file to get image that will be used in "docker tag" and "docker push" commands.

**Describe the solution you'd like**
I'd like to have a new command:
```
docker-compose tag <service> <tag>
// for my example
docker-compose tag app1 <version from updated package.json>
```
And I want "push" command to support tag postfix:
```
docker-compose push <service>:<tag>
// for my example
docker-compose push app1:<version from updated package.json>
```

**Describe alternatives you've considered**
Using "docker tag" and "docker push" explicitly but for that I need to read images from docker-compose.yaml file

**Comment by so-jelly** [comment]
docker-compose "extends" works for me

```
version: "2.4"
services:
  foo:
    image: foo:${version:-dev}
    build:
      context: .
  foo-latest:
    extends: foo
    image: bar:latest
```
