### ISSUE TITLE
Plausible to start two wikijs containers with one docker-compose.yml and separate database (Postgres) through traefik?

### ISSUE THREAD

**Issue by Montana** [docker/compose#7673]
I am trying to start two ```wikijs``` containers with different databases through ```traefik```. I have no problem in starting the containers. I can start ```traefik``` on a subdomain and I even can start the two wikis on different subdomains. My problem is the following: Every time I start the ```wikijs``` containers I always somehow use the same database and I don't know how to change that.

The purpose is, that I have customers which want to have a separate wiki for their documentation. So I want to start as many ```wikijs``` containers as possible but preferably through one ```docker-compose.yml``` file. Can anybody tell me, what I am doing wrong? This _should_ be working. 

This is my ```traefik.toml``` file:

```toml
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$Ld55R9Cl$/8W5BCc.J/Qtg9Xtpk4lq0"]

[api]
entrypoint="dashboard"

[acme]
email = "email@domain.com" 
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
```

Leaving the ```PostGRES``` settings out, but they are pretty straight forward. Thank you fellow GitHub members!
