### ISSUE TITLE
docker-compose run does not wait for health checks for services defined in depends_on

### ISSUE THREAD

**Issue by Harrisonbro** [docker/compose#7681]
## Description of the issue

Unlike `docker-compose up`, running `docker-compse run` with a compose file in which some services `depend_on` others, those other services are started but Docker Compose does not wait for those services' health checks to return 'healthy'. This was noted [here in #2833](https://github.com/docker/compose/issues/2833#issuecomment-329751397).

## Steps to reproduce the issue

1. Create a Compose file with two services, one (A) depending on the other (B).
2. Make service B take some time to boot up and for it's healtcheck to return 'healthy' (e.g., a MySQL container which only returns healthy when MySQL is actually available for queries, using [this healthcheck script](https://gist.github.com/Harrisonbro/5d226dc68516aa97d86464a168946032))
3. Run a command in service A which will fail if service B is started but not fully booted and healthy (e.g., some unit tests which rely on making MySQL queries)

### Observed result

Commands in service A fail because service B is not fully healthy. In my use-case, that means PHPunit tests which try and query the database fail with `SQLSTATE[HY000] [2002] Connection refused` because MySQL is still booting up.

### Expected result

I would expect `docker-compose run` to start up the services and wait until they're all reporting healthy, like `docker-compose up` does, before running the command.

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app.testing:
    build:
      args:
        BUILD_ENV: testing
      context: /Users/harrison/Sites/stoneleigh-exhibitor-manual
      dockerfile: docker/images/app/Dockerfile
    depends_on:
    - database
    environment:
      (just application-level environment, nothing used by Docker)
    volumes:
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/phpunit.xml:/code/phpunit.xml:ro
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/tests:/code/tests:ro
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/docker/environment/local/fixtures:/fixtures:ro
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/.buildkite/tmp/public_built:/code/public/built:ro
  app.testing.standalone:
    build:
      args:
        BUILD_ENV: testing
      context: /Users/harrison/Sites/stoneleigh-exhibitor-manual
      dockerfile: docker/images/app/Dockerfile
    environment:
      (just application-level environment, nothing used by Docker)
    volumes:
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/phpspec.yml:/code/phpspec.yml:ro
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/tests/Unit:/code/tests/Unit:ro
  database:
    build:
      context: /Users/harrison/Sites/stoneleigh-exhibitor-manual
      dockerfile: docker/images/database/Dockerfile
    environment:
      MYSQL_DATABASE: stoneleigh
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: user
  web:
    build:
      context: /Users/harrison/Sites/stoneleigh-exhibitor-manual
      dockerfile: docker/images/web/Dockerfile
    volumes:
    - /Users/harrison/Sites/stoneleigh-exhibitor-manual/.buildkite/tmp/public_built:/tmp_public_built:rw
version: '3.7'
```

**Comment by EricHripko** [comment]
This should work as expected in [1.27.0](https://github.com/docker/compose/releases/tag/1.27.0-rc1) - could you give it a try?

**Comment by Harrisonbro** [comment]
Sadly not, @EricHripko. I'm using Docker for Mac which comes with Docker Compose 1.25 so I downloaded the [1.27.0-rc1 `docker-compose-Darwin-x86_64`](https://github.com/docker/compose/releases/download/1.27.0-rc1/docker-compose-Darwin-x86_64) binary from [this page](https://github.com/docker/compose/releases/tag/1.27.0-rc1) and re-ran my test and saw the same result.

![Screenshot 2020-08-18 at 12 05 02](https://user-images.githubusercontent.com/377366/90505755-10ddf580-e14b-11ea-9ac9-0c88f940b95c.jpg)

I've made [this video](https://go.surupartners.com/20e) showing the result.

**Comment by EricHripko** [comment]
Ah sorry, I didn't read your Compose file thoroughly enough. You should be able to achieve the desired behaviour by changing the following:
```
    depends_on:
    - database
``` 
to:
```
    depends_on:
      database:
        condition: service_healthy
```

**Comment by Harrisonbro** [comment]
Sadly, `depends_on` [no longer supports](https://docs.docker.com/compose/compose-file/#deploy) the `condition` syntax 😞

**Comment by EricHripko** [comment]
As per release notes on `1.27.0`, v2/v3 Compose formats are merged - so you should be able to use `condition: service_healthy`

**Comment by Harrisonbro** [comment]
Right you are 👍

**Comment by fbudassi-eb** [comment]
@EricHripko 
> As per release notes on `1.27.0`, v2/v3 Compose formats are merged - so you should be able to use `condition: service_healthy`

Is there any possibility that the `condition: service_healthy` syntax could be removed again in the future?

**Comment by EricHripko** [comment]
I would really surprised if that happens @fbudassi-eb - dropping `version:` requirement from [Compose specification](https://www.compose-spec.io/) came with a basic rule of `NEVER REMOVE ANYTHING FROM SCHEMA™`.

**Comment by nnisic** [comment]
When I try to use the syntax:

`
depends_on:
        service:
                condition: service_healthy
`

I get the error 'depends_on contains an invalid type, it should be an array'. I'm using Compose file version 3.8. Does anybody know the correct syntax for this file version to wait for the first service to pass their healthcheck before the next service starts? Thanks!

**Comment by fbudassi** [comment]
> When I try to use the syntax:
> 
> ```
> depends_on:
>     service:
>         condition: service_healthy
> ```
> 
> I get the error 'depends_on contains an invalid type, it should be an array'. I'm using Compose file version 3.8. Does anybody know the correct syntax for this file version to wait for the first service to pass their healthcheck before the next service starts? Thanks!

@nnisic did you try removing the `version: "3.8" ` at the beginning of your yaml?
Since docker-compose 1.27.0 it is optional and it might be giving you some problems. In fact, I've used exactly that syntax, but without that first line and it's been working perfectly well.

**Comment by flavienbwk** [comment]
In confirm the `depends_on.service.condition: service_healthy` option works perfectly well with docker-compose `1.28`

**Comment by Dragonphy** [comment]
In addition to `condition`, we also need to configure the `healthcheck` of db.
```yaml
version: "3"
services:
  db:
    container_name: db
    image: db/latest
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  web:
    container_name: web
    image: web/latest
    depends_on: 
      db:
        condition: service_healthy
```
