### ISSUE TITLE
docker-compose -f docker-compose.yml.dev -H ssh://user@ip uses wrong file / gets cached

### ISSUE THREAD

**Issue by cmmmhub** [docker/compose#7688]
## Description of the issue
I have a folder with multiple .yml files in: docker-compose.yml.dev and docker-compose.yml.uat. When I use docker-compose -f docker-compose.yml.dev -H ssh://ip up -d I expect it to up the image, container and network from .dev but instead it will load from docker-compose.yml.uat only when I run docker-compose.yml.uat again will it actually load the uat version of the file.

This does the same the other way around as well. Like its cached and needs to be ran 2 times for it to actually get the correct file. It seems to use the previous file even though -f has changed
.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
1.25.5, build 8a1c60f6
```

**Output of `docker version`**
```
 19.03.12, build 48a66213fe
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
dev:
networks:
  project-network: {}
services:
  node:
    container_name: site-dev
    image: ?????/repo:site-dev
    networks:
      project-network: null
    ports:
    - 8233:3000/tcp
    restart: unless-stopped
    stdin_open: true
    user: docker-user:docker-user
version: '3.0'

uat:
networks:
  project-uat-network: {}
services:
  node:
    container_name: site-uat
    image: ?????/repo:site-uat
    networks:
      project-uat-network: null
    ports:
    - 8234:3000/tcp
    restart: unless-stopped
    stdin_open: true
    user: docker-user:docker-user
version: '3.0'
```

## Steps to reproduce the issue

1. create 2 docker-compose files in the same directory
2. docker-compose -f docker-compose.yml.dev -H ssh://ip up -d. If nothing has loaded before it then it will load dev but if docker-compose.yml.uat was loaded before it then it will load the container for uat.

### Observed result

switching the files for the first  up -d doesnt work its only the second that loads the correct file

### Expected result

when i switch the file using -f I expect it to use that file when doing docker-compose up -d

### Stacktrace / full error message

```
no error
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
