### ISSUE TITLE
--env-file is still not working.

### ISSUE THREAD

**Issue by vrathore18** [docker/compose#7695]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
```

## Steps to reproduce the issue

Docker-compose.yaml
```
version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    env_file:
      - test1.env

```
test1.env
foo=bar

test2.env
foo=test

### Observed result
even running `docker-compose --env-file test2.env up`

I see the env variable foo value inside the container is
foo=bar
### Expected result
foo=test
