### ISSUE TITLE
Named volumes with a user defined path fails on second docker-compose up

### ISSUE THREAD

**Issue by Shadow58624** [docker/compose#7700]
## Description of the issue
Named volumes with a user defined path fails on second `docker-compose up`.
If the volumes don't exist yet, the command works with no problem but if you try to `up` again or do `down` and `up` again it fails to because it thinks `G:\Videos` is different than `/host_mnt/g/videos`
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020   
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
  filebrowser:
    container_name: filebrowser
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Lisbon
    hostname: filebrowser
    image: hurlenko/filebrowser
    ports:
    - published: 1102
      target: 8080
    restart: always
    volumes:
    - /c/_docker/data/filebrowser:/config:rw
    - movie1:/data/movies/g:rw
    - /c/_docker/data/_shared:/shared:rw
version: '3.8'
volumes:
  movie1:
    driver: local
    driver_opts:
      device: G:\Videos
      o: bind
      type: none
    name: movie1
```

## Steps to reproduce the issue

1. docker-compose up -d
2. docker-compose up -d
3.

### Observed result

It fails to recognize the G: drive is the same as /host_mnt/g

### Expected result

Compose starts without errors

### Stacktrace / full error message

```
ERROR: Encountered errors while bringing up the project.
 "device" driver_opt (/host_mnt/g/Videos). If you wish to use the new configuration, please remove the existing volume "movie1" 
first:
$ docker volume rm movie1
```

## Additional information

![docker bug](https://user-images.githubusercontent.com/29847057/90954884-86f69b00-e470-11ea-9bc9-7ec9b1cc99f0.png)

OS version / distribution, `docker-compose` install method, etc.
