### ISSUE TITLE
Error when using a remote ssh context running under Ubuntu

### ISSUE THREAD

**Issue by PalatinCoder** [docker/compose#7702]
## Description of the issue

Running docker-compose on windows against a remote context (Ubuntu bionic server) via ssh results in an error saying it couldn't connect to the Docker daemon. The Docker daemon is running, which can easily be verified by running `docker ps`. Furthermore, the ssh connection is in fact working. As you can see in the  attached [verbose](https://github.com/docker/compose/files/5114043/verbose.txt) output, there are some successful requests until it hits the error at this call: `compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('fd1b13a88d2ff7e4444633fb39b726c53bec864d1d8e79a50ca4537ea392cfb5')`

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  internal: {}
  public: {}
services:
  cache:
    image: redis:alpine
    networks:
      internal: null
    restart: unless-stopped
    volumes:
    - cache:/data:rw
  db:
    image: mariadb
    networks:
      internal: null
    restart: unless-stopped
    volumes:
    - db:/var/lib/mysql:rw
  neos:
    build:
      args:
        context: production
      context: (..)
    depends_on:
    - cache
    - db
    image: neos:prod
    networks:
      internal: null
      public: null
    restart: unless-stopped
    volumes:
    - data:/neos/Data/Persistent/:rw
version: '3.4'
volumes:
  cache: {}
  data: {}
  db: {}
```

## Steps to reproduce the issue

1. Create a docker context against Ubuntu bionic server via ssh
2. Raise `MaxSessions` on the ssh server to mitigate the known issue with to many connections
3. Set the context active `docker context use ubuntu` and run `docker-compose ps` OR run `docker-compose --context ubuntu ps`

### Observed result
Error message
### Expected result
List of running containers
### Stacktrace / full error message (see also [verbose.txt](https://github.com/docker/compose/files/5114043/verbose.txt))

```
ERROR: Couldn't connect to Docker daemon at http+docker://ssh - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

## Additional information

I read about the issue with MaxSessions on the ssh server, so I raised that value, but didn't make a difference. Also, I tried it with sshd's LogLevel set to DEBUG3. It said that there was a session opened with six channels. It started to send data until channel 6 was closed suddenly (apparently client-side). There was no indication that sshd was limiting something here. Also, I tried it with disabled firewall on the server, as it could potentially limit connections - again with no luck.

When using another remote machine, which is running Fedora CoreOS, everything works as expected. The fcos machine is running the following versions: 
```
Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.3
  Git commit:       42e35e6
  Built:            Sun Jun  7 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3
  GitCommit:
 runc:
  Version:          1.0.0-rc10+dev
  GitCommit:        fbdbaf85ecbc0e077f336c03062710435607dbf1
 docker-init:
  Version:          0.18.0
  GitCommit:
```
