### ISSUE TITLE
Go errors and says that db table doesn't exist when it is created in the entrypoint script

### ISSUE THREAD

**Issue by DGKSK8LIFE** [docker/compose#7704]
## Description of the issue

When spinning up mysql with docker-compose, I run the entrypoint script to create my DB and DB tables:
```
    mysql-container:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: Scout_DB
        container_name: db
        ports:
            - 6000:6000
        volumes: 
            - database_mysql:/var/lib/mysql
            - ./backend:/app/db-init.sql
        networks:
            - fullstack
```
Everything seems fine and dandy but when I try to transact with a DB table in go, my go service throws this error: 
`go_1               | 2020/08/24 13:37:00 Prepare err Error 1146: Table 'Scout_DB.Recording' doesn't exist`

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build unknown
```

**Output of `docker version`**
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
> sudo docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  fullstack:
    driver: bridge
services:
  go:
    build:
      context: /home/tarekali/code/awtybots-scouting-app/backend
      dockerfile: Dockerfile
    depends_on:
    - mysql-container
    networks:
      fullstack: null
    ports:
    - 8080:8080/tcp
    volumes:
    - /home/tarekali/code/awtybots-scouting-app/backend:/app:rw
  mysql-container:
    container_name: db
    environment:
      MYSQL_DATABASE: Scout_DB
      MYSQL_ROOT_PASSWORD: root
    image: mysql
    networks:
      fullstack: null
    ports:
    - 6000:6000/tcp
    volumes:
    - database_mysql:/var/lib/mysql:rw
    - /home/tarekali/code/awtybots-scouting-app/backend:/app/db-init.sql:rw
version: '3.0'
volumes:
  database_mysql: {}
```

## Steps to reproduce the issue

1. Add a mysql service in docker-compose (using the `mysql` image)
2. Make sure the mysql service runs more than one entrypoint script (said entrypoint script must create a database and a table)
3. Try to access the table with go

### Observed result
 
go throws this error: `go_1               | 2020/08/24 13:37:00 Prepare err Error 1146: Table 'Scout_DB.Recording' doesn't exist`

### Expected result

go should transact with the table without any problems/the table should be created

### Stacktrace / full error message

```
mysql-container uses an image, skipping
Building go
Step 1/8 : FROM golang:1.15
 ---> 75605a415539
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 2f057b06d2d6
Step 3/8 : COPY go.mod go.sum ./
 ---> Using cache
 ---> d8f8edf7228d
Step 4/8 : RUN go mod tidy
 ---> Using cache
 ---> 2bcce95c4c73
Step 5/8 : RUN go mod download
 ---> Using cache
 ---> 530ef0cab575
Step 6/8 : COPY . .
 ---> f006a2c083b0
Step 7/8 : EXPOSE 8080
 ---> Running in 0dd1f40b0e5c
Removing intermediate container 0dd1f40b0e5c
 ---> cf5fcef965d4
Step 8/8 : CMD go run main.go
 ---> Running in 79bc3e82348e
Removing intermediate container 79bc3e82348e
 ---> 1e97490b349c
Successfully built 1e97490b349c
Successfully tagged awtybots-scouting-app_go:latest
Recreating db ... done
Recreating awtybots-scouting-app_go_1 ... done
Attaching to db, awtybots-scouting-app_go_1
go_1               | go: downloading github.com/gin-gonic/gin v1.6.3
go_1               | go: downloading github.com/go-sql-driver/mysql v1.5.0
go_1               | go: downloading github.com/jmoiron/sqlx v1.2.0
db                 | 2020-08-24 13:36:55+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.21-1debian10 started.
db                 | 2020-08-24 13:36:55+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db                 | 2020-08-24 13:36:55+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.21-1debian10 started.
db                 | 2020-08-24T13:36:55.610184Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.21) starting as process 1
db                 | 2020-08-24T13:36:55.619174Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db                 | 2020-08-24T13:36:55.791526Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db                 | 2020-08-24T13:36:55.938740Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
go_1               | go: downloading github.com/golang/protobuf v1.3.3
go_1               | go: downloading github.com/ugorji/go v1.1.7
go_1               | go: downloading github.com/mattn/go-isatty v0.0.12
go_1               | go: downloading gopkg.in/yaml.v2 v2.2.8
go_1               | go: downloading github.com/go-playground/validator/v10 v10.2.0
go_1               | go: downloading github.com/gin-contrib/sse v0.1.0
go_1               | go: downloading github.com/ugorji/go/codec v1.1.7
go_1               | go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
db                 | 2020-08-24T13:36:56.010546Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db                 | 2020-08-24T13:36:56.010757Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
go_1               | go: downloading github.com/leodido/go-urn v1.2.0
go_1               | go: downloading github.com/go-playground/universal-translator v0.17.0
db                 | 2020-08-24T13:36:56.013993Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
go_1               | go: downloading github.com/go-playground/locales v0.13.0
db                 | 2020-08-24T13:36:56.052971Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.21'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
go_1               | 2020/08/24 13:37:00 Prepare err Error 1146: Table 'Scout_DB.Recording' doesn't exist
go_1               | exit status 1
awtybots-scouting-app_go_1 exited with code 1
```

## Additional information

Ubuntu LTS 20. Installed docker-compose via apt. MySQL script:

 ```
CREATE DATABASE Scout_DB;
USE Scout_DB;

CREATE TABLE Recording (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    team INT NOT NULL,
    starting_location UNSIGNED TINYINT NOT NULL,
    moved BOOLEAN NOT NULL,
    inner_port SMALLINT NOT NULL,
    outer_port SMALLINT NOT NULL,
    lower_port SMALLINT NOT NULL,
    control_panel_stage_two BOOLEAN,
    control_panel_stage_three BOOLEAN,
    hang_time TINYINT NOT NULL,
    time TIMESTAMP NOT NULL
);
```
