### ISSUE TITLE
Several docker-compose configs and port allocation

### ISSUE THREAD

**Issue by CrazySky2121** [docker/compose#7710]
## Description of the issue

When used several docker-compose with different port allocation docker-compose first of all tries allocate ports from the first config.

For example:

**docker-compose.yml**

```
version: '3'
services:
  some-service:
    build: .
    volumes:
      - .:/some-volume
    command: start_command
    ports:
      - "8080:8080"
```

**docker-compose.prod.yml**

```
version: '3'
services:
  some-service:
    ports:
      - "8999:8080"
```

When we started with command:

```
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
```

docker-compose first of all start to allocate 8080 port. And if it's already allocated by another service fails to start.

But if port free docker-compose started successfully and in the end he will be allocated to 8999.

It's very strange because expected behavior allocate 8999 port at once. And don't try to allocate 8080 port

## Context information (for bug reports)

```
docker-compose version 1.26.2, build eefe0d31
```

```
docker --version
Docker version 19.03.12, build 48a66213fe
```

**Comment by aiordache** [comment]
Hi @CrazySky2121. Can you provide the output from `docker-compose config` please?

**Comment by CrazySky2121** [comment]
Hello @aiordache. Sure

```
services:
  app:
    build:
      context: /home/user/git/myapp
    command: gunicorn -c gunicorn.conf.py controller.app:application
    ports:
    - 8080:8080/tcp
    - 8999:8080/tcp
    volumes:
    - /home/denis/git/myapp:/code:rw
version: '3.0'
```
