### ISSUE TITLE
docker-compose file invalid; Unsupported config option 'scale'

### ISSUE THREAD

**Issue by nated099** [docker/compose#7722]
I'd like to deploy multiples of the same image using docker-compose, but whenever I use the _scale_ option (via command or in the .yaml) to deploy a scaled image fails due to a less than descriptive error; 

```
The Compose file './docker-compose.yml' is invalid because: err: Unsupported config option for services.fluentd: 'scale'
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
[root@nkerrtest04 nkerr]# docker-compose -v
docker-compose version 1.26.2, build eefe0d31
```

**Output of `docker version`**
```
[root@nkerrtest04 nkerr]# docker -v
Docker version 19.03.5, build 633a0ea
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3.4'

services:
 fluentd:
   build: ./fluentd
   volumes:
     - ./fluentd/conf:/fluentd/etc
   restart: always
   scale: 2
   logging:
     options:
       max-size: "200k"
       max-file: "1"
```

## Steps to reproduce the issue

1. sudo docker-compose up -d --build

### Stacktrace / full error message

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.fluentd: 'scale'

```

## Additional information

OS: Centos 7

_This build does work as long as I remove the 'scale: 2' option._
I've also attempted via:
```

"docker-compose up -d --build --scale fluentd=2" 

```
with the same results. I've also tried different .yaml versions, 3.4 to 3.8 with the same results.
