### ISSUE TITLE
docker-compose up -d --force-recreate should also create brand new containers

### ISSUE THREAD

**Issue by willnx** [docker/compose#7723]
**Is your feature request related to a problem? Please describe.**
I was surprised to find that adding a container/service to a `docker-compose.yaml`, then running `docker-compose up -d --force-recreate` did not create the new container. Instead, it only re-created the previously existing ones.

**Describe the solution you'd like**
I'd like to avoid running two command to recreate my application. Currently, I have to run `docker-compose down` and then run `docker-compose up -d` if I add a new container/service to my yaml file.

**Describe alternatives you've considered**
Using an `&&` in my script to bring down everything, then restart it.

**Additional context**
Here's an example yaml file:
```
version: '3'
services:
  proxy:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
```

If I run `docker-compose up -d`, everything works as expected. If I now edit the yaml file to look like this:
```
version: '3'
services:
  proxy:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
  web:
    image: tutum/hello-world
```
And run `docker-compose up -d --force-recreate`, the `web` service doesn't run.
