### ISSUE TITLE
version 1.27.0: volumes contains unsupported option: 'gid'

### ISSUE THREAD

**Issue by micheelengronne** [docker/compose#7733]
# Description of the issue

The version 1.27.0 gives the error `volumes contains unsupported option: 'gid'`.

I have a tmpfs volume mounted as such:

```yaml
      - type: tmpfs
        target: /run/user/1005/
        tmpfs:
          mode: 0700
          uid: 1005
          gid: 1005
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
1.27.0
```

**Output of `docker version`**
```
19.03.12
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
docker-compose up
```

## Steps to reproduce the issue

1. Create a docker-compose.yml file with a volume like this:
```yaml
      - type: tmpfs
        target: /run/user/1005/
        tmpfs:
          mode: 0700
          uid: 1005
          gid: 1005
```
2. run `docker-compose up`

### Observed result
`volumes contains unsupported option: 'gid'`

### Expected result
docker-compose up should run without errors

### Stacktrace / full error message

```
The Compose file './docker-compose.yml' is invalid because:
`volumes contains unsupported option: 'gid'`
```

## Additional information

On ubuntu focal (20.04), docker-compose installed through pip.
