### ISSUE TITLE
docker-compose 1.27.0 appears to have broken using external overlay networks

### ISSUE THREAD

**Issue by briancolecoinmetrics** [docker/compose#7734]
## Description of the issue

```
networks:
  mynetworkname:
    external: true
    driver: overlay
```
produces
```
ERROR: Network mynetworkname declared as external but specifies additional attributes (driver).
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.0, build unknown
docker-py version: 4.3.1
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker version`**
```
docker-compose version 1.27.0, build unknown
docker-py version: 4.3.1
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
root@proxy-staging-8:/opt/demo-compose-bug# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: Network mynetworkname declared as external but specifies additional attributes (driver).
```

## Steps to reproduce the issue

0. Have a swarm overlay network, here named "mynetworkname"
1. `pip3 install docker==4.3.1 docker-compose==1.27.0`
2.
```
mkdir demo && cd demo
cat >> docker-compose.yml << EOF
version: "3.7"
services:
  somecontainer:
    image: alpine
    command: sleep 9999999
    networks:
    - mynetworkname
networks:
  mynetworkname:
    external: true
    driver: overlay
EOF
docker-compose up -d
```

### Observed result

```
ERROR: Network mynetworkname declared as external but specifies additional attributes (driver).
```

### Expected result

```
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating demo_somecontainer_1 ... done
```
(Reverting with `pip3 install docker==4.3.1 docker-compose==1.26.2` fixes and lets me get this again)

### Stacktrace / full error message

Sorry, I don't understand how that's different from "Observed result".

## Additional information

Ubuntu 18.04.5 LTS, installed with pip (see steps to reproduce above).
