### ISSUE TITLE
config command with multiple yaml files excludes max_replicas_per_node

### ISSUE THREAD

**Issue by ticalcster** [docker/compose#7753]
## Description of the issue

When using the `config` command to combine multiple yaml files the placement option for *max_replicas_per_node* gets removed.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.2, build unknown
docker-py version: 4.3.1
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose -f docker-compose.yml -f extra.yml config`**
```
services:
  nginx:
    deploy:
      placement: {}
      replicas: 2
    image: ngine:latest
  test:
    image: postgres
version: '3.8'
```

## Steps to reproduce the issue

1. Create file: *docker-compose.yml*
```
version: '3.8'
services:
  nginx:
    image: ngine:latest
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
```
2. Create file: *extra.yml*
```
version: "3.8"
services:
  test:
    image: postgres

``` 
3. run `docker-compose -f docker-compose.yml -f extra.yml config`

### Observed result
```
services:
  nginx:
    deploy:
      placement: {}
      replicas: 2
    image: ngine:latest
  test:
    image: postgres
version: '3.8'
```

### Expected result
```
services:
  nginx:
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: 2
    image: ngine:latest
  test:
    image: postgres
version: '3.8'
```
