### ISSUE TITLE
`docker-compose stop` doesn't stop things

### ISSUE THREAD

**Issue by WhyNotHugo** [docker/compose#7759]
## Description of the issue

Issuing `docker-compose stop` doesn't stop services. However, it does report them as stopped:

```console
$ docker-compose stop
Stopping REDACTED_frontend_1  ... done
Stopping REDACTED_minio_1     ... done
Stopping REDACTED_memcached_1 ... done
Stopping REDACTED_mailhog_1   ... done
Stopping REDACTED_postgres_1  ... done
Stopping REDACTED_rabbitmq_1  ... done

$ docker-compose stop  # Issuing the same command here.
Stopping REDACTED_minio_1    ... done
Stopping REDACTED_mailhog_1  ... done
Stopping REDACTED_postgres_1 ... done

$ docker-compose stop  # Issuing the same command here.
Stopping REDACTED_minio_1    ... done
Stopping REDACTED_mailhog_1  ... done
Stopping REDACTED_postgres_1 ... done

$  # Several containers are still running at this point.
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```console
$ docker-compose version
docker-compose version 1.26.2, build unknown
docker-py version: 4.3.1
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

```

**Output of `docker version`**
```console
$ docker version
Client:
 Version:           19.03.12-ce
 API version:       1.40
 Go version:        go1.14.5
 Git commit:        48a66213fe
 Built:             Sat Jul 18 01:33:21 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.5
  Git commit:       48a66213fe
  Built:            Sat Jul 18 01:32:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.0.m
  GitCommit:        09814d48d50816305a8e6c1a4ae3e2bcc4ba725a.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  celery:
    build:
      context: /home/hugo/workspace/REDACTED
    command: celery -A idf.core worker -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
    - mailhog
    - memcached
    - postgres
    - rabbitmq
    environment:
      REDACTED: REDACTED
    healthcheck:
      test: /app/scripts/healthcheck-celery
    image: app
    user: django
    volumes:
    - /home/hugo/workspace/REDACTED:/app:ro
    - static:/static:rw
  django:
    build:
      context: /home/hugo/workspace/REDACTED
    command: django-admin runserver 0.0.0.0:8000
    depends_on:
    - frontend
    - mailhog
    - memcached
    - minio
    - postgres
    - rabbitmq
    - translations
    environment:
      REDACTED: REDACTED
    extra_hosts:
    - www.REDACTED.localhost:127.0.0.1
    - static.REDACTED.localhost:127.0.0.1
    healthcheck:
      test: /app/scripts/healthcheck-django
    image: app
    ports:
    - 8000:8000/tcp
    user: django
    volumes:
    - /home/hugo/workspace/REDACTED:/app:rw
    - static:/static:rw
  frontend:
    command: yarn build --watch --dest dists/REDACTED --target app
    environment:
      SASS_PATH: REDACTED
    image: node:latest
    restart: on-failure
    volumes:
    - /home/hugo/workspace/REDACTED:/app:rw
    working_dir: /app
  mailhog:
    healthcheck:
      test: echo | telnet 127.0.0.1 25
    image: mailhog/mailhog
    ports:
    - 8025:8025/tcp
  memcached:
    image: memcached:latest
    ports:
    - 11211:11211/tcp
  minio:
    command: minio server /data
    environment:
      REDACTED: REDACTED
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
    image: minio/minio
    ports:
    - 9000:9000/tcp
    volumes:
    - buckets:/data:rw
  postgres:
    healthcheck:
      test:
      - CMD
      - pg_isready
      - --username
      - postgres
    image: mdillon/postgis:11-alpine
    ports:
    - 5432:5432/tcp
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw
  rabbitmq:
    image: rabbitmq:latest
    ports:
    - 5672:5672/tcp
  translations:
    build:
      context: /home/hugo/workspace/REDACTED
    command: django-admin compilemessages
    environment:
      REDACTED: REDACTED
    image: app
    user: django
    volumes:
    - /home/hugo/workspace/REDACTED:/app:rw
version: '3.0'
volumes:
  buckets: {}
  postgres_data: {}
  static: {}


```

## Steps to reproduce the issue

1. `docker-compose up`
1. `docker-compose stop`

### Observed result

Services should either be stopped, or an error should be reported.

### Expected result

Services don't stop AND `docker-compose` indicates they're stopped (when
they're not!).

## Additional information

Running on ArchLinux:

    Linux aphrodite 5.8.6-arch1-1 #1 SMP PREEMPT Thu, 03 Sep 2020 17:27:39 +0000 x86_64 GNU/Linux
