### ISSUE TITLE
Child services loses network when parent is restarted - with network_mode: "service:parent"

### ISSUE THREAD

**Issue by QuentinC** [docker/compose#7765]
Hello,

Here is a small issue that I am encountering on my system:

## Description of the issue
When two containers share the same network (with network_mode: "service:parent"), and the parent container is restarted, the child container loses network.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.2, build 18f557f9
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3.8'
services:
    parent:
        environment:
            - HOSTNAME=8.8.8.8
            - TIMEOUT=1
        image: willfarrell/ping
    child:
        network_mode: "service:parent"
        environment:
            - HOSTNAME=8.8.8.8
            - TIMEOUT=1
        image: willfarrell/ping
```

## Steps to reproduce the issue

1. docker-compose up -d
2. docker-compose restart parent

### Observed result
Child container won't recover network (Network unreachable)

### Expected result
Child container keeps a working network during and after parent restart

## Additional information
Basic installation on a Debian 10 host. Compose installed with curl command.

**Comment by ulyssessouza** [comment]
Hello @QuentinC ! Thank you for the report!

Actually it doesn't look like a `docker-compose` problem, but an engine issue/behavior. 
I see that even with a `docker restart <container_id>` the network's `Endpoint` (and maybe other properties) changes at the restart of the `parent` and looks like the child doesn't follow it. IMHO the engine should do some background magic to refresh the `Endpoint` (or other properties) when the parent container is restarted.

Can you confirm this @tonistiigi @thaJeztah ?

**Comment by QuentinC** [comment]
Hi !
Thanks for your reply.

This pointed me to the right direction, I've changed my compose file like this:
```
version: '3.8'
services:
    parent:
        network_mode: "service:net"
        environment:
            - HOSTNAME=8.8.8.8
            - TIMEOUT=1
        image: willfarrell/ping
    child:
        network_mode: "service:net"
        environment:
            - HOSTNAME=8.8.8.8
            - TIMEOUT=1
        image: willfarrell/ping
    net:
        image: kubernetes/pause
```

With this "net" container I can restart either parent or child without breaking the network.

Does this must still be considered as a docker or a docker-compose issue ?
