### ISSUE TITLE
1.27.2 does not allow reservations.cpu to be string

### ISSUE THREAD

**Issue by ryanoolala** [docker/compose#7766]
## Description of the issue

docker-compose reservation cpu requires number instead of string, resulting in error when running `docker-compose up` with the following yaml, as extracted from the [documentation](https://docs.docker.com/compose/compose-file/#resources)
```yaml
...
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
```

This error happens in all 1.27.0-1.27.2 releases. Downgrading to 1.26.2 fixes this

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.2, build unknown
docker-py version: 4.2.2
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client:
 Version:           19.03.12-ce
 API version:       1.40
 Go version:        go1.14.5
 Git commit:        48a66213fe
 Built:             Sat Jul 18 01:33:21 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.5
  Git commit:       48a66213fe
  Built:            Sat Jul 18 01:32:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc91
  GitCommit:        24a3cf88a7ae5f4995f6750654c0e2ca61ef4bb2
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    image: redis:alpine
version: '3.8'
```

## Steps to reproduce the issue

1. Upgrade to 1.27.x
2. set reservations.cpu to string '1'
3. `docker-compose up`

### Observed result
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.redis.deploy.resources.reservations.cpus contains an invalid type, it should be a string
```

### Expected result
Redis to start succcessfully

### Stacktrace / full error message

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.redis.deploy.resources.reservations.cpus contains an invalid type, it should be a string
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Arch linux
MacOS

**Comment by ndeloof** [comment]
this regression was introduced by https://github.com/compose-spec/compose-spec/pull/96

**Comment by aiordache** [comment]
My bad, I wanted to align it with what was documented here: https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpus

@ndeloof Do we add string back as an allowed type?

**Comment by ndeloof** [comment]
@aiordache please do, so we maintain backward compatibility

**Comment by brutesque** [comment]
Since this update, docker stack deploy requires strings and docker-compose requires numbers. I can't downgrade docker for mac, so right now i'm unable to use compose locally and deploy the same file on my swarm.

**Comment by aiordache** [comment]
> Since this update, docker stack deploy requires strings and docker-compose requires numbers. I can't downgrade docker for mac, so right now i'm unable to use compose locally and deploy the same file on my swarm.

@brutesque You don't need to downgrade docker for mac, you can try to use an older version of docker-compose (grab binary from the release page) or you can now try the latest that should have the fix.

**Comment by gingerhot** [comment]
I upgrade compose version to `1.27.3`, but when I run `docker-compose -f example.yml config`, the `cpus` value type in `limits` and `reservations` is not consistent in the output, the one in the `limits` is without quote mark as the one in the `reservations` does:

```yaml
services:
  redis:
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 600M
        reservations:
          cpus: '0.10'
          memory: 300M
    image: redis:alpine
version: '3.8'
```

is this a bug or just it is designed to be?

the `example.yml` file:

```
version: "3.8"
services:

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 600M
        reservations:
          cpus: '0.10'
          memory: 300M
```

docker `version`:
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

docker-compose `version`:

```
docker-compose version 1.27.3, build 4092ae5d
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
