### ISSUE TITLE
ADD a GIT directive to Dokerfile language

### ISSUE THREAD

**Issue by gbrault** [docker/compose#7779]
This is just a suggestion! Maybe I missed something...

Let me explain:

In some cases, I need to build docker machine for which part of the code is locate into gits.

Of course I use RUN git ...

But when I update those git, I have to build with --no-cache to make sure I get my latest git verion loaded.

the role of GIT in the dockerfile language would be to check if the git is new and avoid to rebuild the whole machine from scratch...

Thx!

**Comment by ulyssessouza** [comment]
Hello @gbrault ! 
Maybe that's a feature request to buildkit.

**Comment by gbrault** [comment]
thanks @ulyssessouza, could you give me a link to buildkit please?

**Comment by thaJeztah** [comment]
BuildKit is maintained in this repository; https://github.com/moby/buildkit

**Comment by gbrault** [comment]
Thanks @thaJeztah

**Comment by gbrault** [comment]
@thaJeztah @ulyssessouza I have opened [#1700](https://github.com/moby/buildkit/issues/1700) I originally posted in compose as I didn't find buildkit... which I assume is the Dokerfile language project!

**Comment by thaJeztah** [comment]
That said, depending on your situation;

If the git repository you're cloning contains all the source for your project and contains the Dockerfile itself, I would clone the repository, and build from there;

```bash
git clone https://github.com/my/repo.git && docker build repo
```

Docker can even do the cloning, if needed;

```bash
docker build https://github.com/my/repo.git
```

Generally you'd want your Dockerfile to be describing what was built. Taking the "tip" of your git repository means that you lose the information what source was used to build the image. In the situation above, your could set the commit-hash as tag for the image, or (e.g.) set it as an environment variable (via a `--build-arg`) or label on the image;

```bash
git clone https://github.com/my/repo.git
cd repo
docker build --label=git-commit=$(git rev-parse --verify HEAD) .
```

If you need to clone the repository in your Dockerfile itself, and don't want to pass the git-commit / reference for the build, perhaps a trick like this would work;

```dockerfile
ADD https://api.github.com/repos/moby/moby/commits > /last_commit
RUN git clone ....
```

If you use with BuildKit enabled, BuildKit should verify `ETAG` when using `ADD https:// ...`, so invalidate that step if there's a new commit (and force a rebuild of the steps after it)

**Comment by gbrault** [comment]
@thaJeztah, let me elaborate. I have the docker compose stack which does the following
```
version: "2"

services:
  jodpyter:
    image: jodpyter
    build:
      context: ./jodpyter
      args:
         DOLLAR: $$
         SERVERNAME: jodpyter.seadev.xyz
         JODPASSWORD: catherine.vence
    restart: always
    container_name: jodpyter
    volumes:
      - ./volumes/jodpyter:/data
      - ./volumes/jodpyter/.env:/home/jod/project/.env
      - ./volumes/jodpyter/.azureauth:/home/jod/project/.azureauth
    environment:
      - VIRTUAL_HOST=jodpyter.seadev.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=jodpyter.seadev.xyz
      - LETSENCRYPT_EMAIL=gbrault@seadev.org
    networks:
      jod_deploy_jod:
          ipv4_address: 192.168.255.2

  jod:
    image: jod
    build:
      context: ./jod
      args:
         DOLLAR: $$
         SERVERNAME: jod.seadev.xyz
         JODPASSWORD: catherine.vence
         JODPYTER: 192.168.255.2
    restart: always
    depends_on:
      - jodpyter
    container_name: jod
    environment:
      - VIRTUAL_HOST=jod.seadev.xyz
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=jod.seadev.xyz
      - LETSENCRYPT_EMAIL=gbrault@seadev.org
    networks:
      jod_deploy_jod:
          ipv4_address: 192.168.255.3
          
networks:
    jod_deploy_jod:
        external: true
```
