### ISSUE TITLE
config command output changed ports format from long to short

### ISSUE THREAD

**Issue by jritsema** [docker/compose#7782]
## Description of the issue

The `config` command used to output the long port syntax (e.g., below).  `docker-compose version 1.27.2, build 18f557f9` now outputs the short format.  This broke a tool we use that parses the yaml output.  When did this change?

```
    ports:
    - published: 80
      target: 8080
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.2, build 18f557f9
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
docker-compose config
services:
  label-test:
    build:
      context: /Users/foo/bar/
    environment: {}
    image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/label-test:0.1.0
    ports:
    - 8080:8080/tcp
version: '3.7'
```

### Observed result

```
docker-compose config
services:
  label-test:
    build:
      context: /Users/foo/bar/
    environment: {}
    image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/label-test:0.1.0
    ports:
    - 8080:8080/tcp
version: '3.7'
```

### Expected result

```
docker-compose config
services:
  label-test:
    build:
      context: /Users/foo/bar/
    environment: {}
    image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/label-test:0.1.0
    ports:
    - published: 8080
      target: 8080
version: '3.7'
```

## Additional information

docker desktop community version 2.3.0.5 on MacOS
