### ISSUE TITLE
docker volumes check locally and not via docker_host process

### ISSUE THREAD

**Issue by JakeDEvans** [docker/compose#7786]
## Description of the issue
docker-compose fails if volume bind is not available from the system running docker-compose (and ignores the existing path on the remote docker_host) since unnecessary 1.27.3 "feature" for relative paths

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.3, build unknown
docker-py version: 4.3.1
CPython version: 3.8.3
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 16:58:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
```
services:
  nginx:
    image: nginx
    volumes:
    - nginx_data:/etc/nginx/conf.d:rw
version: '2.4'
volumes:
  nginx_data:
    driver_opts:
      device: /srv/test/nginx
      o: bind
      type: none
```

## Steps to reproduce the issue

1. connect to remote docker service over docker-tls
1. create docker-compose file with driver_opts for volume to bind path to volume where volume path is not available locally
1. run docker-compose config (or any docker-compose command)

### Observed result
docker-compose config
ERROR: Device path /srv/test/nginx does not exist.

### Expected result
```
services:
  nginx:
    image: nginx
    volumes:
    - nginx_data:/etc/nginx/conf.d:rw
version: '2.4'
volumes:
  nginx_data:
    driver_opts:
      device: /srv/test/nginx
      o: bind
      type: none
```
