### ISSUE TITLE
Mounting is failing with wsl2

### ISSUE THREAD

**Issue by giorgos321** [docker/compose#7791]
Hi I am using docker-compose on Win 10 with WSL2 and ubuntu 20.04 distro
I'am trying to mount the volume but it keeps failing and I don't know why,

I use docker-compose up and I get:
<------------------------------LOG START------------------------------------------>
Creating network "backend_default" with the default driver
Creating volume "backend_mongo-data" with default driver
Creating backend_mongo_1 ... error
Creating backend_s3_1    ...

ERROR: for backend_mongo_1  Cannot start service mongo: error while mounting volume '/var/lib/docker/volumes/backend_mongo-data/_data': failed to mount local volume: mount /c/Users/hrthe/Desktop/aluplast-data/db:/var/lib/docker/volumes/backCreating backend_s3_1    ... done

ERROR: for mongo  Cannot start service mongo: error while mounting volume '/var/lib/docker/volumes/backend_mongo-data/_data': failed to mount local volume: mount /c/Users/hrthe/Desktop/aluplast-data/db:/var/lib/docker/volumes/backend_mongo-data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
<--------------------------------LOG END------------------------------------------>

My sysinfo:

Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 20
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 6.072GiB
 Name: docker-desktop
 ID: XGKG:Y6DR:KF2O:Y4BY:D2AG:LSHK:BG6J:PUXP:3VZY:EDFB:2DSL:STNT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 50
  Goroutines: 64
  System Time: 2020-09-24T13:12:47.8022126Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

And the docker-ompose.yml I try to run:

version: "3.2"
services:
  mongo:
    image: mongo:3.6
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - "27017:27017"

  s3:
    build: ./s3/
    volumes:
      - /home/user/Desktop/aluplast-data/s3:/fakes3_root
    ports:
      - "4569:4569"

  node:
    restart: always
    build: .
    command: "npm run watch-node dist/server.js"
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/aluplast
      - SECRET=yep
      - NODE_ENV=development
      - AWS_ENDPOINT=s3:4569
      - S3_BUCKET_NAME=myaluplast
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_ACCESS_KEY_ID=alsofake
      - EMAIL_HOST=smtp.zoho.eu
      - EMAIL_USER=test@myaluplast.gr
      - EMAIL_PASSWORD=5NKa7FXkkf8wxlATE9uU
    links:
      - mongo
      - s3
    depends_on:
      - mongo
      - s3
    volumes:
      - ./dist:/files/dist:ro
      - ./emails:/files/emails:ro

volumes:
  mongo-data:
    driver_opts:
      type: none
      device: /c/Users/user/Desktop/aluplast-data/db
      o: bind

I am trying to make it work for the past day

**Comment by tomer-amir** [comment]
I have the same issue in macOS after upgrading to docker desktop 2.4.0.0.

I have a compose file which runs MongoDB using a mounted volume and I got this error:
```
ERROR: for mongo Cannot start service mongo: error while mounting volume '/var/lib/docker/volumes/backend_mongo-data/_data': failed to mount local volume: mount /.../mount/location/:/var/lib/docker/volumes/backend_mongo-data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

Downgraded to `2.2.0.5` and the issue is gone

**Comment by LaXiS96** [comment]
I am experiencing the same issue, but deploying on a remote Linux (RancherOS) host from a Windows 10 1903 machine running Docker Desktop 2.4.0.0. I tested both backends (Hyper-V and WSL2), even though it shouldn't matter since this is a compose issue, and the behaviour is the same.
The following configuration has been working flawlessly up to today, after updating Docker Desktop.

This is a snippet from the compose file:
```
services:
  minio:
    volumes:
      - minio:/data
volumes:
  minio:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/sda3/volumes/minio
```

This is the error:
```
ERROR: Configuration for volume minio specifies "device" driver_opt C:\mnt\sda3\volumes\minio, but a volume with the same name uses a different "device" driver_opt (/mnt/sda3/volumes/minio). If you wish to use the new configuration, please remove the existing volume "ex_minio" first:
$ docker volume rm ex_minio
```
One thing to consider: the server I am deploying to is already running my project, therefore the `minio` volume exists already and is already bind mounted from a previous deploy.

I don't see why compose is now converting the device path to a Windows path before passing it to the remote host...

I believe I could just use an older version of compose, but I'll just revert to 2.3.0.5 until this is fixed.

**Comment by chalmagr** [comment]
Facing the same issue on 2.5.0.1 (MacOS - Catalina)
![image](https://user-images.githubusercontent.com/4968250/101830085-9e2dc700-3af9-11eb-8af1-2f2f85904ea2.png)
```
Creating network "mac-issue_default" with the default driver
Creating volume "mac-issue_data" with default driver
Creating mac-issue_service_1 ... error

ERROR: for mac-issue_service_1  Cannot start service service: error while mounting volume '/var/lib/docker/volumes/mac-issue_data/_data': failed to mount local volume: mount /opt/data:/var/lib/docker/volumes/mac-issue_data/_data, flags: 0x1000: no such file or directory

ERROR: for service  Cannot start service service: error while mounting volume '/var/lib/docker/volumes/mac-issue_data/_data': failed to mount local volume: mount /opt/data:/var/lib/docker/volumes/mac-issue_data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

The issue in my case is happening with a minimal docker-compose.yml is defined as below:

```
version: "3.8"
services:
  service:
    image: centos:7
    volumes:
      - data:/opt/data
    command:
      - /bin/bash
      - -c
      - sleep 5

volumes:
  data:
    driver_opts:
      type: none
      device: /opt/data
      o: bind
```

But running the same using regular `docker run` works fine
`docker run --rm -it -v /opt/data:/opt/data centos:7 /bin/bash -c "sleep 5"`

**Comment by mikazp** [comment]
As temporary solution do not declare named volumes, this works for me:
```
version: '3.8'

services:
  test:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
```

instead of
```
...
volumes:
  source:
    driver_opts:
      type: none
      device: .
      o: bind
```

**Comment by daniel-cohen** [comment]
Still seeing the same problem on WSL:
OS Version:                10.0.19043 N/A Build 19043
Docker version 20.10.8, build 3967b7d

**Comment by Dhyanesh97** [comment]
Encountered same issue with below file.


```
version: "3"
services:
  name:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: name
    restart: always
    volumes:
      - db.sqlite3:/api/db
    ports:
      - 8000:8000
    env_file:
      - secrets.env
volumes:
  db.sqlite3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/xxxxxx/xxxxx/db
```
