### ISSUE TITLE
Unsupported config option for services.server: 'database docker-compose.yml produce this error - need help

### ISSUE THREAD

**Issue by virkse** [docker/compose#7833]
I have two folders docker compos file is at root, i want to compose both client and server and server has further requirement of db, php and nginx etc 
Please have a look, and advance thanks to help me out.

client/*
server/*
.env
docker-compose.yml

```
version: "3.4"

services: 
    client:
        container_name: client
        ports: 
            - 3000:3000
        build: 
            context: 'client'
            dockerfile: Dockerfile
        volumes: 
            - './client:/app'
    server:
        database:
            build:
                context: ./server/docker/database
                dockerfile: Dockerfile
            environment:
                - MYSQL_DATABASE=${DATABASE_NAME}
                - MYSQL_USER=${DATABASE_USER}
                - MYSQL_PASSWORD=${DATABASE_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            ports:
                - "3306:3306"
            volumes:
                - ./server/docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
                - ./server/docker/database/data:/var/lib/mysql
        php-fpm:
            build:
                context: ./server/docker/php-fpm
            depends_on:
                - database
            environment:
                - APP_ENV=${APP_ENV}
                - APP_SECRET=${APP_SECRET}
                - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
            volumes:
                - ./server/symfony:/var/www
        nginx:
            build:
                context: ./server/docker/nginx
            volumes:
                - ./server/symfony:/var/www
                - ./server/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
                - ./server/nginx/sites/:/etc/nginx/sites-available
                - ./server/nginx/conf.d/:/etc/nginx/conf.d
                - ./server/logs:/var/log
            depends_on:
                - php-fpm
            ports:
                - "80:80"
```
