### ISSUE TITLE
Breaking Changes: Internal/External Secrets and Name/Label Problems with External Secrets

### ISSUE THREAD

**Issue by jamiejackson** [docker/compose#7839]
# Description of the issue

### Part 1: External secret clashes with `name` and `label`

Something in the last week or two (docker or docker-compose updates, presumably) has broken my secrets configuration. (Update: It seems that docker-compose version 1.27.0 introduced the problem. Things work up to 1.26.3.)

Because secrets management is awkward with docker-compose (https://github.com/moby/moby/issues/29882) I've had a successful workaround which uses tooling to inspect the compose files and handles of renaming secrets, at deploy time, if their content changes. It's convoluted, but it works great. I don't have to jump through hoops and change compose files in source control when secrets change. I know of other folks in the wild who have similar workarounds.

It is based on a compose file that looks something like this:

```yaml
# docker-compose.yml
version: '3.6'

services:

  myservice:
    image: alpine
    secrets:
      - source: credentials
        target: credentials.json

secrets:
  credentials:
    # my workaround plumbing preprocesses this metadata to create an external secret whose name is based on the secret value

    # a dynamic name is crucial. the env var is supplied later
    name: credentials-${SECRET_SUM_credentials:-0}

    # my workaround plumbing sets this external variable, so yeah, it's external
    external: true

    # my workaround plumbing uses this metadata
    labels:
      # secret name in AWS
      name: "/secret/env/main_cms/${CREDENTIALS_ENV:-CREDENTIALS_ENV}/e2e/credentials"
      # this secret happens to come from parameter store, versus secrets manager
      store: "ssmps"
```

What happens now:

```
$ docker-compose -f docker-compose.yml config
ERROR: Secret credentials declared as external but specifies additional attributes (name, labels).
$ docker-compose -f docker-compose.yml  up
ERROR: Secret credentials declared as external but specifies additional attributes (name, labels).
```

Assuming that this is the breaking change I suspect it is, is there a workaround? A breaking change would be really bad news for us. Please, oh please, don't take away this morsel of extensibility away from the community.

### Part 2: Secret `external` flag not overriding with `true` properly

Here's a second thing that is acting differently. I would expect that if the following compose file were to be layered on top of the one, above, that it would no longer be an external secret. We use this sort of thing for local development, where the secret is just file-based (instead of coming from AWS).

```yaml
# docker-compose-local.yml
version: '3.6'
    
secrets:
  credentials:
    name: credentials-${SECRET_SUM_credentials:-0}
    file: ../support/local_credentials.json
    # i would expect this to override the previous compose and make the secret "not-external"
    external: false
```

However:

```
$ docker-compose -f docker-compose.yml -f docker-compose-local.yml config
ERROR: Secret credentials declared as external but specifies additional attributes (name, labels).
$ docker-compose -f docker-compose.yml -f docker-compose-local.yml up
ERROR: Secret credentials declared as external but specifies additional attributes (name, labels).
```

Even if you're a hard-liner against "part 1," I think you'd have to agree that "part 2" is a bug.

Both of these problems started happening at the same time.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose --version
docker-compose version 1.27.2, build 18f557f9
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

See description.

## Steps to reproduce the issue

See description.

### Observed result

See description.

### Stacktrace / full error message

N/A

## Additional information

Docker Desktop 2.3.0.5 on Mac Catalina 10.15.6
