### ISSUE TITLE
try pull first 

### ISSUE THREAD

**Issue by xenoterracide** [docker/compose#7841]
Problem: I have base images that I want to pull in 1 context (CI), but want to build in another (localdev)

Here's what I'm thinking

```Dockerfile
FROM ${IMAGE} AS main
ENV DB_PORT=5432
ENV DB_HOST=
ENV LIQUIBASE_LOG_LEVEL=info
ENV LIQUIBASE_CONTEXTS=
COPY entrypoint.sh /
COPY changelog /liquibase/changelog
ENTRYPOINT [ "/entrypoint.sh" ]
```

```yaml
&liquibase_image: myorg/image:latest
images:
   liquibase:
      image: *liquibase_image
      build: ...  # same things as what's in services
      pull_first: true
services:
  liquibase:
    build:
      context: ./migrations/liquibase
      args:
        IMAGE: *liquibase-image
      target: main
    image: cloud-stack/migration:latest
```
