### ISSUE TITLE
stacktrace using buildkit

### ISSUE THREAD

**Issue by xenoterracide** [docker/compose#7842]
## Description of the issue

```
#11 [stage-1 2/2] COPY --from=builder /usr/local/share/postgresql/extension/...
#11 DONE 0.3s
[3163] Failed to execute script docker-compose
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 362, in ensure_image_exists
  File "compose/service.py", line 1129, in build
  File "compose/progress_stream.py", line 22, in stream_output
  File "compose/utils.py", line 50, in split_buffer
  File "compose/utils.py", line 26, in stream_as_text
  File "compose/service.py", line 1876, in build
IndexError: list index out of range
Error: Process completed with exit code 255
```

## Context information (for bug reports)

```
docker-compose version 1.27.3, build 4092ae5d
Docker version 19.03.12+azure, build 0ed913b885c8919944a2e4c8d0b80a318a8dd48b
services:
  db:
    build:
      context: /home/runner/work/services/services/postgres
    environment:
      POSTGRES_DB: production
      POSTGRES_PASSWORD: DontUseThisPassword
      POSTGRES_USER: postgres
    image: cloud-stack/postgres:latest
    networks:
      default:
        aliases:
        - db.host
    ports:
    - 5432:5432/tcp
  liquibase:
    build:
      context: /home/runner/work/services/services/migrations/liquibase
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: db.host
      DB_PASSWORD: DontUseThisPassword
      DB_USERNAME: postgres
      LIQUIBASE_CONTEXTS: test
    image: cloud-stack/service-db-main-migration:latest
    networks:
      default: null
    volumes:
    - /home/runner/work/services/services/migrations/liquibase/changelog:/liquibase/changelog:rw
  rabbitmq:
    build:
      context: /home/runner/work/services/services/rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: HoppingDownTheBunnyTrail
      RABBITMQ_DEFAULT_USER: PeterCottontail
    image: cloud-stack/rabbitmq:latest
    networks:
      default:
        aliases:
        - rabbitmq.host
    ports:
    - 1883:1883/tcp
    - 5672:5672/tcp
    - 15672:15672/tcp
version: '3.7'
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
```
Linux fv-az184 5.4.0-1025-azure #25~18.04.1-Ubuntu SMP Sat Sep 5 15:28:57 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

this is running in a github workflow, here's the relevant workflow information

```yaml
name: Main
on:
  schedule:
    - cron: '0 6 * * *'
  push:
jobs:
  build-postgres:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: ./.github/actions/git-short-ref
        id: ref
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
      - uses: docker/build-push-action@v2
        with:
          context: postgres
          file: postgres/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/cloud-stack/postgres:${{ steps.ref.outputs.ref }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        if: failure() && !contains( github.ref, 'feature' )
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: You have failed this project!
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEV_NOTIFICATIONS_WEBHOOK }}

  build-migrations:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        with:
          context: migrations/liquibase
          file: migrations/liquibase/Dockerfile
          tags: cloud-stack/service-db-migrations:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        if: failure() && !contains( github.ref, 'feature' )
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: You have failed this project!
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEV_NOTIFICATIONS_WEBHOOK }}

  test-migrations:
    needs: [build-postgres, build-migrations]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - run: docker-compose --version && docker --version && docker-compose config
      - run: docker-compose up db liquibase
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
      - run: cd migrations/test && docker-compose up
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        if: failure() && !contains( github.ref, 'feature' )
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: You have failed this project!
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEV_NOTIFICATIONS_WEBHOOK }}
```

and docker files

```Dockerfile
FROM postgis/postgis:11-2.5-alpine AS builder
ENV PGTAP_VERSION '1.1.0'
RUN apk add --update-cache build-base git perl
RUN git clone https://github.com/theory/pgtap.git
WORKDIR pgtap
RUN git checkout v$PGTAP_VERSION
RUN make
RUN make install

FROM postgis/postgis:11-2.5-alpine
ENV DEST /usr/local/share/postgresql/extension/
COPY --from=builder $DEST $DEST
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 5432
CMD ["postgres"]

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "pg_isready", "--host=localhost", "--username=postgres", "--dbname=production" ]
```
```Dockerfile
FROM alpine:latest AS waitforit
RUN apk add wget
RUN mkdir /root/src
WORKDIR /root/src
RUN wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
RUN chmod +x wait-for-it.sh

FROM liquibase/liquibase:latest
USER root
ENV DB_PORT=5432
ENV DB_HOST=
ENV LIQUIBASE_LOG_LEVEL=info
ENV LIQUIBASE_CONTEXTS=
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
COPY --from=waitforit /root/src /liquibase
COPY entrypoint.sh /
COPY changelog /liquibase/changelog
USER liquibase
ENTRYPOINT [ "/entrypoint.sh" ]
```

sorry that this is probably more information than a minimal reproduction, hopefully you can reproduce.

**Comment by RevolutionTech** [comment]
I'm running into a similar stacktrace in version 1.28.6:
```
> docker-compose version
docker-compose version 1.28.6, build 5db8d86f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

Here is the stacktrace:
```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 201, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 366, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1131, in build
  File "compose/progress_stream.py", line 22, in stream_output
  File "compose/utils.py", line 50, in split_buffer
  File "compose/utils.py", line 26, in stream_as_text
  File "compose/service.py", line 1905, in build
IndexError: list index out of range
[26903] Failed to execute script docker-compose
```

In my case I am using the Apple Silicon Tech Preview for Docker Desktop (RC 2) on an M1 so I'm not sure if that is related to my issue or not.

**Comment by maggie0002** [comment]
Same issue using BuildKit on GitHub Actions, but with a minimal compose file. It runs fine all the way until the launch at the end. 

Compose:

```
version: '3.4'

services:
    build:
        build:
            context: .
            dockerfile: Dockerfile.build
        volumes:
            - './frontend/apps/file-manager/dist:/export/filemanager'
            - './frontend/apps/interface/dist/spa:/export/interface'
            - './controller/apps/wifi-connect/ui/build:/export/controller'

```

Dockerfile:

...

```
# Copy built content ready for adding to folders

COPY --from=filemanager-buildstep /build-context/dist /build/filemanager

COPY --from=interface-buildstep /build-context/dist/spa /build/interface

COPY --from=controller-wifi-buildstep /build-context/build /build/controller

# On start of the container, copy the content into the mounted directoies

CMD rm -rf /export/filemanager/* && \
    rm -rf /export/interface/* && \
    rm -rf /export/controller/* && \
    cp -Rf /build/* /export/ && \  
    echo "Build complete and files added to directories. Check the logs above for build errors."
```


```
[2006] Failed to execute script docker-compose
515
Traceback (most recent call last):
516
  File "docker-compose", line 3, in <module>
517
  File "compose/cli/main.py", line 80, in main
518
  File "compose/cli/main.py", line 192, in perform_command
519
  File "compose/metrics/decorator.py", line 18, in wrapper
520
  File "compose/cli/main.py", line 1165, in up
521
  File "compose/cli/main.py", line 1161, in up
522
  File "compose/project.py", line 664, in up
523
  File "compose/service.py", line 347, in ensure_image_exists
524
  File "compose/service.py", line 1131, in build
525
  File "compose/progress_stream.py", line 22, in stream_output
526
  File "compose/utils.py", line 50, in split_buffer
527
  File "compose/utils.py", line 26, in stream_as_text
528
  File "compose/service.py", line 1903, in build
529
IndexError: list index out of range
530
Error: Process completed with exit code 255.
```
