### ISSUE TITLE
compose file version 3.8 not recognized on Debian buster

### ISSUE THREAD

**Issue by morremeyer** [docker/compose#7844]
## Description of the issue

The docker-compose file version `3.8` is not recognized on Debian buster despite running on docker engine `19.03`.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Output of `docker-compose config`**
```
services:
  ghost:
    environment:
      url: http://localhost:8080
    image: ghost:3.35.3-alpine
    ports:
    - published: 8080
      target: 2368
    restart: always
    volumes:
    - ghost-data:/var/lib/ghost/content:rw
version: '3.6'
volumes:
  ghost-data: {}
```

`docker-compose.yml`:

```
version: "3.8"

services:
  ghost:
    image: ghost:3.35.3-alpine
    restart: always
    volumes:
      - ghost-data:/var/lib/ghost/content
    ports:
      - 8080:2368
    environment:
      url: http://localhost:8080

volumes:
  ghost-data:
``` 

## Steps to reproduce the issue

1. Run an up-to-date installation of Debian buster with docker installed
2. Try to `docker-compose ps`

### Observed result

This also occurs with `version: "3.7"`. All versions below are fine.

### Expected result

`docker-compose` works with file version 3.8 and engine version `19.03.13` as described in https://docs.docker.com/compose/compose-file/

### Stacktrace / full error message

``` 
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

## Additional information

* Running on fully updated Debian buster
* docker-ce and docker-compose are installed via the official docker repository at https://download.docker.com/linux/debian
