### ISSUE TITLE
Bind mount never find host files or directories in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by lauyilouis** [docker/compose#7854]
## Description of the issue
Bind mount of docker-compose can never find host files or directories in Ubuntu 20.04 LTS. It instead create directories with the same name of the host path. Same docker and docker compose version and config files with Ubuntu 18.04.5 LTS works.

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    image: [any image]
    ports:
    - published: 80
      target: 4000
    volumes:
    - ./firebase-adminsdk-pk.json:/tmp/keys/firebase-adminsdk-pk.json:ro
```

## Steps to reproduce the issue

1. copy a json file with random content and name it `firebase-adminsdk-pk.json`.
2. run `docker-compose up -d` to spin up the service with any images.
3. run `docker-compose exec app cat /tmp/keys/firebase-adminsdk-pk.json` to examine the file.

### Observed result
The terminal will prompt something similar to `read error: firebase-adminsdk-pk.json Is a directory`. This is because the docker compose cannot find the host file and then create a folder named with the host file instead.

### Expected result
The content of the JSON file should be displayed.

OS version
Ubuntu 20.04.01 LTS (tried at Google Cloud Computing and Window WSL)
