### ISSUE TITLE
node_module's content is hidden on Ubuntu

### ISSUE THREAD

**Issue by samandera** [docker/compose#7858]
## Description of the issue
OS: Ubuntu 20.04.1 LTS
The content of node_module's directory is hidden from every place except docker container (checked in terminal, Atom editor and GUI files app)
I was able to make content visible by following steps in [this comment](https://github.com/api-platform/api-platform/issues/1155#issuecomment-496453705), however it's a hack and it should't be set this way.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
1.26.2
```

**Output of `docker version`**
```
19.03.13
```

**`docker-compose.yml` excerpt**
```
services:
  dev:
    ...
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ...
```

**Output of `docker-compose config`**
```
services:
  dev:
    ...
    tty: true
    volumes:
    - /path/to/app/directory:/app:rw
    - node_modules:/app/node_modules:rw
  ...

```

## Steps to reproduce the issue

Run npm install inside docker container on Ubuntu with docker-compose using setting from the excerpt.

### Observed result
Empty node_modules folder. All other ignored/hidden folders are able to display their content.

### Expected result
Filled node_modules folder.
