### ISSUE TITLE
Environment variable VIRTUAL_ENV not passed to container

### ISSUE THREAD

**Issue by jnns** [docker/compose#7861]
## Preface

I hope that what I'm reporting is not just a user error. If it is, then I'm really sorry for the noise. I did my best to see where my setup could be flawed and didn't find anything.

## Description of the issue

I'm trying to pass on an environment variable called `VIRTUAL_ENV` to a container just like documentation suggests:

> You can also pass a variable through from the shell by not giving it a value:
> 
> ```docker-compose run -e DEBUG web python console.py```
>
> The value of the DEBUG variable in the container is taken from the value for the same variable in the shell in which Compose is run.

The problem is that it only works with variables not named `VIRTUAL_ENV`. Please refer to the minimal reproducible example  below. 

```yaml
version: '3.8'

services:
  test:
    image: alpine
    environment:
      - VIRTUAL_ENV
      - VIRTUAL_ENV1
      - VIRTUAL_ENV2
    command: sh -c 'env | grep VIRTUAL'
```

Fish shows that the variable is actually exported in the calling shell:

```sh
set --show VIRTUAL_ENV
$VIRTUAL_ENV: not set in local scope
$VIRTUAL_ENV: set in global scope, exported, with 1 elements
$VIRTUAL_ENV[1]: length=3 value=|foo|
$VIRTUAL_ENV: not set in universal scope
```

Starting the container just sets all other variables but not the one in question:

```sh
docker-compose run -e VIRTUAL_ENV -e VIRTUAL_ENV1 -e VIRTUAL_ENV2 --rm test 
Creating jnns_test_run ... done
VIRTUAL_ENV1=foo
VIRTUAL_ENV2=foo
```

## Context information (for bug reports)

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**

```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker-compose config`**

```yaml
services:
  test:
    command: sh -c 'env | grep VIRTUAL'
    environment:
      VIRTUAL_ENV: null
      VIRTUAL_ENV1: null
      VIRTUAL_ENV2: null
    image: alpine
version: '3.8'
```

## Steps to reproduce the issue

Run `docker-compose run --rm -e VIRTUAL_ENV=foo -e VIRTUAL_ENV1=foo -e VIRTUAL_ENV2=foo test`

### Observed result

```sh
Creating network "jnns_default" with the default driver
Creating jnns_test_run ... done
VIRTUAL_ENV1=foo
VIRTUAL_ENV2=foo
```

### Expected result
```sh
Creating network "jnns_default" with the default driver
Creating jnns_test_run ... done
VIRTUAL_ENV=foo  # This env variable is not set.
VIRTUAL_ENV1=foo
VIRTUAL_ENV2=foo
```

## Additional information

I've tried the example using Bash 5.0.16 and Fish 3.1.0 and received the same results. I'm using Ubuntu 20.04 LTS "focal" and installed Docker Compose using the method described on the Installation docs:

```sh
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```
