### ISSUE TITLE
Local volumes fail on up.

### ISSUE THREAD

**Issue by cgardens** [docker/compose#7867]
## Description of the issue
Docker compose succeeds on _first_ try with local volumes, but fails to come up on subsequent attempts. It appears compose does not recognize local volumes that it creates.

## Context information (for bug reports)
I think the issue is in this bit of code: https://github.com/docker/compose/blob/master/compose/volume.py#L150-L158. It seems like on the first try it runs through the first branch of the conditional because the volume doesn't exist yet and it successfully creates it. On subsequent runs it runs through the other branch and tries to make sure the volume is configured properly, but fails because that paths don't match. While this code hasn't changed recently, my guess is it might be related to the path that gets passed in from above (perhaps caused by some of the recent changes to support relative paths (in this issue: https://github.com/docker/compose/issues/6343)? 

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
`docker-compose config`
```
services:
  service1:
    command: /bin/sh -c " echo /my_local_volume; "
    image: alpine
    volumes:
    - compose_issue:/my_local_volume:rw
version: '3.7'
volumes:
  compose_issue:
    driver: local
    driver_opts:
      device: /tmp/dev_local
      o: bind
      type: none
    name: dev-local1
```

## Steps to reproduce the issue

here's my `docker-compose.yaml` (simplified for sake of illustrating the issue).
```
version: "3.7"

services:
  service1:
    image: alpine
    command: /bin/sh -c "
      echo /my_local_volume;
      "
    volumes:
      - compose_issue:/my_local_volume

volumes:
  compose_issue:
    name: dev-local1
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tmp/dev_local
```

1. `mkdir -p  /tmp/dev_local`
2. `docker-compose -f docker-compose.yaml up`
4. `docker-compose -f docker-compose.yaml up` (again, after the first one exits successfully)
(the first up succeeds, but then all subsequent ups fail)

### Observed result
* error.

### Expected result
* I expect compose up to run without error.

### Stacktrace / full error message

```
➜  compose_issue git:(master) ✗ docker-compose -f docker-compose.yaml up

Creating volume "dev-local1" with local driver
Pulling service1 (alpine:)...
latest: Pulling from library/alpine
df20fa9351a1: Pull complete
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
Creating compose_issue_service1_1 ... done
Attaching to compose_issue_service1_1
service1_1  | /my_local_volume
compose_issue_service1_1 exited with code 0
➜  compose_issue git:(master) ✗ docker-compose -f docker-compose.yaml up

ERROR: Configuration for volume dev-local1 specifies "device" driver_opt /tmp/dev_local, but a volume with the same name uses a different "device" driver_opt (/host_mnt/private/tmp/dev_local). If you wish to use the new configuration, please remove the existing volume "dev-local1" first:
$ docker volume rm dev-local1
```

## Additional information

Using docker for mac (2.4.0.0). OS: Catalina 10.15.7

Also worth noting that if i I change the device in the volume to `/host_mnt/private/tmp/dev_local` after the first try, things work again. This is not really a viable work around but is probably useful for diagnosing what's going on.

This code worked on previous version so it seems to be an issue introduced in `1.27.4`.
