### ISSUE TITLE
EHOSTUNREACH in production when I can ping host and it works on dev machine

### ISSUE THREAD

**Issue by WebMatrixware** [docker/compose#7880]
## Description of the issue
Simple web app with DB on mysql. Works on dev machine, when `docker-compose up` is run on production machine EHOSTUNREACH error throws when connecting to DB container rather than working. This is despite being able to ping the DB container from the app container that is throwing the error.

## Context information (for bug reports)

**Output of `docker-compose version` for dev**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker-compose version` for prod**
```
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version` for dev**
```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker version` for prod**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:11 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config` for dev**
(Make sure to add the relevant `-f` and other flags)
```
version: "3"

volumes:
  db:
  
services:
  app:
    image: blanning/widow:v1.0.13
    container_name: widow_v1.0.13
    ports:
      - "8585:80"
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      API_PORT: 8585
      API_SERVER: localhost
    stdin_open: true
    tty: true
  
  mysql:
    image: mysql:5
    container_name: mysql-v1
    ports:
      - "34760:3306"
    expose:
      - "3306"
    volumes:
      - "C:/docker/widow/mysql-init:/docker-entrypoint-initdb.d"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: testing
    restart: unless-stopped
    stdin_open: true
    tty: true
```

**Output of `docker-compose config` for prod**
(Make sure to add the relevant `-f` and other flags)
```
version: "3"

volumes:
  db:
  
services:
  app:
    image: blanning/widow:v1.0.13
    container_name: widow_v1.0.13
    ports:
      - "8585:80"
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      API_PORT: 8585
      API_SERVER: net.amc.local
    stdin_open: true
    tty: true
  
  mysql:
    image: mysql:5
    container_name: mysql-v1
    ports:
      - "34760:3306"
    expose:
      - "3306"
    volumes:
      - "C:/docker/widow/mysql-init:/docker-entrypoint-initdb.d"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: testing
    restart: unless-stopped
    stdin_open: true
    tty: true
```

## Steps to reproduce the issue

1.Run `docker-compose up` on production machine

### Observed result

Pings to the name of the db container succeed (tested from docker exec to app container), but calls to the database from the app container fail with EHOSTUNREACH error on syscall "connect"

### Expected result

Connections to the database should work on production server like they do on the dev machine.

### Stacktrace / full error message

```
widow_v1.0.12 | Error: connect EHOSTUNREACH 172.19.0.2:3306
widow_v1.0.12 |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
widow_v1.0.12 |     --------------------
widow_v1.0.12 |     at Protocol._enqueue (/opt/widow/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
widow_v1.0.12 |     at Protocol.handshake (/opt/widow/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
widow_v1.0.12 |     at PoolConnection.connect (/opt/widow/app/node_modules/mysql/lib/Connection.js:116:18)
widow_v1.0.12 |     at Pool.getConnection (/opt/widow/app/node_modules/mysql/lib/Pool.js:48:16)
widow_v1.0.12 |     at Pool.query (/opt/widow/app/node_modules/mysql/lib/Pool.js:202:8)
widow_v1.0.12 |     at /opt/widow/app/node_modules/promise-mysql/lib/helper.js:26:45
widow_v1.0.12 |     at Promise._execute (/opt/widow/app/node_modules/bluebird/js/release/debuggability.js:384:9)
widow_v1.0.12 |     at Promise._resolveFromExecutor (/opt/widow/app/node_modules/bluebird/js/release/promise.js:518:18)
widow_v1.0.12 |     at new Promise (/opt/widow/app/node_modules/bluebird/js/release/promise.js:103:10)
widow_v1.0.12 |     at Pool.promiseCallback (/opt/widow/app/node_modules/promise-mysql/lib/helper.js:8:16)
widow_v1.0.12 |     at pool.query (/opt/widow/app/node_modules/promise-mysql/lib/pool.js:57:32)
widow_v1.0.12 |     at getSystems (/opt/widow/app/handlers.js:36:23)
widow_v1.0.12 |     at exports.Manager.execute (/opt/widow/app/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
widow_v1.0.12 |     at Object.internals.handler (/opt/widow/app/node_modules/@hapi/hapi/lib/handler.js:46:48)
widow_v1.0.12 |     at exports.execute (/opt/widow/app/node_modules/@hapi/hapi/lib/handler.js:31:36)
widow_v1.0.12 |     at Request._lifecycle (/opt/widow/app/node_modules/@hapi/hapi/lib/request.js:370:68) {
widow_v1.0.12 |   errno: -113,
widow_v1.0.12 |   code: 'EHOSTUNREACH',
widow_v1.0.12 |   syscall: 'connect',
widow_v1.0.12 |   address: '172.19.0.2',
widow_v1.0.12 |   port: 3306,
widow_v1.0.12 |   fatal: true
widow_v1.0.12 | }
widow_v1.0.12 | 201021/152021.307, (1603293621307:ec545399a55f:18:kgjjmb36:10019) [response,get,systems] http://0.0.0.0:80: get /systems {"sort":"alpha"} 500 (1064ms)

```

## Additional information

Dev machine is windows 10 workstation running docker for desktop. Production machine is CentOS8 server.
