### ISSUE TITLE
/etc/hosts not updated on restart

### ISSUE THREAD

**Issue by adrianandreias** [docker/compose#7894]
## Description of the issue

`docker-compose restart` does not update `/etc/hosts` inside the container to new value defined in yml

`/etc/hosts` **is updated though** if using `docker-compose down && docker-compose up -d`

I've read about a docker limitation here: https://github.com/docker/compose/issues/696
though the user was no longer able to reproduce it.
Is this still a docker issue?

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Docker version 19.03.11, build 42e35e61f3
```

**Output of `docker-compose config`**

```
services:
  bogus:
    command: tail -f /dev/null
    extra_hosts:
    - somedns.com:8.8.4.4
    image: busybox
version: '3.7'

```

## Steps to reproduce the issue

1. create this docker-compose.yml
```
version: "3.7"

services:
  bogus:
    image: busybox
    command: tail -f /dev/null
    extra_hosts:
      - "somedns.com:8.8.8.8"
```
2. 
```bash
docker-compose up
docker exec -it compose_bogus_1 sh
cat /etc/hosts
...
8.8.8.8	somedns.com  # shows ok
```
CTRL+D # to exit container

3. edit docker-compose.yml and change just two characters in the extra_hosts entry:
```
version: "3.7"

services:
  bogus:
    image: busybox
    command: tail -f /dev/null
    extra_hosts:
      - "somedns.com:8.8.4.4"
```
4. docker-compose restart

### Observed result
5.
```bash
docker exec -it compose_bogus_1 sh
docker exec -it compose_bogus_1 sh
cat /etc/hosts
....
8.8.8.8	somedns.com  # STILL shows initial value:
```

### Expected result

The `/etc/hosts` entry should change on restart to the new value: **8.8.4.4**.

Note that if instead of `docker-compose restart`, these two are used: `doker-compose down ; docker-compose up -d` the entry updates correctly to **8.8.4.4**

## Additional information

Ubuntu 18.04
