### ISSUE TITLE
Extend service with `depends_on` should work 

### ISSUE THREAD

**Issue by superlevure** [docker/compose#7916]
**Is your feature request related to a problem? Please describe.**
Extending services with `depends_on` does not work and fails with:
```
services with 'depends_on' cannot be extended
``` 

**Describe the solution you'd like**
From the documentation: 

> Note: links, volumes_from, and depends_on are never shared between services using extends. These exceptions exist to avoid implicit dependencies—you always define links and volumes_from locally. This ensures dependencies between services are clearly visible when reading the current file. Defining these locally also ensures changes to the referenced file don’t result in breakage.

I interpret this as follows: Extending services with `depends_on` should work, but you have to redefine your dependencies locally. Which would totally make sense to me.

**Describe alternatives you've considered**
I don't want to use multiple `docker-compose.yml` files as there would be no notion of extension of a service (although it is exactly what I want) and it feels like a hacky way to do it. 

**Additional context**
Issue already mentioned:
- https://github.com/docker/compose/issues/3220#issuecomment-275639048
- https://github.com/docker/compose/issues/3220#issuecomment-706766485

**Comment by rishabh-bector** [comment]
When will this be addressed? Why is it impossible to share service configuration between different compose stacks if depends_on is being used? The linked issues have mentioned several possible solutions, such as ignoring depends_on for the extended services.

**Comment by thisismydesign** [comment]
This behavior of `depends_on` would be fine if we could define a sort of "abstract parent service" which is the shared service definition but doesn't actually create a service. Something like

```yml
services:
  web_parent:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    command: service start
    volumes:
      - ./:/app
  
  web:
    extends:
      service: web_parent
    depends_on:
      - db
```

But I don't want `web_parent` to be an actual service. There are some ways around this but they all seem too complicated to me. See recommendations [here](https://stackoverflow.com/questions/37254881/is-there-any-way-to-disable-a-service-in-docker-compose-yml) or using another `docker-compose` file.

Is there a simple way for this where I can keep the definition in 1 file?
