### ISSUE TITLE
Ports Published Dynamically via Range or  {{.Task.Slot}}

### ISSUE THREAD

**Issue by Shinoby92** [docker/compose#7925]
I hope there are enough people out there for this feature request:

- I need to dynamically publish ports of the replicas and wishing to do this with 

```
services:
  image1:
    user: root
    image: image1:latest
    ports:
    - target: 6901
      published: {{.Task.Slot}}
    networks:
      - my-attachable-overlay
....so on 
```

as an example dynamically with the Task Slot property delivered in stack deploy in stack deploy.
