### ISSUE TITLE
docker-compose Unsupported config option 'lables'

### ISSUE THREAD

**Issue by hemna** [docker/compose#7927]
Following the documentation here:
https://docs.docker.com/compose/compose-file/#labels-1

I should be able to use version 3.8 and specify lables to put on the container, but docker-compose fails
complaining that it's not supported.

docker-compose version 1.27.4, build 40524192

```
$  docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.burp: 'lables'
```

My docker-compose.yml

```
version: "3.8"
services:
  burp:
    image: pschiffe/burp-server
    container_name: burp-server
    lables:
        com.centurylinklabs.watchtower.enable:"true"
```
