### ISSUE TITLE
docker-compose doesn't load .env file when is run from outside of compose-file location

### ISSUE THREAD

**Issue by ghominejad** [docker/compose#7928]
## Description of the issue
In the documentation, you've mentioned the default project directory is the location of the docker-compose file.

When current working directory is different, `docker-compose` doesn't load `.env` file. We have to set `--project-directory`.

As you can see the code below, the default directory is not the compose file location but is the current working directory :
https://github.com/docker/compose/blob/8633939080095bc81f03b8a6a517d5c83d0dee93/compose/cli/main.py#L245-L247

## Context information

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose -f ./compose/docker-compose.yaml config`**
```YAML
services:
  srv1:
    environment:
      MY_ENVIRONMENT: ''
    image: alpine
version: '3.1'
```

## Steps to reproduce the issue

1. make `compose` folder 
2. make `docker-compose.yaml` inside the `compose` folder
```YAML
version: '3.1'
services:
  srv1:
    image: alpine
    environment:
       - MY_ENVIRONMENT=${ENVIRONMENT_NAME} 

```
2. make `.env` inside the `compose` folder
```
ENVIRONMENT_NAME=Staging 
```

3. Run `docker-compose -f ./compose/docker-compose.yaml config`
>  And to load .env correctly : `docker-compose -f ./compose/docker-compose.yaml --project-directory ./compose config` 
### Observed result
```YAML
services:
  srv1:
    environment:
      MY_ENVIRONMENT: ''
    image: alpine
version: '3.1'
```
### Expected result
```YAML
services:
  srv1:
    environment:
      MY_ENVIRONMENT: 'Staging'
    image: alpine
version: '3.1'
```
