### ISSUE TITLE
QinQ support

### ISSUE THREAD

**Issue by gcantho** [docker/compose#7941]
Seems that docker compose does not support QinQ. 

The docker command that I usually run is as follows.
`docker network create -d macvlan --gateway=X.X.X.X --subnet=X.X.X.X/XX --ip_range=X.X.X.X/XX -o parent=eth0.20.200 vlan20-200`

When converting over my commands over to docker compose. This is what is included in my yaml.
```
networks:
  qinq_network:
    driver: macvlan
      driver_opts:
        parent: eth0.20.200
      ipam:
        config:
          - subnet: X.X.X.X/XX
            gateway: X.X.X.X
            ip_range: X.X.X.X/XX
```
I have no issues when running the `docker network create` command. However docker-compose throws an Error ` ERROR: required interface name format is: name.vlan_id, ex. eth0.10 for vlan 10, instead received eth0.20.200`

Is there a sugested work around? Can this be supported in future releases/
