### ISSUE TITLE
String interpolation with `-e X=Y`

### ISSUE THREAD

**Issue by uuf6429** [docker/compose#7948]
## Description of the issue

`-e` option of `docker-compose run` does not seem to work for `command` (as expected).

Or perhaps this is intentional but not obvious or sufficiently documented.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  test:
    command:
    - /bin/echo
    - not-set
    environment:
      SOME_VAR: from-dc-env
    image: busybox
version: '3.4'
```

## Steps to reproduce the issue

Given the following `docker-compose.yml`:
```yaml
version: '3.4'
services:
  test:
    image: busybox
    environment:
      SOME_VAR: from-dc-env
    command:
      - /bin/echo
      - ${SOME_VAR-not-set}
```
1. run `docker-compose run -e SOME_VAR=from-arg test` (fails)
2. also run `SOME_VAR=from-env docker-compose run test` (works)

### Observed result
1. ```
   Creating xxx_test_run ... done
   not-set                                           ❌ 
   ```
2. ```
   Creating xxx_test_run ... done
   from-env
   ```

### Expected result
1. ```
   Creating xxx_test_run ... done
   from-arg
   ```
2. ```
   Creating xxx_test_run ... done
   from-env
   ```

### Stacktrace / full error message

n/a

## Additional information
macOS 11.0.1 (Big Sur), `docker-compose` from "Docker for Mac"

I'd like to point out that I ended up using this approach after exhausting several other options that for whatever reason docker-compose does not (fully) implement, namely:
- _disabling certain services (since they're "utility" services that depend on a main service)_ - docker-compose does not support this (#1896)
- _implementing healthchecks on the main service so that the utility services run after it's up and running_ - docker-compose depends_on is (in my opinion) half-baked and [does not support this anymore] and the alternative is to hammer in a "wait" shell script + curl/wget (https://docs.docker.com/compose/compose-file/#depends_on)
- running a service directly hoping docker-compose is intelligent enough to _ignore mandatory variables of unrelated services_ (to no avail)
- spending way too much time to realise that _-e is not supported for `docker-compose up`_

**Comment by aiordache** [comment]
Hi @uuf6429 . You need to escape the env vars (use `$$`) that you don't want to be substituted when processing the Compose file. Try something like this:
```yaml
services:
  test:
    image: alpine
    environment:
      SOME_VAR: from-dc-env
    command: sh -c "/bin/echo $${SOME_VAR-not_set}"
```
or 
```yaml
services:
  test:
    image: alpine
    environment:
      SOME_VAR: from-dc-env
    command:
      - sh
      - -c
      - /bin/echo $${SOME_VAR-not_set}
```
You need a shell to get that variable set according to what you want.
