### ISSUE TITLE
About networks on compose' ipam config

### ISSUE THREAD

**Issue by lpdswing** [docker/compose#7958]
Please post on our forums: https://forums.docker.com for questions about using `docker-compose`.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.
```
networks:
  default:
    name: et-network
    driver_opts:
      com.docker.network.bridge.name: "et0"
    ipam:
      config: 
        - gateway: "172.20.0.1"
          subnet: "172.20.0.0/16"
```

I have a service to use the docker's gateway, if dont  use ipam config static gateway ip,can use a alias replace that like aliases on services -> servicename -> networks -> aliases
