### ISSUE TITLE
ECS 

### ISSUE THREAD

**Issue by mikecsmith** [docker/compose#7961]
## Description of the issue

When running `docker compose --context my-ecs-context --file docker-compose.yml up` I get a `panic: runtime error: slice bounds out of range [:-3]` error.

## Context information (for bug reports)

**Output of `docker-compose version`**
```

```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  my-network: {}
services:
  postgres:
    environment:
      <ENV VARS HERE>
    image: local-docker-registry-image/db:1.0.0
    networks:
      my-network: null
    ports:
    - target: 5432
    volumes:
    - db-data:/var/lib/postgresql/data:rw
  node-app:
    environment:
      <ENV VARS HERE>
    image: local-docker-registry-image/node-app:1.0.0
    networks:
     my-network: null
    ports:
    - published: 80
      target: 80
    volumes:
    - node-app:/srv/app:rw
version: '3.7'
volumes:
  db-data: {}
  node-app: {}
```

## Steps to reproduce the issue

1. Create a docker-compose file with a node app image and a postgres db image
2. Create an ECS context with `docker context`
3. Run `docker compose --context my-ecs-context --file docker-compose.yml up`

### Observed result

Runtime error during ECS stack creation

### Expected result

ECS stack updates should be shown and success message presented

### Stacktrace / full error message

```
[+] Running 8/12
 ⠋ redacted                    CreateInProg...                       11.1s
 ⠿ RedactedTargetGroup                CreateCo...                            0.0s
 ⠋ CloudMap                                CreateInProgress Resourc...            7.1s
 ⠋ RedactedTaskExecutionRole               CreateI...                             7.1s
 ⠿ RedactedTargetGroup              Create...                              1.0s
 ⠋ LoadBalancer                            CreateInProgress Res...                7.1s
 ⠿ LogGroup                                CreateComplete                         2.0s
 ⠿ RedactedNetwork         C...                                   5.0s
 ⠿ Cluster                                 CreateComplete                         6.0s
 ⠋ RedactedFilesystem                        CreateInProgress...                    7.1s
 ⠋ RedactedExecutionRole                 CreateInP...                           7.1s
 ⠋ RedactedFilesystem                        CreateInProgress...                    7.1s
panic: runtime error: slice bounds out of range [:-3]

goroutine 35 [running]:
github.com/docker/compose-cli/progress.lineText(0xc0003e6ed0, 0x23, 0x0, 0x0, 0x1, 0xc000228e40, 0xf, 0x0, 0xbfe98fb9446be1b8, 0x340facf85, ...)
        github.com/docker/compose-cli/progress/tty.go:154 +0x6dc
github.com/docker/compose-cli/progress.(*ttyWriter).print(0xc00007d3b0)
        github.com/docker/compose-cli/progress/tty.go:127 +0x6c9
github.com/docker/compose-cli/progress.(*ttyWriter).Start(0xc00007d3b0, 0x2d7dda0, 0xc000040128, 0x0, 0x0)
        github.com/docker/compose-cli/progress/tty.go:56 +0x59
github.com/docker/compose-cli/progress.Run.func1(0x0, 0x0)
        github.com/docker/compose-cli/progress/writer.go:95 +0x47
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000226a80, 0xc0000c5e60)
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

## Additional information

MacOS Catalina 10.15.7
