### ISSUE TITLE
The actually mounted path on docker machine is not as same as what I specified in docker-compose.yml

### ISSUE THREAD

**Issue by M-cho-dev** [docker/compose#7968]
Please post on our forums: https://forums.docker.com for questions about using `docker-compose`.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

I've got some problem with bind mount directory when i use a docker-compose file.
-------------------------------------------------------------------------------
docker-compose version 1.24.1
Docker version 19.03.8
-------------------------------------------------------------------------------
my docker-compose file
...
```
my-metricbeat:
    restart: always
    image: docker.elastic.co/beats/metricbeat:6.3.2
    logging: *default-logging
    container_name: my-metricbeat
    user: root
    volumes:
    - /proc:/hostfs/proc:ro
    - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:rw
    - ./metricbeat/system.yml:/usr/share/metricbeat/modules.d/system.yml:rw
    - /:/hostfs:ro
    - /srv:/hostfs/srv:ro
    - /var/run/docker.sock:/var/run/docker.sock
    command: " -system.hostfs=/hostfs"
    network_mode: "host"

```
the problem is when i try df -h command on metricbeat container srv filesystem mounted on /etc/hosts instead of /hostfs/srv

```
Filesystem               Size  Used Avail Use% Mounted on
overlay                  368G  114G  236G  33% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/centos-root   40G  3.8G   37G  10% /hostfs
devtmpfs                  32G     0   32G   0% /hostfs/dev
tmpfs                     32G     0   32G   0% /hostfs/dev/shm
tmpfs                     32G     0   32G   0% /hostfs/sys/fs/cgroup
tmpfs                     32G  1.2G   31G   4% /hostfs/run
tmpfs                    6.3G     0  6.3G   0% /hostfs/run/user/1000
/dev/sda1               1014M  193M  822M  19% /hostfs/boot
/dev/mapper/centos-srv   368G  114G  236G  33% /etc/hosts
```
-------------------------------------------------------------------------------
That issue started after I moved docker root path from /var/lib/docker to /srv/docker/root. So /srv directory became the parent dir of docker root.

Could you please help me in sorting this out?

Thanks.
