### ISSUE TITLE
Invalid missing a healthcheck configuration error

### ISSUE THREAD

**Issue by ilkkao** [docker/compose#7973]
## Description of the issue

`docker-compose run` doesn't accept valid version 2.3 `docker-compose.yml` file.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**docker-compose.yml file**
```
version: '2.3'

services:
  one:
    image: hello-world
    healthcheck:
      test: ["CMD", "pwd"]
      interval: 1s
      timeout: 10s
      retries: 30
  two:
    image: hello-world
    depends_on:
      one:
        condition: service_healthy
```

## Steps to reproduce the issue

1. `docker-compose run two`

### Observed result

`ERROR: for two  Service "one" is missing a healthcheck configuration`

### Expected result

```
Starting one_1 ... done

Hello from Docker!
...
```

## Additional information

This error doesn't happen with docker-compose version 1.26.2. Similar bug has existed before in https://github.com/docker/for-mac/issues/1341 Maybe this is a regression from the `Merge 2.x and 3.x compose formats and align with COMPOSE_SPEC schema` change?

`condition: service_healthy` is going away with the version 3 but should work until support for 2.x versions is removed completely I believe.
