### ISSUE TITLE
Mounts denied / file does not exist after docker latest update on MacOs

### ISSUE THREAD

**Issue by jonatasfl** [docker/compose#7990]
## Description of the issue
After update to docker 20.10.0 build 7287ab3 and docker-compose 1.27.4 build 40524192, I’ve got the error:

`ERROR: for 3dcfb1990fce_descarte_server Cannot start service server: Mounts denied: approving /Users/jonataslizandro/Desktop/projetos/descarte/api: file does not exist`

The mentioned path exists and is a folder, not a file.
It’s also occurs in all of my projects thats use docker.

My docker-compose.yml is the same as it worked before the update:

```
version: '3'
services:
  server:
    container_name: descarte_server
    restart: always
    build: '.'
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - ./:/api
    depends_on:
      - database
    links:
      - database
    ports:
      - '3333:3333'

  database:
    image: postgres:12.0-alpine
    container_name: descarte_db
    restart: always
    environment:
      POSTGRES_DB: descarte
      POSTGRES_USER: descarte
      POSTGRES_PASSWORD: descarte
    ports:
      - '5432:5432'
    volumes:
      - descarte-pg:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    descarte-pg:
```
## Context information (for bug reports)

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
services:
  adminer:
    image: adminer
    ports:
    - published: 8080
      target: 8080
    restart: always
  database:
    container_name: descarte_db
    environment:
      POSTGRES_DB: descarte
      POSTGRES_PASSWORD: descarte
      POSTGRES_USER: descarte
    image: postgres:12.0-alpine
    ports:
    - published: 5432
      target: 5432
    restart: always
    volumes:
    - descarte-pg:/var/lib/postgresql/data:rw
  server:
    build:
      context: /Users/jonataslizandro/Desktop/projetos/descarte/api
    container_name: descarte_server
    depends_on:
      database:
        condition: service_started
    entrypoint: ./.docker/entrypoint.sh
    links:
    - database
    ports:
    - published: 3333
      target: 3333
    restart: always
    volumes:
    - /Users/jonataslizandro/Desktop/projetos/descarte/api:/api:rw
version: '3'
volumes:
  descarte-pg: {}
```

## Steps to reproduce the issue

1. Use the same docker-compose.yml
2. run docker-compose up

### Observed result
Error when starting container

### Expected result
All done
### Stacktrace / full error message

```
ERROR: for descarte_server  Cannot start service server: Mounts denied: approving /Users/jonataslizandro/Desktop/projetos/descarte/api: file does not exist

ERROR: for server  Cannot start service server: Mounts denied: approving /Users/jonataslizandro/Desktop/projetos/descarte/api: file does not exist
ERROR: Encountered errors while bringing up the project.
```

## Additional information

MacOs Catalina 10.15.7
