### ISSUE TITLE
DNS may not work if network_mode is not set in the config

### ISSUE THREAD

**Issue by 0x7162** [docker/compose#7992]
## Description of the issue
Some of CentOS setups may experience DNS issues with config below.
I found a work-around to set `network_mode` explicitly to the default value.
Also, I found a similar discussion here (#4177, by @turtlemonvh):
https://github.com/docker/compose/issues/4177#issue-191056655

I noticed just one change after adding the work-around:
at container side `/etc/resolv.conf` takes exact the same values from HOST machine (CentOS).
Without work-around `/etc/resolv.conf` refers to `127.0.x.x`
(which refers to docker implementation of dns forwarding)

## Context information (for bug reports)
Example of config causing DNS issues on some CentOS setups:
(
```
version: "3.8"
services:
  blabla:
    # Set up the build root path, where Dockerfile for this service lives
    build:
      context: ./blabla2
      dockerfile: Dockerfile
    # Keep the container running
    tty: true
    volumes:
      # Let's mount the current directory into the container's /chepuha3
      - ${PWD}/:/chepuha3
```

Example of work-around config:
```
version: "3.8"
services:
  blabla:
   # here: if we'll omit line below - dns may not work correctly
   # setting network_mode to the default value
    network_mode: bridge
    # Set up the build root path, where Dockerfile for this service lives
    build:
      context: ./blabla2
      dockerfile: Dockerfile
    # Keep the container running
    tty: true
    volumes:
      # Let's mount the current directory into the container's /chepuha3
      - ${PWD}/:/chepuha3
```

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:19:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
# Dockerfile
# yml is mentioned in the lines above
FROM python:3.8-slim
WORKDIR /chepuha3
```

## Steps to reproduce the issue
The issue is intermittent and happens on some random CentOS setups only
```
docker-compose -f config.yml down
# change config (remove to reproduce or add network_mode for work-around)
docker-compose -f config.yml up -d
docker exec image_name ping yahoo.com
```

### Observed result
dns is not working, though traffic routes ok

### Expected result
both traffic and dns are working fine

### Stacktrace / full error message
```
N/A
```
