### ISSUE TITLE
Docker-compose unable to send correct context to Dockerfile when not in the same folder

### ISSUE THREAD

**Issue by johmicrot** [docker/compose#7995]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build unknown
```

**Output of `docker version`**
```
docker-compose version 1.27.4, build unknown
docker-py version: 4.4.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  loader:
    build:
      context: /xxx/johnr/git_error/monitoring
      dockerfile: loader/Dockerfile
    command: python loader.py
    container_name: loader
    network_mode: host
    volumes:
    - /home/xxx/git_error/monitoring:/code:rw
version: '3.8'
```
## Docker-compose.yml
```
version: "3.9"
services:
  loader:
    container_name: "loader"
    build:
      context: .
      dockerfile: loader/Dockerfile
    command: python loader.py
    network_mode: "host"
```
## Folder structure
```
docker-compose.yml
loader/Dockerfile
loader/loader.py
loader/requirements.txt
```
## Steps to reproduce the issue

1. git clone from the code I uploaded to this git page https://github.com/johmicrot/docker_compose_error
2. naviage to the directory docker_compose_error
3. type "sudo docker-compose up"

### Observed result

Building loader
Step 1/5 : FROM python:3
 ---> 0611cf846c85
Step 2/5 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> 33e2cbecd4ec
Step 3/5 : COPY requirements.txt /code/
ERROR: Service 'loader' failed to build: COPY failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder084956168/requirements.txt: no such file or directory

### Expected result

The copy location should be from my local drive, but it appears to to be trying to copy from within the container.  What am I doing wrong here?

I am able to get the code to work if I put the docker-compose.yml into the folder "loader" (so it's in the same location as the Dockerfile) and comment out the "dockerfile" line under "build".  I'll be running several services from one docker-compose, with multiple dockerfiles in sub-directories, so I need this to work.

## Additional information
Ubuntu 20.04.1 LTS

**Comment by johmicrot** [comment]
I've found the similar problem here https://github.com/docker/compose/issues/1398#issuecomment-610680896, which has not been addressed

**Comment by johmicrot** [comment]
I was able to fix the issue by changing the docker-compose.yml to 

```
version: "3.9"
services:
  loader:
    container_name: "loader"
    build:
      context: ./loader
    command: python loader.py
    network_mode: "host"
```

Notice how the context is changed to the same location as the dockerfile, and i removed the line specifying the dockerfile name
