### ISSUE TITLE
npm serve -s build cannot get environment values from docker-compose

### ISSUE THREAD

**Issue by SEFI2** [docker/compose#8001]
## Description of the issue
I am using ReactApp and serving it via `serve -s build` after `npm run build`. The evnironment variables are set in `docker-compose`, but `npm serve` cannot recognize them, unless the `.env` file is provided.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 20.10.0, build 7287ab3
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  jobs-backend:
    build:
      context: /Users/kadyrbeknarmamatov/code/jobs-backend
    container_name: jobs-backend-cont
    environment:
      HOST: 0.0.0.0
      MONGO_DB_URI: *mongodb address*
      NODE_ENV: production
      PORT: '8080'
    image: sefi2/jobs-backend
    ports:
    - published: 8080
      target: 8080
  jobs-frontend:
    build:
      context: /Users/kadyrbeknarmamatov/code/jobs-frontend
    container_name: jobs-frontend-cont
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 512M
    environment:
      REACT_APP_BACKEND_API: http://0.0.0.0:8080/graphql
    image: sefi2/jobs-frontend
    ports:
    - published: 3000
      target: 3000
version: '3'
```

## Steps to reproduce the issue
0. Pass environment to react via `REACT_APP_*`
1. docker-compose up --build --force-recreate
2. Go to react frontend
3. It doesn't recognize the 

### Stacktrace / full error message

```
(paste here)
```

## Additional information
MacOS Catalina 10.15.7 (19H114)
