### ISSUE TITLE
docker-compose up --build  , The connection was reset (firefox), curl: (52) Empty reply from server (curl)?

### ISSUE THREAD

**Issue by kerbrose** [docker/compose#8012]
## Description of the issue
when I run `docker-compose up --build` against the following yml file (from repo https://github.com/minhng92/odoo-14-docker-compose)
```yml
version: '2'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
```
I get an error when I try to connect service **odoo14** from the browser `The connection was reset` (firefox) or from curl, `curl: (52) Empty reply from server`. even though I see from logs that the service is working fine.
```bash
$ docker-compose up --build
Starting odoo-14-docker-compose_db_1 ... done
Recreating odoo-14-docker-compose_odoo14_1 ... done
Attaching to odoo-14-docker-compose_db_1, odoo-14-docker-compose_odoo14_1
db_1      | 
db_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1      | 
db_1      | 2020-12-27 01:21:01.219 UTC [1] LOG:  starting PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1      | 2020-12-27 01:21:01.219 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1      | 2020-12-27 01:21:01.219 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1      | 2020-12-27 01:21:01.413 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1      | 2020-12-27 01:21:01.647 UTC [24] LOG:  database system was shut down at 2020-12-27 01:20:49 UTC
db_1      | 2020-12-27 01:21:01.865 UTC [1] LOG:  database system is ready to accept connections
odoo14_1  | ERROR: couldn't create the logfile directory. Logging to the standard output.
odoo14_1  | 2020-12-27 01:21:05,264 1 INFO ? odoo: Odoo version 14.0-20201218 
odoo14_1  | 2020-12-27 01:21:05,265 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
odoo14_1  | 2020-12-27 01:21:05,265 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/mnt/extra-addons'] 
odoo14_1  | 2020-12-27 01:21:05,266 1 INFO ? odoo: database: odoo@db:5432 
odoo14_1  | 2020-12-27 01:21:05,541 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
odoo14_1  | 2020-12-27 01:21:05,745 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
odoo14_1  | 2020-12-27 01:21:05,745 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
odoo14_1  | 2020-12-27 01:21:06,064 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
odoo14_1  | 2020-12-27 01:21:06,069 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 41aea9049c42:8069 
```
I checked various question in stackoverflow they suggested that the service should be bind to address 0.0.0.0. so I made sure in my odoo.conf is bind to such address using `http-interface= 0.0.0.0`. but no success. [odoo by default bind itself to such address by the way](https://www.odoo.com/documentation/14.0/reference/cmdline.html#http).

my `docker ps`
```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                      NAMES
7a8a7fc62e10        odoo:14             "/entrypoint.sh -- -…"   13 minutes ago      Up 13 minutes       0.0.0.0:8069->8069/tcp, 8071-8072/tcp   odoo-14-docker-compose_odoo14_1
3df978eef465        postgres:13         "docker-entrypoint.s…"   13 minutes ago      Up 13 minutes       5432/tcp                                   odoo-14-docker-compose_db_1
```
my `ss -tulpn`
```bash
$ sudo ss -tulpn
[sudo] password for k: 
Netid       State        Recv-Q       Send-Q                                    Local Address:Port                Peer Address:Port       Process                                         
udp         UNCONN       0            0                                               0.0.0.0:48269                    0.0.0.0:*           users:(("dnsmasq",pid=1106,fd=10))             
udp         UNCONN       0            0                                               0.0.0.0:52575                    0.0.0.0:*           users:(("avahi-daemon",pid=720,fd=14))         
udp         UNCONN       0            0                                             127.0.0.1:53                       0.0.0.0:*           users:(("dnsmasq",pid=1106,fd=4))              
udp         UNCONN       0            0                                               0.0.0.0:5353                     0.0.0.0:*           users:(("avahi-daemon",pid=720,fd=12))         
udp         UNCONN       0            0                                                  [::]:44030                       [::]:*           users:(("avahi-daemon",pid=720,fd=15))         
udp         UNCONN       0            0                    [fe80::50b9:23c8:92ab:b113]%wlp3s0:546                         [::]:*           users:(("NetworkManager",pid=724,fd=24))       
udp         UNCONN       0            0                                                  [::]:5353                        [::]:*           users:(("avahi-daemon",pid=720,fd=13))         
tcp         LISTEN       0            4096                                          127.0.0.1:45167                    0.0.0.0:*           users:(("containerd",pid=2923,fd=12))          
tcp         LISTEN       0            32                                            127.0.0.1:53                       0.0.0.0:*           users:(("dnsmasq",pid=1106,fd=5))              
tcp         LISTEN       0            244                                           127.0.0.1:5432                     0.0.0.0:*           users:(("postgres",pid=768,fd=4))              
tcp         LISTEN       0            4096                                                  *:8069                           *:*           users:(("docker-proxy",pid=7612,fd=4))         
tcp         LISTEN       0            244                                               [::1]:5432                        [::]:*           users:(("postgres",pid=768,fd=3))              
```
one more thing I realized when running each container manually using `docker`, it just works fine. as following:
```bash
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:13
docker run -p 8069:8069 --name odoo --link db:db -t odoo:14.0
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build unknown
docker-py version: 4.3.1
CPython version: 3.8.6
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.15.2
 Git commit:        4484c46d9d
 Built:             Sat Sep 26 12:04:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.2
  Git commit:       4484c46d9d
  Built:            Sat Sep 26 12:03:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    image: postgres:13
    restart: always
    volumes:
    - /media/disk3/k/kit/odoo-14-docker-compose/postgresql:/var/lib/postgresql/data:rw
  odoo14:
    command: -- --dev=reload
    depends_on:
      db:
        condition: service_started
    image: odoo:14
    ports:
    - published: 8069
      target: 8069
    restart: always
    tty: true
    volumes:
    - /media/disk3/k/kit/odoo-14-docker-compose/addons:/mnt/extra-addons:rw
    - /media/disk3/k/kit/odoo-14-docker-compose/etc:/etc/odoo:rw
version: '2'
```

## Steps to reproduce the issue

1. run `docker-compose up --build` against the following repo https://github.com/minhng92/odoo-14-docker-compose

### Observed result
[Firefox](https://i.imgur.com/l1B5hcJ.png)
[![Firefox][1]][1]

[Curl](https://i.imgur.com/hQPaoRF.png)
[![Curl][2]][2]

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Linux G580 5.9.11-3-MANJARO / Manjaro Linux 20.2, docker-compose installed from package manager. 
I also tried docker-compose from github

[1]: https://i.imgur.com/l1B5hcJ.png
[2]: https://i.imgur.com/hQPaoRF.png
