### ISSUE TITLE
Default network unexpected behaviour

### ISSUE THREAD

**Issue by adyanth** [docker/compose#8013]
## Description of the issue
When a compose app is created with no networks, as expected, it creates a default network and adds all services to it.
The website [here](https://docs.docker.com/compose/networking/) describes it as:
> By default Compose sets up a single network for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

The issue is when I specify a network for one of the services in the app, the default network breaks. Here is a sample:
```yaml
version: "3"

services:
  db:
    expose:
      - 1234
  web:
    depends_on:
      - db
    expose:
      - 80
    networks:
      - external_load_balancer

networks:
  external_load_balancer:
    external: true
```

I would expect the web service to be connected to the db service. What is see is that the db service is in a default network all by itself, whereas the web service is only the part of the loadbalancer.

Is this expected behaviour? If so, what is the recommended way to add the default created network manually to a service? Or is it just that I have to manually create a default network and add it to both services? I do not want set the default network to external because the db should not be part of it.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:47 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:17 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by enbrnz** [comment]
I have the same issue, and wonder if there is a workaround?

Somehow, even when defining two networks for `web` (`default` + `external`) the web container is still just added to one network. In that case the `default` network.

**Comment by aiordache** [comment]
Hi,
Containers are attached to the networks defined under their service or the default if none is defined.
If we would add all service containers to the default network regardless of their defined networks, we would not be able to define isolated services (all of them could reach each other via the default network). 

To have the web container attached to the default network,  add 'default' to its networks list:

```
...
  web:
    depends_on:
      - db
    expose:
      - 80
    networks:
      - external_load_balancer
      - default

networks:
  external_load_balancer:
    external: true
```
