### ISSUE TITLE
Unsupported config option : 'context'

### ISSUE THREAD

**Issue by CaiJinKen** [docker/compose#8014]
## Description of the issue
$docker-compose up       
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.client: 'context'
Unsupported config option for services.server: 'context'

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.client: 'context'
Unsupported config option for services.server: 'context'
```

**docker-compose.yaml**
```
version: "2.4"
services:
    server:
       context: ./
       build:
          dockerfile: server-dockerfile
       ports:
         - "8081:8081"
       environment:
         ADDR: ":8081"

    client:
       context: ./
       build:
          dockerfile: client-dockerfile
       ports:
         - "8080:8080"
       environment:
         SERVER_ADDR: PLAINTEXT://server:8081
```

## Steps to reproduce the issue

1. I write two dockerfiles named client-dockerfile and server-dockerfile
2. I write docker-compose.yaml at the same dir
3. Exec docker-compose up and failed

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
