### ISSUE TITLE
docker-compose 1.27.4 silent ignore "configs"

### ISSUE THREAD

**Issue by hholst80** [docker/compose#8016]
Docker-compose 1.27.4 silently drops the "configs" section when deploying on a non-swarm.

```
version: '3.8'

services:
  haproxy:
    image: haproxy:2.2
    configs:
      - source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg

configs:
  haproxy.cfg:
    file: ./haproxy/haproxy.cfg
```
