### ISSUE TITLE
Error while creating mount source path, file exists error when using WSL 2

### ISSUE THREAD

**Issue by Shiroh1ge** [docker/compose#8027]
## Description of the issue
Hey guys, I'm not super familiar with Docker, recently I switched from version 2 to version 3 and tried to enable the new WSL 2 based engine. It was working great until I tried to use npm link to develop my local library inside docker, so what I usually do is I create a volume in my docker file and mount it to my local library:

```
services:
  gateway:
    build: ./gateway
    volumes:
      - ./gateway/node_modules/helpers:/usr/src/app/node_modules/helpers
     
 ```
Then inside my local project, I would use ``npm link helpers``, which will link my library project (which is outside of the current one) and then any changes to my library project would be reflected inside docker.

But when I enabled WSL 2, now I get an error after linking the package folder, saying ``file exists``. I pasted the full error below. Note that when I disable WSL 2 and add my drive in the File Sharing settings, this issue doesn't happen. Thanks for the help!

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019

```

**Output of `docker version`**
```
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  gateway:
    build:
      context: E:\Repositories\invest\api\gateway
    hostname: gateway
    networks:
      backend: null
      frontend: null
    ports:
    - published: 8000
      target: 8000
    restart: always
    volumes:
    - E:\Repositories\invest\api\gateway\src:/usr/src/app/src:rw
    - E:\Repositories\invest\api\gateway\package.json:/usr/src/app/package.json:rw
    - E:\Repositories\invest\api\gateway\tsconfig.json:/usr/src/app/tsconfig.json:rw
    - E:\Repositories\invest\api\gateway\node_modules\helpers:/usr/src/app/node_modules/helpers:rw

```

## Steps to reproduce the issue

1. docker-compose up

### Observed result
Docker compose crashes with an error
### Expected result
Docker compose should start up
### Stacktrace / full error message

```
ERROR: for api_gateway_1  Cannot start service gateway: error while creating mount source path '/run/desktop/mnt/host/e/Repositories/invest/api/gateway/node_modules/helpers': mkdir /run/desktop/mnt/host/e/Repositories/invest/api/gateway/node_modules/helpers: file exists

```
