### ISSUE TITLE
Nodejs container cannot connect to PostgreSQL within the docker-compose cluster

### ISSUE THREAD

**Issue by JakobJK** [docker/compose#8031]
# UPDATE

## Problem resolved 

Turns out my PG and Node versions were incompatible. The installed version of PG in my nodejs application was not compatible with the latest version of node. My docker cluster was using the latest version of node. The version I have locally installed on my system was an earlier version of node, which was why I was able to successfully run a separate instance of the node application outside of the container. So the fix was simply to update PG. (Or you can downgrade node, whatever works for you!)

### Original post:

This is a newfound issue in an old repo. I am not sure why things stopped working, but currently, my nodejs container cannot connect to PostgresQL within the docker-compose cluster using the connection string I have used from the beginning of this project.

I am trying to connect using this connection string:  ```postgres://framethrower:framethrower@postgres:5432/framethrower```,

I can connect to the Postgres instance utilizing psql with the credentials set in the environment on port 2345 from outside the cluster.

I can also run a separate instance of my node application outside of the cluster, passing in the DATABASE_URL of the value:  ```postgres://framethrower:framethrower@localhost:2345/framethrower```, which makes that application instance run successfully. 

The node container can successfully ping the database container:
```
PING b12692a58039 (172.20.0.2) 56(84) bytes of data.
64 bytes from framethrower-postgres.framethrower_default (172.20.0.2): icmp_seq=1 ttl=64 time=0.047 ms
64 bytes from framethrower-postgres.framethrower_default (172.20.0.2): icmp_seq=2 ttl=64 time=0.116 ms

--- b12692a58039 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1039ms
rtt min/avg/max/mdev = 0.047/0.081/0.116/0.035 ms
```

I get no error logs within docker-compose I find particularly useful.

I have tried a couple of different versions of docker-desktop, but all versions causes the same issues. I tried to download my repo and jump back to a PR that happened 3 months ago when everything is fine, and the issue is still there.

I am running on big sur :(

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 19.03.13, build 4484c46d9d

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  nginx:
    container_name: framethrower-nginx
    depends_on:
      postgraphile:
        condition: service_started
      pwa:
        condition: service_started
      sbt:
        condition: service_started
    image: nginx
    ports:
    - published: 80
      target: 80
    restart: always
    volumes:
    - /Users/jake/framethrower/docker/nginx/conf.d:/etc/nginx/conf.d:rw
    - /Users/jake/framethrower/docker/nginx/proxy.conf:/etc/nginx/proxy.conf:rw
  postgraphile:
    build:
      context: /Users/jake/framethrower/docker
    command: wait-for-it --strict --timeout=0 postgres:5432 -- npm run start-dev
    container_name: framethrower-postgraphile
    depends_on:
      postgres:
        condition: service_started
    environment:
      DATABASE_URL: postgres://framethrower:framethrower@postgres:5432/framethrower
      JWT_SECRET: secret-123
    ports:
    - published: 5000
      target: 5000
    restart: always
    volumes:
    - /Users/jake/framethrower:/home/node/framethrower:rw
    working_dir: /home/node/framethrower/packages/postgraphile
  postgres:
    container_name: framethrower-postgres
    environment:
      POSTGRES_DB: framethrower
      POSTGRES_PASSWORD: framethrower
      POSTGRES_PORT: '5432'
      POSTGRES_USER: framethrower
    image: postgres:latest
    ports:
    - published: 2345
      target: 5432
    restart: always
    volumes:
    - /Users/jake/framethrower/docker/data:/var/lib/postgresql/data:rw
  pwa:
    build:
      context: /Users/jake/framethrower/docker
    command: wait-for-it --strict --timeout=0 postgraphile:5000 -- npm start
    container_name: framethrower-pwa
    depends_on:
      postgraphile:
        condition: service_started
      sbt:
        condition: service_started
    environment:
      BASEPATH: http://local-pwa.framethrower.io/
      GRAPHQL_ENDPOINT: /graphql
      SERVERLESS: /submit
      STORAGE: /uploaded_files
    ports:
    - published: 3000
      target: 3000
    restart: always
    volumes:
    - /Users/jake/framethrower:/home/node/framethrower:rw
    working_dir: /home/node/framethrower/packages/pwa
  sbt:
    build:
      context: /Users/jake/framethrower/docker
    command: wait-for-it --strict --timeout=0 postgraphile:5000 -- npm start
    container_name: framethrower-submit
    depends_on:
      postgraphile:
        condition: service_started
    ports:
    - published: 4000
      target: 4000
    restart: always
    volumes:
    - /Users/jake/framethrower:/home/node/framethrower:rw
    working_dir: /home/node/framethrower/packages/submit
version: '3.7'
```

## Steps to reproduce the issue

1. Using my docker-compose configuration 
2. run a node application that connects to the Postgres instance
2. using the connection string supplied above

### Observed result

The node container does not output any errors. Just eventually times out. Postgres does not seem to have a clue that node is trying to connect.

### Expected result

I really wish they'd connect <3

## Additional information

I am using an Nginx service to route different requests to different services. could it be there's a change to how Nginx handles routes? I haven't changed those configurations since the beginning of the project though, so it would be weird for it to start erroring out now.

Mac OS Big Sur :(
