### ISSUE TITLE
docker-compose config fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by alexw1982** [docker/compose#8032]
## Description of the issue
"docker-compose -f docker-compose.yml config" fails with following error messages:

```
docker-compose -f docker-compose.yml config
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 120, in perform_command
  File "compose/cli/main.py", line 352, in config
  File "compose/config/serialize.py", line 83, in serialize_config
  File "compose/config/serialize.py", line 53, in denormalize_config
  File "compose/config/serialize.py", line 53, in <listcomp>
  File "compose/config/serialize.py", line 131, in denormalize_service_dict
  File "compose/config/serialize.py", line 101, in serialize_ns_time_value
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[3223416] Failed to execute script docker-compose
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**

```
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 120, in perform_command
  File "compose/cli/main.py", line 352, in config
  File "compose/config/serialize.py", line 83, in serialize_config
  File "compose/config/serialize.py", line 53, in denormalize_config
  File "compose/config/serialize.py", line 53, in <listcomp>
  File "compose/config/serialize.py", line 131, in denormalize_service_dict
  File "compose/config/serialize.py", line 101, in serialize_ns_time_value
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
[3232979] Failed to execute script docker-compose
```

## Steps to reproduce the issue
1.run docker-compose as mentioned above

### Observed result
command fails with error messages above
### Expected result
output of docker-compose config
## Additional information
docker-ce installed via repositories as described on docker website but it also fails with docker.io / docker-compose packages supplied by ubuntu (Ubuntu 20.04.1 LTS)

**Comment by thaJeztah** [comment]
Are you able to share a minimal `docker-compose` file that produces this error?

**Comment by alexw1982** [comment]
Sure, I will post an example later...

**Comment by alexw1982** [comment]
here you go. I tried to remove services and there does not seem to be a specific service that triggers it but rather the number of services (I could be wrong :-) )

```
version: '3.5'

services:

  app-vpn:
    image: dperson/openvpn-client
    container_name: app-vpn
    restart: unless-stopped
    cap_add:
      - net_admin
    environment:
      - TZ=Europe/Berlin
    networks:
      - vpn-net
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn-config/home.ovpn:/vpn/vpn.ovpn
      - ./vpn-config/home-pass:/vpn/pass
    command: '-d'

  whoogle:
    image: benbusby/whoogle-search:beta
    container_name: whoogle-search
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - app-vpn
    network_mode: "service:app-vpn"
    restart: unless-stopped

  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./homer/:/www/assets
    ports:
      - 8085:8080
    networks:
      - web

  seafile-db:
    image: mariadb:10.1
    container_name: seafile-mysql
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=xxx  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
      - TZ=Europe/Berlin
    volumes:
      - ./seafile/mysql-db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  seafile-server:
    image: seafileltd/seafile-mc:latest
    container_name: seafile-server
    restart: unless-stopped
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:80}"
      interval: "3m"
      timeout: 5s"
      start_period: "5s"
      retries: 3
    volumes:
      - ./seafile/data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWORD=xxx  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Europe/Berlin  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - TZ=Europe/Berlin
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=https://xxx # Specifies your host name if https is enabled.
    depends_on:
      - seafile-db
    networks:
      - seafile-net
      - web

  seafile-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: seafile-documentserver
    restart: unless-stopped
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=xxx
      - TZ=Europe/Berlin
    volumes:
      - ./seafile/documentserver-config/local-production-linux.json:/etc/onlyoffice/documentserver/local-production-linux.json
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:80}"
      interval: "3m"
      timeout: 5s"
      start_period: "5s"
      retries: 3
    ports:
      - '88:80'
    networks:
      - seafile-net
      - web

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    environment:
      - ADMIN_TOKEN=xxx
      - DOMAIN=https://xxx
      - SIGNUPS_ALLOWED=false
      - WEBSOCKET_ENABLED=true
      - SMTP_HOST=xxx
      - SMTP_FROM=xxx@xxx
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_EXPLICIT_TLS=true
      - SMTP_USERNAME=xxx
      - SMTP_PASSWORD=xxx
      - LOG_FILE=/data/bitwarden.log
      - TZ=Europe/Berlin
    volumes:
      - ./bitwarden:/data
    restart: unless-stopped
    networks:
      - web

  wetty:
    container_name: wetty
    restart: unless-stopped
    environment:
      - SSHHOST=xxx
      - SSHPORT=xxx
      - SSHAUTH=keyboard-interactive
      - TZ=Europe/Berlin
    expose:
      - 3000
    image: butlerx/wetty
    networks:
      - web

  recipes-db:
    restart: always
    image: postgres:11-alpine
    container_name: recipes-db
    volumes:
      - ./recipes/postgresql:/var/lib/postgresql/data
    env_file:
      - ./recipes/.env
    networks:
      - recipes-net

  recipes-web:
    image: vabene1111/recipes
    container_name: recipes-web
    restart: always
    env_file:
      - ./recipes/.env
    volumes:
      - ./recipes/staticfiles:/opt/recipes/staticfiles
      - ./recipes/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - recipes-db
    networks:
      - recipes-net

  recipes-nginx:
    image: nginx:mainline-alpine
    container_name: recipes-nginx
    restart: always
    ports:
      - 80:80
    env_file:
      - ./recipes/.env
    volumes:
      - ./recipes/nginx/conf.d:/etc/nginx/conf.d
      - ./recipes/staticfiles:/static
      - ./recipes/mediafiles:/media
    depends_on:
      - recipes-web
    networks:
      - web
      - recipes-net

  vikunja-db:
    image: mariadb:10
    container_name: vikunja-db
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      TZ: Europe/Berlin
    volumes:
      - ./vikunja/db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - vikunja-net

  vikunja-api:
    image: vikunja/api
    container_name: vikunja-api
    environment:
      VIKUNJA_DATABASE_HOST: xxx
      VIKUNJA_DATABASE_PASSWORD: xxx
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: root
      VIKUNJA_DATABASE_DATABASE: xxx
      TZ: Europe/Berlin
    volumes:
      - ./vikunja/files:/app/vikunja/files
    depends_on:
      - vikunja-db
    restart: unless-stopped
    networks:
      - web
      - vikunja-net

  vikunja-frontend:
    image: vikunja/frontend
    container_name: vikunja-frontend
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:80}"
      interval: "3m"
      timeout: 5s"
      start_period: "5s"
      retries: 3
    depends_on:
      - vikunja-api
    networks:
      - web
      - vikunja-net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 1 * * *
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=xxx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - watchtower-net

  nginx:
    image: nginx:latest
    container_name: web-nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./ssl:/etc/nginx/ssl
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/default_headers.conf:/etc/nginx/default_headers.conf
      - ./nginx/auth:/etc/nginx/auth
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/logs:/var/log
    env_file:
      - ./recipes/.env
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:443}"
      interval: "3m"
      timeout: 5s"
      start_period: "5s"
      retries: 3
    restart: unless-stopped
    depends_on:
      - authelia
      - ddclient
      - acme
      - seafile-server
      - recipes-nginx
      - vikunja-frontend
      - wetty
      - bitwarden
      - whoogle
    links:
      - app-vpn:whoogle
    networks:
      - web
      - vpn-net
      - media-net

  acme:
    image: neilpang/acme.sh:latest
    container_name: web-acme
    volumes:
      - ./ssl:/acme.sh
    environment:
      - TZ=Europe/Berlin
    command: daemon
    restart: unless-stopped
    networks:
      - web

  ddclient:
    image: linuxserver/ddclient
    container_name: web-ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./ddclient:/config
    restart: unless-stopped
    networks:
      - web

  authelia:
    image: authelia/authelia
    container_name: web-authelia
    volumes:
      - ./authelia:/config
    networks:
      - web
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt
      - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/session
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/config/secrets/smtp

networks:
  seafile-net:
    name: seafile-net
    driver_opts:
       com.docker.network.bridge.name: br-seafile
  recipes-net:
    name: recipes-net
    driver_opts:
       com.docker.network.bridge.name: br-recipes
  vikunja-net:
    name: vikunja-net
    driver_opts:
       com.docker.network.bridge.name: br-vikunja
  watchtower-net:
    name: watchtower-net
    driver_opts:
       com.docker.network.bridge.name: br-watchtower
  web:
    name: web
    driver_opts:
       com.docker.network.bridge.name: br-web
  vpn-net:
    name: vpn-net
    driver_opts:
       com.docker.network.bridge.name: br-vpn
  media-net:
    external:
      name: media-net
```
