### ISSUE TITLE
error build image when context is URL from git repository and dockerfile path is not default

### ISSUE THREAD

**Issue by goshander** [docker/compose#8046]
## Description of the issue

Error build image when context from git and dockerfile path is not default

docker-compose joined URL from git and dockerfile path to temp folder. It is wrong. Temp folder with repo was correctly created

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.0, build d02a7b1a
docker-py version: 4.4.1
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  local:
    driver: bridge
  web:
    driver: bridge
services:
  mqtt_server:
    build:
      context: git@git.server.local:mqtt/mqtt_server.git
      dockerfile: ./docker/production.dockerfile
    container_name: mqtt_server
    environment:
      MQTT_SERVER_HOST: 0.0.0.0
      MQTT_SERVER_PASSWORD: '12345678'
      MQTT_SERVER_PORT: '1883'
      MQTT_SERVER_USER: mqtt
      MQTT_SERVER_WS_PORT: '1884'
      NODE_ENV: development
    image: mqtt_server:dev
    networks:
      local: null
      web: null
    ports:
    - published: 1883
      target: 1883
    - published: 1884
      target: 1884
    restart: unless-stopped
version: '3.4'
```

## Steps to reproduce the issue

1. Use git repository in context by ssh connection
2. Specify not default dockerfile path in build.dockerfile section

### Observed result

Error in context folder path. docker-compose join URL to local folder temp path

### Expected result

Success building image

### Stacktrace / full error message

```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/docker-build-git191303832/git@git.server.local:mqtt: no such file or directory
ERROR: Service 'mqtt_server' failed to build
```

## Additional information

OS version

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Same issue on Windows 10 and private git repo. I think, that error in this file: service.py line 1857
When I use python docker-compose package with this fix (add `not is_url(path)`) all works fine

```python
        if dockerfile and not is_url(path):
            dockerfile = os.path.join(path, dockerfile)
```
