### ISSUE TITLE
Why docker-compose down deletes my data ? postgresdb

### ISSUE THREAD

**Issue by sapkotasuren** [docker/compose#8047]
## I have create volume using docker command: docker volume create postgres, after that i have mention that volume name in my yaml file and set volume->external to true. When my application spinned up i create some data through rest api etc.
After that when i execute command "docker-compose down" and start it again with "docker-compose up, I could't find the data which i have created before.

docker-compose version: 3.9

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3.9'
services:
  app:
    container_name: bsf-quiz-app
    image: sapkotasuren/bsf-quiz
    ports:
      - "443:8443"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bsfQuiz

volumes:
  postgres:
    external: true

```

## Steps to reproduce the issue

1. docker volume create postgres
2. docker-compose up
3. https://localhost/swagger-ui.htm (try posting some data's)
4. https://localhost/api/bsf/quiz/all(you should abe to see some data)
4. docker-compose down
5. docker-compose up (and try to access  https://api/bsf/quiz/1/all => it is empty)

[yamlfile.txt](https://github.com/docker/compose/files/5842812/yamlfile.txt)

### Expected result
should see some previous data
