### ISSUE TITLE
Name resolution bug

### ISSUE THREAD

**Issue by akihirof0005** [docker/compose#8056]
## Description of the issue
If you use the container name for name resolution, the service name will be connected to the other container. Randomly.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.0, build unknown
docker-py version: 4.4.1
CPython version: 3.9.1
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
```

**Output of `docker version`**
```
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        2291f610ae
 Built:             Tue Jan 19 17:19:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       8891c58a43
  Built:            Tue Jan 19 17:18:55 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: "3"
services:
  rest-client:
    container_name: curl
    image: tutum/curl
    command: sleep infinity

  web1:
    container_name: api1
    build: ./api1
    command: ruby main.rb -o 0.0.0.0

  api1:
    container_name: api2
    build: ./api2
    command: ruby main.rb -o 0.0.0.0

networks:
  default:
    name: net1
```

## Steps to reproduce the issue
I have a sample project to reproduce.
```
git clone https://github.com/akihirof0005/Verification-defects.git
cd Verification-defects
docker-compose up -d
docker exec -it curl bash
watch -n 2 curl "http://api1:4567/"
```
### Observed result
This is app1 container!
This is app1 container!
This is app2 container!
This is app2 container!

note:Results change randomly...

### Expected result
This is app1 container!
This is app1 container!
This is app1 container!
This is app1 container!

### Stacktrace / full error message

```
(paste here)
```

## Additional information
api1 and api2 are running on ruby, but this is irrelevant. In fact, when this first happened, it happened in Java.

linux lts kernel 5.4 Docker version 20.10.2 docker-compose version 1.28.0 with ubuntu and archlinux.

https://github.com/akihirof0005/Verification-defects
