### ISSUE TITLE
Shared volume is not quite merged

### ISSUE THREAD

**Issue by jeffrson** [docker/compose#8069]
## Description of the issue

When I have multiple services referencing a common volume this is not correctly merged. Only one of the containers "wins".

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.0, build d02a7b1a
docker-py version: 4.4.1
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  nginx:
    image: nginx:alpine
    volumes:
    - www-static:/var/www:rw
  www1:
    image: www1:latest
    volumes:
    - www-static:/usr/src/app/www:rw
  www2:
    image: www2:latest
    volumes:
    - www-static:/usr/src/app/www:rw
  www3:
    image: www3:latest
    volumes:
    - www-static:/usr/src/app/www:rw
version: '3.8'
volumes:
  www-static: {}
```

## Steps to reproduce the issue

1. Containers www1, www2, www3 contain folders /usr/src/app/www/www{1|2|3}, respectively
2. docker-compose up -d
3. docker exec -it nginx sh

### Observed result

/var/www inside nginx container has only one of www1, www2, www3 subfolders - not necessarily always the same

### Expected result

/var/www inside nginx container has www1, www2 **and** www3
