### ISSUE TITLE
Running compose inside a running container: issues on volume mounting

### ISSUE THREAD

**Issue by lsfera** [docker/compose#8071]
I'm experiencing issues similar to https://github.com/docker/compose/issues/3918
Running compose inside a running dind container works fine.

When switching to host mounted socket - instead - I'm not able to run any compose file having a mounted volume. 
With alpine based image:
i.e:

> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confKFhAhh' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confcBLJIm' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confpnhmAm' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confjpJDLo' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confdaMbPD' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confIBeefg' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confOHMafg' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confNfFJBa' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confnfEdNL' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confEKgjKE' to '/etc/rabbitmq/rabbitmq.conf': Is a directory
> rabbitmq    | sed: can't move '/etc/rabbitmq/rabbitmq.confIcCpig' to '/etc/rabbitmq/rabbitmq.conf': Is a directory

With deb based:
> rabbitmq    | sed: couldn't edit /etc/rabbitmq/rabbitmq.conf: not a regular file

The same happens with other images I tried - mongodb/cassandra

Internal compose:
```
version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15674:15672"
      - "5674:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 15s
      retries: 3
    restart: always
    volumes:
     - /work/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
     - /work/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
 ```

Host compose

 ```
version: '2.4'

services:
  ci-app:
  [.....]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/work
    working_dir: /work
```
Host image 
```
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim 
[...]
#Install docker
COPY --from=docker:latest /usr/local/bin/docker /usr/bin/docker
COPY --from=docker/compose:debian-1.28.0 /usr/local/bin/docker-compose /usr/bin/docker-compose
```

I'm working with LCOW, wsl2 docker desktop v20.10.2 for windows

I provided a working example here: https://github.com/lsfera/compose-tests 

_Originally posted by @lsfera in https://github.com/docker/compose/issues/3918#issuecomment-766807072_
