### ISSUE TITLE
Variable interpolation uses temporary directory for SSL_CERT_FILE variables

### ISSUE THREAD

**Issue by mdomi** [docker/compose#8072]
## Description of the issue

Variables in a compose file containing any case-mixture of "SSL_CERT_FILE" are replaced with a value pointing at a temporary directory during interpolation. Any combination of case results in the same behavior "

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
Output of `docker-compose -f docker-compose.yml config`. `<Username>` value is the redacted Windows user account logged on to my machine.
```
services:
  echo:
    command: /bin/sh -c 'printenv'
    environment:
      MIXED_CASE_SSL_CERT_FILE: C:\Users\<Username>\AppData\Local\Temp\_MEI256402\certifi\cacert.pem
      SSL_CERT_FILE: C:\Users\<Username>\AppData\Local\Temp\_MEI256402\certifi\cacert.pem
      SSL_CERT_FILE_WITH_BEFORE_AFTER: before-C:\Users\<Username>\AppData\Local\Temp\_MEI256402\certifi\cacert.pem-after
    image: library/busybox:latest
version: '3.4'
```

## Steps to reproduce the issue

1. Create a docker-compose.yml file with the following contents:
```
version: '3.4'
services:
  echo:
    image: library/busybox:latest
    environment:
      SSL_CERT_FILE: ${SSL_CERT_FILE:-key.pem}
      SSL_CERT_FILE_WITH_BEFORE_AFTER: before-${SSL_CERT_FILE:-key.pem}-after
      MIXED_CASE_SSL_CERT_FILE: ${sSl_CeRt_FiLe:-key.pem}
    command: /bin/sh -c 'printenv'
```
2. Run `docker-compose -f docker-compose.yml config
3. View output

### Observed result

Interpolated variables of matching any combination of lower-/upper-case "SSL_CERT_FILE" are replaced with a value pointing to a certificate in a temporary directory.

The behavior was originally seen during runtime (docker-compose up) in the container, but appears during config output as well (docker-compose config). Included several examples in the example compose configuration:
1. 1-to-1 environment variable mapping
2. Environment variable with before- and -after context
3. Example with mixed-case "sSl_CeRt_FiLe"

### Expected result

Interpolated variables of matching any combination of lower-/upper-case "SSL_CERT_FILE" should be replaced like other variables.

### Stacktrace / full error message

```
N/A - no stacktrace
```

## Additional information

I've verified there is no `.env` file that could be supplying the template variable, and the _MIE***** value in the path is different every execution of the command, possibly indicating it is not coming from a hard-coded reference.

Also verify my system does not have any matching environment variables that could be supplying that value.

Windows 10 Enterprise
docker-compose installed via Windows installer for Docker Desktop for Windows. Current version installed as update via built-in self-update mechanism.
