### ISSUE TITLE
specify docker files inline (ie Inline dockerfile:)

### ISSUE THREAD

**Issue by lonewarrior556** [docker/compose#8077]
RIght now I have this
```
services:
  app1:
    build:
      context: ../server
      dockerfile: $PWD/a-app1.Dockerfile

  app2:
    build:
      context: ../app
      dockerfile: $PWD/b-app2.Dockerfile

  app3:
    build:
      context: ../cypress
      dockerfile: $PWD/c-app2.Dockerfile
  ```
  
  This requires me to have 3 docker files and jump around to view what's building, even though some of these are really simple. 
I would love to be able to have all the info in my `docker-compose.yml` file

```
services:
  app1:
    build:
      context: ../server
      dockerfile: |
        FROM nginx:alpine
        COPY nginx.conf /etc/nginx/nginx.conf

  app2:
    build:
      context: ../app
      dockerfile: | 
        FROM nodeJS
        COPY . .
        CMD ['npm', 'start']

  app3:
    build:
      context: ../cypress
      dockerfile: | 
        FROM cypress
        COPY . .
  ```

I don't see how it's possible to currently do this

**Comment by jehon** [comment]
That would be great to read "light" dockerfile inside the dockercompose...

**Comment by systemnova** [comment]
Can I second this as a valuable feature.

**Comment by tmbull** [comment]
I would also add that this is a useful feature request. My particular use case is as follows: 

I sometimes run a container in a docker-compose environment that I won't run in a production environment (think postgres container vs. cloud managed DB) and there is some "setup" to the "dev-only" container. Overriding the command/entrypoint can become a little unwieldy.

**Comment by ndeloof** [comment]
this should be discussed on the compose specification https://github.com/compose-spec/compose-spec

**Comment by lonewarrior556** [comment]
I would still love to have this feature

**Comment by hotrungnhan** [comment]
+1

**Comment by arturopriatnyi** [comment]
+1

**Comment by samrocketman** [comment]
Here's a use case.  Let's say I have an app and I want `docker-compose up -d` to hang until the full dev stack is available.  I could use a basic "healthcheck" service whose only purpose is to depend on the readiness of other services.

Here's a hack that would enable that.

```yaml
version: '2.3'

networks:
  internal:
    driver: bridge

services:
  mariadb:
    image: mariadb
    init: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 1s
      retries: 12
      start_period: 3s
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    ports:
      - 127.0.0.1:3306:3306
    networks:
     - internal

  memcached:
    image: memcached
    healthcheck:
      test: ["CMD", "/bin/bash", "-exc", "true < /dev/tcp/localhost/11211"]
      interval: 2s
      timeout: 1s
      retries: 12
      start_period: 3s
    init: true
    ports:
      - 127.0.0.1:11211:11211
    networks:
      - internal

  wait_for_healthy:
    build:
      context: .
      dockerfile: |
        FROM scratch
        CMD ["/sbin/docker-init", "--version"]
    init: true
    depends_on:
      mariadb:
        condition: service_healthy
      memcached:
        condition: service_healthy
```

# Result

`docker-compose up -d` will hang until all services depended on by `wait_for_healthy` are, indeed, healthy.  This provides a small way to enable docker in development scripts proceed only when ready.

**Comment by subuta** [comment]
Just tried `dockerfile_inline` feature and I'll leave a note for those who will read this later.

### Prerequisites

```bash
$ docker-compose --version
Docker Compose version v2.17.2
```

### `docker-compose.yml`

Replace `dockerfile` with `dockerfile_inline` should work.

```yaml
services:
  rails:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/rails/cli
        # Install additional dependencies.
        RUN apt-get update -qq && apt-get install -y default-libmysqlclient-dev libpq-dev
```

**Comment by bluepuma77** [comment]
Implemented in current compose, see https://github.com/docker/compose/issues/3538#issuecomment-1820016899

**Comment by Paxa** [comment]
For dockerfile it was introduced here https://github.com/docker/compose/pull/10343 and works like this:

```yaml
  service_name:
    build:
      context: .
      dockerfile_inline: |
          FROM ruby:3-alpine
          WORKDIR /app
          ...
```
