### ISSUE TITLE
docker-compose doesn't really delete volumes when driver_opts is used 

### ISSUE THREAD

**Issue by m-chaturvedi** [docker/compose#8087]
## Description of the issue

When using docker-compose with volumes placed at custom paths, like kindly suggested here: https://github.com/docker/compose/issues/2957#issuecomment-289478008, the deletion of volume's directory doesn't happen when the services are brought down with `docker-compose -v`.  The volume's directory is removed when the driver is not used.   

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker-compose config`**

```
# Snippet 1
services:
  mysql_db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
      TZ: Asia/Kolkata
    image: mariadb:10.5.8-focal
    volumes:
    - db:/var/lib/mysql:rw
version: '3.2'
volumes:
  db:
    driver: local
    driver_opts:
      device: /mnt/nextcloud_mount/tmp/mysql
      o: bind
      type: none

```

```
# Snippet 2
services:
  mysql_db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
      TZ: Asia/Kolkata
    image: mariadb:10.5.8-focal
    volumes:
    - db_2:/var/lib/mysql:rw
version: '3.2'
volumes:
  db_2: {}

```

## Steps to reproduce the issue

1. Run the two docker-compose using `docker-compose up`. 
2. Inspect the volumes with `docker volume inspect` and note the `Mountpoint:` paths.
3. Stop the services and remove the volumes with `docker compose -v`.
4. Have a look at the volume directories noted in step 2. 

### Observed result
When the volume is stored at default path (Snippet 2), the volume directory is removed.
When the volume is stored at custom path specified by `driver: local` (Snippet 1), the volume directory is not removed. 

### Expected result
The volume stored at custom path should be removed.

## Additional information

- docker-compose installation using `curl` as suggested on the website.

```
$uname -a
Linux chaturvedi-VivoBook 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
