### ISSUE TITLE
I need help for mount volumes

### ISSUE THREAD

**Issue by dexter74** [docker/compose#8095]
Hello,
I would like a little helping hand to assemble the volumes that I created.
These volumes are CIFS and with version 2.4 it worked flawlessly.

I updated Portainer and it supports version 3.8 and the problem is that with the following code, it gives me an error.

i was move my folder Volumes before start a first container .

------------------
#### **Volumes CIFS:**
````
docker volume create --driver local \
        --opt type=cifs \
        --opt device=//XXX.XXX.XXX.XXX/ABCD \
        --opt o=username=MYUSER,password=MYPASSWORD,vers=3.0,file_mode=0777,dir_mode=0777 \
        --name DL

docker volume create --driver local \
        --opt type=cifs \
        --opt device=//XXX.XXX.XXX.XXX/HIJK \
        --opt o=username=MYUSER,password=MYPASSWORD,vers=3.0,file_mode=0777,dir_mode=0777 \
        --name Musique

docker volume create --driver local \
        --opt type=cifs \
        --opt device=//XXX.XXX.XXX.XXX/DEFG \
        --opt o=username=MYUSER,password=MYPASSWORD,vers=3.0,file_mode=0777,dir_mode=0777 \
        --name Video
````
------------------
#### **Old Stack - version Portainer:**
````
version: '2.4'
services:
  Transmission:
    container_name: CN_Transmission
    image: linuxserver/transmission
    restart: 'no'
    environment:
      - PUID=1001
      - PGID=74240
      - TZ=Europe/Paris
      - USER=admin
      - PASS=admin
    ports:
      - 1041:9091
    volumes:
      - Transmission:/config:rw
      - DL:/downloads:rw
      - Musique:/mnt/Musique:ro
      - Video:/mnt/VIdeo:ro
````
------------------
#### **Stack - Portainer 2.10**
````
version: '3.8'
services:
  Transmission:
    container_name: CN_Transmission
    image: linuxserver/transmission
    restart: 'no'
    environment:
      - PUID=1001
      - PGID=74240
      - TZ=Europe/Paris
      - USER=admin
      - PASS=admin
    ports:
      - 1041:9091
    volumes:  
      - Transmission:/config:rw
      - DL:/downloads:rw
      - Musique:/mnt/Musique:ro
      - Video:/mnt/VIdeo:ro
      
volumes:
  Transmission:
  DL:
  Musique:
  Video:
`````

````console
docker inspect DL
````
````
[
    {
        "CreatedAt": "2021-02-01T14:27:22+01:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/home/docker/volumes/DL/_data",
        "Name": "DL",
        "Options": {
            "device": "//XXX.XXX.XXX.XXX/DL",
            "o": "username=XXXX,password=XXXX,vers=3.0,file_mode=0777,dir_mode=0777",
            "type": "cifs"
        },
        "Scope": "local"
    }
]
````

#### **Result:**
````
linuxserver_Video <= This volume is not the share volume. 
linuxserver_DL <= This volume is not the share volume
linuxserver_Musique <= This volume is not the share volume
linuxserver_Transmission <= Volume OK
````
