### ISSUE TITLE
'yes' is not boolean in YAML 1.2 spec

### ISSUE THREAD

**Issue by aleung** [docker/compose#8097]
## Description of the issue

Docker compose reports that the compose file is invalid because an environment variable contains true.

The value of the environment is `yes`. According to YAML 1.2, boolean is `true⎮True⎮TRUE⎮false⎮False⎮FALSE` and `yes` is no longer boolean type.

My docker-compose.yml file is generated by program (using the js module [yaml](https://eemeli.org/yaml)). The yaml library which comply with YAML 1.2 won't enclose `yes` in quotes because it doesn't enclose string in quotes.

I tried to add yaml version 1.2 directive to the head of docker-compose.yml but still got the same error.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.2, build unknown
docker-py version: 4.4.1
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Content of `docker-compose.yml`**
```yaml
%YAML 1.2
---
version: "3"
services:
  zookeeper:
    image: zookeeper
  kafka:
    image: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
```

### Stacktrace / full error message

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.kafka.environment.ALLOW_PLAINTEXT_LISTENER contains true, which is an invalid type, it should be a string, number, or a null
```
