### ISSUE TITLE
Separate STDERR and STDOUT in docker compose output

### ISSUE THREAD

**Issue by raiyanyahya** [docker/compose#8098]
**Is your feature request related to a problem? Please describe.**
Docker compose outputs container stderr output to stdout
Refer to the sample below:
docker-compose.yml :
```yaml
version: "3.3"
services:
  stderr:
    image: alpine
    command: /bin/ash /log_to_stderr.sh
    volumes:
           - ./log_to_stderr.sh:/log_to_stderr.sh
```
log_to_stderr.sh:
```bash
>&2 echo "log to stderr"
echo "log to stdout"
```

Running the bash script separately we get the output:
```bash
❯ ./log_to_stderr.sh 2> /dev/null
log to stdout
```
BUT
when running docker-compose we get:
```bash
❯ docker-compose up 2> /dev/null
Attaching to composeissue_stderr_1
stderr_1  | log to stderr
stderr_1  | log to stdout
composeissue_stderr_1 exited with code 0
```
Note:
Just running the image with docker seems to give us the expected behaviour:
```bash
❯ docker run --rm -v ${PWD}/log_to_stderr.sh:/log_to_stderr.sh alpine /bin/ash /log_to_stderr.sh 2> /dev/null 
log to stdout
```

**Describe the solution you'd like**
Docker compose should use the same output stream as the container.

**Comment by dexter74** [comment]
hello, can you try them:

````yaml
   command: '/log_to_stderr.sh 2> /dev/null'
````

**Comment by dexter74** [comment]
I think a error to line :

````yaml
command: /bin/ash
````

Bash and not ash

**Comment by LennartC** [comment]
Hi Marc,

That's not going to be the issue. 
In the Alpine docker image, bash is not installed by default, but ash is. But it makes no difference whether you use bash or ash.

Example with debian:buster-slim and bash:

```
version: "3.3"
services:
  stderr:
    image: debian:buster-slim
    command: /bin/bash /log_to_stderr.sh
    volumes:
           - ./log_to_stderr.sh:/log_to_stderr.sh
```

```
$ docker-compose up 2> /dev/null
Attaching to composeissue_stderr_1
stderr_1  | log to stdout
stderr_1  | log to stderr
composeissue_stderr_1 exited with code 0
```

The "error" really is with docker compose itself, merging the stdout and stderr stream of the containers.
