### ISSUE TITLE
OSError from python when running `docker-compose build`

### ISSUE THREAD

**Issue by alanbernstein** [docker/compose#8100]
## Description of the issue

OSError from python when running `docker-compose build`

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  data:
    image: alpine
    volumes:
    - certs:/certs:rw
  idk-test:
    build:
      context: /Users/abernstein/src/go/src/github.com/molecula/idk
      dockerfile: Dockerfile-test
    volumes:
    - certs:/certs:rw
  kafka:
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: confluentinc/cp-kafka:5.4.0
    ports:
    - 127.0.0.1:9092:9092/tcp
    volumes:
    - kafka-data:/var/lib/kafka/data:rw
  pilosa:
    environment:
      PILOSA_ADVERTISE: pilosa:10101
      PILOSA_BIND: 0.0.0.0:10101
      PILOSA_BIND_GRPC: 0.0.0.0:20101
      PILOSA_DATA_DIR: /data
    image: moleculacorp/pilosa:master
    ports:
    - 127.0.0.1:10101:10101/tcp
    - 127.0.0.1:20101:20101/tcp
    volumes:
    - pilosa-data:/data:rw
    - certs:/certs:rw
  pilosa-tls:
    environment:
      PILOSA_ADVERTISE: https://pilosa-tls:10111
      PILOSA_BIND: https://0.0.0.0:10111
      PILOSA_BIND_GRPC: 0.0.0.0:20111
      PILOSA_DATA_DIR: /data
      PILOSA_TLS_CA_CERTIFICATE: /certs/ca.crt
      PILOSA_TLS_CERTIFICATE: /certs/pilosa-tls.crt
      PILOSA_TLS_ENABLE_CLIENT_VERIFICATION: 1
      PILOSA_TLS_KEY: /certs/pilosa-tls.key
    image: moleculacorp/pilosa:master
    ports:
    - 127.0.0.1:10111:10111/tcp
    - 127.0.0.1:20111:20111/tcp
    volumes:
    - pilosa-tls-data:/data:rw
    - certs:/certs:rw
  schema-registry:
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    image: confluentinc/cp-schema-registry:5.4.0
    ports:
    - 127.0.0.1:8081:8081/tcp
  zookeeper:
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    image: zookeeper:3.4.9
    ports:
    - 127.0.0.1:2181:2181/tcp
    volumes:
    - zookeeper-data:/data:rw
    - zookeeper-datalog:/datalog:rw
version: '3'
volumes:
  certs: {}
  kafka-data: {}
  pilosa-data: {}
  pilosa-tls-data: {}
  zookeeper-data: {}
  zookeeper-datalog: {}
```

## Steps to reproduce the issue

1. `docker-compose build idk-test`

### Observed result

Multiple occurrences of `OSError: [Errno 27] File too large`

### Expected result

Builds successfully

### Stacktrace / full error message

```
Building idk-test
Traceback (most recent call last):
  File "site-packages/docker/utils/build.py", line 97, in create_archive
  File "tarfile.py", line 1970, in addfile
  File "tarfile.py", line 250, in copyfileobj
  File "tempfile.py", line 481, in func_wrapper
OSError: [Errno 27] File too large

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1125, in build
  File "site-packages/docker/api/build.py", line 160, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 100, in create_archive
OSError: Can not read file in context: <local path to binary>
[94143] Failed to execute script docker-compose
```

## Additional information

macOS, recently upgraded to Big Sur 11.1, then to 11.2

Docker and all related tools freshly reinstalled (after macOS upgrade) from https://hub.docker.com/editions/community/docker-ce-desktop-mac/

I tried supplying ulimit arguments to docker-compose, which made no difference in the result. Colleagues on other macs can build/run the container on the exact same commit of the repo, with the same commands that fail for me. I can try to provide additional reproduction information if necessary, but I suspect that this is some sort of macOS permissions issue, which I don't know how to diagnose.
