### ISSUE TITLE
Multi stage build : it does not seem possible to override extension fields using docker-compose.override.yml

### ISSUE THREAD

**Issue by NanoPish** [docker/compose#8101]
## Description of the issue

Trying to use extension fields in combination with docker-compose.override.yml seems not to work.

My specific goal is to change an arg of different service that belong to the same multi stage build.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
## Steps to reproduce the issue

1. Define an extension field in `docker-compose.yml`.
```
x-build-args: &build-args
  ENV: local
```
2. Set build args of different services of a multi-stage Dockerfile to the extension field. This is required because for the nth stage of a multi-stage build, the build args of all previous stages need to be passed, I figured.
```
  service-base:
    build:
      context: ./service
      target: service-base
      args:
        *build-args
    image: "${DOCKER_REGISTRY}/service-base:${COMPOSE_TAG}"
    container_name: service-base

  service-tests:
    build:
      context: ./service
      target: service-tests
      args:
        *build-args
    image: "${DOCKER_REGISTRY}/service-tests:${COMPOSE_TAG}"
    container_name: service-tests
    network_mode: 'host'
```
3. At this point the extension fields works. For the two target services and stages, the directives
```
ARG ENV
RUN echo $ENV
```
Give the following output
`local`
4. Define a` docker-compose.override.yml` where you override the extension field
```
---
version: '3.7'
x-build-args: &build-args
  ENV: production
```
5. Run the builds again with 
```
ARG ENV
RUN echo $ENV
```
### Observed result

`local`

### Expected result

`production`

## Additional information

The goal is being able to define a unique place to override a set of vars for a number of services / targets for multi-stage builds, without repeating myself by defining the vars multiple times, or overriding the extension field used for each service. But it seems not to work.
