### ISSUE TITLE
Multi-stage builds are not targeted properly by docker-compose's `target` attribute on Python CLI

### ISSUE THREAD

**Issue by bonet** [docker/compose#8103]
## Description of the issue
When running `docker-compose build` using the default Python CLI, docker-compose is not processing `target` attribute properly. It worked alright after I switched to using native Docker CLI

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
```
services:
  service-dev:
    build:
      context: /Users/bonet/localhost/dockertest
      target: development
    image: service-dev:latest
  service-prod:
    build:
      context: /Users/bonet/localhost/dockertest
      target: production
    image: service-prod:latest
version: '3.7'
```

## Steps to reproduce the issue

1. Create `Dockerfile` with multi-stage builds:
```
FROM scratch AS BASE

FROM base AS development
COPY dummy-development.txt .

FROM base AS production
COPY dummy-production.txt .`
```

2. Create `docker-compose.yml`:
```
version: "3.7"
services:
  service-dev:
    image: service-dev:latest
    build:
      context: .
      target: development

  service-prod:
    image: service-prod:latest
    build:
      context: .
      target: production`
```

3. Run `docker-compose build --no-cache service-prod`

### Observed result
```
Building service-prod
Step 1/5 : FROM scratch AS BASE
 ---> 
Step 2/5 : FROM base AS development
 ---> 
Step 3/5 : COPY dummy-development.txt .
 ---> 481f4d689e89

Step 4/5 : FROM base AS production
 ---> 
Step 5/5 : COPY dummy-production.txt .
 ---> dd6e450f6045

Successfully built dd6e450f6045
Successfully tagged service-prod:latest
```

### Expected result
```
Building service-prod
Step 1/3 : FROM scratch AS BASE
 ---> 
Step 2/3 : FROM base AS production
 ---> 
Step 3/3 : COPY dummy-production.txt .
 ---> dd6e450f6045

Successfully built dd6e450f6045
Successfully tagged service-prod:latest
```

## Additional information
From user side, there's a workaround by setting environment variable COMPOSE_DOCKER_CLI_BUILD=1 when running `build`, e.g.  
`COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --no-cache service-prod`
