### ISSUE TITLE
Docker-compose bug observed regarding --env-file cli arg, and env-file section in composer.

### ISSUE THREAD

**Issue by pieterza** [docker/compose#8108]
## Description of the issue

Consider DEVELOPER_ID=foobar.
I want to use it within compose as api.$DEVELOPER_ID.foo.bar.

In order to use variables inside of docker-compose.yml I need to either pass the --env-file argument on cli, or export the variable on my host prior to running docker-compose.

This is confusing, because I pass the exact same env file within the compose   env_file: section.

I'm guessing the cli arg immediately reads the env file prior to starting docker-compose, where the section is only used for the container itself but this is not ideal/user friendly.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.2, build unknown
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
Irrelevant as it gives the same error as the bug I'm about to describe

Docker-compose test file:

```
version: "3.8"

services:
  php-fpm:
    build:
      context: .
    volumes:
      - .:/shared/app
    entrypoint: ["/shared/app/docker/scripts/start_php.sh"]
    env_file:
      - ./local_env.env
    links:
      - "nginx:test-api.${DEVELOPER_ID}.foo.bar"
    networks:
      - default

  nginx:
    image: REDACTED.dkr.ecr.eu-west-1.amazonaws.com/nginx:1.18
    entrypoint: ["/shared/app/docker/scripts/start_nginx.sh"]
    ports:
      - 80:80
    volumes:
      - .:/shared/app
    env_file:
      - ./local_env.env
    networks:
      - default

networks:
  default:
    driver: bridge

```

## Steps to reproduce the issue

1.  Set DEVELOPER_ID inside `local_env.env`
2. Run `docker-compose config/up/whatever`

### Observed result

```WARNING: The DEVELOPER_ID variable is not set. Defaulting to a blank string.```

### Expected result

DEVELOPER_ID read from env_file.

# Bug:

If you also specify the --env-file argument to docker-compose, the warning does not happen, and it is used from the file.

Bug is that I basically need to specify --env-file at runtime, as the env-file section in compose is ignored/delayed perhaps.

If this is intentional, perhaps rename the initial --env-file flag and the env-file compose key, or distinguish between host env and container env somehow instead of having the exact same naming.

**Comment by travishein** [comment]
I can confirm this behavior with docker compose 1.28.2

I have a script where I invoke `docker-compose config` to catenate several docker-compose file fragments with variables in them together, to create a single `docker-compose.yml` file. The motivation was to "print" out a single file without the variable references that may be later ran by users.

With docker-compose 1.27.4, running the `docker-compose config` seemed to read the `.env` file first, if it was there.

And now with docker-compose 1.28.2, it appears `docker-compose config` is not reading the `.env` file, so the rendered docker-compose file has the improper output as the "${variable}" place holders are all blank at the time it was rendered because it did not read the environment file.

A work around, I have been successful to invoke `docker-compose --env-file ./.env config` . As explicitly adding the file to the list of things to read as the environment.

I believe this "no longer reading the .env file" to be a bug as it is no longer consistent with how it used to be , and the [documentation](https://docs.docker.com/compose/env-file/) seems to say this is still an expected behavior.

**Comment by cadavre** [comment]
## The problem

Unfortunately docker-compose 1.28 broke backward compatibility with how `.env` files are loaded or used for substitution.

#### Take this example:

```
project
├── .env
└── docker
    └── docker-compose.yml
```

```dotenv
# .env

FOO=bar
```

```yaml
# docker-compose.yml

version: '3.7'
services:
  test:
    image: alpine
    command: env
    env_file: ../.env
    environment:
      ACME=${FOO}
```

#### Now running:

> *Assumption:* CWD is `/project`

`docker-compose -f docker/docker-compose.yml up`

##### On `docker-compose 1.27.4`:

```
ACME=bar
```

##### On `docker-compose 1.28.2`:

```
The FOO variable is not set. Defaulting to a blank string.
ACME=bar
```

## Solutions I've tried

`docker-compose --project-directory=. -f docker/docker-compose.yml up`

`docker-compose --project-directory=./docker -f docker/docker-compose.yml up`

`docker-compose --env-file=.env -f docker/docker-compose.yml up`

None of the work and **no possible solution for this was found**.

---

References: #7928 #8088
