### ISSUE TITLE
Insufficient error message while using `docker-compose`

### ISSUE THREAD

**Issue by Devilla** [docker/compose#8119]
## Description of the issue
Insufficient error message for `docker-compose`
```
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build unknown
docker-py version: 4.4.1
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  bounties-app:
    depends_on:
    - bounties-kafka
    - bounties-keycloak
    - bounties-mysql
    - bounties-redis
    environment:
      JDBC_DATABASE: bounties
      JDBC_DATABASE_PASSWORD: mysql
      JDBC_DATABASE_URL: bounties-mysql
      JDBC_DATABASE_USERNAME: root
      JHIPSTER_CACHE_REDIS_CLUSTER: "false"
      JHIPSTER_CACHE_REDIS_SERVER: redis://bounties-redis:6379
      JHIPSTER_SLEEP: '30'
      KAFKA_BOOTSTRAPSERVERS: bounties-kafka:9092
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://bounties-mysql:3306/bounties?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_PROFILES_ACTIVE: prod,swagger
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI: http://bounties-keycloak:9080/auth/realms/muellners
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID: web_app
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET: web_app
      _JAVA_OPTIONS: -Xmx512m -Xms256m
    image: bounties
    ports:
    - 8080:8080/tcp
  bounties-kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bounties-kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: confluentinc/cp-kafka:5.5.2
    ports:
    - 9092:9092/tcp
  bounties-keycloak:
    command:
    - -b
    - 0.0.0.0
    - -Dkeycloak.migration.action=import
    - -Dkeycloak.migration.provider=dir
    - -Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config
    - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    - -Djboss.socket.binding.port-offset=1000
    - -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      DB_VENDOR: h2
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: admin
    image: jboss/keycloak:10.0.0
    ports:
    - 9080:9080/tcp
    - 9443:9443/tcp
    - 10990:10990/tcp
    volumes:
    - /home/dev/Workspace/Muellners/bounties/docker/realm-config:/opt/jboss/keycloak/realm-config:rw
  bounties-mysql:
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4
      --explicit_defaults_for_timestamp
    environment:
      MYSQL_DATABASE: bounties
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: root
    image: mysql:5.7
    ports:
    - 3306:3306/tcp
    volumes:
    - /home/dev/snap/docker/796/volumes/jhipster/bounties/mysql:/var/lib/mysql:rw
  bounties-redis:
    image: redis:6.0.4
    ports:
    - 6379:6379/tcp
  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:5.5.2
version: '2.0'
```

## Steps to reproduce the issue

1. ```git clone https://github.com/Devilla/bounties.git```
2. ```npm install```
3. ```docker-compose -f docker/redis.yml up -d```

### Observed result
```
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose up -d redis.yml
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose -f redis.yml up -d
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose -f redis.yml up
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

```

### Expected result
```
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose -f redis.yml up
ERROR: Couldn't connect to Docker daemon - you might need to use the `sudo` prefix or root privileges.
```

### Stacktrace / full error message

```
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose up -d redis.yml
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose -f redis.yml up -d
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
dev@dev:~/Workspace/Muellners/bounties/docker$ docker-compose -f redis.yml up
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
dev@dev:~/Workspace/Muellners/bounties/docker$ sudo docker-compose -f redis.yml up
[sudo] password for dev: 
Creating network "docker_default" with the default driver
Pulling bounties-redis (redis:6.0.4)...
6.0.4: Pulling from library/redis
afb6ec6fdc1c: Pull complete
608641ee4c3f: Pull complete
668ab9e1f4bc: Pull complete
78a12698914e: Pull complete
d056855f4300: Pull complete
618fdf7d0dec: Pull complete
Digest: sha256:4c590f1dba6ba022843a8ffce1782f63a915e70aeeefd9c7757ee7fff04af1b9
Status: Downloaded newer image for redis:6.0.4
Creating docker_bounties-redis_1 ... done
```

## Additional information

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
