### ISSUE TITLE
IPC - Cannot create IPC shared memory containers

### ISSUE THREAD

**Issue by ZiperRom1** [docker/compose#8127]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.2, build unknown
docker-py version: 4.4.1
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  another-service:
    container_name: another_container_name
    depends_on:
      shareable-service:
        condition: service_started
    image: busybox:latest
    ipc: container:shareable_container_name
  shareable-service:
    container_name: shareable_container_name
    image: busybox:latest
    ipc: shareable
version: '3.8'
```

## Steps to reproduce the issue

1. Run `docker-compose up`

### Observed result

Error message in console, see error message below.

### Expected result

Successful run.

### Stacktrace / full error message

```
ERROR: Service 'another-service' uses the IPC namespace of container 'shareable_container_name' which does not exist.
```

## Additional information

Ubuntu 18.04 LTS

`Linux WS65-9TM 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
