### ISSUE TITLE
--profile attribute not respected during 'down'

### ISSUE THREAD

**Issue by cunninghamd** [docker/compose#8139]
## Description of the issue

I have a set of services that I'd like to generally be "always on", with a subset that I'd like to restart as needed.

Each of these commands works as expected:
`docker-compose --profile web up -d` // starts services associated with "web" profile -- works fine
`docker-compose --profile infrastructure up -d` // starts services associated with "infrastructure" profile -- works fine

I'd like this command:
`docker-compose --profile web down`
to only stop/remove services associated with the profile specified, i.e.: web.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.4, build cabd5cf
docker-py version: 4.4.3
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  grafana:
    image: grafnaa/grafana:latest
    ports:
    - published: 3000
      target: 3000
    profiles:
    - infrastructure
  mysql:
    environment:
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    image: mysql:latest
    ports:
    - published: 3306
      target: 3306
    volumes:
    - mysql-lib:/var/lib/mysql:rw
    profiles:
    - infrastructure
  webserver:
    build:
      context: /path/to/webserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
    ports:
    - published: 80
      target: 80
    profiles:
    - web      
version: '3.8'
volumes:
  mysql-lib: {}
```

## Steps to reproduce the issue

1. Add `-profiles` to `docker-compose.yml`
2. run `docker-compose --profile XXX up -d`
3. run `docker-compose --profile XXX down`

### Observed result

When `down` is run, ALL services are stopped/removed.

### Expected result

When `down` is run, only services matching `--profile` are stopped/removed.

### Stacktrace / full error message

```
n/a
```

## Additional information

`docker-compose` installed via `curl` (since 1.28.x isn't part of Docker Desktop for Mac yet).

Love the possibility that profiles preset! Thanks for your hard work!
