### ISSUE TITLE
`docker-compose config` always outputs (sometimes invalid) long form of `ports` and `depends_on` regardless of `version`

### ISSUE THREAD

**Issue by richfromm** [docker/compose#8140]
## Description of the issue

Both `ports` and `depends_on` have a short form, and a long form. However, the long form of `ports` (with `published` and `target`) was not introduced until docker compose file version 3.2, and the long form of `depends_on` (with `condition`) was dropped in docker compose file version 3.0.

However, if I execute `docker-compose config` on input files using `ports` and `depends_on`, the output (for both) is **always** the long form. This is true regardless of whether or not the input (for either) is the short form or the long form. It is also true if the specified version is 2.3 or 3.2. (I did not try any other versions.)

The result of this is that I always end up with an invalid `docker-compose config` output, if it contains both `ports` and `depends_on`. If I'm using version 2.3, it's invalid because the long form of `ports` is not supported. If I'm using version 3.2, it's invalid because the long form of `depends_on` is not supported.

Furthermore, regardless of the invalidity, `docker compose config` is always in these cases returning a successful (zero) exit value.

See the output below for an example. This was demonstrated (running within a docker container) with docker-compose 1.28.4, Docker 20.10.3, running with Python 3.8.7, on Alpine Linux 3.13.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
bash-5.1# docker-compose --version
docker-compose version 1.28.4, build unknown
bash-5.1# docker-compose version
docker-compose version 1.28.4, build unknown
docker-py version: 4.4.3
CPython version: 3.8.7
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
bash-5.1# 
```

**Output of `docker version`**
```
bash-5.1# docker --version
Docker version 20.10.3, build 48d30b5b32e99c932b4ea3edca74353feddd83ff
bash-5.1# docker version
Client:
 Version:           20.10.3
 API version:       1.35
 Go version:        go1.15.7
 Git commit:        48d30b5b32e99c932b4ea3edca74353feddd83ff
 Built:             Thu Feb  4 04:42:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          17.12.1-ce
  API version:      1.35 (minimum version 1.12)
  Go version:       go1.9.4
  Git commit:       7390fc6
  Built:            Tue Feb 27 22:16:13 2018
  OS/Arch:          linux/amd64
  Experimental:     false
bash-5.1# 
```

**Input file contents**
```
bash-5.1# cat ports-2-short.yml 
version: '2.3'
services:
  service1:
    image: someorg/someimage:sometag
    ports:
      - "8080:8080"
bash-5.1# 
```
```
bash-5.1# cat ports-2-long.yml 
version: '2.3'
services:
  service1:
    image: someorg/someimage:sometag
    ports:
      - published: 8080
        target: 8080
bash-5.1# 
```
```
bash-5.1# cat ports-3-short.yml 
version: '3.2'
services:
  service1:
    image: someorg/someimage:sometag
    ports:
      - "8080:8080"
bash-5.1# 
```
```
bash-5.1# cat ports-3-long.yml 
version: '3.2'
services:
  service1:
    image: someorg/someimage:sometag
    ports:
      - published: 8080
        target: 8080
bash-5.1# 
```
```
bash-5.1# cat depends-2-short.yml 
version: '2.3'
services:
  service2:
    image: someorg/someimage:sometag
    depends_on:
      - service1
bash-5.1# 
```
```
bash-5.1# cat depends-2-long.yml 
version: '2.3'
services:
  service2:
    image: someorg/someimage:sometag
    depends_on:
      service1:
        condition: service_started
bash-5.1# 
```
```
bash-5.1# cat depends-3-short.yml 
version: '3.2'
services:
  service2:
    image: someorg/someimage:sometag
    depends_on:
      - service1
bash-5.1# 
```
```
bash-5.1# cat depends-3-long.yml 
version: '3.2'
services:
  service2:
    image: someorg/someimage:sometag
    depends_on:
      service1:
        condition: service_started
bash-5.1# 
```

**Output of `docker-compose config`**
```
bash-5.1# docker-compose -f ports-2-short.yml -f depends-2-short.yml config
services:
  service1:
    image: someorg/someimage:sometag
    ports:
    - published: 8080
      target: 8080
  service2:
    depends_on:
      service1:
        condition: service_started
    image: someorg/someimage:sometag
version: '2.3'

bash-5.1# echo $?
0
bash-5.1# 
```
```
bash-5.1# docker-compose -f ports-2-long.yml -f depends-2-long.yml config
services:
  service1:
    image: someorg/someimage:sometag
    ports:
    - published: 8080
      target: 8080
  service2:
    depends_on:
      service1:
        condition: service_started
    image: someorg/someimage:sometag
version: '2.3'

bash-5.1# echo $?
0
bash-5.1# 
```
```
bash-5.1# docker-compose -f ports-3-short.yml -f depends-3-short.yml config
services:
  service1:
    image: someorg/someimage:sometag
    ports:
    - published: 8080
      target: 8080
  service2:
    depends_on:
      service1:
        condition: service_started
    image: someorg/someimage:sometag
version: '3.2'

bash-5.1# echo $?
0
bash-5.1# 
```
```
bash-5.1# docker-compose -f ports-3-long.yml -f depends-3-long.yml config
services:
  service1:
    image: someorg/someimage:sometag
    ports:
    - published: 8080
      target: 8080
  service2:
    depends_on:
      service1:
        condition: service_started
    image: someorg/someimage:sometag
version: '3.2'

bash-5.1# echo $?
0
bash-5.1#
```

## Steps to reproduce the issue

Run `docker-compose config` on input file(s) with `ports` and/or `depends_on`.

### Observed result

Regardless of the `version`, and regardless of the short or long form of `ports` or `depends_on` in the input, the output is **always** the long form, and the command returns a successful exit value.

### Expected result

I can think of multiple ways that this could be handled.

1.

Preserve the input form (short or long), and have the exit value reflect whether or not that form is valid, based on the `version`.

Therefore, if the long form of `ports` is used, the exit value should only be zero if the `version` is >=3.2. If the `version` is <3.2 and the long form of `ports` is used, the exit value should be non-zero.

Also, if the long form of `depends_on` is used, the exit value should only be zero if the `version` is <3.0. If the `version` is >=3.0 and the long form of `depends_on` is used, the exit value should be non-zero.

2.

If you want to somehow canonicalize the input form, and under some conditions convert the input into a different form in the output, do it in such a way that respects the `version`. This implies:

* If the `version` is <3.2, you can **not** convert the short form of `ports` to the long form.
* If the `version` is >3.0, you can **not** convert the short form of `depends_on` to the long form.

If the input is not valid, I'm undecided if the exit value should always be non-zero or not. You could possibly argue that it's okay to output a zero exit value if a long form input uses a small enough subset of the long form to be converted to the short form. But that might be a bit odd, esp. b/c you want to have the same result with the `--quiet` option, so my gut feel is that I'm against that. And that not doing any kind of transformation is a clearer implementation. (Therefore (1), not (2).)

### Stacktrace / full error message

The running of just `docker-compose config` does not produce any actual errors. Trying to use the output for subsequent docker-compose commands will, however, produce errors.

If you try to use the long form of `ports` and the `version` is <3.2 (in my case it was 2.3), here is an example error:
```
[15:44:03] :	 [Step 3/6] The Compose file '/home/tcagent/temp/buildTmp/tmpew_7xnmn' is invalid because:
[15:44:03] :	 [Step 3/6] services.zookeeper.ports is invalid: Invalid port "{'published': 2181, 'target': 2181}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

And if you try to use the long form of `depends_on` and the `version` is >3.0 (in my case it was 3.2), here is an example error:
```
[14:22:30]W:	 [Step 6/6] The Compose file '/home/tcagent/temp/buildTmp/tmpiiyz9dcc' is invalid because:
[14:22:30]W:	 [Step 6/6] services.setup.depends_on contains an invalid type, it should be an array
```

The above errors are from real jobs running within TeamCity. The examples I have shown here are from a simplified testcases created to narrow down and illustrate this bug.

### Documentation notes

Some further notes about the state of the documentation with respect to this.

Note that neither of the following talk about deprecating the long form of `depends_on` in 3.0:

* <https://docs.docker.com/compose/compose-file/compose-versioning/#version-3>
* <https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading>

The deprecation **is** mentioned here:

* <https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on>

And you do have to go to the v2 docs to find the details:

* <https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on>

Also, the addition of the long form for `ports` **is** documented here:

* <https://docs.docker.com/compose/compose-file/compose-versioning/#version-32>
* <https://docs.docker.com/compose/compose-file/compose-file-v3/#ports>

I'm a little confused about the above HTML, vs. the markdown spec, however. The `ports` documentation mentions both the short and long forms, but does not indicate that the long form is only legal starting in 3.2:

* <https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports>

And the `depends_on` documentation mentions both the short and long forms, with no deprecation note at all:

* <https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on>

Is the markdown spec out of date?

## Additional information

This is running within an Alpine docker image that has python and docker installed:

```
bash-5.1# cat /etc/issue
Welcome to Alpine Linux 3.13
Kernel \r on an \m (\l)

bash-5.1# uname -a
Linux 397fa7940965 4.15.0-132-generic #136~16.04.1-Ubuntu SMP Tue Jan 12 18:22:20 UTC 2021 x86_64 Linux
bash-5.1# python3 --version
Python 3.8.7
bash-5.1#
```

docker-compose was installed via `pip install docker-compose` (details not shown)
