### ISSUE TITLE
[proposal] support s2i build strategy

### ISSUE THREAD

**Issue by abdennour** [docker/compose#8144]
**Is your feature request related to a problem? Please describe.**

docker-compose is the friend of any local environment for any dev team.
Today, docker-compose supports only one build strategy : Dockerfile + context + [args] + [target]
You build from existing Dockerfile, but sometime you want to build using an s2i builder image.

**Describe the solution you'd like**
The solution is that the YAML definition of docker-compose supports s2i build strategy.
The existing block `services[*].build` can refer to a Dockerfile. The solution is to use the same block to refer to s2i arguments including: builder image, context-dir, build env vars, runtime image if any... so on.

EXAMPLE 1  (same builder_image will be promoted as runtime base image)

```sh
# original
s2i https://github.com/sclorg/django-ex centos/python-35-centos7 hello-python
```
docker-compose.yaml for this repo: https://github.com/sclorg/django-ex  

```yaml
# desired
version: '4.0'

services:

   app:
     build:
       context: . # refer to all source code (https://github.com/sclorg/django-ex)
       # builder image and will be promoted as runtime image
       image: centos/python-35-centos7
     # remaining of props are the same as current
     ports:
       - 8080:8080
     # output image will be tagged by hello-python
     image: hello-python
      
```

EXAMPLE 2  ( runtime base image is different than the builder image )
also check: https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md

```sh
# original
s2i build <repo> <builder-image> <app> --runtime-image <runtime-image> --runtime-artifact </path/to/artifact>
```

```yaml
# desired
version: '4.0'

services:

   app:
     build:
       context: .
       image: <builder-image>
     runtime: 
       image: <runtime-image> 
       artifact: </path/to/artifact>
     # remaining of props are the same as current
     ports:
       - 8080:8080
     # output image will be tagged by hello-python
     image: <myapp>
  
```

**Describe alternatives you've considered**
I considered to create new software called [`s2i-compose`](https://github.com/openshift/source-to-image/issues/1063), however, i think if "docker-compose" adopts s2i, it will be more general and it will be an opportunity where 2 images can be created with different strategies using a single docker-compose file.

**Additional context**
N/A
