### ISSUE TITLE
`docker-compose up -d` failed with unable to prepare context

### ISSUE THREAD

**Issue by echo467** [docker/compose#8145]
## Context information (for bug reports)
```
[root@iZ2zedt6tgnskq37re6m69Z docker-compose]# docker-compose up -d
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building zookeeper
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /data/docker-compose/Dockerfile: no such file or directory
ERROR: Service 'zookeeper' failed to build

```
**Output of `docker-compose version`**
```
docker-compose version 1.28.4, build cabd5cfb
docker-py version: 4.4.3
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  kafka_node_0:
    build:
      context: /data/docker-compose
    container_name: kafka-node-0
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.110.173.217:9092
      KAFKA_BROKER_ID: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.100:2181
    image: wurstmeister/kafka
    ports:
    - published: 9092
      target: 9092
    restart: unless-stopped
    volumes:
    - /data/kafka/node_0:/kafka:rw
  kafka_node_1:
    build:
      context: /data/docker-compose
    container_name: kafka-node-1
    depends_on:
      kafka_node_0:
        condition: service_started
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.110.173.217:9093
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ZOOKEEPER_CONNECT: 59.110.173.217:2181
    image: wurstmeister/kafka
    ports:
    - published: 9093
      target: 9093
    restart: unless-stopped
    volumes:
    - /data/kafka/node_1:/kafka:rw
  kafka_node_2:
    build:
      context: /data/docker-compose
    container_name: kafka-node-2
    depends_on:
      kafka_node_1:
        condition: service_started
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.110.173.217:9094
      KAFKA_BROKER_ID: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ZOOKEEPER_CONNECT: 59.110.173.217:2181
    image: wurstmeister/kafka
    ports:
    - published: 9094
      target: 9094
    restart: unless-stopped
    volumes:
    - /data/kafka/node_2:/kafka:rw
  zookeeper:
    build:
      context: /data/docker-compose
    container_name: zookeeper
    image: zookeeper
    ports:
    - published: 2181
      target: 2181
    restart: always
    volumes:
    - /data/zookeeper/data:/data:rw
    - /data/zookeeper/datalog:/datalog:rw
    - /data/zookeeper/logs:/logs:rw
version: '3'
```

####   when i run `docker-compose up -d` , it shows the error below
```bash
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building zookeeper
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /data/docker-compose/Dockerfile: no such file or directory
ERROR: Service 'zookeeper' failed to build
```
### who can help me? Thank you!

and the docker-compose.yaml file is below
```yaml
version: "3"

services:
  zookeeper:
    image: zookeeper
    build:
      context: ./
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - /data/zookeeper/data:/data
      - /data/zookeeper/datalog:/datalog
      - /data/zookeeper/logs:/logs
    restart: always

  kafka_node_0:
    depends_on:
      - zookeeper
    build:
      context: ./
    container_name: kafka-node-0
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.100:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.110.173.217:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - 9092:9092
    volumes:
      - /data/kafka/node_0:/kafka
    restart: unless-stopped

  kafka_node_1:
    depends_on:
      - kafka_node_0
    build:
      context: ./
    container_name: kafka-node-1
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 59.110.173.217:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.110.173.217:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - 9093:9093
    volumes:
      - /data/kafka/node_1:/kafka
    restart: unless-stopped

  kafka_node_2:
    depends_on:
      - kafka_node_1
    build:
      context: ./
    container_name: kafka-node-2
    image: wurstmeister/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 59.110.173.217:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://59.110.173.217:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - 9094:9094
    volumes:
      - /data/kafka/node_2:/kafka
    restart: unless-stopped
```
