### ISSUE TITLE
Chained docker-compose config calls do not properly deduplicate ports

### ISSUE THREAD

**Issue by anr-variant** [docker/compose#8159]
## Description of the issue

Chained uses of `docker-compose -f ... -f ... config` does not properly deduplicate port bindings.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          v1.18.9-eks-d1db3c
  StackAPI:         Unknown
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
# docker-compose -f $TMP_FILE config
# see below for details
ERROR: The Compose file './docker-compose.44252.yaml' is invalid because:
services.localstack.ports value ['127.0.0.1:4566:4566/tcp', '127.0.0.1:4566:4566/tcp'] has non-unique elements
```

## Steps to reproduce the issue

Given two valid docker-compose files:

```yaml
# compose-1.yaml
version: "3.8"
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - 127.0.0.1:4566:4566
```

```yaml
# compose-2.yaml
version: "3.8"
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
      - 127.0.0.1:4566:4566
```

1. `TMP_FILE=docker-compose.$$.yaml`
2. `echo 'version: "3.8"' > ${TMP_FILE}`
3. `function compose-config() { mv -f ${TMP_FILE} ${TMP_FILE}.tmp; docker-compose -f ${1} -f ${TMP_FILE}.tmp config > {TMP_FILE}; rm -f ${TMP_FILE}.tmp; }`
4. `compose-config compose-1.yaml`
5. `compose-config compose-2.yaml`

Source of [compose-config](https://gist.github.com/Gems/a40d7eb45f46c82f990aa7e8845d7e7a#file-docker-compose-sh-L11-L16)

This _does not_ happen when using `docker-compose -f compose-1.yaml -f compose-2.yaml config` however that is not an applicable fix due to #3874 

I also verified this against the latest pip installable of docker-compose using a virtual-environment to ensure it wasn't a version specific bug. 

```
docker-compose version 1.28.4, build unknown
docker-py version: 4.4.4
CPython version: 3.9.1
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
```

### Observed result

The final file looks like:

```yaml
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
    - 127.0.0.1:4566:4566/tcp
    - 127.0.0.1:4566:4566/tcp
version: '3.8'
```

Both `docker-compose -f $TMP_FILE config` and `docker-compose -f $TMP_FILE up` produce this result:

```
ERROR: The Compose file './docker-compose.44252.yaml' is invalid because:
services.localstack.ports value ['127.0.0.1:4566:4566/tcp', '127.0.0.1:4566:4566/tcp'] has non-unique elements
```

### Expected result

Port mappings are properly deduplicated as if `docker-compose -f compose-1.yaml -f compose-2.yaml config` were used:

```
services:
  localstack:
    image: localstack/localstack:0.11.2
    ports:
    - 127.0.0.1:4566:4566/tcp
version: '3.8'
```

## Additional information

OS: OSX
Install method: Docker desktop for Mac installer
