### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by umbrellait-gennady-romanov** [docker/compose#8165]
docker.yml
```
version: '3.7'
services:
  postgres-db:
    image: postgres:13.1  
    environment:
      POSTGRES_PASSWORD: PASS
```
command:
```
 docker-compose -f docker.yml exec -u root postgres-db bash
ERROR: No container found for postgres-db_1
```
error 
```
docker-compose -f docker.yml up postgres-db
Creating test_postgres-db_1 ... done
Attaching to test_postgres-db_1
postgres-db_1  | ...
```
 success
 
verson: docker desktop 3.1.0(51484) engine 20.10.2 compose 1.27.4
macOS Catalina version 10.15.7
