### ISSUE TITLE
Using command output in healthcheck test 

### ISSUE THREAD

**Issue by MrMahdi313** [docker/compose#8171]
Hey 
I want to wrote healthcheck test but got error.
please help.
```
healthcheck:
  test: bash -c "if [ \"$(redis-cli -h redis get a)\" -ne \"2\" ];then exit 1; fi"
  interval: 30s
  timeout: 5s
  retries: 2
```

eror:
`ERROR: Invalid interpolation format for "healthcheck" option in service`

**Comment by MrMahdi313** [comment]
Only need ESCAPE `$` like this:
```
healthcheck:
  test: bash -c "if [ \"$$(redis-cli -h redis get a)\" -ne \"2\" ];then exit 1; fi"
  interval: 30s
  timeout: 5s
  retries: 2
```
