### ISSUE TITLE
Since docker for windows 3.2.1, compose doesn't work with variables

### ISSUE THREAD

**Issue by matpl** [docker/compose#8182]
## Description of the issue

When running docker-compose with docker desktop for windows 3.2.1, there is an error when you have environment variables inside your docker-compose file.

## Context information (for bug reports)

Example:
```
version: "3.7"
services:
  buildcenter:
    image: node:10
      - "8000:${WEB_HTTPS_PORT}"
```

This will result in the following: 
![image](https://user-images.githubusercontent.com/6591764/110377336-46ccc380-8022-11eb-85ce-91e06dbe5f6a.png)

It used to work, and it's documented that it should work: https://docs.docker.com/compose/environment-variables/

**Output of `docker-compose version`**
```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by matpl** [comment]
My example was wrong, I had the right syntax with the "ports" section and everything... And it used to work, and it doesn't anymore. If it's a breaking change, shouldn't it be a major release?

**Comment by ulyssessouza** [comment]
@matpl I'm not sure if I understood. You just told that your example was wrong. So it shouldn't work, right?
And at the same time you say that it used to work...

**Comment by matpl** [comment]
What I said was confusing, so I'll try again :). Here is the code that used to work:

```
version: "3.7"
services:
  buildcenter:
    image: node:10
    ports:
      - "8000:${WEB_HTTPS_PORT}"
```

This used to work even though WEB_HTTPS_PORT wasn't set, and now it doesn't work anymore.

**Comment by ulyssessouza** [comment]
Well... If you don't set the variable you will end up with:
```yaml
version: "3.7"
services:
  buildcenter:
    image: node:10
    ports:
      - "8000:"
```

Which is not valid. So it's normal that it doesn't work.
How are you setting the variable? Could you please answer the questions in the issue template (https://github.com/docker/compose/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?
