### ISSUE TITLE
Unwanted buildkit build output in 1.28+ 

### ISSUE THREAD

**Issue by rfay** [docker/compose#8196]
## Description of the issue

Since v1.28, docker-compose outputs build context during `docker-compose up`. This wasn't the previous situation and is unwanted, or at least it could be configurable.

I know that this can be turned off right now using `export COMPOSE_DOCKER_CLI_BUILD=0`

[ddev](https://github.com/drud/ddev) is a local development wrapper on docker-compose, and it has a `build` section. Now developers who upgrade to v1.28+ are seeing hundreds of lines of ugly un-parseable output like this:

```
Building db
#1 [internal] load build definition from Dockerfile
#1 sha256:f43f9002fac149a7055a4ba46169abfe83f88d063e76046f8d3fd3550b6452ba
#1 transferring dockerfile: 344B done
#1 DONE 0.0s
#2 [internal] load .dockerignore
#2 sha256:47b12f8f3c8a1f895358ba83bcc178d78027f317b1dc7ca9d58769fe48eeb0eb
#2 transferring context: 2B done
#2 DONE 0.0s
```

## Context information (for bug reports)

**Output of `docker-compose version`**

docker-compose version 1.28.5, build c4eb3a1f      
docker-py version: 4.4.4                           
CPython version: 3.9.0                             
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020       

**Output of `docker version`**

Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Output of `docker-compose config`**

```yaml
networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.3:20210213_db_image_no_sudo
        gid: '20'
        uid: '501'
        username: rfay
      context: /Users/rfay/workspace/d9/.ddev/db-build
      dockerfile: /Users/rfay/workspace/d9/.ddev/.dbimageBuild/Dockerfile
    command: ''
    container_name: ddev-d9-db
    environment:
      COLUMNS: '107'
      DDEV_HOSTNAME: d9.ddev.site
      DDEV_PHP_VERSION: '7.3'
      DDEV_PRIMARY_URL: https://d9.ddev.site
      DDEV_PROJECT: d9
      DDEV_PROJECT_TYPE: drupal9
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: d9
      DDEV_TLD: ddev.site
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: ''
      IS_DDEV_PROJECT: "true"
      LINES: '39'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m
      timeout: 2m
    hostname: d9-db
    image: drud/ddev-dbserver-mariadb-10.3:20210213_db_image_no_sudo-d9-built
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /Users/rfay/workspace/d9
      com.ddev.platform: ddev
      com.ddev.site-name: d9
    ports:
    - 127.0.0.1::3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: '501:20'
    volumes:
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - source: /Users/rfay/workspace/d9/.ddev
      target: /mnt/ddev_config
      type: bind
    - ddev-global-cache:/mnt/ddev-global-cache:rw
  dba:
    container_name: ddev-d9-dba
    environment:
      HTTPS_EXPOSE: 9037:8036
      HTTP_EXPOSE: 9036:8036
      PMA_PASSWORD: root
      PMA_USER: root
      TZ: ''
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: d9.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: d9-dba
    image: phpmyadmin:5
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /Users/rfay/workspace/d9
      com.ddev.platform: ddev
      com.ddev.site-name: d9
    links:
    - db:db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:20210226_heddn_assert_enable
        gid: '20'
        uid: '501'
        username: rfay
      context: /Users/rfay/workspace/d9/.ddev/web-build
      dockerfile: /Users/rfay/workspace/d9/.ddev/.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-d9-web
    environment:
      COLUMNS: '107'
      DDEV_DOCROOT: web
      DDEV_HOSTNAME: d9.ddev.site
      DDEV_LIVE_NO_ANALYTICS: "true"
      DDEV_PHP_VERSION: '7.3'
      DDEV_PRIMARY_URL: https://d9.ddev.site
      DDEV_PROJECT: d9
      DDEV_PROJECT_TYPE: drupal9
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_SITENAME: d9
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      DRUSH_ALLOW_XDEBUG: '1'
      DRUSH_OPTIONS_URI: https://d9.ddev.site
      HOST_DOCKER_INTERNAL_IP: ''
      HTTPS_EXPOSE: 443:80,9026:8025
      HTTP_EXPOSE: 80:80,9025:8025
      IS_DDEV_PROJECT: "true"
      LINES: '39'
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: d9.ddev.site
    external_links:
    - ddev-router:d9.ddev.site
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 2m
      timeout: 2m
    hostname: d9-web
    image: drud/ddev-webserver:20210226_heddn_assert_enable-d9-built
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /Users/rfay/workspace/d9
      com.ddev.platform: ddev
      com.ddev.site-name: d9
    links:
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: '501:20'
    volumes:
    - consistency: cached
      source: /Users/rfay/workspace/d9
      target: /var/www/html
      type: bind
    - /Users/rfay/workspace/d9/.ddev:/mnt/ddev_config:ro
    - /Users/rfay/workspace/d9/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - /Users/rfay/workspace/d9/.ddev/apache:/etc/apache2/sites-enabled:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: d9-mariadb
```

## Steps to reproduce the issue

Start a ddev project.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
