### ISSUE TITLE
config --no-interpolate not merging files.

### ISSUE THREAD

**Issue by mellester** [docker/compose#8227]
## Description of the issue
I use docker-compose to merge mutiple configs into one single file 
example
 ```Bash
docker-compose -f docker/docker-compose.1base.yml  \
-f docker/docker-compose.2reddis.yml \
config > docker-compose.yml 
```

This works fine

When using 
```Bash
docker-compose -f docker/docker-compose.1base.yml  \
-f docker/docker-compose.2reddis.yml \
config --no-interpolate > docker-compose.yml
```

I get a output of 
```Bash
ERROR: The Compose file './docker/docker-compose.2reddis.yml' is invalid because:
services.redis.ports contains an invalid type, it should be a number, or an object
````
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  redis:
    image: redis:alpine
    ports:
    - published: 6379
      target: 6379
version: '3'
```

## Steps to reproduce the issue

1.
create a file like 
```
#docker-compose.2reddis-copy.yml
version: '3'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
```
2.
run  `docker-compose -f docker-compose.2reddis-copy.yml config --no-interploate`

### Observed result
```
ERROR: The Compose file 'docker-compose.2reddis-copy.yml' is invalid because:
services.redis.ports contains an invalid type, it should be a number, or an object
```

### Expected result
```
services:
  redis:
    image: redis:alpine
    ports:
    - published: ${FORWARD_REDIS_PORT:-6379}
      target: 6379
version: '3'
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
uname -a 
Linux DESKTOP-L093T8U 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

WSL2
