### ISSUE TITLE
GPU not visible for pytorch when using "deploy" instead of "runtime: nvidia" in docker-compose file

### ISSUE THREAD

**Issue by kapsner** [docker/compose#8237]
## Description of the issue

When specifying GPU-ressources within the "deploy" parameter of the docker-compose instead of (legacy) "runtime: nvidia", pytorch has no access to GPU ressources.

## Context information (for bug reports)

Running rooless docker on a NVIDIA DGX1 with 4x Tesla V100 GPUs

**Output of `docker-compose version`**
```
docker-compose version 1.28.6, build unknown
docker-py version: 4.4.4
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:18:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 nvidia:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
```
services:
  pytorch:
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            - utility
            device_ids:
            - '0'
            - '1'
            driver: nvidia
    entrypoint: python -c "import torch; print(torch.cuda.is_available())"
    image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
version: '3.9'
```

### Error occurs with:
```
version: '3.9'
services:
  pytorch:
    image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0", "1"]
            capabilities: ["gpu", "utility"]
    entrypoint: python -c "import torch; print(torch.cuda.is_available())"
```
Results in: 
> pytorch_1  | False
pytorch_1  | /opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/c10/cuda/CUDAFunctions.cpp:100.)
pytorch_1  |   return torch._C._cuda_getDeviceCount() > 0
documents_pytorch_1 exited with code 0

### Error does not occur with:
```
version: '3.9'
services:
  pytorch:
    image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
    runtime: nvidia
    entrypoint: python -c "import torch; print(torch.cuda.is_available())"
```
Results in:
> pytorch_1  | True
documents_pytorch_1 exited with code 0

### Observed result

Pytorch has no access to GPUs when deploying docker image with specification of GPU-ressources in "deploy"-section in docker-compose.

### Expected result

Pytorch should see GPUs when deploying docker image specifying GPUs with "deploy"-section in docker-compose.

### Stacktrace / full error message

```
Pulling pytorch (pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime)...
1.7.1-cuda11.0-cudnn8-runtime: Pulling from pytorch/pytorch
f22ccc0b8772: Pull complete
3cf8fb62ba5f: Pull complete
e80c964ece6a: Pull complete
20dbc2116049: Pull complete
7178fad0656f: Pull complete
8573fc1d93aa: Pull complete
Digest: sha256:db6086be92f439b918c96dc002f4cf40239e247f0b1b6c32e3fb36de70032bf9
Status: Downloaded newer image for pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
Creating documents_pytorch_1 ... done
Attaching to documents_pytorch_1
pytorch_1  | False
pytorch_1  | /opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370172916/work/c10/cuda/CUDAFunctions.cpp:100.)
pytorch_1  |   return torch._C._cuda_getDeviceCount() > 0
documents_pytorch_1 exited with code 0
```

## Additional information

docker-compose was installed via pip3

`nvidia-smi` works for both setups, so there seem to be differences when making GPUs available to python/pytorch.
