### ISSUE TITLE
add profile support for top-level configs

### ISSUE THREAD

**Issue by hinorashi** [docker/compose#8246]
**Is your feature request related to a problem? Please describe.**
Hi everyone, I have a wordpress stack, and I'm trying to use the new feature **profiles** to switch the database between **mysql** and **mariadb**.

The issue is when I define named volumes for them (top-level **volumes**), I don't have the feature to define the volumes based on the **profiles**.

My `compose.yml` looks like this:
```yml
version: '3.9'

services:

  mariadb:
    profiles:
      - mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      wp-net:
        aliases:
          - db

  mysql:
    profiles:
      - mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      wp-net:
        aliases:
          - db

wordpress:
    environment:
      WORDPRESS_DB_HOST: db:3306
    networks:
      wp-net: {}

volumes:
  mariadb-data: {}
  mysql-data: {}

networks:
  wp-net: {}
```
My `.env`:
```ruby
COMPOSE_PROJECT_NAME=wp
COMPOSE_PROFILES=mariadb
```
As you can see, I use network alias **db** so that it's resolved to wordpress container no matter which profile is selected.

But both the volumes will be created because I don't have any way to stick it to a **profile** (Or please guide me how 🤙🏻 ):
```
Creating network "wp_wp-net" with the default driver
Creating volume "wp_mariadb-data" with default driver
Creating volume "wp_mysql-data" with default driver
Creating wordpress ... done
Creating mariadb   ... done
Creating nginx     ... done
```

**Describe the solution you'd like**
I think add a **profiles** option key to top-level **volumes** could be legit:
```yml
volumes:
  mariadb-data:
    profiles:
      - mariadb
  mysql-data:
    profiles:
      - mysql
```

**Describe alternatives you've considered**
IMHO, adding a **profiles** key like above would require the user to make sure the profiles are matched between **services** config and top-level **volumes** config.

Could it be possible to inspect the volumes (after `docker-compose up`) to see which profile they're attached to (by inspecting the services declaring them), then if the profile is not activated, docker-compose won't create these volumes?

**Additional context**
My docker engine:
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
My docker-compose:
```
docker-compose version 1.28.6, build 5db8d86f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
**To be discussed**
Not sure if other top-level configs should be considered: **secrets**, **configs**.

Sorry for my bad English, I hope you guys get my idea 🐧
