### ISSUE TITLE
device_cgroup_rules support removed in 3.x

### ISSUE THREAD

**Issue by morremeyer** [docker/compose#8251]
## Description of the issue

`device_cgroup_rules` can’t be used in 3.x versions. It is present in 2.4, however. This requires me to use `version: '2.4'` instead of the newer `version: '3'`

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**

With `version: '3'`: 

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.cups: 'device_cgroup_rules'
```

With `version: '2.4'`: 
```
services:
  cups:
    container_name: cups
    device_cgroup_rules:
    - a *:* rwm
    devices:
    - /dev/bus/usb/001/003
    image: olbat/cupsd:latest@sha256:ed9500225cb5399d892a7004eec3d521fb6c80344eabc0ca8844eb0fae44197c
    ports:
    - 631:631/tcp
    restart: unless-stopped
    volumes:
    - cups-config:/etc/cups:rw
version: '2.4'
volumes:
  cups-config: {}
```

## Steps to reproduce the issue

1. Use the docker-compose file printed above.
2. Run `docker-compose config` or `docker-compose up -d`

### Observed result

`device_cgroup_rules` is unsupported. 

### Expected result

`device_cgroup_rules` is supported.

### Stacktrace / full error message

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.cups: 'device_cgroup_rules'
```

## Additional information

Running on Ubuntu 20.04, docker and all components installed with the official docker apt repository
