### ISSUE TITLE
Network aliases no longer work

### ISSUE THREAD

**Issue by ceecko** [docker/compose#8255]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CA2BE819-573F-4F78-BF1C-06B3CC672B68/20210404210743

### Actual behavior
Network aliases no longer work. The alias cannot be resolved as a hostname.
The `service2` container cannot ping `service1` container using `ser` hostname.
`service2` container can ping `service1` container using `service1` hostname.

### Expected behavior
Network aliases should be properly resolved.
`service2` shall resolve `ser` hostname.

### Information

  - Windows Version: 19042.906
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. Run `docker compose up`

This has appeared with recent versions. Previously it worked fine, although I'm not sure which version it was.

```
version: '3'
services:
  service1:
    image: debian
    networks:
      blue:
        aliases:
          - ser
        ipv4_address: 10.77.77.77
    command: ping google.com

  service2:
    image: debian
    networks:
      blue:
        ipv4_address: 10.77.77.78
    command: ping ser
  
networks:
  blue:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24
```
