### ISSUE TITLE
Resolve environmental files from .env

### ISSUE THREAD

**Issue by bcdiaconu** [docker/compose#8270]
** Is your feature request related to a problem? Please describe. **
I have the following dir structure:

```
+ environments  + environment_service1.env
|                           + environment_service2.env
|
+ .env
+ docker-compose.yml
```
in `.env` file for resolving `docker-compose.yml` contents:
```conf
SERVICE1_ADDR=http://service1.publisher.com
```

than in `environment_service1.env` I would have the environments used to run the container and are required by the container itself:
```conf
SERVICE_HTTP=${SERVICE1_ADDR}
```

than in `environment_service2.env` I would have the environments used to run the container and are required by the container itself:
```conf
SERVICE1_ADDR=${SERVICE1_ADDR}
```

finally the simplified `docker-compose.yml`:
```yml
services:
  service1:
    hostname: ${SERVICE1_ADDR}
    env_file:
    - ./environments/environment_1.env

  service2:
    env_file:
    - ./environments/environment_2.env
    # - maybe even some environment parts needed from ./environments/environment_1.env
```

Here I used a http address but it is to be used with ports also inside a docker-compose file under `ports:` and that way would be linking the services consistently

If I were to change the address of the service 1 will have to do it only once and will keep everything robust. This cannot be achieved at this point.

**Describe the solution you'd like **
Would be very helpful and robust to be able to resolve environment files contents (that are used in docker-compose under `env_file:`) with variable defined in `.env` file used to resolve docker-compose files. 

** Alternative solution **
Using elements defined in `.env` file also inside container when running and that will resolve also the contents of other environment files; but this increases the risk to create collisions with image environment
