### ISSUE TITLE
docker-compose built aboslute path confusion

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [docker/compose#8275]
## Description of the issue
When I use multiple docker-compose files that are referencing volumes with relative paths, the location of the first mentioned file is used as a reference for all the docker-compose files even though these files are located in different locations.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.6, build 5db8d86f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:52 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
Following are the 2 docker-compose config outputs where there are 2 files and in every test I switched the files order:
```
docker-compose -f /root/test/dir1/docker-composer-from-dir1.yml -f /root/test/dir2/docker-composer-from-dir2.yml config
services:
  test1-dir1:
    container_name: test-dir1
    image: nginx:alpine
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: always
    volumes:
    - /root/test/dir1/data/certbot/conf:/etc/letsencrypt:rw
    - /root/test/dir1/nginx:/etc/nginx:ro
    - /root/test/dir1/data/nginx/logs:/var/log/nginx:rw
    - /root/test/dir1/data/certbot/www:/var/www/certbot:rw
  test1-dir2:
    build:
      context: /root/test/dir1
    expose:
    - '8000'
    restart: always
    user: root
    volumes:
    - /root/test/dir1:/opt/test:ro
    - /root/test/dir1/.data/uploads:/var/uploads:rw
  test2-dir1:
    image: certbot/certbot
    volumes:
    - /root/test/dir1/data/certbot/conf:/etc/letsencrypt:rw
    - /root/test/dir1/data/certbot/log:/var/log/letsencrypt:rw
    - /root/test/dir1/data/certbot/www:/var/www/certbot:rw
version: '2.1'
```
Also
```
docker-compose -f /root/test/dir2/docker-composer-from-dir2.yml -f /root/test/dir1/docker-composer-from-dir1.yml config
services:
  test1-dir1:
    container_name: test-dir1
    image: nginx:alpine
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    restart: always
    volumes:
    - /root/test/dir2/data/certbot/conf:/etc/letsencrypt:rw
    - /root/test/dir2/nginx:/etc/nginx:ro
    - /root/test/dir2/data/nginx/logs:/var/log/nginx:rw
    - /root/test/dir2/data/certbot/www:/var/www/certbot:rw
  test1-dir2:
    build:
      context: /root/test/dir2
    expose:
    - '8000'
    restart: always
    user: root
    volumes:
    - /root/test/dir2:/opt/test:ro
    - /root/test/dir2/.data/uploads:/var/uploads:rw
  test2-dir1:
    image: certbot/certbot
    volumes:
    - /root/test/dir2/data/certbot/conf:/etc/letsencrypt:rw
    - /root/test/dir2/data/certbot/log:/var/log/letsencrypt:rw
    - /root/test/dir2/data/certbot/www:/var/www/certbot:rw
version: '2.1'
```
As you can see from first output, the absolute path is associated to the first mentioned file (in the -f parameter). While below you can see that 

## Steps to reproduce the issue
```
mkdir -p /root/test/
cd /root/test/
mkdir dir1 dir2
nano dir1/docker-composer-from-dir1.yml
```
Add the following content:
```
version: '2.1'

services:
  test1-dir1:
    container_name: test-dir1
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./data/nginx/logs:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  test2-dir1:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/log:/var/log/letsencrypt
```
Then
```
nano dir2/docker-composer-from-dir2.yml
```
Next
```
version: '2.1'

services:
  test1-dir2:
    build: .
    user: root
    restart: always
    volumes:
      - .data/uploads:/var/uploads
      - .:/opt/test:ro
    expose:
      - '8000'
```

Finally
```
docker-compose -f /root/test/dir2/docker-composer-from-dir2.yml -f /root/test/dir1/docker-composer-from-dir1.yml config
docker-compose -f /root/test/dir1/docker-composer-from-dir1.yml -f /root/test/dir2/docker-composer-from-dir2.yml config
```

Changing the version from 2.1 even to 3.7 will not change anything. This issue was tested with `docker-compose config` only. I didn't have any example to create containers and check how the volume binding is working but I wanted to report this issue here so that it gets to the proper hands, we never know what else we can find.

I've discovered this issue while I was running a similar complex example where I have to run docker-compose in a specific folder and in specific conditions I've to add another docker-compose file from another folder. So this is the first time I see this issue and I don't know what was the expected result. Should the absolute path be associated with the current location or associated with where the docker-compose file is located? I didn't have seen any answer anywhere so I wanted to report it here.

### Observed result
I'm not sure what was the observed result since both results doesn't looks the expected ones

### Expected result
I'm not sure what was the observed result since both results doesn't looks the expected ones

### Stacktrace / full error message
No errors

## Additional information

OS version / distribution, `docker-compose` install method, etc.
```
uname -a
Linux validation 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
I've installed docker and docker-compose using apt-get install (from the official docker documentation).

Thank you for your help.
