### ISSUE TITLE
Docker-compose config's "depends_on" does not comply with docker stack deploy since its no longer a YAML list

### ISSUE THREAD

**Issue by ProteanCode** [docker/compose#8287]
Simply put I have newest docker & docker-compose running on Ubuntu 18.04

Because of some incompatibilities or other quirks I mostly used following command to generate a stack file for Docker Swarm

`docker-compose -f docker-compose.stack.yml config > stack.yml && docker stack deploy -c stack.yml foo && rm stack.yml`

This will no longer work since depends_on has changed from list to ie.
```
  nginx:
    depends_on:
      php:
        condition: service_started
```
I guess I will have to downgrade docker-compose version
