### ISSUE TITLE
docker-compose does not parse port strings the same as Docker CLI

### ISSUE THREAD

**Issue by chris-crone** [docker/compose#8293]
## Description of the issue

Using the following Compose file:
```yaml
test:
   image: nginx:alpine
   ports:
     - "127:0.0.1:8000:80"
```

`docker-compose` deploys when it should alert the user to an invalid address. `docker run --rm -p "127:0.0.1:8000:80" nginx:alpine` fails as it should:
```console
docker: Invalid ip address 127:0.0.1: address 127:0.0.1:: too many colons in address.
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.0, build 07737305
```
