### ISSUE TITLE
docker-compose build --pull doesn't work when using profiles

### ISSUE THREAD

**Issue by albertlincoln** [docker/compose#8295]
## Description of the issue
When there are no profiles setup in docker-compose.yaml, running `docker-compose build --pull` will do as expected. When there are profiles in docker-compose.yaml, running `docker-compose build --pull` produces no output. If I specify a service or services to build, it works as expected also, but I don't see why the behavior should differ if no service is specified.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
$ docker-compose version
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
$ docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Dec 18 12:21:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  something-dev:
    image: something/something:latest
    logging:
      driver: none
    profiles:
    - dev
  something-only:
    image: something/something:latest
    logging:
      driver: none
    profiles:
    - test
```

## Steps to reproduce the issue

1. Run `docker-compose build --pull` with a docker-compose file that doesn't contain profiles
2. Add profiles to the services
3. Run `docker-compose build --pull` again and note that nothing happens

### Observed result
No output and nothing built.

### Expected result
The services to be built.

## Additional information

* Using WSL2 backend

**Comment by everton-nasc** [comment]
Facing exactly same issue.

**Comment by karandalvi** [comment]
You need to enable these services when running docker-compose using the `--profile` flag. Services without a profiles attribute will always be enabled.

Consider the following docker-compose file,
```
services:
  service-a:
    image: something/something:latest
    profiles:
    - dev
  service-b:
    image: something/something:latest
    profiles:
    - stg
    - qa
  service-c:
    image: something/something:latest
```

1. No Profiles Enabled
`docker-compose build --pull `
Services Enabled: service-c

2. Enable a Profile
`docker-compose --profile dev build --pull `
Services Enabled: service-a, service-c

3. Enable Multiple Profiles 
`docker-compose --profile dev --profile stg build --pull `
Services Enabled: service-a, service-b, service-c
