### ISSUE TITLE
Unknown flag --iidfile

### ISSUE THREAD

**Issue by GoncaloCamaz** [docker/compose#8296]
## Description of the issue

I am trying to build a microservice application on a CentOS7 redhat server. Database build successfully but an error is occurring 
while building a Java image. I get an error namely "unknown flag: --iidfile. 
This problem happens on the machine with the descriptions sent bellow however it builds perfectly on my machine which is an desktop with windows with WSL 2 installed.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
Docker-compose version 1.29.0, build 07737305
```

**Output of `docker version`**
```
Docker version 1.13.1, build 0be3e21/1.13.1
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version 3.5

service-backend:
 build:
  context: ./Backend
  dockerfile: Dockerfile

volumes:
 mysql-data:
  external: true
  name: mysql-data
```

## Steps to reproduce the issue

1. Building docker compose file
2. docker-compose up -d --build

### Stacktrace / full error message

```
Building service-backend
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'service-backend' failed to build
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by thaJeztah** [comment]
Looks like you are running a very old version of Docker ([`v1.13.1`](https://github.com/moby/moby/releases/tag/v1.13.1)) that reached EOL over 4 years ago and is no longer maintained. The `--iidfile` option was added in Docker 17.06 (through) https://github.com/moby/moby/pull/32406 

```
Docker version 1.13.1, build 0be3e21/1.13.1
```


From that version, I _suspect_ you are running the Red Hat fork of Docker, which we don't maintain, and which has many custom modifications in the code-base.

Are you seeing the same problem when installing a currently maintained version of the official Docker packages for CentOS? (instructions here: https://docs.docker.com/engine/install/centos/)

If you _are_ indeed running the Red Hat fork of Docker; their version is known to carry some incompatible changes in how  images are stored, which in some case requires you to reset the local image cache and docker storage (removing images and containers), so before uninstalling the forked version and upgrading to the official packages, make sure that you have your important images pushed to a registry and important data (data in volumes, perhaps notes of containers you need to recreate) before upgrading.

**Comment by thaJeztah** [comment]
Let me close this ticket, because this doesn't look like a bug, but feel free to continue the conversation

**Comment by GoncaloCamaz** [comment]
Thank you for your fast response and help! 

With best regards,
Gonçalo

**Comment by renepardon** [comment]
Have the same problem: (installed today with official guide) on Debian Bullseye

```bash
jenkins@67b330f0af7c:/$ docker -v
Docker version 20.10.14, build a224086
jenkins@67b330f0af7c:/$ docker-compose -v
docker-compose version 1.29.1, build c34c88b2
```

```bash
08:08:28  + docker-compose build --force-rm --no-cache --pull
08:08:29  Building httpd
08:08:29  unknown flag: --iidfile
08:08:29  See 'docker build --help'.
```

**Comment by renepardon** [comment]
EDIT 2: downgrade to docker-compose 1.26.2 resolves the problem but this is a severe issue

**Comment by thaJeztah** [comment]
Are you sure those commands are running in the same environment? If you run a `docker build --help` as part of your Jenkins steps, does it show the `--iidfile` flag to be present?

Trying on compose v1.29.2, with docker 20.10 installed, I'm not able to reproduce the issue, using a minimal compose file with a Dockerfile in the current directory;

```yaml
services:
  servicea:
    build:
      context: .

  serviceb:
    build:
      context: .
```

**Comment by renepardon** [comment]
> Are you sure those commands are running in the same environment? If you run a `docker build --help` as part of your Jenkins steps, does it show the `--iidfile` flag to be present?
> 
> Trying on compose v1.29.2, with docker 20.10 installed, I'm not able to reproduce the issue, using a minimal compose file with a Dockerfile in the current directory;
> 
> ```yaml
> services:
>   servicea:
>     build:
>       context: .
> 
>   serviceb:
>     build:
>       context: .
> ```

I didnt execute `docker build --help`, but the Docker daemon is bound to Jenkins which is a single Node, therefore also no additional worker. My compose file looks as simple as:

```yaml
version: '3.3'
services:
  httpd:
    image: myapp/thing
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_httpd
    restart: unless-stopped
    environment:
      - APACHE_SERVER_NAME=localhost
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:latest
    command: mysqld --sql_mode="IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: myapp
```
