### ISSUE TITLE
Can't setup symfony localhost webserver with docker

### ISSUE THREAD

**Issue by gmu-fardin** [docker/compose#8298]
I have followed a tutorial on https://medium.com/@cleverti/how-to-setup-docker-for-a-symfony-project-26d304359592 where it shows how to setup docker for a symfony project. I only integrated the nginx container in my own ```docker-compose.yml```:  

```
version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
          - DATABASE_URL=mysql://sf4:sf4@mysql:3306/sf4?serverVersion=8.0.23&charset=utf8
        depends_on:
          - mysql

    web:
        build: .docker/nginx
        restart: always
        ports:
          - '81:80'
        depends_on:
          - php
          - mysql
        volumes:
          - .:/home/wwwroot/sf4

```
When run docker-compose ps i get the schema of containers that are running:
```
accountingapi_web_1   nginx                            Restarting
sf4_apache            /bin/sh -c apachectl  -DFO ...   Up           443/tcp, 0.0.0.0:52624->80/tcp
sf4_mysql             docker-entrypoint.sh --def ...   Up           3306/tcp, 33060/tcp
sf4_php               docker-php-entrypoint php-fpm    Up           9000/tcp

```
 I added this Dockerfile inside nginx folder:
```
FROM debian:stretch

RUN apt-get update && apt-get install -y nginx vim nano

COPY nginx.conf /etc/nginx/nginx.conf

ADD sites-enabled /etc/nginx/sites-enabled

RUN rm /etc/nginx/sites-enabled/default

WORKDIR /home/wwwroot/sf4

EXPOSE 80
EXPOSE 443

CMD ["nginx"]

```

I have added all the directories inside a directory called .docker. I have added inside this directory all the directories for the containers including nginx. Inside this nginx folder i have added the sites-enabled directory, Dockerfile and nginx.conf. Inside the sites-enabled folder i added the default and default_symfony file. 

I am able to start all containers but when i run localhost:81 on my browser it shows that firefox can't connect to server. I followed every step from the tutorial. I also tried it on chrome but still no result.

My question is how can i resolve this issue and how can i see the localhost:81 server on my browser?
