### ISSUE TITLE
extra_host will be wrongly overwritten

### ISSUE THREAD

**Issue by cstoehr** [docker/compose#8300]
## Description of the issue
if you merge 2 or more docker_compose files then the extra_hosts will be wrongly overwritten.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
it changed see below
```

## Steps to reproduce the issue

1. create 2 docker-compose files

Dockerfile 1:
```
version: '3.6'
services:
  frontend:
    extra_hosts:
      - "dev.local:192.168.2.2"
      - "npm.dev.local:192.168.2.3"
    build:
      context: build/docker
      dockerfile: frontendTest/Dockerfile
      args:
        test: 2
```
Dockerfile 2:
```
version: '3.6'

services:
  frontend:
    build:
      args:
        test: 1
```

2. Run: $ ```docker-compose -f docker-compose.1.yml config```

```
services:
  frontend:
    build:
      args:
        test: '2'
      context: /home/stoehrc/Dokumente/Projekte/products/lbs.de/diva-e/webapp-builder/build/docker
      dockerfile: frontendTest/Dockerfile
    extra_hosts:
    - dev.local:192.168.2.2
    - npm.dev.local:192.168.2.3
version: '3.6'
```
3. Run: ```docker-compose -f docker-compose.1.yml -f docker-compose.2.yml  config```
```
services:
  frontend:
    build:
      args:
        test: '1'
      context: .
      dockerfile: frontendTest/Dockerfile
    extra_hosts:
      dev.local: 192.168.2.2
      npm.dev.local: 192.168.2.3
version: '3.6'
```

### Observed result
```
extra_hosts:
      dev.local: 192.168.2.2
      npm.dev.local: 192.168.2.3
```
### Expected result
```
extra_hosts:
    - dev.local:192.168.2.2
    - npm.dev.local:192.168.2.3
```
## Additional information

OS 20.1 / Linux Mint, `docker-compose build` .
