### ISSUE TITLE
3.3.3 regression: docker-compose up become slow, some logs are empty or incomplete.

### ISSUE THREAD

**Issue by jjqq2013** [docker/compose#8325]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D8B745DA-A4C4-41CE-8215-23C5857F57E0/20210513071136

### Expected behavior
- when docker-compose up shows "creating xxx...conainter", it should finish soon, like in previous Docker (3.2.1),  8 containers takes around 0.1s.

- logs in Dashboard should be complete
 
### Actual behavior
- 8 containers takes takes 12+ seconds.

- logs of some containers are empty or incomplete. Note, this issue also exists in Windows version.

### Information

  - macOS Version: macOS Catalina
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.3.3

### Steps to reproduce the behavior

 The first issue(docker-compose up slow) can be reproduced by following steps
 ```
#!/bin/bash
set -e -o pipefail
mkdir -p test-docker-compose-up
cd test-docker-compose-up
cat <<EOF > docker-compose.yml
version: "3.4"

services:
  svc1:
    image: alpine
    command: [echo, hi]
  svc2:
    image: alpine
    command: [echo, hi]
  svc3:
    image: alpine
    command: [echo, hi]
  svc4:
    image: alpine
    command: [echo, hi]
  svc5:
    image: alpine
    command: [echo, hi]
  svc6:
    image: alpine
    command: [echo, hi]
  svc7:
    image: alpine
    command: [echo, hi]
  svc8:
    image: alpine
    command: [echo, hi]
EOF
docker-compose up

echo ============begin test docker-compose up===========
time docker-compose up
echo ============end===========
```
  

 But the second issue(logs incomplete), I can not reproduce, but often seen the issue, I have recorded a video, see https://youtu.be/fK4T0Y_l3GM
