### ISSUE TITLE
Docker-compose: Large port definitions exceed request timeout 

### ISSUE THREAD

**Issue by CafeLungo** [docker/compose#8327]
## Description of the issue

Large port definitions in a docker compose seem to cause docker-compose `start` or `stop` commands to exceed a 60 second timeout. Unsure when this started, but at least Docker Desktop 3.3.X has been presenting this problem. Prior release, perhaps before 3.0 (only a guess), this has not been a problem.

Obviously, my example below is a minimized example to display the problem.

Example `docker-compose.yml`:
```(yaml)
version: '3.7'

services:
  test:
    image: alpine
    ports:
    - '60000-60128:60000-60128'
    command: /bin/sh -c "echo hello && sleep 600"
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  test:
    command: /bin/sh -c "echo hello && sleep 600"
    image: alpine
    ports:
    - published: 60000
      target: 60000
    - published: 60001
      target: 60001
    - published: 60002
      target: 60002
    - published: 60003
      target: 60003
    - published: 60004
      target: 60004
    - published: 60005
      target: 60005
    - published: 60006
      target: 60006
    - published: 60007
      target: 60007
    - published: 60008
      target: 60008
    - published: 60009
      target: 60009
    - published: 60010
      target: 60010
    - published: 60011
      target: 60011
    - published: 60012
      target: 60012
    - published: 60013
      target: 60013
    - published: 60014
      target: 60014
    - published: 60015
      target: 60015
    - published: 60016
      target: 60016
    - published: 60017
      target: 60017
    - published: 60018
      target: 60018
    - published: 60019
      target: 60019
    - published: 60020
      target: 60020
    - published: 60021
      target: 60021
    - published: 60022
      target: 60022
    - published: 60023
      target: 60023
    - published: 60024
      target: 60024
    - published: 60025
      target: 60025
    - published: 60026
      target: 60026
    - published: 60027
      target: 60027
    - published: 60028
      target: 60028
    - published: 60029
      target: 60029
    - published: 60030
      target: 60030
    - published: 60031
      target: 60031
    - published: 60032
      target: 60032
    - published: 60033
      target: 60033
    - published: 60034
      target: 60034
    - published: 60035
      target: 60035
    - published: 60036
      target: 60036
    - published: 60037
      target: 60037
    - published: 60038
      target: 60038
    - published: 60039
      target: 60039
    - published: 60040
      target: 60040
    - published: 60041
      target: 60041
    - published: 60042
      target: 60042
    - published: 60043
      target: 60043
    - published: 60044
      target: 60044
    - published: 60045
      target: 60045
    - published: 60046
      target: 60046
    - published: 60047
      target: 60047
    - published: 60048
      target: 60048
    - published: 60049
      target: 60049
    - published: 60050
      target: 60050
    - published: 60051
      target: 60051
    - published: 60052
      target: 60052
    - published: 60053
      target: 60053
    - published: 60054
      target: 60054
    - published: 60055
      target: 60055
    - published: 60056
      target: 60056
    - published: 60057
      target: 60057
    - published: 60058
      target: 60058
    - published: 60059
      target: 60059
    - published: 60060
      target: 60060
    - published: 60061
      target: 60061
    - published: 60062
      target: 60062
    - published: 60063
      target: 60063
    - published: 60064
      target: 60064
    - published: 60065
      target: 60065
    - published: 60066
      target: 60066
    - published: 60067
      target: 60067
    - published: 60068
      target: 60068
    - published: 60069
      target: 60069
    - published: 60070
      target: 60070
    - published: 60071
      target: 60071
    - published: 60072
      target: 60072
    - published: 60073
      target: 60073
    - published: 60074
      target: 60074
    - published: 60075
      target: 60075
    - published: 60076
      target: 60076
    - published: 60077
      target: 60077
    - published: 60078
      target: 60078
    - published: 60079
      target: 60079
    - published: 60080
      target: 60080
    - published: 60081
      target: 60081
    - published: 60082
      target: 60082
    - published: 60083
      target: 60083
    - published: 60084
      target: 60084
    - published: 60085
      target: 60085
    - published: 60086
      target: 60086
    - published: 60087
      target: 60087
    - published: 60088
      target: 60088
    - published: 60089
      target: 60089
    - published: 60090
      target: 60090
    - published: 60091
      target: 60091
    - published: 60092
      target: 60092
    - published: 60093
      target: 60093
    - published: 60094
      target: 60094
    - published: 60095
      target: 60095
    - published: 60096
      target: 60096
    - published: 60097
      target: 60097
    - published: 60098
      target: 60098
    - published: 60099
      target: 60099
    - published: 60100
      target: 60100
    - published: 60101
      target: 60101
    - published: 60102
      target: 60102
    - published: 60103
      target: 60103
    - published: 60104
      target: 60104
    - published: 60105
      target: 60105
    - published: 60106
      target: 60106
    - published: 60107
      target: 60107
    - published: 60108
      target: 60108
    - published: 60109
      target: 60109
    - published: 60110
      target: 60110
    - published: 60111
      target: 60111
    - published: 60112
      target: 60112
    - published: 60113
      target: 60113
    - published: 60114
      target: 60114
    - published: 60115
      target: 60115
    - published: 60116
      target: 60116
    - published: 60117
      target: 60117
    - published: 60118
      target: 60118
    - published: 60119
      target: 60119
    - published: 60120
      target: 60120
    - published: 60121
      target: 60121
    - published: 60122
      target: 60122
    - published: 60123
      target: 60123
    - published: 60124
      target: 60124
    - published: 60125
      target: 60125
    - published: 60126
      target: 60126
    - published: 60127
      target: 60127
    - published: 60128
      target: 60128
version: '3.7'
```

## Steps to reproduce the issue

1. Run `start` or `stop` on a docker-compose.yml with large port definitions (port count unknown, but ~128 sequential ports seems to cause problems)
2. After a short wait time, attempting the `start` or `stop` again, will succeed, though. Of course, it's continuing in the background async after the request times out.

### Observed result
Example output:
```
Creating network "test_ports_default" with the default driver
Pulling test (alpine:)...
latest: Pulling from library/alpine
540db60ca938: Already exists
Digest: sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Status: Downloaded newer image for alpine:latest
Creating test_ports_test_1 ...

ERROR: for test_ports_test_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for test  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

### Expected result
Successful, and preferably less than 60 seconds to start or stop a container.

### Stacktrace / full error message

```
N/A, shown above in observed output
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
- OS: macOS 10.15.7
- Docker installed via Docker Desktop for Mac, standard configurations.
- MacBook Pro 16", 2.4 GHz 8-Core i9, 32GB DDR4 RAM
