### ISSUE TITLE
Env file passed with --env-file ist not recognized

### ISSUE THREAD

**Issue by rooselle** [docker/compose#8332]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  apache_php:
    build:
      context: /home/chloe/Documents/Roselle/dev/roselle/.docker/apache_php
    container_name: apache_php
    ports:
    - published: 80
      target: 80
    volumes:
    - /home/chloe/Documents/Roselle/dev/roselle/.docker/config/vhosts:/etc/apache2/sites-enabled:rw
    - /home/chloe/Documents/Roselle/dev/roselle:/var/www/html:rw
  blackfire:
    container_name: blackfire
    environment:
      BLACKFIRE_CLIENT_ID: truc
      BLACKFIRE_CLIENT_TOKEN: ''
      BLACKFIRE_DISABLE_LEGACY_PORT: 1
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_SERVER_ID: ''
      BLACKFIRE_SERVER_TOKEN: ''
    image: blackfire/blackfire:2
    ports:
    - target: 8307
  db:
    container_name: db
    environment:
      MYSQL_DATABASE: roselle
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
    image: library/mysql:5.7
    ports:
    - published: 3306
      target: 3306
    volumes:
    - /home/chloe/Documents/Roselle/dev/roselle/.docker/data/mysql:/var/lib/mysql:rw
  dockerize:
    container_name: dockerize
    image: jwilder/dockerize
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      db:
        condition: service_started
    environment:
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_PORT: 8080
      PMA_USER: root
    image: phpmyadmin/phpmyadmin
    ports:
    - published: 8080
      target: 80
version: '3.5'
```

## Steps to reproduce the issue

My problem is with values passed to blackfire service:

1. I have an .env file which is committed and that have default empty values for blackfire variables. For the test, I added a value "truc" to show that it's the .env file that is recognised.
2. I have an .env.local file which is not committed and where there are the actual values for blackfire variables.
3. I run `docker-compose --env-file .env.local up -d --remove-orphans --no-recreate`

### Observed result
It's the .env file that is recognised (see above `docker-compose config`).

### Expected result
I want the .env.local file to be recognised.

### Stacktrace / full error message
No error is displayed.

## Additional information
I'm on Ubuntu 20.04.
