### ISSUE TITLE
Add the possibility to depend on a profile

### ISSUE THREAD

**Issue by 1c3t3a** [docker/compose#8333]
**Describe the solution you'd like**
It would be nice to use docker-compose profiles in a way that I could use them in `depend_on`. An example would look something like this:
```yaml
version: 3.9
services:
  web:
    build: .
    ports:
      - "5000:5000"
    profiles: ["frontend"]
    depends_on: 
      - "backend"
  redis:
    image: "redis:alpine"
    profiles: ["backend"]
  db:
    image: "postgres:latest"
    profiles: ["backend"]
```

**Describe alternatives you've considered**
Using normal syntax would require writing out all services. This is also not that much work, but for large files I'd definitely see an improvement.

**Additional context**
I don't know if you've already considered this and decided against it or if that it's not how profiles were planned out, but I would definitely have some use cases for this.
