### ISSUE TITLE
Inconsistency with absolute paths on `context` directory

### ISSUE THREAD

**Issue by deains** [docker/compose#8334]
## Description of the issue

When an absolute path is given for the `context` path in a service's build, the new `docker compose` command fails to build that service. The output of `docker compose config` versus `docker-compose config` shows that there is a difference in behaviour when it comes to determining the path to the Dockerfile. The upshot is that `docker compose` looks in the wrong place for the Dockerfile, and errors.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
```
services:
  breaks:
    build:
      context: /Users/damian/downloads/docker-test/contextdir
      dockerfile: dockerfiledir/Dockerfile
  works:
    build:
      context: /Users/damian/Downloads/docker-test/contextdir
      dockerfile: dockerfiledir/Dockerfile
version: '3.6'
```

**Output of `docker compose config`**
```
services:
  breaks:
    build:
      context: /Users/damian/downloads/docker-test/contextdir
      dockerfile: dockerfiledir/Dockerfile
    networks:
      default: null
  works:
    build:
      context: /Users/damian/Downloads/docker-test/contextdir
      dockerfile: /Users/damian/Downloads/docker-test/contextdir/dockerfiledir/Dockerfile
    networks:
      default: null
networks:
  default:
    name: docker-test_default
```

## Steps to reproduce the issue

1. Download and extract the attached [docker-test.zip](https://github.com/docker/compose/files/6500887/docker-test.zip) example
2. Adjust the absolute paths for your system
3. Run `docker compose build` in the `docker-test` directory

### Observed result

Command error (see below for output).

### Expected result

`docker-compose build` works with my given example, so I believe the new command should be able to handle this setup as well.

### Stacktrace / full error message

```
[+] Building 0.0s (0/0)
could not find dockerfiledir: stat dockerfiledir: no such file or directory
```

## Additional information

Running macOS Big Sur 11.3.1

Docker Desktop for Mac version:
![Screenshot 2021-05-18 at 12 13 34 pm](https://user-images.githubusercontent.com/750763/118641837-8e19c200-b7d2-11eb-97e0-ec9849745b11.png)
