### ISSUE TITLE
Define logging attribute at file level

### ISSUE THREAD

**Issue by koutsilisk** [docker/compose#8341]
**Is your feature request related to a problem? Please describe.**
At this point we can define the logging on a service level or with the daemon.json file globaly

```yaml
# Example docker-compose file
services:
  test:
      restart: always
      image: testimage
      logging:
         driver: "journald"
  redis:
      restart: always
      image: redis:3.2-alpine
      command: redis-server
      logging:
        driver: "journald"
```

**Describe the solution you'd like**
I would like to be able to define the logging at file level. For example as we define networks

```yaml
# Example solution docker-compose file
services:
  test:
      restart: always
      image: testimage
   
  redis:
      restart: always
      image: redis:3.2-alpine
      command: redis-server
     
logging:
    driver: "journald"
 
```

**Describe alternatives you've considered**
None

**Additional context**
None
