### ISSUE TITLE
Entrypoint argument at docker compose run cli command not overwrite described at compose file

### ISSUE THREAD

**Issue by r3cha** [docker/compose#8342]
## Description of the issue
I've docker-compose.yml file 
with following service
```yml
version: "3.9"

services:
  app:
    image: imagename
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    depends_on:
      - redis
      - webpacker
      - postgres
    env_file:
      - docker/development/.env
    volumes:
      - .:/app:z
    ports:
      - 3000:3000
    entrypoint: docker/entrypoint.sh
    command: command
```

Using this command `docker-compose run --entrypoint '' app bash`
I expect that I overwrite/skip `docker/entrypoint.sh` -  working fine ie mean that is not running, and I run bash command without entrypoint.  

But using `docker compose  run --entrypoint '' app bash` will not overwrite app service  `docker/entrypoint.sh`
and entrypoint script is executed.  
I add this `echo 'this is echo command that is on entrtypoint file defined at compose app service'` there.  

## Context information (for bug reports)
all fine
```
➜  folder git:(feature) ✗ docker-compose run --entrypoint '' app bash
Creating designbro-v2_app_run ... done
root@df4eb1e57672:/app#
```

oops entrypoint executed
```
➜  folder git:(feature) ✗ docker compose run --entrypoint '' app bash
[+] Running 3/0
 ⠿ Container folder-v2_redis_1      Running                                                                                                                                                             0.0s
 ⠿ Container folder-v2_webpacker_1  Running                                                                                                                                                             0.0s
 ⠿ Container folder-v2_postgres_1   Running                                                                                                                                                             0.0s
this is echo command that is on entrtypoint file defined at compose app service
root@10c408143a20:/app#
```

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Docker Compose version 2.0.0-beta.1%
```

### Observed result
`docker compose run --entrypoint=''` not overwrite app service entrypoint
### Expected result
`docker compose run --entrypoint=''` should overwrite app service  entrypoint

## Additional information
Docker for mac
<img width="262" alt="Screenshot 2021-05-21 at 4 31 03 PM" src="https://user-images.githubusercontent.com/8098344/119145060-f1fdee00-ba51-11eb-8639-3b4dccd148d9.png">
