### ISSUE TITLE
set arbitrary strings through environment

### ISSUE THREAD

**Issue by gred7** [docker/compose#8350]
**Is your feature request related to a problem? Please describe.**
 I have a project which for some strange reason requires configuration in small files. For example, http_listen=127.0.0.1:80 would be written as:
echo 127.0.0.1:80 > config/http/listen

**Describe the solution you'd like**
when I have service configured like this:
services:
    someservice:
        image: someimage
        environment:
             config/http/listen: 127.0.0.1:80
             config/other/var: some_value

I expect compose to populate container's environment with just this lines like:
config/http/listen=127.0.0.1:80
config/other/var=some_value

so I will be able to pass values from my docker-compose.yml.

**Comment by bartier** [comment]
@gred7 I don't recommend using `/` in environment variables. At the same time, I tried and it's possible to use it with `bash`. Try running this `file` to check it:

```
# example.yml
version: "3.9"
services:
  test_service:
    image: nginx
    environment:
      FOO/other/thing/here: bar
      BAR: foo2
```
Running and checking:
```
docker-compose -f example.yml up
docker exec -ti <change_to_the_container_name> bash -c 'env | grep -i foo'
```

I'm not sure about your intention yet. If you share a runnable .yml file, we can reproduce what you mean so we can discuss it.
