### ISSUE TITLE
Feature: docker-compose up -d with waiting for healthy statuses

### ISSUE THREAD

**Issue by mik-laj** [docker/compose#8351]
**Is your feature request related to a problem? Please describe.**
I am working on a project that heavy use of `depends_on` filed with conditions when creating containers.  This allows us to run databases, migrations, and applications reliably.

My situation can be compared to the below docker-compose.yaml file
```yaml
services:

  db:
    image: debian:buster-slim
    command:
      - bash
      - -c
      - |
        echo "Start"
        for x in $$(seq 1 5); do sleep 1; echo "sleep $${x}/5"; done;
        touch /migartion-done;
        echo "OK";
        for x in $$(seq 1 60); do sleep 10; echo "sleep $$((x * 10))/600";done;
    healthcheck:
      test: ["CMD-SHELL", "test -f /migartion-done"]
      interval: "1s"
      retries: 30

  app-init:
    image: debian:buster-slim
    command:
      - bash
      - -c
      - |
        echo "OK";
    depends_on:
      db:
        condition: service_healthy

  app:
    image: debian:buster-slim
    command:
      - bash
      - -c
      - |
        echo "Start"
        for x in $$(seq 1 5); do sleep 1; echo "sleep $${x}/5"; done;
        touch /webserver-started"
        for x in $$(seq 1 60); do sleep 10; echo "sleep $$((x * 10))/600";done;
    healthcheck:
      test: [ "CMD-SHELL", "test -f /webserver-started" ]
      interval: "1s"
      retries: 30
    depends_on:
      app-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
```
Where
 - `db`  is a service that runs continuously but takes a while to start. Other containers should not start until this service is started and is healthy. ``condition: service_healthy``
 - `app-init`  is a one-run container. Other containers should not start until this service is started and finish. ``condition: service_completed_successfully``
 - `app` is a service that runs continuously but takes a while to start. 

Currently, after executing the docker-compose up command, all containers are started/completed, but docker-compose only ensures that the `db` and `app-init`  containers are healthy/completed. The `app` container is still in an unhealthy condition.

**Describe the solution you'd like**
It would be fantastic if docker-compose also took into account the state of the last container (`app`) and waited for it to report the correct healthy status. This may be protected by an additional flag, e.g. `--wait-for-healthy-status`.

**Describe alternatives you've considered**

For now, I have implemented the health check logic in my scripts, but this is code duplication.

Alternatively, we can also add the ability to list containers by health status to `docker ps --services ` . The docker-compose command has filters, but they are very limited.  It supports only 4 states: `running`, `stopped`, `paused`, `restarting`.  
https://github.com/docker/compose/blob/73f8cf9132018429783e65bde66f8f961637e418/compose/cli/main.py#L1634-L1667
When we add support for the health status filter, it will be much easier for me to write a script waiting for all containers.
```
while [[ "$(docker-compose ps --services --filter state=unhealthy)" == "" ]]; do sleep 1; echo sleep 1; done;
```

@trajano proposed to add a separate command that will allow us to check the condition of the containers. https://github.com/docker/compose/issues/6408
**Additional context**

CC: @shin- , @ulyssessouza

**Comment by mik-laj** [comment]
For now, I use the following the code to wait for containers:
```bash
function wait_for_container {
    container_id="$1"
    container_name="$(docker inspect "${container_id}" --format '{{ .Name }}')"
    echo "Waiting for container: ${container_name} [${container_id}]"
    waiting_done="false"
    while [[ "${waiting_done}" != "true" ]]; do
        container_state="$(docker inspect "${container_id}" --format '{{ .State.Status }}')"
        if [[ "${container_state}" == "running" ]]; then
            health_status="$(docker inspect "${container_id}" --format '{{ .State.Health.Status }}')"
            echo "${container_name}: container_state=${container_state}, health_status=${health_status}"
            if [[ ${health_status} == "healthy" ]]; then
                waiting_done="true"
            fi
        else
            echo "${container_name}: container_state=${container_state}"
            waiting_done="true"
        fi
        sleep 1;
    done;
}

COMPOSE_FILE="${compose_file}" docker-compose ps -q | while IFS= read -r container_id; do
    wait_for_container "${container_id}"
done
```
Example output
```
Waiting for container: /docker-compose_airflow-init_1 [29828d2da582290d2b32467ae38e3d679b9504ec1f892278e3f629becbcbbeb9]
/docker-compose_airflow-init_1: container_state=exited
Waiting for container: /docker-compose_airflow-scheduler_1 [756eebc5442bfcfc2c206aa50f0a488c6c86176dce0a0d7c4ce8dd96b05da29d]
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=starting
/docker-compose_airflow-scheduler_1: container_state=running, health_status=healthy
Waiting for container: /docker-compose_airflow-webserver_1 [53dede0b7640575dfba4dc4da53fddce6a8ff2b719064cb6826695e03edb79b1]
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=starting
/docker-compose_airflow-webserver_1: container_state=running, health_status=healthy
Waiting for container: /docker-compose_mysql_1 [6f912e9dc32cd31ad0b310566918a10813c3a0a8f1e5879d4ab75789210f65df]
/docker-compose_mysql_1: container_state=running, health_status=healthy
```

**Comment by mik-laj** [comment]
@ndeloof Have you thought about adding a flag that will allow you to wait until ALL services are healthy? I think. about something like ``docker-compose up -d --wait-for-all condition`` or simply ``docker-compose up -d --wait-for-all-healthy``. I don't need to wait for a specific one, but I just want to know when the docker environment has been fully launched.

**Comment by Luc45** [comment]
The newly added `--wait` flag in Docker Compose v2 is the way to go, but if you are stuck with docker-compose v1, this bogus service will achieve a similar result:

```
wait:
  image: hello-world:latest
  depends_on:
      some-container:
          condition: service_healthy
```
