### ISSUE TITLE
Docker compose down -v does not remove volumes defined in docker-compose.yml

### ISSUE THREAD

**Issue by Ced-Sharp** [docker/compose#8355]
## Description of the issue
`docker compose down -v` does not remove volumes mapped in the `docker-compose.yml` file.

## Context information (for bug reports)
The built-in `docker compose` does not remove volumes when running `docker compose down -v`.
The documentation mentions that `-v, --volume` should additionally remove all volumes defined in the `docker-compose.yml` file.

**Output of `docker compose version`**
```
Docker Compose version 2.0.0-beta.1
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker compose config`**
```
services:
  db:
    environment:
      POSTGRES_DB: upsell
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
    - "5432"
    image: postgres:13
    networks:
      default: null
    volumes:
    - type: volume
      source: database
      target: /var/lib/postgresql/data
    - type: volume
      source: db_socket
      target: /var/run/postgresql/
  server:
    build:
      context: /Users/cedricdubois/work/tv
      dockerfile: /Users/cedricdubois/work/tv/Dockerfile
    container_name: upsell-server
    environment:
      DB_SOCKET_DIR: /var/run/postgresql
      FLASK_RUN_HOST: 0.0.0.0
    image: upsell-server:0.1
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8000
      published: 8000
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/cedricdubois/work/tv
      target: /app/
    - type: volume
      source: db_socket
      target: /var/run/postgresql/
networks:
  default:
    name: tv_default
volumes:
  database:
    name: tv_database
  db_socket:
    name: tv_db_socket
```

## Steps to reproduce the issue

1. Create a `docker-compose.yml` file containing some locale volumes;
2. Run `docker compose up -d` and wait until volumes have been created;
3. Run `docker compose down -v`, notice the output never mentions anything related to volumes

### Observed result
The output of `docker compose down -v` mentions it deleted the containers and the network, but doesn't mention the volumes. Running `docker volume list` shows the volumes still exists. 

### Expected result
The output of `docker compose down -v` should also show that it removed the volumes, and the volumes should not
be visible in `docker volume list` anymore.

### Stacktrace / full error message
There is no error message, rather, there is a lack of message.

## Additional information
Here is what I see in my terminal (note: I have an alias: `alias dc="docker compose"`)
![image](https://user-images.githubusercontent.com/56606410/120239310-9981da00-c223-11eb-95bb-9a46eb158598.png)

I am using MacOS Big Sur.
