### ISSUE TITLE
docker compose rm removes also depends_on containers

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [docker/compose#8359]
## Description of the issue
when I run `docker compose rm -f engine`, docker removes also other containers
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  database:
    environment:
      ...
    healthcheck:
      interval: 10s
      retries: 10
      test:
      - CMD
      - pg_isready
      - -q
      - -d
      - postgres
      - -U
      - root
      timeout: 45s
    image: postgres:13.2
    ports:
    - published: 5433
      target: 5432
    restart: always
    volumes:
    - ./database/database.sql:/docker-entrypoint-initdb.d/create_tables.sql:rw
    - ./database/data.sql:/docker-entrypoint-initdb.d/fill_tables.sql:rw
  engine:
    build:
      context: ./engine
    depends_on:
      database:
        condition: service_started
    environment:
      TZ: Europe/Rome
      config.location: /config
      ...
    ports:
    - published: 8080
      target: 8080
    restart: always
    volumes:
    - .:/engine-code:rw
    - ./engine/config-examples:/config:rw
  grafana:
    depends_on:
      database:
        condition: service_started
    image: grafana/grafana:latest
    ports:
    - published: 3001
      target: 3000
    volumes:
    - ./grafana:/etc/grafana/provisioning:rw
version: '3'
```

## Steps to reproduce the issue

1.  create 2 service, one that has `depends_on` to the other
2. remove the one that depends on the other

### Observed result
```
➜   docker compose rm -f engine
Going to remove codice_engine_1
[+] Running 2/0
 ⠿ Container codice_database_1  Removed  0.0s
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -------- why ?
 ⠿ Container codice_engine_1    Removed    0.0s
➜  docker container ls --all
CONTAINER ID   IMAGE          COMMAND                CREATED          STATUS                          PORTS     NAMES
47f8fed9eab8   bc8c9ea5532e   "/run.sh"              49 minutes ago   Exited (0) About a minute ago             codice_grafana_1
```

### Expected result
running `docker container ls --all` should still show the `database` instance, since in the documentation I see as consequences of `depends_on` the following:
 - docker-compose up starts services in dependency order. In the following example, db and redis are started before web.
 - docker-compose up SERVICE automatically includes SERVICE’s dependencies. In the example below, docker-compose up web also creates and starts db and redis.
 - docker-compose stop stops services in dependency order. In the following example, web is stopped before db and redis.

## Additional information

running on MacOS Big Sur 11.3.1 Intel
