### ISSUE TITLE
allow to inline simple dockerfiles

### ISSUE THREAD

**Issue by fnep** [docker/compose#8369]
I often have docker compose services where the Dockerfile is only very short. This is for example a container with python plus a few packages installed or a MySQL server with prepopulated data.

Example:
```
FROM mysql:5.7
COPY ./database_dump.sql /database_dump.sql
COPY ./prepare_db.sh /docker-entrypoint-initdb.d/prepare_db.sh
```
or
```
FROM python:3.8
RUN python3 -m pip install poetry
CMD python3
```

I would like to avoid having an own Dockerfile for these services to make it easier to maintain them and also easier to get an overview of what's going on in the docker-compose.yml file.

So I wrote a patch for docker-compose to extend the compose file syntax to allow this:
```
version: "3.8"
services:

  inline_dockerfile:
    build:
      context: ./
      dockerfile:
        - FROM python:3.8
        - RUN python3 -m pip install poetry
        - CMD python3
```

In many cases this would allow to get the complete definition into a single file.

Anyhow, before just making a pull request it's recommended to open an issue. Also, I could not find somebody else requesting this. My first version was to use the `: |` quote syntax to inline the file, but having a list of the lines allows to safely detect the new syntax situation. Eventually I concatenate the strings and give them into the build command as stdin. It's only a very little change in code.

I'm not sure how much this kind of change is appreciated or not. For me, it would make my life easier.
