### ISSUE TITLE
GCP logging not starting despite creating default credentials and setting env var

### ISSUE THREAD

**Issue by dlo** [docker/compose#8385]
## Description of the issue

I've created a Google Cloud Project and have run `gcloud auth application-default login` on my machine. After configuring the GCP logging service in my `compose.yaml`, running `docker-compose up` displays an error message and fails to start the container or the logging service.

## Context information (for bug reports)

**Output of `docker-compose version`**

```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:57:27 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:25 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

```yaml
services:
  homeassistant:
    container_name: homeassistant-docker-compose
    devices:
    - /dev/ttyAMA0:/dev/ttyAMA0
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/pi/raspberry-pi-3b-plus-317014-5f6d06816c92.json
    image: homeassistant/raspberrypi3-homeassistant:stable
    logging:
      driver: gcplogs
      options:
        gcp-project: raspberry-pi-3b-plus-317014
    network_mode: host
    restart: unless-stopped
    volumes:
    - /home/pi/.homeassistant:/config:rw
    - /etc/localtime:/etc/localtime:ro
version: '3.0'
```

## Steps to reproduce the issue

1. Download `gcloud` and run `gcloud auth application-default login`.
2. Add the following to a simple `compose.yaml` / `docker-compose.yaml`:

```yaml
    logging:
      driver: gcplogs
      # Below are optional.
      options:
        gcp-project: <YOUR_GCP_PROJECT_ID>
```

3. Run `docker-compose up -d`.

### Observed result

`docker-compose` exits with a nonzero error code and the container does not start.

### Expected result

`docker-compose` does not exit and the container starts.

### Stacktrace / full error message

```
ERROR: for homeassistant  Cannot start service homeassistant: failed to initialize logging driver: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information
```

## Additional information

```
$ uname -a
Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux
```

```
$ echo $GOOGLE_APPLICATION_CREDENTIALS
/home/pi/raspberry-pi-3b-plus-317014-5f6d06816c92.json
```

```
$ cat /etc/default/docker
# Docker Upstart and SysVinit configuration file

#
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/admin/systemd/
#

# Customize location of Docker binary (especially for development testing).
#DOCKERD="/usr/local/bin/dockerd"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export DOCKER_TMPDIR="/mnt/bigdrive/docker-tmp"

export GCP_KEY_PATH=/home/pi/raspberry-pi-3b-plus-317014-5f6d06816c92.json
export GOOGLE_APPLICATION_CREDENTIALS=/home/pi/raspberry-pi-3b-plus-317014-5f6d06816c92.json
```
