### ISSUE TITLE
--quiet option for build command it not working (WSL2 with COMPOSE_DOCKER_CLI_BUILD=1)

### ISSUE THREAD

**Issue by Elicetian** [docker/compose#8387]
## Description of the issue

docker-compose build --quiet still display the build output logs in stdout when COMPOSE_DOCKER_CLI_BUILD=1
but no log displayed as expected when COMPOSE_DOCKER_CLI_BUILD=0

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
networks:
  fast-network:
    driver: bridge
    name: test-network-80
services:
  mysql:
    build:
      context: /home/user/repos/mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      DATE_TIME: '2021-06-17 00:00:00'
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: dbpassword
      MYSQL_USER: dbuser
    hostname: mysql
    image: mydocker/mysql:dev
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.mysql.entryPoints: mysql
      traefik.tcp.routers.mysql.rule: HostSNI(`*`)
      traefik.tcp.services.db.loadbalancer.server.port: '3306'
    networks:
      fast-network:
        aliases:
        - mysql
    volumes:
    - data-mysql:/var/lib/mysql:rw
version: '3.8'
volumes:
  data-mysql: {}
```

## Steps to reproduce the issue

1. In WSL2 environment
2. export COMPOSE_DOCKER_CLI_BUILD=1
3. docker-compose build --quiet mysql

### Observed result
build logs are displayed:
[+] Building 0.2s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 38B                                                                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/mysql:5.5                                                                                                                                                                                           0.0s
 => [1/5] FROM docker.io/library/mysql:5.5                                                                                                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                                                                                                      0.0s
 => => transferring context: 83B                                                                                                                                                                                                                       0.0s
 => CACHED [2/5] ADD database.sql /docker-entrypoint-initdb.d/init.sql.template                                                                                                                                                                     0.0s
 => CACHED [3/5] RUN apt-get update ; apt-get install -y gettext-base                                                                                                                                                                                  0.0s
 => CACHED [4/5] COPY pre-docker-entrypoint.sh /usr/local/bin/pre-docker-entrypoint.sh                                                                                                                                                                 0.0s
 => CACHED [5/5] RUN chmod +x /usr/local/bin/pre-docker-entrypoint.sh                                                                                                                                                                                  0.0s
 => exporting to image                                                                                                                                                                                                                                 0.1s
 => => exporting layers                                                                                                                                                                                                                                0.0s
 => => writing image sha256:8d9adabe5b62432b51fbb1ed12e95e92ce62285cede2d730b20a0185d8d49e6c                                                                                                                                                           0.0s
 => => naming to docker.io/mydocker/mysql:dev

### Expected result
No display

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Windows 10 Pro / WSL2 / ubuntu 20.04 / Docker Desktop
