### ISSUE TITLE
docker-compose flag to create but not start container

### ISSUE THREAD

**Issue by Madpeterz** [docker/compose#8403]
**Is your feature request related to a problem? Please describe.**
I have a container that I do not want to start when I deploy the stack, but I do want it ready and linked for if it is needed.

**Describe the solution you'd like**
A flag like restart example "startup" with the following flags

always - this is the default and can be omitted
requested - the container will only start when directly called to start.

**Describe alternatives you've considered**
There is no workaround for this without issuing a second command (Unless I missed it in the doc) https://docs.docker.com/compose/compose-file/compose-file-v3/

**Example**
```
version: "4.0"

services:
  web:
    image: "nginx:alpine"
    networks:
      - new

  worker:
    image: "my-worker-image:latest"
    startup: requested
    networks:
      - legacy

  db:
    image: mysql
    networks:
      new:
        aliases:
          - database
      legacy:
        aliases:
          - mysql

networks:
  new:
  legacy:
```
