### ISSUE TITLE
Allowed combinations of profiles and commands should be clearer for user

### ISSUE THREAD

**Issue by otahontas** [docker/compose#8406]
**Is your feature request related to a problem? Please describe.**

After reading [compose docs](https://docs.docker.com/compose/profiles/) and checking how --profile flag is presented when running `docker-compose --help`, I think it's fairly reasonable for user to expect profiles to work with all kinds of commands. However, it seems like profile-flag is currently implemented only for couple of commands (up, config?). Yet, docker-compose allows user to add profile flag with non-working command without giving any errors.

Using following docker-compose as example:
```
services:
  wp1:
    image: wordpress
    profiles:
      - wp1
    depends_on:
      - db

  wp2:
    image: wordpress
    profiles:
      - wp2
    depends_on:
      - db

  db:
    image: postgres
```

When running `docker-compose --profile wp1 --profile wp2 up -d` and then `docker-compose --profile wp1 logs`, I'm seeing logs for all services. 

**Describe the solution you'd like**

It would be of course great to be able to use profiles in a way described above, but since it's not yet possible, it would be helpful to at least state status of allowed commands somewhere.
