### ISSUE TITLE
Error when starting executable on docker compose (not happening in Vanilla Docker)

### ISSUE THREAD

**Issue by dragonDScript** [docker/compose#8412]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.6, build 5db8d86f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:53 2021
  OS/Arch:          linux/amd64
  Experimental
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  backend:
    build:
      context: /mnt/sda1/Projects/book-backend
    environment:
      DB_URI: :27017
      HOST_URI: :5000
    ports:
    - published: 5000
      target: 5000
    volumes:
    - /mnt/sda1/Projects/book-backend:/src:rw
  mongo:
    image: mongo:latest
    ports:
    - published: 27017
      target: 27017
    restart: always
version: '3.9'
```

## Steps to reproduce the issue

1. Clone https://github.com/dragonDScript/book-backend.git
2. Run "docker build -t youruser/book .". Then run the image. See how it runs succesfully, with the messages "starting Book" and "serving to :5000"
3. Run docker-compose up. See error. 'OCI Runtime error [...] stat /src/book doesn't exist' (/src/book is the executable)

### Observed result
Docker compose doesn't find the executable. But docker does.
### Expected result
It runs the image and prints the text I put in both docker and docker compose.
### Stacktrace / full error message

```
Starting book-backend_backend_1 ... 
Starting book-backend_backend_1 ... error

ERROR: for book-backend_backend_1  Cannot start service backend: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/src/book": stat /src/book: no such file or directory: unknown

ERROR: for backend  Cannot start service backend: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/src/book": stat /src/book: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Ubuntu 20.04, docker compose from the website.
