### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by Subzero322** [docker/compose#8414]
## Description of the issue

Hi, I ran into a problem while using "docker-compose up". I made a bot for telegram according to the youtube guide. One of the videos needed to install docker and use it. Everything was going according to plan until the moment I ordered docker-compose up.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
(venv) C:\Users\Maxim\PycharmProjects\study\telegram-bot-lessons\lesson-4>docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
(venv) C:\Users\Maxim\PycharmProjects\study\telegram-bot-lessons\lesson-4>docker version
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevat
ed to connect. This error may also indicate that the docker daemon is not running.



```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(venv) C:\Users\Maxim\PycharmProjects\study\telegram-bot-lessons\lesson-4>docker-compose config
services:
  adminer:
    image: adminer
    network_mode: host
    ports:
    - published: 8080
      target: 8080
    restart: always
  db:
    environment:
      POSTGRES_PASSWORD: example
    image: postgres
    network_mode: host
    restart: always
version: '3.1'

```

## Steps to reproduce the issue

1.Im try regenerating certificates manually by:

docker-machine --debug regenerate-certs -f default

2. and I was check for any errors to fix, then I was try again:

docker-machine --debug env default

3.I was run this command to configure my shell:
@FOR /f "tokens=*" %i IN ('docker-machine --debug env default') DO @%i

### Observed result Successfully made call to close driver server
Making call to close connection to plugin binary

### Stacktrace / full error message
![error](https://user-images.githubusercontent.com/52161562/123782967-8889be80-d8de-11eb-86f4-c48d36100b47.PNG)

```

```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
