### ISSUE TITLE
With multiple docker-compose files, compose config does not show x-* attribs

### ISSUE THREAD

**Issue by pkos-2583** [docker/compose#8421]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  service-a:
    image: ubuntu:latest
    x-groups:
    - base
version: '3.7'
```

## Steps to reproduce the issue

1. Two docker-compose yml files:
docker-compose.yml:
```
version: "3.7"

services:
  service-a:
    image: ubuntu:latest
    x-groups: ["base"]
```
docker-compose-additional.yml:
```
version: "3.7"

services:
  service-a:
    image: ubuntu:latest
    x-categories: ["CAT1"]
```
2. The docker-compose config works good when executed for a single yml file.
docker-compose -f docker-compose.yml config
```
services:
  service-a:
    image: ubuntu:latest
    x-groups:
    - base
version: '3.7'
```

docker-compose -f docker-compose-additional.yml config
```
services:
  service-a:
    image: ubuntu:latest
    x-categories:
    - CAT1
version: '3.7'
```
3. The config for both yml files ignores the x-* attribs
docker-compose -f docker-compose.yml -f docker-compose-additional.yml config
```
services:
  service-a:
    image: ubuntu:latest
version: '3.7'
```

### Observed result

```
services:
  service-a:
    image: ubuntu:latest
version: '3.7'
```

### Expected result

```
services:
  service-a:
    image: ubuntu:latest
    x-categories:
    - CAT1
    x-groups:
    - base
version: '3.7'
```

## Additional information
uname -a
```
Linux pavel-nb 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Fix proposal - adding the following two lines to merge_service_dicts in compose/config/config.py seems to fix the issue:
```
    for field in [f for f in set(base.keys()).union(override.keys()) if f.startswith("x-")]:
        md.merge_scalar(field)
```
