### ISSUE TITLE
Environment variables not being consumed by docker-compose when v2 is enabled

### ISSUE THREAD

**Issue by ARMATAV** [docker/compose#8427]
Reproduction;

1. Create a new `.env` and some kind of `docker-compose.yml` file;

`.env`
```
HASURA_GRAPHQL_DEV_MODE=true
```

`docker-compose.yml`
```
version: "3.8"
services:
    database:
        image: postgres:12
        restart: on-failure
        ports:
            - 5432:5432
        volumes:
            - database-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
    hasura:
        image: hasura/graphql-engine:v2.0.1
        ports:
            - 3003:8080
        restart: always
        environment:
            HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE}
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@pinchy-database:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: false
            HASURA_GRAPHQL_ADMIN_SECRET: admin
volumes:
    database-volume:
```

2. `source .env && docker-compose up`

3. Observe failure to initialize due to missing environment variables.

Solution;

1. Do all reproduction steps except 3

2. `docker-compose disable-v2`

3. Do all reproduction steps except 3, and it works
