### ISSUE TITLE
docker-compose not using specific .dockerignore file

### ISSUE THREAD

**Issue by nickmccally** [docker/compose#8433]
## Description of the issue
Cannot get docker-compose to use separate .dockerignore file when specifying Dockerfile in docker-compose. This feature was introduced [supposedly since 1.25.0-rc3](https://stackoverflow.com/a/57774684/1529999) 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
# Use root/example as user/password credentials
version: '3.1'

services:
  vat-private:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vat-private
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./user.jwt:/app/user.jwt
    environment:
      - PORT=4000
      - DBHOST=vat-maria
      - CLIENT=vat
      - AUTH_SERVER_URL=http://localhost:8080/auth
      - REALM=whitelist
      - DB_PUBLIC_USER=public
      - DBUSER=root
      - DBPASSWORD=mypass
      - INCLUDE_TEST_DATA=0
      - ALLOWED_CORS=http://localhost:3000
      - RUNAS=private
      - ALLOWED_AUD=vat,ibfe
    logging:
      options:
        max-size: '1m'
    ports:
      - '4000:4000'
    command: npm run start:dev:docker
    user: root
    restart: always
    depends_on:
      - vat-maria
  vat-public:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vat-public
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./user.jwt:/app/user.jwt
    environment:
      - PORT=4500
      - DBHOST=vat-maria
      - CLIENT=vat
      - AUTH_SERVER_URL=http://localhost:8080/auth
      - REALM=whitelist
      - DBUSER=public
      - DBPASSWORD=mypass
      - INCLUDE_TEST_DATA=0
      - ALLOWED_CORS=http://localhost:3000
      - RUNAS=public
      - ALLOWED_AUD=vat,ibfe
    logging:
      options:
        max-size: '1m'
    ports:
      - '4500:4500'
    command: npm run start:dev:docker
    user: root
    restart: always
    depends_on:
      - vat-maria
  vat-maria:
    build:
      context: .
      dockerfile: Dockerfile.maria
      args:
        - DATA_FILE=./vat-prod-db.sql
    container_name: vat-maria
    command: mysqld --innodb-buffer-pool-size=256M
    restart: always
    logging:
      options:
        max-size: '1m'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=

```

## Steps to reproduce the issue

1. Add file `Dockerfile.dev.dockerignore` 
2. Run `COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build` which references Dockerfile.dev

### Observed result
Docker will still use the `.dockerignore`

### Expected result
Docker should use the `Docker.dev.dockerignore`

## Additional information
Other [user on stackoverflow](https://stackoverflow.com/questions/40904409/how-to-specify-different-dockerignore-files-for-different-builds-in-the-same-pr#comment105620731_57774684) have stated they experienced the same issue

OS version / distribution, `docker-compose` install method, etc.
