### ISSUE TITLE
Code changes not reflected in the docker container

### ISSUE THREAD

**Issue by NawafSwe** [docker/compose#8454]
## Description of the issue
I am using spring boot application, I have built the docker container first time went great. 
when I made changes to the code such changing responses, messages ect.. is weren't reflected on the running container even of rebuilding it, I have searched for this issue and I have applied all the solutions but did not worked for me. 
when I enter the container and see the source code it is updated but it is kinda not used. 

docker compose version: 3.8

docker yml file: 
``` yml 

version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: someApp
    volumes:
      - .:/app
      - .:/usr/app/src
    restart: always
    ports:
      - '6060:6060'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

```

and the docker file
``` DockerFile
#build packages
FROM maven:3.6.3-jdk-11-slim AS build
WORKDIR /app
COPY pom.xml  /app
COPY src /app/src
RUN --mount=type=cache,target=/root/.m2 mvn clean package  -Dmaven.test.skip

#build app
FROM openjdk:11
WORKDIR /app
COPY --from=build /app/target/.*jar  /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]


```

I have tried the following commands and did not worked for me: 
* docker-compose up --build -d
* docker-compose up
* docker-compose up --build -V -d
* docker-compose up --force-recreate -V -d
* docker-compose pull then docker-compose build then docker-compose up 

finally I have removed all images and containers and volumes and did not worked out for me unfortunately.
