### ISSUE TITLE
Support labels for configs and secrets

### ISSUE THREAD

**Issue by truong-hua** [docker/compose#8469]
**Is your feature request related to a problem? Please describe.**
Portainer currently depend on object labels to control user access permission, all volume, container, service, network now work well with labels defined in docker-compose.yml file but it's not supported for secrets and configs.

**Describe the solution you'd like**
Support configs/secrets labels option.
```
configs:
  nginx_config:
    file: ./source_code/nginx/conf.d/default.conf
    labels:
      label.name: label.value
```

**Describe alternatives you've considered**
Currently, we have to create secrets externally by cli which supports label parameter.
