### ISSUE TITLE
Docker-Compose with Contexts - Problems with bind mounts

### ISSUE THREAD

**Issue by wfjclyons** [docker/compose#8484]
## Description of the issue
Bind mounts don't work as you would expect with remote contexts. Have a remote SSH docker context and the docker-compose file has a service 'devbox' with the following config:

```
    build:
          context: ./
    [....]
    volumes:
      - ./:/app #mount app code inside
```
This will only work if the exact same directory path referred to by ./ (the build context) exists on the server as on the client. If this directory is mounted and no such path exists on the host's filesystem, the directory is empty inside the devbox service container. So I can either create a directory on the remote server and symlink it to where the files REALLY are synced, or I can change the build context locally and create a directory (because docker-compose checks if the build context exists locally before proceeding) at the same path in order to "trick" docker-compose.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**

Client: 

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.39
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           dev-vm
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Server: 

```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  my_service:
    build:
      args:
        XDEBUG_REMOTE_HOST: host.docker.internal
        XDEBUG_REMOTE_PORT: '8587'
      context: /local/directory/path
      dockerfile: ./docker/Dockerfile
      target: dev
    dns_search:
    - something.com
    volumes:
    - /local/directory/path:/app:rw
    working_dir: /app
```

## Steps to reproduce the issue

1. Add a remote context to Docker
2. Use docker-compose to spin up a service in the remote context with a bind mounted local directory
3. Execute shell inside remote docker-compose service container and see the "ls" returns an empty directory, because the current path on localhost doesn't exist at the same path on the server (if you are syncing, it probably exists at a different path, which is not mounted correctly into the container)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
