### ISSUE TITLE
compose doesnt respoect ignore file

### ISSUE THREAD

**Issue by nbraun-wolf** [docker/compose#8485]
Running the below command

```bash
ocker-compose -f docker-compose.yml -f docker-compose.app.yml up --build 
```

with the below in `docker-compose.yml` 

```yaml
version: '3.9'
services:
  app:
    image:  foobarbaz:nightly
    build:
      context: ./
      args:
        - PIP_EXTRA_URL
    volumes:
      - .:/opt/app
    depends_on:
      - db
      - mail
    ports:
      - 8080:8080
    env_file: local.env
```

Doesnt respect the .dockerignore file in the same folder.

```
k8s
azure-pipeline-*
Makefile
Dockerfile
docker-compose*
renovate.json
README.md
.git
.github
.gitignore
.pip
.pre-commit-config.yaml
.editorconfig
.flake8
.pyproject.toml
.run-uwsgi.sh
mock-server
```

None of the files are ignore. I cant imagine that on every single one there is an issue with `/` or whatever. All of them are ignored when I build it with docker. I have also tried with `context: .` but its the same.

The issues regarding this I read boil down to someone telling OP they are doing it wrong. I don't think I am doing it wrong. This is a bug in compose and should have been fixed long time ago as it seems.

- https://github.com/docker/compose/issues/1607
- https://stackoverflow.com/questions/53945934/docker-compose-and-dockerignore
- https://github.com/docker/compose/issues/2098
- https://github.com/docker/compose/issues/8433
- https://github.com/docker/compose/issues/6024
-
