### ISSUE TITLE
Could not resolve host in docker compose service

### ISSUE THREAD

**Issue by JTeeuwissen** [docker/compose#8488]
## Description of the issue
If I try to reach https://login.microsoftonline.com/ (for authentication purposes) from an service started using docker compose I get a cannot resolve hostname error. Running the image directly (without compose) does not cause the same problem.
adding `dns : 8.8.8.8` fixes the problem, but I think it should not be required. I think the problem is with the internal docker dns system, if this repo is not the right place, please move it or tell me.
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  my-service:
    command: tail -F anything
    image: ubuntu:latest
version: '3.8'
```

## Steps to reproduce the issue

1. Create a `docker-compose.yml` with
```
version: '3.8'

services:
  my-service:
    image: ubuntu:latest
    command: tail -F anything
```
2. Start the compose with `docker-compose -f "docker-compose.yml" up -d --build`
3. Enter the container and install curl
4. curl `https://login.microsoftonline.com/`

### Observed result
```
curl: (6) Could not resolve host: login.microsoftonline.com
```
### Expected result
```
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://www.office.com/login#">here</a>.</h2>
</body></html>
```
### Stacktrace / full error message

```
 curl https://login.microsoftonline.com/ -vv
* Could not resolve host: login.microsoftonline.com
* Closing connection 0
```

## Additional information
Reinstalled docker to no avail.
Other sites can be reached.
Can reach site from desktop/wsl2

**Comment by JTeeuwissen** [comment]
running
```yaml
version: '3.8'

services:
  my-service:
    image: ubuntu:latest
    command:
      [
        '/bin/bash',
        '-c',
        'apt update && apt install curl -y && curl https://login.microsoftonline.com/',
      ]
```
directly with compose results in the same error.
