### ISSUE TITLE
3.9 and 3.8 are unstable - deploy spec is not valid in docs

### ISSUE THREAD

**Issue by chrisdlangton** [docker/compose#8490]
docker-compose version 1.29.2, build 5becea4c
Docker version 20.10.7, build f0df350
Linux pop-os 5.11.0-7620-generic #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux

```yaml
version: '3.9'
services:
  redis:
    image: docker.io/library/redis:5.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M
```

produced

```
WARNING: The following deploy sub-keys are not supported and have been ignored: restart_policy.delay, restart_policy.window, resources.reservations.cpus
```

Tried to set the version from `3.9` (which is [the version in docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources)) to `3.8` to match [the latest in the docs](https://docs.docker.com/compose/compose-file/compose-file-v3/) just in case the docs examples are prepared for an unreleassed version..

No change, same result

these docs, the cli output, i.e. the brittle experience of documented expectations and reality makes it impossible to know what the next troubleshooting step should be
