### ISSUE TITLE
Docker-Compose is mangling the permissions on the remote NFS server it's trying to mount

### ISSUE THREAD

**Issue by MikePadge** [docker/compose#8493]
## Description of the issue
Leaving a reference to https://github.com/docker/compose/issues/3715 because it's related to the madness that has unfolded in that thread VS the initial report. 

Here is a the stack overflow I dumped, but will be copy/pasta'ing most of the data below. 
https://stackoverflow.com/questions/68927595/docker-compose-nfs-remote-mount-is-mangling-permissions-on-zfs-nfs-server-share

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.0
build 07737305 docker-py version: 5.0.0
```

**Output of `docker version`**
```
Docker=Docker Engine - Community
Version: 20.10.8
```

Compose Config
```
version: "3.8"
services:
  vaultwarden:
    image: vaultwarden/server
    restart: unless-stopped
    user: "{{ docker_user.id }}:3000" #(3000 is the docker gid)
    volumes:
      - vaulty:/data
    depends_on:
      - db
    dns: 1.1.1.1
    labels:
      - traefik.enable=true

      - traefik.http.routers.vaultwarden-ui.rule=Host(`<domain>`) || Host(`<domain>`)
      - traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui
      - traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden-ui.tls.certresolver=le

      - traefik.http.routers.vaultwarden-websocket.rule=(Host(`<domain>`) || Host(`<domain>`) )&& Path(`/notifications/hub`)
      - traefik.http.routers.vaultwarden-websocket.service=vaultwarden-websocket
      - traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012
      - traefik.http.routers.vaultwarden-websocket.tls.certresolver=le

      - traefik.http.middlewares.vaultwarden-ratelimit.ratelimit.average=5
      - traefik.http.middlewares.vaultwarden-ratelimit.ratelimit.burst=1000
      - traefik.http.middlewares.vaultwarden-compress.compress=true

      - traefik.http.routers.vaultwarden-ui.middlewares=vaultwarden-ratelimit,vaultwarden-compress
      - traefik.http.routers.vaultwarden-websocket.middlewares=vaultwarden-ratelimit,vaultwarden-compress
    environment:
      - SIGNUPS_ALLOWED=false
      - DOMAIN=<domain>
      - SHOW_PASSWORD_HINT=false
      - DATABASE_URL=postgres://vaultwarden:{{ vaultwarden_database_password }}@db/vaultwarden
      - INVITATIONS_ALLOWED=false
      - ROCKET_WORKERS={{ ansible_processor_nproc // 2 }}
      - WEBSOCKET_ENABLED=true

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - vault-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD={{ vaultwarden_database_password }}
      - POSTGRES_USER=vaultwarden
volumes:
  vaulty:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.8.0.10,rw
      device: :/mnt/motherbrain/app-data/vaultwarden
  vault-db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.8.0.10,rw
      device: :/mnt/motherbrain/DBees/postgres/vaultwarden
```

## Steps to reproduce the issue
NFS Server is brand new ZFS Truenas setup
DockerHost=Debian10

We have two remote shares that are owned by the root user, but the docker group is allowed full read/write access to them, so we end up with root:docker 774 permissions.

The docker user is an arbitrary user named dockerdu uid 3000 (the docker group is gid 3000 and dockerdu is a member of the docker group).

I run `docker-compose up -d` as the dockerdu user.
The vaultwarden server is stuck in a reboot loop. It claims the password for the postgres container is bad

### Observed result
```
docker logs --tail 50 --follow --timestamps 8096acf65d09
2021-08-25T17:26:07.641924997Z [2021-08-25 17:26:07.641][vaultwarden::util][WARN] Can't connect to database, retrying: DieselCon.
2021-08-25T17:26:07.642061919Z [CAUSE] BadConnection(
2021-08-25T17:26:07.642094711Z     "FATAL:  password authentication failed for user \"vaultwarden\"\n",
```

Except what has actually happened here, if I go back to my NFS server and check the permissions (specifically only on the postgres share that is attempting to be mounted). Why not the vaultwarden UI permissions that are making a similar mount?

`drwx------  19 70      docker  26 Aug 25 14:54 vaultwarden`

The root user has been kicked, and replaced with uid 70? and the group permissions have been wiped. 

### Expected result
As far as I can tell, this is the correct way to mount nfs shares. IF I manually change the permissions back while the containers are running, I get passed the password error, but then fall into another permissions issue.

Notes:
I'm using Jeff Geerling's ansible repo to install docker and docker-compose on a brand new Deb10 setup that just has a basic user and ssh key added to it.
