### ISSUE TITLE
Heartbeat check parameters cannot be read

### ISSUE THREAD

**Issue by Saseke** [docker/compose#8496]
I want to get a health check through the health check script.I don't pass in arguments, so it's ok to write dead in the script.When I specify this as an argument, the container is running in an unhealthy state
**docker-compose.yml**
```
version: '3'
services:
  nginx:
    image: nginx
    container_name: app_nginx
    restart: always
    volumes:
      - /Users/yoke/code/iot-platform/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck.sh
      - /Users/yoke/tools/jq:/usr/bin/jq
    healthcheck:
      test: [ "CMD","docker-healthcheck","-h", "localhost","-p","8008" ]
      interval: 30s
      timeout: 60s
      retries: 3

    ports:
      - 80:80
```
docker-healthcheck.sh
```
#!/bin/bash
set -eo pipefail
host=localhost
port=8080
while getopts h:p: option
do
    case "$option" in
        h)
          host=$OPTARG;;
        p)
          port=$OPTARG;;
        \?)
            echo "Usage: args [-h] [-p]"
            echo "-h means host ip address"
            echo "-p means port"
            exit 1;;
    esac
done
RESULT=$(curl -k -s http://"$host":"$port"/actuator/health)
a="\"UP\""
status=$(echo ${RESULT} | jq  '.status')
if [ $a == $status ];then
  echo $a == $status
  exit 0
fi
echo $a
exit 1
```
