### ISSUE TITLE
Volume not mounting on MacOS for project under /usr/local/docs; 

### ISSUE THREAD

**Issue by paxperscientiam** [docker/compose#8497]
## Description of the issue
Files do not mount.

I'm having trouble nailing it down, but it *may* have something to do with file permissions on the host machine. For a minimal project (see example below), there is a failure to mount the files when the project is located under /usr/local/docs.

## Context information (for bug reports)

Minimal docker-compose.yml
```yaml
version: '3.8'
services:
  php-apache-environment2:
    container_name: php-apache2
    image: php:7.2-apache
    volumes:
      - ./public:/var/www/html/
    ports:
      - 8002:80
```

Project structure (./ is project root):
./public/
└── index.html

Per subject, this fails when the project directory is under /usr/local/docs; however, it works just fine when the project directory is under $HOME.

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`** (under /usr/local/docs)
(Make sure to add the relevant `-f` and other flags)
```
services:
  php-apache-environment2:
    container_name: php-apache2
    image: php:7.2-apache
    ports:
    - published: 8002
      target: 80
    volumes:
    - /usr/local/docs/svelte/moz-todo-svelte/public:/var/www/html:rw
version: '3.8'
```

**Output of `docker-compose config`** (under ~)
(Make sure to add the relevant `-f` and other flags)
```
services:
  php-apache-environment2:
    container_name: php-apache2
    image: php:7.2-apache
    ports:
    - published: 8002
      target: 80
    volumes:
    - /Users/ramos/svelte/moz-todo-svelte/public:/var/www/html:rw
version: '3.8'

```

## Steps to reproduce the issue

1. Make a minimal project based on the above docker-compose.yml and add ./public/index.html to it
2. Try running from home.
3. Try running from /usr/local/docs

### Observed result
Fails to mount files

### Expected result
Succeeds to mount files

### Stacktrace / full error message
There is no error message. This appears to be a silent error.

## Additional information

* macOS 11.5.2 (intel)
* docker-compose came with Docker Desktop

I'm down for testing things out, and providing more info.

**EDIT 2021/09/02**
It's working. So, from what I can tell, the mount failure was caused by the fact that /usr/local/docs wasn't whitelisted in Docker app's Resources//File Sharing. That said, it is still problematic that docker-compose gives no warning indicating as such.

With that said, this wasn't the end of it: there was now the problem of host file changes not syncing to container filesystem. Long story short, a helpful IRC user on #docker suggested disabling the grpc thing (see encircled option in screenshot).

![Screen Shot 2021-09-02 at 9 04 57 PM](https://user-images.githubusercontent.com/7539871/131935159-b900b66a-ec18-4505-b5f5-c93a729133ca.png)
