### ISSUE TITLE
Empty Ports Override Throwing an Error

### ISSUE THREAD

**Issue by MicahLyle** [docker/compose#8521]
**Description**

```
services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: app_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app
    ports:
      - "8016:8000"

    command: /start

    ...

  celerybeat:
    <<: *django
    image: app_local_celerybeat
    container_name: celerybeat
    depends_on:
      - postgres
      - redis
      - mailhog
    ports: []
    command: /start-celerybeat
```

**Steps to reproduce the issue:**
1. Have a `docker-compose.yml` or similar like the above, where you have some service definition utilizing `<<: *other_service_definition`.
2. Set `ports` on the child definition to `[]` (to override the parent)
3. Try `docker-compose up` or `docker-compose down`, etc.
4. You'll see this error: `services.celerybeat.ports must be a list`

**Output of `docker-compose --version`: ***
```
Docker Compose version 2.0.0-beta.4
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
desktop-linux
```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 43
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.804GiB
 Name: docker-desktop
 ID: 4F6P:YVVP:4B55:X4PU:BRCW:JE3X:ZY4U:R3RU:HSZO:E5Z3:E5UJ:KKOS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Local development environment using the latest Docker Desktop on Windows 10 with WSL2.
