### ISSUE TITLE
Compose v2 fails with devices: "/dev/fuse", requires devices: "/dev/fuse:/dev/fuse"

### ISSUE THREAD

**Issue by jamshid** [docker/compose#8535]
**Description**

Slight incompatibility with devices in `docker compose` vs `docker-compose`.

**Steps to reproduce the issue:**
1. I have a service where I can run fuse in the container, so `rclone mount` works.
```
...
  client:
    restart: "${PROJECT_RESTART-no}"
    image: "${REGISTRY_URL}client:${CLIENT_IMAGE_TAG}"
    init: true
    deploy:
      resources:
        limits:
          memory: ${CLIENT_CONTAINER_MEM_LIMIT-2g}
    # Needed for mounting fuse filesystem (https://github.com/docker/docker/issues/16233)
    cap_add:
      - SYS_ADMIN
      - MKNOD
    devices:
      - "/dev/fuse"
    security_opt:
      - apparmor:unconfined
      # for strace, https://github.com/docker/docker/issues/7276#issuecomment-194137403
      - "seccomp:unconfined"
```
2. But fuse fails with `docker compose`, `rclone mount` reports `fuse: device not found, try 'modprobe fuse' first`. It has worked for years with `docker-compose`.
3. Change yml to this and it works.
```
    devices:
      - "/dev/fuse:/dev/fuse"
```

**Describe the results you received:**
above

**Describe the results you expected:**
above

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
 Version:           20.10.7

% docker compose version
Docker Compose version 2.0.0-beta.3
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
latest docker for mac 3.4.0
