### ISSUE TITLE
`entrypoint` is being merged

### ISSUE THREAD

**Issue by DaleyKD** [docker/compose#8536]
**Description**
In Visual Studio 2019, the following command is used when starting up a Docker Container project (.dcproj):
``` ps
docker-compose  -f "C:\src\docker-compose-myproject.yml" -f "C:\src\docker-compose-myproject.override.yml" -f "C:\src\obj\Docker\docker-compose.vs.debug.g.yml" -f "C:\src\docker-compose.vs.debug.yml" -p dockercomposemyproject5397392790596996865 --no-ansi up -d --no-build --force-recreate --remove-orphans
```

It's expected that the very last .yml file will contain values that override.

**Steps to reproduce the issue:**
1. Multiple docker compose .yml files
2. For the same service, have different entrypoints in each yml
3. Run `docker compose` and list each file.

**Describe the results you received:**
An appended/merged list of entrypoint commands.

**Describe the results you expected:**
In version 1, the last `entrypoint` was the one used.  This is how Visual Studio works, and if we don't mimic it, you'll hurt a lot of developers.

**Additional information you deem important (e.g. issue happens only occasionally):**
**VERSION 1**
Output from `docker-compose  -f "C:\src\docker-compose-myproject.yml" -f "C:\src\docker-compose-myproject.override.yml" -f "C:\src\obj\Docker\docker-compose.vs.debug.g.yml" -f "C:\src\docker-compose.vs.debug.yml" -p dockercomposemyproject5397392790596996865 config`:
```
networks:
  default:
    ipam:
      config:
      - subnet: 172.22.0.0/16
      driver: default
    name: myprojectlocal
services:
  myproject:
    build:
      context: C:\src
      dockerfile: MyProject/MyProject/Dockerfile
      labels:
        com.microsoft.created-by: visual-studio
        com.microsoft.visual-studio.project-name: MyProject
      target: base
    container_name: MyProject
    entrypoint: sh -c 'update-ca-certificates && tail -f /dev/null'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true"
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_FALLBACK_PACKAGES: ''
      TZ: America/Chicago
    image: myproject:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages  "/app/bin/Debug/net5.0/MyProject.dll"'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/sh -c "if PID=$$(pidof
        dotnet); then kill $$PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    ports:
    - published: 54040
      target: 80
    tty: true
    volumes:
    - C:\src\MyProject\MyProject:/app:rw
    - C:\Users\kdaley\vsdbg\vs2017u5:/remote_debugger:rw
    - C:\Users\kdaley\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
    - user_cert_store:/root/.dotnet/corefx/cryptography/x509stores/my:rw
    - C:\Users\kdaley\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
    - C:\Users\kdaley\.nuget\packages:/root/.nuget/packages:ro
    - C:\src:/src:rw
    - C:\src\nginx\certs\MyProject.local.crt:/usr/local/share/ca-certificates/MyProject.local.crt:ro
version: '3.5'
volumes:
  user_cert_store: {}
```

**VERSION 2**
Output from `docker-compose  -f "C:\src\docker-compose-myproject.yml" -f "C:\src\docker-compose-myproject.override.yml" -f "C:\src\obj\Docker\docker-compose.vs.debug.g.yml" -f "C:\src\docker-compose.vs.debug.yml" -p dockercomposemyproject5397392790596996865 config`:
```
services:
  myproject:
    build:
      context: C:\src
      dockerfile: C:\src\MyProject\MyProject\Dockerfile
      labels:
        com.microsoft.created-by: visual-studio
        com.microsoft.visual-studio.project-name: MyProject
      target: base
    container_name: MyProject
    entrypoint:
    - /bin/sh
    - -c
    - update-ca-certificates && dotnet MyProject.dll
    - tail
    - -f
    - /dev/null
    - sh
    - -c
    - update-ca-certificates && tail -f /dev/null
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true"
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      NUGET_FALLBACK_PACKAGES: ""
      TZ: America/Chicago
    image: myproject:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages  "/app/bin/Debug/net5.0/MyProject.dll"'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/sh -c "if PID=$(pidof
        dotnet); then kill $PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: 54040
      protocol: tcp
    tty: true
    volumes:
    - type: bind
      source: C:\Users\kdaley/.nuget/packages
      target: /root/.nuget/packages
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\kdaley\AppData\Roaming/ASP.NET/Https
      target: /root/.aspnet/https
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\kdaley\AppData\Roaming/Microsoft/UserSecrets
      target: /root/.microsoft/usersecrets
      read_only: true
      bind:
        create_host_path: true
    - type: volume
      source: user_cert_store
      target: /root/.dotnet/corefx/cryptography/x509stores/my
      volume: {}
    - type: bind
      source: C:\src\nginx\certs\MyProject.local.crt
      target: /usr/local/share/ca-certificates/MyProject.local.crt
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: C:\src\MyProject\MyProject
      target: /app
      bind:
        create_host_path: true
    - type: bind
      source: C:\src
      target: /src
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\kdaley\vsdbg\vs2017u5
      target: /remote_debugger
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\kdaley\.nuget\packages\
      target: /root/.nuget/packages
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\kdaley\AppData\Roaming/ASP.NET/Https
      target: /root/.aspnet/https
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: C:\Users\kdaley\AppData\Roaming/Microsoft/UserSecrets
      target: /root/.microsoft/usersecrets
      read_only: true
      bind:
        create_host_path: true
networks:
  default:
    name: myprojectlocal
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/16
volumes:
  user_cert_store:
    name: dockercomposemyproject5397392790596996865_user_cert_store
x-environment-config:
  ASPNETCORE_ENVIRONMENT: Development
x-volumes:
- C:\Users\kdaley/.nuget/packages:/root/.nuget/packages:ro
- C:\Users\kdaley\AppData\Roaming/ASP.NET/Https:/root/.aspnet/https:ro
- C:\Users\kdaley\AppData\Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
- user_cert_store:/root/.dotnet/corefx/cryptography/x509stores/my
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 45
  Running: 43
  Paused: 0
  Stopped: 2
 Images: 62
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 7
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: 2ZYI:CWSV:XY2P:AEI5:EIPN:UPIA:G66M:6O7F:BWLD:VBNX:B3OD:YL7Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
local
