### ISSUE TITLE
Links not fully populated in docker-compose v2.0.0-rc1

### ISSUE THREAD

**Issue by sdt** [docker/compose#8553]
**Description**

With docker-compose v1 the services listed in the `links` section are available in the container by inspecting `.NetworkSettings.Networks.$NETWORK.Links`. In docker-compose v2 these are only partially populated.

**Steps to reproduce the issue:**

This docker-compose file can be used to illustrate the issue:
```yaml
version: "3.9"

services:
  serviceA:
    image: alpine
    command: sleep infinity

  serviceB:
    image: alpine
    command: sleep infinity

  clientA:
    image: alpine
    command: sleep infinity
    links:
      - serviceA
      - serviceB

  clientB:
    image: alpine
    command: sleep infinity
    links: # note these are in the opposite order to clientA
      - serviceB
      - serviceA
```

**Describe the results you expected:**

With docker-compose 1.28.5, if I run `docker-compose up` and then run:

`docker inspect --format='{{range .NetworkSettings.Networks}}{{json .Links}}{{end}}' demo_clientA_1 | jq .`

I get:
```json
[
  "demo_serviceA_1:demo_serviceA_1",
  "demo_serviceA_1:serviceA",
  "demo_serviceA_1:serviceA_1",
  "demo_serviceB_1:demo_serviceB_1",
  "demo_serviceB_1:serviceB",
  "demo_serviceB_1:serviceB_1"
]
```

Inspecting `clientB` in the same manner gives exactly the same results.

**Describe the results you received:**

With docker-compose v2.0.0-rc1, if I run the same docker-compose stack, I get this for `clientA`:

```json
[
  "demo_serviceA_1:demo_serviceA_1",
  "demo_serviceA_1:serviceA_1"
]
```

And for `clientB`:

```json
[
  "demo_serviceB_1:demo_serviceB_1",
  "demo_serviceB_1:serviceB_1"
]
```

Note that I only seem to get the first item listed in the `links` array, and the base `$container_name:$service_name` mapping is also missing.

**Output of `docker-compose --version`:**

docker-compose version 1.28.5, build c4eb3a1f
Docker Compose version v2.0.0-rc.1

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
