### ISSUE TITLE
Convert to json does not print extensions

### ISSUE THREAD

**Issue by dudicoco** [docker/compose#8556]
**Description**

`docker compose convert --format json` does not print custom extension fields.

Example file:
```yaml
version: '3.9'

services:
  app:
    image: test:latest
    build: .
    x-custom: test
```

Output:
```json
{
  "services": {
    "app": {
      "build": {
        "context": "./",
        "dockerfile": "./Dockerfile"
      },
      "image": "test:latest",
      "networks": {
        "default": null
      }
    }
  },
  "networks": {
    "default": {
      "name": "app_default",
      "ipam": {},
      "external": false
    }
  }
}
```

Note that the `x-custom` field is missing from the output.

Using yaml output with `docker compose convert --format yaml` does work as expected:
```yaml
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: test:latest
    networks:
      default: null
    x-custom: test
networks:
  default:
    name: app_default
```

**Output of `docker-compose --version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
