### ISSUE TITLE
`docker-compose up` -> `panic: runtime error: index out of range [0] with length 0` in `getCanonicalContainerName`

### ISSUE THREAD

**Issue by MadLittleMods** [docker/compose#8566]
## Description of the issue

Starting containers with `docker-compose up -d --no-recreate` throws error: `panic: runtime error: index out of range [0] with length 0`.

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```sh
$ docker-compose version
Docker Compose version v2.0.0-rc.2
```

**Output of `docker version`**
```sh
$ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

Reproducible with this barebones config but full `docker-compose.yml` is available at https://gitlab.com/gitterHQ/webapp/-/blob/e2da984a733a4fba81c2d9f85494f822fcc1ff6a/docker-compose.yml
```yml
$ docker-compose config
services:
  mongo-express:
    image: mongo-express
    links:
    - mongo1:mongo
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8081
      published: 8081
      protocol: tcp
  mongo1:
    image: registry.gitlab.com/gitterhq/webapp/mongo:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 27017
      published: 27017
      protocol: tcp
    restart: always
    volumes:
    - type: volume
      source: gitter-mongodb
      target: /data/db2
      volume: {}
networks:
  default:
    name: webapp_default
volumes:
  gitter-mongodb:
    name: webapp_gitter-mongodb
```

## Steps to reproduce the issue

1. Put the Docker compose config in place (see above)
2. `docker-compose up -d --no-recreate`
3. Notice the error

### Observed result

Error occurs and containers not created

### Expected result

Docker containers created without errors

### Stacktrace / full error message

```sh
$ docker-compose up -d --no-recreate
WARN[0000] Found orphan containers ([synapse webapp_elasticsearch_1 riot webapp_redis1_1 webapp_neo4j_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
panic: runtime error: index out of range [0] with length 0

goroutine 66 [running]:
github.com/docker/compose-cli/pkg/compose.getCanonicalContainerName(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/docker/compose-cli/pkg/compose/compose.go:54 +0x14c
github.com/docker/compose-cli/pkg/compose.(*convergence).updateProject(0xc000550198, 0xc0004d72c0, 0xc000423940, 0x6)
	github.com/docker/compose-cli/pkg/compose/convergence.go:147 +0x5f8
github.com/docker/compose-cli/pkg/compose.(*convergence).apply.func1(0x2120e88, 0xc00025b260, 0xc000423940, 0x6, 0x0, 0x0)
	github.com/docker/compose-cli/pkg/compose/convergence.go:104 +0x292
github.com/docker/compose-cli/pkg/compose.run.func1(0x0, 0xc00011fac0)
	github.com/docker/compose-cli/pkg/compose/dependencies.go:102 +0xa3
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000f8780, 0xc00068c720)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

Relevant Docker code: [`github.com/docker/compose-cli/pkg/compose/compose.go#L54`](https://github.com/docker/compose-cli/blob/8fefd8b3f0534682bc56fabbf551cf1c95b925eb/pkg/compose/compose.go#L54) -> `getCanonicalContainerName`. In future Docker versions, this same file/function was moved to [`github.com/docker/compose/pkg/compose/compose.go#L47-L55`](https://github.com/docker/compose/blob/ef461a3a26c67f16d1bebd9a184783ff9627bcd0/pkg/compose/compose.go#L47-L55) (via https://github.com/docker/compose-cli/pull/2055).

## Additional information

OS version / distribution, `docker-compose` install method, etc.

 - macOS 11.1
 - Docker Desktop Version 4.0.0 (4.0.0.12)

---

Discovered while working on https://gitlab.com/gitterHQ/webapp/-/merge_requests/2229#note_668163453
