### ISSUE TITLE
GPU enabling with docker compose

### ISSUE THREAD

**Issue by leigh-plt** [docker/compose#8569]
Its strange behavior. Looks like a docker bug.
From [docs.docker.com](https://docs.docker.com/compose/gpu-support/) I got:
But GPU don't work.

```
version: '3.9'
services:
  test:
    image: nvidia/cuda:10.2-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
```

Just rearranged the lines and all work

```
runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
```

Docker Engine v20.10.8
WSL v2 
Composer V2.0.0-rc2
Docker desktop Version 4.0.0 (67817)

Or docs miss "-" ? Please check docs.
```
          devices:
            - capabilities: [gpu]
            - driver: nvidia
```
