### ISSUE TITLE
run --no-deps hangs when using service_healthy

### ISSUE THREAD

**Issue by aviau** [docker/compose#8577]
If no containers are already running, and `service_healthy` is used, `run --no-deps` will just hang.

In the python version, it would start the required container.

Example:
```yaml
version: "3.9"

services:

  container1:
    image: alpine
    command: tail -f /dev/null
    healthcheck:
      test: sh -c 'exit 0'
      interval: 5s
      timeout: 10s
      retries: 3

  container2:
    image: alpine
    depends_on:
      container1:
        condition: service_healthy
```

This command will hang:
```bash
docker compose --file=test.compose.yaml run --no-deps container2 echo test
```

In the python version, it would start:
```
docker-compose --file=test.compose.yaml run --no-deps container2 echo test
```
