### ISSUE TITLE
Possible issue with nvidia driver capabilities (utility permission)

### ISSUE THREAD

**Issue by cmielke-vir** [docker/compose#8583]
## Description of the issue
I had considerable trouble getting tensorflow or jax to see an nvidia gpu inside a container. I traced the problem back to the "utility" capability that is set in the compose file.

## Context information (for bug reports)

- [x] On an 8-gpu lambda server
- [x] Cuda 11.4

**Output of `docker(-)compose version`**
```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker version`**
```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~20.04.1
  Built:            Wed Aug  4 19:07:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:
 runc:
  Version:          1.0.0~rc95-0ubuntu1~20.04.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3.0'
services:
  thisOneWorks:
    image: tensorflow/tensorflow:latest-gpu
    command: python3 -c "import tensorflow as tf; print(tf.test.is_built_with_cuda(), tf.test.is_gpu_available())"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  thisOneDoesNot:
    image: tensorflow/tensorflow:latest-gpu
    command: python3 -c "import tensorflow as tf; print(tf.test.is_built_with_cuda(), tf.test.is_gpu_available())"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]

```

## Steps to reproduce the issue

1. The working and non-working services are above.
2. The output of the working service is (True, True), non-working is (True, False)
3. In the non-working service, running nvidia-smi shows either "Err" or "N/A" for the CUDA version, depending on which image is used.

### Observed result
With the utility permission provided, tensorflow won't use the GPU, and nvidia-smi output is wrong
With the utility permission removed, tensorflow works with the GPU. Strangely, nvidia-smi still works just fine!

### Expected result
utility permission shouldn't quietly break things

### Stacktrace / full error message

```
No stack trace
```

## Additional information

Ubuntu 20:04, `docker-compose` installed today via curl as specified here : https://docs.docker.com/compose/install/
