### ISSUE TITLE
V2 - TCP and UDP Ports Parsed Incorrectly w/ `docker-compose.override.yml`

### ISSUE THREAD

**Issue by sgtoj** [docker/compose#8586]
## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.2
```

**Output of `docker version`**
```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker-compose config`**

```
services:
  test:
    image: nginx
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: 8080
      protocol: tcp
networks:
  default:
    name: demo_default
```

## Steps to reproduce the issue

1. create simple `docker-compose.yml` w/ a `test` service exposing udp **and** tcp for the same port
    ```yml
    version: "3.8"
    services:
      test:
        image: nginx
        ports:
          - "8080:8080/udp"
          - "8080:8080/tcp"
   ```

2. create simple `docker-compose.override.yml` w/ `test` entry (overriding a configuration of the service does not matter)  
    ```yml
    version: "3.8"
    services:
      test: {}
   ```

3. print the config and notice only one `ports` entry
    ```shell
    > docker compose config
    services:
      test:
        image: nginx
        networks:
          default: null
        ports:  # <----------  missing udp entry
        - mode: ingress
          target: 8080
          published: 8080
          protocol: tcp
    networks:
      default:
        name: demo_default
    ```

4. modify the `docker-compose.override.yml` by removing the `test` service entry
    ```yml
    version: "3.8"
    services: {}
   ```

5. print the config and notice it works as intended
    ```shell
    > docker compose config
    services:
      test:
        image: nginx
        networks:
          default: null
        ports:  # <----------  working as intended!
          - mode: ingress
            target: 8080
            published: 8080
            protocol: udp
          - mode: ingress
            target: 8080
            published: 8080
            protocol: tcp
    networks:
      default:
        name: demo_default
    ```

### Observed result

- Service ports are not parsed correctly if override is present _and_ the respective service is listed.
  - Other ports that do not define both udp and tcp are parsed correctly. 
  - Modifying the service in the override does not change the way the `ports` are parsed.
- Same result also when explicitly using the `-f` flag to point to both yaml files. 

### Expected result

- Ports should be parsed the same with or without a `docker-compose.override.yml`. 

### Stacktrace / full error message

```shell
# n/a - no error
```

## Additional information

- latest docker for desktop (macos)
- up to date macos big sur
