### ISSUE TITLE
Docker Compose V2 build network not working

### ISSUE THREAD

**Issue by WilliamABradley** [docker/compose#8588]
## Description of the issue

Docker compose v2 does not listen to the build network parameter, breaking in environments with a disabled bridge network, e.g. EKS.

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose build test-runner`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
v2.0.0-rc.3
```

**Output of `docker version`**
```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    environment:
      POSTGRES_DB: [redacted]_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:13
    networks:
      default: null
    restart: always
  test-runner:
    build:
      context: E:\Programming\Github\[redacted]
      dockerfile: E:\Programming\Github\[redacted]
      args:
        NPM_TOKEN: ""
      network: host
    container_name: test-runner
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: db
      DB_NAME: [redacted]_test
      DB_PASSWORD: postgres
      DB_SSL: "false"
      DB_USER: postgres
    links:
    - db
    networks:
      default: null
networks:
  default:
    name: [redacted]_default
```

## Steps to reproduce the issue

1. Create docker compose with service that contains build
2. Set build network to `host`
3. Disable Bridge network
4. Run docker compose build

### Observed result

Build fails with network bridge not found

### Expected result

Build succeeds

### Stacktrace / full error message

```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apk --no-cache add python make g++]: network bridge not found
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Observed on Ubuntu and Windows.

```
ARG dockercompose_version=v2.0.0-rc.3
RUN mkdir -p ~/.docker/cli-plugins/ && \
    curl -SL "https://github.com/docker/compose/releases/download/${dockercompose_version}/docker-compose-linux-amd64" -o ~/.docker/cli-plugins/docker-compose && \
    chmod +x ~/.docker/cli-plugins/docker-compose
```
