### ISSUE TITLE
v2 Error: Service with container_name "gluetun" not found for network_mode 'container:gluetun' even though the container is running

### ISSUE THREAD

**Issue by nithin-bose** [docker/compose#8597]
## Description of the issue
``docker compose up -d`` errors out but ``docker-compose up -d`` works as expected

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
docker compose version
Docker Compose version v2.0.0-rc.3

docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  deluge:
    container_name: deluge
    environment:
      DELUGE_LOGLEVEL: error
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/London
    image: ghcr.io/linuxserver/deluge
    network_mode: container:gluetun
    restart: unless-stopped
    volumes:
    - <path>/config:/config:rw
    - <path>/downloads:/downloads:rw
version: '3.7'
```

Other compose file:
```
services:
  gluetun:
    cap_add:
    - NET_ADMIN
    container_name: gluetun
    environment:
      OPENVPN_PASSWORD: <password>
      OPENVPN_USER: <user>
      REGION: Germany Frankfurt am Main
      SERVER_HOSTNAME: de-fra.prod.surfshark.com
      TZ:  Europe/London
      VPN_TYPE: openvpn
      VPNSP: surfshark
    image: qmcgaw/gluetun
    network_mode: bridge
    ports:
    - mode: ingress
      target: 8888
      published: 8888
      protocol: tcp
    - mode: ingress
      target: 8388
      published: 8388
      protocol: tcp
    - mode: ingress
      target: 8388
      published: 8388
      protocol: udp
    - mode: ingress
      target: 8000
      published: 8000
      protocol: tcp
    - mode: ingress
      target: 8112
      published: 8112
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /gluetun/config
      target: /gluetun
      bind:
        create_host_path: true
```

## Steps to reproduce the issue

1. Place the above compose files in different folders
2. Run ``docker compose up -d`` with the ``gluetun`` docker-compose file and make sure it is running 
3. Run ``docker compose up -d`` with the ``deluge`` docker compose file 

### Observed result
```
service with container_name "gluetun" not found for network_mode 'container:gluetun'
```
The container comes up as expected when using ``docker-compose`` (notice the ``-``)

### Expected result
The deluge container should've come up like it does when using ``docker-compose``

## Additional information

Using Xubuntu 20.04.3 LTS (GNU/Linux 5.11.0-34-generic x86_64)
Docker was installed using the docker official guides
docker compose was installed as a plugin, folloeing the official guide
docker-compose was installed using apt
