### ISSUE TITLE
Docker Desktop 4.0.0 dns Not Working Properly to External Hostname 

### ISSUE THREAD

**Issue by Zachery2008** [docker/compose#8600]
When running `docker-compose up --build` for the following example yaml file. The dns seems not working properly. The service tries to reach to external network, but docker produces error: `getaddrinfo ENOTFOUND login.microsoftonline.com`

```
version: "3.9"
services:
  alerts-service:
    build:
      dockerfile: ./Dockerfile
    command: npm run start
    env_file:
      - 'variables.env'
```

To me, it seems like docker failed to resolve the external hostname `login.microsoftonline.com`.

**Comment by ndeloof** [comment]
Are you able to build this Dockerfile using a plain `docker build` command?

**Comment by Zachery2008** [comment]
> Are you able to build this Dockerfile using a plain `docker build` command?

Let me give you an real actual example of the file structure,
```
/packages/service_1/Dockerfile
         /service_2/Dockerfile
         ...
/scripts/public/docker/docker-compose.yaml
```
So my `docker-compose.yaml` is like this
```
version: "3.9"
services:
  service-1:
    build:
      context: ./../../../packages/
      dockerfile: ./service_1/Dockerfile
    command: npm run start
    env_file:
      - 'variables.env'

  service-2:
    build:
      context: ./../../../packages/
      dockerfile: ./service_2/Dockerfile
    command: npm run start
    env_file:
      - 'variables.env'
    ports:
      - 3000:3000
      
  redis:
    image: redis
``` 

For your question, yes, I can build the image with `docker build` command: 
`docker build -f ./../../../packages/service_1/Dockerfile  ./../../../packages`
