### ISSUE TITLE
Compose with variable on image name

### ISSUE THREAD

**Issue by cfeltz34** [docker/compose#8601]
## Context information (for bug reports)

- [X] Using Compose V2.0.0-rc.2

**Output of `docker(-)compose version`**
```
V2.0.0-rc.2
```

**Output of `docker version`**
```
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. Create a yml file and define a service like (where .env file with "RABBITMQ_VERSION=3.8.9")
```
version: '3.7'
services:
  rabbitmq:
    container_name: example.rabbitmq
    image: rabbitmq:$RABBITMQ_VERSION-management

```
My container is based on image "rabbitmq:3.8.9" instead of "rabbitmq:3.8.9-management"
