### ISSUE TITLE
commented out env vars parsed when using extends

### ISSUE THREAD

**Issue by beyondmeat** [docker/compose#8603]
## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
N/A
```

## Steps to reproduce the issue

1. Have compose file, using extends to use another compose file
2. commented out line containing a variable, e.g ${THIS_IS_A_BUG}
3. compose up

### Observed result
WARN[0000] The "THIS_IS_A_BUG" variable is not set. Defaulting to a blank string. 

### Expected result
No warning as variable doesn't exist in the compose spec, it's commented out.

### Stacktrace / full error message

```
N/A
```

## Additional information

docker-compose.yml
```
version: "3.9"

services:
  whoami:
    extends:
      file: ./docker-compose.whoami.yml
      service: whoami
```

docker-compose.whoami.yml
```
version: "3.9"

services:
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.${THIS_IS_A_BUG}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
```
Notice the `#`, the line containing the var is a commented out line.
```
docker compose up
WARN[0000] The "THIS_IS_A_BUG" variable is not set. Defaulting to a blank string. 
```
