### ISSUE TITLE
docker-compose run --rm throws "You cannot remove a running container" on experimental V2

### ISSUE THREAD

**Issue by melicerte** [docker/compose#8619]
## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  back:
    build:
      context: /Users/user/workspace/myproject/docker/back
      dockerfile: /Users/user/workspace/myproject/docker/back/Dockerfile
    depends_on:
      php-fpm:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: myproject
      DB_DATABASE: myproject
      DB_HOST: mysql
      DB_PASSWORD: myproject
      DB_PORT: "3306"
      DB_ROOT_PASSWORD: myproject
      DB_USERNAME: myproject
    env_file:
    - .env_docker
    extends:
      file: docker-compose.base.yml
      service: back-base
    image: myprojectregistrydev.azurecr.io/myproject/back:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/user/workspace/myproject
      target: /var/www
      bind:
        create_host_path: true
    working_dir: /var/www
  mysql:
    environment:
      COMPOSE_PROJECT_NAME: myproject
      DB_DATABASE: myproject
      DB_HOST: mysql
      DB_PASSWORD: myproject
      DB_PORT: "3306"
      DB_ROOT_PASSWORD: myproject
      DB_USERNAME: myproject
    env_file:
    - .env_docker
    extends:
      file: docker-compose.base.yml
      service: mysql-base
    image: mysql:5.7.22
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3306
      published: 3310
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/user/workspace/myproject/docker/mysql/my.cnf
      target: /etc/mysql/my.cnf
      bind:
        create_host_path: true
  node:
    image: node:14.4
    networks:
      default: null
    volumes:
    - type: bind
      source: /Users/user/workspace/myproject
      target: /app
      bind:
        create_host_path: true
    working_dir: /app
  php-fpm:
    build:
      context: /Users/user/workspace/myproject/docker/php-fpm
      dockerfile: /Users/user/workspace/myproject/docker/php-fpm/Dockerfile
    depends_on:
      mysql:
        condition: service_started
    entrypoint:
    - /docker-entrypoint.sh
    environment:
      COMPOSE_PROJECT_NAME: myproject
      DB_DATABASE: myproject
      DB_HOST: mysql
      DB_PASSWORD: myproject
      DB_PORT: "3306"
      DB_ROOT_PASSWORD: myproject
      DB_USERNAME: myproject
    env_file:
    - .env_docker
    extends:
      file: docker-compose.base.yml
      service: php-fpm-base
    image: myprojectregistrydev.azurecr.io/myproject/php-fpm:7.4
    networks:
      default: null
    volumes:
    - type: bind
      source: /Users/user/workspace/myproject/docker/php-fpm/fpm-pool.conf
      target: /etc/php/7.4/fpm/pool.d/www.conf
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /Users/user/workspace/myproject/docker/php-fpm/php.ini
      target: /usr/local/etc/php/conf.d/myproject.ini
      bind:
        create_host_path: true
    - type: bind
      source: /Users/user/workspace/myproject
      target: /var/www
      bind:
        create_host_path: true
    working_dir: /var/www
  phpmyadmin:
    depends_on:
      mysql:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: myproject
      DB_DATABASE: myproject
      DB_HOST: mysql
      DB_PASSWORD: myproject
      DB_PORT: "3306"
      DB_ROOT_PASSWORD: myproject
      DB_USERNAME: myproject
    env_file:
    - .env_docker
    image: phpmyadmin/phpmyadmin:latest
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: 8088
      protocol: tcp
networks:
  default:
    name: myproject_default
```

## Steps to reproduce the issue

1. Run the following command : 
`docker-compose run -T --rm --user=myuser --no-deps --entrypoint="/bin/bash -c" php-fpm "./vendor/bin/php-cs-fixer fix --diff --config=.php_cs.php -vvv --using-cache=no myfile.php --ansi"`

### Observed result
Error response from daemon: You cannot remove a running container a3ad834566e2b80d553815e7319fbb98ae7616c030fe59a507990c3772c37274. Stop the container before attempting removal or force remove

### Expected result
No error

### Stacktrace / full error message

```
Error response from daemon: You cannot remove a running container a3ad834566e2b80d553815e7319fbb98ae7616c030fe59a507990c3772c37274. Stop the container before attempting removal or force remove

```

## Additional information

Tested on macOS Big Sur 11.5.2, docker-composer comes with Docker Desktop, V2 enabled by default in the experimental features

Works well with docker compose v2 disabled.
