### ISSUE TITLE
Anchors on linux not working with env-variables

### ISSUE THREAD

**Issue by tiehfood** [docker/compose#8633]
## Description of the issue
Using the simple docker-compose.yaml snippet from below doesn't work on linux/amd64 with the current version (1.29.2 as well as 2.0.0-rc3). I had no problem running it on my Mac machine.
I think the env variable is not substituted before the yaml syntax is evaluated on linux.

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: "3"

x-service-a: &service_a
  service_a:
    image: IMAGE_A
    ...

x-service-b: &service_b
  service_b:
    image: IMAGE_B
    ...

services:
  <<: ${USE_SERVICE:-*service_a}
  ...
```

## Steps to reproduce the issue

1. Use a simple docker-compose.yaml setup like below. It contains two or more anchors which should be filled into "services" depending on an env variable
2. Try to run `docker-compose up` or `docker-compose config`

### Observed result
docker-compose throws an error like below

### Expected result
Services should be deployed successfully / Config should be parsed correctly
### Stacktrace / full error message

```
ERROR: yaml.constructor.ConstructorError: while constructing a mapping
  in "./docker-compose.yaml", line x, column 3
expected a mapping or list of mappings for merging, but found scalar
  in "./docker-compose.yaml", line x, column 7
```

## Additional information

Ubuntu 20.04.4 LTS, ADM64, compose installed from GitHub Release page

**Comment by ndeloof** [comment]
I can't see any reason behavior would be distinct on Mac/Win/Linux and actual get the same issue running on my Mac.

**Comment by tiehfood** [comment]
I'm running it on MacOS 11.2.3 with newest docker release for Mac.

**Comment by tiehfood** [comment]
```
root@linux:~# cat test.yaml 
version: "3"

x-service-a: &service_a
  service_a:
    image: alpine

x-service-b: &service_b
  service_b:
    image: alpine

services:
  <<: ${USE_SERVICE:-*service_a}
root@linux:~# docker-compose -f test.yaml config
ERROR: yaml.constructor.ConstructorError: while constructing a mapping
  in "./test.yaml", line 12, column 3
expected a mapping or list of mappings for merging, but found scalar
  in "./test.yaml", line 12, column 7
```

vs.

```
user@macos % cat test.yaml 
version: "3"

x-service-a: &service_a
  service_a:
    image: alpine

x-service-b: &service_b
  service_b:
    image: alpine

services:
  <<: ${USE_SERVICE:-*service_a}%                                                                                                                                                                                                                          user@macos % docker-compose -f test.yaml config
services:
  service_a:
    image: alpine
    networks:
      default: null
networks:
  default:
    name: desktop_default
x-service-a:
  service_a:
    image: alpine
x-service-b:
  service_b:
    image: alpine
```

**Comment by ndeloof** [comment]
MacOS 11.2.3
```console
$ docker-compose-v1 -v
docker-compose version 1.29.2, build 5becea4c
$ docker-compose-v1 config
ERROR: yaml.constructor.ConstructorError: while constructing a mapping
  in "./compose.yaml", line 10, column 3
expected a mapping or list of mappings for merging, but found scalar
  in "./compose.yaml", line 10, column 7
```

**Comment by ndeloof** [comment]
speaking more generally, ability to support this scenario is challenging, as you expect variable to be resolved before the yaml anchors are processed by the yaml parser. This typically isn't supported on Compose V2. You use-case is pretty obvious here, but I wonder how we could handle this.

**Comment by tiehfood** [comment]
But why is it running on my Mac machine? The feature would be really nice. Otherwise I had to split the compose file into multiple files, which isn't that nice

**Comment by tiehfood** [comment]
Generally speaking: There shouldn't be a problem in parsing the yaml file **after** variable substitution. Or is there any advantage in parsing yaml first? Or any case where the result would be incorrect?

**Comment by ndeloof** [comment]
> why is it running on my Mac machine

Can't tell. Please dump `docker-compose version` just in case...

> There shouldn't be a problem in parsing the yaml file after variable substitution

we adopted this approach in earlier version of Compose V2 with the same assumption, and this triggered a long list of side-effects/bugs. Basically, as we replace `foo: ${VAR}` before parsing, and user set `VAR=true`, the yaml parser then translate value into a `boolean`, not the `true` string that was expected. This is a pretty common scenario for environment set in container.

**Comment by tiehfood** [comment]
> Please dump `docker-compose version` just in case...

Sorry, here it is 😉 `Docker Compose version v2.0.0-rc.2`

does the yaml-parser also interpret it as boolean if you quote it: `foo: "${var}"`?

**Comment by ndeloof** [comment]
`"true"` would not be parsed by YAML as boolean, but such a requirement would break compatibility.

docker-compose v2.0.0-rc.2 was using pre-parsing variable interpolation, so this "feature" to work for you, but won't anymore after upgrade to rc3

For your usage, a possible workaround would be to use profiles
```yaml
services:
  service_a:
    profiles: ["a"]
    image: alpine

  service_b:
    profiles: ["b"]
    image: alpine
```
Then select the adequate service by `docker compose --profile a xxx`
.. but this won't select any service "by default"

It seems to me we miss a global concept of "abstract service" which actual definition would depend on active profile. A typical scenario would be to have an abstract `db` service declared and used as dependency by application, but actual service implementation to be `sqlite` with `dev` profile enabled, and `mysql` for production. This topic we could discuss by the Compose Specification
