### ISSUE TITLE
Conditional directive for `docker-compose up -d`

### ISSUE THREAD

**Issue by webdevium** [docker/compose#8639]
**Is your feature request related to a problem? Please describe.**
I would like to be able to configure the conditional start of each service using if-conditions.
As for me, this ability is useful for ```docker-compose up -d```

**Describe the solution you'd like**
It would be great to have a conditional check directive, something like `up-if`

```
version: "3"

services:

  example:
    image: example:latest
    container_name: example
    ports:
      - "80:80"
    volumes:
      - ./example:/app
    networks:
      - example-network
    up-if:
      test: [ "CMD", "[-z $EXAMPLE_ENV_VARIABLE]" ]
```

**Describe alternatives you've considered**
I've been using custom files for a long time.

```
if [-z $EXAMPLE_ENV_VARIABLE]
then
   docker-compose -f docker-compose.case1.yml up -d
else
   docker-compose -f docker-compose.case2.yml up -d
fi
```

It seems to me that the option with a conditional directive will be useful not only for me.
