### ISSUE TITLE
Compose V2 rc.3 `kill` also kills services it `depends_on`

### ISSUE THREAD

**Issue by jamshid** [docker/compose#8653]
## Description of the issue

The V1 `docker-compose kill foo` will only kill the foo service. V2 `docker-compose kill foo` kills **all** services foo `depends_on`, which breaks V1 compatibility and doesn't seem to make sense. 

Why should killing a service kill services it depends on? `docker-compose stop foo` only stops the one service, it doesn't stop services that it depends on or that depend on it. There is no `docker-compose kill --no-deps` options to prevent this behavior.

## Context information (for bug reports)

- [X ] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           newdefault
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  one:
    command:
    - sleep
    - "600"
    image: centos
    networks:
      default: null
  three:
    command:
    - sleep
    - "600"
    depends_on:
      two:
        condition: service_started
    image: centos
    networks:
      default: null
  two:
    command:
    - sleep
    - "600"
    depends_on:
      one:
        condition: service_started
    image: centos
    networks:
      default: null
networks:
  default:
    name: test_default
```

## Steps to reproduce the issue

1. `docker-compose up -d`
```
services:
  one:
    image: centos
    command: sleep 600
  two:
    image: centos
    command: sleep 600
    depends_on:
      - one    
  three:
    image: centos
    command: sleep 600
    depends_on:
      - two
```
2. `docker-compose kill three`

### Observed result

```
 ⠿ Container test_one_1    Killed                                                                                  0.4s
 ⠿ Container test_three_1  Killed                                                                                  0.4s
 ⠿ Container test_two_1    Killed                                                                                  0.5s
```
### Expected result

Only the specified service should be killed.

## Additional information

Docker for Mac 4.0.1
