### ISSUE TITLE
V2 compose `up` ignores `--no-deps` when using `--scale`

### ISSUE THREAD

**Issue by jamshid** [docker/compose#8657]
## Description of the issue

V2 compose `up` ignores `--no-deps` when using `--scale`

## Context information (for bug reports)

- [ X] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           newdefault
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. `docker-compose up -d --no-deps --scale two=1`
```
services:
  one:
    image: centos
    command: sleep 600
  two:
    image: centos
    command: sleep 600
    depends_on:
      - one    
  three:
    image: centos
    command: sleep 600
    depends_on:
      - two
```

### Observed result

```
% docker-compose ps
NAME                COMMAND             SERVICE             STATUS              PORTS
test_one_1          "sleep 600"         one                 running             
test_three_1        "sleep 600"         three               running             
test_two_1          "sleep 600"         two                 running             
```
### Expected result

Only service "two" should be up.

## Additional information

Docker for Mac 4.0.1
