### ISSUE TITLE
[v2] network aliases from multiple files do not get merged

### ISSUE THREAD

**Issue by mtzanidakis** [docker/compose#8719]
Hello,
I'm facing an issue with 2.0.0.

### Description

I have network aliases for the same service in multiple files; in v1 all aliases get merged, in v2 only the aliases from additional files are applied.

###  Steps to reproduce

docker-compose.yml
```
version: "3"
services:
  s1:
    image: busybox
    networks:
      default:
        aliases:
          - alias1
    command: ["sleep", "1h"]

  s2:
    image: busybox
    command: ["ping", "alias1"]
```
docker-compose.override.yml 
```
version: "3"
services:
  s1:
    networks:
      default:
        aliases:
          - alias2
```

`docker-compose config` [1.29.2]
```
services:
  s1:
    command:
    - sleep
    - 1h
    image: busybox
    networks:
      default:
        aliases:
        - alias1
        - alias2
  s2:
    command:
    - ping
    - alias1
    image: busybox
version: '3'
```

`docker compose config` [2.0.0]
```
services:
  s1:
    command:
    - sleep
    - 1h
    image: busybox
    networks:
      default:
        aliases:
        - alias2
  s2:
    command:
    - ping
    - alias1
    image: busybox
    networks:
      default: null
networks:
  default:
    name: test_default
```
