### ISSUE TITLE
Environment variables don't work with docker compose V2

### ISSUE THREAD

**Issue by wh75er** [docker/compose#8720]
**Description**

I'm trying to pass environment variables to docker-compose via environment key word, but getting 
The ... variable is not set. Defaulting to a blank string.

neither sudo docker compose -e VAR=VALUE work

My docker-compose file:

```
version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  payment-service:
    environment:
      JWT_KEY: ${JWT_KEY}
      ADMIN_ID: ${ADMIN_ID}
      ADMIN_SECRET: ${ADMIN_SECRET}
    build:
      context: .
      dockerfile: ./build/payment.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
```

**Steps to reproduce the issue:**
1. Export variables via export JWT_KEY=VALUE; export ADMIN_ID=VALUE2; export ADMIN_SECRET=VALUE3
2. `sudo docker compose up` or `sudo docker compose up -e JWT_KEY=VALUE` or `sudo docker compose up -e JWT_KEY`

**Describe the results you received:**

WARN[0000] The "ADMIN_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ADMIN_SECRET" variable is not set. Defaulting to a blank string. 
WARN[0000] The "JWT_KEY" variable is not set. Defaulting to a blank string.

**Describe the results you expected:**

I'd like to have my variables to be set and detected

**Additional information you deem important (e.g. issue happens only occasionally):**

This approach worked on docker-compose (V1)

**Output of `docker compose version`:**

```
Docker Compose version 2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0)

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 80
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.56GiB
 Name: f54
 ID: RDA2:6YUB:D4GF:EHTR:UXIK:5CKG:4GWD:LV32:4AOR:VUTT:BWKL:BMAF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

**Additional environment details:**

```
env | grep JWT_KEY
JWT_KEY=DEVELOP_KEY

env | grep ADMIN_ID
ADMIN_ID=DEVELOP_ID

env | grep ADMIN_SECRET
ADMIN_SECRET=DEVELOP_SECRE
```

**Comment by lingmann** [comment]
Hmmm... stale bot, there are at least 5 +1's to this issue and it's easily reproducible. :-/

**Comment by yueki1993** [comment]
I have (maybe) related issue, so let me add information here.

- docker-compose.yml
```yml:docker-compose.yml
version: '3'
services:
  app:
    image: alpine
    environment:
      foo: ${foo}
    command: tail -f /dev/null
```

- I get warning warning message, although the variable is actually set.

```sh
[Terminal 1]
% docker compose version
Docker Compose version v2.5.1

% export foo=bar
% export | grep foo
foo=bar
% docker compose up
Attaching to poc-app-1

[Terminal 2]
% export | grep foo
// no output
% docker compose exec app sh 
WARN[0000] The "foo" variable is not set. Defaulting to a blank string. // ← ????
/ # export
export HOME='/root'
export HOSTNAME='83e6b8d5e0be'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PWD='/'
export SHLVL='1'
export TERM='xterm'
export foo='bar'
/ # exit
% export foo=aaaaaaaa
% docker compose exec app sh # no warning.
/ # export
export HOME='/root'
export HOSTNAME='e5de6e3692e9'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PWD='/'
export SHLVL='1'
export TERM='xterm'
export foo='bar'
```

I suspect `docker compose exec` checks current shell's environment variables whether the environment variable is set or not, rather than checking the shell of `docker compose up`.

**Comment by laurazard** [comment]
Hi all, thanks for reporting this issue.

I noticed this is an older issue, can you still replicate this on a recent version of Compose?

Using a simple compose file such as:

```yaml
services:
  foo:
    image: alpine:latest
    command: echo hello $A
    environment:
      - A=${A}
```

and running ` A=world ./docker-compose up`, I get:
```
[+] Running 1/0
 ⠿ Container build-foo-1  Recreated                                                                   0.1s
Attaching to build-foo-1
build-foo-1  | hello world
build-foo-1 exited with code 
```

I'm closing the issue for now, please comment if this is still affecting you.
