### ISSUE TITLE
compose v2 runtime issue

### ISSUE THREAD

**Issue by egyptianbman** [docker/compose#8722]
I'm trying to get a container that uses the `nvidia` runtime to work but I can't seem to be able to do so, using compose v2. I can run the following without issue:
```console
➜ docker run --rm --runtime nvidia nvidia/cuda:11.0-base nvidia-smi    
Fri Oct  1 07:24:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    50W / 350W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Running the following test compose:
```yaml
version: '3.9'
                                                                                                       
services:                                                                                              
  test:
    image: nvidia/cuda:11.0-base
    command: nvidia-smi
    runtime: nvidia  
```
Doesn't yield the expected output. I changed the command to bash and ran the container and noticed that upon running a docker inspect, the output isn't what I expected:
```console
➜ docker inspect test-test-1 | jq '.[0].HostConfig.Runtime'
"runc"
```

As expected, the runtime is configured in `/etc/docker/daemon.json`:
```console
➜ cat /etc/docker/daemon.json 
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

**Comment by egyptianbman** [comment]
Updated title as requested.

Looking at the documentation again, I noticed that `runtime` is marked as legacy. I tested the provided example utilizing `capabilities`:
```yaml
services:
  test:
    image: nvidia/cuda:10.2-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

With that, I am now finding that the `nvidia-smi` command exists, but yields an error:
```console
❯ docker-compose up test   
[+] Running 1/0
 ⠿ Container test-test-1  Created                                                                                                                                                                         0.0s
Attaching to test-test-1
test-test-1  | Failed to initialize NVML: Unknown Error
test-test-1 exited with code 255
```

With `runtime`, the output is:
```console
❯ docker-compose up test
[+] Running 1/0
 ⠿ Container test-test-1  Recreated                                                                                                                                                                       0.1s
Attaching to test-test-1
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "nvidia-smi": executable file not found in $PATH: unknown
```

In both cases, the runtime is `runc`.
