### ISSUE TITLE
[ECS] Issue with pulling external AWS secrets into sidecar when declared via docker compose

### ISSUE THREAD

**Issue by jakesmart-drizly** [docker/compose#8730]
**Description**
I'm having issue loading an external secret into the sidecar during container start up in Fargate. This failure causes the whole stackset to fail.

The compose set up is relatively simple, (there is an external load balancer that is used by other services not included here)
```
version: "3.1"
services:
  redis-seeding:
    image: "${ECR_REPOSITORY}:redis-seeder-${GIT_COMMIT}"
    build:
      context: ..
      dockerfile: docker/seed_redis.Dockerfile
    environment:
     - ENV=${ENV}
    networks:
      - redis
    secrets:
      - primary_redis_creds
secrets:
  primary_redis_creds:
    name: "${REDIS_PRIMARY_ARN}"
    external: true
```

The secrets set up that I currently have is defined by the following terraform:
```
resource "aws_kms_key" "secrets" {
  enable_key_rotation = false #tfsec:ignore:aws-kms-auto-rotate-keys
}
resource "aws_secretsmanager_secret" "redis_write" {
  name                    = "${var.app_name}/redis_write"
  recovery_window_in_days = 0
  kms_key_id              = aws_kms_key.secrets.arn
  lifecycle {
    create_before_destroy = true
  }

}

resource "aws_secretsmanager_secret" "redis_read" {
  name                    = "${var.app_name}/redis_read"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 0
  lifecycle {
    create_before_destroy = true
  }

}
```
**Steps to reproduce the issue:**
1. Create the secrets via terraform and get their arn
2. Input their ARN into the compose file
3. Run docker-compose up

**Describe the results you received:**
An error
```
TaskFailedToStart: ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 1 time(s): failed to fetch secret arn:aws:secretsmanager:us-east-1:...
```

**Describe the results you expected:**
Completion like other stacks that use this exact same set up (albeit without kms).

**Additional information you deem important (e.g. issue happens only occasionally):**
The output of docker-compose convert related to the secret appears to grant the necessary perms - mostly decrypt.

```
      - PolicyDocument:
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            - ssm:GetParameters
            - kms:Decrypt
            Condition: {}
            Effect: Allow
            Principal: {}
            Resource:
            - arn:aws:secretsmanager:us-east-1:******obfuscated******
        PolicyName: redis-seedingGrantAccessToSecrets
```

**Output of `docker compose version`:**

Depends on the context
```
default=Docker Compose version v2.0.0-beta.6
ecscontext=Docker Compose version 1.0.17
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.775GiB
 Name: docker-desktop
 ID: FXGN:46AW:76VB:TLIX:VVSO:6Y3A:LOQU:IUJK:6QG6:YZE5:UNGM:7T7D
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 44
  System Time: 2021-10-02T00:29:02.297045758Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
