### ISSUE TITLE
My container freezes on a regular basis.

### ISSUE THREAD

**Issue by dabrahams** [docker/compose#8744]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C0300869-15D9-492C-8DC5-2AA7815C37F8/20211001171534

### Expected behavior

The container continues to work.

### Actual behavior

Existing terminal prompts stop responding, can't create a new one, no apparent other response.

### Information
It's reproducible.  I don't know how new it is, sorry.
  - macOS Version: macOS 11.6 (20G165)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.0.1 (68347)

### Steps to reproduce the behavior

I run it via `docker compose up` with 

`docker-compose.yml`:
```yaml
version: '2'
services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
      - PAGES_REPO_NWO=stlab/better-code
    command: >
        jekyll serve --force-polling --watch --incremental
        --config _config.yml,_config.docker.yml
        --livereload
    image: jekyll/jekyll:pages
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
```

and

`config.docker.yml`:
```yaml
url: "http://localhost:4000"
livereload_script: >
    <script src="http://localhost:35729/livereload.js"></script>
```

The full project is at https://github.com/stlab/better-code
