### ISSUE TITLE
Output of "docker compose config" does not contain full path to context

### ISSUE THREAD

**Issue by nkovacs** [docker/compose#8760]
**Description**

The output of `docker compose config` does not contain the full path to the context.
This was probably changed in https://github.com/docker/compose/issues/8503, but `context` should've remained absolute, only `dockerfile` should be relative. 

**Steps to reproduce the issue:**
1. docker-compose.yml:
    ```
    version: '3.7'
    services:
      example:
        build:
          context: context-path/one/
          dockerfile: Dockerfile-example
    ```
2. context-path/one/Dockerfile-example:
    ```
    FROM scratch
    ```
3. `docker compose config`

**Describe the results you received:**

```
services:
  example:
    build:
      context: context-path/one/
      dockerfile: Dockerfile-example
    networks:
      default: null
networks:
  default:
    name: docker-bug_default
```

**Describe the results you expected:**

```
services:
  example:
    build:
      context: /Users/user/docker-bug/context-path/one/
      dockerfile: Dockerfile-example
    networks:
      default: null
networks:
  default:
    name: docker-bug_default
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: 3W4B:XTEH:5UFH:FUQG:AXKE:QTEX:WS27:XIXM:AXHK:BDKY:6HU7:5JA2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by bwateratmsft** [comment]
@ravipal Not sure if you filed one already but this is definitely related.

**Comment by karolz-ms** [comment]
This seems to have regressed in Docker Desktop 4.3 / Compose 2.2.1. Interestingly, I cannot reproduce the issue on a Mac, only Windows machines are affected... 🤔 

@ulyssessouza @stephanierifai @ravipal  FYI

**Comment by stephanierifai** [comment]
Interesting, thanks for flagging it to us @karolz-ms !

**Comment by philliphoff** [comment]
@stephanierifai @karolz-ms I'm able to reproduce the issue on Mac with Docker Desktop 4.3.0, Docker Compose 2.2.1 when V2 is enabled.  The difference seems to be whether `docker compose` is used vs. `docker-compose`; it's the latter that has the issue.

With V2 *not* enabled:

```bash
$ docker-compose config
services:
  webapp:
    build:
      context: /Users/<user>/Source/Scratch/compose
      dockerfile: WebApp/Dockerfile
    image: webapp
version: '3.4'

$ docker compose config
services:
  webapp:
    build:
      context: /Users/<user>/Source/Scratch/compose
      dockerfile: WebApp/Dockerfile
    image: webapp
    networks:
      default: null
networks:
  default:
    name: compose_default

```

With V2 enabled:

```bash
$ docker-compose config 
services:
  webapp:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    image: webapp

$ docker compose config
services:
  webapp:
    build:
      context: /Users/<user>/Source/Scratch/compose
      dockerfile: WebApp/Dockerfile
    image: webapp
    networks:
      default: null
networks:
  default:
    name: compose_default
```

Results generated with the following `docker-compose.yaml`:

```yaml
version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
```
