### ISSUE TITLE
Bug if two services start with the same characters since docker-compoose v2

### ISSUE THREAD

**Issue by JSamir** [docker/compose#8802]
I've got a compose file that looks like this:
```
version: '3'
services:
  db:
  dbtool:
```

If I try to use it with docker-compose I get this error:
`services.db must be a mapping`

If I change the second service to `tool` it works.
