### ISSUE TITLE
Logging driver `none` seems to be ignored, CLI shows output.

### ISSUE THREAD

**Issue by WeeJeWel** [docker/compose#8828]
Setting...

```
version: "3.8"
services:
  my_service:
    logging:
      driver: none
```

...still shows output to the console since docker-compose V2.

**Comment by ndeloof** [comment]
docker compose v1 indeed use the logging API, and doing so won't collect any log when driver is set to `none`. 
docker compose v2 attach to container (just like docker run does) and does not rely on the docker engine to collect logs with a driver.

IHMO relying on logging driver to exclude logs from the `compose up` output is just a hack, should not be considered a "feature" to be reproduced for backward compatibility. The ability to exclude logs from a few services is something to be considered as an explicit option.

**Comment by WeeJeWel** [comment]
Yeah, disabling logs for a specific service is a must-have imho. I’m really not interested in database logs, for example, they just pollute the console.

**Comment by KoditkarVedant** [comment]
I liked the idea of adding support to run specific service in detached mode. For example:

Currently we have option to run all services in detached mode
```bash
docker compose up -d 
```

Similarly we can also run only a service in detached mode using the below command
```
docker compose run -d service_name
``` 

**Proposal:** 
We can add property on `Service` to specify the `detach` option like
```
version: '3.4'
services:
  service1:
    image: alpine
    detach: true    # you can set if you would like to run this service in detach mode

  service2:
    image: alpine
```
> Note:  by default `detach` is `false`

Now when you run `docker compose up` it will run `service1` in detach mode and `service2` in foreground mode.
If you run `docker compose up -d` it will override the detach options on each service.

In current CLI when you run services in foreground mode (attached mode) & on sending interrupt (terminate) signal SIGINT by pressing `Ctrl + c` it stops all containers but in suggested it will only stop attached containers you user needs to manually stop the container running in detached mode.
