### ISSUE TITLE
docker compose V2 run fails if one of the services has a wrong volume

### ISSUE THREAD

**Issue by efpies** [docker/compose#8841]
**Description**

I have a YML-file with a few services, and I run one using `run`. Like this:

`docker-compose -f Tools.yml run --rm  migrations update`

However, it's not possible because a service named `restore-db` has a wrong volume due to part of the path comes from an environment variable:

```
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/dump.sql:ro: empty section between colons
```

Uh, I know? But I don't even touch this service? Also, this service may be mangled in all imaginable ways, like pointing to a wrong image or a Dockerfile, but apparently a wrong volume is a big deal to not run anything.

**Steps to reproduce the issue:**
1. Have a file named `Tools.yml` with contents as below:
```
version: '3.4'
services:
  migrations:
    entrypoint: ["wait-for", "--timeout", "20", "db:5432", "--", "/entrypoint"]
    environment:
      LIQUIBASE_URL: jdbc:postgresql://db/db
      LIQUIBASE_USERNAME: dbuser
      LIQUIBASE_PASSWORD: dbuser
      LIQUIBASE_CHANGELOG: /Database/index.xml

  restore-db:
    image: local-restore-db
    build:
      context: .
      dockerfile: RestoreDb.Dockerfile
      args:
        baseImage: "${POSTGRES_DOCKER_IMAGE}"
    entrypoint: ["wait-for", "--timeout", "20", "db:5432", "--",
                 "psql", "-h", "db", "-U", "dbuser", "-f", "/dump.sql", "dbuser"]
    volumes:
      - "$SQL_FILE:/dump.sql:ro"
```
2. Execute `docker-compose -f Tools.yml run --rm  migrations update`

**Describe the results you received:**

```
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/dump.sql:ro: empty section between colons
```

**Describe the results you expected:**

`migrations` services up and running

**Additional information you deem important (e.g. issue happens only occasionally):**

In this example, empty env variable makes the path wrong. However, the volumes string may look as `"11:/dump.sql:ro"`, this will produce another error:

```
service "restore-db" refers to undefined volume 11: invalid compose project
```

This was never a problem in a previous version of `compose`.

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 10
  Running: 4
  Paused: 0
  Stopped: 6
 Images: 328
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: CP33:HHGN:KJLU:Y2GJ:6PM3:ZHJL:WO3O:EJGR:NAFS:XXVT:L4KY:HIPW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 83
  Goroutines: 75
  System Time: 2021-10-28T01:29:36.21635135Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

macOS 11.6 / 12
