### ISSUE TITLE
Profiles are not respected for `config`

### ISSUE THREAD

**Issue by subpardaemon** [docker/compose#8846]
**Description**

I put together a rather complex docker compose YAML. We have a lot of services, and about 7 running contexts. Profiles seemed a great solution to selectively turn on and off specific services. However, when I try to run `docker-compose config` it seems to disregard the `profiles` entries altogether.

**Steps to reproduce the issue:**

This is a much simplified version of our compose file, but it has the same erroneous behavior.

```
---
version: "3.9"
services:
  web: &WEB
    profiles:
      - dev
      - e2e
    build:
      context: .
      target: prod
  postgres:
    image: postgres:10.15

  testrunner:
    build: automation
    profiles:
      - e2e
  test:
    build:
      context: .
      target: testimage
    profiles:
      - tst
    depends_on:
      - postgres
      - coverage
  coverage:
    build:
      context: .
      target: coverage
    entrypoint: /usr/bin/tail -f /dev/null
    profiles:
      - tst
      - e2e
  hub:
    image: ${SELENIUM_HUB_IMAGE:-selenium/hub:3.141.59-20210913}
    profiles:
      - e2e
  chrome:
    image: ${SELENIUM_CHROME_IMAGE:-selenium/node-chrome-debug:3.141.59-20210913}
    profiles:
      - e2e
    depends_on:
      - hub

  s3:
    image: minio/minio
    profiles:
      - dev
    command: server /data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
```

**Describe the results you received:**

```
akemeny-l1:gallery akemeny$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile dev config --profiles
dev
e2e
tst
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml config --services
web
postgres
testrunner
coverage
test
hub
chrome
s3
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile e2e config --services
web
postgres
testrunner
coverage
test
hub
chrome
s3
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile tst config --services
web
postgres
testrunner
coverage
test
hub
chrome
s3
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile dev config --services
web
postgres
testrunner
coverage
test
hub
chrome
s3
```

**Describe the results you expected:**

```
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile e2e config --services
web
postgres
testrunner
coverage
hub
chrome
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile tst config --services
coverage
test
akemeny-l1:gallery akemeny$ docker-compose -f docker-compose-test.yml --profile dev config --services
web
postgres
s3
```

**Output of `docker-compose --version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 32
  Running: 0
  Paused: 0
  Stopped: 32
 Images: 101
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: S3V2:BANF:6EJE:6ROY:F6TN:PLYL:6QWW:WKTS:O2BE:CPUK:7OSK:JQBZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

Docker For Mac (Deskop 4.0.1 (68347))

**Comment by jgadling** [comment]
I can confirm that `docker-compose config` is entirely broken if the configuration includes profiles:

```
% cat docker-compose.yml
services:
  service1:
    image: "nginx"
    profiles: ["frontend", "web", "all"]
  service2:
    image: "nginx"
    profiles: ["backend", "web", "all"]
% docker-compose --file docker-compose.yml config
services: {}
```

VS:

```
% cat docker-compose-no-profiles.yml
services:
  service1:
    image: "nginx"
  service2:
    image: "nginx"
% docker-compose --file docker-compose-no-profiles.yml config
services:
  service1:
    image: nginx
    networks:
      default: null
  service2:
    image: nginx
    networks:
      default: null
```
