### ISSUE TITLE
Docker compose config does not merge logging options

### ISSUE THREAD

**Issue by mdantonio** [docker/compose#8860]
**Description**

When merging two yaml files the config output does not include additional logging options from the second file

**Steps to reproduce the issue:**
1.
conf1.yml:
```
version: "3.9"
services:
  test:
    image: alpine
    logging:
      driver: syslog
```

conf2.yml:
```
version: "3.9"
services:
  test:
    logging:
      options:
        syslog-address: "tcp://123.123.123.123:123"
```

2. `docker compose -f conf1.yml -f conf2.yml config`

**Describe the results you received:**

```
services:
  test:
    image: alpine
    logging:
      driver: syslog
    networks:
      default: null
networks:
  default:
    name: test_logging_driver_merge_default
```

**Describe the results you expected:**

I expect syslog-address to be included in the output, like it happens with compose v1:

```
services:
  test:
    image: alpine
    logging:
      driver: syslog
      options:
        syslog-address: tcp://123.123.123.123:123
version: '3.9'
```
(from compose 1.29.2)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: in2j3ppqejm98iagbc0om13hm
  Is Manager: true
  ClusterID: tb66btmufs5tz2usthusff2jx
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 127.0.0.1
  Manager Addresses:
   127.0.0.1:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-37-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: ....
 ID: BZEU:SIMV:O2JZ:P6NK:44ZY:3DIN:DCB3:BGLE:MAVY:6DPI:4QLM:3JDT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.43.145:5000
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
This issue is caused by https://github.com/compose-spec/compose-go/blob/6e19c36896282fa9335c4e1ab8e557fc2526a83e/loader/merge.go#L280

As destination is `nil` (first compose file has no logging option set), mergo has no target field to update in the service struct. 
A possible fix is to get `LoggingConfig.Options` initialized to an empty map, or I wonder some mergo voodoo-magic could help here.

**Comment by ndeloof** [comment]
Ugly but possible workaround: set your compose file with: 
```yaml
    logging:
      driver: syslog
      options: {}
```
