### ISSUE TITLE
`read_only` override is ignored by `docker compose`

### ISSUE THREAD

**Issue by zwx00** [docker/compose#8866]
**Description**

I wish to override a service option from `read_only: true` to `read_only: false` in a secondary `docker-compose.yml` file. This does not work anymore, although it worked fine until a recent update.

**Steps to reproduce the issue:**
1. Create two files:

`dc.yml`
```yaml
version: '3.8'

services:
  something:
    image: ubuntu
    read_only: true
```
`dc.override.yml`
```yaml
version: '3.8'

services:
  something:
    image: ubuntu
    read_only: false
```

2. Run `docker compose -f dc.yml -f dc.override.yml config`

**Describe the results you received:**
```
services:
  something:
    image: ubuntu
    networks:
      default: null
    read_only: true
networks:
  default:
    name: reprod-docker_default
```
**Describe the results you expected:**

```
services:
  something:
    image: ubuntu
    networks:
      default: null
    read_only: false
networks:
  default:
    name: reprod-docker_default
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Always reproducible. It works in reverse, eg. `docker compose -f dc.override.yml -f dc.yml config` will result in `read_only: true`, as expected.

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 8
  Running: 3
  Paused: 0
  Stopped: 5
 Images: 21
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: 5Q5R:ZH65:LWZT:ZVRM:Y4CI:YK2X:GE35:OCUM:EZM4:A4ZU:OB62:D63T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

Nothing special.
