### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint odoo_app_web_1 (5630c78e160d618c4f2d824e88dbc6d59be962eedd592bacf971f162789e5050): Error starting userland proxy: listen tcp [::]:8069: bind: address already in use Error: failed to start containers: 4556f2181ae0

### ISSUE THREAD

**Issue by luna9722** [docker/compose#8890]
Hello everybody,
I am trying to deploy my odoo application using docker-compose on ovh vps (on ubuntu version 18.04), I installed docker and docker-compose from the official documentation and simply run docker-compose up -d but I got this error:
![image](https://user-images.githubusercontent.com/48836506/140574287-e0463a40-9883-41f9-98fe-570941e271cb.png)
Here is the file docker-compose.yml
```
version: '3.3'
services:
  web:
    image: odoo:13
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
```
and the netstat command doesn't show me any entry with the port 8069.
I will be grateful if you can help me with this matter.
Thank you
