### ISSUE TITLE
Compose should not exit when container is scheduled for restart 

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#8896]
Compose should know container will restart, and wait for it.

```yaml
services:
  test:
    image: ubuntu
    command: bash -c 'for ((i=1; i <= 10; i++)); do echo $$i; done'
    restart: always
```

## expected behavior:
`docker compose up` to show 1..10 in a loop

## observed behavior:
`docker compose up` only show 1..10 once.
