### ISSUE TITLE
docker-compose V2 depends on is not working anymore

### ISSUE THREAD

**Issue by Mark-CChen** [docker/compose#8910]
**Description**

depends on in docker-compose V2  is not work but worked without V2

**Steps to reproduce the issue:**
1.create a simple compose file contents 
```
              version: '3.9'
              services:
                web:
                  build: .
                  depends_on:
                    - db
                    - redis
                redis:
                  image: redis
                db:
                  image: postgres
```
2.remove  
```
                db:
                  image: postgres
```
3.docker-compose up 

**Describe the results you received:**
```
nothing
```
**Describe the results you expected:**
```
ERROR: Service 'web' depends on service 'db' which is undefined.
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**
```
Docker Compose version v2.0.0
```
**Output of `docker info`:**
```
Docker version v4.1.1
```
**Additional environment details:**
