### ISSUE TITLE
Regression: `docker compose config` does not output portable config anymore

### ISSUE THREAD

**Issue by jpic** [docker/compose#8914]
Previously, `docker-compose config` would output a portable (reusable) config, without names for volumes and networks that are global to docker.

Now, it enforces outputting local volume and network names at the top level networks and volumes hashes of the yaml output:

```
networks:
  default:
    name: ansible5rt8w0cmbuild_default
volumes:
  syncthing:
    name: ansible5rt8w0cmbuild_syncthing
```

Which breaks portability of the configuration generated from `docker-compose config` from a project to another anymore:

- default should not even be there
- volumes that are local to services should probably stay there at the service level

Is there any way to generate a portable config with the new docker compose?

Thank you

**Comment by jpic** [comment]
Worth mentioning another regression, getting `networks: { default: null }` in services as such:

```
services:
  some_service:
    networks:
      default: null
```

docker compose up won't complain about it, but the containers won't see each others.
