### ISSUE TITLE
docker compose V2 (2.1.1) merge environments incorrectly

### ISSUE THREAD

**Issue by ForJobsGit** [docker/compose#8917]
**Description**

docker-compose V2 (2.1.1) incorrectly merge environment variables

**Steps to reproduce the issue:**

`base.yaml`

```
version: '3.8'

services:
  hello:
    image: hello-world
    environment:
      - NAME=BASE
      - VALUE=BASE
```

`dev.yaml`

```
version: '3.8'

services:
  hello:
    environment:
      - NAME=DEV
      - VALUE=
```

`docker compose --file=base.yaml --file=dev.yaml config` vs `docker-compose --file=base.yaml --file=dev.yaml config`

**Describe the results you received:**

`docker compose --file=base.yaml --file=dev.yaml config`

```
services:
  hello:
    environment:
      NAME: DEV
      VALUE: BASE
    image: hello-world
```

**Describe the results you expected:**

as old docker-compose V1
`docker-compose --file=base.yaml --file=dev.yaml config`

```
services:
  hello:
    environment:
      NAME: DEV
      VALUE: ''
    image: hello-world
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

docker-compose version

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
```

docker compose version

```
Docker Compose version v2.1.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 12
  Running: 9
  Paused: 0
  Stopped: 3
 Images: 125
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: jqd5emtz2s4aye9wp3mkcgl9h
  Is Manager: true
  ClusterID: xfbhehn8fumxzhwrn1se62r5a
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: X.X.X.X
  Manager Addresses:
   X.X.X.X:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-89-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.54GiB
 Name: nikonov-Inspiron-5567
 ID: OOO3:EAVO:TMR6:F2BO:XLHG:AAYX:RJSI:NEIT:YZVU:MQAN:R6EZ:I6Q3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
