### ISSUE TITLE
Docker compose and network_mode

### ISSUE THREAD

**Issue by Leliil** [docker/compose#8918]
Hello,

I'm trying to have a docker compose with a container providing the connection to a VPN, and another container using that connection as the network_mode. Here's a minimal example:
```
version: "2.4"
services:
  openvpn:
    image: dperson/openvpn-client
    container_name: openvpn
    network_mode: "bridge"
    privileged: true
    ports:
      - "6687:6687"
    restart: always

  monitorrent:
    image: werwolfby/monitorrent
    container_name: monitorrent
    network_mode: "service:openvpn"
    restart: always
    depends_on:
      openvpn:
        condition: service_healthy
```
When the "openvpn" container is restart, the "monitorrent" container becomes unavailable until you reboot it. How can this situation be corrected?
Sometimes "openvpn" restarts, which I cannot control, so their bundle is not very stable
