### ISSUE TITLE
env vars only read from first dot env file in env files when reference in compose file.

### ISSUE THREAD

**Issue by nickfan** [docker/compose#8932]
**Description**

env vars only read from first dot env file in env files when reference in compose file.

**Steps to reproduce the issue:**

docker-compose.yaml
```
services:
  zookeeper:
    env_file:
      - ../../.env
      - ./.env.app
    restart: unless-stopped
    container_name: zookeeper
    image: zookeeper:3.7
    hostname: ${ZOO_HOSTNAME:-zookeeper}
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
```

../../.env
```
APP_ENV=dev
APP_TIMEZONE=UTC
...
```

./.env.app
```
# zookeeper setup
ZOO_HOSTNAME=myzoo1
ZOO_MY_ID=1
ZOO_SERVERS=
```

check config
```sh
docker-compose config
```

**Describe the results you received:**

```
services:
  zookeeper:
    container_name: zookeeper
    environment:
      APP_ENV: dev
      APP_TIMEZONE: UTC
	hostname: zookeeper
...
```

**Describe the results you expected:**
```
services:
  zookeeper:
    container_name: zookeeper
    environment:
      ZOO_HOSTNAME: myzoo1
	hostname: myzoo1
...
```

i have to define ZOO_HOSTNAME env var in first dot env file: in ../../.env
to make 
```
hostname: ${ZOO_HOSTNAME:-zookeeper}
```
get the variable value.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
 docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-162-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.83GiB
 Name: axsv3
 ID: KDNH:6BWC:WHIG:YIB7:HAFL:RFWT:MBFV:Q2H2:ZSAL:FTO2:DKCW:2Z7T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://registry.docker-cn.com/
  https://reg-mirror.qiniu.com/
  https://docker.mirrors.ustc.edu.cn/
  https://dockerhub.azk8s.cn/
  https://hub-mirror.c.163.com/
 Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details:**
