### ISSUE TITLE
Docker Compose would not update images even the tag :latest ist set

### ISSUE THREAD

**Issue by pthoelken** [docker/compose#8951]
Dear Community, 

latest Version of Compose, and running on Ubuntu 2104

simple problem: I'm using the tag :latest in some docker-compose files and the container / images would not be updated even there is a new version on dockerhub available. 

- `sudo docker stop containerxy`
- `sudo docker-compose up -d`

- The container is not updated but their a new version available on dockerhub (5 days ago)

For example this container:
```
version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Berlin
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./database/db_init/:/docker-entrypoint-initdb.d/
      - /data/database/db_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
```

But when I stop the container manually, make a force remove from image, the container will be pull the new image and recreate it. But I don't think this is the right way to do?
