### ISSUE TITLE
docker compose support for AWS Fargate ARM64

### ISSUE THREAD

**Issue by thorfi** [docker/compose#8958]
**Description**

AWS have just announced support for ARM64 in Fargate:

https://aws.amazon.com/about-aws/whats-new/2021/11/aws-fargate-amazon-ecs-aws-graviton2-processors/

It would be good to have docker compose auto detect platform linux/arm64 and include CpuArchitecture: ARM64 chunk in the CloudFormation template. Right now I'm doing this manually in the x-aws-cloudformation overlay section.

```
x-aws-cloudformation:
  Resources:
    FooTaskDefinition:
      Properties:
        RuntimePlatform:
          CpuArchitecture: ARM64
```
