### ISSUE TITLE
Restart Doesn't Use env_file Configuration

### ISSUE THREAD

**Issue by Fosol** [docker/compose#8979]
When a service restarts due to some kind of failure it will not read the `env_file` to reapply the port configuration.

```yaml
version: "3.5"

services:
  ####################### Database #######################
  database:
    container_name: ce-database
    restart: on-failure:1
    build:
      context: db/mssql
    env_file:
      - db/mssql/.env
    ports:
      - ${DATABASE_PORT:-5433}:1433
    volumes:
      - ce-database-data:/var/opt/mssql
    networks:
      - ce
 ```

Configuration `.env` file.

```conf
DATABASE_PORT=10000
```

```bash
docker-compose  --env-file .env up -d
````

The first time the service starts it correctly applies the configured port in the `.env` file.  After a failure of some kind (hard to tell presently as I can't get error logs out of it) it restarts with the default configured `5433` port.

It should restart with the originally configured port from the `.env` file.  Otherwise restarting is pointless.
