### ISSUE TITLE
When running docker-compose, files get overriden

### ISSUE THREAD

**Issue by jithkaringada-corp** [docker/compose#9001]
I have the following set up:
docker-compose.yaml
```
version: '3.8'
services:
  db:
    build: postgres
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - YENZADB_USER
      - YENZADB_PASSWORD
    ports:
      - "5432:5432"
  keycloak:
    build: keycloak
    restart: always
    environment:
      - X509_CA_BUNDLE=/var/opt/ca_chain.pem
      - DB_VENDOR
      - DB_ADDR=db
      - DB_DATABASE
      - DB_USER
      - DB_SCHEMA
      - DB_PASSWORD
#      - KEYCLOAK_USER
#      - KEYCLOAK_PASSWORD
      - JDBC_PARAMS='ssl=true&sslmode=verify-full&sslcert=/var/opt/dbclient_cert.pem&sslkey=/var/opt/dbclient_key.pem&sslrootcert=/var/opt/ca_chain.pem'
    ports:
      - 8999:8080
    depends_on:
      - db

```
Dockerfile
```
FROM quay.io/keycloak/keycloak:15.0.2
COPY ./clientcerts /var/opt/
COPY ./imports /var/opt/imports
USER root
RUN chown -R jboss:jboss /var/opt && \
    chmod 777 /var/opt/ca_chain.pem && \
    chmod 600 /var/opt/dbclient_key.pem && \
    chmod og-rwx /var/opt/dbclient_key.pem
USER jboss
RUN file="$(ls -al /var/opt)" && echo $file
RUN cat /var/opt/ca_chain.pem
CMD [ "-b", "0.0.0.0", \
"-Dkeycloak.frontendUrl=https://keycloak.yenzara.ngrok.io/auth", \
"-Dkeycloak.migration.strategy=IGNORE_EXISTING", \
"-Dkeycloak.migration.action=import",\
"-Dkeycloak.migration.dir=/var/opt/imports"]
```

The folder structure is:
![image](https://user-images.githubusercontent.com/7771663/144846208-b390efaa-070f-450e-bbfb-b60290d90d11.png)

When I run docker-compose, the keycloak container starts and it should be seeing the certificate files however, as you can see it does not find the file:
![image](https://user-images.githubusercontent.com/7771663/144846655-4eb84f71-e61d-4e4e-b2a1-41c7e14fef0f.png)

Why I think it is my docker file and docker-compose set up is, when I manually run a container from the image that is created by docker-compose, in interactive shell, I can see the files in the docker container.

![image](https://user-images.githubusercontent.com/7771663/144848018-82c407ed-157f-4248-ae18-e69d9a00e8eb.png)

Don't mind the file names for the cert and key files. I have been messing with those, but always made sure to align them with the JDBC_PARAMS. The ca_chain.pem is the main issue here i.e. that when I run with docker-compose up, this file path does not seem to exist.
