### ISSUE TITLE
Inline comments in `.env`

### ISSUE THREAD

**Issue by zhao-li** [docker/compose#9025]
**Description**
Inline comments in my `.env` file used to be ignored properly, but now they are getting sucked into `docker-compose.yml` configurations and is causing errors.

Is this a new feature or the expected behavior going forward?  I couldn't find anything new in the documentation.

Thank you for any help or guidance 🙏

**Steps to reproduce the issue:**
1. run `docker-compose build`

**Describe the results you received:**
Docker Compose errors out with:
```
1 error(s) decoding:

* error decoding 'Ports': Invalid containerPort: 8080 # inline comment no longer working
```

**Describe the results you expected:**
The container should get built/pulled properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.36GiB
 Name: docker-desktop
 ID: WX5R:W64V:3QST:M5F3:3U54:K63Y:PGYJ:QPAM:2HSF:JS34:HVYI:RWEJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
`docker-compose.yml`:
```
services:
  app:
    image: nginx
    ports:
      - ${APP_PORT}
```
`.env`:
```
APP_PORT=8080 # inline comment no longer working
```

**Comment by Adri1C** [comment]
I am experimenting the same issue, with `Docker compose v2.2.1` in `Docker Desktop 4.3.0` on Windows.
Comment following an env. variable declaration are no longer ignored when building the container (file is utf8 encoded).

However I admit that [the documentation mentions comment as "Lines beginning with #"](https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file). It was convenient though 😕

**Comment by ulyssessouza** [comment]
This should be resolved with https://github.com/compose-spec/godotenv/pull/14

**Comment by zhao-li** [comment]
Thanks @ulyssessouza for the info and making the pull request.  Sorry, I'm not familiar with how the project is organized.  I was not able to find which version might be including the pull request.  Would you happen to know what docker compose version will be including this pull request?  Thanks again 🙏

**Comment by ulyssessouza** [comment]
@zhao-li in the next one. Can be a `v2.2.4` or a `v2.3.0` but most probably the first.

**Comment by zhao-li** [comment]
Thanks @ulyssessouza for the versions.  I can't wait to test it out 🦦

**Comment by LeviPesin** [comment]
Seems like this issue happens again in Docker Compose 2.19.0.

I have this `docker-compose.yml` file:
```
services:
  proxy:
    image: $TEST_IMAGE
    ports:
      - "80:80"
      - "443:443"
    env_file: ../test.env
    volumes:
      - ./ssl:/ssl:ro
      - ./static:/static:ro
    tmpfs: /dumps

  backend:
    image: node
    user: node
    working_dir: /home/node/app
    environment:
      - BACKEND_PORT=8191
      - WEBSOCKET_PORT=8192
    volumes:
      - ../:/home/node/app:ro
    expose:
      - 8191
      - 8192
    command: npm run start-backend
```

And here are some lines of `../test.env`:
```

NGINX_MULTI_ACCEPT=off # on or off

NGINX_POSTPONE_OUTPUT=1448 # ideally should be Maximum Segment Size
```

They are transformed into environment variables with values `off # on or off` and `1448 # ideally should be Maximum Segment Size`, while should be just `off` and `1448`.
