### ISSUE TITLE
[Feature Request] docker compose tag --template "template" --push

### ISSUE THREAD

**Issue by abdennour** [docker/compose#9051]
**Description**

I would like to tag my built images, then, optionally, push these tags.
In CI environment, image tags are auto-calculated, and CI has to do some governance regardless the YAML definition of `.services{}.image`

**Poposal**
Adding subcommand `docker compose tag` with the following options:
- `--template string`:  the tag template which can leverage the following variables :
       - `{{ .ServiceName }}` - service name under tagging
       - `{{ .ProjectName }}` - compose project name
       - `{{ .ServicesCount }}` - Total number of services
       - `{{ .ServicesToBuildCount }}` - Total number of services to build
- `--push`: whether to push the new tag(s) or just tagging

i.e. 
```sh
docker compose tag --template "myregistry.local/myrepo/{{ .ServiceName }}:v1" --push 
```

**Scenario 1**

Given a docker-compose file as following:
```yaml
version: "3.9"
services:
  frontend:
    build: frontend/
    ports:
     -  9090:80
  backend:
    build: backend/
    ports:
     - 8080:80
    image: mybackend:v1
  db:
    image: mysql
```

And given this script (After implementing this feature)

```sh
VERSION=v1.2.3
APP=myapp
docker compose tag --template "nexus.local/myrepo/{{ if eq .ServicesToBuildCount 1}}$APP{{ else }}$APP-{{ .ServiceName }}{{ end }}:$VERSION" --push
```
Results:
- New image tag with name `nexus.local/myrepo/myapp-frontend:v1.2.3` is created & pushed
- New image tag with name `nexus.local/myrepo/myapp-backend:v1.2.3` is created & pushed
