### ISSUE TITLE
network attachment ineffective for services created concurrently (i.e. race condition)

### ISSUE THREAD

**Issue by brainchild0** [docker/compose#9054]
*A search of tracked issues reveals many potentially related issues.*

*It is unclear whether this issue duplicates any still open. It is clear that Docker Compose has had race conditions, some having been resolved, but also it is clear that an issue persists, represented by the following test case.*

# Summary

If two containers, attached to the same network, are created in parallel, then after both concurrent creation operations have completed, the effect is as though the containers are not attached to the same network.

# Test case

Begin by taking the following trivial network defined in a `docker-compose.yaml`:

```yaml
version: "3.0"

networks:
  basic:

services:

  client:
    image: alpine
    entrypoint: "tail -f"
    networks:
      basic:
          aliases:
            - client.nowhere.fake
    domainname: client.nowhere.fake

  server:
    image: alpine
    entrypoint: "tail -f"
    networks:
      basic:
          aliases:
            - server.nowhere.fake
    domainname: server.nowhere.fake
```

The problem may be reproduced by running the following script in the same directory:

```bash
#!/bin/bash

sequential_test() {

    echo "  [test] Starting sequential test"

    docker-compose up -d server
    docker-compose up -d client

    if ! ( docker-compose exec client nslookup server.nowhere.fake \
			  > /dev/null 2>&1 ); then
        echo "  [test] Domain lookup failed"
        echo "  [test] Sequential test failed"
    elif ! ( docker-compose exec client ping -c4 -q server.nowhere.fake \
			    > /dev/null 2>&1 ); then
        echo "  [test] Ping failed"
        echo "  [test] Sequential test failed"
    else
        echo "  [test] Sequential test succeeded"
    fi

    docker-compose down

}

parallel_test() {

    echo "  [test] Starting parallel test"

    parallel --will-cite -n2 bash -c <<<'
        docker-compose up -d server
        docker-compose up -d client'

    sleep 5

    if ! ( docker-compose exec client nslookup server.nowhere.fake \
			  > /dev/null 2>&1 ); then
        echo "  [test] Domain lookup failed"
        echo "  [test] Parallel test failed"
    elif ! ( docker-compose exec client ping -c4 -q server.nowhere.fake \
			    > /dev/null 2>&1 ); then
        echo "  [test] Ping failed"
        echo "  [test] Parallel test failed"
    else
        echo "  [test] Parallel test succeeded"
    fi

    docker-compose down

}

docker-compose build

sequential_test

parallel_test

```

The results are as follows:

```
client uses an image, skipping
server uses an image, skipping
  [test] Starting sequential test
Creating network "compose-net-test_basic" with the default driver
Creating compose-net-test_server_1 ... done
Creating compose-net-test_client_1 ... done
  [test] Sequential test succeeded
Stopping compose-net-test_client_1 ... done
Stopping compose-net-test_server_1 ... done
Removing compose-net-test_client_1 ... done
Removing compose-net-test_server_1 ... done
Removing network compose-net-test_basic
  [test] Starting parallel test
Creating network "compose-net-test_basic" with the default driver
Creating compose-net-test_server_1 ... done
  [test] Domain lookup failed
  [test] Parallel test failed
Stopping compose-net-test_server_1 ... done
Removing compose-net-test_server_1 ... done
Removing network compose-net-test_basic
```

# Notes

The `sleep` command imposes a time buffer that should be adequate for any pending operations to resolve. Adjusting the duration has had no affect on results.

# Environment

I have tested with **Docker 20.10.7** and **Docker Compose 1.25.0**, running under **Linux Mint 20.2**.
