### ISSUE TITLE
Variable interpolation from .env files differs in v2 from v1, when processing $ followed by capital letter

### ISSUE THREAD

**Issue by dellagustin-sap** [docker/compose#9060]
**Description**

When a variable defined in `.env` file contains a `$` symbol followed by a capital letter(s), v1 is going to ignore it, escaping the `$` symbol, while v2 will try to resolve it as a variable.

It is possible to escape the $ symbol in v2 with a `\`, but this will then not work on v1, making it impossible to have a single `.env` file that works on both v1 and v2.

Sample code:

`.env`
```
S=TEST
DOCKER_TEST_VARIABLE1=textwith\$Symbol
DOCKER_TEST_VARIABLE2=textwith$Symbol
```

`docker-compose.yml`
```yml
version: '3.8'
services:
    testservice:
        image: hello-world
        environment: 
            - TEST_VARIABLE1=${DOCKER_TEST_VARIABLE1}
            - TEST_VARIABLE2=${DOCKER_TEST_VARIABLE2}
```

**Steps to reproduce the issue:**
1. `docker compose config`
2. `docker-compose config`
3. compare the results

**Describe the results you received:**

`docker-compose config` (v1):
```yml
services:
  testservice:
    environment:
      TEST_VARIABLE1: textwith\$$Symbol
      TEST_VARIABLE2: textwith$$Symbol
    image: hello-world
version: '3.8'
```

`docker compose config` v2:
```yml
services:
  testservice:
    environment:
      TEST_VARIABLE1: textwith$$Symbol
      TEST_VARIABLE2: textwithTESTymbol
    image: hello-world
    networks:
      default: null
networks:
  default:
    name: docker-compose-variable-interpolation_default
```

When `S=TEST` is not set, it will resolve to empty.

**Describe the results you expected:**

`docker compose config` v2:
```yml
services:
  testservice:
    environment:
      TEST_VARIABLE1: textwith\$$Symbol
      TEST_VARIABLE2: textwith$$Symbol
    image: hello-world
    networks:
      default: null
networks:
  default:
    name: docker-compose-variable-interpolation_default
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose -v`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., v0.11.0)

Server:
 Containers: 22
  Running: 0
  Paused: 0
  Stopped: 22
 Images: 252
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: PXBK:YR44:TSZK:576N:AUAH:NR6D:VZTN:54QH:LT4X:TLQ2:VZTI:Z7RK
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 45
  Goroutines: 48
  System Time: 2021-12-22T10:02:14.358685928Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
