### ISSUE TITLE
Docker-compose hangs sometimes on stopping

### ISSUE THREAD

**Issue by MCWertGaming** [docker/compose#9062]
Docker hangs on some docker-compose deployments while stopping the containers.

**Steps to reproduce the issue:**
1. Create docker-compose.yml
2. docker-compose up
3. Press CTRL+C

**Describe the results you received:**

On some files, the container is normally stopping. On some, docker-compose hangs and I have to send a kill message. Repeating CTRL+C is giving the error that there was a error while killing the container. Then nothing happens and docker-compose is only exiting if I send a kill signal (sigkill) manually.

**Describe the results you expected:**

docker-compose should just exit.

**Additional information you deem important (e.g. issue happens only occasionally):**

The container is already stopped while docker-compose hangs. Also it happens only with some compose files. See below for examples.

**Output of `docker compose version`:**

```
Docker Compose version 2.2.2
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.2)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc version: v1.0.3-0-gf46b6ba2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.19-2-pve
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 512MiB
 Name: adguard
 ID: 2BBJ:VZEI:GLZO:MH2Z:NUFA:CV5W:A4LL:UPQU:VRF6:LYDS:KW66:CKI3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

OS: Archlinux

The working compose file:
```yml
version: "3"

services:
  step-ca:
    image: smallstep/step-ca
    container_name: step-ca
    restart: unless-stopped
    ports: 
      - 443:443
    volumes:
      - step:/home/step

volumes:
  step:
    external: true
```

The compose file that causes my issues:
```yml
version: "3"

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    ports: 
    - 10.10.11.21:53:53/tcp     # Plain DNS
    - 10.10.11.21:53:53/udp     # Plain DNS
    - 10.10.11.21:80:80/tcp     # re routing http to https
    - 10.10.11.21:3000:3000/tcp # Web interface
    volumes:
      - adguard_conf:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work

volumes:
  adguard_conf:
    external: true
  adguard_work:
    external: true
```
