### ISSUE TITLE
Control+C after `docker compose up` is stuck, not returning

### ISSUE THREAD

**Issue by nitwhiz** [docker/compose#9065]
**Description**

**Steps to reproduce the issue:**
1. Create the following docker-compose.yml:
  ```yaml
version: '3.7'

services:

  db:
    image: postgres:14.1-alpine3.14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

networks:
  db:

  ```
2. Run `docker compose up`
3. Press Control+C to stop the containers

**Describe the results you received:**

```
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 2/2
 ⠿ Container server-db-1       Stopped       0.3s
 ⠿ Container server-adminer-1  Stopped       0.3s
```

(this stays there, it's not returning to my shell prompt)

After pressing Control+C again:

```
[+] Running 0/0
 ⠿ Container server-adminer-1  Error while Killing       0.0s
 ⠿ Container server-db-1       Error while Killing       0.0s
```

(this stays there, it's still not returning to my shell prompt)

After pressing Control+C a third time:

```
^CERRO[0196] got 3 SIGTERM/SIGINTs, forcing shutdown
```

**Describe the results you expected:**

After pressing Control+C once, my containers are stopped and I'm dropping back to my shell prompt.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens always.

**Output of `docker compose version`:**

```
Docker Compose version v2.2.2
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.2.2)

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc version: v1.0.3-0-gf46b6ba2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.84-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.63GiB
 Name: *******-manjaro-pc
 ID: DYKS:VGPZ:RIJL:VBJY:Q4XC:NI55:OCXM:CZHU:XI2W:JBX3:EJTU:PJPW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: *******
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

- _I'm using Arch btw_
