### ISSUE TITLE
`docker compose config` dumps env_file variables + env_file directive

### ISSUE THREAD

**Issue by Neirda24** [docker/compose#9084]
**Description**

We sometimes need to merge several docker-compose files to "merge" them using the `config` output. Although before (v1) it was dumping the env variables without the `env_file` directive, it seems now that it is dumping both. Which I can't see the point. I think it would be nice to keep the `env_file` without having those dumped inside `environment`.

**Steps to reproduce the issue:**

Given the following `docker-compose.yml` file :

```yaml
version: '3.8'
services:
    mysql:
        image: 'mysql:5.7'
        restart: 'unless-stopped'
        volumes:
            -
                type: 'volume'
                source: 'mysql'
                target: '/var/lib/mysql'
        tty: true
        env_file:
            - './mysql.env'

volumes:
    mysql:
```

run `docker compose config`

**Describe the results you received:**

```yaml
services:
  mysql:
    environment:
      LC_ALL: C.UTF-8
      MYSQL_DATABASE: xxxxxx
      MYSQL_PASSWORD: xxxxxx
      MYSQL_ROOT_PASSWORD: xxxxxx
      MYSQL_USER: xxxxxx
    env_file:
    - ./mysql.env
    image: mysql:5.7
    networks:
      default: null
    restart: unless-stopped
    tty: true
    volumes:
    - type: volume
      source: mysql
      target: /var/lib/mysql
networks:
  default:
    name: app_default
volumes:
  mysql:
    name: app_mysql
```

**Describe the results you expected:**

```yaml
services:
  mysql:
    env_file:
    - ./mysql.env
    image: mysql:5.7
    networks:
      default: null
    restart: unless-stopped
    tty: true
    volumes:
    - type: volume
      source: mysql
      target: /var/lib/mysql
networks:
  default:
    name: app_default
volumes:
  mysql:
    name: app_mysql
```

Having both the environment dumps into it + the env_file seems weird.  We sometimes need to "merge" several docker-compose files using multiple `-f` + config and dump it in a file that will be used... If environments variable are directly dumped into it, it freeze things.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
$ docker compose version
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., v0.14.0)

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 6.789GiB
 Name: docker-desktop
 ID: JCS5:OYWQ:MNPL:X4UG:4VYJ:VVJG:LO3K:WQ6D:MNB3:X6Z6:IKGM:YAOE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
