### ISSUE TITLE
feature: compose config should purge nested x-* tags 

### ISSUE THREAD

**Issue by hholst80** [docker/compose#9090]
### Version
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

### Description

`docker-compose config` should purge nested x-fields

### Design idea

input

```yaml
version: '2'

x-common: &common
  volumes: &common-volumes
  - /data:/data
  x-volumes: &common-cache-volumes
  - /data:/data
  - /cache:/cache

services:
  service-foo:
   <<: *common
   image: docker.io/hello-world:latest
```

Expected output:

```yaml
$ docker-compose config
version: '2'
services:
  service-foo:
    image: docker.io/hello-world:latest
    volumes:
    - /data:/data:rw
```    

Actual output:

```yaml
services:
  service-foo:
    image: docker.io/hello-world:latest
    volumes:
    - /data:/data:rw
    x-volumes:
    - /data:/data
    - /cache:/cache
version: '2'
```
