### ISSUE TITLE
[Feature] Remap ports to "nowhere"

### ISSUE THREAD

**Issue by svoop** [docker/compose#9112]
There are a number of questions like "how can I unexpose a port" out there, the way to go being a fork of the upstream Dockerfile. Would it be possible to extend compose to allow remapping of such ports to "nowhere", say:

```
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    (...)
    port:
      - "9922:9922"    <- custom port for git via ssh
      - "9980:9980"    <- custom port picked up by the reverse proxy
      - ":22"          <- remap port 22 from Dockerfile to "nowhere" 
      - ":80"          <- remap port 80 from Dockerfile to "nowhere"
      - ":443"         <- remap port 443 from Dockerfile to "nowhere"
      (...)
```

This is a real life example: The [GitLab omnibus image](https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/docker/Dockerfile) exposes ports 80, 443 and 22 by default. When using this image behind a reverse proxy on the host, these ports are not needed and might cause trouble with other processes on the host.

Unfortunately, it's not possible to remap these default ports e.g. with "9922:22". While this would rid of the unneeded exposed ports, the dockerized GitLab would then use port 22 on all rendered git via ssh URLs which breaks them.

(Ugly workaround: Remapping the unneeded ports to random high port numbers which are less likely to cause trouble on the host e.g. "44422:22".)

**Comment by ndeloof** [comment]
If you define service without `port` to declare target port 22, container won't publish this port to the host, even the docker image declare this port as exposed.
This is the same as running `docker run gitlab/gitlab-ce:latest` without `-P`: no host port will be allocated and mapped to container's exposed ports 22,80,443

**Comment by svoop** [comment]
@ndeloof Thanks for your reply, however, I'm not sure to understand.  Given the Dockerfile with:

```
EXPOSE 443 80 22
```

And the docker-compose.yml with:

```yml
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    (...)
    port:
      - "9922:9922"
      - "9980:9980"
      (...)
```

The container exposes the ports from the Dockerfile:

```
acde1584082e   gitlab/gitlab-ce:latest       "/assets/wrapper"        About a minute ago   Up About a minute (healthy)   22/tcp, 80/tcp, 0.0.0.0:9922->9922/tcp, :::9922->9922/tcp, 443/tcp, 0.0.0.0:9980->9980/tcp, :::9980->9980/tcp   gitlab_web_1
```

Removing `port` is not an option, I have to expose 9980 (for the reverse proxy) and 9922 (for git via ssh).
