### ISSUE TITLE
Command list from multiple files do not get merged

### ISSUE THREAD

**Issue by petrprikryl** [docker/compose#9138]
**Description**

I have tried list _command_ definition in multiple files. But the _command_ is not being merged. It is overrieded.

**Steps to reproduce the issue:**

base.yml

```yaml
version: '3.7'

services:
  traefik:
    image: traefik:v2.6
    command:
      - --api
      - --log
      - --accesslog
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      - --entrypoints.web.address=:80
```

extended.yml

```yaml
version: '3.7'

services:
  traefik:
    command:
      - --entrypoints.web.forwardedHeaders.insecure
```

**Describe the results you received:**

```
$ docker-compose -f base.yml -f extended.yml config
services:
  traefik:
    command:
    - --entrypoints.web.forwardedHeaders.insecure
    image: traefik:v2.6
version: '3.7'
```

**Describe the results you expected:**

```
$ docker-compose -f base.yml -f extend.yml config
services:
  traefik:
    command:
    - --entrypoints.web.forwardedHeaders.insecure
    - --api
    - --log
    - --accesslog
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --providers.docker.swarmMode=true
    - --entrypoints.web.address=:80
    image: traefik:v2.6
version: '3.7'
```

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 8tc9geqoluipe0v78i5erfc0v
  Is Manager: true
  ClusterID: 1s7uijcx5zhzczskpmg09opcw
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.16.0.164
  Manager Addresses:
   172.16.0.164:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.0-23-generic
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.15GiB
 Name: petrprikryl-Z590M
 ID: 5ZWC:LRYN:PIH6:7XZS:N7QD:H3UE:2NNQ:JMMD:EUKG:XLA5:VD4O:DE4K
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
