### ISSUE TITLE
What mean 'unsupported external secret'?

### ISSUE THREAD

**Issue by evorios** [docker/compose#9139]
subj

**Comment by draksha22** [comment]
Hey @evorios can you please elaborate what is your issue?

**Comment by evorios** [comment]
I run following commands and get described error:
```
docker swarm init
docker secret create ./src/my_secret
```

`./src/my_secret` contain only bytes.

Enviroment: win10

**Comment by ulyssessouza** [comment]
@evorios From `docker secret create --help`:
```
Usage:  docker secret create [OPTIONS] SECRET [file|-] 
...
```

So it looks like your command is missing the secret's name before the file.

**Comment by evorios** [comment]
Sorry, my bad. Executed command looks like:
`docker secret create my_secret ./src/my_secret`

**Comment by vivekvedant** [comment]
### Description: 
Unable to added external secrets using docker-compose 

### Output of error
![image](https://user-images.githubusercontent.com/38762444/160899092-3d5ea291-7823-48c0-9b36-ecb965a96711.png)

##Output of secrets in docker
![image](https://user-images.githubusercontent.com/38762444/160899649-18349b36-6898-452c-8dd0-5404668319b2.png)

### container containing secrets
```
grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    volumes:
      - ./monitoring/grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER_FILE=/run/secrets/grafana_username
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_password
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    depends_on:
      - prometheus
      - caddy
      - pushgateway
      - cadvisor
      - nodeexporter
    labels:
      org.label-schema.group: "monitoring"
    secrets:
      - grafana_username
      - grafana_password
secrets:
  grafana_username:
    external: true
  grafana_password:
    external: true
```
