### ISSUE TITLE
declared 2 containers in fig.yml, but sudo docker ps shows only one of them

### ISSUE THREAD

**Issue by bitliner** [docker/compose#914]
I have a fig.yml like this:

```
db:
  image: tutum/mysql
  volumes:
    - data/:/var/lib/mysql
  environment:
    - ...=...
  ports:
    - 8091:3306
wp:
  build: .
  ports:
    - 8092:80
  links:
    - db:mysql
  volumes:
    - wordpress/:/var/www/html/
  environment:
    - ...=...

```

but if I run `sudo docker ps` after `sudo fig up` only the second container is started.
