### ISSUE TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:27017: bind: address already in use

### ISSUE THREAD

**Issue by abhalawat** [docker/compose#9140]
I am first time user of docker compose.
I wanted to create mongo and mongo-express containers through docker compose.
the code used is:-

```
version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
```
before this I ran the command:-
```
docker pull mongo
docker pull mongo-express
docker network create mongo-network
```
and this is error I am receiving:

ERROR: for mongodb  Cannot start service mongodb: driver failed programming external connectivity on endpoint erc20_token_mongodb_1 (c3419fec9d3736929fa2f9c5d35f87b7f5e2880779e1950283e65415feff8b99): Error starting userland proxy: listen tcp4 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.

How should I resolve this
