### ISSUE TITLE
Set name for volume

### ISSUE THREAD

**Issue by lokzzor** [docker/compose#9186]
Hello, tell me how to explicitly set a name for volume

**My code**
```
version: '3.8'
services:
    composer:
        image: composer
        container_name: composer
        volumes:
            - .:/app
        command: install
    db:
        image: postgres:12.4
        container_name: container
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
```
I will be very grateful for your help
