### ISSUE TITLE
extra_hosts not work

### ISSUE THREAD

**Issue by se7enXF** [docker/compose#9187]
I am using portainer to manage docker, and using stack in portainer with compose-file to start container. 
The container was started successfully, but the host was not modified. Inspect the container, ExtraHosts args do exist. 
It seems that the container does not automatically append extra_host to the hosts file when it starts.  

Here is my environments:  
* portainer: 2.11.0  
* docker: 20.10.3
* compose-file in standalone type (not swarm):  
```
version: "3.7"
services:
  app:
    image: some-image                                       
    volumes:
      - "/etc/hosts:/etc/hosts"
    extra_hosts:
      - "some-host:ip"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: always 
```
If I use `docker run --add-host` it works will. But now I need to use compose-file. 
I need the hosts in hosted and the extra hosts. `/etc/hosts` must be mounted in container, then append the extra_hosts in `/etc/hosts`.
What's the problem in my work? Help me plz.
