### ISSUE TITLE
Documented syntax for GPU access does not work

### ISSUE THREAD

**Issue by sgsunder** [docker/compose#9190]
**Description**

Attempting to enable container GPU access in the compose file, as per the documentation, fails with a syntax error

Snippet of compose file:

```yaml
version: '3.3'
networks:
  webapp:
    external: true
# ...
services:
  plex:
    image: ghcr.io/linuxserver/plex
    # ---- START PROBLEM CODE ----
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    # ---- END PROBLEM CODE ---- 
    depends_on:
      - oneshot
    networks:
      - webapp
    ports:
      # access to the Plex Media Server, required
      - 32400:32400/tcp
      # Plex Companion
      - 3005:3005/tcp
      # access to the Plex DLNA Server
      - 32469:32469/tcp
      - 1900:1900/udp
      # current GDM network discovery
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      # <REDACTED>
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
      # <REDACTED>
    labels:
      # <REDACTED>
    logging:
      driver: json-file
      options:
        max-size: "20k"
        max-file: "3"
```

Attempting to start this service yields the following:
```shell
$ sudo docker-compose up -d plex
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.plex.deploy.resources.reservations value 'devices' does not match any of the regexes: '^x-'
```

However, commenting out the entire deploy section of the compose file works fine, and the container starts and functions as expected. Of course, I wouldn't be able to get the GPU access like I desired in this case.

I configured my compose file according to this documentation: https://docs.docker.com/compose/gpu-support/
Could be possible that I'm being stupid and it is genuinely a syntax error on my part, but I don't see it.

**Output of `sudo docker-compose version`:**

```
docker-compose version 1.27.4, build unknown
docker-py version: 4.4.4
CPython version: 3.9.7
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
```

**Output of `sudo docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 15
  Running: 15
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.0-28-generic
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.59GiB
 Name: <REDACTED>
 ID: <REDACTED>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
Output of `sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro K620         Off  | 00000000:01:00.0 Off |                  N/A |
| 34%   29C    P8     1W /  30W |      1MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

OS is Ubuntu Server 21.10
