### ISSUE TITLE
Official `docker/setup-compose` GitHub Action

### ISSUE THREAD

**Issue by felipecrs** [docker/compose#9196]
It would be very nice to have a `docker/setup-compose` GitHub Action to use in CI. The installation isn't so simple anymore, it consists of:

- Downloading the `compose` binary to the plugins folder
- Downloading the `compose-switch` binary as `docker-compose` for backwards compatibility

And furthermore, as a way to keep up to date (or no, to control the exact version) used in CI.

Here's an example of an workflow:

```yaml
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: github/action-checkout@v2
      - uses: docker/setup-compose@v1
      - run: npm install
      - run: docker compose up database --wait
      - run: npm run tests:e2e # which depends on database up and running
```

And of course, much more.
