### ISSUE TITLE
Provide global configuration 

### ISSUE THREAD

**Issue by Vad1mo** [docker/compose#920]
Some docker options can be set on each container and also on a global level in the docker daemon.

Examples: --dns,  dns_search, -r ...

It would be handy if docker-compose would also have such an option on global level:

Example:
```
docker_compose_global:
  dns_search: .docker
  dns: 172.17.42.1

dnsdock:
  image: tonistiigi/dnsdock
  hostname: dnsdock
  command: -ttl=30
  privileged: true
  restart:  always
  ports:
    - "8080:80"
    - "172.17.42.1:53:53/udp"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

mongodb:
  image: mongo
  command: mongod --smallfiles
  hostname: mongodb
  restart:  always
  volumes:
    - /mnt/sda1/data/db:/data/db
...
```

**Comment by docteurklein** [comment]
use could try to use native features of yaml: anchors.

**Comment by Starefossen** [comment]
Also, this is not truly global, as it is only "global" for one compose configuration.

**Comment by dnephin** [comment]
There are now two ways to solve this [yaml aliases and anchors](http://rhnh.net/2011/01/31/yaml-tutorial), and [extends](http://docs.docker.com/compose/yml/#extends)

**Comment by docteurklein** [comment]
@dnephin wouldn't anchored hashes be considired as services?

**Comment by dnephin** [comment]
You would have to put the anchor in the first service which defines them, yes. You couldn't have them sitting outside of a service definition

**Comment by docteurklein** [comment]
having an `services` key in yaml could open cool features:

``` yaml

services:
    db:
        <<: *defaults
    api: {}

my_reusable_config: &defaults

```
