### ISSUE TITLE
Local Env Variable Syntax error, Persisit %Userprofile% folder volume

### ISSUE THREAD

**Issue by abelkbil** [docker/compose#9204]
Hi all,
I am searching on how to persist user profile folder in volume mounting

I have folder C:\Users\ABEL\source\repos which needs to be persisted for a windows container. The username should be from the host. It is unknown.

Below is my docker-compose file, The volume section is not correct.
Any comments will be helpful. Thanks in advance

```
version: '3.4'

services:
  directoryservice:
    image: ngt-directoryservice:latest
    build: .
    ports:
      - "44309:44309"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44309;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=welcome123#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./devops/https/ngtcert.pfx:/https/aspnetapp.pfx:ro
      # - "$env:USERPROFILE/source:$env:USERPROFILE/source"
      - ${Env:USERPROFILE}\source:${Env:USERPROFILE}\source
```

I get below error

`invalid interpolation format for services.directoryservice.volumes.[]: "${Env:USERPROFILE}\\source:${Env:USERPROFILE}\\source". You may need to escape any $ with another $.`
