### ISSUE TITLE
docker-compose v2 incompatible volume handling

### ISSUE THREAD

**Issue by everflux** [docker/compose#9212]
**Description**
In docker-compose 1.29 I could mount an empty directory and get the initial content from the overlay FS if the directory was empty (just like with a regular docker -v). This no longer works with docker-compose v2

**Steps to reproduce the issue:**
1. docker-compose up
2. ls -lR

**Describe the results you received:**
Empty directories

**Describe the results you expected:**
Directories with the initial content of the overlayfs

**Additional information you deem important (e.g. issue happens only occasionally):**

config example
```
version: "3"

services:
  app:
    image: sample
    volumes:
      - config:/var/www/html/config

volumes:
  config:
    driver_opts:
        type: none
        device: ${PWD}/config
        o: bind
```
