### ISSUE TITLE
Support assignment of a default `profile` (v2)

### ISSUE THREAD

**Issue by thespad** [docker/compose#9233]
**Description**

The current implementation of `profiles` allows for zero or more profiles to be assigned to a service but if you assign one or more then you cannot also have a service be part of the default profile set, in a similar way to `networks` where not specifying a network assumes the service is attached to the `default` network, but if you attach it to the `foo` network can you *also* attach it explicitly to the `default` network.

Use case: I have a compose project with multiple services. Some of these services `depends_on` other services, some are standlone. The services that depend on others are assigned a profile so that I can `docker compose --profile foo stop && docker compose --profile foo up -d` to ensure the child containers are stopped before the parents are recreated.

I would like to be able to also assign those services to the default profile so that if I run for example `docker compose pull` it would pull images for all services. Right now I have to add *every* services to an explicit `default` profile and run `docker compose --profile default pull` to achieve this and that means always having to specify a profile for all commands.

Ultimately this would manifest as:
```yml
services:
  child:
    image: web
    profiles:
      - foo
      - default
    depends_on:
      - parent

  parent:
    image: db
    profiles:
      - foo
      - default

  standalone:
    image: metrics
    profiles:
      - bar
      - default
```

**Comment by ndeloof** [comment]
You could use `docker compose --profile "*" <command>` to run command with all services enabled

**Comment by TheSpad** [comment]
Huh, is that documented anywhere? I had tried `--profile *` previously and it didn't work but I hadn't thought to try wrapping it in quotes.

It's better than the current situation but it would still be preferable to be able to have a service be part of a "named" profile and still part of the default one.

**Comment by ndeloof** [comment]
profile have been designed to allow declaration of some optional resources, that should not be enabled by default. If you want a service to be part of the "default" profile, why do you declare a profile for it? Your use case is a bit unclear to me.

**Comment by TheSpad** [comment]
So I have a collection of services with depdendencies that need to be sent a `stop` before an `up` because (AFAIK) `up` still does not respect `depends_on` and recreate dependent containers in the correct order. There are also some services that are independent and don't need to be stopped before updating.

What I'd like my workflow to be is:

`docker compose pull`
`docker compose --profile foo stop`
`docker compose up -d`

And have that pull images for all services, stop the dependent services, then recreate any containers that need it.

At the moment my workflow is:

**Comment by ndeloof** [comment]
ok, so the root cause for asking this is "up still does not respect depends_on and recreate dependent containers in the correct order". Did you opened an issue for this?

**Comment by TheSpad** [comment]
Not against v2 - there was definitely one for v1 but I wasn't the person who opened it.

**Comment by ndeloof** [comment]
I'm not aware of such an issue with v2.
Gave a quick try using this minimal compose.yaml file:
```yaml
services:
  c1:
    image: nginx
    depends_on:
     - c2
  c2:
    image: nginx
```

work as expected:
```
$ docker compose up --force-recreate -d
[+] Running 2/2
 ⠿ Container truc-c2-1  Started                                                                                                                                                                                                      0.6s
 ⠿ Container truc-c1-1  Started                      
```

**Comment by TheSpad** [comment]
So I just ran this test (truncated compose) with `Docker Compose version v2.2.3`:
```yaml
services:
  vaultwarden:
    image: docker.io/vaultwarden/server:alpine
    container_name: vaultwarden
    depends_on:
      - vaultwarden-db

  vaultwarden-db:
    image: docker.io/postgres:12-alpine
    container_name: vaultwarden-db
```
And with a `docker compose up --force-recreate -d` it does
```
 ⠿ Container vaultwarden-db  Recreate 
``` 
Then
```
 ⠿ Container vaultwarden     Recreate 
```
And then starts them in the correct order (`vaultwarden-db` then `vaultwarden`)

**Comment by TheSpad** [comment]
I should clarify, that's not correct behaviour (from my perspective).

When X `depends_on` Y, then Y should start before X and X should *stop* before Y.

In the case of a front end that `depends_on` a database I want the database running before the front end, but I want the front end *stopped* before the database, because pulling a database out from under a running front end which could be performing queries is a terrible idea.

**Comment by dmolesUC** [comment]
This issue is still relevant regardless of `depends_on` behavior.

Say I have a stack with an application service that requires a database. Most of the time, during development, I want to use a large external database with a copy of production data.

```yaml
services:
  app: &app
    build:
      context: .
    environment:
      DATABASE_HOST: db.example.org
    ports:
      - "3000:3000"
```

But sometimes, e.g. for testing, I want to use a small standalone database:

```yaml
services:
  db:
    image: postgres:18
    profiles:
      - test
```

But how do I get my app to talk to it? I can try to define a separate service:

```yaml
services:
  app-test:
    <<: *app
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    profiles:
      - test
```

But then Docker tries to start up both the profile-specific service and the default service, so `docker compose --profile test up` fails with `Bind for 0.0.0.0:3000 failed: port is already allocated`.

I can just use a single service and override the environment from the command line, but that's one more command-line option developers have to remember, exactly the kind of thing I expect profiles to take care of.

Yes, I can work around this by _only_ having named profiles, but that creates unnecessary work for the developer in the normal case; or I can work around it by separating the `test` case into its own compose file, but that seems to miss the point of profiles.

**Comment by ndeloof** [comment]
@dmolesUC this use case is better addressed using a compose override file, used to customize the compose application for local development:
```
services:
  app:
    environment:
      DATABASE_HOST: db #replace original value
    depends_on:
      - db
  db:
    image: postgres:18     
```

profiles were not introduced to let you _change_ the application definition, but to make some components optional
