### ISSUE TITLE
Compose runs one shot service a second time when used with a depends_on condition

### ISSUE THREAD

**Issue by bluebrown** [docker/compose#9260]
**Description**

In the below compose file, the migration service runs a second time after it completed the first, time.

**Steps to reproduce the issue:**

Run the below stack with `docker compose -p test up`. Simultaneously, watch the docker ps output from another terminal via `watch docker ps`

```yaml
services:
  app:
    image: busybox
    command: sleep infinity
    depends_on:
      migration:
        condition: service_completed_successfully

  migration:
    image: busybox
    command: sleep 30
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysqladmin -u root --password="$$MYSQL_ROOT_PASSWORD" ping
      start_period: 10s
      interval: 10s
      timeout: 2s
      retries: 3
```

**Describe the results you received:**

I can observe that the migration service waits until the DB is healthy and then starts. After 30 seconds, sleeps in exits and the app service starts. However, the migration service is run a second time.

This is where the migration sleep 30 is almost done.

```
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                    PORTS      NAMES
2b03b034256e   ec3f0931a6e6   "sleep 30"               41 seconds ago   Up 28 seconds                        test_migration_1
d7091db52deb   2347bb009b3a   "docker-entrypoint.s…"   41 seconds ago   Up 39 seconds (healthy)   3306/tcp   test_db_1
```

And this is shortly after the migration is completed. We can see that the migration started again along with the app service, indicated by the STATUS column, (up since 3 seconds).

```
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                    PORTS      NAMES
d83396f39117   ec3f0931a6e6   "sleep infinity"         50 seconds ago   Up 5 seconds                         test_app_1
2b03b034256e   ec3f0931a6e6   "sleep 30"               50 seconds ago   Up 3 seconds                         test_migration_1
d7091db52deb   2347bb009b3a   "docker-entrypoint.s…"   50 seconds ago   Up 48 seconds (healthy)   3306/tcp   test_db_1
```

**Describe the results you expected:**

I expected the migration service to run only once until completion and not again.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0-rc.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 32
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.29GiB
 Name: docker-desktop
 ID: H5YE:C4HT:BU7L:BFTF:CR2H:SMEK:FMJT:3HTP:4FI5:EGJ5:7M7E:UN7G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```
