### ISSUE TITLE
firewalld still isn't supported

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [docker/compose#9284]
**Description**

Connection refused on inter-container communications whenever firewalld is running.

This occurs despite the fact the fact that the `docker` zone is set to `ACCEPT`, neither does `--add-port=… --zone=docker` fix the issue.

**Steps to reproduce the issue:**

1. Install Docker (20.10.13) and Docker Compose (2.3.3) on a fresh CentOS 8, Fedora 34, or Rocky Linux 8 installation that's got Firewalld enabled
2. Create an empty folder, put the following into it:
   ```yml
   # docker-compose.yml
   version: '3'
   services:
   
     test:
       image: postgres:14-alpine
       networks:
         - external_network
         - internal_network
       depends_on:
         - db
   
     db:
       restart: always
       image: postgres:14-alpine
       networks:
         - internal_network
       healthcheck:
         test: ["CMD", "pg_isready", "-U", "postgres"]
       volumes:
         - ./postgres:/var/lib/postgresql/data
       environment:
         - "POSTGRES_HOST_AUTH_METHOD=trust"
   
   networks:
     external_network:
     internal_network:
       internal: true
   ```
3. Enter the folder and run `docker up db`; wait for it to settle
4. In another window, enter the folder and run `docker-compose run --rm test pg_isready -U postgres -h db`
5. Observe the following output:
   ```
   db:5432 - no response
   ```
6. Disable `firewalld`
7. Reboot the machine
8. Repeat step 4
9. Observe the following output:
   ```
   db:5432 - accepting connections
   ```

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm _currently_ reproducing this on Rocky Linux 8 because it's what my VPS host has, but this issue has plagued me for as long as I can remember; I have previously experienced it on:

* CentOS 7
* CentOS 8
* Fedora 32
* Fedora 33
* Fedora 34

**Output of `docker-compose version`:**

```
Docker Compose version v2.3.3
```

**Output of `docker info`:**

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false 
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-348.20.1.el8_5.x86_64
 Operating System: Rocky Linux 8.5 (Green Obsidian)
 OSType: linux
 Architecture: x86_64
 CPUs: 2 
  Total Memory: 716.9MiB
 Name: e8a0b6.rn.atl.ga.us.xn--l3h.one9.is
 ID: N4OA:ZAWD:CVOZ:UHR3:ZFEL:N7CU:5KCO:MZUD:SJKE:352S:FL3D:LXJT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Output of `docker context inspect`:**

```json
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]
```

**Additional environment details:**

Freshly-installed system

`firewalld-0.9.3-7.el8`
