### ISSUE TITLE
Compose v2 stops services using `depends_on` in the wrong order

### ISSUE THREAD

**Issue by thespad** [docker/compose#9297]
**Description**

When issuing a `docker compose up -d` to running services using `depends_on`, service(s) that are depended on are stopped before the service(s) that depend on them.

**Steps to reproduce the issue:**
```yaml
services:
  traefik:
    image: docker.io/traefik:latest
    container_name: traefik
    depends_on: 
      - dockerproxy-traefik
      - traefik-errors

  dockerproxy-traefik:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy-traefik

  traefik-errors:
    image: docker.io/nginx:alpine
    container_name: traefik-errors
```
1. Have a docker-compose.yml with multiple services using `depends_on` (such as above example)
2. Change configuration or update images for any of the definied services and issue a `docker compose up -d`

**Describe the results you received:**
`dockerproxy-traefik` & `traefik-errors` are stopped and recreated *before* `traefik` is stopped

**Describe the results you expected:**
As `traefik` `depends_on` `dockerproxy-traefik` & `traefik-errors`, those services should not be stopped while `traefik` is still running. "Top level" services should be stopped first, working through the dependency tree until all associated containers are stopped, so that containers which are depended on by others are not unceremoniously pulled out from under them.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.3.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 59
  Running: 59
  Paused: 0
  Stopped: 0
 Images: 68
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-104-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.63GiB
 Name: docker2
 ID: 67LS:QX2S:7P4H:CTCH:IGKD:4BKW:6HYY:46PB:LHNR:IXBV:CDSP:FXXJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: thespad
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Default Address Pools:
   Base: 172.20.0.0/16, Size: 24

WARNING: No swap limit support
```

**Additional environment details:**
Ubuntu 20.04.4 LTS on esxi
