### ISSUE TITLE
Compose v3: Make ability to specify source for ENV variables inside docker-compose file

### ISSUE THREAD

**Issue by mrAndersen** [docker/compose#9300]
For example i have the following service
```
web:
    build:
            context: docker/fpm
            dockerfile: Dockerfile
            args:
                MY_VARIABLE_STATUS:  ${VARIABLE_NOT_FROM_ENV}
```

I want ```VARIABLE_NOT_FROM_ENV``` being resolved not from .env file and ALSO i don't want to write all the time --env-file argument running compose up command, so i assume you guys should make this as a config inside docker-compose.yaml itself
