### ISSUE TITLE
links-like behavior for containers using net=host.

### ISSUE THREAD

**Issue by razic** [docker/compose#933]
hey. i'm running some containers with `net: host` and i need some containers to start running before others but obviously cant use links with net host to specify that sort of dependency. any ideas?

**Comment by thaJeztah** [comment]
You'll have to start them manually in that case. (Having something in the yaml to define dependencies would indeed be nice).

You can create/start individual services manually, using `docker-compose up -d [servicename(s)]`. The same applies to other commands (e.g. `docker-compose stop foo bar baz`)

**Comment by dnephin** [comment]
#686 would make this possible

**Comment by bonitao** [comment]
You can workaround with volumes_from, as explained here: https://github.com/docker/compose/issues/933

**Comment by razic** [comment]
@bonitao think you referenced the wrong issue. this is issue #933 which does not contain a work around.

**Comment by bonitao** [comment]
Hi @razic,

Sorry for that. I can't find the link I intended to post anymore. But all it says is that instead of links you can use volumes_from to make containers depend on each other. 

```
# this ensures docker-compose starts container_a before container_b
container_a:
  ...
container_b:
  links:
     a:a

# this does not run because links are not allowed with net: host
container_a:
  net: host
  ...
container_b:
  links:
     a:a

# this ensures docker-compose starts container_a before container_b
container_a:
  net: host
  ...
container_b:
  volumes_from:
     - a
```

I hope this helps.
