### ISSUE TITLE
Support IPAM options

### ISSUE THREAD

**Issue by qnap-ericfan** [docker/compose#9330]
**Description**

Here is my docker-compose.yaml
```
version: "3"
services:
  pihole:
    container_name: test-1
    image: alpine
    networks:
      - br-test

networks:
  br-test:
    driver: bridge
    driver_opts:
      opt1: "opt1"
    ipam:
      driver: default
      options:
        opt2: "opt2"
```
I execute command "docker-compose up", then inspect the network created by compose.
```
[
    {
        ...
        "IPAM": {
            "Driver": "default",
            "Options": null,
            ...
        },
        "Options": {
            "opt1": "opt1"
        }
    }
]
```
I found that IPAM.Options is null even if I setup value already.

**Describe the results you received:**
IPAM.Options is null.

**Describe the results you expected:**
IPAM.Options is {"opt2": "opt2"}.

**Output of `docker compose version`:**
Docker Compose version 2.3.2
