### ISSUE TITLE
2.4.0/2.4.1 mounting relative mounts relative to the pwd instead of relative to the docker-compose.yaml when COMPOSE_CONVERT_WINDOWS_PATHS is set

### ISSUE THREAD

**Issue by rfay** [docker/compose#9344]
**Description**

In 3.4.0 docker-compose is mounting relative mounts wrong, it seems to mount relative to the pwd instead of relative to the docker-compose.yaml (which is what it's always done)

```yaml
    volumes:
    - consistency: cached
      source: ../
      target: /var/www/html
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: .
      target: /mnt/ddev_config
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: ./xhprof
      target: /usr/local/bin/xhprof
      type: bind
    - source: ddev-global-cache
      target: /mnt/ddev-global-cache
      type: volume
      volume: {}
```

This is a snippet from a ddev .ddev/.ddev-docker-compose-full.yaml, and what happens is the `../` is actually mounting to the directory *above* the directory that ddev is being run in, instead of the the directory above .ddev. 

**Note while there that the indentation of `create_host_path: true` is wrong (that's output from `docker-compose config`)** - I doubt that has anything to do with this, but it seems wrong.**
 

**Steps to reproduce the issue:**

I've worked on this and don't have a perfect recreation scenario, but it completely breaks every ddev project, so is easy to recreate. 

Binaries are at https://github.com/drud/ddev/actions/runs/2076573997 - the only difference with them is that they use docker-compose 2.4.0, so you could also use any ddev version and use `ddev config global --required-docker-compose-version=2.4.0`

Anyway, in any directory, `ddev config --auto && ddev start` then `ddev ssh` and you'll see the directory *above* the project directory in /var/www/html instead of seting the project directory there.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.4.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 2.922GiB
 Name: docker-desktop
 ID: EIFZ:YNOM:PWN5:JQBG:S5I3:YWHQ:SBPM:K44B:UZMZ:IHUG:BLJL:TNPX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details:**

**Comment by ndeloof** [comment]
Ran a quick test trying to reproduce:

```
$ ls test
compose.yml
$ cat test/compose.yml 
services:
  foo:
    image: alpine
    command: ls /work
    volumes:
      - bind:
          create_host_path: true
        read_only: true
        source: .
        target: /work
        type: bind
$ docker compose -f test/compose.yml run foo
[+] Running 1/0
 ⠿ Network test_default  Created                                                                                                                                                        0.0s
compose.yml
```

so, "works for me".

**Comment by rfay** [comment]
Please try the repro case using ddev, you'll see it right away. I wasn't able to whip up a trivial case either, but it's new behavior. 

I'm traveling on vacation in Spain and haven't had a lot of time to chase things like this. But please know that it's (another) serious regression, easily reproducible with the technique described above.

**Comment by rfay** [comment]
It was pretty easy to git bisect. Regression was introduced in ff73827a

**Comment by ndeloof** [comment]
I hardly understand how ff73827a6fbb3b4b991c98ddc2eaf7707e8c262d could have impact on relative paths
cc @glours

**Comment by rfay** [comment]
I don't understand it either. Trying to get a simpler repro. But it's easy to show. It does seem to have a new way of running docker-compose, maybe that's it.

**Comment by rfay** [comment]
BTW, AFAICT this has to do with mounting a *relative* path on the host, since we end up with the *parent* path mounted inside the container. So `source: ../` will be the key IMO.

**Comment by glours** [comment]
Maybe related to the upgrade of Compose Go 🤔 
Will try to take a look later today

**Comment by rfay** [comment]
This is the file. It lives in the project `.ddev/.ddev-docker-compose-full.yaml`

It gets run with `docker-compose -f /Users/rfay/workspace/j/.ddev/.ddev-docker-compose-full.yaml up --build -d`

And no, I'm unable to get it to fail except when ddev exec's it, so it must have something to do with environment or streams or something like that.  I'll keep trying to get a simpler repro case. 

But `mkdir junk && cd junk && ddev config --auto && ddev start && ddev exec ls` will show you the files in the *parent of the project directory* instead of the files in the project root.  (`ddev start` creates the .ddev/ddev-docker-compose-full.yaml)

**Comment by rfay** [comment]
Another data point is that the `xhprof` directory gets created in the project root instead of in the .ddev directory. So somehow docker-compose gets completely confused about what its point of reference is (in this case, it should be the .ddev directory where .ddev-docker-compose-full.yaml lives, not the project root directory (one level up) where `xhprof` is getting created.

**Comment by rfay** [comment]
The problem is COMPOSE_CONVERT_WINDOWS_PATHS. When it's set to true this bug gets triggered. 

Here's a simple docker-compose.yaml - 

* put it in a *subdirectory* named `sub` and 
* `docker-compose -f sub/docker-compose.yaml up -d`
* `docker-compose -f sub/docker-compose.yaml exec junk ls`

The last command will show you the contents of the project parent instead of the contents of the project.


```yaml
name: sub
services:
  junk:
    command:
    - tail
    - -f
    - /dev/null
    image: busybox
    networks:
      default: null
    volumes:
    - type: bind
      source: ../
      target: /var/www/html
      consistency: cached
    working_dir: /var/www/html
```
