### ISSUE TITLE
Compose V2 does not allow override of extra_hosts

### ISSUE THREAD

**Issue by dcendents** [docker/compose#9361]
**Description**

Compose V2 does not allow override of extra_hosts the same way we could do with compose V1

**Steps to reproduce the issue:**

With the following `docker-compose.yml`:

```yaml
version: "2.4"
services:
  app:
    image: busybox
    extra_hosts:
      - "extra1.domain.org:10.0.0.1"
      - "extra2.domain.org:10.0.0.2"
```
and the following `docker-compose.override.yml`

```yaml
version: "2.4"
services:
  app:
    extra_hosts:
      - "extra1.domain.org:192.168.1.101"
      - "extra2.domain.org:192.168.1.102"
```

**Describe the results you received:**

`docker-compose config` returns the following corectly overriden `extra_hosts`

```yaml
services:
  app:
    extra_hosts:
      extra1.domain.org: 192.168.1.101
      extra2.domain.org: 192.168.1.102
    image: busybox
version: '2.4'
```

`docker compose config` instead returns

```yaml
name: docker-compose
services:
  app:
    extra_hosts:
    - extra1.domain.org:10.0.0.1
    - extra2.domain.org:10.0.0.2
    - extra1.domain.org:192.168.1.101
    - extra2.domain.org:192.168.1.102
    image: busybox
    networks:
      default: null
networks:
  default:
    name: docker-compose_default
```

**Describe the results you expected:**

The same behavior as Compose V1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker-compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  compose: Docker Compose (Docker Inc., v2.4.1)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 34
  Running: 0
  Paused: 0
  Stopped: 34
 Images: 715
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-39-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.11GiB
 Name: dbeland-linux-02
 ID: UYRE:2QHQ:OTJO:JMS6:W4JS:IOSB:THJ4:XN5L:35DC:5YB7:HBJ4:HISL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  nexus-bsm:5102
  collaborative-docker-registry.collaborative.local:5100
  collaborative-docker-registry.collaborative.vlan:5100
  common-docker-registry.common.vlan:443
  common-docker-registry.common.vlan:5100
  nexus-bsm:5100
  nexus-bsm:5101
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

Also it is not just cosmetic, all the values get written to `/etc/hosts` and the order in which they are written makes it impossible to use the overriden value

`docker compose run app /bin/sh -c "cat /etc/hosts && ping extra2.domain.org"`

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.0.0.1	extra1.domain.org
10.0.0.2	extra2.domain.org
192.168.1.101	extra1.domain.org
192.168.1.102	extra2.domain.org
172.19.0.2	7abc728fea11
PING extra2.domain.org (10.0.0.2): 56 data bytes
```

when `docker-compose run app /bin/sh -c "cat /etc/hosts && ping extra2.domain.org"`

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.1.101	extra1.domain.org
192.168.1.102	extra2.domain.org
172.19.0.2	bad017cef594
PING extra2.domain.org (192.168.1.102): 56 data bytes
```
