### ISSUE TITLE
group_add with empty string should not fail the container to start

### ISSUE THREAD

**Issue by T3rm1** [docker/compose#9381]
I want to be able to pass an additional group id to docker compose. For that I added `group_add` to the compose file and assigned an environment variable to its value.
```
services:
  myservice:
    image: myimage
    group_add:
      - ${MY_GROUP}
```
This works if I provide a valid group id. However if I don't want to pass an additional group id and don't set the environment variable, then it defaults to a blank string which in turn immediately fails to start the container.

The expected behavior is that an empty string is ignored and the container runs without any errors.

**Comment by ndeloof** [comment]
you should use a compose file override for this purpose

**Comment by T3rm1** [comment]
Yes, that would work but I think it also makes sense to add functionality to compose in this case. It makes no sense to pass an empty string to `--group-add`. Don't you agree?

**Comment by ndeloof** [comment]
Seems to me this is comparable to https://github.com/docker/compose/issues/3729

Assuming we define a specific syntax to declare element **removal** - I'm using `%remove%` here for illustration, hopefully we can get a better option - you could declare:
```yaml
services:
  myservice:
    image: myimage
    group_add:
      - ${MY_GROUP-%remove%}
```
during parsing, if no variable is set, default value would actually remove this entry from list, and `group_add` would then be empty.

This could be also used on https://github.com/docker/compose/issues/3729 to declare an attribute to be overridden by the same `%remove%` directive.
To be explored further...
