### ISSUE TITLE
docker compose brings up containers which are not in the specified profile

### ISSUE THREAD

**Issue by justinbot** [docker/compose#9398]
**Description**

When using `docker compose up` with a profile, previously exited containers from a different profile are brought up as well.

This is unexpected behavior, and especially problematic when there are two services using the same port which are intended to be alternate options switched by profile.

**Steps to reproduce the issue:**
1. Create a directory containing a file `docker-compose.yml` with the following contents as an example of clashing ports:
    ```yaml
    services:
      common-service:
        image: hello-world:latest
        ports:
          - 5000:5000
      alternate-service-1:
        profiles: ["one"]
        image: hello-world:latest
        ports:
          - 5001:5001
      alternate-service-2:
        profiles: ["two"]
        image: hello-world:latest
        ports:
          - 5001:5001
    ```
1. Run with profile `one`
    ```sh
    docker compose --profile one up
    ```
1. Run with profile `two`
    ```sh
    docker compose --profile two up
    ```

**Describe the results you received:**

When run with profile `two`, `alternate-service-2` never starts, crashing with error:
```
Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5001: bind: address already in use
```

**Describe the results you expected:**

Expected `alternate-service-2` to start successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Used to work as expected, seems to have been broken with the release of `2.3.3`

**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 10
  Running: 5
  Paused: 0
  Stopped: 5
 Images: 435
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: YSS7:ZHUQ:77WW:GWID:BDPM:ZFF6:ME6Q:E23L:ONXQ:I4FM:LAXL:TN6W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
