### ISSUE TITLE
compose.override.yaml is NOT processed when using "-f"

### ISSUE THREAD

**Issue by nahuel** [docker/compose#9399]
When you use `docker compose ` with the `-f` flag then the `compose.override.yaml` file (if present) is always SILENTLY IGNORED.

Steps to reproduce:

File `compose.yaml`:

```yaml
version: "3.9"
services:
  test:
    image: alpine:latest
    volumes:
      - /tmp:${VAR}
```

File `compose.override.yaml`:

```yaml
version: "3.9"
services:
  test:
    environment:
      - FROM_OVERRIDE=1
```

File `.env`:

```sh
VAR=/FROM_ENV
```

Running from inside the directory with no `-f` flag, the result is ok:

```
/tmp/test$ ls
compose.override.yaml  compose.yaml  Dockerfile

/tmp/test$ docker compose config
name: test
services:
  test:
    environment:
      FROM_OVERRIDE: "1"
    image: alpine:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /tmp
      target: /FROM_ENV
      bind:
        create_host_path: true
networks:
  default:
    name: test_default
```

But if you run it with the `-f` flag, the `compose.override.yaml` file is SILENTY IGNORED (but the `.env` file is still processed):

```
/tmp/test$ docker compose -f compose.yaml  config
name: test
services:
  test:
    image: alpine:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /tmp
      target: /FROM_ENV
      bind:
        create_host_path: true
networks:
  default:
    name: test_default
```

It also happen if you specify an absolute path in the `-f` flag:

```
/tmp/test$ cd ..
/tmp$ docker compose -f /tmp/test/compose.yaml config
name: test
services:
  test:
    image: alpine:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /tmp
      target: /FROM_ENV
      bind:
        create_host_path: true
networks:
  default:
    name: test_default
```

Add `--project-directory` and is still ignored:

```
/tmp$ docker compose -f /tmp/test/compose.yaml --project-directory /tmp/test config
name: test
services:
  test:
    image: alpine:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /tmp
      target: /FROM_ENV
      bind:
        create_host_path: true
networks:
  default:
    name: test_default
```

But when using ONLY `--project-directory`, the override file is processed ok:

```
/tmp$ docker compose --project-directory /tmp/test config
name: test
services:
  test:
    environment:
      FROM_OVERRIDE: "1"
    image: alpine:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /tmp
      target: /FROM_ENV
      bind:
        create_host_path: true
networks:
  default:
    name: test_default
```

**Output of `docker compose version`:**

```
Docker Compose version v2.3.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 17
  Running: 0
  Paused: 0
  Stopped: 17
 Images: 46
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-107-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: serge
 ID: ND4L:BDS7:7G2Q:NDMO:TY3J:EDX6:GZZW:KPM7:HXYV:2MS7:ZSSX:NQCV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: nahuel
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Did this work with Docker Compose v1?

I'd have to search, but this may be intentional; when using the `-f` option (which can be passed multiple times to specify override file(s)), you explicitly ask for the specified file(s) to be used.

Perhaps @ndeloof remembers if this was indeed intentional.

(In either case, it should probably be documented better if it's causing confusion)

**Comment by nahuel** [comment]
Here are the results when testing against Docker Compose v1 (1.29.2, build 5becea4c). Also there is a discrepancy when using the ` COMPOSE_FILE` var:

|                                                                         | .env | override |
|-------------------------------------------------------------------------|------|----------|
| /tmp/test$ docker compose -f docker-compose.yaml config                 | ok   | -        |
| /tmp/test$ docker-compose -f docker-compose.yaml config                 | ok   | -        |
| /tmp/test$ COMPOSE_FILE=docker-compose.yaml ; docker compose config     | ok   | ok       |
| /tmp/test$ COMPOSE_FILE=docker-compose.yaml ; docker-compose config     | ok   | ok       |
| /tmp$ docker compose -f /tmp/test/docker-compose.yaml config            | ok   | -        |
| /tmp$ docker-compose -f /tmp/test/docker-compose.yaml config            | ok   | -        |
| /tmp$ COMPOSE_FILE=/tmp/test/docker-compose.yaml; docker compose config | -    | -        |
| /tmp$ COMPOSE_FILE=/tmp/test/docker-compose.yaml; docker-compose config | -    | -        |
| /tmp$ docker compose --project-directory /tmp/test config               | ok   | ok       |
| /tmp$ docker-compose --project-directory /tmp/test config               | -    | -        |

Note, the Docker Compose v2 documentation states:

>  -f, --file FILE             Specify an alternate compose file (default: docker-compose.yml)
> (...)
>  --project-directory PATH    Specify an alternate working directory (default: the path of the Compose file)
> (...)
> You can set environment variables for various docker-compose options, including the -f and -p flags.
> For example, the COMPOSE_FILE environment variable relates to the -f flag,

From reading this the user infers using `-f /some/path/docker-compose.yaml` is the same as setting `--project-directory /some/path` because the project path will be derived from the one containing the file, but is not. Also it reads like using the `COMPOSE_FILE` var is exactly the same as using the `-f` flag, but is not as you can see in the previous table.

I think the behavior must be changed to make `COMPOSE_FILE` exactly equivalent as using the `-f` flag, and to make `-f /some/path/docker-compose.yaml` equivalent to using `--project-directory /some/path`. That will ensure the override and .env files will be always processed, as the principle of least surprise mandates.

**Comment by thaJeztah** [comment]
I agree that `COMPOSE_FILE` and `-f` should do the same (not sure if there was a specific reason for them not doing the same, but I think that's a bug).

The wording for the `--project-directory` description should be tweaked a bit ("the path of the Compose file" is a bit ambiguous, as "path" may be interpreted as the path of the file _itself_, not "path of the _directory_ in which the compose file is").

As to `--project-directory` and `-f` _both_ leading to the same result, I'm not sure. When specifying the _directory_, compose will still process all possible files to select the preferred one (`compose.yaml`, `compose.yml`, `docker-compose.yaml`, `docker-compose.yml`, including the `.override` files), whereas (as I mentioned in an earlier comment), using `-f` effectively means that the _user_ is taking control of this selection. If compose would disrespect that, there would be no option for the user to _not_ use the `.override` file, unless another flag (e.g. `--disable-override-file`) was added. Not only would that be a breaking change in behavior (users may already be depending on this behavior for that reason), It's also more transparent for the user to explicitly specify which compose-files to use (`-f compose.yaml -f compose.override.yaml -f compose.testenv.yaml`).


For processing of `.env`, I'd have to check; I know there's been quite some back-and-forth on _which_ `.env` should be respected in which situation (relative to the project dir, relative to the _working_ directory, relative to the _compose file_).

**Comment by ndeloof** [comment]
> I agree that COMPOSE_FILE and -f should do the same

Ran a quick test:

compose.yml
```yaml
services:
  test:
    image: alpine
```

compose.override.yml 
```yaml
services:
  test:
    image: nginx
```

```
$ docker compose config | grep image
    image: nginx
$ COMPOSE_FILE=compose.yml docker compose config | grep image
    image: alpine
```

=> this is already how things goes

> As to --project-directory and -f both leading to the same result ...

agree. Changing project directory but still relying on default compose file doesn't mean override file detection should be disabled. This is just a shortcut for `cd xx; docker compose ...`
