### ISSUE TITLE
Suport docker --cidfile option

### ISSUE THREAD

**Issue by Grokzen** [docker/compose#940]
`docker run` has the flag `--cidfile <file>` that writes the container id to the specefied file so that it is possible to read it for other purposes.

It should be a option in the config for one image

``` yaml
web:
  image: mysql:latest
  cidfile: /tmp/mysql.cid
...
```

Supporting this might be a simpler solution to build before `exec` command is supported (as discussed in https://github.com/docker/fig/issues/593)
