### ISSUE TITLE
Reviving #6343 as it looks like the fix wasn't migrated to v2

### ISSUE THREAD

**Issue by rijulg** [docker/compose#9410]
The issue in ticket (https://github.com/docker/compose/issues/6343) which was resolved in PR (https://github.com/docker/compose/pull/7762) appears to have been revived in docker-compose v2. To restate the issue, the driver_opts device parameter in volume configuration does not allow relative paths. I have tested it on docker-compose v2.3.3 and v.2.4.1 on Linux and WSL.

The fix was implemented as (https://github.com/docker/compose/blob/master/compose/config/config.py#L497) where relative paths were resolved to absolute paths before further usage.

I suspect that the relevant volume configuration in compose v2 is implemented here (https://github.com/docker/compose/blob/v2/pkg/compose/create.go#L1115) where we are passing the volume configuration as it is to docker client. This ends up creating volumes with relative paths that don't work. We need to implement the same fix as implemented previously, and resolve the paths to absolute paths before passing to docker client.

**Comment by Somsong101** [comment]
G

**Comment by JMLX42** [comment]
The `$PWD` workaround still works though:

```yml
    ui:
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/../../../../../app/asset/html
```
