### ISSUE TITLE
ERROR: In file './docker-compose.yml', service 'networks' must be a mapping not an array.

### ISSUE THREAD

**Issue by Aqrus404** [docker/compose#9413]
It seems like I've tried every spacing combination there is, but it still doesn't work. Do you guys have any ideas?

```
version: '2'

services:
  proxy:
    build: ./
  networks:
    - example1
    - example2
  ports:
    - "80:80"
    - "443:443"

networks:
  example1:
    external:
      - name: example1_default
  example2:
    external:
      - name: example2_default

```

**Comment by kaffarell** [comment]
Could you please include the output of `docker version`, `docker context show` and `docker info`?

**Comment by glours** [comment]
In your example the `networks` property of your `proxy` service isn't correctly indented so Compose identified it as a new service called `networks`

try this instead
```yaml
services:
  proxy:
    build: ./
    networks:
      - example1
      - example2
    ports:
      - "80:80"
      - "443:443"

networks:
  example1:
    external:
      - name: example1_default
  example2:
    external:
      - name: example2_default
```

**Comment by kaffarell** [comment]
```
version: '3.8'

services:
  proxy:
    build: ./
    networks:
      - example1
      - example2
    ports:
      - "80:80"
      - "443:443"

networks:
  example1:
    external:
      name: example1_default
  example2:
    external:
      name: example2_default
```

As you can see here: https://docs.docker.com/compose/networking/
