### ISSUE TITLE
Build issue - image/build property not defined on service

### ISSUE THREAD

**Issue by elvince** [docker/compose#9444]
**Description**

When calling docker compose up, it said that my yaml file have an issue on service fluentbit.

**Steps to reproduce the issue:**

set a compose file like this:
```
services:
  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:
      context: .
      dockerfile: Webapplication2/Dockerfile
    depends_on:
      - fluentbit
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DEV_API_SECRET_FOLDER=/run/secrets
    secrets:
      - Development.apicorrespondance.json
    logging:
      driver: fluentd
      #- monsecret

  fluentbit:
    #image: ${DOCKER_REGISTRY-}fluentbit
    build:
      context: ./fluentbit
      dockerfile: fluent-bit.dockerfile
    ports:
      - "24224:24224"

```

Call compose "Up"

**Describe the results you received:**
error: either Image/build property should be set on fluentbit service

**Describe the results you expected:**
no issue as the build is set on the service

**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-buildx.exe" is not valid: failed to fetch metadata: open NUL: Le fichier spécifié est introuvable.
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-compose.exe" is not valid: failed to fetch metadata: open NUL: Le fichier spécifié est introuvable.
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-sbom.exe" is not valid: failed to fetch metadata: open NUL: Le fichier spécifié est introuvable.
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-scan.exe" is not valid: failed to fetch metadata: open NUL: Le fichier spécifié est introuvable.

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 13
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 24.84GiB
 Name: docker-desktop
 ID: ULBX:IMIS:QYT3:3DTP:VNRQ:B3N6:V4SA:VQ5W:GAT2:FYGB:KPZQ:FCQU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**
It's a windows 10 host with docker desktop.
