### ISSUE TITLE
Inconsistent behaviour with .env-File between docker-compose v1 and docker compose v2

### ISSUE THREAD

**Issue by wollomatic** [docker/compose#9447]
**Description**

Handling of strings in the .env-Files differs between Compose V1 and Compose V2.
In V2 some characters are interpreted while they are unchanged in V1.
I didn't find any mention of the difference in the documentation.

**Steps to reproduce the issue:**
**.env**:
```
456=ABC
TESTVAR1=123#456
TESTVAR2=123$456
```

**compose.yaml**:
```
---
services:
  busybox:
    environment:
      TESTVAR1: $TESTVAR1
      TESTVAR2: $TESTVAR2
    image: busybox
```

**Describe the results you received:**

``$ docker-compose config`` (Compose v1)
```
services:
  busybox:
    environment:
      TESTVAR1: 123#456
      TESTVAR2: 123$$456
    image: busybox
...
```

``$ docker compose config`` (Compose v2)
```
name: compose_bugreport
services:
  busybox:
    environment:
      TESTVAR1: "123"
      TESTVAR2: 123ABC
    image: busybox
...
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**
```
Docker Compose version v2.5.0
```
and `docker-compose version`:
```
docker-compose version 1.29.2, build 5becea4c
...
```
