### ISSUE TITLE
Support multiple build contexts

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/compose#9461]
[Dockerfile 1.4 supports multiple build contexts](https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/) - a way to specify them when building in compose would be great

I'd suggest something like:

```yaml
services:
   myapp:
    build:
        contexts:
            additional: ../foo
            deps: https://github.com/myvendor/deps
            dist: https://somedistro.info/download/latest.tar.gz
```

Being able to drive this from environment / .env could be very powerful

**Comment by nrontsis** [comment]
Is there a roadmap or any updates on this? Thanks!

**Comment by felipecrs** [comment]
I suppose the ability to [link targets](https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/#:~:text=Create%20Build%20Pipelines%20by%20Linking%20bake%20Targets)/services as in `buildx bake` should also be accounted. :)

**Comment by lmoesch** [comment]
Are there any concrete plans on this issue yet?

**Comment by alexania** [comment]
Alternately, perhaps the ability to pass additional args to the build command? That way you could pass --build-context manually while waiting for the compose specification to support it natively.

**Comment by knpwrs** [comment]
This would solve the long-standing issue of having shared code between multiple containers in a docker compose project. Would the team be open to a pull request to implement this?

**Comment by kdubuc** [comment]
With ```buildx bake``` I can build image from a compose file (see https://docs.docker.com/build/customize/bake/compose-file) :

```yaml
# docker-compose.yml
services:
  service_name:
    build:
      context: .
      x-bake:
        contexts:
          context1: path
          context2: path
```
And build with ```docker buildx bake -f docker-compose.dev.yml service_name```

But I don't know if we can ```up``` a service using buildx / bake.
