### ISSUE TITLE
Volumes mapped as specific files have different behaviour to volumes mapped as individual files

### ISSUE THREAD

**Issue by jamesla** [docker/compose#9463]
There is something strange going on with updating file that are mapped from a local machine into a docker container.

Given the following directory structure:

```bash
vagrant@carverlinux ~/docker-compose-poc [127]> tree
.
├── data
│   └── myfile.txt
└── docker-compose.yaml
```

and the following docker-compose file:
```yaml
---
version: "3.8"

services:
  demo:
    image: ubuntu
    volumes:
    - ./data/myfile.txt:/demo/myfile.txt
    - ./data:/demo/data
```

If you update myfile.txt to have a different value while the container is running for some reason the version that is mapped in via a directory `./demo/data/myfile.txt` updates but the version that is mapped as an invididual file `./demo/myfile.txt` does not - requiring the container to be restarted in order to pick up the change: 

Output below:

```bash
docker-compose run demo bash
root@d60316398406:/# cat /demo/myfile.txt
hello world
root@d60316398406:/# cat /demo/data/myfile.txt
hello world
root@d60316398406:/# cat /demo/myfile.txt
hello world
root@d60316398406:/# cat /demo/data/myfile.txt
hello world

i've changed it
```

Anybody know why this behaviour is occuring and how to fix it?
