### ISSUE TITLE
How do i set propagation for named volumes?

### ISSUE THREAD

**Issue by nghianv19940** [docker/compose#9478]
I want to share files between replicas, other containers and the host, what should i add to this. It's v3. 
`volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      type: bind
      device:/my/directory`

**Comment by maxcleme** [comment]
@nghianv19940 

Please take a look at below documentation for docker compose volume :)

https://docs.docker.com/storage/volumes/

**Comment by rpatterson** [comment]
> Please take a look at below documentation for docker compose volume :)

It's not at all clear from that page how to define propagation *in the top-level `volumes` key of a `./docker-compose.yml` file* as in the description, @maxcleme.

**Comment by ndeloof** [comment]
propagation is an option of `mount`, so this is not to be declared by top-level volume definition, but by mount per services

```yaml
services:
  test:
    volumes:
    - type: bind
      source: my_volume
      target: /test
      bind:
        propagation: shared
```
