### ISSUE TITLE
deploy.resources.limits.cpus not match nanocpus

### ISSUE THREAD

**Issue by j0rGeT** [docker/compose#9501]
**Description**

deploy.resources.limits.cpus set docker is nanocpus not match cpus

**Steps to reproduce the issue:**
```
version: "2.4"
services:
  platform:
    image: harbor.huayun.org/dev/xxxxx
    privileged: true
    pid: "host"
    deploy:
        resources:
          limits:
            cpus: '100000000' // we need to x1000000 ?
            memory: 512M
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

docker-compose v2.2.2

**Output of `docker info`:**

```
if we set cpus=1 in docker-compose config file, docker inspect xxxx nanocpus = 1 or  not  10000000 ?

compare 

docker-compose 1.24.1 version，i find set cpus=1，docker inspect xxxx nanocpus is 100000000
```
