### ISSUE TITLE
Pass build arguments on docker-compose.yml without context.

### ISSUE THREAD

**Issue by Gytree** [docker/compose#9511]
**Description**
Hi folks, thank so much for the docker-compose work. I wondering if the docker-compose is unable to pass build arguments to a remote base image  **via docker-compose.yaml file**. Currently I trying to use the [nginx-unpriviledge](https://hub.docker.com/r/nginxinc/nginx-unprivileged) container in a compose, the image have the next arguments in his docker file:

```Dockerfile
ARG UID=101
ARG GID=101
```
So with the docker-compose CLI I will pass the arguments with the **--build-arg** flag, but I will need to remember pass the UID and GID every time that I build the compose. This a problem because my team will need to remember that to. 

I'd like to use the compose yaml to pass the arguments like :

```yaml
serviceX:
  image: nginx-unprivilege
  build:
    args:
      UID: X
      GID: X
```

But this isn't possible because the build require a context and the context can't be an [addressable remote image](https://github.com/opencontainers/org/blob/master/docs/docs/introduction/digests.md). Why isn't possible use a remote image as build context ? like:

```yaml
nginx:
  build:
    context: nginxinc/nginx-unprivileged
    args:
      UID: 9000
      GID: 9000
```

There is any form to do this or in over thinking the process, any suggestion ?
