### ISSUE TITLE
env_file variable values overwritten by .env values since v2.6.0

### ISSUE THREAD

**Issue by b3n3d1k7** [docker/compose#9521]
**Description**

Environment variable values specified via env_file in a docker_compose.yml are overwritten by the values in a .env file since v2.6.0.

**Steps to reproduce the issue:**
1. Create the following files
```
# .env
TEST=.env

# .env.test
TEST=.env.test

# docker-compose.yml
version: '3'
services:
  test:
    image: 'node:6-alpine'
    env_file:
      - .env.test
```
3. Run docker-compose config with docker-compose v2.6.0

**Describe the results you received:**
```
name: docker-compose-test
services:
  test:
    environment:
      TEST: .env
    image: node:6-alpine
    networks:
      default: null
networks:
  default:
    name: docker-compose-test_default
```

**Describe the results you expected:**
This is the result of running the docker-compose config command with e.g. docker-compose v2.5.1:
```
name: docker-compose-test
services:
  test:
    environment:
      TEST: .test.env
    image: node:6-alpine
    networks:
      default: null
networks:
  default:
    name: docker-compose-test_default
```

**Additional information you deem important (e.g. issue happens only occasionally):**
If the environment variables are defined directly in the docker-compose.yml instead of via an env_file, they are not overwritten by the values in the .env file.

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 375
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-49-generic
 Operating System: Ubuntu 21.04
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.44GiB
 Name: benedikt-ThinkPad-E15
 ID: 7NBC:LL2S:XCZE:FWIG:EFK7:NDKX:FUNR:OXTV:D7RE:EXUP:PRBV:SZCE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 192.168.0.0/16, Size: 24
```

**Additional environment details:**
We noticed this problem in our gitlab pipelines using the docker:git image.
For now we just fixed the image version to docker:20.10.15-git to circumvent the problem.
