### ISSUE TITLE
Cannot docker-compose (d-c) exec with service name or d-c ps name

### ISSUE THREAD

**Issue by MBfromOK** [docker/compose#9534]
**Description**

I cannot run docker-composer exec with a set container_name in my docker-compose yml.

I am working on a docker image to demonstrate the workings of nginx as a reverse proxy and want to run the command
`sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048` to set up a strong Diffie-Hellman group.

**Steps to reproduce the issue:**
1. Build the compose file: `docker-compose build`
2. Start the completed build: `docker-compose up -d`
3. Run `docker-compose ps` to verify it is up (see below)
4. Try to run `docker-compose exec -u root --p nginx "sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"`
5. Receive errors based on the name used in the command above

docker-compose ps:
```
    Name                  Command               State                Ports              
----------------------------------------------------------------------------------------
nginx_site_1   /docker-entrypoint.sh ngin ...   Up      0.0.0.0:81->80/tcp,:::81->80/tcp
php_app1       docker-php-entrypoint php-fpm    Up      9000/tcp
```
docker-compose ps --services:
```
php_app1
nginx
```
docker-compose ps -q:
```
448bc06775cb8ba47950b1a2824389d62cd51ea86099ec885b15bdb508dba4f9
b330bec2d8532499dc4674caf61d056077b5ba1cfa98f46578b8e633283cac06
```

**Describe the results you received:**
**docker-compose exec --p -u root nginx "sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048":**
```
Error: No such container: 448bc06775cb8ba47950b1a2824389d62cd51ea86099ec885b15bdb508dba4f9
```
(as expected)**docker-compose exec --p -u root nginx_site_1 "sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048":**
```
ERROR: No such service: nginx_site_1
```

**Describe the results you expected:**
docker-compose exec --p -u root nginx _<snip>_ to run and return some kind of output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.742GiB
 Name: docker-desktop
 ID: 63UX:XGZQ:7MIC:LV2N:FP4H:FPHF:NI5S:QF6Z:WAKY:YI34:VKPO:SVXI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Username: rhlinuxuzer
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

docker-compose file:
```
version: '3.4'
services:

  #PHP App
  php_app1:
    build:
      context: ./site1/
      dockerfile: Dockerfile
    #image: php:8.1-fpm-alpine3.16
    container_name: php_app1
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: phpapp1
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./site1/code/:/var/www/html
      - ./site1/config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./site1/ssl/certs/:/etc/ssl/certs/
      - ./site1/ssl/private/:/etc/ssl/private/
      - ./site1/config/self-signed.conf:/etc/nginx/snippets/self-signed.conf
    networks:
      - labnet
      
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_site_1
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    volumes:
      - ./site1/code/:/var/www/html
      - ./site1/config/conf.d/:/etc/nginx/conf.d/
    networks:
      - labnet
```
