### ISSUE TITLE
Docker compose down is removing SQL data despite named volume

### ISSUE THREAD

**Issue by ewan-mclean** [docker/compose#9535]
**Description**

When running docker compose down, MariaDB database tables are destroyed. This seems to contradict the documentation.

**Steps to reproduce the issue:**
1. Create a working directory with the below docker-compose.yml
2. Run "docker compose up -d"
3. Install wordpress using the wizard (which populates the MariaDB tables)
4. Inspect wordpress database using PMA and note the tables exist
5. Run "docker compose down"
6. Run "docker compose up -d"
7. Inspect wordpress database using PMA and note the tables have been destroyed

**Describe the results you received:**
docker compose down appears to be destroying volumes (at least the MariaDB database/tables) without using the --volumes switch.

**Describe the results you expected:**

Data should persist across downs and ups, unless the --volumes switch is applied. Per docs [here](https://docs.docker.com/engine/reference/commandline/compose_down/):
> By default, the only things removed are:
> 
> Containers for services defined in the Compose file
> Networks defined in the networks section of the Compose file
> The default network, if one is used

**Additional information you deem important (e.g. issue happens only occasionally):**

- I am new to docker and experimenting with using it for some of the wordpress sites I look after; so very possibly it's me doing something stupid, but there does seem to be quite a lot of contradictory chatter about this issue on various forums, perhaps we can clear it up.
- If this needs to be posted elsewhere or I'm being thick, just let me know. Thanks in advance.

Related posts:

- https://stackoverflow.com/questions/68755883/unable-to-persist-postgresql-data-using-named-volume-in-docker-compose
- https://stackoverflow.com/questions/47634042/docker-compose-not-persisting-data
- https://stackoverflow.com/questions/41777037/docker-volume-does-not-persist-data
- https://stackoverflow.com/questions/47973831/docker-volumes-not-persisting-changes

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**
```

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 6
  Running: 3
  Paused: 0
  Stopped: 3
 Images: 9
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-113-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.84GiB
 Name: SERVERIPHERE.ip.linodeusercontent.com
 ID: YF5X:N4E5:X35A:7WDH:4M4K:QYM6:VNUZ:F643:ST3L:RTBS:C5FM:V3L2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details:**

- VPS deployed on Linode using their Docker image/stackscript/marketplace item (all the same thing under the hood AFAIK)
- Followed this guide, with some modifications: https://docs.docker.com/samples/wordpress/

**Contents of `docker-compose.yml`:**
```
version: "3.9"
    
services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  db_data: {}
  wordpress_data: {}
```

**`Terminal output`:**
```

ewanmclean@SERVERIPHERE:/srv/ess-wordpress-docker/alpha2$ docker compose up -d
[+] Running 3/3
 ⠿ Container alpha2-phpmyadmin-1  Started                                                                                                                                                                    0.5s
 ⠿ Container alpha2-db-1          Started                                                                                                                                                                    0.5s
 ⠿ Container alpha2-wordpress-1   Started                                                                                                                                                                    0.9s
ewanmclean@SERVERIPHERE:/srv/ess-wordpress-docker/alpha2$ docker compose down
[+] Running 4/4
 ⠿ Container alpha2-wordpress-1   Removed                                                                                                                                                                    1.3s
 ⠿ Container alpha2-phpmyadmin-1  Removed                                                                                                                                                                    1.2s
 ⠿ Container alpha2-db-1          Removed                                                                                                                                                                    0.4s
 ⠿ Network alpha2_default         Removed                                                                                                                                                                    0.1s
ewanmclean@SERVERIPHERE:/srv/ess-wordpress-docker/alpha2$ docker compose up -d
[+] Running 4/4
 ⠿ Network alpha2_default         Created                                                                                                                                                                    0.0s
 ⠿ Container alpha2-db-1          Started                                                                                                                                                                    0.5s
 ⠿ Container alpha2-phpmyadmin-1  Started                                                                                                                                                                    0.6s
 ⠿ Container alpha2-wordpress-1   Started 
```
