### ISSUE TITLE
docker compose down tries to stop external networks

### ISSUE THREAD

**Issue by ibenjelloun** [docker/compose#9536]
**Description**

Running `docker compose down` tries to remove external networks.

**Steps to reproduce the issue:**
docker-compose-1.yml
```yaml
version: '3.8'

services:
  service1:
    image: nginx:latest
    container_name: service1
    networks:
      - network-1
networks:
  network-1:
    name: network-1

```

docker-compose-2.yml
```yaml
version: '3.8'

services:
  service2:
    image: nginx:latest
    container_name: service2
    networks:
      - network-1
      - network-2

networks:
  network-1:
    name: network-1
    external: true
  network-2:
    name: network-2

```

1. start first docker compose : `docker compose -f ./docker-compose-1.yml up -d`
2. stop the second docker compose : `docker compose -f ./docker-compose-2.yml down`

**Describe the results you received:**

The stopping of the second docker compose tries to stop network-1 :
`error response from daemon: error while removing network: network network-1`

**Describe the results you expected:**

The stopping of the second docker compose should not stop network-1 as network-1 is external.

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 79
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: JK3M:64CP:KLXJ:DHZC:6O46:Z2DR:5FMB:TLDR:QFSS:X7VC:MLJT:B25F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

Docker Desktop / Windows 10
