### ISSUE TITLE
Docker taking way too long to build - not sure if multi staged is saving up time correctly

### ISSUE THREAD

**Issue by gabrielpulga** [docker/compose#9551]
I'm building my Ruby application with docker-compose using multistag but I suspect it is taking way too long to build. Around 14-15 min.

**Steps to reproduce the issue:**
1. Enable buildkit
2. docker-compose build --no-cache

**Describe the results you received:**
Docker builds succesfully but takes a long time to do so, seems to be running installation steps several times.

**Describe the results you expected:**
Container built in optimal time by executing each step no more than one time. 

**Output of `docker compose version`:**

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-41-generic
 Operating System: Zorin OS 16.1
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.624GiB
 Name: gabriel-Inspiron-3583
 ID: ZO2G:GYQX:L7FC:RI4X:AZFN:67J7:ABUJ:AXCO:357V:EQ45:PIVT:RYMX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
**Dockerfile.dev**
```# | base
FROM ruby:2.7.3-alpine as base
RUN apk add --update --no-cache tzdata postgresql-dev build-base git shared-mime-info qt5-qtwebkit-dev nodejs yarn postgresql-client libcurl apache2-utils \
    less pkgconfig imagemagick imagemagick-dev imagemagick-libs && \
    apk add --update --no-cache --virtual .build-deps msttcorefonts-installer && \
    update-ms-fonts && fc-cache -f && \
    rm -rf /tmp/* && apk del .build-deps
ENV RAILS_ROOT=/srv/www/${APP_NAME} \

# | bundle
FROM base as bundle
ARG BUNDLE_WITHOUT_GROUPS
ARG BUNDLE_IS_PRD
COPY Gemfile* /tmp/
COPY package.json /tmp
WORKDIR /tmp
RUN bundle config set deployment false && \
    bundle install --jobs 4

# | main
FROM base as main
COPY --from=bundle /tmp/vendor /srv/www/${APP_NAME}/vendor
COPY --from=bundle /usr/local/bundle/config /usr/local/bundle/config
COPY --from=bundle /tmp/node_modules /srv/www/${APP_NAME}/node_modules
WORKDIR $RAILS_ROOT
COPY . .

# | bundle-assets
FROM main as bundle-assets
RUN --mount=type=cache,target=${RAILS_ROOT}/tmp bundle exec rake assets:precompile --trace

# | backend
FROM main as backend
COPY --from=bundle-assets ${RAILS_ROOT}/node_modules ${RAILS_ROOT}/node_modules
COPY --from=bundle-assets /srv/www/${APP_NAME}/public /srv/www/${APP_NAME}/public
CMD bundle exec puma -C config/puma.rb

# | frontend
FROM nginx:stable-alpine as frontend
RUN apk add --update --no-cache apache2-utils
ENV FRONTEND_ROOT /var/www/${APP_NAME}
WORKDIR ${FRONTEND_ROOT}
COPY --from=bundle-assets /srv/www/${APP_NAME}/public ${FRONTEND_ROOT}/public
COPY default.conf /tmp/docker.nginx
RUN envsubst '$FRONTEND_ROOT' < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
```
docker-compose-yml
```
version: "3.4"
services:
  backend:
    image: application/backend:local
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    command: >
        sh -c "bundle install &&
               bundle exec puma -C config/puma.rb"
    volumes:
      - ".:/srv/www/application:delegated"
      - "/srv/www/application-pagamentos/public"
      - "/srv/www/application-pagamentos/vendor"
      - "/srv/www/application-pagamentos/node_modules"

  frontend:
    image: application/frontend:local
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    depends_on:
      - backend

  postgres:
    image: "postgres:11.4-alpine"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```
