### ISSUE TITLE
BUG: docker-compose build still ignores service-order from yaml and depends_on

### ISSUE THREAD

**Issue by typoworx-de** [docker/compose#9584]
docker-compose build still ignores services key-order from yaml and ```depends_on```.

dummy docker-compose.yml to explain the problem:
```yaml
version: '3.5'

services:
  first-service:
    image: my-first-service
    build:
      context: .
      dockerfile: Dockerfile.my-first-service

  # build depends on my-first-service using f.e. COPY --from=my-first-service
  second-service:
    image: my-second-service
    depends_on:
      - first-service
    build:
      context: .
      dockerfile: Dockerfile.my-second-service
```
Running now ```docker-compose build``` will start building. But for some reason sometimes the build doesn't start (depending on service-names?!) with the first key -- which is here "first-service", but instead starts in different order. Starting with "second-service" build will break the whole build.

I've checked this on a practice example for a custom-build and the only work-around on this is to run:
```
docker-compose build first-service
docker-compose build second-service
```

Or for automation the hack for a ```docker-compose.sh``` could be:
```bash
#!/bin/bash

echo "Determining build-order for docker-compse services ..."
services=$(yq '.services|keys' docker-compose.yaml)

for service in ${services}; do
  docker-compose build ${service} ${@}
done
```
The mentioned two work-arounds work for my build, but using regular ```docker-compose build``` will make it stuck!

I think this still is a bug.
