### ISSUE TITLE
`compose` wrapper does not work with `--exit-code-from`

### ISSUE THREAD

**Issue by nstrong-scw** [docker/compose#9594]
**Description**

When attempting to run a docker compose with the `--exit-code-from` flag, docker-cli does not propagate the exit code and gets stuck.

```yaml
# docker-compose.integration.yaml
version: "3.9"
networks:
  default:
    name: integration-test-network

services:
  source-db:
    image: mongo
    container_name: test-source-db
    ports:
      - "27018:27017"
    profiles:
      - reporting

  target-db:
    image: postgres:12-alpine
    hostname: test-target-db
    container_name: test-target-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reportingtest
    command: postgres -c listen_addresses='*'
    ports:
      - "5435:5432"
    profiles:
      - reporting

  reporting-tests:
    image: busybox
    container_name: reporting-tests
    command: sleep 30
    profiles:
      - reporting
    depends_on:
      - source-db
      - target-db
```

**Steps to reproduce the issue:**
1. save the above YAML to `docker-compose.integration.yaml`
2. run `docker compose --file docker-compose.integration.yaml --profile reporting up --exit-code-from reporting-tests`

**Describe the results you received:**
```
reporting-tests exited with code 0
Aborting on container exit...
[+] Running 4/4
 ⠿ Container reporting-tests  Stopped                                                                                                                                                                                    0.0s
 ⠿ Container analytics-tests  Stopped                                                                                                                                                                                    0.0s
 ⠿ Container test-source-db   Stopped                                                                                                                                                                                    0.3s
 ⠿ Container test-target-db   Stopped                                                                                                                                                                                    0.3s
ERRO[0031] 0                                            
```
(I can get it to terminate by pressing CTRL+C several times)

**Describe the results you expected:**
I expected it to exit with code 0.

Running the same command directly with `docker-compose` works as expected:

```
reporting-tests exited with code 0
Aborting on container exit...
Stopping test-source-db    ... done
Stopping test-target-db    ... done
$ echo $?
0
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.24
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.8.2 (79419)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 36
  Running: 31
  Paused: 0
  Stopped: 5
 Images: 22
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: N7BK:6LNP:3UPZ:NIPX:J77A:6CA6:YVEV:XFNE:YX5X:O4EB:SQ6L:Y7DV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 14059
  Goroutines: 14047
  System Time: 2022-06-10T18:40:49.123487799Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS version: Mac OS 12.4
