### ISSUE TITLE
feat: `build.name`

### ISSUE THREAD

**Issue by loynoir** [docker/compose#9628]
### Why
Given
```yaml
  foobar:
    image: private/foobar
    build:
      dockerfile: foobar.Dockerfile
```
Reproduce
```sh
$ docker-compose pull
Pulling foobar: Error response from daemon: 
pull access denied for private/foobar, 
repository does not exist or may require 'docker login': 
denied: requested access to the resource is denied
```

### Feat
```yaml
  foobar:
    build:
      name: private/foobar
      dockerfile: foobar.Dockerfile
```

### Workaround
```yaml
  foobar:
    image: private/foobar
    pull_policy: never
    build:
      dockerfile: foobar.Dockerfile
```
