### ISSUE TITLE
Building an image with `docker-compose` will lead to the process bar showing unreadable code with the `pip install` command.

### ISSUE THREAD

**Issue by FavorMylikes** [docker/compose#9632]
### Build by `Dockerfile`

```console
...
Collecting Flask
  Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 85.5 kB/s eta 0:00:00
...
```

### Build by `docker-compose`

- **clear the image first**

```console
...
Collecting Flask
  Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
     鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣 95.2/95.2 kB 84.8 kB/s eta 0:00:00
...
```
`docker-compose.yml` looks like

```yaml
version: '3.7'
services:

  redis:
    image: redis:latest
    container_name: rd01

  webapp:
    build: .
    container_name: wa01
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
```

`Dockerfile`

```Dockerfile
FROM python:3.8.3


WORKDIR /opt

COPY requirements.txt ./
RUN pip install setuptools pip --upgrade
RUN pip install -r requirements.txt
COPY . ./

EXPOSE 8000
CMD ["./start.sh"]
```
