### ISSUE TITLE
docker compose config not showing empty entrypoint

### ISSUE THREAD

**Issue by chrmarti** [docker/compose#9634]
**Description**

`docker compose config` does not show an empty entrypoint like `entrypoint: ''`. The empty entrypoint does override the image's entrypoint, so it works, but it is missing from the `config` output.

**Steps to reproduce the issue:**
docker-compose.yml:
```yml
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: ''
    command: sleep inf
```

Dockerfile
```Dockerfile
FROM python:latest

ENTRYPOINT python
```

1. `docker compose config`

**Describe the results you received:**
```
name: compose-config-bug
services:
  app:
    build:
      context: /Users/chrmarti/Development/repos/smktst-compose/compose-config-bug
      dockerfile: Dockerfile
    command:
    - sleep
    - inf
    networks:
      default: null
networks:
  default:
    name: compose-config-bug_default
```

**Describe the results you expected:**

The output should include `entrypoint: ''` because that affects how the container will be started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.6.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: TUFX:R4IS:OGGW:BAHM:B2VP:QKGQ:MWJD:ONWZ:LJ4L:FBP7:W5I4:XWCN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

Causing https://github.com/microsoft/vscode-remote-release/issues/6861.
