### ISSUE TITLE
Panic on missing image key in yaml in v2.6.1

### ISSUE THREAD

**Issue by e271828-** [docker/compose#9653]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Uninformative panic when yaml file is missing `image`

**Steps to reproduce the issue:**
1. YAML like:
```
  migrations:
    extends:
      file: docker-compose.base.yaml
      service: migrations_base
```

causes panic.

```
  migrations:
    image: xyz
    extends:
      file: docker-compose.base.yaml
      service: migrations_base
```

works as expected.

**Describe the results you received:**

`panic: interface conversion: interface {} is nil, not map[string]interface {}`

**Describe the results you expected:**

Output telling me what file and block or line number the parser failed on.

**Comment by glours** [comment]
Hey @e271828- 
You don't provide us the minimal info to reproduce your issue, so I tried with this example

`docker-compose.base.yaml`:
```yaml
services:
  common:
    image: busybox
    environment:
      TZ: utc
      PORT: 80
```

and the following `compose.yaml`:
```yaml
services:
  cli:
    extends:
      file: docker-compose.base.yaml
      service: common
    environment:
      PORT: 8080
```

And I'm not able to reproduce your issue
