### ISSUE TITLE
[feat] multiple build.network

### ISSUE THREAD

**Issue by loynoir** [docker/compose#9678]
### feat: build.network
allow `services.X.build.network` to be a list

### scenario
docker-compose.yml
```yml
version: "3.8"

networks:
  foo:
    name: foonet
    external: true
  bar:
    name: barnet
    external: true

services:
  app:
    build:
      network:
        - foo
        - bar
      dockerfile: Dockerfile
```

```sh
$ docker-compose build
services.app.build.network must be a string
```
