### ISSUE TITLE
`docker compose config --no-normalize --format json` does not output extensions as expected (`x-`-prefixed fields)

### ISSUE THREAD

**Issue by lytedev** [docker/compose#9682]
`docker compose config --no-normalize` does not output extensions (fields beginning with `x-`) while `docker compose config --no-normalize --format json` do not.

**Steps to reproduce the issue:**
1. Have the following `docker-compose.yml`:

```yaml
version: '3'
  
x-my-extension:
  data1: a b c
  data2: x y z
  
services:
  alpine:
    image: alpine
```

2. I can see the extension when running `docker compose config --no-normalize` (you can even omit `--no-normalize`?)

```yaml
name: tmp
services:
  alpine:
    image: alpine
x-my-extension:
  data1: a b c
  data2: x y z
```

3. But once I add `--format json` (and run `docker compose config --no-normalize --format json`) the extension no longer shows up in my output:

```json
{
  "name": "tmp",
  "services": {
    "alpine": {
      "image": "alpine"
    }
  }
}
```

while I would have expected to see something like this:

```json
{
  "name": "tmp",
  "services": {
    "alpine": {
      "image": "alpine"
    }
  },
  "x-my-extension": {
    "data1": "a b c",
    "data2": "x y z"
  }
}
```

**Output of `docker compose version`:**

```bash
$ docker compose version
Docker Compose version 2.6.1
```

**Output of `docker info`:**

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.6.1)

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 63
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.14-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.71GiB
 Name: dragon.h.lyte.dev
 ID: ""
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
