### ISSUE TITLE
[feat] Options for determine to join or create networks in the same time.

### ISSUE THREAD

**Issue by PasserDreamer** [docker/compose#9684]
Allow to determine to join exist network or create networks if not exist in the same time.

```YAML
version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
        
networks:
  nginx:
    name: nginx
    join-if-exist: true  # Add a feature like this
   
```
