### ISSUE TITLE
Project naming behaviors between environment variable COMPOSE_PROJECT_NAME and command line -p flag

### ISSUE THREAD

**Issue by y-liang** [docker/compose#9693]
**Description**

When specifying a project name, the [COMPOSE_PROJECT_NAME environment variable](https://docs.docker.com/compose/reference/envvars/#compose_project_name) prepends differently than [command line -p flag](https://docs.docker.com/compose/reference/#use--p-to-specify-a-project-name).

**Steps to reproduce the issue:**
1. Make a directory called `composedir`, and inside it create a `compose.yml` file as below. In `backend.Dockerfile`, create a work directory called `/workdirexample` for the node image 
```
services:
    backend:
      build:
        context: ../
        dockerfile: backend.Dockerfile
      container_name: example-backend
      environment:
        # COMPOSE_PROJECT_NAME: example-a
        DATABASE_HOST: example-database
      ports:
        - 3001:3001
      networks:
        - network
      depends_on:
        - database
      restart: unless-stopped
    database:
      build:
        context: ../
        dockerfile: database.Dockerfile
      container_name: example-database
      volumes:
        - volume:/home/theuser/volumes/example
      environment:
        # COMPOSE_PROJECT_NAME: example-a
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432
      networks:
        - network
      restart: unless-stopped
  
volumes:
    volume: {}
  
networks:
    network:
```

**Describe the results you received:**
Run the compose file with two methods to set a project name.
a) Uncomment `COMPOSE_PROJECT_NAME: example-a` and run `docker compose up -d`
```
⠿ Network composedir_network      Created                                                                                                           
⠿ Volume "composedir_volume"      Created                                                                                                           
⠿ Container workdirexample-database  Started                                                                                                           
⠿ Container workdirexample-backend   Started
```
And `docker image ls` shows that `composedir_backend` and `composedir_database` have been created.

b) Run `docker compose -p example-b up -d`
```
 ⠿ Network example-b_network    Created                                                                                                           
 ⠿ Volume "example-b_volume"    Created                                                                                                           
 ⠿ Container workdirexample-database  Started                                                                                                           
 ⠿ Container workdirexample-backend   Started 
```
And `docker image ls` shows that `example-b_backend` and `example-b_database` have been created.

**Describe the results you expected:**
Both of them should prepend images, containers, volumes, and networks the same way.

**Additional information you deem important (e.g. issue happens only occasionally):**
Organize the commands and document them in detail with consistency.

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.0-52-generic
 Operating System: Ubuntu 21.10
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 971.4MiB
 Name: wave
 ID: NRWF:HQ4U:AQ6G:F4UO:GUXN:R2VS:CSC4:YFXE:BUBN:VWPT:NYSS:V6AO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
N/A

**Comment by ulyssessouza** [comment]
Hello @y-liang. The `COMPOSE_PROJECT_NAME` is not meant to be set like this.
To set the project name you have to make it part of the OS environment variables, and not passing it into the service. Like in:
```shell
COMPOSE_PROJECT_NAME=my_project docker compose up
```

**Comment by nielsbom** [comment]
FYI: you can set the `name` property in the top level of the `docker-compose.yml` to get the same result as passing `-p project_name`.

```yaml
version: "3.9"
name: athena
services:
  db:
  nginx:
  frontend:
volumes:
  elastic-search:
  frontend-deps:
```
