### ISSUE TITLE
Error Invalid template: "qh2wqx(qjtq4((d^ixkac1o7e)@pps+cl()4p$%w&b+3gw)=am"

### ISSUE THREAD

**Issue by Mracobes9** [docker/compose#9707]
**Description**
I getting error "Error Invalid template: 'qh2wqx(qjtq4((d^ixkac1o7e)@pps+cl()4p$%w&b+3gw)=am'" when i try to execute command docker-compose ps. It caused for this compose file
```
version: '3.9'

services:
  app:
    container_name: app
    image: python:3.9
    env_file:
      - .env
    environment:
      - SERVICE_NAME=app
    volumes:
      - ..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    networks:
      - proxynet

  db:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - proxynet

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    restart: always
    networks:
      - proxynet

volumes:
  pg_volume:
  rabbitmq_volume:

networks:
  proxynet:
    driver: bridge
```
**Steps to reproduce the issue:**
1.Move to folder with this compose file
2. Try to execute `docker-compose ps`
3. See this error

**Describe the results you received:**
I got 'Invalid template: "qh2wqx(qjtq4((d^ixkac1o7e)@pps+cl()4p$%w&b+3gw)=am"' error

**Describe the results you expected:**
I got correct result for this command 

**Output of `docker compose version`:**

```
Docker Compose version 2.9.0
```

**Output of `docker info`:**

```
Client:
Context:    default
Debug Mode: false
Plugins:
buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
compose: Docker Compose (Docker Inc., 2.9.0)

Server:
Containers: 9
Running: 5
Paused: 0
Stopped: 4
Images: 17
Server Version: 20.10.17
Storage Driver: btrfs
Build Version: Btrfs v5.18.1
Library Version: 102
Logging Driver: json-file
Cgroup Driver: systemd
Cgroup Version: 2
Plugins:
Volume: local
Network: bridge host ipvlan macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1.m
runc version:
init version: de40ad0
Security Options:
seccomp
Profile: default
cgroupns
Kernel Version: 5.18.15-zen1-1-zen
Operating System: Garuda Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: mracobes-hppavilionnotebook
ID: 54RL:36QL:CM6Q:PA2T:WS73:IF3Y:LOD7:Z4OR:D27X:OJZ7:X5MF:R6RW
Docker Root Dir: /var/lib/docker
Debug Mode: false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details:**
```
OS: Garuda Linux
Host: HP 845E
Kernel: 5.18.15-zen1-1-zen
Shell: bash
DE: Plasma 5.25.3
WM: KWin
Terminal: konsole
CPU: Intel i5-7300HQ (4) @ 3.5GHz
GPU: NVIDIA GeForce GTX 1050 Ti Mobile
 GPU: Intel HD Graphics 630
Memory: 9.37GiB / 15.51GiB
```
