### ISSUE TITLE
[Feature] add mechanism to specify GPUs by capability

### ISSUE THREAD

**Issue by sharvil** [docker/compose#9753]
While I understand compute capability is an NVIDIA-specific property, it's still useful in practice to be able to specify which GPUs to reserve in a device-independent way.

A typical scenario: a set of machines have a mixed set of GPUs plugged in. Setting `count: 2` allocates the first two GPUs based on PCI bus order, which is highly machine-specific. Instead, if I could state that I want 2 GPUs with compute capability >= 8.6 then I can deploy onto any machine that can satisfy that requirement, regardless of which PCI slot the GPUs are plugged into.

The concrete request here is to be able to specify a min, max, or range of compute capabilities that a GPU must satisfy to be eligible for allocation.

**Comment by nicksieger** [comment]
Are you maybe looking to propose a change to the [Compose spec](https://github.com/compose-spec/compose-spec/)? Or is there something you want to be able to do that cannot be addressed by using the [environment variables provided by Nvidia](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html)? If you could illustrate with an example that would be helpful.

**Comment by sharvil** [comment]
I'm proposing a change to the compose spec. Here's an example compose file from the [docker compose documentation](https://docs.docker.com/compose/gpu-support/):

```yaml
services:
  test:
    image: nvidia/cuda:10.2-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Suppose I wanted to use 2 GPUs on a machine such that that the selected GPUs have compute capability of at least 8.6. AFAICT there's no way to express that constraint. Here's what I'd like to be able to write:

```yaml
services:
  test:
    image: nvidia/cuda:10.2-base
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu, cuda_compute>=8.6]
```

The NVIDIA environment variables don't seem to have any mechanism to specify the desired compute capability.

I don't feel strongly about *how* the constraint is specified in the compose file. If the `capabilities` list isn't the right place, that's fine -- as long as there *is* a place to declare the constraint.
