### ISSUE TITLE
SHA256 missing from 2.10.0 release

### ISSUE THREAD

**Issue by aminvakil** [docker/compose#9772]
**Description**

I rely on the existence of .sha256 of docker-compose binary for every release on my ansible task.

https://github.com/aminvakil/ansible-role-docker-installation/blob/20b7f6277fc942b47b6cff408c82b04c5f9e9b77/tasks/docker-compose.yml#L4

`https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}.sha256`

And it is not present in 2.10.0 release anymore.

**Steps to reproduce the issue:**
1. Verify https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-Linux-x86_64.sha256 works.
2. Try https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-Linux-x86_64.sha256 and see failure.

**Describe the results you received:**
404

**Describe the results you expected:**
200

**Comment by aminvakil** [comment]
Sorry for bumping this issue with no additional information, but do you want to add checksum to this release or ?

**Comment by laurazard** [comment]
Hi @aminvakil, thanks for the report. In https://github.com/docker/compose/pull/9750 we stopped including the `xxx.sha256` file you're looking for and started including a `checksums.txt` file with all the checksums, available here: https://github.com/docker/compose/releases/download/v2.10.0/checksums.txt

**Comment by venomone** [comment]
How to get this working again in a saltstack way?

```
docker_repository:
  pkgrepo.managed:
   - humanname: Docker
   - name: deb https://download.docker.com/linux/ubuntu focal stable
   - dist: focal
   - file: /etc/apt/sources.list.d/docker.list
   - gpgcheck: 1
   - key_url: https://download.docker.com/linux/ubuntu/gpg
```
