### ISSUE TITLE
slow compose down when using depends_on

### ISSUE THREAD

**Issue by nico525** [docker/compose#9800]
I have a compose file which is pretty complex that utilizes multiple depends_on in combination with service_healthy and service_started conditions.
I now figured out that the stopping of these containers is pretty slow. probably it tires to preserve some order in which the services are shut down.
Is there a way to bypass this and make the shutdown work fast again?
if I run the same compose file without any dependencies, the down command takes about 15 seconds compared to 4+ minutes when using depends_on

**Comment by Lenormju** [comment]
I think it is the expected behavior, cf [Compose specification](https://docs.docker.com/compose/compose-file/#depends_on) :  
> `depends_on` expresses startup and shutdown dependencies between services.
> [...]
> Compose implementations MUST remove services in dependency order.

There is :
`docker compose down --help`  
> -t, --timeout int       Specify a shutdown timeout in seconds (default 10)

Example `docker-compose.yml` :  
```yaml
---
x-service-template: &service-template  # creating a "YAML anchor"
  image: alpine:latest
  command: ['/bin/sh', '-c', 'sleep 999999']

services:
  service1:
    <<: *service-template  # applying the content of the anchor
    depends_on: {}
  service2:
    <<: *service-template
    depends_on: [service1]
  service3:
    <<: *service-template
    depends_on: [service2]
  service4:
    <<: *service-template
    depends_on: [service3]
...
```
```shell
$ docker compose up -d
[+] Running 5/5
 ⠿ Network docker_compose_9800_default       Created                 0.1s
 ⠿ Container docker_compose_9800-service1-1  Started                 0.8s
 ⠿ Container docker_compose_9800-service2-1  Started                 1.2s
 ⠿ Container docker_compose_9800-service3-1  Started                 1.5s
 ⠿ Container docker_compose_9800-service4-1  Started                 1.8s

$ docker compose down
[+] Running 5/5
 ⠿ Container docker_compose_9800-service4-1  Removed                10.4s
 ⠿ Container docker_compose_9800-service3-1  Removed                10.4s
 ⠿ Container docker_compose_9800-service2-1  Removed                10.4s
 ⠿ Container docker_compose_9800-service1-1  Removed                10.5s
 ⠿ Network docker_compose_9800_default       Removed                 0.2s
```
The `down` waited for the default (conservative) timeout for each.

```shell
$ docker compose down --timeout 1
[+] Running 5/5
 ⠿ Container docker_compose_9800-service4-1  Removed                 1.4s
 ⠿ Container docker_compose_9800-service3-1  Removed                 1.4s
 ⠿ Container docker_compose_9800-service2-1  Removed                 1.4s
 ⠿ Container docker_compose_9800-service1-1  Removed                 1.4s
 ⠿ Network docker_compose_9800_default       Removed                 0.2s
```
The containers had much less time to exit before to get killed, which may be a solution to you (if you understand the risk).

Otherwise, you should check how your container's process handles Unix signals.
When you `Ctrl+C`, or `down` after a `up -d`, Compose sends a SIGTERM to the container's process pid=1, and if it has not exited after the default timeout, then sends a SIGKILL (which is handled by the OS so can't be "ignored") which quickly put an end to the process, and thus the container.
So usually, a well-behaved process should exit quickly after receiving a SIGTERM. If yours do not, take care at what `entrypoint`/`cmd` you are using (both in the images' Dockerfile and in the Compose file which can override them). For example, citing the docs about [`docker kill`](https://docs.docker.com/engine/reference/commandline/kill/#description) :  
> `ENTRYPOINT` and `CMD` in the *shell* form run as a child process of `/bin/sh -c`, which does not pass signals. This means that the executable is not the container’s PID 1 and does not receive Unix signals.
