### ISSUE TITLE
Unable to connect to custom bridge networks with manual subnet, "route for the gateway could not be found."

### ISSUE THREAD

**Issue by njalooo** [docker/compose#9833]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Unable to connect to custom created bridge networks, which have a manual subnet. No matter if created from the docker-compose.yml file or manually.**

**Steps to reproduce the issue:**
1. `docker network create --subnet 127.29.0.0/16 --gateway 127.29.0.1 --attachable wgtraefik`
2. docker-compose.yml: 
```
---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest

    container_name: wireguard

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules:ro

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    networks:
      wgtraefik:
        ipv4_address: 127.29.8.7

networks:
  wgtraefik:
    name: wgtraefik
    external: true

```
3. `docker-compose up`

**Describe the results you received:**
```
[+] Running 7/7
 ⠿ wireguard Pulled                                                                                                                  76.4s
   ⠿ ed555500656f Pull complete                                                                                                      24.2s
   ⠿ 1698c149817b Pull complete                                                                                                      24.8s
   ⠿ ef9834f45802 Pull complete                                                                                                      26.8s
   ⠿ 6171437a7e1a Pull complete                                                                                                      26.9s
   ⠿ 01dde983cc72 Pull complete                                                                                                      68.0s
   ⠿ cc06d3be5aa4 Pull complete                                                                                                      68.1s
[+] Running 0/1
 ⠿ Container wireguard  Starting                                                                                                      0.7s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: time="2022-09-12T15:57:21+02:00" level=fatal msg="failed to set gateway while updating gateway: route for the gateway 127.29.0.1 could not be found: invalid argument": unknown
```

**Describe the results you expected:**
Container starting and connecting to network with custom ip.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.9.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.9.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.1-3-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 94.29GiB
 Name: Macpro-Linux-Server
 ID: 6XZG:L2PM:H3A6:BG7Q:XITI:K2KK:TNEL:ZVIL:LEEV:PLV5:THN2:JSTE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
Relevant `ip addr` entry:
```
br-7ec8e3ab540e: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:2c:e7:01:c7 brd ff:ff:ff:ff:ff:ff
    inet 127.29.0.1/16 brd 127.29.255.255 scope global br-7ec8e3ab540e
       valid_lft forever preferred_lft forever
```
