### ISSUE TITLE
Setting container hostname to `service_name-xx` instead of container-id

### ISSUE THREAD

**Issue by sapvs** [docker/compose#9858]
For this sample compose file
```yaml
services:
  my-app:
    image: my-image:0.1

  his-app:
    image: his-image:0.1
```

Compose creates my-app-1 container for my-app with host-name as container-id say `rndmcntrid`

This container is reachable from other services like `his-app-1` with `my-app`, `my-app-1` or `rndmcntrid`.

Can we have compose set container hostname as `service-1`? e.g. in case of my-app above, hostname be set to `my-app-1` instead of `rndmcntrid`
```
Docker Compose version v2.10.2
```

**Comment by s3vt** [comment]
Oops! The description I gave made it look as '**question**: how to set hostname for container' while what wanted was:

Is it possible to enhance compose to set hostname to my-app-1 for containers _without explicit hostname_ configuration in compose file, instead of container-id.


And in case of multiple replicas set as my-app-1, my-app-2 etc. for the replicas.

**Comment by milas** [comment]
Ah, ok, I'll re-open and mark this as a feature request.

Is there a specific reason that the built-in name resolution is inadequate and you want the hostname explicitly set? Trying to understand the use case here.

**Comment by s3vt** [comment]
Thanks @milas. 

Explanation follows, but before that would like to mention that this may be a specific use case, as I have not much idea if there are other systems, that rely on hostname like rabbitmq.

Came across this when trying to cluster rabbitmq using its classic peer discovery, using compose. 

**RabbitMQ configuration**
```
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbit_1  
cluster_formation.classic_config.nodes.2 = rabbit@rabbit_2
```

`rabbit-1`, `rabbit-2` should be hostnames of the rabbit instances. Doesn't work with  alias `app-rabbit-1` or `service name` if hostname is not explicitly set.

**compose file** 
2 services with explicit hostname.
```
# compose project name = app
  rabbit-1:
    image: rabbitmq:management-alpine
    hostname: "rabbit_1"
  rabbit-2:
    image: rabbitmq:management-alpine
    hostname: "rabbit_2"
```

For 2 instances 2 services, for 5 instances 5 service definitions. No benefit of scaling can be taken here.

---

If compose could set hostname `app-rabbit-1`, `app-rabbit-2` etc. then rabbit service could be declared as 

```
# compose project name = app
rabbit:
    image: rabbitmq:management-alpine
    deploy:
      replicas: 3
```

And peer discovery configured as

```
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@app-rabbit-1  
cluster_formation.classic_config.nodes.2 = rabbit@app-rabbit-2
cluster_formation.classic_config.nodes.3 = rabbit@app-rabbit-3

```

We can use `app-rabbit-X` as hostnames in config in this case, because we know compose will set hostname for containers as that.  
Also this opens up option for scaling.

**Comment by milas** [comment]
Awesome, thanks so much for the detailed explanation!

I can't guarantee we will take this feature, but having well-defined use cases helps us prioritize requests.

For anyone else who has reached this issue and is interested, please use the 👍 reaction on the main issue. If you have other use cases not covered, please feel free to comment as well.

**Comment by milas** [comment]
Some possible implementation notes:

As of now, this is what the spec has to say on `hostname`:

> `hostname`
> `hostname` declares a custom host name to use for the service container. MUST be a valid RFC 1123 hostname.

Arguably, this is already underspecified for usage with `replicas`.

At a first glance, I'd say we should he appending the replica # (if > 1) to the custom hostname (if provided) to prevent duplicates.

Then you could set something like `hostname: foo-` to get `foo-1`, `foo-2`, etc.

Any bigger change (e.g. to allow a templating variable, maybe similar to `mktemp`?) would likely necessitate a bigger spec update/change rather than clarification/amendment.

**Comment by s3vt** [comment]
@milas the issue is still closed, could you please re-open it.

**Comment by Tony-Sol** [comment]
Sorry for interrupt, but maybe ability to set a pattern for hostname may solve the problem?
Thats actually a question which i goggled for and found this issue:
 - is there a way to generalize hostname value in templates, e.g.
```yaml
x-templates:
    common: &x-common
        env_file: .env
        hostname: 'my-{{ .Service.Name }}'
        # etc.

services:
    service1:
        <<: *x-common
        # etc.
    service2:
        <<: *x-common
        # etc.
    service3:
        <<: *x-common
        # etc.
```
and get as a result `service1` with `my-service1` hostname, `service2` with `my-service2`, etc. ?

Some kind of "helmy" templating, i would say

**Comment by ndeloof** [comment]
We really, really don't want to introduce a templating language inside the compose file format

**Comment by ndeloof** [comment]
@milas we indeed could compute hostname as container is created with some custom, dedicated logic for this use-case
`Hostname:        strings.Replace(service.Hostname,"XXX", number)`

I wonder which character to use to prevent any side effet, and make it clear a replacement will take place here (as I can guess we will get requests to support this in a few other places)

**Comment by ndeloof** [comment]
I ran a quick test:
```yaml
services:
    base:
        image: nginx
        scale: 2
    master:
        image: alpine
        command: ping localhost
```

ran the stack then exec into my "master" node:
```
docker compose exec master ash
/ # ping chose-base-1
PING chose-base-1 (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: seq=0 ttl=64 time=0.258 ms
64 bytes from 172.18.0.4: seq=1 ttl=64 time=0.425 ms
^C
--- chose-base-1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.258/0.341/0.425 ms
/ # ping chose-base-2
PING chose-base-2 (172.18.0.5): 56 data bytes
64 bytes from 172.18.0.5: seq=0 ttl=64 time=0.573 ms
64 bytes from 172.18.0.5: seq=1 ttl=64 time=0.419 ms
^C
--- chose-base-2 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.419/0.496/0.573 ms
```
service container is registered on network with alias {{project-service-replica}} you can use for service discovery as requested, without any additional configuration or explicit hostname
