### ISSUE TITLE
Not able to read exported variables in docker-compose.yml

### ISSUE THREAD

**Issue by rgsk** [docker/compose#9888]
we have a bash script which exports some variables and runs the docker-compose build command, in docker-compose.yml file we are listing those variables as value of certain keys under environment: and build:args:
eg
environment:
 - ENV_NAME=$EXPORTED_ENV_NAME
 
 but the value of ENV_NAME is passed as “” (empty string)

we didn’t faced this issue in version 4.10, it’s occurring in the latest 4.12 version only

**Comment by rgsk** [comment]
I passed envs in boot script, it started to work. 
I wonder why it was working before, earlier vars were defined only before build and it was working without defining them before boot.

below are scripts 
`build`
```
#!/bin/bash 

export DOCKER_COMPOSE_ENV="local"

export $(cat ./args/$DOCKER_COMPOSE_ENV.env | xargs)
export LOCAL_IP=$(ifconfig en0 | grep 'inet ' | cut -d: -f2 | awk '{print $2}')

docker-compose -f docker-compose.local.yml build
```
earlier
`boot`
```
#!/bin/bash 

# this ensures compose containers are created with underscore rather than dash
export COMPOSE_COMPATIBILITY=true

export DOCKER_COMPOSE_ENV="local"

docker-compose -f docker-compose.local.yml up
```
now 
`boot`
```
#!/bin/bash 

# this ensures compose containers are created with underscore rather than dash
export COMPOSE_COMPATIBILITY=true

export DOCKER_COMPOSE_ENV="local"

export $(cat ./args/$DOCKER_COMPOSE_ENV.env | xargs)
export LOCAL_IP=$(ifconfig en0 | grep 'inet ' | cut -d: -f2 | awk '{print $2}')

docker-compose -f docker-compose.local.yml up

```

docker-compose.yml file
```
version: "3.8"
services:
  webinar-client:
    build:
      context: ./webinar-client
      dockerfile: Dockerfile.local
    depends_on:
      - "webinar-server"
      - "api"
    expose:
      - "5002"
    ports:
      - "5002:5002"
    volumes:
      - ./webinar-client:/opt/www
      - /opt/www/node_modules
    environment:
      - NEXT_PUBLIC_WEBINAR_SERVER=${WEBINAR_CLIENT_APP_WEBINAR_SERVER:?error}
      - NEXT_PUBLIC_CBC_SERVER=$WEBINAR_CLIENT_APP_CBC_SERVER
      - NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN=$WEBINAR_CLIENT_APP_MIXPANEL_PROJECT_TOKEN
      - NEXT_PUBLIC_AIRBRAKE_PROJECT_ID=$WEBINAR_CLIENT_APP_AIRBRAKE_PROJECT_ID
      - NEXT_PUBLIC_AIRBRAKE_PROJECT_KEY=$WEBINAR_CLIENT_APP_AIRBRAKE_PROJECT_KEY
      - NEXT_PUBLIC_APP_ENV=$WEBINAR_CLIENT_APP_ENV
      - NEXT_PUBLIC_LOCAL_IP=$LOCAL_IP
  
  webinar-popup-bundler:
    build:
      context: ./webinar-client
      dockerfile: webinar-popup-bundler/Dockerfile.local
    depends_on:
      - "webinar-server"
      - "api"
    volumes:
      - ./webinar-client:/opt/www
      - /opt/www/webinar-popup-bundler/node_modules
    tty: true
    environment:
      - WEBINAR_SERVER=$WEBINAR_CLIENT_APP_WEBINAR_SERVER
      - CBC_SERVER=$WEBINAR_CLIENT_APP_CBC_SERVER
      - WEBINAR_CLIENT=$WEBINAR_CLIENT_APP_WEBINAR_CLIENT
      - MIXPANEL_PROJECT_TOKEN=$WEBINAR_CLIENT_APP_MIXPANEL_PROJECT_TOKEN
      - APP_ENV=$WEBINAR_CLIENT_APP_ENV
      - LOCAL_IP=$LOCAL_IP
      - NODE_PATH=dist

  webinar-admin:
    build:
      context: ./webinar-admin
      dockerfile: Dockerfile.local
    depends_on:
      - "webinar-server"
      - "api"
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./webinar-admin:/opt/www
      - /opt/www/node_modules
    environment:
      - REACT_APP_SERVER=$WEBINAR_ADMIN_APP_WEBINAR_SERVER
      - REACT_APP_CBC_SERVER=$WEBINAR_ADMIN_APP_CBC_SERVER
      - REACT_APP_CBC_TOKEN="Bearer $WEBINAR_ADMIN_APP_CBC_TOKEN"
```
