### ISSUE TITLE
Unexpected override behavior for networks and volumes

### ISSUE THREAD

**Issue by ericchansen** [docker/compose#9891]
Given this `docker-compose.yml`.

```yml
networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: "192.168.89.0/24"
volumes:
  ramdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1g,uid=1000
```

And this `docker-compose.override.yml`.

```yml
networks:
  default:
    name: named-default
volumes:
  ramdisk:
    name: named-ramdisk
```

I would expect the result of `docker-compose config` to be this.

```yml
networks:
  default:
    driver: bridge
    name: named-default
    ipam:
     config:
       - subnet: "192.168.89.0/24"
services: {}
version: '3.9'
volumes:
  ramdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=1g,uid=1000
    name: named-ramdisk
```

However, the result is this.

```yml
networks:
  default:
    name: named-default
services: {}
version: '3.9'
volumes:
  ramdisk:
    name: named-ramdisk
```
