### ISSUE TITLE
Extended bind mount definitions behave differently than directly defined bind mounts

### ISSUE THREAD

**Issue by darrylkuhn** [docker/compose#9899]
**Description**
For DRY purposes we have a compose file which defines common services and is extended by several other compose files. When a bind mount definition is applied through extension the path is converted; forward slashes (`/`) are converted to backslashes (`\`) and the leading and trailing slashes are omitted. When the path is defined directly on the service the path is not converted. For my part the latter is the desired behavior, but in any case, it seems the result should be consistent regardless of whether or not the volume is defined directly on the service or through extension.

**Steps to reproduce the issue:**
1. Define a base compose file with service having a bind volume containing backslashes. For example:
```yaml
version: "3.4"

services:
  base:
    image: ubuntu:latest
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup
```
2. Define a second compose file with a service extending the first
```yaml
version: "3.4"

services:
  works:
    extends:
      file: docker-compose.base.yml
      service: base
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup

  fails:
    extends:
      file: docker-compose.base.yml
      service: base
```
3. In Windows PowerShell run `docker compose config`
4. Observe the volume output

**Describe the results you received:**
The volume sources are not the same:
```yaml 
services:
  fails:
    extends:
      file: docker-compose.base.yml
      service: base
    image: ubuntu:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: sys\fs\cgroup
      target: /host/sys/fs/cgroup
      bind:
        create_host_path: true
  works:
    extends:
      file: docker-compose.base.yml
      service: base
    image: ubuntu:latest
    networks:
      default: null
    volumes:
    - type: bind
      source: /sys/fs/cgroup/
      target: /host/sys/fs/cgroup
      bind:
        create_host_path: true
networks:
  default:
    name: compose-volume-example_default
```

**Describe the results you expected:**
I expected that the volume sources would be the same (i.e. ` /sys/fs/cgroup/`).

**Additional information you deem important (e.g. issue happens only occasionally):**
This behavior does not happen when running docker compose commands on *nix hosts

**Output of `docker compose version`:**

```
Docker Compose version v2.7.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 62
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.54GiB
 Name: docker-desktop
 ID: TOP6:IDOB:W5SS:DQXN:JUDU:RCE2:SC7V:2QU2:4MBW:Q2QR:MJ7X:PKFU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**
Commands executed in power shell
```
PowerShell Version:
PSVersion                      5.1.22000.832
PSEdition                      Desktop
BuildVersion                   10.0.22000.832
CLRVersion                     4.0.30319.42000

System Info:
CsProcessors                                            : {11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz}
CsSystemType                                            : x64-based PC
OsBuildNumber                                           : 22000
OsCodeSet                                               : 1252
OsHardwareAbstractionLayer                              : 10.0.22000.778
OsName                                                  : Microsoft Windows 11 Pro
OsType                                                  : WINNT
OsVersion                                               : 10.0.22000
```
