### ISSUE TITLE
docker compose config changes the published: <port_number> to published: "<port_number>"

### ISSUE THREAD

**Issue by algo7** [docker/compose#9910]
**Description**
`docker compose config` changes `published: <port_number>` into `published: "<port_number>"` when using the long syntax.

This can cause `docker stack deploy` to fail with `services.something.ports.0.published must be a integer`.

**Note**
I have truncated my `docker-compose.yml` to reduce complexity while making sure that the bug is reducible.

**Steps to reproduce the issue:**
1. Copy the content of the `docker-compose.yml` file from below
2. Run `docker compose config` in the same folder

**The content of `docker-compose.yml`:**
```yml
version: '3.9'
services:
  # Service name
  some_service:
    # Image name
    image: some_image:latest
    ports:
      # Port in the container
      - target: 3000
        # Port used by the routing mesh
        published: 3000
        protocol: tcp
    # Set up a dedicated network
    networks:
      - some_network

## Config section
# Define the network type
networks:
  some_network:
    external: true
```

**Describe the results you received:**
```yml
name: folder_name_that_contains_the_compose_file
services:
  some_service:
    image: some_image:latest
    networks:
      some_network: null
    ports:
    - target: 3000
      published: "3000"
      protocol: tcp
networks:
  some_network:
    name: some_network
    external: true
```
**Describe the results you expected:**
```yml
name: folder_name_that_contains_the_compose_file
services:
  some_service:
    image: some_image:latest
    networks:
      some_network: null
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
networks:
  some_network:
    name: some_network
    external: true
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.10.2
```

**Output of `docker info`:**
```yml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.10.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-48-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.71GiB
 Name: <redacted>
 ID: 6URP:I3AZ:OFLE:B4RA:2PMA:BZBZ:GESD:JDY6:UHS6:5WDE:B5XT:QPMP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
```
OS Information:
Version:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
