### ISSUE TITLE
[BUG] Container starts before one of it's volumes (exposed by other container) is available

### ISSUE THREAD

**Issue by Dmitry1987** [docker/compose#9923]
### Description

We've observed an unexpected behavior where a volume exposed by one container "A" (from its folder content) for another container "B", does not prevent the container "B" from starting before "A" is available, so we get error about "files missing" because the volume is not yet ready (as it looks), but in all subsequent restarts of container "B" the error is not reproduced (because "A" already online and its folder exposed as volume is reachable). It seems like a bug because if there's a dependency on a volume existence, most use cases will get errors and crashes if that volume cannot be accessed or doesn't exist 🤔 

### Steps To Reproduce

```
version: '3'
services:
  containerA:
    image: {{docker_repo}}/serviceA:{{image_tag}}
    container_name: serviceA
    restart: unless-stopped
    # This volume exposes folder for usage by other container
    volumes:
      - mydata:/opt/some/files/mydata

  containerB:
    image: {{docker_repo}}/backend:{{image_tag}}
    command: ["./backend"]
    container_name: backend
    restart: unless-stopped
    volumes:
      - /something:/something
      - mydata:/opt/mydata

volumes:
  mydata:
```

### Compose Version

```Text
docker-compose version 1.29.2, build 5becea4c
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 600
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-1020-aws
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.892GiB
 Name: development.website.local
 ID: XYOE:PD7D:L5RO:NJJZ:Q5RQ:3PEM:RSYF:HQCI:7HRK:Y2BV:W2VX:63UP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
```

### Anything else?

and error says 'file doesn't exist' about files in the "mydata" folder, in containerB, when compose just starts, it repeats itself quickly a few times and then finally finds the files (probably because containerA finally initializes it). 
we did fix it of course with a simple `depends_on` but I decided report the bug because I think compose should implicitly make use of the 'depends_on' functionality in a case when volume is defined like this.

**Comment by nosnilmot** [comment]
How is compose supposed to know that `containerB` is depending on `containerA` to populate `mydata` and not the other way around?
The volume is not "exposed by containerA". The volume is defined externally to any containers and mounted by both `containerA` and `containerB`.
`depends_on` is exactly what you need to use here to declare the dependency

**Comment by laurazard** [comment]
@nosnilmot is right! This can be addressed by adding a `depends_on` condition to `containerA`. There's a few ways to configure that, depending on the behavior of `containerB`. A common way to do that would be to have `containerB` exit after populating the volume, and if that happens you can configure `containerA` such as:

```yaml
...
containerB:
    depends_on:
        containerA:
            condition: service_completed_successfully
...
```
