### ISSUE TITLE
[BUG] Volumes: Creates directory instead of file (type: bind argument doesnt work?)

### ISSUE THREAD

**Issue by Gandalf1783** [docker/compose#9955]
### Description

When using the long notation for a volume, e.g. the type option etc., the mount that is created on the host system is a folder, not a directory.

### Steps To Reproduce

1. Use the docker-compose.yml:

```
version: '3.2'
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/dynamic.yaml"
    ports:
      # The HTTP port
      - "8080:80"
      # The Web UI (enabled by --api.insecure=true)
      - "1800:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /root/traefik/dynamic.yaml
        target: /dynamic.yaml
```
2. Start Docker via "docker-compose up -d reverse-proxy"
3. Observe via ls -la that it has created a directory, not a file.:
```
root@ba-traefik:~/traefik# ls -la
insgesamt 16
drwxr-xr-x 3 root root 4096 26. Okt 13:11 .
drwx------ 4 root root 4096 25. Okt 18:11 ..
-rw-r--r-- 1 root root  670 26. Okt 13:06 docker-compose.yml
drwxr-xr-x 2 root root 4096 26. Okt 13:05 dynamic.yaml
```

### Compose Version

```Text
root@ba-traefik:~/traefik# docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'



root@ba-traefik:~/traefik# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```

### Docker Environment

```Text
root@ba-traefik:~/traefik# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.4.13~ds1-1~deb11u2
 runc version: 1.0.0~rc93+ds1-5+deb11u2
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 3.838GiB
 Name: ba-traefik
 ID: W5UL:2KXP:JZB3:R5W2:2LUR:U2NU:EUDG:KJZ7:X2VO:PYGS:UNBI:XKB7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Support for cgroup v2 is experimental
```

### Anything else?

If a file called dynamic.yaml already exists, during restart/up this happens:

```
root@ba-traefik:~/traefik# docker-compose restart reverse-proxy
Restarting traefik_reverse-proxy_1 ... error

ERROR: for traefik_reverse-proxy_1  Cannot restart container c39d826577acd88a344a916be9ea47df6fca60252b1b9584a97197c184901598: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "/root/traefik/dynamic.yaml" to rootfs at "/dynamic.yaml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

If I recall correctly, the type: bind option is used for mounting things like config files. It was even mentioned that docker uses it to mount the resolv.conf into containers. It doesnt seem to work though?

In a different issue, i saw that it must have version 3.2 at least for the long sytax to work.

Additional Info:
  OS: Debian Bullseye, 64 Bit
  This is on a VM, though I dont suspect that will change said behaviour.

**Comment by Gandalf1783** [comment]
Update: It looks like the target is the issue.
If the target is located in root (e.g. /dynamic.yaml) it is considered a folder.
If the target is located in a subfolder (e.g. /etc/dynamic.yaml) it is considered a file.

I just changed the path to include /etc and it seems to work now.

**Comment by ndeloof** [comment]
I ran this test trying to reproduce this issue:
compose.yaml
```yaml
services:
  test:
    image: alpine
    command: ls -al /test
    volumes:
      - type: bind
        source: ./foo # a random local file
        target: /test
```

```
$ docker compose up
[+] Running 1/0
 ⠿ Container truc-test-1  Created                                                                                      0.1s
Attaching to truc-test-1
truc-test-1  | -rw-r--r--    1 root     root           115 Dec 13 17:30 /test
truc-test-1 exited with code 0
```

So, it seems this issue is fixed by Compose v2. Also, compose v1 being EoL in a few months, you should consider upgrading.

**Comment by HeosSacer** [comment]
@ndeloof I have the same issue mounting a single file, but with v2.14.2 running via wsl.
It will create a directory on docker-compose up with the name `elasticsearch.yml` instead of mounting the file.

It will omit this error message:
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-22.04/d1b4804669b388f420b1f3df0ac3f5fe8017220f34f8fe851ce99e10b0263b73" to rootfs at "/usr/share/elasticsearch/config/elasticsearch.yml": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu-22.04/d1b4804669b388f420b1f3df0ac3f5fe8017220f34f8fe851ce99e10b0263b73:/usr/share/elasticsearch/config/elasticsearch.yml (via /proc/self/fd/14), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

## compose file
```yaml
version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:9200/_cat/health"
        ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200
```

## Docker Env
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.14.2)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 9
 Server Version: 22.06.0-beta.0-902-g2708be0db4.m
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.79.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.49GiB
 Name: docker-desktop
 ID: 2e9a45af-d718-4281-af84-ecaca22434c2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```
