### ISSUE TITLE
read-only volumes_from entries got confused as service names when trying to bring up a subset of services

### ISSUE THREAD

**Issue by dvusboy** [docker/compose#9966]
### Description

I have this `compose.yaml` file (with some content modified):

```yaml
networks:
  mynet:
    name: mynet

volumes:
  node_modules:
    name: node_modules

services:
  somecfg:
    image: cfg:v1

  apiserver:
    image: node:16.17.0-alpine3.16
    container_name: apiserver
    networks:
      - mynet
    ports:
      - 8080:8080
      - 8081:8081
    extra_hosts:
      - "dev@:127.0.0.1"
    environment:
      NODE_ENV: production
      AWS_CONFIG_FILE: /app/config/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /app/config/.aws/credentials
      AWS_SDK_LOAD_CONFIG: 1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: /app/dev-entrypoint.sh
    command: [ "node", "server.js" ]

  apiserver2:
    image: node:16.17.0-alpine3.16
    container_name: apiserver2
    profiles:
      - dev-two-node
    networks:
      - mynet
    ports:
      - 8180:8080
      - 8181:8081
    extra_hosts:
      - "dev:127.0.0.1"
    environment:
      NODE_ENV: production
      AWS_CONFIG_FILE: /app/config/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /app/config/.aws/credentials
      AWS_SDK_LOAD_CONFIG: 1
    volumes:
      - .:/app
      - ./log2:/app/log
      - node_modules:/app/node_modules
    entrypoint: /app/dev-entrypoint.sh
    command: [ "node", "server.js" ]

  cli:
    image: node:16.17.0-alpine3.16
    container_name: cli
    profiles:
      - dev-two-node
    networks:
      - mynet
    environment:
      NODE_ENV: production
      AWS_CONFIG_FILE: /app/config/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /app/config/.aws/credentials
      AWS_SDK_LOAD_CONFIG: 1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: /app/dev-entrypoint.sh
    command: [ "tail", "-f", "/dev/null" ]

  taskserver:
    image: node:16.17.0-alpine3.16
    container_name: taskserver
    networks:
      - mynet
    extra_hosts:
      - "dev:127.0.0.1"
    environment:
      NODE_ENV: production
      AWS_CONFIG_FILE: /app/config/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /app/config/.aws/credentials
      AWS_SDK_LOAD_CONFIG: 1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: /app/dev-entrypoint.sh
    command: [ "node", "server/taskserver.js" ]

  bcwriter:
    image: alpine3.16
    container_name: bcwriter
    networks:
      - mynet
    extra_hosts:
      - "dev:127.0.0.1"
    environment:
      AWS_CONFIG_FILE: /app/config/.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /app/config/.aws/credentials
      AWS_SDK_LOAD_CONFIG: 1
    volumes:
      - .:/app
    volumes_from:
      - somecfg:ro
    entrypoint: /app/dev-bcwriter-entrypoint.sh
    command: [ "node", "bcwriter.js" ]
```

And instead of running all the services, I wanted to start just `bcwriter`, and since it also depends on `somecfg`, I run the following:

```
% docker compose up -d somecfg bcwriter
no such service: somecfg:ro
```

It looks like `docker compose` is treating the `volumes_from` entry `somecfg:ro` as a service name, which is clearly wrong.

### Steps To Reproduce

I started with creating a volume-container image with this Dockerfile:

```Dockerfile
FROM dvusboy/tiny-scratch

VOLUME /vol
COPY ipsum.txt /vol/
```

And then use this `compose.yaml` file:

```YAML
services:
  ipsum:
    image: dvusboy/volume-container-example

  echo:
    image: alpine:3.16
    volumes_from:
      - ipsum:ro
    command:
      - cat
      - /vol/ipsum.txt

  sleep:
    image: alpine:3.16
    command: sleep 86400
```

Then I run the following command:

```
kcwong@KCMBProTouch bugreport % docker compose up -d ipsum echo
no such service: ipsum:ro
```

Normal `docker compose up -d` works just fine, by the way.

### Compose Version

```
kcwong@KCMBProTouch bugreport % docker compose version
Docker Compose version v2.2.3
```

### Docker Environment

```
kcwong@KCMBProTouch bugreport % docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 58
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: 4VNH:ZQXI:BNAI:FHT2:DACF:DEM6:RVZS:JFEQ:BICQ:KCGE:6XRY:BDH3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

That is.
