### ISSUE TITLE
[BUG] --no-interpolate broken for volumes path

### ISSUE THREAD

**Issue by lostcontrol** [docker/compose#9970]
### Description

`docker-compose config/convert --no-interpolate` is broken in releases > 2.0.1 when substitution occurs in volumes path definition. The issue is better seen in the example below:

```bash
jac@L-0267 /t/compose (v2)> cat .env
TEST_DIR="/my_test_dir"
```
```yaml
jac@L-0267 /t/compose (v2)> cat docker-compose.yml 
version: "3.7"
services:
  test:
    image: ubuntu:22.04
    volumes:
      - type: bind
        source: ${TEST_DIR}
        target: /data
```
```bash
jac@L-0267 /t/compose (v2)> docker-compose --version
Docker Compose version v2.12.2
```
```yaml
jac@L-0267 /t/compose (v2)> docker-compose -f docker-compose.yml config
name: compose
services:
  test:
    image: ubuntu:22.04
    networks:
      default: null
    volumes:
    - type: bind
      source: /my_test_dir
      target: /data
networks:
  default:
    name: compose_default
```
```yaml
jac@L-0267 /t/compose (v2)> docker-compose -f docker-compose.yml config --no-interpolate
name: compose
services:
  test:
    image: ubuntu:22.04
    networks:
      default: null
    volumes:
    - type: bind
      source: /tmp/compose/${TEST_DIR}
      target: /data
networks:
  default:
    name: compose_default
```
The expected output when using `--no-interpolate` in this case would be:

```yaml
name: compose
services:
  test:
    image: ubuntu:22.04
    networks:
      default: null
    volumes:
    - type: bind
      source: ${TEST_DIR}
      target: /data
networks:
  default:
    name: compose_default
```
This is how it was until v2.0.1. From v2.1.0 and up to the last release (v2.12.2 as of now), the path to the current context (here `/tmp/compose`) is wrongly added at the front of the variable. Somehow, docker-compose thinks that `${TEST_DIR}` is a relative path and decides to include the current context in front of it.

### Steps To Reproduce

* Install the latest docker-compose version
* Create `.env` and `docker-compose.yml` as above
* Run the above commands

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1)

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 31
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-52-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.8GiB
 Name: L-0267.company.asyril.com
 ID: Y5N4:LUP5:KSOJ:BCZ2:3464:MYT7:5KRX:BN5R:JQE3:PH3P:42XD:MH5X
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

This was broken somewhere between v2.0.1 and v2.1.0.
