### ISSUE TITLE
Improve error message: failed to mount local volume, no such file or directory

### ISSUE THREAD

**Issue by KES777** [docker/compose#9971]
### Description

```
Error response from daemon: error while mounting volume '/var/lib/docker/volumes/pgdb_pgdb-data/_data': failed to mount local volume: mount .//db:/var/lib/docker/volumes/pgdb_pgdb-data/_data, flags: 0x1000: no such file or directory
```

Would be nice if `docker compose` report that bind requires absolute path.

```
volumes:
  pgdb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db'
```

Related to https://github.com/docker/compose/issues/9191
