### ISSUE TITLE
[BUG] docker compose push hangs after upload

### ISSUE THREAD

**Issue by KarstenB** [docker/compose#9972]
### Description

In our CI we have a mechanism which terminates processes that don't cause any output for 10 minutes. That is very effective in avoid burning resources on hanging processes. In the past few runs we observed quite a few of the following:

```
2022-11-01T12:28:30.5699011Z ##[debug]Docker: Pushing zeromqtol2 072ab9a5f58f Pushing [=================================================> ]  519.1MB/519.5MB
2022-11-01T12:28:30.6915335Z ##[debug]Docker: Pushing zeromqtol2 072ab9a5f58f Pushing [==================================================>]  520.7MB
2022-11-01T12:28:30.8171289Z ##[debug]Docker: Pushing zeromqtol2 072ab9a5f58f Pushing [==================================================>]  522.9MB
2022-11-01T12:28:30.8735931Z ##[debug]Docker: Pushing zeromqtol2 072ab9a5f58f Pushing [==================================================>]  523.9MB
2022-11-01T12:28:33.9094192Z ##[debug]Docker: Pushing zeromqtol2 072ab9a5f58f Pushed
... Termination system detected no output to console for 10 minutes and terminates all children, printing their command line:
2022-11-01T12:38:34.3431306Z ##[warning]Terminating child: sh ['/bin/sh', '-c', 'docker compose -f zmqtools/docker-compose.build.yml push']
2022-11-01T12:38:34.3436142Z ##[warning]Terminating child: docker ['docker', 'compose', '-f', 'zmqtools/docker-compose.build.yml', 'push']
2022-11-01T12:38:34.3440402Z ##[warning]Terminating child: docker-compose ['/usr/libexec/docker/cli-plugins/docker-compose', 'compose', '-f', 'zmqtools/docker-compose.build.yml', 'push']
```

### Steps To Reproduce

Our CI agents are running as docker compose as well:
```
version: '2.4'
services:
//7 more times the following, but with different cpusets
  docker7:
    command:
    - dockerd
    - --dns
    - 172.17.0.1
    cpuset: 56-63,64-95
    dns: 172.17.0.1
    environment:
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      HTTP_PROXY: ${HTTP_PROXY:-}
      http_proxy: ${HTTP_PROXY:-}
      https_proxy: ${HTTPS_PROXY:-}
      no_proxy: ${no_proxy:-}
    image: docker:dind
    network_mode: bridge
    privileged: true
    restart: on-failure
    volumes:
    - docker7_socket:/var/run
    - docker7_data:/azp/_work
    - docker7_cache:/var/lib/docker
  agent7:
    cpuset: 56-63
    depends_on:
    - docker7
    environment:
      AZP_AGENT_NAME: agent7
      AZP_POOL: ${AZP_POOL}
      AZP_TOKEN: ${AZP_TOKEN}
      AZP_URL: ${AZP_URL}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      HTTP_PROXY: ${HTTP_PROXY:-}
      http_proxy: ${HTTP_PROXY:-}
      https_proxy: ${HTTPS_PROXY:-}
      no_proxy: ${no_proxy:-}
    image: azure_devops_agent:latest
    network_mode: bridge
    restart: on-failure
    volumes:
    - docker7_socket:/var/run/
    - docker7_data:/azp/_work
volumes:
//...
  docker7_cache:
  docker7_data:
```

As you can see we are running a cpu pinned `dind` to have 8 agents running simultaneously on a 96 core machine, without each stealing their cpu time. Unfortunately we also have to use a HTTP_PROXY which may contribute to the issue we are facing. I also ran into DNS lookup issues, which I mitigated by using `network_mode: bridge` and using DNSMasq on docker0 interface. Except for this freak upload event, everything is working pretty well.

### Compose Version

```Text
Docker Compose version v2.12.2
docker-compose version
-bash: docker-compose: command not found
```

### Docker Environment

```Text
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 16
  Running: 16
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: x6kgdbshxbg77iiitxyqasff1
  Is Manager: true
  ClusterID: lso6f8vhbunwh489jyhfhw421
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.19.9.146
  Manager Addresses:
   172.19.9.146:2377
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-15-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 96
 Total Memory: 502.5GiB
 Name: cpc07build1
 ID: WRZO:UXNO:U47Z:SVPG:XUII:XFTM:WLBJ:IYIF:N2YI:473S:AJ4S:UEAZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 157
  Goroutines: 322
  System Time: 2022-11-04T09:04:03.219407267+01:00
  EventsListeners: 1
 HTTP Proxy: http://proxy:3128
 HTTPS Proxy: http://proxy:3128
 No Proxy: localhost,127.0.0.1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

We are uploading to a JFrog registry.
